export interface ABTestingTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const abTestingToolsList: ABTestingTool[] = [
  // --- 🔥 PRIORITY 20 FREE TOOLS (IDs 1-20 | isPro: false) ---
  { id: 1, name: "A/B Test Calculator", slug: "ab-test-calculator", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 2, name: "Test Duration Calculator", slug: "test-duration-calculator", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 3, name: "Experiment Sample Size Planner", slug: "experiment-sample-size-planner", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 4, name: "Minimum Detectable Effect Calculator", slug: "minimum-detectable-effect-calculator", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 5, name: "Statistical Significance Checker", slug: "statistical-significance-checker", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 6, name: "Experiment Confidence Calculator", slug: "experiment-confidence-calculator", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 7, name: "Conversion Lift Calculator", slug: "conversion-lift-calculator", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 8, name: "Variant Performance Calculator", slug: "variant-performance-calculator", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 9, name: "Experiment Winner Calculator", slug: "experiment-winner-calculator", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 10, name: "Test Power Calculator", slug: "test-power-calculator", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 11, name: "Experiment Traffic Split Calculator", slug: "experiment-traffic-split-calculator", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 12, name: "Control vs Variant Calculator", slug: "control-vs-variant-calculator", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 13, name: "Experiment Uplift Calculator", slug: "experiment-uplift-calculator", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 14, name: "Experiment ROI Calculator", slug: "experiment-roi-calculator", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 15, name: "Test Prioritization Matrix", slug: "test-prioritization-matrix", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 16, name: "Sample Ratio Checker", slug: "sample-ratio-checker", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 17, name: "Experiment Hypothesis Builder", slug: "experiment-hypothesis-builder", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 18, name: "Test Plan Generator", slug: "test-plan-generator", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 19, name: "Experiment Metric Dictionary", slug: "experiment-metric-dictionary", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 20, name: "Experiment Guardrail Checker", slug: "experiment-guardrail-checker", category: "A/B Testing & Experimentation Tools", isPro: false },

  // --- REMAINING 40 CORE FREE TOOLS (IDs 21-60 | isPro: false) ---
  { id: 21, name: "Relative Lift Calculator", slug: "relative-lift-calculator", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 22, name: "Absolute Lift Calculator", slug: "absolute-lift-calculator", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 23, name: "Experiment Baseline Calculator", slug: "experiment-baseline-calculator", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 24, name: "Conversion Difference Calculator", slug: "conversion-difference-calculator", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 25, name: "Experiment Revenue Impact Calculator", slug: "experiment-revenue-impact-calculator", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 26, name: "Test Stopping Calculator", slug: "test-stopping-calculator", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 27, name: "Sequential Test Planner", slug: "sequential-test-planner", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 28, name: "Multi-Variant Test Planner", slug: "multi-variant-test-planner", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 29, name: "Factorial Experiment Planner", slug: "factorial-experiment-planner", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 30, name: "Holdout Group Calculator", slug: "holdout-group-calculator", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 31, name: "Experiment Objective Builder", slug: "experiment-objective-builder", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 32, name: "Experiment Brief Generator", slug: "experiment-brief-generator", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 33, name: "Experiment Naming Generator", slug: "experiment-naming-generator", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 34, name: "Variant Naming Generator", slug: "variant-naming-generator", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 35, name: "Experiment Checklist", slug: "experiment-checklist", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 36, name: "Experiment QA Checklist", slug: "experiment-qa-checklist", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 37, name: "Experiment Launch Checklist", slug: "experiment-launch-checklist", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 38, name: "Experiment Analysis Template", slug: "experiment-analysis-template", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 39, name: "Experiment Results Template", slug: "experiment-results-template", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 40, name: "Experiment Documentation Generator", slug: "experiment-documentation-generator", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 41, name: "Experiment Archive Organizer", slug: "experiment-archive-organizer", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 42, name: "Experiment Calendar", slug: "experiment-calendar", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 43, name: "Experiment Backlog", slug: "experiment-backlog", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 44, name: "Experiment Scoring Matrix", slug: "experiment-scoring-matrix", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 45, name: "Test Opportunity Matrix", slug: "test-opportunity-matrix", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 46, name: "Experiment Idea Generator", slug: "experiment-idea-generator", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 47, name: "Conversion Experiment Ideas", slug: "conversion-experiment-ideas", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 48, name: "Pricing Experiment Planner", slug: "pricing-experiment-planner", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 49, name: "Landing Page Experiment Planner", slug: "landing-page-experiment-planner", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 50, name: "Product Experiment Planner", slug: "product-experiment-planner", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 51, name: "Email Experiment Planner", slug: "email-experiment-planner", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 52, name: "Feature Experiment Planner", slug: "feature-experiment-planner", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 53, name: "UX Experiment Planner", slug: "ux-experiment-planner", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 54, name: "Mobile Experiment Planner", slug: "mobile-experiment-planner", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 55, name: "Checkout Experiment Planner", slug: "checkout-experiment-planner", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 56, name: "Experiment Report Generator", slug: "experiment-report-generator", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 57, name: "Experiment Summary Generator", slug: "experiment-summary-generator", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 58, name: "Experiment Decision Log", slug: "experiment-decision-log", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 59, name: "Experiment Learning Log", slug: "experiment-learning-log", category: "A/B Testing & Experimentation Tools", isPro: false },
  { id: 60, name: "Experiment KPI Tracker", slug: "experiment-kpi-tracker", category: "A/B Testing & Experimentation Tools", isPro: false },

  // --- ⚡ 40 PRO / SAAS TOOLS (IDs 61-100 | isPro: true) ---
  { id: 61, name: "Experimentation Workspace", slug: "experimentation-workspace", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 62, name: "Experiment Portfolio Dashboard", slug: "experiment-portfolio-dashboard", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 63, name: "A/B Testing Command Center", slug: "ab-testing-command-center", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 64, name: "Experiment Lifecycle Manager", slug: "experiment-lifecycle-manager", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 65, name: "Experiment Backlog Workspace", slug: "experiment-backlog-workspace", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 66, name: "Experiment Prioritization Engine", slug: "experiment-prioritization-engine", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 67, name: "Experiment Planning Workspace", slug: "experiment-planning-workspace", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 68, name: "Statistical Experiment Engine", slug: "statistical-experiment-engine", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 69, name: "Multi-Variant Testing Workspace", slug: "multi-variant-testing-workspace", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 70, name: "Factorial Testing Workspace", slug: "factorial-testing-workspace", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 71, name: "Sequential Testing Workspace", slug: "sequential-testing-workspace", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 72, name: "Experiment Monitoring Dashboard", slug: "experiment-monitoring-dashboard", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 73, name: "Experiment Guardrail Dashboard", slug: "experiment-guardrail-dashboard", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 74, name: "Experiment Results Intelligence", slug: "experiment-results-intelligence", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 75, name: "Experiment Revenue Impact Dashboard", slug: "experiment-revenue-impact-dashboard", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 76, name: "Experiment Learning Repository", slug: "experiment-learning-repository", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 77, name: "Experiment Knowledge Base", slug: "experiment-knowledge-base", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 78, name: "Experiment Documentation Hub", slug: "experiment-documentation-hub", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 79, name: "Experiment QA Workspace", slug: "experiment-qa-workspace", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 80, name: "Experiment Launch Management", slug: "experiment-launch-management", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 81, name: "Experiment Rollout Manager", slug: "experiment-rollout-manager", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 82, name: "Experiment Holdout Manager", slug: "experiment-holdout-manager", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 83, name: "Experiment Segmentation Workspace", slug: "experiment-segmentation-workspace", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 84, name: "Experiment Cohort Workspace", slug: "experiment-cohort-workspace", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 85, name: "Experiment Metrics Dashboard", slug: "experiment-metrics-dashboard", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 86, name: "Experiment Analytics API", slug: "experiment-analytics-api", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 87, name: "Experiment Data Importer", slug: "experiment-data-importer", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 88, name: "Experiment Data Exporter", slug: "experiment-data-exporter", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 89, name: "Experiment Reporting Engine", slug: "experiment-reporting-engine", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 90, name: "Experiment Automation Workspace", slug: "experiment-automation-workspace", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 91, name: "Product Experiment Platform", slug: "product-experiment-platform", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 92, name: "Growth Experiment Platform", slug: "growth-experiment-platform", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 93, name: "Conversion Experiment Platform", slug: "conversion-experiment-platform", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 94, name: "Pricing Experiment Platform", slug: "pricing-experiment-platform", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 95, name: "UX Experiment Platform", slug: "ux-experiment-platform", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 96, name: "Enterprise Experiment Management", slug: "enterprise-experiment-management", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 97, name: "Experiment Governance Workspace", slug: "experiment-governance-workspace", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 98, name: "Experiment Intelligence Platform", slug: "experiment-intelligence-platform", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 99, name: "Continuous Experimentation Platform", slug: "continuous-experimentation-platform", category: "A/B Testing & Experimentation Tools", isPro: true },
  { id: 100, name: "Enterprise Experiment Command Center", slug: "enterprise-experiment-command-center", category: "A/B Testing & Experimentation Tools", isPro: true }
];