export interface AITool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const aiToolsList: AITool[] = [
  // --- CORE / HIGH-DEMAND (FREE TOOLS: 1-60) ---
  { id: 1, name: "AI Chat Assistant", slug: "ai-chat-assistant", category: "AI Tools", isPro: false },
  { id: 2, name: "AI Text Generator", slug: "ai-text-generator", category: "AI Tools", isPro: false },
  { id: 3, name: "AI Content Writer", slug: "ai-content-writer", category: "AI Tools", isPro: false },
  { id: 4, name: "AI Blog Post Generator", slug: "ai-blog-post-generator", category: "AI Tools", isPro: false },
  { id: 5, name: "AI Article Rewriter", slug: "ai-article-rewriter", category: "AI Tools", isPro: false },
  { id: 6, name: "AI Summarizer", slug: "ai-summarizer", category: "AI Tools", isPro: false },
  { id: 7, name: "AI Paragraph Generator", slug: "ai-paragraph-generator", category: "AI Tools", isPro: false },
  { id: 8, name: "AI Sentence Generator", slug: "ai-sentence-generator", category: "AI Tools", isPro: false },
  { id: 9, name: "AI Headline Generator", slug: "ai-headline-generator", category: "AI Tools", isPro: false },
  { id: 10, name: "AI Title Generator", slug: "ai-title-generator", category: "AI Tools", isPro: false },
  { id: 11, name: "AI Hook Generator", slug: "ai-hook-generator", category: "AI Tools", isPro: false },
  { id: 12, name: "AI Outline Generator", slug: "ai-outline-generator", category: "AI Tools", isPro: false },
  { id: 13, name: "AI Story Generator", slug: "ai-story-generator", category: "AI Tools", isPro: false },
  { id: 14, name: "AI Essay Generator", slug: "ai-essay-generator", category: "AI Tools", isPro: false },
  { id: 15, name: "AI Email Writer", slug: "ai-email-writer", category: "AI Tools", isPro: false },
  { id: 16, name: "AI Reply Generator", slug: "ai-reply-generator", category: "AI Tools", isPro: false },
  { id: 17, name: "AI Social Post Generator", slug: "ai-social-post-generator", category: "AI Tools", isPro: false },
  { id: 18, name: "AI Caption Generator", slug: "ai-caption-generator", category: "AI Tools", isPro: false },
  { id: 19, name: "AI Ad Copy Generator", slug: "ai-ad-copy-generator", category: "AI Tools", isPro: false },
  { id: 20, name: "AI Product Description Generator", slug: "ai-product-description-generator", category: "AI Tools", isPro: false },
  { id: 21, name: "AI Meta Description Generator", slug: "ai-meta-description-generator", category: "AI Tools", isPro: false },
  { id: 22, name: "AI FAQ Generator", slug: "ai-faq-generator", category: "AI Tools", isPro: false },
  { id: 23, name: "AI Review Generator", slug: "ai-review-generator", category: "AI Tools", isPro: false },
  { id: 24, name: "AI Bio Generator", slug: "ai-bio-generator", category: "AI Tools", isPro: false },
  { id: 25, name: "AI Mission Statement Generator", slug: "ai-mission-statement-generator", category: "AI Tools", isPro: false },
  { id: 26, name: "AI Business Name Generator", slug: "ai-business-name-generator", category: "AI Tools", isPro: false },
  { id: 27, name: "AI Slogan Generator", slug: "ai-slogan-generator", category: "AI Tools", isPro: false },
  { id: 28, name: "AI Tagline Generator", slug: "ai-tagline-generator", category: "AI Tools", isPro: false },
  { id: 29, name: "AI Script Generator", slug: "ai-script-generator", category: "AI Tools", isPro: false },
  { id: 30, name: "AI YouTube Script Generator", slug: "ai-youtube-script-generator", category: "AI Tools", isPro: false },
  { id: 31, name: "AI Video Idea Generator", slug: "ai-video-idea-generator", category: "AI Tools", isPro: false },
  { id: 32, name: "AI Content Idea Generator", slug: "ai-content-idea-generator", category: "AI Tools", isPro: false },
  { id: 33, name: "AI Brainstorming Tool", slug: "ai-brainstorming-tool", category: "AI Tools", isPro: false },
  { id: 34, name: "AI Rewriter", slug: "ai-rewriter", category: "AI Tools", isPro: false },
  { id: 35, name: "AI Paraphraser", slug: "ai-paraphraser", category: "AI Tools", isPro: false },
  { id: 36, name: "AI Expander", slug: "ai-expander", category: "AI Tools", isPro: false },
  { id: 37, name: "AI Text Shortener", slug: "ai-text-shortener", category: "AI Tools", isPro: false },
  { id: 38, name: "AI Tone Changer", slug: "ai-tone-changer", category: "AI Tools", isPro: false },
  { id: 39, name: "AI Formalizer", slug: "ai-formalizer", category: "AI Tools", isPro: false },
  { id: 40, name: "AI Simplifier", slug: "ai-simplifier", category: "AI Tools", isPro: false },
  { id: 41, name: "AI Grammar Improver", slug: "ai-grammar-improver", category: "AI Tools", isPro: false },
  { id: 42, name: "AI Proofreader", slug: "ai-proofreader", category: "AI Tools", isPro: false },
  { id: 43, name: "AI Fact-Checking Assistant", slug: "ai-fact-checking-assistant", category: "AI Tools", isPro: false },
  { id: 44, name: "AI Translator", slug: "ai-translator", category: "AI Tools", isPro: false },
  { id: 45, name: "AI Language Detector", slug: "ai-language-detector", category: "AI Tools", isPro: false },
  { id: 46, name: "AI Keyword Generator", slug: "ai-keyword-generator", category: "AI Tools", isPro: false },
  { id: 47, name: "AI SEO Content Generator", slug: "ai-seo-content-generator", category: "AI Tools", isPro: false },
  { id: 48, name: "AI Schema Generator", slug: "ai-schema-generator", category: "AI Tools", isPro: false },
  { id: 49, name: "AI Alt Text Generator", slug: "ai-alt-text-generator", category: "AI Tools", isPro: false },
  { id: 50, name: "AI Image Prompt Generator", slug: "ai-image-prompt-generator", category: "AI Tools", isPro: false },
  { id: 51, name: "AI Video Prompt Generator", slug: "ai-video-prompt-generator", category: "AI Tools", isPro: false },
  { id: 52, name: "AI Voice Script Generator", slug: "ai-voice-script-generator", category: "AI Tools", isPro: false },
  { id: 53, name: "AI Resume Writer", slug: "ai-resume-writer", category: "AI Tools", isPro: false },
  { id: 54, name: "AI Cover Letter Writer", slug: "ai-cover-letter-writer", category: "AI Tools", isPro: false },
  { id: 55, name: "AI Job Description Generator", slug: "ai-job-description-generator", category: "AI Tools", isPro: false },
  { id: 56, name: "AI Interview Question Generator", slug: "ai-interview-question-generator", category: "AI Tools", isPro: false },
  { id: 57, name: "AI Meeting Summary Generator", slug: "ai-meeting-summary-generator", category: "AI Tools", isPro: false },
  { id: 58, name: "AI Action Item Generator", slug: "ai-action-item-generator", category: "AI Tools", isPro: false },
  { id: 59, name: "AI Presentation Generator", slug: "ai-presentation-generator", category: "AI Tools", isPro: false },
  { id: 60, name: "AI Study Notes Generator", slug: "ai-study-notes-generator", category: "AI Tools", isPro: false },

  // --- PRO LEVEL (PAID TOOLS: 61-100) ---
  { id: 61, name: "AI Research Assistant", slug: "ai-research-assistant", category: "AI Tools", isPro: true },
  { id: 62, name: "AI Deep Research Workspace", slug: "ai-deep-research-workspace", category: "AI Tools", isPro: true },
  { id: 63, name: "AI Document Analyzer", slug: "ai-document-analyzer", category: "AI Tools", isPro: true },
  { id: 64, name: "AI Contract Analyzer", slug: "ai-contract-analyzer", category: "AI Tools", isPro: true },
  { id: 65, name: "AI PDF Question Answering", slug: "ai-pdf-question-answering", category: "AI Tools", isPro: true },
  { id: 66, name: "AI Spreadsheet Analyst", slug: "ai-spreadsheet-analyst", category: "AI Tools", isPro: true },
  { id: 67, name: "AI Data Cleaning Assistant", slug: "ai-data-cleaning-assistant", category: "AI Tools", isPro: true },
  { id: 68, name: "AI SQL Query Generator", slug: "ai-sql-query-generator", category: "AI Tools", isPro: true },
  { id: 69, name: "AI Regex Generator", slug: "ai-regex-generator", category: "AI Tools", isPro: true },
  { id: 70, name: "AI Code Generator", slug: "ai-code-generator", category: "AI Tools", isPro: true },
  { id: 71, name: "AI Code Explainer", slug: "ai-code-explainer", category: "AI Tools", isPro: true },
  { id: 72, name: "AI Code Refactoring Assistant", slug: "ai-code-refactoring-assistant", category: "AI Tools", isPro: true },
  { id: 73, name: "AI Debugging Assistant", slug: "ai-debugging-assistant", category: "AI Tools", isPro: true },
  { id: 74, name: "AI API Generator", slug: "ai-api-generator", category: "AI Tools", isPro: true },
  { id: 75, name: "AI JSON Generator", slug: "ai-json-generator", category: "AI Tools", isPro: true },
  { id: 76, name: "AI Database Schema Generator", slug: "ai-database-schema-generator", category: "AI Tools", isPro: true },
  { id: 77, name: "AI Technical Documentation Generator", slug: "ai-technical-documentation-generator", category: "AI Tools", isPro: true },
  { id: 78, name: "AI README Generator", slug: "ai-readme-generator", category: "AI Tools", isPro: true },
  { id: 79, name: "AI Unit Test Generator", slug: "ai-unit-test-generator", category: "AI Tools", isPro: true },
  { id: 80, name: "AI Test Case Generator", slug: "ai-test-case-generator", category: "AI Tools", isPro: true },
  { id: 81, name: "AI UX Copy Generator", slug: "ai-ux-copy-generator", category: "AI Tools", isPro: true },
  { id: 82, name: "AI Landing Page Copy Generator", slug: "ai-landing-page-copy-generator", category: "AI Tools", isPro: true },
  { id: 83, name: "AI Sales Page Generator", slug: "ai-sales-page-generator", category: "AI Tools", isPro: true },
  { id: 84, name: "AI Proposal Generator", slug: "ai-proposal-generator", category: "AI Tools", isPro: true },
  { id: 85, name: "AI Business Plan Generator", slug: "ai-business-plan-generator", category: "AI Tools", isPro: true },
  { id: 86, name: "AI Market Research Assistant", slug: "ai-market-research-assistant", category: "AI Tools", isPro: true },
  { id: 87, name: "AI Competitor Analysis Assistant", slug: "ai-competitor-analysis-assistant", category: "AI Tools", isPro: true },
  { id: 88, name: "AI SWOT Analysis Generator", slug: "ai-swot-analysis-generator", category: "AI Tools", isPro: true },
  { id: 89, name: "AI Customer Persona Generator", slug: "ai-customer-persona-generator", category: "AI Tools", isPro: true },
  { id: 90, name: "AI Sales Email Personalizer", slug: "ai-sales-email-personalizer", category: "AI Tools", isPro: true },
  { id: 91, name: "AI Cold Outreach Generator", slug: "ai-cold-outreach-generator", category: "AI Tools", isPro: true },
  { id: 92, name: "AI Lead Qualification Assistant", slug: "ai-lead-qualification-assistant", category: "AI Tools", isPro: true },
  { id: 93, name: "AI Meeting Intelligence Tool", slug: "ai-meeting-intelligence-tool", category: "AI Tools", isPro: true },
  { id: 94, name: "AI Knowledge Base Generator", slug: "ai-knowledge-base-generator", category: "AI Tools", isPro: true },
  { id: 95, name: "AI FAQ Knowledge Assistant", slug: "ai-faq-knowledge-assistant", category: "AI Tools", isPro: true },
  { id: 96, name: "AI Workflow Planner", slug: "ai-workflow-planner", category: "AI Tools", isPro: true },
  { id: 97, name: "AI Decision Assistant", slug: "ai-decision-assistant", category: "AI Tools", isPro: true },
  { id: 98, name: "AI Report Generator", slug: "ai-report-generator", category: "AI Tools", isPro: true },
  { id: 99, name: "AI Executive Summary Generator", slug: "ai-executive-summary-generator", category: "AI Tools", isPro: true },
  { id: 100, name: "AI Custom Prompt Builder", slug: "ai-custom-prompt-builder", category: "AI Tools", isPro: true },
];