export interface BrowserTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const browserToolsList: BrowserTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "URL Encoder", slug: "url-encoder", category: "Browser Tools", isPro: false },
  { id: 2, name: "URL Decoder", slug: "url-decoder", category: "Browser Tools", isPro: false },
  { id: 3, name: "URL Validator", slug: "url-validator", category: "Browser Tools", isPro: false },
  { id: 4, name: "URL Parser", slug: "url-parser", category: "Browser Tools", isPro: false },
  { id: 5, name: "URL Cleaner", slug: "url-cleaner", category: "Browser Tools", isPro: false },
  { id: 6, name: "UTM Builder", slug: "utm-builder", category: "Browser Tools", isPro: false },
  { id: 7, name: "UTM Parser", slug: "utm-parser", category: "Browser Tools", isPro: false },
  { id: 8, name: "URL Redirect Checker", slug: "url-redirect-checker", category: "Browser Tools", isPro: false },
  { id: 9, name: "HTTP Status Checker", slug: "http-status-checker", category: "Browser Tools", isPro: false },
  { id: 10, name: "HTTP Header Checker", slug: "http-header-checker", category: "Browser Tools", isPro: false },
  { id: 11, name: "User Agent Parser", slug: "user-agent-parser", category: "Browser Tools", isPro: false },
  { id: 12, name: "Screen Resolution Checker", slug: "screen-resolution-checker", category: "Browser Tools", isPro: false },
  { id: 13, name: "Viewport Size Checker", slug: "viewport-size-checker", category: "Browser Tools", isPro: false },
  { id: 14, name: "IP Address Checker", slug: "ip-address-checker", category: "Browser Tools", isPro: false },
  { id: 15, name: "JWT Decoder", slug: "jwt-decoder", category: "Browser Tools", isPro: false },
  { id: 16, name: "Base64 Encoder", slug: "base64-encoder", category: "Browser Tools", isPro: false },
  { id: 17, name: "HTML Formatter", slug: "html-formatter", category: "Browser Tools", isPro: false },
  { id: 18, name: "JSON Viewer", slug: "json-viewer", category: "Browser Tools", isPro: false },
  { id: 19, name: "Open Graph Checker", slug: "open-graph-checker", category: "Browser Tools", isPro: false },
  { id: 20, name: "Browser Compatibility Checker", slug: "browser-compatibility-checker", category: "Browser Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "URL Shortener", slug: "url-shortener", category: "Browser Tools", isPro: false },
  { id: 22, name: "URL Expander", slug: "url-expander", category: "Browser Tools", isPro: false },
  { id: 23, name: "URL Parameter Remover", slug: "url-parameter-remover", category: "Browser Tools", isPro: false },
  { id: 24, name: "Query String Parser", slug: "query-string-parser", category: "Browser Tools", isPro: false },
  { id: 25, name: "Query String Generator", slug: "query-string-generator", category: "Browser Tools", isPro: false },
  { id: 26, name: "UTM Cleaner", slug: "utm-cleaner", category: "Browser Tools", isPro: false },
  { id: 27, name: "Domain Extractor", slug: "domain-extractor", category: "Browser Tools", isPro: false },
  { id: 28, name: "Hostname Extractor", slug: "hostname-extractor", category: "Browser Tools", isPro: false },
  { id: 29, name: "Path Extractor", slug: "path-extractor", category: "Browser Tools", isPro: false },
  { id: 30, name: "Query Parameter Extractor", slug: "query-parameter-extractor", category: "Browser Tools", isPro: false },
  { id: 31, name: "User Agent Generator", slug: "user-agent-generator", category: "Browser Tools", isPro: false },
  { id: 32, name: "Browser User Agent Lookup", slug: "browser-user-agent-lookup", category: "Browser Tools", isPro: false },
  { id: 33, name: "Browser Detection Tool", slug: "browser-detection-tool", category: "Browser Tools", isPro: false },
  { id: 34, name: "Browser Version Checker", slug: "browser-version-checker", category: "Browser Tools", isPro: false },
  { id: 35, name: "Device Pixel Ratio Checker", slug: "device-pixel-ratio-checker", category: "Browser Tools", isPro: false },
  { id: 36, name: "Browser Time Zone Checker", slug: "browser-time-zone-checker", category: "Browser Tools", isPro: false },
  { id: 37, name: "Browser Language Checker", slug: "browser-language-checker", category: "Browser Tools", isPro: false },
  { id: 38, name: "IPv4 Address Validator", slug: "ipv4-address-validator", category: "Browser Tools", isPro: false },
  { id: 39, name: "IPv6 Address Validator", slug: "ipv6-address-validator", category: "Browser Tools", isPro: false },
  { id: 40, name: "Browser Cache Checker", slug: "browser-cache-checker", category: "Browser Tools", isPro: false },
  { id: 41, name: "Cookie Parser", slug: "cookie-parser", category: "Browser Tools", isPro: false },
  { id: 42, name: "Cookie Size Calculator", slug: "cookie-size-calculator", category: "Browser Tools", isPro: false },
  { id: 43, name: "Cookie Formatter", slug: "cookie-formatter", category: "Browser Tools", isPro: false },
  { id: 44, name: "JWT Encoder", slug: "jwt-encoder", category: "Browser Tools", isPro: false },
  { id: 45, name: "JWT Header Decoder", slug: "jwt-header-decoder", category: "Browser Tools", isPro: false },
  { id: 46, name: "JWT Payload Decoder", slug: "jwt-payload-decoder", category: "Browser Tools", isPro: false },
  { id: 47, name: "Base64 Decoder", slug: "base64-decoder", category: "Browser Tools", isPro: false },
  { id: 48, name: "HTML Entity Encoder", slug: "html-entity-encoder", category: "Browser Tools", isPro: false },
  { id: 49, name: "HTML Entity Decoder", slug: "html-entity-decoder", category: "Browser Tools", isPro: false },
  { id: 50, name: "HTML Validator", slug: "html-validator", category: "Browser Tools", isPro: false },
  { id: 51, name: "CSS Formatter", slug: "css-formatter", category: "Browser Tools", isPro: false },
  { id: 52, name: "CSS Minifier", slug: "css-minifier", category: "Browser Tools", isPro: false },
  { id: 53, name: "JavaScript Minifier", slug: "javascript-minifier", category: "Browser Tools", isPro: false },
  { id: 54, name: "JSON Formatter", slug: "json-formatter-browser", category: "Browser Tools", isPro: false },
  { id: 55, name: "XML Viewer", slug: "xml-viewer", category: "Browser Tools", isPro: false },
  { id: 56, name: "Mobile Browser Tester", slug: "mobile-browser-tester", category: "Browser Tools", isPro: false },
  { id: 57, name: "Website Screenshot Tool", slug: "website-screenshot-tool", category: "Browser Tools", isPro: false },
  { id: 58, name: "Webpage Metadata Checker", slug: "webpage-metadata-checker", category: "Browser Tools", isPro: false },
  { id: 59, name: "Twitter Card Checker", slug: "twitter-card-checker", category: "Browser Tools", isPro: false },
  { id: 60, name: "Favicon Checker", slug: "favicon-checker", category: "Browser Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Browser Developer Workspace", slug: "browser-developer-workspace", category: "Browser Tools", isPro: true },
  { id: 62, name: "Web Debugging Workspace", slug: "web-debugging-workspace", category: "Browser Tools", isPro: true },
  { id: 63, name: "URL Intelligence Dashboard", slug: "url-intelligence-dashboard", category: "Browser Tools", isPro: true },
  { id: 64, name: "Redirect Management Workspace", slug: "redirect-management-workspace", category: "Browser Tools", isPro: true },
  { id: 65, name: "HTTP Header Analysis Workspace", slug: "http-header-analysis-workspace", category: "Browser Tools", isPro: true },
  { id: 66, name: "Browser Compatibility Dashboard", slug: "browser-compatibility-dashboard", category: "Browser Tools", isPro: true },
  { id: 67, name: "Cross-Browser Testing Workspace", slug: "cross-browser-testing-workspace", category: "Browser Tools", isPro: true },
  { id: 68, name: "Device Testing Workspace", slug: "device-testing-workspace", category: "Browser Tools", isPro: true },
  { id: 69, name: "Web Metadata Intelligence", slug: "web-metadata-intelligence", category: "Browser Tools", isPro: true },
  { id: 70, name: "Open Graph Management Workspace", slug: "open-graph-management-workspace", category: "Browser Tools", isPro: true },
  { id: 71, name: "Social Preview Workspace", slug: "social-preview-workspace", category: "Browser Tools", isPro: true },
  { id: 72, name: "Favicon Management Workspace", slug: "favicon-management-workspace", category: "Browser Tools", isPro: true },
  { id: 73, name: "Web Performance Testing Workspace", slug: "web-performance-testing-workspace", category: "Browser Tools", isPro: true },
  { id: 74, name: "Browser Network Analysis Workspace", slug: "browser-network-analysis-workspace", category: "Browser Tools", isPro: true },
  { id: 75, name: "Cookie Audit Workspace", slug: "cookie-audit-workspace", category: "Browser Tools", isPro: true },
  { id: 76, name: "Privacy Configuration Workspace", slug: "privacy-configuration-workspace", category: "Browser Tools", isPro: true },
  { id: 77, name: "Browser Storage Analyzer", slug: "browser-storage-analyzer", category: "Browser Tools", isPro: true },
  { id: 78, name: "Local Storage Analyzer", slug: "local-storage-analyzer", category: "Browser Tools", isPro: true },
  { id: 79, name: "Session Storage Analyzer", slug: "session-storage-analyzer", category: "Browser Tools", isPro: true },
  { id: 80, name: "Web API Testing Workspace", slug: "web-api-testing-workspace", category: "Browser Tools", isPro: true },
  { id: 81, name: "REST Request Workspace", slug: "rest-request-workspace", category: "Browser Tools", isPro: true },
  { id: 82, name: "GraphQL Request Workspace", slug: "graphql-request-workspace", category: "Browser Tools", isPro: true },
  { id: 83, name: "WebSocket Testing Workspace", slug: "websocket-testing-workspace", category: "Browser Tools", isPro: true },
  { id: 84, name: "JWT Management Workspace", slug: "jwt-management-workspace", category: "Browser Tools", isPro: true },
  { id: 85, name: "Token Debugging Workspace", slug: "token-debugging-workspace", category: "Browser Tools", isPro: true },
  { id: 86, name: "Frontend Debugging Dashboard", slug: "frontend-debugging-dashboard", category: "Browser Tools", isPro: true },
  { id: 87, name: "Browser Console Workspace", slug: "browser-console-workspace", category: "Browser Tools", isPro: true },
  { id: 88, name: "Website Screenshot Automation", slug: "website-screenshot-automation", category: "Browser Tools", isPro: true },
  { id: 89, name: "Browser Automation Workspace", slug: "browser-automation-workspace", category: "Browser Tools", isPro: true },
  { id: 90, name: "Webpage Monitoring Workspace", slug: "webpage-monitoring-workspace", category: "Browser Tools", isPro: true },
  { id: 91, name: "Webpage Change Detection", slug: "webpage-change-detection", category: "Browser Tools", isPro: true },
  { id: 92, name: "Browser Data Export Workspace", slug: "browser-data-export-workspace", category: "Browser Tools", isPro: true },
  { id: 93, name: "Browser Developer API Workspace", slug: "browser-developer-api-workspace", category: "Browser Tools", isPro: true },
  { id: 94, name: "Web Debugging Report Generator", slug: "web-debugging-report-generator", category: "Browser Tools", isPro: true },
  { id: 95, name: "Web Compatibility Report Generator", slug: "web-compatibility-report-generator", category: "Browser Tools", isPro: true },
  { id: 96, name: "Browser Testing Automation", slug: "browser-testing-automation", category: "Browser Tools", isPro: true },
  { id: 97, name: "Web Developer Intelligence Platform", slug: "web-developer-intelligence-platform", category: "Browser Tools", isPro: true },
  { id: 98, name: "Browser Productivity Platform", slug: "browser-productivity-platform", category: "Browser Tools", isPro: true },
  { id: 99, name: "Web Debugging SaaS Workspace", slug: "web-debugging-saas-workspace", category: "Browser Tools", isPro: true },
  { id: 100, name: "Professional Browser Command Center", slug: "professional-browser-command-center", category: "Browser Tools", isPro: true }
];