import {
  Bot, CircleDollarSign, SearchCheck, PlaySquare, Globe, Type, Image as ImageIcon, FileText,
  Terminal, Share2, ShoppingCart, Megaphone, Briefcase, Mail, GraduationCap,
  Languages, CheckSquare, Calculator, HeartPulse, Scale, Users, Lock, Files, Cpu,
  Table, Database, Network, Palette, BarChart, Video, Headphones, Camera, PenTool,
  Stamp, Building, Car, Plane, CloudRain, Newspaper, ShoppingBag, Laptop, Landmark,
  CreditCard, Bitcoin, TrendingUp, Receipt, HardHat, Ruler, FlaskConical, Sigma,
  ArrowRightLeft, Clock, MapPin, Stethoscope, Apple, Dumbbell, Baby, Dog, Gamepad2,
  Trophy, BookOpen, Backpack, Truck, MessageSquare, Cloud, Monitor, Smartphone,
  AppWindow, Search, UserPlus, Wand2, Rocket, PieChart, BrainCircuit, Binary,
  ShieldCheck, Wifi, Factory, Globe2
} from "lucide-react";

export const categories = [
  { name: "AI Tools", icon: Bot, count: "120+ Tools", color: "text-purple-400" },
  { name: "Finance Tools", icon: CircleDollarSign, count: "45+ Tools", color: "text-green-400" },
  { name: "SEO Tools", icon: SearchCheck, count: "80+ Tools", color: "text-blue-400" },
  { name: "YouTube Tools", icon: PlaySquare, count: "30+ Tools", color: "text-red-500" },
  { name: "Website Tools", icon: Globe, count: "55+ Tools", color: "text-cyan-400" },
  { name: "Text Tools", icon: Type, count: "90+ Tools", color: "text-slate-300" },
  { name: "Image Tools", icon: ImageIcon, count: "65+ Tools", color: "text-yellow-400" },
  { name: "PDF Tools", icon: FileText, count: "25+ Tools", color: "text-red-400" },
  { name: "Developer Tools", icon: Terminal, count: "150+ Tools", color: "text-emerald-400" },
  { name: "Social Media Tools", icon: Share2, count: "40+ Tools", color: "text-pink-400" },
  { name: "eCommerce Tools", icon: ShoppingCart, count: "35+ Tools", color: "text-orange-400" },
  { name: "Marketing Tools", icon: Megaphone, count: "50+ Tools", color: "text-amber-500" },
  { name: "Business & Startup Tools", icon: Briefcase, count: "60+ Tools", color: "text-indigo-400" },
  { name: "Email Productivity Tools", icon: Mail, count: "20+ Tools", color: "text-blue-300" },
  { name: "Education Tools", icon: GraduationCap, count: "45+ Tools", color: "text-yellow-500" },
  { name: "Language Tools", icon: Languages, count: "30+ Tools", color: "text-teal-400" },
  { name: "Productivity Tools", icon: CheckSquare, count: "85+ Tools", color: "text-green-500" },
  { name: "Utility Calculators", icon: Calculator, count: "110+ Tools", color: "text-slate-400" },
  { name: "Health & Fitness Tools", icon: HeartPulse, count: "25+ Tools", color: "text-rose-500" },
  { name: "Legal Tools", icon: Scale, count: "15+ Tools", color: "text-amber-600" },
  { name: "HR & Career Tools", icon: Users, count: "35+ Tools", color: "text-cyan-500" },
  { name: "Security Tools", icon: Lock, count: "20+ Tools", color: "text-red-500" },
  { name: "File & Document Tools", icon: Files, count: "70+ Tools", color: "text-blue-200" },
  { name: "AI Automation Tools", icon: Cpu, count: "40+ Tools", color: "text-purple-500" },
  { name: "Excel & Spreadsheet Tools", icon: Table, count: "30+ Tools", color: "text-emerald-500" },
  { name: "Database & API Tools", icon: Database, count: "45+ Tools", color: "text-indigo-500" },
  { name: "Network & Internet Tools", icon: Network, count: "25+ Tools", color: "text-sky-400" },
  { name: "Design & Accessibility Tools", icon: Palette, count: "55+ Tools", color: "text-pink-500" },
  { name: "Analytics & SaaS Tools", icon: BarChart, count: "35+ Tools", color: "text-blue-500" },
  { name: "Video Tools", icon: Video, count: "40+ Tools", color: "text-purple-300" },
  { name: "Audio Tools", icon: Headphones, count: "25+ Tools", color: "text-orange-500" },
  { name: "Camera & Photo Tools", icon: Camera, count: "30+ Tools", color: "text-slate-300" },
  { name: "Graphic Design Tools", icon: PenTool, count: "45+ Tools", color: "text-fuchsia-400" },
  { name: "Logo & Branding Tools", icon: Stamp, count: "20+ Tools", color: "text-rose-400" },
  { name: "Real Estate Tools", icon: Building, count: "15+ Tools", color: "text-blue-600" },
  { name: "Automobile Tools", icon: Car, count: "10+ Tools", color: "text-red-600" },
  { name: "Travel Tools", icon: Plane, count: "20+ Tools", color: "text-sky-500" },
  { name: "Weather Tools", icon: CloudRain, count: "10+ Tools", color: "text-cyan-300" },
  { name: "News & Media Tools", icon: Newspaper, count: "15+ Tools", color: "text-slate-400" },
  { name: "Shopping Tools", icon: ShoppingBag, count: "25+ Tools", color: "text-pink-600" },
  { name: "Freelancing Tools", icon: Laptop, count: "30+ Tools", color: "text-emerald-300" },
  { name: "Banking Tools", icon: Landmark, count: "20+ Tools", color: "text-yellow-600" },
  { name: "Credit Card Tools", icon: CreditCard, count: "15+ Tools", color: "text-orange-300" },
  { name: "Cryptocurrency Tools", icon: Bitcoin, count: "40+ Tools", color: "text-amber-400" },
  { name: "Stock Market Tools", icon: TrendingUp, count: "35+ Tools", color: "text-green-500" },
  { name: "Tax & Accounting Tools", icon: Receipt, count: "25+ Tools", color: "text-blue-400" },
  { name: "Construction Tools", icon: HardHat, count: "10+ Tools", color: "text-yellow-500" },
  { name: "Engineering Tools", icon: Ruler, count: "20+ Tools", color: "text-slate-400" },
  { name: "Science Tools", icon: FlaskConical, count: "15+ Tools", color: "text-teal-500" },
  { name: "Mathematics Tools", icon: Sigma, count: "45+ Tools", color: "text-indigo-400" },
  { name: "Unit Conversion Tools", icon: ArrowRightLeft, count: "60+ Tools", color: "text-orange-500" },
  { name: "Date & Time Tools", icon: Clock, count: "30+ Tools", color: "text-blue-300" },
  { name: "Geography Tools", icon: Globe2, count: "15+ Tools", color: "text-green-600" },
  { name: "Maps & Location Tools", icon: MapPin, count: "25+ Tools", color: "text-red-500" },
  { name: "Medical Tools", icon: Stethoscope, count: "20+ Tools", color: "text-rose-400" },
  { name: "Nutrition Tools", icon: Apple, count: "15+ Tools", color: "text-green-500" },
  { name: "Workout & Fitness Planning Tools", icon: Dumbbell, count: "25+ Tools", color: "text-slate-300" },
  { name: "Parenting Tools", icon: Baby, count: "10+ Tools", color: "text-pink-300" },
  { name: "Pet Care Tools", icon: Dog, count: "10+ Tools", color: "text-amber-500" },
  { name: "Gaming Tools", icon: Gamepad2, count: "35+ Tools", color: "text-purple-500" },
  { name: "Sports Tools", icon: Trophy, count: "20+ Tools", color: "text-yellow-400" },
  { name: "Book & Reading Tools", icon: BookOpen, count: "15+ Tools", color: "text-blue-400" },
  { name: "Student Tools", icon: Backpack, count: "30+ Tools", color: "text-emerald-400" },
  { name: "Government & Public Service Tools", icon: Landmark, count: "15+ Tools", color: "text-slate-400" },
  { name: "Logistics & Shipping Tools", icon: Truck, count: "20+ Tools", color: "text-cyan-500" },
  { name: "Communication Tools", icon: MessageSquare, count: "40+ Tools", color: "text-blue-500" },
  { name: "Cloud & DevOps Tools", icon: Cloud, count: "50+ Tools", color: "text-sky-400" },
  { name: "Operating System Tools", icon: Monitor, count: "25+ Tools", color: "text-slate-300" },
  { name: "Mobile App Tools", icon: Smartphone, count: "45+ Tools", color: "text-indigo-400" },
  { name: "Browser Tools", icon: AppWindow, count: "20+ Tools", color: "text-orange-400" },
  { name: "Search & Research Tools", icon: Search, count: "35+ Tools", color: "text-blue-400" },
  { name: "Collaboration Tools", icon: UserPlus, count: "40+ Tools", color: "text-teal-400" },
  { name: "No-Code & Automation Tools", icon: Wand2, count: "55+ Tools", color: "text-fuchsia-500" },
  { name: "Startup Resources Tools", icon: Rocket, count: "30+ Tools", color: "text-rose-500" },
  { name: "Business Intelligence Tools", icon: PieChart, count: "25+ Tools", color: "text-amber-500" },
  { name: "Machine Learning Tools", icon: BrainCircuit, count: "35+ Tools", color: "text-purple-400" },
  { name: "Data Science Tools", icon: Binary, count: "40+ Tools", color: "text-emerald-400" },
  { name: "Cybersecurity Tools", icon: ShieldCheck, count: "30+ Tools", color: "text-red-500" },
  { name: "IoT Tools", icon: Wifi, count: "20+ Tools", color: "text-blue-500" },
  { name: "Manufacturing Tools", icon: Factory, count: "15+ Tools", color: "text-slate-400" }
];