export interface CollaborationTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const collaborationToolsList: CollaborationTool[] = [
  // --- 🔥 PRIORITY 20 FREE TOOLS (IDs 1-20 | isPro: false) ---
  { id: 1, name: "RACI Matrix Generator", slug: "raci-matrix-generator", category: "Collaboration Tools", isPro: false },
  { id: 2, name: "Team Workload Calculator", slug: "team-workload-calculator", category: "Collaboration Tools", isPro: false },
  { id: 3, name: "Team Capacity Calculator", slug: "team-capacity-calculator", category: "Collaboration Tools", isPro: false },
  { id: 4, name: "Resource Allocation Calculator", slug: "resource-allocation-calculator", category: "Collaboration Tools", isPro: false },
  { id: 5, name: "Team Availability Planner", slug: "team-availability-planner", category: "Collaboration Tools", isPro: false },
  { id: 6, name: "Team Handoff Checklist", slug: "team-handoff-checklist", category: "Collaboration Tools", isPro: false },
  { id: 7, name: "Team Onboarding Checklist", slug: "team-onboarding-checklist", category: "Collaboration Tools", isPro: false },
  { id: 8, name: "Team Working Agreement Generator", slug: "team-working-agreement-generator", category: "Collaboration Tools", isPro: false },
  { id: 9, name: "Team Task Board", slug: "team-task-board", category: "Collaboration Tools", isPro: false },
  { id: 10, name: "Team Task Prioritizer", slug: "team-task-prioritizer", category: "Collaboration Tools", isPro: false },
  { id: 11, name: "Shared Notes Workspace", slug: "shared-notes-workspace", category: "Collaboration Tools", isPro: false },
  { id: 12, name: "Decision Tracker", slug: "decision-tracker", category: "Collaboration Tools", isPro: false },
  { id: 13, name: "Project Status Tracker", slug: "project-status-tracker", category: "Collaboration Tools", isPro: false },
  { id: 14, name: "OKR Tracker", slug: "okr-tracker", category: "Collaboration Tools", isPro: false },
  { id: 15, name: "Team KPI Tracker", slug: "team-kpi-tracker", category: "Collaboration Tools", isPro: false },
  { id: 16, name: "Project Dependency Mapper", slug: "project-dependency-mapper", category: "Collaboration Tools", isPro: false },
  { id: 17, name: "Project Risk Register", slug: "project-risk-register", category: "Collaboration Tools", isPro: false },
  { id: 18, name: "Workload Balance Checker", slug: "workload-balance-checker", category: "Collaboration Tools", isPro: false },
  { id: 19, name: "Team Performance Dashboard", slug: "team-performance-dashboard-free", category: "Collaboration Tools", isPro: false },
  { id: 20, name: "Collaboration Command Center Free", slug: "collaboration-command-center-free", category: "Collaboration Tools", isPro: false },

  // --- REMAINING 40 CORE FREE TOOLS (IDs 21-60 | isPro: false) ---
  { id: 21, name: "Team Name Generator", slug: "team-name-generator", category: "Collaboration Tools", isPro: false },
  { id: 22, name: "Team Role Planner", slug: "team-role-planner", category: "Collaboration Tools", isPro: false },
  { id: 23, name: "Team Responsibility Matrix", slug: "team-responsibility-matrix", category: "Collaboration Tools", isPro: false },
  { id: 24, name: "Team Meeting Planner", slug: "team-meeting-planner", category: "Collaboration Tools", isPro: false },
  { id: 25, name: "Meeting Agenda Builder", slug: "meeting-agenda-builder", category: "Collaboration Tools", isPro: false },
  { id: 26, name: "Meeting Action Item Tracker", slug: "meeting-action-item-tracker", category: "Collaboration Tools", isPro: false },
  { id: 27, name: "Team Decision Log", slug: "team-decision-log", category: "Collaboration Tools", isPro: false },
  { id: 28, name: "Team Decision Matrix", slug: "team-decision-matrix", category: "Collaboration Tools", isPro: false },
  { id: 29, name: "Project Capacity Calculator", slug: "project-capacity-calculator", category: "Collaboration Tools", isPro: false },
  { id: 30, name: "Team Shift Planner", slug: "team-shift-planner", category: "Collaboration Tools", isPro: false },
  { id: 31, name: "Project Handoff Checklist", slug: "project-handoff-checklist", category: "Collaboration Tools", isPro: false },
  { id: 32, name: "Client Handoff Checklist", slug: "client-handoff-checklist", category: "Collaboration Tools", isPro: false },
  { id: 33, name: "Employee Onboarding Planner", slug: "employee-onboarding-planner", category: "Collaboration Tools", isPro: false },
  { id: 34, name: "Remote Work Checklist", slug: "remote-work-checklist", category: "Collaboration Tools", isPro: false },
  { id: 35, name: "Remote Meeting Checklist", slug: "remote-meeting-checklist", category: "Collaboration Tools", isPro: false },
  { id: 36, name: "Collaboration Agreement Generator", slug: "collaboration-agreement-generator", category: "Collaboration Tools", isPro: false },
  { id: 37, name: "Team Communication Guidelines", slug: "team-communication-guidelines", category: "Collaboration Tools", isPro: false },
  { id: 38, name: "Team SOP Generator", slug: "team-sop-generator", category: "Collaboration Tools", isPro: false },
  { id: 39, name: "Project SOP Checklist", slug: "project-sop-checklist", category: "Collaboration Tools", isPro: false },
  { id: 40, name: "Shared Task List", slug: "shared-task-list", category: "Collaboration Tools", isPro: false },
  { id: 41, name: "Shared Checklist", slug: "shared-checklist", category: "Collaboration Tools", isPro: false },
  { id: 42, name: "Action Item Tracker", slug: "action-item-tracker", category: "Collaboration Tools", isPro: false },
  { id: 43, name: "Team Progress Tracker", slug: "team-progress-tracker", category: "Collaboration Tools", isPro: false },
  { id: 44, name: "Team Goal Tracker", slug: "team-goal-tracker", category: "Collaboration Tools", isPro: false },
  { id: 45, name: "Team Milestone Tracker", slug: "team-milestone-tracker", category: "Collaboration Tools", isPro: false },
  { id: 46, name: "Project Timeline Generator", slug: "project-timeline-generator", category: "Collaboration Tools", isPro: false },
  { id: 47, name: "Project Issue Tracker", slug: "project-issue-tracker", category: "Collaboration Tools", isPro: false },
  { id: 48, name: "Project Change Log", slug: "project-change-log", category: "Collaboration Tools", isPro: false },
  { id: 49, name: "Project Decision Register", slug: "project-decision-register", category: "Collaboration Tools", isPro: false },
  { id: 50, name: "Project Stakeholder List", slug: "project-stakeholder-list", category: "Collaboration Tools", isPro: false },
  { id: 51, name: "Stakeholder Matrix", slug: "stakeholder-matrix", category: "Collaboration Tools", isPro: false },
  { id: 52, name: "Responsibility Assignment Tool", slug: "responsibility-assignment-tool", category: "Collaboration Tools", isPro: false },
  { id: 53, name: "Team Directory", slug: "team-directory", category: "Collaboration Tools", isPro: false },
  { id: 54, name: "Team Contact Organizer", slug: "team-contact-organizer", category: "Collaboration Tools", isPro: false },
  { id: 55, name: "Employee Skills Matrix", slug: "employee-skills-matrix", category: "Collaboration Tools", isPro: false },
  { id: 56, name: "Team Skills Gap Analyzer", slug: "team-skills-gap-analyzer", category: "Collaboration Tools", isPro: false },
  { id: 57, name: "Team Availability Matrix", slug: "team-availability-matrix", category: "Collaboration Tools", isPro: false },
  { id: 58, name: "Task Assignment Generator", slug: "task-assignment-generator", category: "Collaboration Tools", isPro: false },
  { id: 59, name: "Team Retrospective Template", slug: "team-retrospective-template", category: "Collaboration Tools", isPro: false },
  { id: 60, name: "Daily Standup Template", slug: "daily-standup-template", category: "Collaboration Tools", isPro: false },

  // --- ⚡ 40 PRO / SAAS TOOLS (IDs 61-100 | isPro: true) ---
  { id: 61, name: "Sprint Retrospective Template", slug: "sprint-retrospective-template", category: "Collaboration Tools", isPro: true },
  { id: 62, name: "Weekly Team Report Generator", slug: "weekly-team-report-generator", category: "Collaboration Tools", isPro: true },
  { id: 63, name: "Collaboration Command Center", slug: "collaboration-command-center", category: "Collaboration Tools", isPro: true },
  { id: 64, name: "Team Workspace", slug: "team-workspace", category: "Collaboration Tools", isPro: true },
  { id: 65, name: "Project Collaboration Workspace", slug: "project-collaboration-workspace", category: "Collaboration Tools", isPro: true },
  { id: 66, name: "Cross-Team Collaboration Hub", slug: "cross-team-collaboration-hub", category: "Collaboration Tools", isPro: true },
  { id: 67, name: "Remote Team Management Workspace", slug: "remote-team-management-workspace", category: "Collaboration Tools", isPro: true },
  { id: 68, name: "Team Capacity Planning Engine", slug: "team-capacity-planning-engine", category: "Collaboration Tools", isPro: true },
  { id: 69, name: "Resource Allocation Engine", slug: "resource-allocation-engine", category: "Collaboration Tools", isPro: true },
  { id: 70, name: "Workload Optimization Workspace", slug: "workload-optimization-workspace", category: "Collaboration Tools", isPro: true },
  { id: 71, name: "Team Scheduling Engine", slug: "team-scheduling-engine", category: "Collaboration Tools", isPro: true },
  { id: 72, name: "Shift Optimization Workspace", slug: "shift-optimization-workspace", category: "Collaboration Tools", isPro: true },
  { id: 73, name: "Project Dependency Dashboard", slug: "project-dependency-dashboard", category: "Collaboration Tools", isPro: true },
  { id: 74, name: "Project Risk Management Workspace", slug: "project-risk-management-workspace", category: "Collaboration Tools", isPro: true },
  { id: 75, name: "Project Issue Management Workspace", slug: "project-issue-management-workspace", category: "Collaboration Tools", isPro: true },
  { id: 76, name: "Decision Intelligence Workspace", slug: "decision-intelligence-workspace", category: "Collaboration Tools", isPro: true },
  { id: 77, name: "Team Performance Dashboard Pro", slug: "team-performance-dashboard-pro", category: "Collaboration Tools", isPro: true },
  { id: 78, name: "Team Productivity Analytics", slug: "team-productivity-analytics", category: "Collaboration Tools", isPro: true },
  { id: 79, name: "Team KPI Dashboard", slug: "team-kpi-dashboard", category: "Collaboration Tools", isPro: true },
  { id: 80, name: "OKR Management Workspace", slug: "okr-management-workspace", category: "Collaboration Tools", isPro: true },
  { id: 81, name: "Team Goal Management Workspace", slug: "team-goal-management-workspace", category: "Collaboration Tools", isPro: true },
  { id: 82, name: "Employee Skills Intelligence", slug: "employee-skills-intelligence", category: "Collaboration Tools", isPro: true },
  { id: 83, name: "Skills Gap Dashboard", slug: "skills-gap-dashboard", category: "Collaboration Tools", isPro: true },
  { id: 84, name: "Stakeholder Management Workspace", slug: "stakeholder-management-workspace", category: "Collaboration Tools", isPro: true },
  { id: 85, name: "Project Communication Dashboard", slug: "project-communication-dashboard", category: "Collaboration Tools", isPro: true },
  { id: 86, name: "Meeting Intelligence Workspace", slug: "meeting-intelligence-workspace", category: "Collaboration Tools", isPro: true },
  { id: 87, name: "Meeting Action Management", slug: "meeting-action-management", category: "Collaboration Tools", isPro: true },
  { id: 88, name: "Team Knowledge Base", slug: "team-knowledge-base", category: "Collaboration Tools", isPro: true },
  { id: 89, name: "SOP Management Workspace", slug: "sop-management-workspace", category: "Collaboration Tools", isPro: true },
  { id: 90, name: "Team Document Collaboration", slug: "team-document-collaboration", category: "Collaboration Tools", isPro: true },
  { id: 91, name: "Client Collaboration Workspace", slug: "client-collaboration-workspace", category: "Collaboration Tools", isPro: true },
  { id: 92, name: "Vendor Collaboration Workspace", slug: "vendor-collaboration-workspace", category: "Collaboration Tools", isPro: true },
  { id: 93, name: "Multi-Project Workspace", slug: "multi-project-workspace", category: "Collaboration Tools", isPro: true },
  { id: 94, name: "Team Data Import Workspace", slug: "team-data-import-workspace", category: "Collaboration Tools", isPro: true },
  { id: 95, name: "Collaboration Analytics Dashboard", slug: "collaboration-analytics-dashboard", category: "Collaboration Tools", isPro: true },
  { id: 96, name: "Team Report Generator", slug: "team-report-generator", category: "Collaboration Tools", isPro: true },
  { id: 97, name: "Collaboration API Workspace", slug: "collaboration-api-workspace", category: "Collaboration Tools", isPro: true },
  { id: 98, name: "Workflow Collaboration Automation", slug: "workflow-collaboration-automation", category: "Collaboration Tools", isPro: true },
  { id: 99, name: "Cross-Team Notification Workspace", slug: "cross-team-notification-workspace", category: "Collaboration Tools", isPro: true },
  { id: 100, name: "Professional Collaboration Command Center", slug: "professional-collaboration-command-center", category: "Collaboration Tools", isPro: true }
];