export interface CommunicationTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const communicationToolsList: CommunicationTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "Phone Number Validator", slug: "phone-number-validator", category: "Communication Tools", isPro: false },
  { id: 2, name: "Phone Number Formatter", slug: "phone-number-formatter", category: "Communication Tools", isPro: false },
  { id: 3, name: "Phone Number Country Finder", slug: "phone-number-country-finder", category: "Communication Tools", isPro: false },
  { id: 4, name: "Email Address Validator", slug: "email-address-validator", category: "Communication Tools", isPro: false },
  { id: 5, name: "Email Domain Checker", slug: "email-domain-checker", category: "Communication Tools", isPro: false },
  { id: 6, name: "Email MX Record Checker", slug: "email-mx-record-checker", category: "Communication Tools", isPro: false },
  { id: 7, name: "Email Signature Generator", slug: "email-signature-generator", category: "Communication Tools", isPro: false },
  { id: 8, name: "Meeting Agenda Generator", slug: "meeting-agenda-generator", category: "Communication Tools", isPro: false },
  { id: 9, name: "Meeting Notes Generator", slug: "meeting-notes-generator", category: "Communication Tools", isPro: false },
  { id: 10, name: "Meeting Duration Calculator", slug: "meeting-duration-calculator", category: "Communication Tools", isPro: false },
  { id: 11, name: "Meeting Time Zone Converter", slug: "meeting-time-zone-converter", category: "Communication Tools", isPro: false },
  { id: 12, name: "International Meeting Planner", slug: "international-meeting-planner", category: "Communication Tools", isPro: false },
  { id: 13, name: "Out-of-Office Message Generator", slug: "out-of-office-message-generator", category: "Communication Tools", isPro: false },
  { id: 14, name: "SMS Character Counter", slug: "sms-character-counter", category: "Communication Tools", isPro: false },
  { id: 15, name: "SMS Segment Calculator", slug: "sms-segment-calculator", category: "Communication Tools", isPro: false },
  { id: 16, name: "vCard Generator", slug: "vcard-generator", category: "Communication Tools", isPro: false },
  { id: 17, name: "Contact List Formatter", slug: "contact-list-formatter", category: "Communication Tools", isPro: false },
  { id: 18, name: "Contact Deduplicator", slug: "contact-deduplicator", category: "Communication Tools", isPro: false },
  { id: 19, name: "Email List Cleaner", slug: "email-list-cleaner", category: "Communication Tools", isPro: false },
  { id: 20, name: "Unified Communication Workspace", slug: "unified-communication-workspace", category: "Communication Tools", isPro: true },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "International Dialing Code Finder", slug: "international-dialing-code-finder", category: "Communication Tools", isPro: false },
  { id: 22, name: "Country Calling Code Lookup", slug: "country-calling-code-lookup", category: "Communication Tools", isPro: false },
  { id: 23, name: "Phone Number Format Checker", slug: "phone-number-format-checker", category: "Communication Tools", isPro: false },
  { id: 24, name: "Phone Number Type Checker", slug: "phone-number-type-checker", category: "Communication Tools", isPro: false },
  { id: 25, name: "Email Format Checker", slug: "email-format-checker", category: "Communication Tools", isPro: false },
  { id: 26, name: "Email Disposable Domain Checker", slug: "email-disposable-domain-checker", category: "Communication Tools", isPro: false },
  { id: 27, name: "Email Length Checker", slug: "email-length-checker", category: "Communication Tools", isPro: false },
  { id: 28, name: "Professional Email Signature Generator", slug: "professional-email-signature-generator", category: "Communication Tools", isPro: false },
  { id: 29, name: "Meeting Notes Template Generator", slug: "meeting-notes-template-generator", category: "Communication Tools", isPro: false },
  { id: 30, name: "Meeting Minutes Generator", slug: "meeting-minutes-generator", category: "Communication Tools", isPro: false },
  { id: 31, name: "Time Zone Meeting Finder", slug: "time-zone-meeting-finder", category: "Communication Tools", isPro: false },
  { id: 32, name: "Business Hours Finder", slug: "business-hours-finder", category: "Communication Tools", isPro: false },
  { id: 33, name: "Availability Message Generator", slug: "availability-message-generator", category: "Communication Tools", isPro: false },
  { id: 34, name: "Away Message Generator", slug: "away-message-generator", category: "Communication Tools", isPro: false },
  { id: 35, name: "Voicemail Script Generator", slug: "voicemail-script-generator", category: "Communication Tools", isPro: false },
  { id: 36, name: "Call Script Generator", slug: "call-script-generator", category: "Communication Tools", isPro: false },
  { id: 37, name: "Customer Service Script Generator", slug: "customer-service-script-generator", category: "Communication Tools", isPro: false },
  { id: 38, name: "Sales Call Script Generator", slug: "sales-call-script-generator", category: "Communication Tools", isPro: false },
  { id: 39, name: "Communication Tone Checker", slug: "communication-tone-checker", category: "Communication Tools", isPro: false },
  { id: 40, name: "Message Tone Converter", slug: "message-tone-converter", category: "Communication Tools", isPro: false },
  { id: 41, name: "Professional Message Generator", slug: "professional-message-generator", category: "Communication Tools", isPro: false },
  { id: 42, name: "Business Message Generator", slug: "business-message-generator", category: "Communication Tools", isPro: false },
  { id: 43, name: "Follow-Up Message Generator", slug: "follow-up-message-generator", category: "Communication Tools", isPro: false },
  { id: 44, name: "Appointment Reminder Generator", slug: "appointment-reminder-generator", category: "Communication Tools", isPro: false },
  { id: 45, name: "Meeting Reminder Generator", slug: "meeting-reminder-generator", category: "Communication Tools", isPro: false },
  { id: 46, name: "WhatsApp Message Character Counter", slug: "whatsapp-message-character-counter", category: "Communication Tools", isPro: false },
  { id: 47, name: "Social Message Character Counter", slug: "social-message-character-counter", category: "Communication Tools", isPro: false },
  { id: 48, name: "URL Message Preview Generator", slug: "url-message-preview-generator", category: "Communication Tools", isPro: false },
  { id: 49, name: "QR Code Message Generator", slug: "qr-code-message-generator", category: "Communication Tools", isPro: false },
  { id: 50, name: "QR Code Contact Generator", slug: "qr-code-contact-generator", category: "Communication Tools", isPro: false },
  { id: 51, name: "Contact Card Generator", slug: "contact-card-generator", category: "Communication Tools", isPro: false },
  { id: 52, name: "Contact CSV Cleaner", slug: "contact-csv-cleaner", category: "Communication Tools", isPro: false },
  { id: 53, name: "Contact CSV Formatter", slug: "contact-csv-formatter", category: "Communication Tools", isPro: false },
  { id: 54, name: "Phone Contact CSV Converter", slug: "phone-contact-csv-converter", category: "Communication Tools", isPro: false },
  { id: 55, name: "Email List Deduplicator", slug: "email-list-deduplicator", category: "Communication Tools", isPro: false },
  { id: 56, name: "Email List Formatter", slug: "email-list-formatter", category: "Communication Tools", isPro: false },
  { id: 57, name: "Communication Checklist Generator", slug: "communication-checklist-generator", category: "Communication Tools", isPro: false },
  { id: 58, name: "Call Log Generator", slug: "call-log-generator", category: "Communication Tools", isPro: false },
  { id: 59, name: "Communication Log Organizer", slug: "communication-log-organizer", category: "Communication Tools", isPro: false },
  { id: 60, name: "Conversation Notes Organizer", slug: "conversation-notes-organizer", category: "Communication Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Contact Notes Organizer", slug: "contact-notes-organizer", category: "Communication Tools", isPro: true },
  { id: 62, name: "Communication Report Generator", slug: "communication-report-generator", category: "Communication Tools", isPro: true },
  { id: 63, name: "Contact Management Workspace", slug: "contact-management-workspace", category: "Communication Tools", isPro: true },
  { id: 64, name: "Global Contact Database", slug: "global-contact-database", category: "Communication Tools", isPro: true },
  { id: 65, name: "Communication History Dashboard", slug: "communication-history-dashboard", category: "Communication Tools", isPro: true },
  { id: 66, name: "Customer Communication Workspace", slug: "customer-communication-workspace", category: "Communication Tools", isPro: true },
  { id: 67, name: "Sales Communication Workspace", slug: "sales-communication-workspace", category: "Communication Tools", isPro: true },
  { id: 68, name: "Client Communication Workspace", slug: "client-communication-workspace", category: "Communication Tools", isPro: true },
  { id: 69, name: "Team Communication Workspace", slug: "team-communication-workspace", category: "Communication Tools", isPro: true },
  { id: 70, name: "Remote Team Communication Hub", slug: "remote-team-communication-hub", category: "Communication Tools", isPro: true },
  { id: 71, name: "Meeting Management Workspace", slug: "meeting-management-workspace", category: "Communication Tools", isPro: true },
  { id: 72, name: "Meeting Notes Intelligence Workspace", slug: "meeting-notes-intelligence-workspace", category: "Communication Tools", isPro: true },
  { id: 73, name: "Meeting Action Item Tracker", slug: "meeting-action-item-tracker", category: "Communication Tools", isPro: true },
  { id: 74, name: "Meeting Follow-Up Manager", slug: "meeting-follow-up-manager", category: "Communication Tools", isPro: true },
  { id: 75, name: "International Meeting Scheduler", slug: "international-meeting-scheduler", category: "Communication Tools", isPro: true },
  { id: 76, name: "Availability Coordination Engine", slug: "availability-coordination-engine", category: "Communication Tools", isPro: true },
  { id: 77, name: "Business Hours Intelligence", slug: "business-hours-intelligence", category: "Communication Tools", isPro: true },
  { id: 78, name: "Contact Data Cleaning Engine", slug: "contact-data-cleaning-engine", category: "Communication Tools", isPro: true },
  { id: 79, name: "Contact Deduplication Engine", slug: "contact-deduplication-engine", category: "Communication Tools", isPro: true },
  { id: 80, name: "Contact Enrichment Workspace", slug: "contact-enrichment-workspace", category: "Communication Tools", isPro: true },
  { id: 81, name: "Communication CRM Workspace", slug: "communication-crm-workspace", category: "Communication Tools", isPro: true },
  { id: 82, name: "Customer Interaction Dashboard", slug: "customer-interaction-dashboard", category: "Communication Tools", isPro: true },
  { id: 83, name: "Call Analytics Dashboard", slug: "call-analytics-dashboard", category: "Communication Tools", isPro: true },
  { id: 84, name: "Message Analytics Dashboard", slug: "message-analytics-dashboard", category: "Communication Tools", isPro: true },
  { id: 85, name: "Communication Performance Dashboard", slug: "communication-performance-dashboard", category: "Communication Tools", isPro: true },
  { id: 86, name: "Customer Response Time Analyzer", slug: "customer-response-time-analyzer", category: "Communication Tools", isPro: true },
  { id: 87, name: "Contact Import Workspace", slug: "contact-import-workspace", category: "Communication Tools", isPro: true },
  { id: 88, name: "Contact Export Workspace", slug: "contact-export-workspace", category: "Communication Tools", isPro: true },
  { id: 89, name: "Communication Data Importer", slug: "communication-data-importer", category: "Communication Tools", isPro: true },
  { id: 90, name: "Communication Data Exporter", slug: "communication-data-exporter", category: "Communication Tools", isPro: true },
  { id: 91, name: "Communication API Workspace", slug: "communication-api-workspace", category: "Communication Tools", isPro: true },
  { id: 92, name: "SMS Workflow Workspace", slug: "sms-workflow-workspace", category: "Communication Tools", isPro: true },
  { id: 93, name: "Email Communication Workflow", slug: "email-communication-workflow", category: "Communication Tools", isPro: true },
  { id: 94, name: "Customer Notification Workspace", slug: "customer-notification-workspace", category: "Communication Tools", isPro: true },
  { id: 95, name: "Communication Automation Engine", slug: "communication-automation-engine", category: "Communication Tools", isPro: true },
  { id: 96, name: "International Communication Workspace", slug: "international-communication-workspace", category: "Communication Tools", isPro: true },
  { id: 97, name: "Business Communication Intelligence", slug: "business-communication-intelligence", category: "Communication Tools", isPro: true },
  { id: 98, name: "Client Communication Platform", slug: "client-communication-platform", category: "Communication Tools", isPro: true },
  { id: 99, name: "Customer Communication Platform", slug: "customer-communication-platform", category: "Communication Tools", isPro: true },
  { id: 100, name: "Professional Communication Command Center", slug: "professional-communication-command-center", category: "Communication Tools", isPro: true }
];