export interface ComplianceGovernanceTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const complianceGovernanceToolsList: ComplianceGovernanceTool[] = [
  // --- 🔥 PRIORITY 20 FREE TOOLS (IDs 1-20 | isPro: false) ---
  { id: 1, name: "Compliance Gap Calculator", slug: "compliance-gap-calculator", category: "Compliance & Governance Tools", isPro: false },
  { id: 2, name: "Compliance Readiness Score", slug: "compliance-readiness-score", category: "Compliance & Governance Tools", isPro: false },
  { id: 3, name: "Compliance Requirement Tracker", slug: "compliance-requirement-tracker", category: "Compliance & Governance Tools", isPro: false },
  { id: 4, name: "Audit Preparation Checklist", slug: "audit-preparation-checklist", category: "Compliance & Governance Tools", isPro: false },
  { id: 5, name: "Compliance Risk Calculator", slug: "compliance-risk-calculator", category: "Compliance & Governance Tools", isPro: false },
  { id: 6, name: "Compliance Evidence Tracker", slug: "compliance-evidence-tracker", category: "Compliance & Governance Tools", isPro: false },
  { id: 7, name: "Audit Finding Tracker", slug: "audit-finding-tracker", category: "Compliance & Governance Tools", isPro: false },
  { id: 8, name: "Remediation Tracker", slug: "remediation-tracker", category: "Compliance & Governance Tools", isPro: false },
  { id: 9, name: "Policy Checklist Generator", slug: "policy-checklist-generator", category: "Compliance & Governance Tools", isPro: false },
  { id: 10, name: "Control Checklist Generator", slug: "control-checklist-generator", category: "Compliance & Governance Tools", isPro: false },
  { id: 11, name: "Regulatory Requirement Tracker", slug: "regulatory-requirement-tracker", category: "Compliance & Governance Tools", isPro: false },
  { id: 12, name: "Compliance Deadline Tracker", slug: "compliance-deadline-tracker", category: "Compliance & Governance Tools", isPro: false },
  { id: 13, name: "Audit Evidence Checklist", slug: "audit-evidence-checklist", category: "Compliance & Governance Tools", isPro: false },
  { id: 14, name: "Control Testing Checklist", slug: "control-testing-checklist", category: "Compliance & Governance Tools", isPro: false },
  { id: 15, name: "Governance Risk Matrix", slug: "governance-risk-matrix", category: "Compliance & Governance Tools", isPro: false },
  { id: 16, name: "Third-Party Compliance Checklist", slug: "third-party-compliance-checklist", category: "Compliance & Governance Tools", isPro: false },
  { id: 17, name: "Vendor Compliance Checklist", slug: "vendor-compliance-checklist", category: "Compliance & Governance Tools", isPro: false },
  { id: 18, name: "Compliance Checklist Builder", slug: "compliance-checklist-builder", category: "Compliance & Governance Tools", isPro: false },
  { id: 19, name: "Risk Acceptance Tracker", slug: "risk-acceptance-tracker", category: "Compliance & Governance Tools", isPro: false },
  { id: 20, name: "Corrective Action Tracker", slug: "corrective-action-tracker", category: "Compliance & Governance Tools", isPro: false },

  // --- REMAINING 40 CORE FREE TOOLS (IDs 21-60 | isPro: false) ---
  { id: 21, name: "Policy Review Tracker", slug: "policy-review-tracker", category: "Compliance & Governance Tools", isPro: false },
  { id: 22, name: "Policy Expiry Tracker", slug: "policy-expiry-tracker", category: "Compliance & Governance Tools", isPro: false },
  { id: 23, name: "Policy Approval Tracker", slug: "policy-approval-tracker", category: "Compliance & Governance Tools", isPro: false },
  { id: 24, name: "Compliance Training Tracker", slug: "compliance-training-tracker", category: "Compliance & Governance Tools", isPro: false },
  { id: 25, name: "Compliance Certification Tracker", slug: "compliance-certification-tracker", category: "Compliance & Governance Tools", isPro: false },
  { id: 26, name: "Employee Attestation Tracker", slug: "employee-attestation-tracker", category: "Compliance & Governance Tools", isPro: false },
  { id: 27, name: "Compliance Questionnaire Builder", slug: "compliance-questionnaire-builder", category: "Compliance & Governance Tools", isPro: false },
  { id: 28, name: "Compliance Issue Tracker", slug: "compliance-issue-tracker", category: "Compliance & Governance Tools", isPro: false },
  { id: 29, name: "Compliance Exception Tracker", slug: "compliance-exception-tracker", category: "Compliance & Governance Tools", isPro: false },
  { id: 30, name: "Compliance Decision Log", slug: "compliance-decision-log", category: "Compliance & Governance Tools", isPro: false },
  { id: 31, name: "Compliance Meeting Planner", slug: "compliance-meeting-planner", category: "Compliance & Governance Tools", isPro: false },
  { id: 32, name: "Compliance Calendar", slug: "compliance-calendar", category: "Compliance & Governance Tools", isPro: false },
  { id: 33, name: "Audit Timeline Planner", slug: "audit-timeline-planner", category: "Compliance & Governance Tools", isPro: false },
  { id: 34, name: "Compliance Project Planner", slug: "compliance-project-planner", category: "Compliance & Governance Tools", isPro: false },
  { id: 35, name: "Compliance Responsibility Matrix", slug: "compliance-responsibility-matrix", category: "Compliance & Governance Tools", isPro: false },
  { id: 36, name: "Compliance Ownership Matrix", slug: "compliance-ownership-matrix", category: "Compliance & Governance Tools", isPro: false },
  { id: 37, name: "Control Owner Tracker", slug: "control-owner-tracker", category: "Compliance & Governance Tools", isPro: false },
  { id: 38, name: "Evidence Request Generator", slug: "evidence-request-generator", category: "Compliance & Governance Tools", isPro: false },
  { id: 39, name: "Audit Request Tracker", slug: "audit-request-tracker", category: "Compliance & Governance Tools", isPro: false },
  { id: 40, name: "Compliance Documentation Checklist", slug: "compliance-documentation-checklist", category: "Compliance & Governance Tools", isPro: false },
  { id: 41, name: "Compliance Report Generator", slug: "compliance-report-generator", category: "Compliance & Governance Tools", isPro: false },
  { id: 42, name: "Audit Summary Generator", slug: "audit-summary-generator", category: "Compliance & Governance Tools", isPro: false },
  { id: 43, name: "Compliance Summary Generator", slug: "compliance-summary-generator", category: "Compliance & Governance Tools", isPro: false },
  { id: 44, name: "Risk Summary Generator", slug: "risk-summary-generator", category: "Compliance & Governance Tools", isPro: false },
  { id: 45, name: "Control Effectiveness Calculator", slug: "control-effectiveness-calculator", category: "Compliance & Governance Tools", isPro: false },
  { id: 46, name: "Compliance Coverage Calculator", slug: "compliance-coverage-calculator", category: "Compliance & Governance Tools", isPro: false },
  { id: 47, name: "Audit Completion Calculator", slug: "audit-completion-calculator", category: "Compliance & Governance Tools", isPro: false },
  { id: 48, name: "Remediation Aging Calculator", slug: "remediation-aging-calculator", category: "Compliance & Governance Tools", isPro: false },
  { id: 49, name: "Compliance KPI Generator", slug: "compliance-kpi-generator", category: "Compliance & Governance Tools", isPro: false },
  { id: 50, name: "Compliance Dashboard Template", slug: "compliance-dashboard-template", category: "Compliance & Governance Tools", isPro: false },
  { id: 51, name: "Governance Checklist", slug: "governance-checklist", category: "Compliance & Governance Tools", isPro: false },
  { id: 52, name: "Board Governance Checklist", slug: "board-governance-checklist", category: "Compliance & Governance Tools", isPro: false },
  { id: 53, name: "Risk Committee Checklist", slug: "risk-committee-checklist", category: "Compliance & Governance Tools", isPro: false },
  { id: 54, name: "Policy Governance Checklist", slug: "policy-governance-checklist", category: "Compliance & Governance Tools", isPro: false },
  { id: 55, name: "Compliance SOP Generator", slug: "compliance-sop-generator", category: "Compliance & Governance Tools", isPro: false },
  { id: 56, name: "Audit SOP Generator", slug: "audit-sop-generator", category: "Compliance & Governance Tools", isPro: false },
  { id: 57, name: "Compliance Training Checklist", slug: "compliance-training-checklist", category: "Compliance & Governance Tools", isPro: false },
  { id: 58, name: "Compliance Communication Planner", slug: "compliance-communication-planner", category: "Compliance & Governance Tools", isPro: false },
  { id: 59, name: "Compliance Change Tracker", slug: "compliance-change-tracker", category: "Compliance & Governance Tools", isPro: false },
  { id: 60, name: "Governance Calendar", slug: "governance-calendar", category: "Compliance & Governance Tools", isPro: false },

  // --- ⚡ 40 PRO / SAAS TOOLS (IDs 61-100 | isPro: true) ---
  { id: 61, name: "Compliance Monitoring Dashboard", slug: "compliance-monitoring-dashboard", category: "Compliance & Governance Tools", isPro: true },
  { id: 62, name: "Compliance Management Workspace", slug: "compliance-management-workspace", category: "Compliance & Governance Tools", isPro: true },
  { id: 63, name: "Governance Management Workspace", slug: "governance-management-workspace", category: "Compliance & Governance Tools", isPro: true },
  { id: 64, name: "Regulatory Intelligence Workspace", slug: "regulatory-intelligence-workspace", category: "Compliance & Governance Tools", isPro: true },
  { id: 65, name: "Compliance Risk Dashboard", slug: "compliance-risk-dashboard", category: "Compliance & Governance Tools", isPro: true },
  { id: 66, name: "Control Management Workspace", slug: "control-management-workspace", category: "Compliance & Governance Tools", isPro: true },
  { id: 67, name: "Policy Management Workspace", slug: "policy-management-workspace", category: "Compliance & Governance Tools", isPro: true },
  { id: 68, name: "Audit Management Workspace", slug: "audit-management-workspace", category: "Compliance & Governance Tools", isPro: true },
  { id: 69, name: "Evidence Management Workspace", slug: "evidence-management-workspace", category: "Compliance & Governance Tools", isPro: true },
  { id: 70, name: "Remediation Management Workspace", slug: "remediation-management-workspace", category: "Compliance & Governance Tools", isPro: true },
  { id: 71, name: "Corrective Action Workspace", slug: "corrective-action-workspace", category: "Compliance & Governance Tools", isPro: true },
  { id: 72, name: "Regulatory Change Monitoring", slug: "regulatory-change-monitoring", category: "Compliance & Governance Tools", isPro: true },
  { id: 73, name: "Compliance Obligation Tracker", slug: "compliance-obligation-tracker", category: "Compliance & Governance Tools", isPro: true },
  { id: 74, name: "Control Testing Workspace", slug: "control-testing-workspace", category: "Compliance & Governance Tools", isPro: true },
  { id: 75, name: "Compliance Assessment Workspace", slug: "compliance-assessment-workspace", category: "Compliance & Governance Tools", isPro: true },
  { id: 76, name: "Third-Party Compliance Workspace", slug: "third-party-compliance-workspace", category: "Compliance & Governance Tools", isPro: true },
  { id: 77, name: "Vendor Compliance Dashboard", slug: "vendor-compliance-dashboard", category: "Compliance & Governance Tools", isPro: true },
  { id: 78, name: "Compliance Training Dashboard", slug: "compliance-training-dashboard", category: "Compliance & Governance Tools", isPro: true },
  { id: 79, name: "Employee Attestation Workspace", slug: "employee-attestation-workspace", category: "Compliance & Governance Tools", isPro: true },
  { id: 80, name: "Compliance Certification Management", slug: "compliance-certification-management", category: "Compliance & Governance Tools", isPro: true },
  { id: 81, name: "Risk Acceptance Workspace", slug: "risk-acceptance-workspace", category: "Compliance & Governance Tools", isPro: true },
  { id: 82, name: "Exception Management Workspace", slug: "exception-management-workspace", category: "Compliance & Governance Tools", isPro: true },
  { id: 83, name: "Governance Reporting Workspace", slug: "governance-reporting-workspace", category: "Compliance & Governance Tools", isPro: true },
  { id: 84, name: "Compliance Reporting Engine", slug: "compliance-reporting-engine", category: "Compliance & Governance Tools", isPro: true },
  { id: 85, name: "Audit Reporting Workspace", slug: "audit-reporting-workspace", category: "Compliance & Governance Tools", isPro: true },
  { id: 86, name: "Compliance Analytics", slug: "compliance-analytics", category: "Compliance & Governance Tools", isPro: true },
  { id: 87, name: "Governance Analytics", slug: "governance-analytics", category: "Compliance & Governance Tools", isPro: true },
  { id: 88, name: "Compliance Automation Workspace", slug: "compliance-automation-workspace", category: "Compliance & Governance Tools", isPro: true },
  { id: 89, name: "Compliance Alert Engine", slug: "compliance-alert-engine", category: "Compliance & Governance Tools", isPro: true },
  { id: 90, name: "Regulatory Deadline Engine", slug: "regulatory-deadline-engine", category: "Compliance & Governance Tools", isPro: true },
  { id: 91, name: "Compliance Data Import Workspace", slug: "compliance-data-import-workspace", category: "Compliance & Governance Tools", isPro: true },
  { id: 92, name: "Compliance Data Export Workspace", slug: "compliance-data-export-workspace", category: "Compliance & Governance Tools", isPro: true },
  { id: 93, name: "Compliance API", slug: "compliance-api", category: "Compliance & Governance Tools", isPro: true },
  { id: 94, name: "Compliance Knowledge Base", slug: "compliance-knowledge-base", category: "Compliance & Governance Tools", isPro: true },
  { id: 95, name: "Enterprise Governance Platform", slug: "enterprise-governance-platform", category: "Compliance & Governance Tools", isPro: true },
  { id: 96, name: "Enterprise Compliance Platform", slug: "enterprise-compliance-platform", category: "Compliance & Governance Tools", isPro: true },
  { id: 97, name: "Regulatory Intelligence Platform", slug: "regulatory-intelligence-platform", category: "Compliance & Governance Tools", isPro: true },
  { id: 98, name: "Governance Intelligence Platform", slug: "governance-intelligence-platform", category: "Compliance & Governance Tools", isPro: true },
  { id: 99, name: "Compliance Command Center", slug: "compliance-command-center", category: "Compliance & Governance Tools", isPro: true },
  { id: 100, name: "Enterprise GRC Workspace", slug: "enterprise-grc-workspace", category: "Compliance & Governance Tools", isPro: true }
];