export interface ConstructionTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const constructionToolsList: ConstructionTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "Construction Cost Calculator", slug: "construction-cost-calculator", category: "Construction Tools", isPro: false },
  { id: 2, name: "House Construction Cost Calculator", slug: "house-construction-cost-calculator", category: "Construction Tools", isPro: false },
  { id: 3, name: "Concrete Calculator", slug: "concrete-calculator", category: "Construction Tools", isPro: false },
  { id: 4, name: "Cement Calculator", slug: "cement-calculator", category: "Construction Tools", isPro: false },
  { id: 5, name: "Rebar Calculator", slug: "rebar-calculator", category: "Construction Tools", isPro: false },
  { id: 6, name: "Steel Weight Calculator", slug: "steel-weight-calculator", category: "Construction Tools", isPro: false },
  { id: 7, name: "Brick Calculator", slug: "brick-calculator", category: "Construction Tools", isPro: false },
  { id: 8, name: "Block Calculator", slug: "block-calculator", category: "Construction Tools", isPro: false },
  { id: 9, name: "Slab Concrete Calculator", slug: "slab-concrete-calculator", category: "Construction Tools", isPro: false },
  { id: 10, name: "Foundation Concrete Calculator", slug: "foundation-concrete-calculator", category: "Construction Tools", isPro: false },
  { id: 11, name: "Excavation Volume Calculator", slug: "excavation-volume-calculator", category: "Construction Tools", isPro: false },
  { id: 12, name: "Paint Quantity Calculator", slug: "paint-quantity-calculator", category: "Construction Tools", isPro: false },
  { id: 13, name: "Tile Quantity Calculator", slug: "tile-quantity-calculator", category: "Construction Tools", isPro: false },
  { id: 14, name: "Roofing Material Calculator", slug: "roofing-material-calculator", category: "Construction Tools", isPro: false },
  { id: 15, name: "Material Cost Calculator", slug: "material-cost-calculator", category: "Construction Tools", isPro: false },
  { id: 16, name: "Labor Cost Calculator", slug: "labor-cost-calculator", category: "Construction Tools", isPro: false },
  { id: 17, name: "Construction Budget Calculator", slug: "construction-budget-calculator", category: "Construction Tools", isPro: false },
  { id: 18, name: "Contractor Markup Calculator", slug: "contractor-markup-calculator", category: "Construction Tools", isPro: false },
  { id: 19, name: "Construction Estimate Generator", slug: "construction-estimate-generator", category: "Construction Tools", isPro: false },
  { id: 20, name: "Building Cost Calculator", slug: "building-cost-calculator", category: "Construction Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Construction Material Calculator", slug: "construction-material-calculator", category: "Construction Tools", isPro: false },
  { id: 22, name: "Sand Calculator", slug: "sand-calculator", category: "Construction Tools", isPro: false },
  { id: 23, name: "Aggregate Calculator", slug: "aggregate-calculator", category: "Construction Tools", isPro: false },
  { id: 24, name: "Gravel Calculator", slug: "gravel-calculator", category: "Construction Tools", isPro: false },
  { id: 25, name: "Mortar Calculator", slug: "mortar-calculator", category: "Construction Tools", isPro: false },
  { id: 26, name: "AAC Block Calculator", slug: "aac-block-calculator", category: "Construction Tools", isPro: false },
  { id: 27, name: "Reinforcement Calculator", slug: "reinforcement-calculator", category: "Construction Tools", isPro: false },
  { id: 28, name: "Beam Concrete Calculator", slug: "beam-concrete-calculator", category: "Construction Tools", isPro: false },
  { id: 29, name: "Column Concrete Calculator", slug: "column-concrete-calculator", category: "Construction Tools", isPro: false },
  { id: 30, name: "Footing Concrete Calculator", slug: "footing-concrete-calculator", category: "Construction Tools", isPro: false },
  { id: 31, name: "Wall Concrete Calculator", slug: "wall-concrete-calculator", category: "Construction Tools", isPro: false },
  { id: 32, name: "Floor Concrete Calculator", slug: "floor-concrete-calculator", category: "Construction Tools", isPro: false },
  { id: 33, name: "Staircase Concrete Calculator", slug: "staircase-concrete-calculator", category: "Construction Tools", isPro: false },
  { id: 34, name: "Asphalt Calculator", slug: "asphalt-calculator", category: "Construction Tools", isPro: false },
  { id: 35, name: "Backfill Calculator", slug: "backfill-calculator", category: "Construction Tools", isPro: false },
  { id: 36, name: "Earthwork Calculator", slug: "earthwork-calculator", category: "Construction Tools", isPro: false },
  { id: 37, name: "Soil Volume Calculator", slug: "soil-volume-calculator", category: "Construction Tools", isPro: false },
  { id: 38, name: "Fill Material Calculator", slug: "fill-material-calculator", category: "Construction Tools", isPro: false },
  { id: 39, name: "Area Calculator", slug: "area-calculator", category: "Construction Tools", isPro: false },
  { id: 40, name: "Wall Area Calculator", slug: "wall-area-calculator", category: "Construction Tools", isPro: false },
  { id: 41, name: "Floor Area Calculator", slug: "floor-area-calculator", category: "Construction Tools", isPro: false },
  { id: 42, name: "Roof Area Calculator", slug: "roof-area-calculator", category: "Construction Tools", isPro: false },
  { id: 43, name: "Flooring Material Calculator", slug: "flooring-material-calculator", category: "Construction Tools", isPro: false },
  { id: 44, name: "Wallpaper Calculator", slug: "wallpaper-calculator", category: "Construction Tools", isPro: false },
  { id: 45, name: "Insulation Calculator", slug: "insulation-calculator", category: "Construction Tools", isPro: false },
  { id: 46, name: "Drywall Calculator", slug: "drywall-calculator", category: "Construction Tools", isPro: false },
  { id: 47, name: "Roofing Cost Calculator", slug: "roofing-cost-calculator", category: "Construction Tools", isPro: false },
  { id: 48, name: "Window Quantity Calculator", slug: "window-quantity-calculator", category: "Construction Tools", isPro: false },
  { id: 49, name: "Door Quantity Calculator", slug: "door-quantity-calculator", category: "Construction Tools", isPro: false },
  { id: 50, name: "Construction Waste Calculator", slug: "construction-waste-calculator", category: "Construction Tools", isPro: false },
  { id: 51, name: "Construction Labor Hour Calculator", slug: "construction-labor-hour-calculator", category: "Construction Tools", isPro: false },
  { id: 52, name: "Equipment Cost Calculator", slug: "equipment-cost-calculator", category: "Construction Tools", isPro: false },
  { id: 53, name: "Equipment Rental Cost Calculator", slug: "equipment-rental-cost-calculator", category: "Construction Tools", isPro: false },
  { id: 54, name: "Project Duration Calculator", slug: "project-duration-calculator", category: "Construction Tools", isPro: false },
  { id: 55, name: "Construction Schedule Calculator", slug: "construction-schedule-calculator", category: "Construction Tools", isPro: false },
  { id: 56, name: "Contractor Profit Calculator", slug: "contractor-profit-calculator", category: "Construction Tools", isPro: false },
  { id: 57, name: "Construction Contingency Calculator", slug: "construction-contingency-calculator", category: "Construction Tools", isPro: false },
  { id: 58, name: "Construction Payment Calculator", slug: "construction-payment-calculator", category: "Construction Tools", isPro: false },
  { id: 59, name: "Progress Payment Calculator", slug: "progress-payment-calculator", category: "Construction Tools", isPro: false },
  { id: 60, name: "Retention Calculator", slug: "retention-calculator", category: "Construction Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Detailed Quantity Takeoff Engine", slug: "detailed-quantity-takeoff-engine", category: "Construction Tools", isPro: true },
  { id: 62, name: "Construction Project Cost Estimator", slug: "construction-project-cost-estimator", category: "Construction Tools", isPro: true },
  { id: 63, name: "BOQ Generator", slug: "boq-generator", category: "Construction Tools", isPro: true },
  { id: 64, name: "Construction Cost Database", slug: "construction-cost-database", category: "Construction Tools", isPro: true },
  { id: 65, name: "Material Price Tracker", slug: "material-price-tracker", category: "Construction Tools", isPro: true },
  { id: 66, name: "Labor Rate Database", slug: "labor-rate-database", category: "Construction Tools", isPro: true },
  { id: 67, name: "Construction Budget Planner", slug: "construction-budget-planner", category: "Construction Tools", isPro: true },
  { id: 68, name: "Project Cost Forecast", slug: "project-cost-forecast", category: "Construction Tools", isPro: true },
  { id: 69, name: "Cost Variance Analyzer", slug: "cost-variance-analyzer", category: "Construction Tools", isPro: true },
  { id: 70, name: "Schedule Variance Analyzer", slug: "schedule-variance-analyzer", category: "Construction Tools", isPro: true },
  { id: 71, name: "Construction Cash Flow Planner", slug: "construction-cash-flow-planner", category: "Construction Tools", isPro: true },
  { id: 72, name: "Contractor Profitability Analyzer", slug: "contractor-profitability-analyzer", category: "Construction Tools", isPro: true },
  { id: 73, name: "Project Profitability Analyzer", slug: "project-profitability-analyzer", category: "Construction Tools", isPro: true },
  { id: 74, name: "Change Order Cost Analyzer", slug: "change-order-cost-analyzer", category: "Construction Tools", isPro: true },
  { id: 75, name: "Change Order Tracker", slug: "change-order-tracker", category: "Construction Tools", isPro: true },
  { id: 76, name: "Construction Risk Analyzer", slug: "construction-risk-analyzer", category: "Construction Tools", isPro: true },
  { id: 77, name: "Construction Contingency Planner", slug: "construction-contingency-planner", category: "Construction Tools", isPro: true },
  { id: 78, name: "Resource Allocation Planner", slug: "resource-allocation-planner", category: "Construction Tools", isPro: true },
  { id: 79, name: "Equipment Utilization Analyzer", slug: "equipment-utilization-analyzer", category: "Construction Tools", isPro: true },
  { id: 80, name: "Equipment Replacement Planner", slug: "equipment-replacement-planner", category: "Construction Tools", isPro: true },
  { id: 81, name: "Construction Procurement Planner", slug: "construction-procurement-planner", category: "Construction Tools", isPro: true },
  { id: 82, name: "Material Procurement Tracker", slug: "material-procurement-tracker", category: "Construction Tools", isPro: true },
  { id: 83, name: "Construction Inventory Dashboard", slug: "construction-inventory-dashboard", category: "Construction Tools", isPro: true },
  { id: 84, name: "Subcontractor Cost Analyzer", slug: "subcontractor-cost-analyzer", category: "Construction Tools", isPro: true },
  { id: 85, name: "Subcontractor Comparison Workspace", slug: "subcontractor-comparison-workspace", category: "Construction Tools", isPro: true },
  { id: 86, name: "Construction Payment Tracker", slug: "construction-payment-tracker", category: "Construction Tools", isPro: true },
  { id: 87, name: "Retention Management Workspace", slug: "retention-management-workspace", category: "Construction Tools", isPro: true },
  { id: 88, name: "Construction Progress Dashboard", slug: "construction-progress-dashboard", category: "Construction Tools", isPro: true },
  { id: 89, name: "Site Productivity Analyzer", slug: "site-productivity-analyzer", category: "Construction Tools", isPro: true },
  { id: 90, name: "Construction Labor Productivity Analyzer", slug: "construction-labor-productivity-analyzer", category: "Construction Tools", isPro: true },
  { id: 91, name: "Project Scheduling Workspace", slug: "project-scheduling-workspace", category: "Construction Tools", isPro: true },
  { id: 92, name: "Construction Document Workspace", slug: "construction-document-workspace", category: "Construction Tools", isPro: true },
  { id: 93, name: "Contractor Management Workspace", slug: "contractor-management-workspace", category: "Construction Tools", isPro: true },
  { id: 94, name: "Construction Estimating Workspace", slug: "construction-estimating-workspace", category: "Construction Tools", isPro: true },
  { id: 95, name: "Construction Project Command Center", slug: "construction-project-command-center", category: "Construction Tools", isPro: true },
  { id: 96, name: "Quantity Surveyor Workspace", slug: "quantity-surveyor-workspace", category: "Construction Tools", isPro: true },
  { id: 97, name: "Cost Control Intelligence Platform", slug: "cost-control-intelligence-platform", category: "Construction Tools", isPro: true },
  { id: 98, name: "Construction Business Dashboard", slug: "construction-business-dashboard", category: "Construction Tools", isPro: true },
  { id: 99, name: "Construction Operations Platform", slug: "construction-operations-platform", category: "Construction Tools", isPro: true },
  { id: 100, name: "Construction Project Intelligence Workspace", slug: "construction-project-intelligence-workspace", category: "Construction Tools", isPro: true }
];