export interface CryptoTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const cryptoToolsList: CryptoTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "Crypto Profit Calculator", slug: "crypto-profit-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 2, name: "Crypto ROI Calculator", slug: "crypto-roi-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 3, name: "Crypto DCA Calculator", slug: "crypto-dca-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 4, name: "Average Buy Price Calculator", slug: "average-buy-price-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 5, name: "Break-Even Price Calculator", slug: "break-even-price-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 6, name: "Position Size Calculator", slug: "position-size-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 7, name: "Trading Fee Calculator", slug: "trading-fee-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 8, name: "Gas Fee Calculator", slug: "gas-fee-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 9, name: "Slippage Calculator", slug: "slippage-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 10, name: "Crypto Market Cap Calculator", slug: "crypto-market-cap-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 11, name: "Token Supply Calculator", slug: "token-supply-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 12, name: "Token Vesting Calculator", slug: "token-vesting-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 13, name: "Staking Rewards Calculator", slug: "staking-rewards-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 14, name: "Crypto Mining Profit Calculator", slug: "crypto-mining-profit-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 15, name: "Crypto Tax Calculator", slug: "crypto-tax-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 16, name: "Crypto Capital Gains Calculator", slug: "crypto-capital-gains-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 17, name: "Crypto Cost Basis Calculator", slug: "crypto-cost-basis-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 18, name: "Wallet Address Validator", slug: "wallet-address-validator", category: "Cryptocurrency Tools", isPro: false },
  { id: 19, name: "Crypto Portfolio Tracker", slug: "crypto-portfolio-tracker", category: "Cryptocurrency Tools", isPro: false },
  { id: 20, name: "Crypto Price Converter", slug: "crypto-price-converter", category: "Cryptocurrency Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Crypto Currency Converter", slug: "crypto-currency-converter", category: "Cryptocurrency Tools", isPro: false },
  { id: 22, name: "Crypto Loss Calculator", slug: "crypto-loss-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 23, name: "Crypto Percentage Gain Calculator", slug: "crypto-percentage-gain-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 24, name: "Crypto Percentage Loss Calculator", slug: "crypto-percentage-loss-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 25, name: "Crypto Investment Calculator", slug: "crypto-investment-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 26, name: "Crypto DCA Planner", slug: "crypto-dca-planner", category: "Cryptocurrency Tools", isPro: false },
  { id: 27, name: "Crypto Compound Growth Calculator", slug: "crypto-compound-growth-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 28, name: "Crypto Risk-to-Reward Calculator", slug: "crypto-risk-to-reward-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 29, name: "Crypto Portfolio Calculator", slug: "crypto-portfolio-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 30, name: "Crypto Portfolio Allocation Calculator", slug: "crypto-portfolio-allocation-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 31, name: "Crypto Portfolio Rebalancing Calculator", slug: "crypto-portfolio-rebalancing-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 32, name: "Crypto Exchange Fee Calculator", slug: "crypto-exchange-fee-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 33, name: "Crypto Network Fee Calculator", slug: "crypto-network-fee-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 34, name: "Gas Fee Converter", slug: "gas-fee-converter", category: "Cryptocurrency Tools", isPro: false },
  { id: 35, name: "Crypto Transaction Cost Calculator", slug: "crypto-transaction-cost-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 36, name: "Crypto Withdrawal Fee Calculator", slug: "crypto-withdrawal-fee-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 37, name: "Crypto Deposit Fee Calculator", slug: "crypto-deposit-fee-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 38, name: "Crypto Slippage Impact Calculator", slug: "crypto-slippage-impact-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 39, name: "Crypto Fully Diluted Valuation Calculator", slug: "crypto-fully-diluted-valuation-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 40, name: "Token Price Calculator", slug: "token-price-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 41, name: "Token Allocation Calculator", slug: "token-allocation-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 42, name: "Token Unlock Calculator", slug: "token-unlock-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 43, name: "Crypto Staking Calculator", slug: "crypto-staking-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 44, name: "Staking APY Calculator", slug: "staking-apy-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 45, name: "Mining Electricity Cost Calculator", slug: "mining-electricity-cost-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 46, name: "Mining Break-Even Calculator", slug: "mining-break-even-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 47, name: "Hashrate Calculator", slug: "hashrate-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 48, name: "Crypto Tax-Loss Calculator", slug: "crypto-tax-loss-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 49, name: "Crypto Transaction Tracker", slug: "crypto-transaction-tracker", category: "Cryptocurrency Tools", isPro: false },
  { id: 50, name: "Crypto Wallet Balance Checker", slug: "crypto-wallet-balance-checker", category: "Cryptocurrency Tools", isPro: false },
  { id: 51, name: "Crypto Address Format Checker", slug: "crypto-address-format-checker", category: "Cryptocurrency Tools", isPro: false },
  { id: 52, name: "Transaction Hash Validator", slug: "transaction-hash-validator", category: "Cryptocurrency Tools", isPro: false },
  { id: 53, name: "Blockchain Transaction Explorer", slug: "blockchain-transaction-explorer", category: "Cryptocurrency Tools", isPro: false },
  { id: 54, name: "Token Contract Checker", slug: "token-contract-checker", category: "Cryptocurrency Tools", isPro: false },
  { id: 55, name: "Token Supply Checker", slug: "token-supply-checker", category: "Cryptocurrency Tools", isPro: false },
  { id: 56, name: "Crypto Price Alert Calculator", slug: "crypto-price-alert-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 57, name: "Crypto Volatility Calculator", slug: "crypto-volatility-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 58, name: "Crypto Drawdown Calculator", slug: "crypto-drawdown-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 59, name: "Crypto Risk Calculator", slug: "crypto-risk-calculator", category: "Cryptocurrency Tools", isPro: false },
  { id: 60, name: "Crypto Investment Checklist", slug: "crypto-investment-checklist", category: "Cryptocurrency Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Crypto Portfolio Intelligence Dashboard", slug: "crypto-portfolio-intelligence-dashboard", category: "Cryptocurrency Tools", isPro: true },
  { id: 62, name: "Multi-Wallet Portfolio Tracker", slug: "multi-wallet-portfolio-tracker", category: "Cryptocurrency Tools", isPro: true },
  { id: 63, name: "Multi-Exchange Portfolio Tracker", slug: "multi-exchange-portfolio-tracker", category: "Cryptocurrency Tools", isPro: true },
  { id: 64, name: "Portfolio Allocation Analyzer", slug: "portfolio-allocation-analyzer", category: "Cryptocurrency Tools", isPro: true },
  { id: 65, name: "Portfolio Rebalancing Engine", slug: "portfolio-rebalancing-engine", category: "Cryptocurrency Tools", isPro: true },
  { id: 66, name: "Crypto Tax Reporting Workspace", slug: "crypto-tax-reporting-workspace", category: "Cryptocurrency Tools", isPro: true },
  { id: 67, name: "Crypto Cost Basis Engine", slug: "crypto-cost-basis-engine", category: "Cryptocurrency Tools", isPro: true },
  { id: 68, name: "Crypto Transaction Classification Engine", slug: "crypto-transaction-classification-engine", category: "Cryptocurrency Tools", isPro: true },
  { id: 69, name: "Crypto Transaction Reconciliation", slug: "crypto-transaction-reconciliation", category: "Cryptocurrency Tools", isPro: true },
  { id: 70, name: "Crypto Capital Gains Analyzer", slug: "crypto-capital-gains-analyzer", category: "Cryptocurrency Tools", isPro: true },
  { id: 71, name: "DCA Strategy Analyzer", slug: "dca-strategy-analyzer", category: "Cryptocurrency Tools", isPro: true },
  { id: 72, name: "DCA Scenario Planner", slug: "dca-scenario-planner", category: "Cryptocurrency Tools", isPro: true },
  { id: 73, name: "Portfolio Risk Analyzer", slug: "portfolio-risk-analyzer", category: "Cryptocurrency Tools", isPro: true },
  { id: 74, name: "Portfolio Volatility Analyzer", slug: "portfolio-volatility-analyzer", category: "Cryptocurrency Tools", isPro: true },
  { id: 75, name: "Drawdown Risk Analyzer", slug: "drawdown-risk-analyzer", category: "Cryptocurrency Tools", isPro: true },
  { id: 76, name: "Crypto Correlation Analyzer", slug: "crypto-correlation-analyzer", category: "Cryptocurrency Tools", isPro: true },
  { id: 77, name: "Tokenomics Analyzer", slug: "tokenomics-analyzer", category: "Cryptocurrency Tools", isPro: true },
  { id: 78, name: "Token Unlock Risk Analyzer", slug: "token-unlock-risk-analyzer", category: "Cryptocurrency Tools", isPro: true },
  { id: 79, name: "Token Vesting Analyzer", slug: "token-vesting-analyzer", category: "Cryptocurrency Tools", isPro: true },
  { id: 80, name: "Staking Yield Analyzer", slug: "staking-yield-analyzer", category: "Cryptocurrency Tools", isPro: true },
  { id: 81, name: "Staking Risk Analyzer", slug: "staking-risk-analyzer", category: "Cryptocurrency Tools", isPro: true },
  { id: 82, name: "Mining Profitability Analyzer", slug: "mining-profitability-analyzer", category: "Cryptocurrency Tools", isPro: true },
  { id: 83, name: "Mining Hardware ROI Analyzer", slug: "mining-hardware-roi-analyzer", category: "Cryptocurrency Tools", isPro: true },
  { id: 84, name: "Network Fee Intelligence", slug: "network-fee-intelligence", category: "Cryptocurrency Tools", isPro: true },
  { id: 85, name: "Gas Fee Monitor", slug: "gas-fee-monitor", category: "Cryptocurrency Tools", isPro: true },
  { id: 86, name: "Exchange Fee Comparison Engine", slug: "exchange-fee-comparison-engine", category: "Cryptocurrency Tools", isPro: true },
  { id: 87, name: "Trading Cost Analyzer", slug: "trading-cost-analyzer", category: "Cryptocurrency Tools", isPro: true },
  { id: 88, name: "Slippage Risk Analyzer", slug: "slippage-risk-analyzer", category: "Cryptocurrency Tools", isPro: true },
  { id: 89, name: "Liquidity Analyzer", slug: "liquidity-analyzer", category: "Cryptocurrency Tools", isPro: true },
  { id: 90, name: "Crypto Market Intelligence Dashboard", slug: "crypto-market-intelligence-dashboard", category: "Cryptocurrency Tools", isPro: true },
  { id: 91, name: "Wallet Intelligence Workspace", slug: "wallet-intelligence-workspace", category: "Cryptocurrency Tools", isPro: true },
  { id: 92, name: "Crypto Tax Workspace", slug: "crypto-tax-workspace", category: "Cryptocurrency Tools", isPro: true },
  { id: 93, name: "Crypto Portfolio Workspace", slug: "crypto-portfolio-workspace", category: "Cryptocurrency Tools", isPro: true },
  { id: 94, name: "Digital Asset Accounting Workspace", slug: "digital-asset-accounting-workspace", category: "Cryptocurrency Tools", isPro: true },
  { id: 95, name: "Crypto Treasury Dashboard", slug: "crypto-treasury-dashboard", category: "Cryptocurrency Tools", isPro: true },
  { id: 96, name: "Crypto Compliance Workspace", slug: "crypto-compliance-workspace", category: "Cryptocurrency Tools", isPro: true },
  { id: 97, name: "Crypto Research Workspace", slug: "crypto-research-workspace", category: "Cryptocurrency Tools", isPro: true },
  { id: 98, name: "Digital Asset Intelligence Platform", slug: "digital-asset-intelligence-platform", category: "Cryptocurrency Tools", isPro: true },
  { id: 99, name: "Crypto Operations Command Center", slug: "crypto-operations-command-center", category: "Cryptocurrency Tools", isPro: true },
  { id: 100, name: "Professional Crypto Portfolio Intelligence", slug: "professional-crypto-portfolio-intelligence", category: "Cryptocurrency Tools", isPro: true }
];