export interface CustomerSupportTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const customerSupportToolsList: CustomerSupportTool[] = [
  // --- 🔥 PRIORITY 20 FREE TOOLS (IDs 1-20 | isPro: false) ---
  { id: 1, name: "Ticket SLA Calculator", slug: "ticket-sla-calculator", category: "Customer Support Tools", isPro: false },
  { id: 2, name: "First Response Time Calculator", slug: "first-response-time-calculator", category: "Customer Support Tools", isPro: false },
  { id: 3, name: "Resolution Time Calculator", slug: "resolution-time-calculator", category: "Customer Support Tools", isPro: false },
  { id: 4, name: "Support Staffing Calculator", slug: "support-staffing-calculator", category: "Customer Support Tools", isPro: false },
  { id: 5, name: "SLA Breach Calculator", slug: "sla-breach-calculator", category: "Customer Support Tools", isPro: false },
  { id: 6, name: "Support Ticket Priority Calculator", slug: "support-ticket-priority-calculator", category: "Customer Support Tools", isPro: false },
  { id: 7, name: "Escalation Matrix Builder", slug: "escalation-matrix-builder", category: "Customer Support Tools", isPro: false },
  { id: 8, name: "Support Capacity Calculator", slug: "support-capacity-calculator", category: "Customer Support Tools", isPro: false },
  { id: 9, name: "Average Handle Time Calculator", slug: "average-handle-time-calculator", category: "Customer Support Tools", isPro: false },
  { id: 10, name: "Agent Capacity Calculator", slug: "agent-capacity-calculator", category: "Customer Support Tools", isPro: false },
  { id: 11, name: "Ticket Volume Calculator", slug: "ticket-volume-calculator", category: "Customer Support Tools", isPro: false },
  { id: 12, name: "First Contact Resolution Calculator", slug: "first-contact-resolution-calculator", category: "Customer Support Tools", isPro: false },
  { id: 13, name: "Support CSAT Calculator", slug: "support-csat-calculator", category: "Customer Support Tools", isPro: false },
  { id: 14, name: "Support NPS Calculator", slug: "support-nps-calculator", category: "Customer Support Tools", isPro: false },
  { id: 15, name: "Cost Per Ticket Calculator", slug: "cost-per-ticket-calculator", category: "Customer Support Tools", isPro: false },
  { id: 16, name: "Support Macro Generator", slug: "support-macro-generator", category: "Customer Support Tools", isPro: false },
  { id: 17, name: "Support Canned Response Builder", slug: "support-canned-response-builder", category: "Customer Support Tools", isPro: false },
  { id: 18, name: "FAQ Generator", slug: "faq-generator-support", category: "Customer Support Tools", isPro: false },
  { id: 19, name: "Support Queue Calculator", slug: "support-queue-calculator", category: "Customer Support Tools", isPro: false },
  { id: 20, name: "Support KPI Generator", slug: "support-kpi-generator", category: "Customer Support Tools", isPro: false },

  // --- REMAINING 40 CORE FREE TOOLS (IDs 21-60 | isPro: false) ---
  { id: 21, name: "Backlog Calculator", slug: "backlog-calculator-support", category: "Customer Support Tools", isPro: false },
  { id: 22, name: "Backlog Aging Calculator", slug: "backlog-aging-calculator", category: "Customer Support Tools", isPro: false },
  { id: 23, name: "Support Coverage Calculator", slug: "support-coverage-calculator", category: "Customer Support Tools", isPro: false },
  { id: 24, name: "Support Priority Matrix", slug: "support-priority-matrix", category: "Customer Support Tools", isPro: false },
  { id: 25, name: "Support Triage Checklist", slug: "support-triage-checklist", category: "Customer Support Tools", isPro: false },
  { id: 26, name: "Support Ticket Classifier", slug: "support-ticket-classifier", category: "Customer Support Tools", isPro: false },
  { id: 27, name: "Support Category Builder", slug: "support-category-builder", category: "Customer Support Tools", isPro: false },
  { id: 28, name: "Support Tag Generator", slug: "support-tag-generator", category: "Customer Support Tools", isPro: false },
  { id: 29, name: "Support Response Template Builder", slug: "support-response-template-builder", category: "Customer Support Tools", isPro: false },
  { id: 30, name: "Help Center Article Outline", slug: "help-center-article-outline", category: "Customer Support Tools", isPro: false },
  { id: 31, name: "Knowledge Base Article Planner", slug: "knowledge-base-article-planner", category: "Customer Support Tools", isPro: false },
  { id: 32, name: "Troubleshooting Flow Builder", slug: "troubleshooting-flow-builder", category: "Customer Support Tools", isPro: false },
  { id: 33, name: "Support Decision Tree Builder", slug: "support-decision-tree-builder", category: "Customer Support Tools", isPro: false },
  { id: 34, name: "Escalation Workflow Builder", slug: "escalation-workflow-builder", category: "Customer Support Tools", isPro: false },
  { id: 35, name: "Support SOP Generator", slug: "support-sop-generator", category: "Customer Support Tools", isPro: false },
  { id: 36, name: "Support QA Checklist", slug: "support-qa-checklist", category: "Customer Support Tools", isPro: false },
  { id: 37, name: "Support Audit Checklist", slug: "support-audit-checklist", category: "Customer Support Tools", isPro: false },
  { id: 38, name: "Agent Onboarding Checklist", slug: "agent-onboarding-checklist-support", category: "Customer Support Tools", isPro: false },
  { id: 39, name: "Support Shift Planner", slug: "support-shift-planner", category: "Customer Support Tools", isPro: false },
  { id: 40, name: "Support Handoff Checklist", slug: "support-handoff-checklist", category: "Customer Support Tools", isPro: false },
  { id: 41, name: "Customer Escalation Form", slug: "customer-escalation-form", category: "Customer Support Tools", isPro: false },
  { id: 42, name: "Bug Report Template", slug: "bug-report-template-support", category: "Customer Support Tools", isPro: false },
  { id: 43, name: "Feature Request Template", slug: "feature-request-template-support", category: "Customer Support Tools", isPro: false },
  { id: 44, name: "Support Feedback Form", slug: "support-feedback-form", category: "Customer Support Tools", isPro: false },
  { id: 45, name: "Customer Complaint Tracker", slug: "customer-complaint-tracker", category: "Customer Support Tools", isPro: false },
  { id: 46, name: "Support Call Summary", slug: "support-call-summary", category: "Customer Support Tools", isPro: false },
  { id: 47, name: "Support Case Summary", slug: "support-case-summary", category: "Customer Support Tools", isPro: false },
  { id: 48, name: "Support Interaction Timeline", slug: "support-interaction-timeline", category: "Customer Support Tools", isPro: false },
  { id: 49, name: "Support Resolution Tracker", slug: "support-resolution-tracker", category: "Customer Support Tools", isPro: false },
  { id: 50, name: "Ticket Reopen Rate Calculator", slug: "ticket-reopen-rate-calculator", category: "Customer Support Tools", isPro: false },
  { id: 51, name: "Customer Effort Score Calculator", slug: "customer-effort-score-calculator", category: "Customer Support Tools", isPro: false },
  { id: 52, name: "Support Productivity Calculator", slug: "support-productivity-calculator", category: "Customer Support Tools", isPro: false },
  { id: 53, name: "Agent Performance Calculator", slug: "agent-performance-calculator", category: "Customer Support Tools", isPro: false },
  { id: 54, name: "Support Cost Calculator", slug: "support-cost-calculator", category: "Customer Support Tools", isPro: false },
  { id: 55, name: "Support Forecast Calculator", slug: "support-forecast-calculator", category: "Customer Support Tools", isPro: false },
  { id: 56, name: "Support Report Generator", slug: "support-report-generator", category: "Customer Support Tools", isPro: false },
  { id: 57, name: "Support Quality Report", slug: "support-quality-report", category: "Customer Support Tools", isPro: false },
  { id: 58, name: "Support Staffing Report", slug: "support-staffing-report", category: "Customer Support Tools", isPro: false },
  { id: 59, name: "Support Backlog Report", slug: "support-backlog-report", category: "Customer Support Tools", isPro: false },
  { id: 60, name: "Support Operations Checklist", slug: "support-operations-checklist", category: "Customer Support Tools", isPro: false },

  // --- ⚡ 40 PRO / SAAS TOOLS (IDs 61-100 | isPro: true) ---
  { id: 61, name: "Customer Support Workspace", slug: "customer-support-workspace", category: "Customer Support Tools", isPro: true },
  { id: 62, name: "Support Operations Dashboard", slug: "support-operations-dashboard", category: "Customer Support Tools", isPro: true },
  { id: 63, name: "Ticket Intelligence Workspace", slug: "ticket-intelligence-workspace", category: "Customer Support Tools", isPro: true },
  { id: 64, name: "Support Queue Management", slug: "support-queue-management", category: "Customer Support Tools", isPro: true },
  { id: 65, name: "SLA Management Workspace", slug: "sla-management-workspace", category: "Customer Support Tools", isPro: true },
  { id: 66, name: "Support Workforce Planner", slug: "support-workforce-planner", category: "Customer Support Tools", isPro: true },
  { id: 67, name: "Agent Performance Dashboard", slug: "agent-performance-dashboard", category: "Customer Support Tools", isPro: true },
  { id: 68, name: "Support Quality Dashboard", slug: "support-quality-dashboard", category: "Customer Support Tools", isPro: true },
  { id: 69, name: "Support Capacity Planning", slug: "support-capacity-planning", category: "Customer Support Tools", isPro: true },
  { id: 70, name: "Support Forecasting Workspace", slug: "support-forecasting-workspace", category: "Customer Support Tools", isPro: true },
  { id: 71, name: "Support Knowledge Base Manager", slug: "support-knowledge-base-manager", category: "Customer Support Tools", isPro: true },
  { id: 72, name: "Help Center Management", slug: "help-center-management", category: "Customer Support Tools", isPro: true },
  { id: 73, name: "Troubleshooting Knowledge Workspace", slug: "troubleshooting-knowledge-workspace", category: "Customer Support Tools", isPro: true },
  { id: 74, name: "Support Macro Management", slug: "support-macro-management", category: "Customer Support Tools", isPro: true },
  { id: 75, name: "Escalation Management Workspace", slug: "escalation-management-workspace", category: "Customer Support Tools", isPro: true },
  { id: 76, name: "Support Case Management", slug: "support-case-management", category: "Customer Support Tools", isPro: true },
  { id: 77, name: "Support Interaction Intelligence", slug: "support-interaction-intelligence", category: "Customer Support Tools", isPro: true },
  { id: 78, name: "Support Conversation Analytics", slug: "support-conversation-analytics", category: "Customer Support Tools", isPro: true },
  { id: 79, name: "Support Sentiment Dashboard", slug: "support-sentiment-dashboard", category: "Customer Support Tools", isPro: true },
  { id: 80, name: "Support Feedback Intelligence", slug: "support-feedback-intelligence", category: "Customer Support Tools", isPro: true },
  { id: 81, name: "Support CSAT Analytics", slug: "support-csat-analytics", category: "Customer Support Tools", isPro: true },
  { id: 82, name: "Support FCR Analytics", slug: "support-fcr-analytics", category: "Customer Support Tools", isPro: true },
  { id: 83, name: "Support Cost Analytics", slug: "support-cost-analytics", category: "Customer Support Tools", isPro: true },
  { id: 84, name: "Support Productivity Analytics", slug: "support-productivity-analytics", category: "Customer Support Tools", isPro: true },
  { id: 85, name: "Support SLA Monitoring", slug: "support-sla-monitoring", category: "Customer Support Tools", isPro: true },
  { id: 86, name: "Support Alert Engine", slug: "support-alert-engine", category: "Customer Support Tools", isPro: true },
  { id: 87, name: "Support Automation Workspace", slug: "support-automation-workspace", category: "Customer Support Tools", isPro: true },
  { id: 88, name: "Support QA Management", slug: "support-qa-management", category: "Customer Support Tools", isPro: true },
  { id: 89, name: "Support Audit Workspace", slug: "support-audit-workspace", category: "Customer Support Tools", isPro: true },
  { id: 90, name: "Support Reporting Engine", slug: "support-reporting-engine", category: "Customer Support Tools", isPro: true },
  { id: 91, name: "Support API Workspace", slug: "support-api-workspace", category: "Customer Support Tools", isPro: true },
  { id: 92, name: "Support Data Importer", slug: "support-data-importer", category: "Customer Support Tools", isPro: true },
  { id: 93, name: "Support Data Exporter", slug: "support-data-exporter", category: "Customer Support Tools", isPro: true },
  { id: 94, name: "Support Workflow Manager", slug: "support-workflow-manager", category: "Customer Support Tools", isPro: true },
  { id: 95, name: "Support Knowledge Analytics", slug: "support-knowledge-analytics", category: "Customer Support Tools", isPro: true },
  { id: 96, name: "Omnichannel Support Workspace", slug: "omnichannel-support-workspace", category: "Customer Support Tools", isPro: true },
  { id: 97, name: "Enterprise Support Platform", slug: "enterprise-support-platform", category: "Customer Support Tools", isPro: true },
  { id: 98, name: "Support Intelligence Platform", slug: "support-intelligence-platform", category: "Customer Support Tools", isPro: true },
  { id: 99, name: "Customer Service Operations Platform", slug: "customer-service-operations-platform", category: "Customer Support Tools", isPro: true },
  { id: 100, name: "Support Command Center", slug: "support-command-center", category: "Customer Support Tools", isPro: true }
];