export interface CybersecurityTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const cybersecurityToolsList: CybersecurityTool[] = [
  // --- 🔥 PRIORITY 20 FREE TOOLS (IDs 1-20 | isPro: false) ---
  { id: 1, name: "Password Strength Checker", slug: "password-strength-checker", category: "Cybersecurity Tools", isPro: false },
  { id: 2, name: "Password Entropy Calculator", slug: "password-entropy-calculator", category: "Cybersecurity Tools", isPro: false },
  { id: 3, name: "File Integrity Checker", slug: "file-integrity-checker", category: "Cybersecurity Tools", isPro: false },
  { id: 4, name: "Security Header Checker", slug: "security-header-checker", category: "Cybersecurity Tools", isPro: false },
  { id: 5, name: "TLS Version Checker", slug: "tls-version-checker", category: "Cybersecurity Tools", isPro: false },
  { id: 6, name: "SSL Certificate Expiry Checker", slug: "ssl-certificate-expiry-checker", category: "Cybersecurity Tools", isPro: false },
  { id: 7, name: "SPF Record Checker", slug: "spf-record-checker", category: "Cybersecurity Tools", isPro: false },
  { id: 8, name: "DKIM Record Checker", slug: "dkim-record-checker", category: "Cybersecurity Tools", isPro: false },
  { id: 9, name: "DMARC Record Checker", slug: "dmarc-record-checker", category: "Cybersecurity Tools", isPro: false },
  { id: 10, name: "DNSSEC Status Checker", slug: "dnssec-status-checker", category: "Cybersecurity Tools", isPro: false },
  { id: 11, name: "HSTS Checker", slug: "hsts-checker", category: "Cybersecurity Tools", isPro: false },
  { id: 12, name: "CSP Header Analyzer", slug: "csp-header-analyzer", category: "Cybersecurity Tools", isPro: false },
  { id: 13, name: "CORS Configuration Checker", slug: "cors-configuration-checker", category: "Cybersecurity Tools", isPro: false },
  { id: 14, name: "Domain Reputation Checker", slug: "domain-reputation-checker", category: "Cybersecurity Tools", isPro: false },
  { id: 15, name: "IP Reputation Checker", slug: "ip-reputation-checker", category: "Cybersecurity Tools", isPro: false },
  { id: 16, name: "CVSS Score Calculator", slug: "cvss-score-calculator", category: "Cybersecurity Tools", isPro: false },
  { id: 17, name: "Risk Score Calculator", slug: "risk-score-calculator", category: "Cybersecurity Tools", isPro: false },
  { id: 18, name: "Vulnerability Assessment Checklist", slug: "vulnerability-assessment-checklist", category: "Cybersecurity Tools", isPro: false },
  { id: 19, name: "Security Audit Checklist", slug: "security-audit-checklist", category: "Cybersecurity Tools", isPro: false },
  { id: 20, name: "Security Incident Timeline", slug: "security-incident-timeline", category: "Cybersecurity Tools", isPro: false },

  // --- REMAINING 40 CORE FREE TOOLS (IDs 21-60 | isPro: false) ---
  { id: 21, name: "Passphrase Strength Checker", slug: "passphrase-strength-checker", category: "Cybersecurity Tools", isPro: false },
  { id: 22, name: "Hash Identifier", slug: "hash-identifier", category: "Cybersecurity Tools", isPro: false },
  { id: 23, name: "Hash Length Identifier", slug: "hash-length-identifier", category: "Cybersecurity Tools", isPro: false },
  { id: 24, name: "Checksum Comparison Tool", slug: "checksum-comparison-tool", category: "Cybersecurity Tools", isPro: false },
  { id: 25, name: "Certificate Information Viewer", slug: "certificate-information-viewer", category: "Cybersecurity Tools", isPro: false },
  { id: 26, name: "Certificate Chain Checker", slug: "certificate-chain-checker", category: "Cybersecurity Tools", isPro: false },
  { id: 27, name: "Domain Security Header Analyzer", slug: "domain-security-header-analyzer", category: "Cybersecurity Tools", isPro: false },
  { id: 28, name: "Email Security Analyzer", slug: "email-security-analyzer", category: "Cybersecurity Tools", isPro: false },
  { id: 29, name: "DNS Security Checker", slug: "dns-security-checker", category: "Cybersecurity Tools", isPro: false },
  { id: 30, name: "Cookie Security Checker", slug: "cookie-security-checker", category: "Cybersecurity Tools", isPro: false },
  { id: 31, name: "Secure Cookie Attribute Checker", slug: "secure-cookie-attribute-checker", category: "Cybersecurity Tools", isPro: false },
  { id: 32, name: "HTTP Security Header Generator", slug: "http-security-header-generator", category: "Cybersecurity Tools", isPro: false },
  { id: 33, name: "Security.txt Generator", slug: "security-txt-generator", category: "Cybersecurity Tools", isPro: false },
  { id: 34, name: "robots.txt Security Review", slug: "robots-txt-security-review", category: "Cybersecurity Tools", isPro: false },
  { id: 35, name: "Subresource Integrity Generator", slug: "subresource-integrity-generator", category: "Cybersecurity Tools", isPro: false },
  { id: 36, name: "SRI Hash Generator", slug: "sri-hash-generator", category: "Cybersecurity Tools", isPro: false },
  { id: 37, name: "URL Safety Analyzer", slug: "url-safety-analyzer", category: "Cybersecurity Tools", isPro: false },
  { id: 38, name: "IP WHOIS Lookup", slug: "ip-whois-lookup", category: "Cybersecurity Tools", isPro: false },
  { id: 39, name: "Domain WHOIS Lookup", slug: "domain-whois-lookup", category: "Cybersecurity Tools", isPro: false },
  { id: 40, name: "ASN Lookup", slug: "asn-lookup", category: "Cybersecurity Tools", isPro: false },
  { id: 41, name: "DNS Record Security Analyzer", slug: "dns-record-security-analyzer", category: "Cybersecurity Tools", isPro: false },
  { id: 42, name: "Port Exposure Checker", slug: "port-exposure-checker", category: "Cybersecurity Tools", isPro: false },
  { id: 43, name: "Network Security Checklist", slug: "network-security-checklist", category: "Cybersecurity Tools", isPro: false },
  { id: 44, name: "Server Hardening Checklist", slug: "server-hardening-checklist", category: "Cybersecurity Tools", isPro: false },
  { id: 45, name: "Linux Hardening Checklist", slug: "linux-hardening-checklist", category: "Cybersecurity Tools", isPro: false },
  { id: 46, name: "Windows Hardening Checklist", slug: "windows-hardening-checklist", category: "Cybersecurity Tools", isPro: false },
  { id: 47, name: "Cloud Security Checklist", slug: "cloud-security-checklist", category: "Cybersecurity Tools", isPro: false },
  { id: 48, name: "Web Application Security Checklist", slug: "web-application-security-checklist", category: "Cybersecurity Tools", isPro: false },
  { id: 49, name: "API Security Checklist", slug: "api-security-checklist", category: "Cybersecurity Tools", isPro: false },
  { id: 50, name: "Password Policy Generator", slug: "password-policy-generator", category: "Cybersecurity Tools", isPro: false },
  { id: 51, name: "Access Control Checklist", slug: "access-control-checklist", category: "Cybersecurity Tools", isPro: false },
  { id: 52, name: "MFA Readiness Checklist", slug: "mfa-readiness-checklist", category: "Cybersecurity Tools", isPro: false },
  { id: 53, name: "Incident Response Checklist", slug: "incident-response-checklist", category: "Cybersecurity Tools", isPro: false },
  { id: 54, name: "Security Risk Matrix", slug: "security-risk-matrix", category: "Cybersecurity Tools", isPro: false },
  { id: 55, name: "Security Control Matrix", slug: "security-control-matrix", category: "Cybersecurity Tools", isPro: false },
  { id: 56, name: "Asset Inventory Template", slug: "asset-inventory-template", category: "Cybersecurity Tools", isPro: false },
  { id: 57, name: "Security Policy Generator", slug: "security-policy-generator", category: "Cybersecurity Tools", isPro: false },
  { id: 58, name: "Privacy Policy Checklist", slug: "privacy-policy-checklist", category: "Cybersecurity Tools", isPro: false },
  { id: 59, name: "Security Awareness Checklist", slug: "security-awareness-checklist", category: "Cybersecurity Tools", isPro: false },
  { id: 60, name: "Cybersecurity Report Generator", slug: "cybersecurity-report-generator", category: "Cybersecurity Tools", isPro: false },

  // --- ⚡ 40 PRO / SAAS TOOLS (IDs 61-100 | isPro: true) ---
  { id: 61, name: "Security Posture Dashboard", slug: "security-posture-dashboard", category: "Cybersecurity Tools", isPro: true },
  { id: 62, name: "Vulnerability Management Workspace", slug: "vulnerability-management-workspace", category: "Cybersecurity Tools", isPro: true },
  { id: 63, name: "Security Operations Dashboard", slug: "security-operations-dashboard", category: "Cybersecurity Tools", isPro: true },
  { id: 64, name: "Attack Surface Inventory", slug: "attack-surface-inventory", category: "Cybersecurity Tools", isPro: true },
  { id: 65, name: "Asset Security Inventory", slug: "asset-security-inventory", category: "Cybersecurity Tools", isPro: true },
  { id: 66, name: "Risk Management Workspace", slug: "risk-management-workspace", category: "Cybersecurity Tools", isPro: true },
  { id: 67, name: "CVSS Risk Prioritization Workspace", slug: "cvss-risk-prioritization-workspace", category: "Cybersecurity Tools", isPro: true },
  { id: 68, name: "Security Findings Dashboard", slug: "security-findings-dashboard", category: "Cybersecurity Tools", isPro: true },
  { id: 69, name: "Security Remediation Tracker", slug: "security-remediation-tracker", category: "Cybersecurity Tools", isPro: true },
  { id: 70, name: "Security Incident Management", slug: "security-incident-management", category: "Cybersecurity Tools", isPro: true },
  { id: 71, name: "Incident Response Workspace", slug: "incident-response-workspace", category: "Cybersecurity Tools", isPro: true },
  { id: 72, name: "Security Event Timeline", slug: "security-event-timeline", category: "Cybersecurity Tools", isPro: true },
  { id: 73, name: "Security Audit Workspace", slug: "security-audit-workspace", category: "Cybersecurity Tools", isPro: true },
  { id: 74, name: "Compliance Readiness Workspace", slug: "compliance-readiness-workspace", category: "Cybersecurity Tools", isPro: true },
  { id: 75, name: "Security Control Management", slug: "security-control-management", category: "Cybersecurity Tools", isPro: true },
  { id: 76, name: "Security Policy Management", slug: "security-policy-management", category: "Cybersecurity Tools", isPro: true },
  { id: 77, name: "Security Evidence Management", slug: "security-evidence-management", category: "Cybersecurity Tools", isPro: true },
  { id: 78, name: "Security Risk Register", slug: "security-risk-register", category: "Cybersecurity Tools", isPro: true },
  { id: 79, name: "Security Asset Management", slug: "security-asset-management", category: "Cybersecurity Tools", isPro: true },
  { id: 80, name: "Security Configuration Audit", slug: "security-configuration-audit", category: "Cybersecurity Tools", isPro: true },
  { id: 81, name: "Cloud Security Posture Workspace", slug: "cloud-security-posture-workspace", category: "Cybersecurity Tools", isPro: true },
  { id: 82, name: "API Security Monitoring", slug: "api-security-monitoring", category: "Cybersecurity Tools", isPro: true },
  { id: 83, name: "Web Security Monitoring", slug: "web-security-monitoring", category: "Cybersecurity Tools", isPro: true },
  { id: 84, name: "Domain Security Monitoring", slug: "domain-security-monitoring", category: "Cybersecurity Tools", isPro: true },
  { id: 85, name: "Certificate Monitoring Workspace", slug: "certificate-monitoring-workspace", category: "Cybersecurity Tools", isPro: true },
  { id: 86, name: "DNS Security Monitoring", slug: "dns-security-monitoring", category: "Cybersecurity Tools", isPro: true },
  { id: 87, name: "Email Security Monitoring", slug: "email-security-monitoring", category: "Cybersecurity Tools", isPro: true },
  { id: 88, name: "Security Header Monitoring", slug: "security-header-monitoring", category: "Cybersecurity Tools", isPro: true },
  { id: 89, name: "Security Alert Dashboard", slug: "security-alert-dashboard", category: "Cybersecurity Tools", isPro: true },
  { id: 90, name: "Security Reporting Workspace", slug: "security-reporting-workspace", category: "Cybersecurity Tools", isPro: true },
  { id: 91, name: "Security Assessment Workspace", slug: "security-assessment-workspace", category: "Cybersecurity Tools", isPro: true },
  { id: 92, name: "Third-Party Risk Workspace", slug: "third-party-risk-workspace", category: "Cybersecurity Tools", isPro: true },
  { id: 93, name: "Vendor Security Assessment", slug: "vendor-security-assessment", category: "Cybersecurity Tools", isPro: true },
  { id: 94, name: "Security Questionnaire Manager", slug: "security-questionnaire-manager", category: "Cybersecurity Tools", isPro: true },
  { id: 95, name: "Security Data Import Workspace", slug: "security-data-import-workspace", category: "Cybersecurity Tools", isPro: true },
  { id: 96, name: "Security API Workspace", slug: "security-api-workspace", category: "Cybersecurity Tools", isPro: true },
  { id: 97, name: "Security Automation Workspace", slug: "security-automation-workspace", category: "Cybersecurity Tools", isPro: true },
  { id: 98, name: "Cybersecurity Intelligence Platform", slug: "cybersecurity-intelligence-platform", category: "Cybersecurity Tools", isPro: true },
  { id: 99, name: "Enterprise Security Command Center", slug: "enterprise-security-command-center", category: "Cybersecurity Tools", isPro: true },
  { id: 100, name: "Security Operations Intelligence Platform", slug: "security-operations-intelligence-platform", category: "Cybersecurity Tools", isPro: true }
];