export interface DataScienceTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const dataScienceToolsList: DataScienceTool[] = [
  // --- 🔥 PRIORITY 20 FREE TOOLS (IDs 1-20 | isPro: false) ---
  { id: 1, name: "CSV Data Profiler", slug: "csv-data-profiler", category: "Data Science Tools", isPro: false },
  { id: 2, name: "Column Statistics Generator", slug: "column-statistics-generator", category: "Data Science Tools", isPro: false },
  { id: 3, name: "Descriptive Statistics Calculator", slug: "descriptive-statistics-calculator", category: "Data Science Tools", isPro: false },
  { id: 4, name: "Standard Deviation Calculator", slug: "standard-deviation-calculator-ds", category: "Data Science Tools", isPro: false },
  { id: 5, name: "Percentile Calculator", slug: "percentile-calculator", category: "Data Science Tools", isPro: false },
  { id: 6, name: "Z-Score Calculator", slug: "z-score-calculator", category: "Data Science Tools", isPro: false },
  { id: 7, name: "Correlation Calculator", slug: "correlation-calculator", category: "Data Science Tools", isPro: false },
  { id: 8, name: "Moving Average Calculator", slug: "moving-average-calculator-ds", category: "Data Science Tools", isPro: false },
  { id: 9, name: "Trend Analyzer", slug: "trend-analyzer", category: "Data Science Tools", isPro: false },
  { id: 10, name: "Time Series Analyzer", slug: "time-series-analyzer", category: "Data Science Tools", isPro: false },
  { id: 11, name: "Probability Calculator", slug: "probability-calculator", category: "Data Science Tools", isPro: false },
  { id: 12, name: "Confidence Interval Calculator", slug: "confidence-interval-calculator", category: "Data Science Tools", isPro: false },
  { id: 13, name: "Margin of Error Calculator", slug: "margin-of-error-calculator", category: "Data Science Tools", isPro: false },
  { id: 14, name: "Sample Size Calculator", slug: "sample-size-calculator-ds", category: "Data Science Tools", isPro: false },
  { id: 15, name: "P-Value Calculator", slug: "p-value-calculator", category: "Data Science Tools", isPro: false },
  { id: 16, name: "T-Test Calculator", slug: "t-test-calculator", category: "Data Science Tools", isPro: false },
  { id: 17, name: "Regression Calculator", slug: "regression-calculator", category: "Data Science Tools", isPro: false },
  { id: 18, name: "Forecast Calculator", slug: "forecast-calculator-ds", category: "Data Science Tools", isPro: false },
  { id: 19, name: "Data Summary Generator", slug: "data-summary-generator", category: "Data Science Tools", isPro: false },
  { id: 20, name: "Statistical Report Generator", slug: "statistical-report-generator", category: "Data Science Tools", isPro: false },

  // --- REMAINING 40 CORE FREE TOOLS (IDs 21-60 | isPro: false) ---
  { id: 21, name: "Data Type Analyzer", slug: "data-type-analyzer", category: "Data Science Tools", isPro: false },
  { id: 22, name: "Mean Calculator", slug: "mean-calculator", category: "Data Science Tools", isPro: false },
  { id: 23, name: "Median Calculator", slug: "median-calculator", category: "Data Science Tools", isPro: false },
  { id: 24, name: "Mode Calculator", slug: "mode-calculator", category: "Data Science Tools", isPro: false },
  { id: 25, name: "Variance Calculator", slug: "variance-calculator-ds", category: "Data Science Tools", isPro: false },
  { id: 26, name: "Quartile Calculator", slug: "quartile-calculator", category: "Data Science Tools", isPro: false },
  { id: 27, name: "Interquartile Range Calculator", slug: "interquartile-range-calculator", category: "Data Science Tools", isPro: false },
  { id: 28, name: "Covariance Calculator", slug: "covariance-calculator", category: "Data Science Tools", isPro: false },
  { id: 29, name: "Pearson Correlation Calculator", slug: "pearson-correlation-calculator", category: "Data Science Tools", isPro: false },
  { id: 30, name: "Spearman Correlation Calculator", slug: "spearman-correlation-calculator", category: "Data Science Tools", isPro: false },
  { id: 31, name: "Weighted Average Calculator", slug: "weighted-average-calculator", category: "Data Science Tools", isPro: false },
  { id: 32, name: "Rolling Average Calculator", slug: "rolling-average-calculator", category: "Data Science Tools", isPro: false },
  { id: 33, name: "Growth Rate Analyzer", slug: "growth-rate-analyzer", category: "Data Science Tools", isPro: false },
  { id: 34, name: "CAGR Analyzer", slug: "cagr-analyzer", category: "Data Science Tools", isPro: false },
  { id: 35, name: "Seasonality Analyzer", slug: "seasonality-analyzer", category: "Data Science Tools", isPro: false },
  { id: 36, name: "Distribution Analyzer", slug: "distribution-analyzer-ds", category: "Data Science Tools", isPro: false },
  { id: 37, name: "Normal Distribution Calculator", slug: "normal-distribution-calculator", category: "Data Science Tools", isPro: false },
  { id: 38, name: "Binomial Distribution Calculator", slug: "binomial-distribution-calculator", category: "Data Science Tools", isPro: false },
  { id: 39, name: "Poisson Distribution Calculator", slug: "poisson-distribution-calculator", category: "Data Science Tools", isPro: false },
  { id: 40, name: "Conditional Probability Calculator", slug: "conditional-probability-calculator", category: "Data Science Tools", isPro: false },
  { id: 41, name: "Bayes Probability Calculator", slug: "bayes-probability-calculator", category: "Data Science Tools", isPro: false },
  { id: 42, name: "Statistical Power Calculator", slug: "statistical-power-calculator", category: "Data Science Tools", isPro: false },
  { id: 43, name: "Chi-Square Calculator", slug: "chi-square-calculator", category: "Data Science Tools", isPro: false },
  { id: 44, name: "ANOVA Calculator", slug: "anova-calculator", category: "Data Science Tools", isPro: false },
  { id: 45, name: "Linear Regression Analyzer", slug: "linear-regression-analyzer", category: "Data Science Tools", isPro: false },
  { id: 46, name: "Logistic Regression Calculator", slug: "logistic-regression-calculator", category: "Data Science Tools", isPro: false },
  { id: 47, name: "Trendline Generator", slug: "trendline-generator", category: "Data Science Tools", isPro: false },
  { id: 48, name: "Outlier Analysis Tool", slug: "outlier-analysis-tool", category: "Data Science Tools", isPro: false },
  { id: 49, name: "Box Plot Data Generator", slug: "box-plot-data-generator", category: "Data Science Tools", isPro: false },
  { id: 50, name: "Histogram Data Generator", slug: "histogram-data-generator", category: "Data Science Tools", isPro: false },
  { id: 51, name: "Scatter Plot Data Generator", slug: "scatter-plot-data-generator", category: "Data Science Tools", isPro: false },
  { id: 52, name: "Pivot Summary Generator", slug: "pivot-summary-generator", category: "Data Science Tools", isPro: false },
  { id: 53, name: "Cross Tabulation Generator", slug: "cross-tabulation-generator", category: "Data Science Tools", isPro: false },
  { id: 54, name: "Frequency Table Generator", slug: "frequency-table-generator", category: "Data Science Tools", isPro: false },
  { id: 55, name: "Data Aggregation Tool", slug: "data-aggregation-tool", category: "Data Science Tools", isPro: false },
  { id: 56, name: "Data Grouping Tool", slug: "data-grouping-tool", category: "Data Science Tools", isPro: false },
  { id: 57, name: "Data Sampling Tool", slug: "data-sampling-tool", category: "Data Science Tools", isPro: false },
  { id: 58, name: "Data Ranking Tool", slug: "data-ranking-tool", category: "Data Science Tools", isPro: false },
  { id: 59, name: "Data Comparison Tool", slug: "data-comparison-tool", category: "Data Science Tools", isPro: false },
  { id: 60, name: "Data Analysis Checklist", slug: "data-analysis-checklist", category: "Data Science Tools", isPro: false },

  // --- ⚡ 40 PRO / SAAS TOOLS (IDs 61-100 | isPro: true) ---
  { id: 61, name: "Data Science Workspace", slug: "data-science-workspace", category: "Data Science Tools", isPro: true },
  { id: 62, name: "Exploratory Data Analysis Workspace", slug: "exploratory-data-analysis-workspace", category: "Data Science Tools", isPro: true },
  { id: 63, name: "Statistical Analysis Workspace", slug: "statistical-analysis-workspace", category: "Data Science Tools", isPro: true },
  { id: 64, name: "Advanced Statistics Dashboard", slug: "advanced-statistics-dashboard", category: "Data Science Tools", isPro: true },
  { id: 65, name: "Dataset Profiling Dashboard", slug: "dataset-profiling-dashboard", category: "Data Science Tools", isPro: true },
  { id: 66, name: "Data Quality Analytics", slug: "data-quality-analytics", category: "Data Science Tools", isPro: true },
  { id: 67, name: "Correlation Intelligence Workspace", slug: "correlation-intelligence-workspace", category: "Data Science Tools", isPro: true },
  { id: 68, name: "Distribution Intelligence Workspace", slug: "distribution-intelligence-workspace", category: "Data Science Tools", isPro: true },
  { id: 69, name: "Time Series Intelligence", slug: "time-series-intelligence", category: "Data Science Tools", isPro: true },
  { id: 70, name: "Forecasting Analytics Workspace", slug: "forecasting-analytics-workspace", category: "Data Science Tools", isPro: true },
  { id: 71, name: "Experiment Analysis Workspace", slug: "experiment-analysis-workspace", category: "Data Science Tools", isPro: true },
  { id: 72, name: "A/B Test Analysis Workspace", slug: "ab-test-analysis-workspace", category: "Data Science Tools", isPro: true },
  { id: 73, name: "Statistical Significance Workspace", slug: "statistical-significance-workspace", category: "Data Science Tools", isPro: true },
  { id: 74, name: "Hypothesis Testing Workspace", slug: "hypothesis-testing-workspace", category: "Data Science Tools", isPro: true },
  { id: 75, name: "Regression Analysis Workspace", slug: "regression-analysis-workspace", category: "Data Science Tools", isPro: true },
  { id: 76, name: "Multivariate Analysis Workspace", slug: "multivariate-analysis-workspace", category: "Data Science Tools", isPro: true },
  { id: 77, name: "Data Segmentation Workspace", slug: "data-segmentation-workspace", category: "Data Science Tools", isPro: true },
  { id: 78, name: "Cohort Analysis Workspace", slug: "cohort-analysis-workspace", category: "Data Science Tools", isPro: true },
  { id: 79, name: "Retention Analysis Workspace", slug: "retention-analysis-workspace", category: "Data Science Tools", isPro: true },
  { id: 80, name: "Trend Intelligence Dashboard", slug: "trend-intelligence-dashboard", category: "Data Science Tools", isPro: true },
  { id: 81, name: "Business Data Analysis Workspace", slug: "business-data-analysis-workspace", category: "Data Science Tools", isPro: true },
  { id: 82, name: "Research Data Analysis Workspace", slug: "research-data-analysis-workspace", category: "Data Science Tools", isPro: true },
  { id: 83, name: "Survey Data Analysis Workspace", slug: "survey-data-analysis-workspace", category: "Data Science Tools", isPro: true },
  { id: 84, name: "Data Visualization Workspace", slug: "data-visualization-workspace", category: "Data Science Tools", isPro: true },
  { id: 85, name: "Interactive Chart Builder", slug: "interactive-chart-builder", category: "Data Science Tools", isPro: true },
  { id: 86, name: "Data Storytelling Workspace", slug: "data-storytelling-workspace", category: "Data Science Tools", isPro: true },
  { id: 87, name: "Data Report Builder", slug: "data-report-builder", category: "Data Science Tools", isPro: true },
  { id: 88, name: "Statistical Report Builder", slug: "statistical-report-builder", category: "Data Science Tools", isPro: true },
  { id: 89, name: "Data Import Workspace", slug: "data-import-workspace-ds", category: "Data Science Tools", isPro: true },
  { id: 90, name: "Data Cleaning Workspace", slug: "data-cleaning-workspace", category: "Data Science Tools", isPro: true },
  { id: 91, name: "Data Transformation Workspace", slug: "data-transformation-workspace", category: "Data Science Tools", isPro: true },
  { id: 92, name: "Data Analysis Automation", slug: "data-analysis-automation", category: "Data Science Tools", isPro: true },
  { id: 93, name: "Analysis Template Workspace", slug: "analysis-template-workspace", category: "Data Science Tools", isPro: true },
  { id: 94, name: "Data Science Notebook Workspace", slug: "data-science-notebook-workspace", category: "Data Science Tools", isPro: true },
  { id: 95, name: "Data Science API", slug: "data-science-api", category: "Data Science Tools", isPro: true },
  { id: 96, name: "Data Analysis Monitoring", slug: "data-analysis-monitoring", category: "Data Science Tools", isPro: true },
  { id: 97, name: "Data Analytics Dashboard", slug: "data-analytics-dashboard", category: "Data Science Tools", isPro: true },
  { id: 98, name: "Data Intelligence Platform", slug: "data-intelligence-platform", category: "Data Science Tools", isPro: true },
  { id: 99, name: "Decision Analytics Workspace", slug: "decision-analytics-workspace", category: "Data Science Tools", isPro: true },
  { id: 100, name: "Enterprise Data Science Command Center", slug: "enterprise-data-science-command-center", category: "Data Science Tools", isPro: true }
];