export interface DatabaseApiTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const databaseApiToolsList: DatabaseApiTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-13) ---
  { id: 1, name: "SQL Query Generator", slug: "sql-query-generator", category: "Database & API Tools", isPro: false },
  { id: 2, name: "SQL Query Formatter", slug: "sql-query-formatter", category: "Database & API Tools", isPro: false },
  { id: 3, name: "SQL Query Validator", slug: "sql-query-validator", category: "Database & API Tools", isPro: false },
  { id: 4, name: "SQL Query Explainer", slug: "sql-query-explainer", category: "Database & API Tools", isPro: false },
  { id: 5, name: "SQL Error Explainer", slug: "sql-error-explainer", category: "Database & API Tools", isPro: false },
  { id: 6, name: "SQL Join Builder", slug: "sql-join-builder", category: "Database & API Tools", isPro: false },
  { id: 7, name: "Database Schema Generator", slug: "database-schema-generator", category: "Database & API Tools", isPro: false },
  { id: 8, name: "Database ER Diagram Generator", slug: "database-er-diagram-generator", category: "Database & API Tools", isPro: false },
  { id: 9, name: "JSON Validator", slug: "json-validator", category: "Database & API Tools", isPro: false },
  { id: 10, name: "JSON Formatter", slug: "json-formatter", category: "Database & API Tools", isPro: false },
  { id: 11, name: "JSON Schema Generator", slug: "json-schema-generator", category: "Database & API Tools", isPro: false },
  { id: 12, name: "JSON to SQL Converter", slug: "json-to-sql-converter", category: "Database & API Tools", isPro: false },
  { id: 13, name: "CSV to SQL Converter", slug: "csv-to-sql-converter", category: "Database & API Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (14-60) ---
  { id: 14, name: "SQL Query Beautifier", slug: "sql-query-beautifier", category: "Database & API Tools", isPro: false },
  { id: 15, name: "SQL Query Minifier", slug: "sql-query-minifier", category: "Database & API Tools", isPro: false },
  { id: 16, name: "SQL Query Converter", slug: "sql-query-converter", category: "Database & API Tools", isPro: false },
  { id: 17, name: "SQL Syntax Checker", slug: "sql-syntax-checker", category: "Database & API Tools", isPro: false },
  { id: 18, name: "SQL Table Generator", slug: "sql-table-generator", category: "Database & API Tools", isPro: false },
  { id: 19, name: "SQL Insert Generator", slug: "sql-insert-generator", category: "Database & API Tools", isPro: false },
  { id: 20, name: "SQL Update Generator", slug: "sql-update-generator", category: "Database & API Tools", isPro: false },
  { id: 21, name: "SQL Delete Generator", slug: "sql-delete-generator", category: "Database & API Tools", isPro: false },
  { id: 22, name: "SQL Select Generator", slug: "sql-select-generator", category: "Database & API Tools", isPro: false },
  { id: 23, name: "SQL Where Builder", slug: "sql-where-builder", category: "Database & API Tools", isPro: false },
  { id: 24, name: "SQL Group By Builder", slug: "sql-group-by-builder", category: "Database & API Tools", isPro: false },
  { id: 25, name: "SQL Order By Builder", slug: "sql-order-by-builder", category: "Database & API Tools", isPro: false },
  { id: 26, name: "SQL Create Table Generator", slug: "sql-create-table-generator", category: "Database & API Tools", isPro: false },
  { id: 27, name: "SQL Alter Table Generator", slug: "sql-alter-table-generator", category: "Database & API Tools", isPro: false },
  { id: 28, name: "SQL Index Generator", slug: "sql-index-generator", category: "Database & API Tools", isPro: false },
  { id: 29, name: "SQL View Generator", slug: "sql-view-generator", category: "Database & API Tools", isPro: false },
  { id: 30, name: "SQL Trigger Generator", slug: "sql-trigger-generator", category: "Database & API Tools", isPro: false },
  { id: 31, name: "SQL Stored Procedure Generator", slug: "sql-stored-procedure-generator", category: "Database & API Tools", isPro: false },
  { id: 32, name: "SQL Seed Data Generator", slug: "sql-seed-data-generator", category: "Database & API Tools", isPro: false },
  { id: 33, name: "SQL Mock Data Generator", slug: "sql-mock-data-generator", category: "Database & API Tools", isPro: false },
  { id: 34, name: "Database Schema Viewer", slug: "database-schema-viewer", category: "Database & API Tools", isPro: false },
  { id: 35, name: "Database Schema Validator", slug: "database-schema-validator", category: "Database & API Tools", isPro: false },
  { id: 36, name: "Database Schema Converter", slug: "database-schema-converter", category: "Database & API Tools", isPro: false },
  { id: 37, name: "Database Relationship Analyzer", slug: "database-relationship-analyzer", category: "Database & API Tools", isPro: false },
  { id: 38, name: "Database Table Comparison", slug: "database-table-comparison", category: "Database & API Tools", isPro: false },
  { id: 39, name: "Database Column Comparison", slug: "database-column-comparison", category: "Database & API Tools", isPro: false },
  { id: 40, name: "Database Migration Generator", slug: "database-migration-generator", category: "Database & API Tools", isPro: false },
  { id: 41, name: "MySQL to PostgreSQL Converter", slug: "mysql-to-postgresql-converter", category: "Database & API Tools", isPro: false },
  { id: 42, name: "PostgreSQL to MySQL Converter", slug: "postgresql-to-mysql-converter", category: "Database & API Tools", isPro: false },
  { id: 43, name: "MySQL to SQLite Converter", slug: "mysql-to-sqlite-converter", category: "Database & API Tools", isPro: false },
  { id: 44, name: "PostgreSQL to SQLite Converter", slug: "postgresql-to-sqlite-converter", category: "Database & API Tools", isPro: false },
  { id: 45, name: "SQL Server to PostgreSQL Converter", slug: "sql-server-to-postgresql-converter", category: "Database & API Tools", isPro: false },
  { id: 46, name: "Excel to SQL Generator", slug: "excel-to-sql-generator", category: "Database & API Tools", isPro: false },
  { id: 47, name: "SQL to JSON Converter", slug: "sql-to-json-converter", category: "Database & API Tools", isPro: false },
  { id: 48, name: "SQL to CSV Converter", slug: "sql-to-csv-converter", category: "Database & API Tools", isPro: false },
  { id: 49, name: "SQL to XML Converter", slug: "sql-to-xml-converter", category: "Database & API Tools", isPro: false },
  { id: 50, name: "JSON Beautifier", slug: "json-beautifier", category: "Database & API Tools", isPro: false },
  { id: 51, name: "JSON Minifier", slug: "json-minifier", category: "Database & API Tools", isPro: false },
  { id: 52, name: "JSON Schema Validator", slug: "json-schema-validator", category: "Database & API Tools", isPro: false },
  { id: 53, name: "JSON Schema Converter", slug: "json-schema-converter", category: "Database & API Tools", isPro: false },
  { id: 54, name: "JSON Path Tester", slug: "json-path-tester", category: "Database & API Tools", isPro: false },
  { id: 55, name: "JSON Diff Checker", slug: "json-diff-checker", category: "Database & API Tools", isPro: false },
  { id: 56, name: "XML Formatter", slug: "xml-formatter", category: "Database & API Tools", isPro: false },
  { id: 57, name: "XML Validator", slug: "xml-validator", category: "Database & API Tools", isPro: false },
  { id: 58, name: "XML to JSON Converter", slug: "xml-to-json-converter", category: "Database & API Tools", isPro: false },
  { id: 59, name: "YAML Validator", slug: "yaml-validator", category: "Database & API Tools", isPro: false },
  { id: 60, name: "YAML to JSON Converter", slug: "yaml-to-json-converter", category: "Database & API Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "API Request Builder", slug: "api-request-builder", category: "Database & API Tools", isPro: true },
  { id: 62, name: "REST API Tester", slug: "rest-api-tester", category: "Database & API Tools", isPro: true },
  { id: 63, name: "GraphQL Query Tester", slug: "graphql-query-tester", category: "Database & API Tools", isPro: true },
  { id: 64, name: "API Documentation Generator", slug: "api-documentation-generator", category: "Database & API Tools", isPro: true },
  { id: 65, name: "OpenAPI Generator", slug: "openapi-generator", category: "Database & API Tools", isPro: true },
  { id: 66, name: "Webhook Tester", slug: "webhook-tester", category: "Database & API Tools", isPro: true },
  { id: 67, name: "Database Query Performance Analyzer", slug: "database-query-performance-analyzer", category: "Database & API Tools", isPro: true },
  { id: 68, name: "API Endpoint Tester", slug: "api-endpoint-tester", category: "Database & API Tools", isPro: true },
  { id: 69, name: "GraphQL Query Builder", slug: "graphql-query-builder", category: "Database & API Tools", isPro: true },
  { id: 70, name: "GraphQL Schema Explorer", slug: "graphql-schema-explorer", category: "Database & API Tools", isPro: true },
  { id: 71, name: "API Response Formatter", slug: "api-response-formatter", category: "Database & API Tools", isPro: true },
  { id: 72, name: "API Response Validator", slug: "api-response-validator", category: "Database & API Tools", isPro: true },
  { id: 73, name: "API Response Diff", slug: "api-response-diff", category: "Database & API Tools", isPro: true },
  { id: 74, name: "API Mock Server Generator", slug: "api-mock-server-generator", category: "Database & API Tools", isPro: true },
  { id: 75, name: "OpenAPI Validator", slug: "openapi-validator", category: "Database & API Tools", isPro: true },
  { id: 76, name: "OpenAPI Converter", slug: "openapi-converter", category: "Database & API Tools", isPro: true },
  { id: 77, name: "API Schema Generator", slug: "api-schema-generator", category: "Database & API Tools", isPro: true },
  { id: 78, name: "API Schema Diff", slug: "api-schema-diff", category: "Database & API Tools", isPro: true },
  { id: 79, name: "API Version Comparator", slug: "api-version-comparator", category: "Database & API Tools", isPro: true },
  { id: 80, name: "API Endpoint Monitor", slug: "api-endpoint-monitor", category: "Database & API Tools", isPro: true },
  { id: 81, name: "API Uptime Monitor", slug: "api-uptime-monitor", category: "Database & API Tools", isPro: true },
  { id: 82, name: "API Latency Monitor", slug: "api-latency-monitor", category: "Database & API Tools", isPro: true },
  { id: 83, name: "API Error Rate Analyzer", slug: "api-error-rate-analyzer", category: "Database & API Tools", isPro: true },
  { id: 84, name: "API Usage Analyzer", slug: "api-usage-analyzer", category: "Database & API Tools", isPro: true },
  { id: 85, name: "API Rate Limit Calculator", slug: "api-rate-limit-calculator", category: "Database & API Tools", isPro: true },
  { id: 86, name: "API Pagination Generator", slug: "api-pagination-generator", category: "Database & API Tools", isPro: true },
  { id: 87, name: "API Authentication Generator", slug: "api-authentication-generator", category: "Database & API Tools", isPro: true },
  { id: 88, name: "Webhook Payload Generator", slug: "webhook-payload-generator", category: "Database & API Tools", isPro: true },
  { id: 89, name: "Webhook Debugger", slug: "webhook-debugger", category: "Database & API Tools", isPro: true },
  { id: 90, name: "Webhook Replay Tool", slug: "webhook-replay-tool", category: "Database & API Tools", isPro: true },
  { id: 91, name: "SQL Execution Plan Analyzer", slug: "sql-execution-plan-analyzer", category: "Database & API Tools", isPro: true },
  { id: 92, name: "Database Index Advisor", slug: "database-index-advisor", category: "Database & API Tools", isPro: true },
  { id: 93, name: "Database Performance Analyzer", slug: "database-performance-analyzer", category: "Database & API Tools", isPro: true },
  { id: 94, name: "Database Migration Planner", slug: "database-migration-planner", category: "Database & API Tools", isPro: true },
  { id: 95, name: "Database Backup Validator", slug: "database-backup-validator", category: "Database & API Tools", isPro: true },
  { id: 96, name: "Database Connection Tester", slug: "database-connection-tester", category: "Database & API Tools", isPro: true },
  { id: 97, name: "Database Health Dashboard", slug: "database-health-dashboard", category: "Database & API Tools", isPro: true },
  { id: 98, name: "API Analytics Dashboard", slug: "api-analytics-dashboard", category: "Database & API Tools", isPro: true },
  { id: 99, name: "API Management Workspace", slug: "api-management-workspace", category: "Database & API Tools", isPro: true },
  { id: 100, name: "Database Intelligence Workspace", slug: "database-intelligence-workspace", category: "Database & API Tools", isPro: true },
];