export interface DateTimeTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const dateTimeToolsList: DateTimeTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "Date Difference Calculator", slug: "date-difference-calculator", category: "Date & Time Tools", isPro: false },
  { id: 2, name: "Days Between Dates Calculator", slug: "days-between-dates-calculator", category: "Date & Time Tools", isPro: false },
  { id: 3, name: "Business Days Calculator", slug: "business-days-calculator", category: "Date & Time Tools", isPro: false },
  { id: 4, name: "Working Days Calculator", slug: "working-days-calculator", category: "Date & Time Tools", isPro: false },
  { id: 5, name: "Age Calculator", slug: "age-calculator", category: "Date & Time Tools", isPro: false },
  { id: 6, name: "Birthday Countdown", slug: "birthday-countdown", category: "Date & Time Tools", isPro: false },
  { id: 7, name: "Event Countdown", slug: "event-countdown", category: "Date & Time Tools", isPro: false },
  { id: 8, name: "Deadline Countdown", slug: "deadline-countdown", category: "Date & Time Tools", isPro: false },
  { id: 9, name: "Time Duration Calculator", slug: "time-duration-calculator", category: "Date & Time Tools", isPro: false },
  { id: 10, name: "Time Zone Converter", slug: "time-zone-converter", category: "Date & Time Tools", isPro: false },
  { id: 11, name: "World Clock", slug: "world-clock", category: "Date & Time Tools", isPro: false },
  { id: 12, name: "Meeting Time Finder", slug: "meeting-time-finder", category: "Date & Time Tools", isPro: false },
  { id: 13, name: "UTC Converter", slug: "utc-converter", category: "Date & Time Tools", isPro: false },
  { id: 14, name: "Unix Timestamp Converter", slug: "unix-timestamp-converter", category: "Date & Time Tools", isPro: false },
  { id: 15, name: "Date Format Converter", slug: "date-format-converter", category: "Date & Time Tools", isPro: false },
  { id: 16, name: "Week Number Calculator", slug: "week-number-calculator", category: "Date & Time Tools", isPro: false },
  { id: 17, name: "Days Remaining Calculator", slug: "days-remaining-calculator", category: "Date & Time Tools", isPro: false },
  { id: 18, name: "Project Deadline Calculator", slug: "project-deadline-calculator", category: "Date & Time Tools", isPro: false },
  { id: 19, name: "Subscription Renewal Calculator", slug: "subscription-renewal-calculator", category: "Date & Time Tools", isPro: false },
  { id: 20, name: "Contract Expiry Calculator", slug: "contract-expiry-calculator", category: "Date & Time Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Add Days to Date", slug: "add-days-to-date", category: "Date & Time Tools", isPro: false },
  { id: 22, name: "Subtract Days from Date", slug: "subtract-days-from-date", category: "Date & Time Tools", isPro: false },
  { id: 23, name: "Add Weeks to Date", slug: "add-weeks-to-date", category: "Date & Time Tools", isPro: false },
  { id: 24, name: "Add Months to Date", slug: "add-months-to-date", category: "Date & Time Tools", isPro: false },
  { id: 25, name: "Add Years to Date", slug: "add-years-to-date", category: "Date & Time Tools", isPro: false },
  { id: 26, name: "Date Calculator", slug: "date-calculator", category: "Date & Time Tools", isPro: false },
  { id: 27, name: "Exact Age Calculator", slug: "exact-age-calculator", category: "Date & Time Tools", isPro: false },
  { id: 28, name: "Birthday Calculator", slug: "birthday-calculator", category: "Date & Time Tools", isPro: false },
  { id: 29, name: "Anniversary Calculator", slug: "anniversary-calculator", category: "Date & Time Tools", isPro: false },
  { id: 30, name: "Anniversary Countdown", slug: "anniversary-countdown", category: "Date & Time Tools", isPro: false },
  { id: 31, name: "Hours Between Times", slug: "hours-between-times", category: "Date & Time Tools", isPro: false },
  { id: 32, name: "Minutes Between Times", slug: "minutes-between-times", category: "Date & Time Tools", isPro: false },
  { id: 33, name: "Seconds Between Times", slug: "seconds-between-times", category: "Date & Time Tools", isPro: false },
  { id: 34, name: "Time Addition Calculator", slug: "time-addition-calculator", category: "Date & Time Tools", isPro: false },
  { id: 35, name: "Time Subtraction Calculator", slug: "time-subtraction-calculator", category: "Date & Time Tools", isPro: false },
  { id: 36, name: "International Meeting Planner", slug: "international-meeting-planner", category: "Date & Time Tools", isPro: false },
  { id: 37, name: "Unix Timestamp Generator", slug: "unix-timestamp-generator", category: "Date & Time Tools", isPro: false },
  { id: 38, name: "Unix Timestamp Decoder", slug: "unix-timestamp-decoder", category: "Date & Time Tools", isPro: false },
  { id: 39, name: "Epoch Time Converter", slug: "epoch-time-converter", category: "Date & Time Tools", isPro: false },
  { id: 40, name: "ISO Date Converter", slug: "iso-date-converter", category: "Date & Time Tools", isPro: false },
  { id: 41, name: "Date to Weekday Calculator", slug: "date-to-weekday-calculator", category: "Date & Time Tools", isPro: false },
  { id: 42, name: "Day of Year Calculator", slug: "day-of-year-calculator", category: "Date & Time Tools", isPro: false },
  { id: 43, name: "Days Until Date Calculator", slug: "days-until-date-calculator", category: "Date & Time Tools", isPro: false },
  { id: 44, name: "Leap Year Calculator", slug: "leap-year-calculator", category: "Date & Time Tools", isPro: false },
  { id: 45, name: "Calendar Generator", slug: "calendar-generator", category: "Date & Time Tools", isPro: false },
  { id: 46, name: "Monthly Calendar Generator", slug: "monthly-calendar-generator", category: "Date & Time Tools", isPro: false },
  { id: 47, name: "Yearly Calendar Generator", slug: "yearly-calendar-generator", category: "Date & Time Tools", isPro: false },
  { id: 48, name: "Workday Calculator", slug: "workday-calculator", category: "Date & Time Tools", isPro: false },
  { id: 49, name: "Payroll Date Calculator", slug: "payroll-date-calculator", category: "Date & Time Tools", isPro: false },
  { id: 50, name: "Pay Period Calculator", slug: "pay-period-calculator", category: "Date & Time Tools", isPro: false },
  { id: 51, name: "Project Duration Calculator", slug: "project-duration-calculator", category: "Date & Time Tools", isPro: false },
  { id: 52, name: "Warranty Expiry Calculator", slug: "warranty-expiry-calculator", category: "Date & Time Tools", isPro: false },
  { id: 53, name: "Trial Expiry Calculator", slug: "trial-expiry-calculator", category: "Date & Time Tools", isPro: false },
  { id: 54, name: "Loan Due Date Calculator", slug: "loan-due-date-calculator", category: "Date & Time Tools", isPro: false },
  { id: 55, name: "Payment Due Date Calculator", slug: "payment-due-date-calculator", category: "Date & Time Tools", isPro: false },
  { id: 56, name: "Date Range Generator", slug: "date-range-generator", category: "Date & Time Tools", isPro: false },
  { id: 57, name: "Recurring Date Generator", slug: "recurring-date-generator", category: "Date & Time Tools", isPro: false },
  { id: 58, name: "Timestamp Generator", slug: "timestamp-generator", category: "Date & Time Tools", isPro: false },
  { id: 59, name: "Date Validation Tool", slug: "date-validation-tool", category: "Date & Time Tools", isPro: false },
  { id: 60, name: "Time Validation Tool", slug: "time-validation-tool", category: "Date & Time Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Project Timeline Planner", slug: "project-timeline-planner", category: "Date & Time Tools", isPro: true },
  { id: 62, name: "Gantt Date Calculator", slug: "gantt-date-calculator", category: "Date & Time Tools", isPro: true },
  { id: 63, name: "Business Calendar Engine", slug: "business-calendar-engine", category: "Date & Time Tools", isPro: true },
  { id: 64, name: "Workforce Scheduling Calculator", slug: "workforce-scheduling-calculator", category: "Date & Time Tools", isPro: true },
  { id: 65, name: "Employee Shift Planner", slug: "employee-shift-planner", category: "Date & Time Tools", isPro: true },
  { id: 66, name: "Shift Rotation Planner", slug: "shift-rotation-planner", category: "Date & Time Tools", isPro: true },
  { id: 67, name: "Global Meeting Planner", slug: "global-meeting-planner", category: "Date & Time Tools", isPro: true },
  { id: 68, name: "Multi-Timezone Team Planner", slug: "multi-timezone-team-planner", category: "Date & Time Tools", isPro: true },
  { id: 69, name: "International Scheduling Workspace", slug: "international-scheduling-workspace", category: "Date & Time Tools", isPro: true },
  { id: 70, name: "Deadline Management Workspace", slug: "deadline-management-workspace", category: "Date & Time Tools", isPro: true },
  { id: 71, name: "Contract Deadline Tracker", slug: "contract-deadline-tracker", category: "Date & Time Tools", isPro: true },
  { id: 72, name: "Subscription Renewal Tracker", slug: "subscription-renewal-tracker", category: "Date & Time Tools", isPro: true },
  { id: 73, name: "Recurring Payment Calendar", slug: "recurring-payment-calendar", category: "Date & Time Tools", isPro: true },
  { id: 74, name: "Payroll Calendar Generator", slug: "payroll-calendar-generator", category: "Date & Time Tools", isPro: true },
  { id: 75, name: "Fiscal Year Calculator", slug: "fiscal-year-calculator", category: "Date & Time Tools", isPro: true },
  { id: 76, name: "Fiscal Calendar Generator", slug: "fiscal-calendar-generator", category: "Date & Time Tools", isPro: true },
  { id: 77, name: "Financial Period Calculator", slug: "financial-period-calculator", category: "Date & Time Tools", isPro: true },
  { id: 78, name: "Accounting Period Planner", slug: "accounting-period-planner", category: "Date & Time Tools", isPro: true },
  { id: 79, name: "SLA Deadline Calculator", slug: "sla-deadline-calculator", category: "Date & Time Tools", isPro: true },
  { id: 80, name: "SLA Monitoring Workspace", slug: "sla-monitoring-workspace", category: "Date & Time Tools", isPro: true },
  { id: 81, name: "Event Scheduling Engine", slug: "event-scheduling-engine", category: "Date & Time Tools", isPro: true },
  { id: 82, name: "Appointment Scheduling Calculator", slug: "appointment-scheduling-calculator", category: "Date & Time Tools", isPro: true },
  { id: 83, name: "Availability Window Calculator", slug: "availability-window-calculator", category: "Date & Time Tools", isPro: true },
  { id: 84, name: "Business Hours Calculator", slug: "business-hours-calculator", category: "Date & Time Tools", isPro: true },
  { id: 85, name: "Holiday Calendar Planner", slug: "holiday-calendar-planner", category: "Date & Time Tools", isPro: true },
  { id: 86, name: "Working Time Analyzer", slug: "working-time-analyzer", category: "Date & Time Tools", isPro: true },
  { id: 87, name: "Employee Attendance Time Calculator", slug: "employee-attendance-time-calculator", category: "Date & Time Tools", isPro: true },
  { id: 88, name: "Overtime Period Calculator", slug: "overtime-period-calculator", category: "Date & Time Tools", isPro: true },
  { id: 89, name: "Time Tracking Analyzer", slug: "time-tracking-analyzer", category: "Date & Time Tools", isPro: true },
  { id: 90, name: "Productivity Time Analyzer", slug: "productivity-time-analyzer", category: "Date & Time Tools", isPro: true },
  { id: 91, name: "Time Allocation Dashboard", slug: "time-allocation-dashboard", category: "Date & Time Tools", isPro: true },
  { id: 92, name: "Global Time Intelligence Dashboard", slug: "global-time-intelligence-dashboard", category: "Date & Time Tools", isPro: true },
  { id: 93, name: "Project Time Intelligence Workspace", slug: "project-time-intelligence-workspace", category: "Date & Time Tools", isPro: true },
  { id: 94, name: "Workforce Time Management Workspace", slug: "workforce-time-management-workspace", category: "Date & Time Tools", isPro: true },
  { id: 95, name: "Scheduling Optimization Engine", slug: "scheduling-optimization-engine", category: "Date & Time Tools", isPro: true },
  { id: 96, name: "Timezone Conflict Detector", slug: "timezone-conflict-detector", category: "Date & Time Tools", isPro: true },
  { id: 97, name: "International Operations Calendar", slug: "international-operations-calendar", category: "Date & Time Tools", isPro: true },
  { id: 98, name: "Date & Time API Workspace", slug: "date-and-time-api-workspace", category: "Date & Time Tools", isPro: true },
  { id: 99, name: "Professional Scheduling Platform", slug: "professional-scheduling-platform", category: "Date & Time Tools", isPro: true },
  { id: 100, name: "Global Time Command Center", slug: "global-time-command-center", category: "Date & Time Tools", isPro: true }
];