export interface DesignAccessibilityTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const designAccessibilityToolsList: DesignAccessibilityTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-16) ---
  { id: 1, name: "Color Palette Generator", slug: "color-palette-generator", category: "Design & Accessibility Tools", isPro: false },
  { id: 2, name: "Color Converter", slug: "color-converter", category: "Design & Accessibility Tools", isPro: false },
  { id: 3, name: "Gradient Generator", slug: "gradient-generator", category: "Design & Accessibility Tools", isPro: false },
  { id: 4, name: "Font Pairing Generator", slug: "font-pairing-generator", category: "Design & Accessibility Tools", isPro: false },
  { id: 5, name: "Contrast Checker", slug: "contrast-checker", category: "Design & Accessibility Tools", isPro: false },
  { id: 6, name: "WCAG Contrast Checker", slug: "wcag-contrast-checker", category: "Design & Accessibility Tools", isPro: false },
  { id: 7, name: "Color Blindness Simulator", slug: "color-blindness-simulator", category: "Design & Accessibility Tools", isPro: false },
  { id: 8, name: "Alt Text Generator", slug: "alt-text-generator", category: "Design & Accessibility Tools", isPro: false },
  { id: 9, name: "Heading Structure Checker", slug: "heading-structure-checker", category: "Design & Accessibility Tools", isPro: false },
  { id: 10, name: "Form Accessibility Checker", slug: "form-accessibility-checker", category: "Design & Accessibility Tools", isPro: false },
  { id: 11, name: "Keyboard Navigation Checker", slug: "keyboard-navigation-checker", category: "Design & Accessibility Tools", isPro: false },
  { id: 12, name: "ARIA Validator", slug: "aria-validator", category: "Design & Accessibility Tools", isPro: false },
  { id: 13, name: "Accessibility Statement Generator", slug: "accessibility-statement-generator", category: "Design & Accessibility Tools", isPro: false },
  { id: 14, name: "WCAG Checklist", slug: "wcag-checklist", category: "Design & Accessibility Tools", isPro: false },
  { id: 15, name: "Responsive Breakpoint Calculator", slug: "responsive-breakpoint-calculator", category: "Design & Accessibility Tools", isPro: false },
  { id: 16, name: "Design Token Generator", slug: "design-token-generator", category: "Design & Accessibility Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (17-60) ---
  { id: 17, name: "Color Picker", slug: "color-picker", category: "Design & Accessibility Tools", isPro: false },
  { id: 18, name: "HEX to RGB Converter", slug: "hex-to-rgb-converter", category: "Design & Accessibility Tools", isPro: false },
  { id: 19, name: "RGB to HEX Converter", slug: "rgb-to-hex-converter", category: "Design & Accessibility Tools", isPro: false },
  { id: 20, name: "HEX to HSL Converter", slug: "hex-to-hsl-converter", category: "Design & Accessibility Tools", isPro: false },
  { id: 21, name: "HSL to HEX Converter", slug: "hsl-to-hex-converter", category: "Design & Accessibility Tools", isPro: false },
  { id: 22, name: "RGB to HSL Converter", slug: "rgb-to-hsl-converter", category: "Design & Accessibility Tools", isPro: false },
  { id: 23, name: "HSL to RGB Converter", slug: "hsl-to-rgb-converter", category: "Design & Accessibility Tools", isPro: false },
  { id: 24, name: "Color Palette Extractor", slug: "color-palette-extractor", category: "Design & Accessibility Tools", isPro: false },
  { id: 25, name: "CSS Gradient Generator", slug: "css-gradient-generator", category: "Design & Accessibility Tools", isPro: false },
  { id: 26, name: "CSS Shadow Generator", slug: "css-shadow-generator", category: "Design & Accessibility Tools", isPro: false },
  { id: 27, name: "CSS Border Generator", slug: "css-border-generator", category: "Design & Accessibility Tools", isPro: false },
  { id: 28, name: "CSS Button Generator", slug: "css-button-generator", category: "Design & Accessibility Tools", isPro: false },
  { id: 29, name: "CSS Card Generator", slug: "css-card-generator", category: "Design & Accessibility Tools", isPro: false },
  { id: 30, name: "CSS Glassmorphism Generator", slug: "css-glassmorphism-generator", category: "Design & Accessibility Tools", isPro: false },
  { id: 31, name: "CSS Neumorphism Generator", slug: "css-neumorphism-generator", category: "Design & Accessibility Tools", isPro: false },
  { id: 32, name: "CSS Animation Generator", slug: "css-animation-generator", category: "Design & Accessibility Tools", isPro: false },
  { id: 33, name: "CSS Transform Generator", slug: "css-transform-generator", category: "Design & Accessibility Tools", isPro: false },
  { id: 34, name: "CSS Filter Generator", slug: "css-filter-generator", category: "Design & Accessibility Tools", isPro: false },
  { id: 35, name: "CSS Clip-Path Generator", slug: "css-clip-path-generator", category: "Design & Accessibility Tools", isPro: false },
  { id: 36, name: "CSS Border Radius Generator", slug: "css-border-radius-generator", category: "Design & Accessibility Tools", isPro: false },
  { id: 37, name: "CSS Text Shadow Generator", slug: "css-text-shadow-generator", category: "Design & Accessibility Tools", isPro: false },
  { id: 38, name: "CSS Typography Scale Generator", slug: "css-typography-scale-generator", category: "Design & Accessibility Tools", isPro: false },
  { id: 39, name: "Font Preview Tool", slug: "font-preview-tool", category: "Design & Accessibility Tools", isPro: false },
  { id: 40, name: "Font Identifier", slug: "font-identifier", category: "Design & Accessibility Tools", isPro: false },
  { id: 41, name: "Font Size Converter", slug: "font-size-converter", category: "Design & Accessibility Tools", isPro: false },
  { id: 42, name: "Line Height Calculator", slug: "line-height-calculator", category: "Design & Accessibility Tools", isPro: false },
  { id: 43, name: "Letter Spacing Calculator", slug: "letter-spacing-calculator", category: "Design & Accessibility Tools", isPro: false },
  { id: 44, name: "Color Accessibility Checker", slug: "color-accessibility-checker", category: "Design & Accessibility Tools", isPro: false },
  { id: 45, name: "Focus Indicator Checker", slug: "focus-indicator-checker", category: "Design & Accessibility Tools", isPro: false },
  { id: 46, name: "Touch Target Checker", slug: "touch-target-checker", category: "Design & Accessibility Tools", isPro: false },
  { id: 47, name: "Image Alt Text Checker", slug: "image-alt-text-checker", category: "Design & Accessibility Tools", isPro: false },
  { id: 48, name: "Link Accessibility Checker", slug: "link-accessibility-checker", category: "Design & Accessibility Tools", isPro: false },
  { id: 49, name: "ARIA Label Generator", slug: "aria-label-generator", category: "Design & Accessibility Tools", isPro: false },
  { id: 50, name: "Accessibility Checklist", slug: "accessibility-checklist", category: "Design & Accessibility Tools", isPro: false },
  { id: 51, name: "Accessible Color Palette Generator", slug: "accessible-color-palette-generator", category: "Design & Accessibility Tools", isPro: false },
  { id: 52, name: "Accessible Button Generator", slug: "accessible-button-generator", category: "Design & Accessibility Tools", isPro: false },
  { id: 53, name: "Grid Generator", slug: "grid-generator", category: "Design & Accessibility Tools", isPro: false },
  { id: 54, name: "Layout Generator", slug: "layout-generator", category: "Design & Accessibility Tools", isPro: false },
  { id: 55, name: "Spacing Scale Generator", slug: "spacing-scale-generator", category: "Design & Accessibility Tools", isPro: false },
  { id: 56, name: "Border Radius Scale Generator", slug: "border-radius-scale-generator", category: "Design & Accessibility Tools", isPro: false },
  { id: 57, name: "Icon Size Guide", slug: "icon-size-guide", category: "Design & Accessibility Tools", isPro: false },
  { id: 58, name: "Image Aspect Ratio Tool", slug: "image-aspect-ratio-tool", category: "Design & Accessibility Tools", isPro: false },
  { id: 59, name: "Design Measurement Converter", slug: "design-measurement-converter", category: "Design & Accessibility Tools", isPro: false },
  { id: 60, name: "Pixel Density Calculator", slug: "pixel-density-calculator", category: "Design & Accessibility Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Automated Accessibility Audit", slug: "automated-accessibility-audit", category: "Design & Accessibility Tools", isPro: true },
  { id: 62, name: "Website Accessibility Scanner", slug: "website-accessibility-scanner", category: "Design & Accessibility Tools", isPro: true },
  { id: 63, name: "UI Accessibility Analyzer", slug: "ui-accessibility-analyzer", category: "Design & Accessibility Tools", isPro: true },
  { id: 64, name: "Design System Analyzer", slug: "design-system-analyzer", category: "Design & Accessibility Tools", isPro: true },
  { id: 65, name: "WCAG Compliance Analyzer", slug: "wcag-compliance-analyzer", category: "Design & Accessibility Tools", isPro: true },
  { id: 66, name: "Accessibility Score Calculator", slug: "accessibility-score-calculator", category: "Design & Accessibility Tools", isPro: true },
  { id: 67, name: "PDF Accessibility Checker", slug: "pdf-accessibility-checker", category: "Design & Accessibility Tools", isPro: true },
  { id: 68, name: "Image Accessibility Analyzer", slug: "image-accessibility-analyzer", category: "Design & Accessibility Tools", isPro: true },
  { id: 69, name: "Design System Token Builder", slug: "design-system-token-builder", category: "Design & Accessibility Tools", isPro: true },
  { id: 70, name: "Design Token Converter", slug: "design-token-converter", category: "Design & Accessibility Tools", isPro: true },
  { id: 71, name: "Design Token Validator", slug: "design-token-validator", category: "Design & Accessibility Tools", isPro: true },
  { id: 72, name: "Component Accessibility Auditor", slug: "component-accessibility-auditor", category: "Design & Accessibility Tools", isPro: true },
  { id: 73, name: "Responsive Design Analyzer", slug: "responsive-design-analyzer", category: "Design & Accessibility Tools", isPro: true },
  { id: 74, name: "Mobile UI Checker", slug: "mobile-ui-checker", category: "Design & Accessibility Tools", isPro: true },
  { id: 75, name: "Desktop UI Checker", slug: "desktop-ui-checker", category: "Design & Accessibility Tools", isPro: true },
  { id: 76, name: "Layout Consistency Analyzer", slug: "layout-consistency-analyzer", category: "Design & Accessibility Tools", isPro: true },
  { id: 77, name: "Typography Consistency Analyzer", slug: "typography-consistency-analyzer", category: "Design & Accessibility Tools", isPro: true },
  { id: 78, name: "Color System Analyzer", slug: "color-system-analyzer", category: "Design & Accessibility Tools", isPro: true },
  { id: 79, name: "UI Pattern Analyzer", slug: "ui-pattern-analyzer", category: "Design & Accessibility Tools", isPro: true },
  { id: 80, name: "Visual Hierarchy Analyzer", slug: "visual-hierarchy-analyzer", category: "Design & Accessibility Tools", isPro: true },
  { id: 81, name: "Spacing Consistency Analyzer", slug: "spacing-consistency-analyzer", category: "Design & Accessibility Tools", isPro: true },
  { id: 82, name: "Component Inventory Generator", slug: "component-inventory-generator", category: "Design & Accessibility Tools", isPro: true },
  { id: 83, name: "UI Documentation Generator", slug: "ui-documentation-generator", category: "Design & Accessibility Tools", isPro: true },
  { id: 84, name: "Design Handoff Generator", slug: "design-handoff-generator", category: "Design & Accessibility Tools", isPro: true },
  { id: 85, name: "Developer Design Specification Generator", slug: "developer-design-specification-generator", category: "Design & Accessibility Tools", isPro: true },
  { id: 86, name: "CSS Design System Generator", slug: "css-design-system-generator", category: "Design & Accessibility Tools", isPro: true },
  { id: 87, name: "Accessible Design System Builder", slug: "accessible-design-system-builder", category: "Design & Accessibility Tools", isPro: true },
  { id: 88, name: "Multi-Brand Design System", slug: "multi-brand-design-system", category: "Design & Accessibility Tools", isPro: true },
  { id: 89, name: "Design QA Workspace", slug: "design-qa-workspace", category: "Design & Accessibility Tools", isPro: true },
  { id: 90, name: "UI QA Checklist Generator", slug: "ui-qa-checklist-generator", category: "Design & Accessibility Tools", isPro: true },
  { id: 91, name: "Visual Regression Checklist", slug: "visual-regression-checklist", category: "Design & Accessibility Tools", isPro: true },
  { id: 92, name: "Accessibility Regression Checker", slug: "accessibility-regression-checker", category: "Design & Accessibility Tools", isPro: true },
  { id: 93, name: "Cross-Device UI Analyzer", slug: "cross-device-ui-analyzer", category: "Design & Accessibility Tools", isPro: true },
  { id: 94, name: "Cross-Browser UI Checklist", slug: "cross-browser-ui-checklist", category: "Design & Accessibility Tools", isPro: true },
  { id: 95, name: "UX Heuristic Checklist", slug: "ux-heuristic-checklist", category: "Design & Accessibility Tools", isPro: true },
  { id: 96, name: "UX Audit Report Generator", slug: "ux-audit-report-generator", category: "Design & Accessibility Tools", isPro: true },
  { id: 97, name: "UI/UX Audit Workspace", slug: "ui-ux-audit-workspace", category: "Design & Accessibility Tools", isPro: true },
  { id: 98, name: "Accessibility Management Dashboard", slug: "accessibility-management-dashboard", category: "Design & Accessibility Tools", isPro: true },
  { id: 99, name: "Enterprise Design System Workspace", slug: "enterprise-design-system-workspace", category: "Design & Accessibility Tools", isPro: true },
  { id: 100, name: "Inclusive Design Intelligence Workspace", slug: "inclusive-design-intelligence-workspace", category: "Design & Accessibility Tools", isPro: true },
];