export interface DeveloperTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const developerToolsList: DeveloperTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-35) ---
  { id: 1, name: "JSON Formatter", slug: "json-formatter-dev", category: "Developer Tools", isPro: false },
  { id: 2, name: "JSON Validator", slug: "json-validator-dev", category: "Developer Tools", isPro: false },
  { id: 3, name: "JSON Viewer", slug: "json-viewer", category: "Developer Tools", isPro: false },
  { id: 4, name: "JSON to CSV Converter", slug: "json-to-csv-converter", category: "Developer Tools", isPro: false },
  { id: 5, name: "CSV to JSON Converter", slug: "csv-to-json-converter", category: "Developer Tools", isPro: false },
  { id: 6, name: "JSON to XML Converter", slug: "json-to-xml-converter", category: "Developer Tools", isPro: false },
  { id: 7, name: "XML to JSON Converter", slug: "xml-to-json-converter", category: "Developer Tools", isPro: false },
  { id: 8, name: "YAML Validator", slug: "yaml-validator-dev", category: "Developer Tools", isPro: false },
  { id: 9, name: "YAML Formatter", slug: "yaml-formatter-dev", category: "Developer Tools", isPro: false },
  { id: 10, name: "CSV Formatter", slug: "csv-formatter-dev", category: "Developer Tools", isPro: false },
  { id: 11, name: "CSV Validator", slug: "csv-validator-dev", category: "Developer Tools", isPro: false },
  { id: 12, name: "SQL Formatter", slug: "sql-formatter", category: "Developer Tools", isPro: false },
  { id: 13, name: "SQL Query Validator", slug: "sql-query-validator", category: "Developer Tools", isPro: false },
  { id: 14, name: "HTML Formatter", slug: "html-formatter-dev", category: "Developer Tools", isPro: false },
  { id: 15, name: "HTML Minifier", slug: "html-minifier-dev", category: "Developer Tools", isPro: false },
  { id: 16, name: "CSS Formatter", slug: "css-formatter-dev", category: "Developer Tools", isPro: false },
  { id: 17, name: "CSS Minifier", slug: "css-minifier-dev", category: "Developer Tools", isPro: false },
  { id: 18, name: "JavaScript Formatter", slug: "javascript-formatter", category: "Developer Tools", isPro: false },
  { id: 19, name: "JavaScript Minifier", slug: "javascript-minifier", category: "Developer Tools", isPro: false },
  { id: 20, name: "Code Diff Checker", slug: "code-diff-checker", category: "Developer Tools", isPro: false },
  { id: 21, name: "Regex Tester", slug: "regex-tester", category: "Developer Tools", isPro: false },
  { id: 22, name: "Regex Generator", slug: "regex-generator", category: "Developer Tools", isPro: false },
  { id: 23, name: "Regex Explainer", slug: "regex-explainer", category: "Developer Tools", isPro: false },
  { id: 24, name: "Base64 Encoder", slug: "base64-encoder", category: "Developer Tools", isPro: false },
  { id: 25, name: "Base64 Decoder", slug: "base64-decoder", category: "Developer Tools", isPro: false },
  { id: 26, name: "JWT Decoder", slug: "jwt-decoder", category: "Developer Tools", isPro: false },
  { id: 27, name: "JWT Generator", slug: "jwt-generator", category: "Developer Tools", isPro: false },
  { id: 28, name: "UUID Generator", slug: "uuid-generator", category: "Developer Tools", isPro: false },
  { id: 29, name: "Hash Generator", slug: "hash-generator", category: "Developer Tools", isPro: false },
  { id: 30, name: "SHA256 Generator", slug: "sha256-generator", category: "Developer Tools", isPro: false },
  { id: 31, name: "Timestamp Converter", slug: "timestamp-converter", category: "Developer Tools", isPro: false },
  { id: 32, name: "Unix Timestamp Converter", slug: "unix-timestamp-converter", category: "Developer Tools", isPro: false },
  { id: 33, name: "Cron Expression Generator", slug: "cron-expression-generator", category: "Developer Tools", isPro: false },
  { id: 34, name: "API Request Builder", slug: "api-request-builder", category: "Developer Tools", isPro: false },
  { id: 35, name: "REST API Tester", slug: "rest-api-tester", category: "Developer Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (36-60) ---
  { id: 36, name: "Webhook Tester", slug: "webhook-tester", category: "Developer Tools", isPro: false },
  { id: 37, name: "JSON Minifier", slug: "json-minifier-dev", category: "Developer Tools", isPro: false },
  { id: 38, name: "JSON Beautifier", slug: "json-beautifier", category: "Developer Tools", isPro: false },
  { id: 39, name: "YAML to JSON Converter", slug: "yaml-to-json-converter", category: "Developer Tools", isPro: false },
  { id: 40, name: "JSON to YAML Converter", slug: "json-to-yaml-converter", category: "Developer Tools", isPro: false },
  { id: 41, name: "XML Formatter", slug: "xml-formatter-dev", category: "Developer Tools", isPro: false },
  { id: 42, name: "XML Validator", slug: "xml-validator-dev", category: "Developer Tools", isPro: false },
  { id: 43, name: "XML Minifier", slug: "xml-minifier-dev", category: "Developer Tools", isPro: false },
  { id: 44, name: "YAML to CSV Converter", slug: "yaml-to-csv-converter", category: "Developer Tools", isPro: false },
  { id: 45, name: "CSV Viewer", slug: "csv-viewer", category: "Developer Tools", isPro: false },
  { id: 46, name: "CSV Cleaner", slug: "csv-cleaner", category: "Developer Tools", isPro: false },
  { id: 47, name: "SQL Minifier", slug: "sql-minifier", category: "Developer Tools", isPro: false },
  { id: 48, name: "SQL Beautifier", slug: "sql-beautifier", category: "Developer Tools", isPro: false },
  { id: 49, name: "SQL to JSON Converter", slug: "sql-to-json-converter", category: "Developer Tools", isPro: false },
  { id: 50, name: "SQL to CSV Converter", slug: "sql-to-csv-converter", category: "Developer Tools", isPro: false },
  { id: 51, name: "HTML Validator", slug: "html-validator-dev", category: "Developer Tools", isPro: false },
  { id: 52, name: "CSS Validator", slug: "css-validator-dev", category: "Developer Tools", isPro: false },
  { id: 53, name: "JavaScript Validator", slug: "javascript-validator", category: "Developer Tools", isPro: false },
  { id: 54, name: "TypeScript Playground", slug: "typescript-playground", category: "Developer Tools", isPro: false },
  { id: 55, name: "Code Formatter", slug: "code-formatter", category: "Developer Tools", isPro: false },
  { id: 56, name: "Code Minifier", slug: "code-minifier", category: "Developer Tools", isPro: false },
  { id: 57, name: "Code Beautifier", slug: "code-beautifier", category: "Developer Tools", isPro: false },
  { id: 58, name: "Code Compare Tool", slug: "code-compare-tool", category: "Developer Tools", isPro: false },
  { id: 59, name: "Regex Debugger", slug: "regex-debugger", category: "Developer Tools", isPro: false },
  { id: 60, name: "Nano ID Generator", slug: "nano-id-generator", category: "Developer Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "OpenAPI Validator", slug: "openapi-validator", category: "Developer Tools", isPro: true },
  { id: 62, name: "OpenAPI Generator", slug: "openapi-generator", category: "Developer Tools", isPro: true },
  { id: 63, name: "API Documentation Generator", slug: "api-documentation-generator", category: "Developer Tools", isPro: true },
  { id: 64, name: "API Mock Generator", slug: "api-mock-generator", category: "Developer Tools", isPro: true },
  { id: 65, name: "GraphQL Query Tester", slug: "graphql-query-tester", category: "Developer Tools", isPro: true },
  { id: 66, name: "GraphQL Schema Validator", slug: "graphql-schema-validator", category: "Developer Tools", isPro: true },
  { id: 67, name: "Database ER Diagram Generator", slug: "database-er-diagram-generator", category: "Developer Tools", isPro: true },
  { id: 68, name: "Test Data Generator", slug: "test-data-generator", category: "Developer Tools", isPro: true },
  { id: 69, name: "Code Complexity Analyzer", slug: "code-complexity-analyzer", category: "Developer Tools", isPro: true },
  { id: 70, name: "Code Quality Analyzer", slug: "code-quality-analyzer", category: "Developer Tools", isPro: true },
  { id: 71, name: "Technical Debt Analyzer", slug: "technical-debt-analyzer", category: "Developer Tools", isPro: true },
  { id: 72, name: "CI/CD Pipeline Generator", slug: "cicd-pipeline-generator", category: "Developer Tools", isPro: true },
  { id: 73, name: "GitHub Actions Generator", slug: "github-actions-generator", category: "Developer Tools", isPro: true },
  { id: 74, name: "Kubernetes Manifest Validator", slug: "kubernetes-manifest-validator", category: "Developer Tools", isPro: true },
  { id: 75, name: "Code Dependency Analyzer", slug: "code-dependency-analyzer", category: "Developer Tools", isPro: true },
  { id: 76, name: "Cron Expression Parser", slug: "cron-expression-parser", category: "Developer Tools", isPro: true },
  { id: 77, name: "Cron Expression Validator", slug: "cron-expression-validator", category: "Developer Tools", isPro: true },
  { id: 78, name: "Git Command Generator", slug: "git-command-generator", category: "Developer Tools", isPro: true },
  { id: 79, name: "Gitignore Generator", slug: "gitignore-generator", category: "Developer Tools", isPro: true },
  { id: 80, name: "Dockerfile Generator", slug: "dockerfile-generator", category: "Developer Tools", isPro: true },
  { id: 81, name: "Docker Compose Generator", slug: "docker-compose-generator", category: "Developer Tools", isPro: true },
  { id: 82, name: "Kubernetes YAML Generator", slug: "kubernetes-yaml-generator", category: "Developer Tools", isPro: true },
  { id: 83, name: "Nginx Configuration Generator", slug: "nginx-configuration-generator", category: "Developer Tools", isPro: true },
  { id: 84, name: "Apache Configuration Generator", slug: "apache-configuration-generator", category: "Developer Tools", isPro: true },
  { id: 85, name: "HTTP Request Builder", slug: "http-request-builder", category: "Developer Tools", isPro: true },
  { id: 86, name: "HTTP Header Analyzer", slug: "http-header-analyzer", category: "Developer Tools", isPro: true },
  { id: 87, name: "HTTP Response Analyzer", slug: "http-response-analyzer", category: "Developer Tools", isPro: true },
  { id: 88, name: "Webhook Payload Generator", slug: "webhook-payload-generator", category: "Developer Tools", isPro: true },
  { id: 89, name: "WebSocket Tester", slug: "websocket-tester", category: "Developer Tools", isPro: true },
  { id: 90, name: "OAuth URL Generator", slug: "oauth-url-generator", category: "Developer Tools", isPro: true },
  { id: 91, name: "CORS Tester", slug: "cors-tester", category: "Developer Tools", isPro: true },
  { id: 92, name: "CSP Generator", slug: "csp-generator", category: "Developer Tools", isPro: true },
  { id: 93, name: "SQL Schema Generator", slug: "sql-schema-generator", category: "Developer Tools", isPro: true },
  { id: 94, name: "Database Seed Generator", slug: "database-seed-generator", category: "Developer Tools", isPro: true },
  { id: 95, name: "Mock JSON Generator", slug: "mock-json-generator", category: "Developer Tools", isPro: true },
  { id: 96, name: "Package Version Checker", slug: "package-version-checker", category: "Developer Tools", isPro: true },
  { id: 97, name: "Semantic Version Calculator", slug: "semantic-version-calculator", category: "Developer Tools", isPro: true },
  { id: 98, name: "MD5 Generator", slug: "md5-generator", category: "Developer Tools", isPro: true },
  { id: 99, name: "URL Encoder", slug: "url-encoder-dev", category: "Developer Tools", isPro: true },
  { id: 100, name: "Developer Toolbox Workspace", slug: "developer-toolbox-workspace", category: "Developer Tools", isPro: true },
];