export interface EducationTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const educationToolsList: EducationTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-14) ---
  { id: 1, name: "Essay Outline Generator", slug: "essay-outline-generator", category: "Education Tools", isPro: false },
  { id: 2, name: "Citation Generator", slug: "citation-generator", category: "Education Tools", isPro: false },
  { id: 3, name: "APA Citation Generator", slug: "apa-citation-generator", category: "Education Tools", isPro: false },
  { id: 4, name: "MLA Citation Generator", slug: "mla-citation-generator", category: "Education Tools", isPro: false },
  { id: 5, name: "Study Guide Generator", slug: "study-guide-generator", category: "Education Tools", isPro: false },
  { id: 6, name: "Flashcard Generator", slug: "flashcard-generator", category: "Education Tools", isPro: false },
  { id: 7, name: "Quiz Generator", slug: "quiz-generator", category: "Education Tools", isPro: false },
  { id: 8, name: "Practice Test Generator", slug: "practice-test-generator", category: "Education Tools", isPro: false },
  { id: 9, name: "Lesson Plan Generator", slug: "lesson-plan-generator", category: "Education Tools", isPro: false },
  { id: 10, name: "Grade Calculator", slug: "grade-calculator", category: "Education Tools", isPro: false },
  { id: 11, name: "GPA Calculator", slug: "gpa-calculator", category: "Education Tools", isPro: false },
  { id: 12, name: "Final Grade Calculator", slug: "final-grade-calculator", category: "Education Tools", isPro: false },
  { id: 13, name: "Attendance Calculator", slug: "attendance-calculator", category: "Education Tools", isPro: false },
  { id: 14, name: "Study Schedule Generator", slug: "study-schedule-generator", category: "Education Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (15-60) ---
  { id: 15, name: "Essay Topic Generator", slug: "essay-topic-generator", category: "Education Tools", isPro: false },
  { id: 16, name: "Essay Introduction Generator", slug: "essay-introduction-generator", category: "Education Tools", isPro: false },
  { id: 17, name: "Essay Conclusion Generator", slug: "essay-conclusion-generator", category: "Education Tools", isPro: false },
  { id: 18, name: "Essay Planner", slug: "essay-planner", category: "Education Tools", isPro: false },
  { id: 19, name: "Essay Word Counter", slug: "essay-word-counter", category: "Education Tools", isPro: false },
  { id: 20, name: "Bibliography Generator", slug: "bibliography-generator", category: "Education Tools", isPro: false },
  { id: 21, name: "Reference Generator", slug: "reference-generator", category: "Education Tools", isPro: false },
  { id: 22, name: "Chicago Citation Generator", slug: "chicago-citation-generator", category: "Education Tools", isPro: false },
  { id: 23, name: "Harvard Citation Generator", slug: "harvard-citation-generator", category: "Education Tools", isPro: false },
  { id: 24, name: "IEEE Citation Generator", slug: "ieee-citation-generator", category: "Education Tools", isPro: false },
  { id: 25, name: "Citation Formatter", slug: "citation-formatter", category: "Education Tools", isPro: false },
  { id: 26, name: "Research Question Generator", slug: "research-question-generator", category: "Education Tools", isPro: false },
  { id: 27, name: "Thesis Statement Generator", slug: "thesis-statement-generator", category: "Education Tools", isPro: false },
  { id: 28, name: "Study Notes Generator", slug: "study-notes-generator", category: "Education Tools", isPro: false },
  { id: 29, name: "Multiple Choice Question Generator", slug: "multiple-choice-question-generator", category: "Education Tools", isPro: false },
  { id: 30, name: "True/False Question Generator", slug: "true-false-question-generator", category: "Education Tools", isPro: false },
  { id: 31, name: "Fill-in-the-Blank Generator", slug: "fill-in-the-blank-generator", category: "Education Tools", isPro: false },
  { id: 32, name: "Worksheet Generator", slug: "worksheet-generator", category: "Education Tools", isPro: false },
  { id: 33, name: "Course Outline Generator", slug: "course-outline-generator", category: "Education Tools", isPro: false },
  { id: 34, name: "Curriculum Planner", slug: "curriculum-planner", category: "Education Tools", isPro: false },
  { id: 35, name: "Assignment Planner", slug: "assignment-planner", category: "Education Tools", isPro: false },
  { id: 36, name: "Homework Planner", slug: "homework-planner", category: "Education Tools", isPro: false },
  { id: 37, name: "Exam Countdown Calculator", slug: "exam-countdown-calculator", category: "Education Tools", isPro: false },
  { id: 38, name: "Weighted Grade Calculator", slug: "weighted-grade-calculator", category: "Education Tools", isPro: false },
  { id: 39, name: "Exam Score Calculator", slug: "exam-score-calculator", category: "Education Tools", isPro: false },
  { id: 40, name: "Percentage Calculator", slug: "percentage-calculator-edu", category: "Education Tools", isPro: false },
  { id: 41, name: "Study Time Calculator", slug: "study-time-calculator", category: "Education Tools", isPro: false },
  { id: 42, name: "Pomodoro Study Timer", slug: "pomodoro-study-timer", category: "Education Tools", isPro: false },
  { id: 43, name: "Reading Time Calculator", slug: "reading-time-calculator-edu", category: "Education Tools", isPro: false },
  { id: 44, name: "Words Per Minute Calculator", slug: "words-per-minute-calculator", category: "Education Tools", isPro: false },
  { id: 45, name: "Typing Speed Calculator", slug: "typing-speed-calculator", category: "Education Tools", isPro: false },
  { id: 46, name: "Academic Word Counter", slug: "academic-word-counter", category: "Education Tools", isPro: false },
  { id: 47, name: "Readability Checker", slug: "readability-checker-edu", category: "Education Tools", isPro: false },
  { id: 48, name: "Plagiarism Checker", slug: "plagiarism-checker", category: "Education Tools", isPro: false },
  { id: 49, name: "Paraphrasing Tool", slug: "paraphrasing-tool-edu", category: "Education Tools", isPro: false },
  { id: 50, name: "Grammar Checker", slug: "grammar-checker-edu", category: "Education Tools", isPro: false },
  { id: 51, name: "Spelling Checker", slug: "spelling-checker-edu", category: "Education Tools", isPro: false },
  { id: 52, name: "Vocabulary Builder", slug: "vocabulary-builder", category: "Education Tools", isPro: false },
  { id: 53, name: "Synonym Finder", slug: "synonym-finder", category: "Education Tools", isPro: false },
  { id: 54, name: "Antonym Finder", slug: "antonym-finder", category: "Education Tools", isPro: false },
  { id: 55, name: "Definition Finder", slug: "definition-finder", category: "Education Tools", isPro: false },
  { id: 56, name: "Dictionary Tool", slug: "dictionary-tool", category: "Education Tools", isPro: false },
  { id: 57, name: "Language Learning Flashcards", slug: "language-learning-flashcards", category: "Education Tools", isPro: false },
  { id: 58, name: "Educational Crossword Generator", slug: "educational-crossword-generator", category: "Education Tools", isPro: false },
  { id: 59, name: "Word Search Generator", slug: "word-search-generator", category: "Education Tools", isPro: false },
  { id: 60, name: "Classroom Activity Generator", slug: "classroom-activity-generator", category: "Education Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-67) ---
  { id: 61, name: "AI Tutor", slug: "ai-tutor", category: "Education Tools", isPro: true },
  { id: 62, name: "AI Study Assistant", slug: "ai-study-assistant", category: "Education Tools", isPro: true },
  { id: 63, name: "AI Homework Assistant", slug: "ai-homework-assistant", category: "Education Tools", isPro: true },
  { id: 64, name: "AI Exam Prep Assistant", slug: "ai-exam-prep-assistant", category: "Education Tools", isPro: true },
  { id: 65, name: "AI Personalized Study Planner", slug: "ai-personalized-study-planner", category: "Education Tools", isPro: true },
  { id: 66, name: "Learning Progress Tracker", slug: "learning-progress-tracker", category: "Education Tools", isPro: true },
  { id: 67, name: "AI Study Workspace", slug: "ai-study-workspace", category: "Education Tools", isPro: true },

  // --- REMAINING PRO LEVEL TOOLS (68-100) ---
  { id: 68, name: "Adaptive Quiz Generator", slug: "adaptive-quiz-generator", category: "Education Tools", isPro: true },
  { id: 69, name: "Adaptive Learning Planner", slug: "adaptive-learning-planner", category: "Education Tools", isPro: true },
  { id: 70, name: "Knowledge Gap Analyzer", slug: "knowledge-gap-analyzer", category: "Education Tools", isPro: true },
  { id: 71, name: "Student Performance Analyzer", slug: "student-performance-analyzer", category: "Education Tools", isPro: true },
  { id: 72, name: "Exam Performance Analyzer", slug: "exam-performance-analyzer", category: "Education Tools", isPro: true },
  { id: 73, name: "Grade Prediction Tool", slug: "grade-prediction-tool", category: "Education Tools", isPro: true },
  { id: 74, name: "GPA Forecasting Tool", slug: "gpa-forecasting-tool", category: "Education Tools", isPro: true },
  { id: 75, name: "Course Grade Planner", slug: "course-grade-planner", category: "Education Tools", isPro: true },
  { id: 76, name: "Degree Planner", slug: "degree-planner", category: "Education Tools", isPro: true },
  { id: 77, name: "Academic Roadmap Generator", slug: "academic-roadmap-generator", category: "Education Tools", isPro: true },
  { id: 78, name: "Career Pathway Planner", slug: "career-pathway-planner", category: "Education Tools", isPro: true },
  { id: 79, name: "Research Paper Planner", slug: "research-paper-planner", category: "Education Tools", isPro: true },
  { id: 80, name: "Literature Review Organizer", slug: "literature-review-organizer", category: "Education Tools", isPro: true },
  { id: 81, name: "Research Source Organizer", slug: "research-source-organizer", category: "Education Tools", isPro: true },
  { id: 82, name: "Research Paper Citation Manager", slug: "research-paper-citation-manager", category: "Education Tools", isPro: true },
  { id: 83, name: "Academic PDF Analyzer", slug: "academic-pdf-analyzer", category: "Education Tools", isPro: true },
  { id: 84, name: "Academic Paper Summarizer", slug: "academic-paper-summarizer", category: "Education Tools", isPro: true },
  { id: 85, name: "Academic Paper Question Answering", slug: "academic-paper-question-answering", category: "Education Tools", isPro: true },
  { id: 86, name: "Research Data Analyzer", slug: "research-data-analyzer", category: "Education Tools", isPro: true },
  { id: 87, name: "Survey Question Generator", slug: "survey-question-generator-edu", category: "Education Tools", isPro: true },
  { id: 88, name: "Survey Analyzer", slug: "survey-analyzer-edu", category: "Education Tools", isPro: true },
  { id: 89, name: "Classroom Quiz Dashboard", slug: "classroom-quiz-dashboard", category: "Education Tools", isPro: true },
  { id: 90, name: "Teacher Assessment Generator", slug: "teacher-assessment-generator", category: "Education Tools", isPro: true },
  { id: 91, name: "Rubric Generator", slug: "rubric-generator", category: "Education Tools", isPro: true },
  { id: 92, name: "Grading Rubric Calculator", slug: "grading-rubric-calculator", category: "Education Tools", isPro: true },
  { id: 93, name: "Learning Objective Generator", slug: "learning-objective-generator", category: "Education Tools", isPro: true },
  { id: 94, name: "Bloom's Taxonomy Question Generator", slug: "blooms-taxonomy-question-generator", category: "Education Tools", isPro: true },
  { id: 95, name: "Course Assessment Planner", slug: "course-assessment-planner", category: "Education Tools", isPro: true },
  { id: 96, name: "Online Course Planner", slug: "online-course-planner", category: "Education Tools", isPro: true },
  { id: 97, name: "Student Portfolio Builder", slug: "student-portfolio-builder", category: "Education Tools", isPro: true },
  { id: 98, name: "Academic Progress Dashboard", slug: "academic-progress-dashboard", category: "Education Tools", isPro: true },
  { id: 99, name: "Learning Analytics Dashboard", slug: "learning-analytics-dashboard", category: "Education Tools", isPro: true },
  { id: 100, name: "Education Management Workspace", slug: "education-management-workspace", category: "Education Tools", isPro: true },
];