export interface EmailTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const emailToolsList: EmailTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-15) ---
  { id: 1, name: "Email Writer", slug: "email-writer", category: "Email Tools", isPro: false },
  { id: 2, name: "Email Reply Generator", slug: "email-reply-generator", category: "Email Tools", isPro: false },
  { id: 3, name: "Email Subject Generator", slug: "email-subject-generator", category: "Email Tools", isPro: false },
  { id: 4, name: "Professional Email Generator", slug: "professional-email-generator", category: "Email Tools", isPro: false },
  { id: 5, name: "Follow-Up Email Generator", slug: "follow-up-email-generator", category: "Email Tools", isPro: false },
  { id: 6, name: "Cold Email Generator", slug: "cold-email-generator", category: "Email Tools", isPro: false },
  { id: 7, name: "Sales Email Generator", slug: "sales-email-generator", category: "Email Tools", isPro: false },
  { id: 8, name: "Subject Line Analyzer", slug: "subject-line-analyzer", category: "Email Tools", isPro: false },
  { id: 9, name: "Email Spam Word Checker", slug: "email-spam-word-checker", category: "Email Tools", isPro: false },
  { id: 10, name: "Email Signature Generator", slug: "email-signature-generator", category: "Email Tools", isPro: false },
  { id: 11, name: "Email Open Rate Calculator", slug: "email-open-rate-calculator", category: "Email Tools", isPro: false },
  { id: 12, name: "Email Introduction Generator", slug: "email-introduction-generator", category: "Email Tools", isPro: false },
  { id: 13, name: "Email Closing Generator", slug: "email-closing-generator", category: "Email Tools", isPro: false },
  { id: 14, name: "Business Email Generator", slug: "business-email-generator", category: "Email Tools", isPro: false },
  { id: 15, name: "Outreach Email Generator", slug: "outreach-email-generator", category: "Email Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (16-60) ---
  { id: 16, name: "Networking Email Generator", slug: "networking-email-generator", category: "Email Tools", isPro: false },
  { id: 17, name: "Thank You Email Generator", slug: "thank-you-email-generator", category: "Email Tools", isPro: false },
  { id: 18, name: "Apology Email Generator", slug: "apology-email-generator", category: "Email Tools", isPro: false },
  { id: 19, name: "Complaint Email Generator", slug: "complaint-email-generator", category: "Email Tools", isPro: false },
  { id: 20, name: "Request Email Generator", slug: "request-email-generator", category: "Email Tools", isPro: false },
  { id: 21, name: "Reminder Email Generator", slug: "reminder-email-generator", category: "Email Tools", isPro: false },
  { id: 22, name: "Meeting Request Email Generator", slug: "meeting-request-email-generator", category: "Email Tools", isPro: false },
  { id: 23, name: "Meeting Confirmation Email Generator", slug: "meeting-confirmation-email-generator", category: "Email Tools", isPro: false },
  { id: 24, name: "Rescheduling Email Generator", slug: "rescheduling-email-generator", category: "Email Tools", isPro: false },
  { id: 25, name: "Cancellation Email Generator", slug: "cancellation-email-generator", category: "Email Tools", isPro: false },
  { id: 26, name: "Job Application Email Generator", slug: "job-application-email-generator", category: "Email Tools", isPro: false },
  { id: 27, name: "Interview Follow-Up Email Generator", slug: "interview-follow-up-email-generator", category: "Email Tools", isPro: false },
  { id: 28, name: "Resignation Email Generator", slug: "resignation-email-generator", category: "Email Tools", isPro: false },
  { id: 29, name: "Welcome Email Generator", slug: "welcome-email-generator", category: "Email Tools", isPro: false },
  { id: 30, name: "Onboarding Email Generator", slug: "onboarding-email-generator", category: "Email Tools", isPro: false },
  { id: 31, name: "Customer Support Email Generator", slug: "customer-support-email-generator", category: "Email Tools", isPro: false },
  { id: 32, name: "Refund Email Generator", slug: "refund-email-generator", category: "Email Tools", isPro: false },
  { id: 33, name: "Review Request Email Generator", slug: "review-request-email-generator", category: "Email Tools", isPro: false },
  { id: 34, name: "Testimonial Request Email Generator", slug: "testimonial-request-email-generator", category: "Email Tools", isPro: false },
  { id: 35, name: "Newsletter Generator", slug: "newsletter-generator", category: "Email Tools", isPro: false },
  { id: 36, name: "Email Announcement Generator", slug: "email-announcement-generator", category: "Email Tools", isPro: false },
  { id: 37, name: "Product Launch Email Generator", slug: "product-launch-email-generator", category: "Email Tools", isPro: false },
  { id: 38, name: "Promotion Email Generator", slug: "promotion-email-generator", category: "Email Tools", isPro: false },
  { id: 39, name: "Event Invitation Email Generator", slug: "event-invitation-email-generator", category: "Email Tools", isPro: false },
  { id: 40, name: "Webinar Invitation Email Generator", slug: "webinar-invitation-email-generator", category: "Email Tools", isPro: false },
  { id: 41, name: "Event Reminder Email Generator", slug: "event-reminder-email-generator", category: "Email Tools", isPro: false },
  { id: 42, name: "HTML Email Signature Generator", slug: "html-email-signature-generator", category: "Email Tools", isPro: false },
  { id: 43, name: "Email Template Generator", slug: "email-template-generator", category: "Email Tools", isPro: false },
  { id: 44, name: "Email Template Formatter", slug: "email-template-formatter", category: "Email Tools", isPro: false },
  { id: 45, name: "Email HTML Generator", slug: "email-html-generator", category: "Email Tools", isPro: false },
  { id: 46, name: "Email HTML Previewer", slug: "email-html-previewer", category: "Email Tools", isPro: false },
  { id: 47, name: "Email Character Counter", slug: "email-character-counter", category: "Email Tools", isPro: false },
  { id: 48, name: "Email Word Counter", slug: "email-word-counter", category: "Email Tools", isPro: false },
  { id: 49, name: "Email Readability Checker", slug: "email-readability-checker", category: "Email Tools", isPro: false },
  { id: 50, name: "Email Tone Checker", slug: "email-tone-checker", category: "Email Tools", isPro: false },
  { id: 51, name: "Email Grammar Checker", slug: "email-grammar-checker", category: "Email Tools", isPro: false },
  { id: 52, name: "Email Preview Tool", slug: "email-preview-tool", category: "Email Tools", isPro: false },
  { id: 53, name: "Email Mobile Preview", slug: "email-mobile-preview", category: "Email Tools", isPro: false },
  { id: 54, name: "Email Link Checker", slug: "email-link-checker", category: "Email Tools", isPro: false },
  { id: 55, name: "Email Image Checker", slug: "email-image-checker", category: "Email Tools", isPro: false },
  { id: 56, name: "Email CTA Analyzer", slug: "email-cta-analyzer", category: "Email Tools", isPro: false },
  { id: 57, name: "Email Length Analyzer", slug: "email-length-analyzer", category: "Email Tools", isPro: false },
  { id: 58, name: "Email Personalization Generator", slug: "email-personalization-generator", category: "Email Tools", isPro: false },
  { id: 59, name: "Email A/B Test Generator", slug: "email-ab-test-generator", category: "Email Tools", isPro: false },
  { id: 60, name: "Email ROI Calculator", slug: "email-roi-calculator", category: "Email Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Email Sequence Generator", slug: "email-sequence-generator", category: "Email Tools", isPro: true },
  { id: 62, name: "Cold Email Personalizer", slug: "cold-email-personalizer", category: "Email Tools", isPro: true },
  { id: 63, name: "Email List Cleaner", slug: "email-list-cleaner", category: "Email Tools", isPro: true },
  { id: 64, name: "Email Deliverability Tester", slug: "email-deliverability-tester", category: "Email Tools", isPro: true },
  { id: 65, name: "SPF Record Generator", slug: "spf-record-generator", category: "Email Tools", isPro: true },
  { id: 66, name: "DKIM Record Generator", slug: "dkim-record-generator", category: "Email Tools", isPro: true },
  { id: 67, name: "DMARC Analyzer", slug: "dmarc-analyzer", category: "Email Tools", isPro: true },
  { id: 68, name: "Email Reputation Checker", slug: "email-reputation-checker", category: "Email Tools", isPro: true },
  { id: 69, name: "Email Marketing ROI Dashboard", slug: "email-marketing-roi-dashboard", category: "Email Tools", isPro: true },
  { id: 70, name: "AI Sales Email Personalizer", slug: "ai-sales-email-personalizer", category: "Email Tools", isPro: true },
  { id: 71, name: "Automated Follow-Up Sequence Builder", slug: "automated-follow-up-sequence-builder", category: "Email Tools", isPro: true },
  { id: 72, name: "Lead Nurture Sequence Builder", slug: "lead-nurture-sequence-builder", category: "Email Tools", isPro: true },
  { id: 73, name: "Customer Onboarding Sequence Builder", slug: "customer-onboarding-sequence-builder", category: "Email Tools", isPro: true },
  { id: 74, name: "Customer Retention Sequence Builder", slug: "customer-retention-sequence-builder", category: "Email Tools", isPro: true },
  { id: 75, name: "Abandoned Cart Email Sequence", slug: "abandoned-cart-email-sequence", category: "Email Tools", isPro: true },
  { id: 76, name: "Re-Engagement Email Sequence", slug: "re-engagement-email-sequence", category: "Email Tools", isPro: true },
  { id: 77, name: "Email Drip Campaign Builder", slug: "email-drip-campaign-builder", category: "Email Tools", isPro: true },
  { id: 78, name: "Email Funnel Builder", slug: "email-funnel-builder", category: "Email Tools", isPro: true },
  { id: 79, name: "Email Campaign Planner", slug: "email-campaign-planner", category: "Email Tools", isPro: true },
  { id: 80, name: "Email Segmentation Tool", slug: "email-segmentation-tool", category: "Email Tools", isPro: true },
  { id: 81, name: "Email List Deduplicator", slug: "email-list-deduplicator", category: "Email Tools", isPro: true },
  { id: 82, name: "Email Syntax Validator", slug: "email-syntax-validator", category: "Email Tools", isPro: true },
  { id: 83, name: "Email Domain Validator", slug: "email-domain-validator", category: "Email Tools", isPro: true },
  { id: 84, name: "Email Authentication Checker", slug: "email-authentication-checker", category: "Email Tools", isPro: true },
  { id: 85, name: "DMARC Record Generator", slug: "dmarc-record-generator", category: "Email Tools", isPro: true },
  { id: 86, name: "Email Blacklist Checker", slug: "email-blacklist-checker", category: "Email Tools", isPro: true },
  { id: 87, name: "Email Bounce Rate Calculator", slug: "email-bounce-rate-calculator", category: "Email Tools", isPro: true },
  { id: 88, name: "Email Click Rate Calculator", slug: "email-click-rate-calculator", category: "Email Tools", isPro: true },
  { id: 89, name: "Email Click-to-Open Rate Calculator", slug: "email-click-to-open-rate-calculator", category: "Email Tools", isPro: true },
  { id: 90, name: "Email Conversion Calculator", slug: "email-conversion-calculator", category: "Email Tools", isPro: true },
  { id: 91, name: "Email Revenue Forecast", slug: "email-revenue-forecast", category: "Email Tools", isPro: true },
  { id: 92, name: "Email Campaign Performance Analyzer", slug: "email-campaign-performance-analyzer", category: "Email Tools", isPro: true },
  { id: 93, name: "Email Engagement Analyzer", slug: "email-engagement-analyzer", category: "Email Tools", isPro: true },
  { id: 94, name: "Email Deliverability Analyzer", slug: "email-deliverability-analyzer", category: "Email Tools", isPro: true },
  { id: 95, name: "Email Subject A/B Testing Tool", slug: "email-subject-ab-testing-tool", category: "Email Tools", isPro: true },
  { id: 96, name: "Email Campaign Reporting Generator", slug: "email-campaign-reporting-generator", category: "Email Tools", isPro: true },
  { id: 97, name: "Email Automation Workflow Builder", slug: "email-automation-workflow-builder", category: "Email Tools", isPro: true },
  { id: 98, name: "Email Marketing Analytics Dashboard", slug: "email-marketing-analytics-dashboard", category: "Email Tools", isPro: true },
  { id: 99, name: "Email Productivity Workspace", slug: "email-productivity-workspace", category: "Email Tools", isPro: true },
  { id: 100, name: "Email Intelligence Workspace", slug: "email-intelligence-workspace", category: "Email Tools", isPro: true },
];