export interface EngineeringTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const engineeringToolsList: EngineeringTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "Engineering Unit Converter", slug: "engineering-unit-converter", category: "Engineering Tools", isPro: false },
  { id: 2, name: "Force Converter", slug: "force-converter", category: "Engineering Tools", isPro: false },
  { id: 3, name: "Pressure Converter", slug: "pressure-converter", category: "Engineering Tools", isPro: false },
  { id: 4, name: "Torque Converter", slug: "torque-converter", category: "Engineering Tools", isPro: false },
  { id: 5, name: "Density Calculator", slug: "density-calculator", category: "Engineering Tools", isPro: false },
  { id: 6, name: "Stress Calculator", slug: "stress-calculator", category: "Engineering Tools", isPro: false },
  { id: 7, name: "Strain Calculator", slug: "strain-calculator", category: "Engineering Tools", isPro: false },
  { id: 8, name: "Beam Deflection Calculator", slug: "beam-deflection-calculator", category: "Engineering Tools", isPro: false },
  { id: 9, name: "Bending Moment Calculator", slug: "bending-moment-calculator", category: "Engineering Tools", isPro: false },
  { id: 10, name: "Moment of Inertia Calculator", slug: "moment-of-inertia-calculator", category: "Engineering Tools", isPro: false },
  { id: 11, name: "Centroid Calculator", slug: "centroid-calculator", category: "Engineering Tools", isPro: false },
  { id: 12, name: "Gear Ratio Calculator", slug: "gear-ratio-calculator", category: "Engineering Tools", isPro: false },
  { id: 13, name: "Motor Power Calculator", slug: "motor-power-calculator", category: "Engineering Tools", isPro: false },
  { id: 14, name: "Ohm's Law Calculator", slug: "ohms-law-calculator", category: "Engineering Tools", isPro: false },
  { id: 15, name: "Wire Size Calculator", slug: "wire-size-calculator", category: "Engineering Tools", isPro: false },
  { id: 16, name: "Voltage Drop Calculator", slug: "voltage-drop-calculator", category: "Engineering Tools", isPro: false },
  { id: 17, name: "Battery Runtime Calculator", slug: "battery-runtime-calculator", category: "Engineering Tools", isPro: false },
  { id: 18, name: "Fluid Flow Calculator", slug: "fluid-flow-calculator", category: "Engineering Tools", isPro: false },
  { id: 19, name: "Pressure Drop Calculator", slug: "pressure-drop-calculator", category: "Engineering Tools", isPro: false },
  { id: 20, name: "Engineering Safety Factor Calculator", slug: "engineering-safety-factor-calculator", category: "Engineering Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Stress Converter", slug: "stress-converter", category: "Engineering Tools", isPro: false },
  { id: 22, name: "Power Converter", slug: "power-converter", category: "Engineering Tools", isPro: false },
  { id: 23, name: "Energy Converter", slug: "energy-converter", category: "Engineering Tools", isPro: false },
  { id: 24, name: "Temperature Converter", slug: "temperature-converter", category: "Engineering Tools", isPro: false },
  { id: 25, name: "Length Converter", slug: "length-converter", category: "Engineering Tools", isPro: false },
  { id: 26, name: "Area Converter", slug: "area-converter", category: "Engineering Tools", isPro: false },
  { id: 27, name: "Volume Converter", slug: "volume-converter", category: "Engineering Tools", isPro: false },
  { id: 28, name: "Mass Converter", slug: "mass-converter", category: "Engineering Tools", isPro: false },
  { id: 29, name: "Force Calculator", slug: "force-calculator", category: "Engineering Tools", isPro: false },
  { id: 30, name: "Work Calculator", slug: "work-calculator", category: "Engineering Tools", isPro: false },
  { id: 31, name: "Power Calculator", slug: "power-calculator", category: "Engineering Tools", isPro: false },
  { id: 32, name: "Energy Calculator", slug: "energy-calculator", category: "Engineering Tools", isPro: false },
  { id: 33, name: "Pressure Calculator", slug: "pressure-calculator", category: "Engineering Tools", isPro: false },
  { id: 34, name: "Young's Modulus Calculator", slug: "youngs-modulus-calculator", category: "Engineering Tools", isPro: false },
  { id: 35, name: "Hooke's Law Calculator", slug: "hookes-law-calculator", category: "Engineering Tools", isPro: false },
  { id: 36, name: "Spring Constant Calculator", slug: "spring-constant-calculator", category: "Engineering Tools", isPro: false },
  { id: 37, name: "Beam Stress Calculator", slug: "beam-stress-calculator", category: "Engineering Tools", isPro: false },
  { id: 38, name: "Shear Force Calculator", slug: "shear-force-calculator", category: "Engineering Tools", isPro: false },
  { id: 39, name: "Section Modulus Calculator", slug: "section-modulus-calculator", category: "Engineering Tools", isPro: false },
  { id: 40, name: "Load Calculator", slug: "load-calculator", category: "Engineering Tools", isPro: false },
  { id: 41, name: "Distributed Load Calculator", slug: "distributed-load-calculator", category: "Engineering Tools", isPro: false },
  { id: 42, name: "Point Load Calculator", slug: "point-load-calculator", category: "Engineering Tools", isPro: false },
  { id: 43, name: "Torque Calculator", slug: "torque-calculator", category: "Engineering Tools", isPro: false },
  { id: 44, name: "Shaft Power Calculator", slug: "shaft-power-calculator", category: "Engineering Tools", isPro: false },
  { id: 45, name: "Belt Length Calculator", slug: "belt-length-calculator", category: "Engineering Tools", isPro: false },
  { id: 46, name: "Pulley Calculator", slug: "pulley-calculator", category: "Engineering Tools", isPro: false },
  { id: 47, name: "Electrical Power Calculator", slug: "electrical-power-calculator", category: "Engineering Tools", isPro: false },
  { id: 48, name: "Voltage Calculator", slug: "voltage-calculator", category: "Engineering Tools", isPro: false },
  { id: 49, name: "Current Calculator", slug: "current-calculator", category: "Engineering Tools", isPro: false },
  { id: 50, name: "Resistance Calculator", slug: "resistance-calculator", category: "Engineering Tools", isPro: false },
  { id: 51, name: "Electrical Energy Calculator", slug: "electrical-energy-calculator", category: "Engineering Tools", isPro: false },
  { id: 52, name: "Battery Capacity Calculator", slug: "battery-capacity-calculator", category: "Engineering Tools", isPro: false },
  { id: 53, name: "Solar Panel Output Calculator", slug: "solar-panel-output-calculator", category: "Engineering Tools", isPro: false },
  { id: 54, name: "Heat Transfer Calculator", slug: "heat-transfer-calculator", category: "Engineering Tools", isPro: false },
  { id: 55, name: "Thermal Expansion Calculator", slug: "thermal-expansion-calculator", category: "Engineering Tools", isPro: false },
  { id: 56, name: "Heat Loss Calculator", slug: "heat-loss-calculator", category: "Engineering Tools", isPro: false },
  { id: 57, name: "Pipe Flow Calculator", slug: "pipe-flow-calculator", category: "Engineering Tools", isPro: false },
  { id: 58, name: "Reynolds Number Calculator", slug: "reynolds-number-calculator", category: "Engineering Tools", isPro: false },
  { id: 59, name: "Pump Power Calculator", slug: "pump-power-calculator", category: "Engineering Tools", isPro: false },
  { id: 60, name: "Flow Rate Calculator", slug: "flow-rate-calculator", category: "Engineering Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Structural Analysis Workspace", slug: "structural-analysis-workspace", category: "Engineering Tools", isPro: true },
  { id: 62, name: "Beam Analysis Engine", slug: "beam-analysis-engine", category: "Engineering Tools", isPro: true },
  { id: 63, name: "Frame Analysis Engine", slug: "frame-analysis-engine", category: "Engineering Tools", isPro: true },
  { id: 64, name: "Load Combination Analyzer", slug: "load-combination-analyzer", category: "Engineering Tools", isPro: true },
  { id: 65, name: "Structural Safety Analyzer", slug: "structural-safety-analyzer", category: "Engineering Tools", isPro: true },
  { id: 66, name: "Mechanical Design Calculator", slug: "mechanical-design-calculator", category: "Engineering Tools", isPro: true },
  { id: 67, name: "Shaft Design Analyzer", slug: "shaft-design-analyzer", category: "Engineering Tools", isPro: true },
  { id: 68, name: "Gear Design Analyzer", slug: "gear-design-analyzer", category: "Engineering Tools", isPro: true },
  { id: 69, name: "Motor Sizing Workspace", slug: "motor-sizing-workspace", category: "Engineering Tools", isPro: true },
  { id: 70, name: "Pump Sizing Workspace", slug: "pump-sizing-workspace", category: "Engineering Tools", isPro: true },
  { id: 71, name: "Pipe Sizing Workspace", slug: "pipe-sizing-workspace", category: "Engineering Tools", isPro: true },
  { id: 72, name: "Fluid System Analyzer", slug: "fluid-system-analyzer", category: "Engineering Tools", isPro: true },
  { id: 73, name: "HVAC Load Calculator", slug: "hvac-load-calculator", category: "Engineering Tools", isPro: true },
  { id: 74, name: "Thermal System Analyzer", slug: "thermal-system-analyzer", category: "Engineering Tools", isPro: true },
  { id: 75, name: "Heat Exchanger Analyzer", slug: "heat-exchanger-analyzer", category: "Engineering Tools", isPro: true },
  { id: 76, name: "Electrical Load Analyzer", slug: "electrical-load-analyzer", category: "Engineering Tools", isPro: true },
  { id: 77, name: "Electrical System Sizing Workspace", slug: "electrical-system-sizing-workspace", category: "Engineering Tools", isPro: true },
  { id: 78, name: "Solar System Design Workspace", slug: "solar-system-design-workspace", category: "Engineering Tools", isPro: true },
  { id: 79, name: "Battery System Design Workspace", slug: "battery-system-design-workspace", category: "Engineering Tools", isPro: true },
  { id: 80, name: "Power System Analyzer", slug: "power-system-analyzer", category: "Engineering Tools", isPro: true },
  { id: 81, name: "Engineering Cost Estimator", slug: "engineering-cost-estimator", category: "Engineering Tools", isPro: true },
  { id: 82, name: "Engineering Material Selector", slug: "engineering-material-selector", category: "Engineering Tools", isPro: true },
  { id: 83, name: "Material Property Analyzer", slug: "material-property-analyzer", category: "Engineering Tools", isPro: true },
  { id: 84, name: "Tolerance Stack-Up Analyzer", slug: "tolerance-stack-up-analyzer", category: "Engineering Tools", isPro: true },
  { id: 85, name: "Dimensional Tolerance Calculator", slug: "dimensional-tolerance-calculator", category: "Engineering Tools", isPro: true },
  { id: 86, name: "Engineering Drawing Checker", slug: "engineering-drawing-checker", category: "Engineering Tools", isPro: true },
  { id: 87, name: "Design Margin Analyzer", slug: "design-margin-analyzer", category: "Engineering Tools", isPro: true },
  { id: 88, name: "Reliability Calculator", slug: "reliability-calculator", category: "Engineering Tools", isPro: true },
  { id: 89, name: "Failure Rate Analyzer", slug: "failure-rate-analyzer", category: "Engineering Tools", isPro: true },
  { id: 90, name: "Engineering Risk Analyzer", slug: "engineering-risk-analyzer", category: "Engineering Tools", isPro: true },
  { id: 91, name: "Engineering Project Calculator", slug: "engineering-project-calculator", category: "Engineering Tools", isPro: true },
  { id: 92, name: "Engineering Calculation Notebook", slug: "engineering-calculation-notebook", category: "Engineering Tools", isPro: true },
  { id: 93, name: "Engineering Report Generator", slug: "engineering-report-generator", category: "Engineering Tools", isPro: true },
  { id: 94, name: "Engineering Design Review Workspace", slug: "engineering-design-review-workspace", category: "Engineering Tools", isPro: true },
  { id: 95, name: "Engineering Data Dashboard", slug: "engineering-data-dashboard", category: "Engineering Tools", isPro: true },
  { id: 96, name: "Engineering Formula Library", slug: "engineering-formula-library", category: "Engineering Tools", isPro: true },
  { id: 97, name: "Engineering Simulation Workspace", slug: "engineering-simulation-workspace", category: "Engineering Tools", isPro: true },
  { id: 98, name: "Professional Engineering Workspace", slug: "professional-engineering-workspace", category: "Engineering Tools", isPro: true },
  { id: 99, name: "Engineering Design Intelligence Platform", slug: "engineering-design-intelligence-platform", category: "Engineering Tools", isPro: true },
  { id: 100, name: "Engineering Operations Command Center", slug: "engineering-operations-command-center", category: "Engineering Tools", isPro: true }
];