export interface FacilityWorkplaceTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const facilityWorkplaceToolsList: FacilityWorkplaceTool[] = [
  // --- 🔥 PRIORITY 20 FREE TOOLS (IDs 1-20 | isPro: false) ---
  { id: 1, name: "Office Capacity Calculator", slug: "office-capacity-calculator", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 2, name: "Workspace Utilization Calculator", slug: "workspace-utilization-calculator", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 3, name: "Office Occupancy Calculator", slug: "office-occupancy-calculator", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 4, name: "Desk Utilization Calculator", slug: "desk-utilization-calculator", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 5, name: "Space Allocation Calculator", slug: "space-allocation-calculator", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 6, name: "Seating Plan Generator", slug: "seating-plan-generator", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 7, name: "Desk Allocation Planner", slug: "desk-allocation-planner", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 8, name: "Meeting Room Planner", slug: "meeting-room-planner", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 9, name: "Cleaning Schedule Generator", slug: "cleaning-schedule-generator", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 10, name: "Maintenance Schedule Generator", slug: "maintenance-schedule-generator", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 11, name: "Facility Asset Register", slug: "facility-asset-register", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 12, name: "Maintenance Request Tracker", slug: "maintenance-request-tracker", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 13, name: "Work Order Tracker", slug: "work-order-tracker", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 14, name: "Maintenance Cost Calculator", slug: "maintenance-cost-calculator", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 15, name: "Facility Operating Cost Calculator", slug: "facility-operating-cost-calculator", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 16, name: "Workspace Cost Per Employee", slug: "workspace-cost-per-employee", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 17, name: "Facility Budget Planner", slug: "facility-budget-planner", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 18, name: "Meeting Room Capacity Calculator", slug: "meeting-room-capacity-calculator", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 19, name: "Floor Capacity Calculator", slug: "floor-capacity-calculator", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 20, name: "Workspace Ratio Calculator", slug: "workspace-ratio-calculator", category: "Facility & Workplace Management Tools", isPro: false },

  // --- REMAINING 40 CORE FREE TOOLS (IDs 21-60 | isPro: false) ---
  { id: 21, name: "Desk Capacity Calculator", slug: "desk-capacity-calculator", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 22, name: "Meeting Room Utilization Calculator", slug: "meeting-room-utilization-calculator", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 23, name: "Employee-to-Desk Calculator", slug: "employee-to-desk-calculator", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 24, name: "Office Seating Chart", slug: "office-seating-chart", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 25, name: "Workspace Booking Planner", slug: "workspace-booking-planner", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 26, name: "Hot Desk Planner", slug: "hot-desk-planner", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 27, name: "Office Move Checklist", slug: "office-move-checklist", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 28, name: "Office Relocation Checklist", slug: "office-relocation-checklist", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 29, name: "Workplace Opening Checklist", slug: "workplace-opening-checklist", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 30, name: "Workplace Closing Checklist", slug: "workplace-closing-checklist", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 31, name: "Facility Inspection Checklist", slug: "facility-inspection-checklist", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 32, name: "Building Inspection Checklist", slug: "building-inspection-checklist", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 33, name: "Safety Inspection Planner", slug: "safety-inspection-planner", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 34, name: "Preventive Maintenance Calendar", slug: "preventive-maintenance-calendar", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 35, name: "Equipment Maintenance Tracker", slug: "equipment-maintenance-tracker", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 36, name: "Workplace Asset Tracker", slug: "workplace-asset-tracker", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 37, name: "Facility Issue Tracker", slug: "facility-issue-tracker", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 38, name: "Vendor Visit Planner", slug: "vendor-visit-planner", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 39, name: "Facility Vendor Directory", slug: "facility-vendor-directory", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 40, name: "Building Service Tracker", slug: "building-service-tracker", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 41, name: "Utility Usage Tracker", slug: "utility-usage-tracker", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 42, name: "Facility Expense Tracker", slug: "facility-expense-tracker", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 43, name: "Cleaning Cost Calculator", slug: "cleaning-cost-calculator", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 44, name: "Office Move Cost Calculator", slug: "office-move-cost-calculator", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 45, name: "Maintenance Budget Calculator", slug: "maintenance-budget-calculator", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 46, name: "Workplace Staffing Calculator", slug: "workplace-staffing-calculator", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 47, name: "Security Staffing Planner", slug: "security-staffing-planner", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 48, name: "Cleaning Staffing Planner", slug: "cleaning-staffing-planner", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 49, name: "Reception Staffing Planner", slug: "reception-staffing-planner", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 50, name: "Facility KPI Generator", slug: "facility-kpi-generator", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 51, name: "Workplace KPI Generator", slug: "workplace-kpi-generator", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 52, name: "Facility Inspection Report", slug: "facility-inspection-report", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 53, name: "Maintenance Report Generator", slug: "maintenance-report-generator", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 54, name: "Workplace Utilization Report", slug: "workplace-utilization-report", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 55, name: "Facility Incident Log", slug: "facility-incident-log", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 56, name: "Visitor Log Template", slug: "visitor-log-template", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 57, name: "Contractor Log", slug: "contractor-log", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 58, name: "Facility Handover Checklist", slug: "facility-handover-checklist", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 59, name: "Emergency Preparedness Checklist", slug: "emergency-preparedness-checklist", category: "Facility & Workplace Management Tools", isPro: false },
  { id: 60, name: "Workplace Operations Checklist", slug: "workplace-operations-checklist", category: "Facility & Workplace Management Tools", isPro: false },

  // --- ⚡ 40 PRO / SAAS TOOLS (IDs 61-100 | isPro: true) ---
  { id: 61, name: "Facility Management Workspace", slug: "facility-management-workspace", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 62, name: "Workplace Management Workspace", slug: "workplace-management-workspace", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 63, name: "Space Management Dashboard", slug: "space-management-dashboard", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 64, name: "Office Occupancy Dashboard", slug: "office-occupancy-dashboard", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 65, name: "Desk Utilization Dashboard", slug: "desk-utilization-dashboard", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 66, name: "Meeting Room Analytics", slug: "meeting-room-analytics", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 67, name: "Workplace Booking Workspace", slug: "workplace-booking-workspace", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 68, name: "Hot Desk Management", slug: "hot-desk-management", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 69, name: "Seating Management Workspace", slug: "seating-management-workspace", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 70, name: "Floor Space Planning Workspace", slug: "floor-space-planning-workspace", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 71, name: "Facility Asset Management", slug: "facility-asset-management", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 72, name: "Maintenance Management Workspace", slug: "maintenance-management-workspace", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 73, name: "Work Order Management", slug: "work-order-management", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 74, name: "Preventive Maintenance Workspace", slug: "preventive-maintenance-workspace", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 75, name: "Facility Vendor Management", slug: "facility-vendor-management", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 76, name: "Contractor Management Workspace", slug: "contractor-management-workspace", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 77, name: "Building Service Management", slug: "building-service-management", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 78, name: "Facility Inspection Workspace", slug: "facility-inspection-workspace", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 79, name: "Workplace Safety Management", slug: "workplace-safety-management", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 80, name: "Facility Incident Management", slug: "facility-incident-management", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 81, name: "Workplace Move Management", slug: "workplace-move-management", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 82, name: "Office Relocation Workspace", slug: "office-relocation-workspace", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 83, name: "Facility Budget Management", slug: "facility-budget-management", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 84, name: "Maintenance Cost Dashboard", slug: "maintenance-cost-dashboard", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 85, name: "Facility Expense Analytics", slug: "facility-expense-analytics", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 86, name: "Utility Consumption Dashboard", slug: "utility-consumption-dashboard", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 87, name: "Workplace Productivity Analytics", slug: "workplace-productivity-analytics", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 88, name: "Facility KPI Dashboard", slug: "facility-kpi-dashboard", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 89, name: "Workplace KPI Dashboard", slug: "workplace-kpi-dashboard", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 90, name: "Space Optimization Workspace", slug: "space-optimization-workspace", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 91, name: "Office Cost Optimization", slug: "office-cost-optimization", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 92, name: "Facility Workforce Planner", slug: "facility-workforce-planner", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 93, name: "Facility Reporting Workspace", slug: "facility-reporting-workspace", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 94, name: "Facility Data Import Workspace", slug: "facility-data-import-workspace", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 95, name: "Facility Data Export Workspace", slug: "facility-data-export-workspace", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 96, name: "Facility API Workspace", slug: "facility-api-workspace", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 97, name: "Facility Automation Workspace", slug: "facility-automation-workspace", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 98, name: "Smart Workplace Dashboard", slug: "smart-workplace-dashboard", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 99, name: "Enterprise Facility Platform", slug: "enterprise-facility-platform", category: "Facility & Workplace Management Tools", isPro: true },
  { id: 100, name: "Workplace Operations Command Center", slug: "workplace-operations-command-center", category: "Facility & Workplace Management Tools", isPro: true }
];