export interface FinanceTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const financeToolsList: FinanceTool[] = [
  // --- TOP 10 PRIORITY TOOLS ---
  { id: 1, name: "Mortgage Calculator", slug: "mortgage-calculator", category: "Finance Tools", isPro: false },
  { id: 2, name: "Loan Calculator", slug: "loan-calculator", category: "Finance Tools", isPro: false },
  { id: 3, name: "Compound Interest Calculator", slug: "compound-interest-calculator", category: "Finance Tools", isPro: false },
  { id: 4, name: "Retirement Calculator", slug: "retirement-calculator", category: "Finance Tools", isPro: false },
  { id: 5, name: "Investment Calculator", slug: "investment-calculator", category: "Finance Tools", isPro: false },
  { id: 6, name: "Debt Payoff Calculator", slug: "debt-payoff-calculator", category: "Finance Tools", isPro: false },
  { id: 7, name: "Salary Calculator", slug: "salary-calculator", category: "Finance Tools", isPro: false },
  { id: 8, name: "ROI Calculator", slug: "roi-calculator", category: "Finance Tools", isPro: false },
  { id: 9, name: "Budget Calculator", slug: "budget-calculator", category: "Finance Tools", isPro: false },
  { id: 10, name: "Currency Converter", slug: "currency-converter", category: "Finance Tools", isPro: false },

  // --- REMAINING CORE / HIGH-DEMAND (FREE TOOLS: 11-60) ---
  { id: 11, name: "EMI Calculator", slug: "emi-calculator", category: "Finance Tools", isPro: false },
  { id: 12, name: "Personal Loan Calculator", slug: "personal-loan-calculator", category: "Finance Tools", isPro: false },
  { id: 13, name: "Auto Loan Calculator", slug: "auto-loan-calculator", category: "Finance Tools", isPro: false },
  { id: 14, name: "Student Loan Calculator", slug: "student-loan-calculator", category: "Finance Tools", isPro: false },
  { id: 15, name: "Business Loan Calculator", slug: "business-loan-calculator", category: "Finance Tools", isPro: false },
  { id: 16, name: "Home Loan Calculator", slug: "home-loan-calculator", category: "Finance Tools", isPro: false },
  { id: 17, name: "Interest Calculator", slug: "interest-calculator", category: "Finance Tools", isPro: false },
  { id: 18, name: "Simple Interest Calculator", slug: "simple-interest-calculator", category: "Finance Tools", isPro: false },
  { id: 19, name: "Monthly Payment Calculator", slug: "monthly-payment-calculator", category: "Finance Tools", isPro: false },
  { id: 20, name: "Loan Amortization Calculator", slug: "loan-amortization-calculator", category: "Finance Tools", isPro: false },
  { id: 21, name: "Mortgage Payment Calculator", slug: "mortgage-payment-calculator", category: "Finance Tools", isPro: false },
  { id: 22, name: "Mortgage Affordability Calculator", slug: "mortgage-affordability-calculator", category: "Finance Tools", isPro: false },
  { id: 23, name: "Home Affordability Calculator", slug: "home-affordability-calculator", category: "Finance Tools", isPro: false },
  { id: 24, name: "Down Payment Calculator", slug: "down-payment-calculator", category: "Finance Tools", isPro: false },
  { id: 25, name: "Refinance Calculator", slug: "refinance-calculator", category: "Finance Tools", isPro: false },
  { id: 26, name: "Mortgage Refinance Savings Calculator", slug: "mortgage-refinance-savings-calculator", category: "Finance Tools", isPro: false },
  { id: 27, name: "Debt Snowball Calculator", slug: "debt-snowball-calculator", category: "Finance Tools", isPro: false },
  { id: 28, name: "Debt Avalanche Calculator", slug: "debt-avalanche-calculator", category: "Finance Tools", isPro: false },
  { id: 29, name: "Credit Card Payoff Calculator", slug: "credit-card-payoff-calculator", category: "Finance Tools", isPro: false },
  { id: 30, name: "Minimum Payment Calculator", slug: "minimum-payment-calculator", category: "Finance Tools", isPro: false },
  { id: 31, name: "Savings Calculator", slug: "savings-calculator", category: "Finance Tools", isPro: false },
  { id: 32, name: "Savings Goal Calculator", slug: "savings-goal-calculator", category: "Finance Tools", isPro: false },
  { id: 33, name: "Emergency Fund Calculator", slug: "emergency-fund-calculator", category: "Finance Tools", isPro: false },
  { id: 34, name: "401(k) Calculator", slug: "401k-calculator", category: "Finance Tools", isPro: false },
  { id: 35, name: "IRA Calculator", slug: "ira-calculator", category: "Finance Tools", isPro: false },
  { id: 36, name: "Roth IRA Calculator", slug: "roth-ira-calculator", category: "Finance Tools", isPro: false },
  { id: 37, name: "Pension Calculator", slug: "pension-calculator", category: "Finance Tools", isPro: false },
  { id: 38, name: "CAGR Calculator", slug: "cagr-calculator", category: "Finance Tools", isPro: false },
  { id: 39, name: "SIP Calculator", slug: "sip-calculator", category: "Finance Tools", isPro: false },
  { id: 40, name: "Mutual Fund Calculator", slug: "mutual-fund-calculator", category: "Finance Tools", isPro: false },
  { id: 41, name: "Dividend Calculator", slug: "dividend-calculator", category: "Finance Tools", isPro: false },
  { id: 42, name: "Net Worth Calculator", slug: "net-worth-calculator", category: "Finance Tools", isPro: false },
  { id: 43, name: "Hourly Wage Calculator", slug: "hourly-wage-calculator", category: "Finance Tools", isPro: false },
  { id: 44, name: "Annual Salary Calculator", slug: "annual-salary-calculator", category: "Finance Tools", isPro: false },
  { id: 45, name: "Take-Home Pay Calculator", slug: "take-home-pay-calculator", category: "Finance Tools", isPro: false },
  { id: 46, name: "Overtime Pay Calculator", slug: "overtime-pay-calculator", category: "Finance Tools", isPro: false },
  { id: 47, name: "Freelance Rate Calculator", slug: "freelance-rate-calculator", category: "Finance Tools", isPro: false },
  { id: 48, name: "Profit Margin Calculator", slug: "profit-margin-calculator", category: "Finance Tools", isPro: false },
  { id: 49, name: "Markup Calculator", slug: "markup-calculator", category: "Finance Tools", isPro: false },
  { id: 50, name: "Break-Even Calculator", slug: "break-even-calculator", category: "Finance Tools", isPro: false },
  { id: 51, name: "Cash Flow Calculator", slug: "cash-flow-calculator", category: "Finance Tools", isPro: false },
  { id: 52, name: "Monthly Budget Planner", slug: "monthly-budget-planner", category: "Finance Tools", isPro: false },
  { id: 53, name: "Annual Budget Calculator", slug: "annual-budget-calculator", category: "Finance Tools", isPro: false },
  { id: 54, name: "Expense Tracker", slug: "expense-tracker", category: "Finance Tools", isPro: false },
  { id: 55, name: "Inflation Calculator", slug: "inflation-calculator", category: "Finance Tools", isPro: false },
  { id: 56, name: "Purchasing Power Calculator", slug: "purchasing-power-calculator", category: "Finance Tools", isPro: false },
  { id: 57, name: "Tip Calculator", slug: "tip-calculator", category: "Finance Tools", isPro: false },
  { id: 58, name: "Discount Calculator", slug: "discount-calculator", category: "Finance Tools", isPro: false },
  { id: 59, name: "Sales Tax Calculator", slug: "sales-tax-calculator", category: "Finance Tools", isPro: false },
  { id: 60, name: "VAT Calculator", slug: "vat-calculator", category: "Finance Tools", isPro: false },

  // --- PRO LEVEL (PAID TOOLS: 61-100) ---
  { id: 61, name: "FIRE Calculator", slug: "fire-calculator", category: "Finance Tools", isPro: true },
  { id: 62, name: "Coast FIRE Calculator", slug: "coast-fire-calculator", category: "Finance Tools", isPro: true },
  { id: 63, name: "Financial Independence Calculator", slug: "financial-independence-calculator", category: "Finance Tools", isPro: true },
  { id: 64, name: "Retirement Income Calculator", slug: "retirement-income-calculator", category: "Finance Tools", isPro: true },
  { id: 65, name: "Retirement Withdrawal Calculator", slug: "retirement-withdrawal-calculator", category: "Finance Tools", isPro: true },
  { id: 66, name: "Safe Withdrawal Rate Calculator", slug: "safe-withdrawal-rate-calculator", category: "Finance Tools", isPro: true },
  { id: 67, name: "Social Security Estimator", slug: "social-security-estimator", category: "Finance Tools", isPro: true },
  { id: 68, name: "Medicare Cost Estimator", slug: "medicare-cost-estimator", category: "Finance Tools", isPro: true },
  { id: 69, name: "College Cost Calculator", slug: "college-cost-calculator", category: "Finance Tools", isPro: true },
  { id: 70, name: "Education Savings Calculator", slug: "education-savings-calculator", category: "Finance Tools", isPro: true },
  { id: 71, name: "Student Loan Repayment Planner", slug: "student-loan-repayment-planner", category: "Finance Tools", isPro: true },
  { id: 72, name: "Debt-to-Income Calculator", slug: "debt-to-income-calculator", category: "Finance Tools", isPro: true },
  { id: 73, name: "Loan-to-Value Calculator", slug: "loan-to-value-calculator", category: "Finance Tools", isPro: true },
  { id: 74, name: "Mortgage Points Calculator", slug: "mortgage-points-calculator", category: "Finance Tools", isPro: true },
  { id: 75, name: "Mortgage Closing Cost Calculator", slug: "mortgage-closing-cost-calculator", category: "Finance Tools", isPro: true },
  { id: 76, name: "Property Tax Calculator", slug: "property-tax-calculator", category: "Finance Tools", isPro: true },
  { id: 77, name: "Capital Gains Calculator", slug: "capital-gains-calculator", category: "Finance Tools", isPro: true },
  { id: 78, name: "Investment Return Calculator", slug: "investment-return-calculator", category: "Finance Tools", isPro: true },
  { id: 79, name: "Portfolio Return Calculator", slug: "portfolio-return-calculator", category: "Finance Tools", isPro: true },
  { id: 80, name: "Portfolio Allocation Calculator", slug: "portfolio-allocation-calculator", category: "Finance Tools", isPro: true },
  { id: 81, name: "Asset Allocation Calculator", slug: "asset-allocation-calculator", category: "Finance Tools", isPro: true },
  { id: 82, name: "Rebalancing Calculator", slug: "rebalancing-calculator", category: "Finance Tools", isPro: true },
  { id: 83, name: "Dividend Reinvestment Calculator", slug: "dividend-reinvestment-calculator", category: "Finance Tools", isPro: true },
  { id: 84, name: "Bond Yield Calculator", slug: "bond-yield-calculator", category: "Finance Tools", isPro: true },
  { id: 85, name: "Bond Price Calculator", slug: "bond-price-calculator", category: "Finance Tools", isPro: true },
  { id: 86, name: "Yield-to-Maturity Calculator", slug: "yield-to-maturity-calculator", category: "Finance Tools", isPro: true },
  { id: 87, name: "Present Value Calculator", slug: "present-value-calculator", category: "Finance Tools", isPro: true },
  { id: 88, name: "Future Value Calculator", slug: "future-value-calculator", category: "Finance Tools", isPro: true },
  { id: 89, name: "NPV Calculator", slug: "npv-calculator", category: "Finance Tools", isPro: true },
  { id: 90, name: "IRR Calculator", slug: "irr-calculator", category: "Finance Tools", isPro: true },
  { id: 91, name: "Payback Period Calculator", slug: "payback-period-calculator", category: "Finance Tools", isPro: true },
  { id: 92, name: "Business Valuation Calculator", slug: "business-valuation-calculator", category: "Finance Tools", isPro: true },
  { id: 93, name: "Startup Valuation Calculator", slug: "startup-valuation-calculator", category: "Finance Tools", isPro: true },
  { id: 94, name: "SaaS Valuation Calculator", slug: "saas-valuation-calculator", category: "Finance Tools", isPro: true },
  { id: 95, name: "EBITDA Calculator", slug: "ebitda-calculator", category: "Finance Tools", isPro: true },
  { id: 96, name: "Free Cash Flow Calculator", slug: "free-cash-flow-calculator", category: "Finance Tools", isPro: true },
  { id: 97, name: "Working Capital Calculator", slug: "working-capital-calculator", category: "Finance Tools", isPro: true },
  { id: 98, name: "Accounts Receivable Calculator", slug: "accounts-receivable-calculator", category: "Finance Tools", isPro: true },
  { id: 99, name: "Accounts Payable Calculator", slug: "accounts-payable-calculator", category: "Finance Tools", isPro: true },
  { id: 100, name: "Financial Ratio Calculator", slug: "financial-ratio-calculator", category: "Finance Tools", isPro: true },
];