export interface FreelancingTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const freelancingToolsList: FreelancingTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "Hourly Rate Calculator", slug: "hourly-rate-calculator", category: "Freelancing Tools", isPro: false },
  { id: 2, name: "Project Rate Calculator", slug: "project-rate-calculator", category: "Freelancing Tools", isPro: false },
  { id: 3, name: "Take-Home Pay Calculator", slug: "take-home-pay-calculator", category: "Freelancing Tools", isPro: false },
  { id: 4, name: "Platform Fee Calculator", slug: "platform-fee-calculator", category: "Freelancing Tools", isPro: false },
  { id: 5, name: "Freelance Profit Calculator", slug: "freelance-profit-calculator", category: "Freelancing Tools", isPro: false },
  { id: 6, name: "Retainer Calculator", slug: "retainer-calculator", category: "Freelancing Tools", isPro: false },
  { id: 7, name: "Quote Calculator", slug: "quote-calculator", category: "Freelancing Tools", isPro: false },
  { id: 8, name: "Proposal Generator", slug: "proposal-generator", category: "Freelancing Tools", isPro: false },
  { id: 9, name: "Contract Generator", slug: "contract-generator", category: "Freelancing Tools", isPro: false },
  { id: 10, name: "Invoice Generator", slug: "invoice-generator", category: "Freelancing Tools", isPro: false },
  { id: 11, name: "Estimate Generator", slug: "estimate-generator", category: "Freelancing Tools", isPro: false },
  { id: 12, name: "SOW Generator", slug: "sow-generator", category: "Freelancing Tools", isPro: false },
  { id: 13, name: "Project Timeline Calculator", slug: "project-timeline-calculator", category: "Freelancing Tools", isPro: false },
  { id: 14, name: "Billable Hours Calculator", slug: "billable-hours-calculator", category: "Freelancing Tools", isPro: false },
  { id: 15, name: "Client Profitability Calculator", slug: "client-profitability-calculator", category: "Freelancing Tools", isPro: false },
  { id: 16, name: "Client Lifetime Value Calculator", slug: "client-lifetime-value-calculator", category: "Freelancing Tools", isPro: false },
  { id: 17, name: "Freelance Lead Tracker", slug: "freelance-lead-tracker", category: "Freelancing Tools", isPro: false },
  { id: 18, name: "Scope Creep Detector", slug: "scope-creep-detector", category: "Freelancing Tools", isPro: false },
  { id: 19, name: "Proposal Performance Tracker", slug: "proposal-performance-tracker", category: "Freelancing Tools", isPro: false },
  { id: 20, name: "Freelance Tax Estimate Calculator", slug: "freelance-tax-estimate-calculator", category: "Freelancing Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Freelance Daily Rate Calculator", slug: "freelance-daily-rate-calculator", category: "Freelancing Tools", isPro: false },
  { id: 22, name: "Freelance Monthly Income Calculator", slug: "freelance-monthly-income-calculator", category: "Freelancing Tools", isPro: false },
  { id: 23, name: "Freelance Annual Income Calculator", slug: "freelance-annual-income-calculator", category: "Freelancing Tools", isPro: false },
  { id: 24, name: "Freelance Payment Fee Calculator", slug: "freelance-payment-fee-calculator", category: "Freelancing Tools", isPro: false },
  { id: 25, name: "Freelance Revenue Calculator", slug: "freelance-revenue-calculator", category: "Freelancing Tools", isPro: false },
  { id: 26, name: "Freelance Break-Even Calculator", slug: "freelance-break-even-calculator", category: "Freelancing Tools", isPro: false },
  { id: 27, name: "Freelance Proposal Template Builder", slug: "freelance-proposal-template-builder", category: "Freelancing Tools", isPro: false },
  { id: 28, name: "Freelance Invoice Calculator", slug: "freelance-invoice-calculator", category: "Freelancing Tools", isPro: false },
  { id: 29, name: "Freelance Invoice Number Generator", slug: "freelance-invoice-number-generator", category: "Freelancing Tools", isPro: false },
  { id: 30, name: "Freelance Scope Generator", slug: "freelance-scope-generator", category: "Freelancing Tools", isPro: false },
  { id: 31, name: "Freelance Project Brief Generator", slug: "freelance-project-brief-generator", category: "Freelancing Tools", isPro: false },
  { id: 32, name: "Freelance Client Questionnaire", slug: "freelance-client-questionnaire", category: "Freelancing Tools", isPro: false },
  { id: 33, name: "Freelance Discovery Call Checklist", slug: "freelance-discovery-call-checklist", category: "Freelancing Tools", isPro: false },
  { id: 34, name: "Freelance Project Checklist", slug: "freelance-project-checklist", category: "Freelancing Tools", isPro: false },
  { id: 35, name: "Freelance Onboarding Checklist", slug: "freelance-onboarding-checklist", category: "Freelancing Tools", isPro: false },
  { id: 36, name: "Freelance Offboarding Checklist", slug: "freelance-offboarding-checklist", category: "Freelancing Tools", isPro: false },
  { id: 37, name: "Freelance Client Brief Template", slug: "freelance-client-brief-template", category: "Freelancing Tools", isPro: false },
  { id: 38, name: "Freelance Portfolio Checklist", slug: "freelance-portfolio-checklist", category: "Freelancing Tools", isPro: false },
  { id: 39, name: "Freelance Portfolio Project Generator", slug: "freelance-portfolio-project-generator", category: "Freelancing Tools", isPro: false },
  { id: 40, name: "Freelance Case Study Generator", slug: "freelance-case-study-generator", category: "Freelancing Tools", isPro: false },
  { id: 41, name: "Freelance Bio Generator", slug: "freelance-bio-generator", category: "Freelancing Tools", isPro: false },
  { id: 42, name: "Freelance Profile Description Generator", slug: "freelance-profile-description-generator", category: "Freelancing Tools", isPro: false },
  { id: 43, name: "Freelance Gig Description Generator", slug: "freelance-gig-description-generator", category: "Freelancing Tools", isPro: false },
  { id: 44, name: "Freelance Service Package Generator", slug: "freelance-service-package-generator", category: "Freelancing Tools", isPro: false },
  { id: 45, name: "Freelance Package Pricing Calculator", slug: "freelance-package-pricing-calculator", category: "Freelancing Tools", isPro: false },
  { id: 46, name: "Freelance Milestone Calculator", slug: "freelance-milestone-calculator", category: "Freelancing Tools", isPro: false },
  { id: 47, name: "Freelance Deadline Calculator", slug: "freelance-deadline-calculator", category: "Freelancing Tools", isPro: false },
  { id: 48, name: "Freelance Workload Calculator", slug: "freelance-workload-calculator", category: "Freelancing Tools", isPro: false },
  { id: 49, name: "Freelance Capacity Calculator", slug: "freelance-capacity-calculator", category: "Freelancing Tools", isPro: false },
  { id: 50, name: "Freelance Utilization Calculator", slug: "freelance-utilization-calculator", category: "Freelancing Tools", isPro: false },
  { id: 51, name: "Freelance Time Tracking Calculator", slug: "freelance-time-tracking-calculator", category: "Freelancing Tools", isPro: false },
  { id: 52, name: "Non-Billable Hours Calculator", slug: "non-billable-hours-calculator", category: "Freelancing Tools", isPro: false },
  { id: 53, name: "Client Acquisition Cost Calculator", slug: "client-acquisition-cost-calculator", category: "Freelancing Tools", isPro: false },
  { id: 54, name: "Freelance Client Tracker", slug: "freelance-client-tracker", category: "Freelancing Tools", isPro: false },
  { id: 55, name: "Freelance Payment Tracker", slug: "freelance-payment-tracker", category: "Freelancing Tools", isPro: false },
  { id: 56, name: "Freelance Invoice Tracker", slug: "freelance-invoice-tracker", category: "Freelancing Tools", isPro: false },
  { id: 57, name: "Freelance Expense Tracker", slug: "freelance-expense-tracker", category: "Freelancing Tools", isPro: false },
  { id: 58, name: "Freelance Income Tracker", slug: "freelance-income-tracker", category: "Freelancing Tools", isPro: false },
  { id: 59, name: "Freelance Goal Calculator", slug: "freelance-goal-calculator", category: "Freelancing Tools", isPro: false },
  { id: 60, name: "Freelance Business Checklist", slug: "freelance-business-checklist", category: "Freelancing Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Freelance Business Dashboard", slug: "freelance-business-dashboard", category: "Freelancing Tools", isPro: true },
  { id: 62, name: "Freelance Business Financial Dashboard", slug: "freelance-business-financial-dashboard", category: "Freelancing Tools", isPro: true },
  { id: 63, name: "Client Profitability Analyzer", slug: "client-profitability-analyzer", category: "Freelancing Tools", isPro: true },
  { id: 64, name: "Client Portfolio Analyzer", slug: "client-portfolio-analyzer", category: "Freelancing Tools", isPro: true },
  { id: 65, name: "Freelance Revenue Forecast", slug: "freelance-revenue-forecast", category: "Freelancing Tools", isPro: true },
  { id: 66, name: "Freelance Income Forecast", slug: "freelance-income-forecast", category: "Freelancing Tools", isPro: true },
  { id: 67, name: "Freelance Cash Flow Forecast", slug: "freelance-cash-flow-forecast", category: "Freelancing Tools", isPro: true },
  { id: 68, name: "Freelance Capacity Planner", slug: "freelance-capacity-planner", category: "Freelancing Tools", isPro: true },
  { id: 69, name: "Freelance Workload Planner", slug: "freelance-workload-planner", category: "Freelancing Tools", isPro: true },
  { id: 70, name: "Multi-Client Project Planner", slug: "multi-client-project-planner", category: "Freelancing Tools", isPro: true },
  { id: 71, name: "Project Profitability Analyzer", slug: "project-profitability-analyzer", category: "Freelancing Tools", isPro: true },
  { id: 72, name: "Project Scope Risk Analyzer", slug: "project-scope-risk-analyzer", category: "Freelancing Tools", isPro: true },
  { id: 73, name: "Project Cost Overrun Analyzer", slug: "project-cost-overrun-analyzer", category: "Freelancing Tools", isPro: true },
  { id: 74, name: "Freelance Pricing Intelligence", slug: "freelance-pricing-intelligence", category: "Freelancing Tools", isPro: true },
  { id: 75, name: "Service Package Optimizer", slug: "service-package-optimizer", category: "Freelancing Tools", isPro: true },
  { id: 76, name: "Retainer Revenue Planner", slug: "retainer-revenue-planner", category: "Freelancing Tools", isPro: true },
  { id: 77, name: "Recurring Revenue Analyzer", slug: "recurring-revenue-analyzer", category: "Freelancing Tools", isPro: true },
  { id: 78, name: "Client Lifetime Value Analyzer", slug: "client-lifetime-value-analyzer", category: "Freelancing Tools", isPro: true },
  { id: 79, name: "Client Acquisition Analytics", slug: "client-acquisition-analytics", category: "Freelancing Tools", isPro: true },
  { id: 80, name: "Freelance Lead Qualification Tool", slug: "freelance-lead-qualification-tool", category: "Freelancing Tools", isPro: true },
  { id: 81, name: "Lead-to-Client Conversion Analyzer", slug: "lead-to-client-conversion-analyzer", category: "Freelancing Tools", isPro: true },
  { id: 82, name: "Client Risk Scoring Tool", slug: "client-risk-scoring-tool", category: "Freelancing Tools", isPro: true },
  { id: 83, name: "Client Payment Risk Analyzer", slug: "client-payment-risk-analyzer", category: "Freelancing Tools", isPro: true },
  { id: 84, name: "Late Payment Predictor", slug: "late-payment-predictor", category: "Freelancing Tools", isPro: true },
  { id: 85, name: "Proposal Conversion Analyzer", slug: "proposal-conversion-analyzer", category: "Freelancing Tools", isPro: true },
  { id: 86, name: "Freelance Contract Risk Analyzer", slug: "freelance-contract-risk-analyzer", category: "Freelancing Tools", isPro: true },
  { id: 87, name: "Freelancer Tax Planning Workspace", slug: "freelancer-tax-planning-workspace", category: "Freelancing Tools", isPro: true },
  { id: 88, name: "Freelancer Financial Planning Workspace", slug: "freelancer-financial-planning-workspace", category: "Freelancing Tools", isPro: true },
  { id: 89, name: "Freelance CRM Workspace", slug: "freelance-crm-workspace", category: "Freelancing Tools", isPro: true },
  { id: 90, name: "Freelance Project Management Workspace", slug: "freelance-project-management-workspace", category: "Freelancing Tools", isPro: true },
  { id: 91, name: "Freelance Invoice & Payment Workspace", slug: "freelance-invoice-and-payment-workspace", category: "Freelancing Tools", isPro: true },
  { id: 92, name: "Freelance Business Intelligence Dashboard", slug: "freelance-business-intelligence-dashboard", category: "Freelancing Tools", isPro: true },
  { id: 93, name: "Freelancer Operations Dashboard", slug: "freelancer-operations-dashboard", category: "Freelancing Tools", isPro: true },
  { id: 94, name: "Agency Freelancer Management Workspace", slug: "agency-freelancer-management-workspace", category: "Freelancing Tools", isPro: true },
  { id: 95, name: "Multi-Freelancer Workspace", slug: "multi-freelancer-workspace", category: "Freelancing Tools", isPro: true },
  { id: 96, name: "Freelance Client Portal", slug: "freelance-client-portal", category: "Freelancing Tools", isPro: true },
  { id: 97, name: "Freelance Business Command Center", slug: "freelance-business-command-center", category: "Freelancing Tools", isPro: true },
  { id: 98, name: "AI Freelance Business Advisor", slug: "ai-freelance-business-advisor", category: "Freelancing Tools", isPro: true },
  { id: 99, name: "Freelance Savings Calculator", slug: "freelance-savings-calculator", category: "Freelancing Tools", isPro: true },
  { id: 100, name: "Freelancer SaaS Operations Platform", slug: "freelancer-saas-operations-platform", category: "Freelancing Tools", isPro: true }
];