export interface HealthFitnessTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const healthFitnessToolsList: HealthFitnessTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "BMI Calculator", slug: "bmi-calculator-health", category: "Health & Fitness Tools", isPro: false },
  { id: 2, name: "Calorie Needs Calculator", slug: "calorie-needs-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 3, name: "TDEE Calculator", slug: "tdee-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 4, name: "BMR Calculator", slug: "bmr-calculator-health", category: "Health & Fitness Tools", isPro: false },
  { id: 5, name: "Calorie Deficit Calculator", slug: "calorie-deficit-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 6, name: "Macro Calculator", slug: "macro-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 7, name: "Protein Intake Calculator", slug: "protein-intake-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 8, name: "Water Intake Calculator", slug: "water-intake-calculator-health", category: "Health & Fitness Tools", isPro: false },
  { id: 9, name: "Body Fat Calculator", slug: "body-fat-calculator-health", category: "Health & Fitness Tools", isPro: false },
  { id: 10, name: "Ideal Weight Calculator", slug: "ideal-weight-calculator-health", category: "Health & Fitness Tools", isPro: false },
  { id: 11, name: "Weight Loss Calculator", slug: "weight-loss-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 12, name: "Calorie Burn Calculator", slug: "calorie-burn-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 13, name: "Steps to Calories Calculator", slug: "steps-to-calories-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 14, name: "Running Pace Calculator", slug: "running-pace-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 15, name: "One Rep Max Calculator", slug: "one-rep-max-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 16, name: "Heart Rate Zone Calculator", slug: "heart-rate-zone-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 17, name: "Sleep Duration Calculator", slug: "sleep-duration-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 18, name: "Workout Planner", slug: "workout-planner", category: "Health & Fitness Tools", isPro: false },
  { id: 19, name: "Fitness Progress Tracker", slug: "fitness-progress-tracker", category: "Health & Fitness Tools", isPro: false },
  { id: 20, name: "Daily Calorie Calculator", slug: "daily-calorie-calculator", category: "Health & Fitness Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Calorie Surplus Calculator", slug: "calorie-surplus-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 22, name: "Carbohydrate Intake Calculator", slug: "carbohydrate-intake-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 23, name: "Fat Intake Calculator", slug: "fat-intake-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 24, name: "Fiber Intake Calculator", slug: "fiber-intake-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 25, name: "Lean Body Mass Calculator", slug: "lean-body-mass-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 26, name: "Body Surface Area Calculator", slug: "body-surface-area-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 27, name: "Waist-to-Height Ratio Calculator", slug: "waist-to-height-ratio-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 28, name: "Waist-to-Hip Ratio Calculator", slug: "waist-to-hip-ratio-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 29, name: "Healthy Weight Range Calculator", slug: "healthy-weight-range-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 30, name: "Weight Gain Calculator", slug: "weight-gain-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 31, name: "Goal Weight Planner", slug: "goal-weight-planner", category: "Health & Fitness Tools", isPro: false },
  { id: 32, name: "Weight Change Tracker", slug: "weight-change-tracker", category: "Health & Fitness Tools", isPro: false },
  { id: 33, name: "Walking Calorie Calculator", slug: "walking-calorie-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 34, name: "Running Calorie Calculator", slug: "running-calorie-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 35, name: "Cycling Calorie Calculator", slug: "cycling-calorie-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 36, name: "Swimming Calorie Calculator", slug: "swimming-calorie-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 37, name: "Hiking Calorie Calculator", slug: "hiking-calorie-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 38, name: "Steps to Distance Calculator", slug: "steps-to-distance-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 39, name: "Pace Calculator", slug: "pace-calculator-health", category: "Health & Fitness Tools", isPro: false },
  { id: 40, name: "Walking Pace Calculator", slug: "walking-pace-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 41, name: "Race Time Predictor", slug: "race-time-predictor", category: "Health & Fitness Tools", isPro: false },
  { id: 42, name: "Workout Volume Calculator", slug: "workout-volume-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 43, name: "Training Load Calculator", slug: "training-load-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 44, name: "Target Heart Rate Calculator", slug: "target-heart-rate-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 45, name: "Resting Heart Rate Tracker", slug: "resting-heart-rate-tracker", category: "Health & Fitness Tools", isPro: false },
  { id: 46, name: "Sleep Schedule Calculator", slug: "sleep-schedule-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 47, name: "Bedtime Calculator", slug: "bedtime-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 48, name: "Wake-Up Time Calculator", slug: "wake-up-time-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 49, name: "Sleep Debt Calculator", slug: "sleep-debt-calculator", category: "Health & Fitness Tools", isPro: false },
  { id: 50, name: "Recovery Time Estimator", slug: "recovery-time-estimator", category: "Health & Fitness Tools", isPro: false },
  { id: 51, name: "Fitness Goal Planner", slug: "fitness-goal-planner", category: "Health & Fitness Tools", isPro: false },
  { id: 52, name: "Weekly Workout Planner", slug: "weekly-workout-planner", category: "Health & Fitness Tools", isPro: false },
  { id: 53, name: "Home Workout Planner", slug: "home-workout-planner", category: "Health & Fitness Tools", isPro: false },
  { id: 54, name: "Gym Workout Planner", slug: "gym-workout-planner", category: "Health & Fitness Tools", isPro: false },
  { id: 55, name: "Running Plan Generator", slug: "running-plan-generator", category: "Health & Fitness Tools", isPro: false },
  { id: 56, name: "Walking Plan Generator", slug: "walking-plan-generator", category: "Health & Fitness Tools", isPro: false },
  { id: 57, name: "Cycling Plan Generator", slug: "cycling-plan-generator", category: "Health & Fitness Tools", isPro: false },
  { id: 58, name: "Stretching Routine Generator", slug: "stretching-routine-generator", category: "Health & Fitness Tools", isPro: false },
  { id: 59, name: "Warm-Up Routine Generator", slug: "warm-up-routine-generator", category: "Health & Fitness Tools", isPro: false },
  { id: 60, name: "Cool-Down Routine Generator", slug: "cool-down-routine-generator", category: "Health & Fitness Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Personalized Workout Planner", slug: "personalized-workout-planner", category: "Health & Fitness Tools", isPro: true },
  { id: 62, name: "Progressive Overload Calculator", slug: "progressive-overload-calculator", category: "Health & Fitness Tools", isPro: true },
  { id: 63, name: "Training Volume Analyzer", slug: "training-volume-analyzer", category: "Health & Fitness Tools", isPro: true },
  { id: 64, name: "Training Intensity Calculator", slug: "training-intensity-calculator", category: "Health & Fitness Tools", isPro: true },
  { id: 65, name: "Training Zone Planner", slug: "training-zone-planner", category: "Health & Fitness Tools", isPro: true },
  { id: 66, name: "Workout Split Planner", slug: "workout-split-planner", category: "Health & Fitness Tools", isPro: true },
  { id: 67, name: "Strength Program Generator", slug: "strength-program-generator", category: "Health & Fitness Tools", isPro: true },
  { id: 68, name: "Hypertrophy Program Generator", slug: "hypertrophy-program-generator", category: "Health & Fitness Tools", isPro: true },
  { id: 69, name: "Endurance Training Planner", slug: "endurance-training-planner", category: "Health & Fitness Tools", isPro: true },
  { id: 70, name: "Marathon Training Planner", slug: "marathon-training-planner", category: "Health & Fitness Tools", isPro: true },
  { id: 71, name: "Half Marathon Training Planner", slug: "half-marathon-training-planner", category: "Health & Fitness Tools", isPro: true },
  { id: 72, name: "5K Training Planner", slug: "5k-training-planner", category: "Health & Fitness Tools", isPro: true },
  { id: 73, name: "10K Training Planner", slug: "10k-training-planner", category: "Health & Fitness Tools", isPro: true },
  { id: 74, name: "Triathlon Training Planner", slug: "triathlon-training-planner", category: "Health & Fitness Tools", isPro: true },
  { id: 75, name: "Cycling Training Planner", slug: "cycling-training-planner", category: "Health & Fitness Tools", isPro: true },
  { id: 76, name: "Sports Performance Tracker", slug: "sports-performance-tracker", category: "Health & Fitness Tools", isPro: true },
  { id: 77, name: "Fitness Assessment Dashboard", slug: "fitness-assessment-dashboard", category: "Health & Fitness Tools", isPro: true },
  { id: 78, name: "Body Composition Tracker", slug: "body-composition-tracker", category: "Health & Fitness Tools", isPro: true },
  { id: 79, name: "Weight Trend Analyzer", slug: "weight-trend-analyzer", category: "Health & Fitness Tools", isPro: true },
  { id: 80, name: "Calorie Trend Analyzer", slug: "calorie-trend-analyzer", category: "Health & Fitness Tools", isPro: true },
  { id: 81, name: "Macro Tracking Dashboard", slug: "macro-tracking-dashboard", category: "Health & Fitness Tools", isPro: true },
  { id: 82, name: "Nutrition Tracking Dashboard", slug: "nutrition-tracking-dashboard", category: "Health & Fitness Tools", isPro: true },
  { id: 83, name: "Meal Macro Calculator", slug: "meal-macro-calculator", category: "Health & Fitness Tools", isPro: true },
  { id: 84, name: "Meal Calorie Analyzer", slug: "meal-calorie-analyzer", category: "Health & Fitness Tools", isPro: true },
  { id: 85, name: "Recipe Nutrition Calculator", slug: "recipe-nutrition-calculator", category: "Health & Fitness Tools", isPro: true },
  { id: 86, name: "Food Portion Calculator", slug: "food-portion-calculator", category: "Health & Fitness Tools", isPro: true },
  { id: 87, name: "Hydration Tracking Dashboard", slug: "hydration-tracking-dashboard", category: "Health & Fitness Tools", isPro: true },
  { id: 88, name: "Sleep Tracking Dashboard", slug: "sleep-tracking-dashboard", category: "Health & Fitness Tools", isPro: true },
  { id: 89, name: "Recovery Tracking Dashboard", slug: "recovery-tracking-dashboard", category: "Health & Fitness Tools", isPro: true },
  { id: 90, name: "Habit & Fitness Tracker", slug: "habit-fitness-tracker", category: "Health & Fitness Tools", isPro: true },
  { id: 91, name: "Fitness Goal Forecast", slug: "fitness-goal-forecast", category: "Health & Fitness Tools", isPro: true },
  { id: 92, name: "Training Readiness Planner", slug: "training-readiness-planner", category: "Health & Fitness Tools", isPro: true },
  { id: 93, name: "Workout Performance Analyzer", slug: "workout-performance-analyzer", category: "Health & Fitness Tools", isPro: true },
  { id: 94, name: "Personal Fitness Analytics", slug: "personal-fitness-analytics", category: "Health & Fitness Tools", isPro: true },
  { id: 95, name: "Athlete Training Dashboard", slug: "athlete-training-dashboard", category: "Health & Fitness Tools", isPro: true },
  { id: 96, name: "Coach Client Dashboard", slug: "coach-client-dashboard", category: "Health & Fitness Tools", isPro: true },
  { id: 97, name: "Fitness Progress Report Generator", slug: "fitness-progress-report-generator", category: "Health & Fitness Tools", isPro: true },
  { id: 98, name: "Wellness Habit Dashboard", slug: "wellness-habit-dashboard", category: "Health & Fitness Tools", isPro: true },
  { id: 99, name: "Fitness Program Builder", slug: "fitness-program-builder", category: "Health & Fitness Tools", isPro: true },
  { id: 100, name: "Health & Fitness Analytics Workspace", slug: "health-fitness-analytics-workspace", category: "Health & Fitness Tools", isPro: true },
];