export interface HealthcareAdminTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const healthcareAdminToolsList: HealthcareAdminTool[] = [
  // --- 🔥 PRIORITY 20 FREE TOOLS (IDs 1-20 | isPro: false) ---
  { id: 1, name: "Clinic Capacity Calculator", slug: "clinic-capacity-calculator", category: "Healthcare Administration Tools", isPro: false },
  { id: 2, name: "Appointment Capacity Calculator", slug: "appointment-capacity-calculator", category: "Healthcare Administration Tools", isPro: false },
  { id: 3, name: "Provider Capacity Calculator", slug: "provider-capacity-calculator", category: "Healthcare Administration Tools", isPro: false },
  { id: 4, name: "Patient Flow Calculator", slug: "patient-flow-calculator", category: "Healthcare Administration Tools", isPro: false },
  { id: 5, name: "Waiting Time Calculator", slug: "waiting-time-calculator", category: "Healthcare Administration Tools", isPro: false },
  { id: 6, name: "No-Show Rate Calculator", slug: "no-show-rate-calculator", category: "Healthcare Administration Tools", isPro: false },
  { id: 7, name: "Appointment Fill Rate", slug: "appointment-fill-rate", category: "Healthcare Administration Tools", isPro: false },
  { id: 8, name: "Provider Utilization Calculator", slug: "provider-utilization-calculator", category: "Healthcare Administration Tools", isPro: false },
  { id: 9, name: "Healthcare Staffing Calculator", slug: "healthcare-staffing-calculator", category: "Healthcare Administration Tools", isPro: false },
  { id: 10, name: "Shift Coverage Calculator", slug: "shift-coverage-calculator", category: "Healthcare Administration Tools", isPro: false },
  { id: 11, name: "Appointment Schedule Planner", slug: "appointment-schedule-planner", category: "Healthcare Administration Tools", isPro: false },
  { id: 12, name: "Provider Schedule Builder", slug: "provider-schedule-builder", category: "Healthcare Administration Tools", isPro: false },
  { id: 13, name: "Insurance Verification Checklist", slug: "insurance-verification-checklist", category: "Healthcare Administration Tools", isPro: false },
  { id: 14, name: "Claims Submission Checklist", slug: "claims-submission-checklist", category: "Healthcare Administration Tools", isPro: false },
  { id: 15, name: "Denial Management Checklist", slug: "denial-management-checklist", category: "Healthcare Administration Tools", isPro: false },
  { id: 16, name: "Prior Authorization Tracker", slug: "prior-authorization-tracker", category: "Healthcare Administration Tools", isPro: false },
  { id: 17, name: "Cost Per Visit Calculator", slug: "cost-per-visit-calculator", category: "Healthcare Administration Tools", isPro: false },
  { id: 18, name: "Claim Collection Rate Calculator", slug: "claim-collection-rate-calculator", category: "Healthcare Administration Tools", isPro: false },
  { id: 19, name: "Revenue Cycle Dashboard", slug: "revenue-cycle-dashboard-free", category: "Healthcare Administration Tools", isPro: false },
  { id: 20, name: "Healthcare Operations Workspace", slug: "healthcare-operations-workspace-free", category: "Healthcare Administration Tools", isPro: false },

  // --- REMAINING 40 CORE FREE TOOLS (IDs 21-60 | isPro: false) ---
  { id: 21, name: "Appointment Slot Calculator", slug: "appointment-slot-calculator", category: "Healthcare Administration Tools", isPro: false },
  { id: 22, name: "Appointment Utilization Calculator", slug: "appointment-utilization-calculator", category: "Healthcare Administration Tools", isPro: false },
  { id: 23, name: "Cancellation Rate Calculator", slug: "cancellation-rate-calculator", category: "Healthcare Administration Tools", isPro: false },
  { id: 24, name: "Clinic Occupancy Calculator", slug: "clinic-occupancy-calculator", category: "Healthcare Administration Tools", isPro: false },
  { id: 25, name: "Room Utilization Calculator", slug: "room-utilization-calculator", category: "Healthcare Administration Tools", isPro: false },
  { id: 26, name: "Exam Room Capacity Calculator", slug: "exam-room-capacity-calculator", category: "Healthcare Administration Tools", isPro: false },
  { id: 27, name: "Staff-to-Patient Ratio Calculator", slug: "staff-to-patient-ratio-calculator", category: "Healthcare Administration Tools", isPro: false },
  { id: 28, name: "On-Call Coverage Planner", slug: "on-call-coverage-planner", category: "Healthcare Administration Tools", isPro: false },
  { id: 29, name: "Clinic Staffing Planner", slug: "clinic-staffing-planner", category: "Healthcare Administration Tools", isPro: false },
  { id: 30, name: "Reception Staffing Planner", slug: "reception-staffing-planner", category: "Healthcare Administration Tools", isPro: false },
  { id: 31, name: "Clinic Schedule Builder", slug: "clinic-schedule-builder", category: "Healthcare Administration Tools", isPro: false },
  { id: 32, name: "Patient Appointment Checklist", slug: "patient-appointment-checklist", category: "Healthcare Administration Tools", isPro: false },
  { id: 33, name: "Patient Intake Checklist", slug: "patient-intake-checklist", category: "Healthcare Administration Tools", isPro: false },
  { id: 34, name: "Clinic Opening Checklist", slug: "clinic-opening-checklist", category: "Healthcare Administration Tools", isPro: false },
  { id: 35, name: "Clinic Closing Checklist", slug: "clinic-closing-checklist", category: "Healthcare Administration Tools", isPro: false },
  { id: 36, name: "Patient Flow Checklist", slug: "patient-flow-checklist", category: "Healthcare Administration Tools", isPro: false },
  { id: 37, name: "Referral Workflow Checklist", slug: "referral-workflow-checklist", category: "Healthcare Administration Tools", isPro: false },
  { id: 38, name: "Discharge Workflow Checklist", slug: "discharge-workflow-checklist", category: "Healthcare Administration Tools", isPro: false },
  { id: 39, name: "Medical Records Checklist", slug: "medical-records-checklist", category: "Healthcare Administration Tools", isPro: false },
  { id: 40, name: "Documentation Completeness Checklist", slug: "documentation-completeness-checklist", category: "Healthcare Administration Tools", isPro: false },
  { id: 41, name: "Billing Workflow Checklist", slug: "billing-workflow-checklist", category: "Healthcare Administration Tools", isPro: false },
  { id: 42, name: "Claims Follow-Up Checklist", slug: "claims-follow-up-checklist", category: "Healthcare Administration Tools", isPro: false },
  { id: 43, name: "Referral Tracker", slug: "referral-tracker", category: "Healthcare Administration Tools", isPro: false },
  { id: 44, name: "Patient Follow-Up Tracker", slug: "patient-follow-up-tracker", category: "Healthcare Administration Tools", isPro: false },
  { id: 45, name: "Appointment Reminder Planner", slug: "appointment-reminder-planner", category: "Healthcare Administration Tools", isPro: false },
  { id: 46, name: "Patient Communication Planner", slug: "patient-communication-planner", category: "Healthcare Administration Tools", isPro: false },
  { id: 47, name: "Clinic Task Tracker", slug: "clinic-task-tracker", category: "Healthcare Administration Tools", isPro: false },
  { id: 48, name: "Healthcare Vendor Tracker", slug: "healthcare-vendor-tracker", category: "Healthcare Administration Tools", isPro: false },
  { id: 49, name: "Medical Equipment Inventory", slug: "medical-equipment-inventory", category: "Healthcare Administration Tools", isPro: false },
  { id: 50, name: "Clinic Supply Inventory", slug: "clinic-supply-inventory", category: "Healthcare Administration Tools", isPro: false },
  { id: 51, name: "Medical Supply Reorder Planner", slug: "medical-supply-reorder-planner", category: "Healthcare Administration Tools", isPro: false },
  { id: 52, name: "Healthcare Cost Calculator", slug: "healthcare-cost-calculator", category: "Healthcare Administration Tools", isPro: false },
  { id: 53, name: "Revenue Per Visit Calculator", slug: "revenue-per-visit-calculator", category: "Healthcare Administration Tools", isPro: false },
  { id: 54, name: "Clinic Revenue Calculator", slug: "clinic-revenue-calculator", category: "Healthcare Administration Tools", isPro: false },
  { id: 55, name: "Provider Revenue Calculator", slug: "provider-revenue-calculator", category: "Healthcare Administration Tools", isPro: false },
  { id: 56, name: "Denial Rate Calculator", slug: "denial-rate-calculator", category: "Healthcare Administration Tools", isPro: false },
  { id: 57, name: "Accounts Receivable Aging Calculator", slug: "accounts-receivable-aging-calculator", category: "Healthcare Administration Tools", isPro: false },
  { id: 58, name: "Clinic KPI Generator", slug: "clinic-kpi-generator", category: "Healthcare Administration Tools", isPro: false },
  { id: 59, name: "Healthcare Operations Report", slug: "healthcare-operations-report", category: "Healthcare Administration Tools", isPro: false },
  { id: 60, name: "Clinic Performance Report", slug: "clinic-performance-report", category: "Healthcare Administration Tools", isPro: false },

  // --- ⚡ 40 PRO / SAAS TOOLS (IDs 61-100 | isPro: true) ---
  { id: 61, name: "Healthcare Operations Workspace", slug: "healthcare-operations-workspace", category: "Healthcare Administration Tools", isPro: true },
  { id: 62, name: "Clinic Management Workspace", slug: "clinic-management-workspace", category: "Healthcare Administration Tools", isPro: true },
  { id: 63, name: "Appointment Management Workspace", slug: "appointment-management-workspace", category: "Healthcare Administration Tools", isPro: true },
  { id: 64, name: "Provider Scheduling Workspace", slug: "provider-scheduling-workspace", category: "Healthcare Administration Tools", isPro: true },
  { id: 65, name: "Patient Flow Dashboard", slug: "patient-flow-dashboard", category: "Healthcare Administration Tools", isPro: true },
  { id: 66, name: "Clinic Capacity Dashboard", slug: "clinic-capacity-dashboard", category: "Healthcare Administration Tools", isPro: true },
  { id: 67, name: "Provider Utilization Dashboard", slug: "provider-utilization-dashboard", category: "Healthcare Administration Tools", isPro: true },
  { id: 68, name: "No-Show Analytics", slug: "no-show-analytics", category: "Healthcare Administration Tools", isPro: true },
  { id: 69, name: "Cancellation Analytics", slug: "cancellation-analytics", category: "Healthcare Administration Tools", isPro: true },
  { id: 70, name: "Clinic Staffing Workspace", slug: "clinic-staffing-workspace", category: "Healthcare Administration Tools", isPro: true },
  { id: 71, name: "Shift Management Workspace", slug: "shift-management-workspace", category: "Healthcare Administration Tools", isPro: true },
  { id: 72, name: "On-Call Management Workspace", slug: "on-call-management-workspace", category: "Healthcare Administration Tools", isPro: true },
  { id: 73, name: "Referral Management Workspace", slug: "referral-management-workspace", category: "Healthcare Administration Tools", isPro: true },
  { id: 74, name: "Patient Follow-Up Workspace", slug: "patient-follow-up-workspace", category: "Healthcare Administration Tools", isPro: true },
  { id: 75, name: "Patient Communication Workspace", slug: "patient-communication-workspace", category: "Healthcare Administration Tools", isPro: true },
  { id: 76, name: "Medical Records Operations Workspace", slug: "medical-records-operations-workspace", category: "Healthcare Administration Tools", isPro: true },
  { id: 77, name: "Documentation Quality Dashboard", slug: "documentation-quality-dashboard", category: "Healthcare Administration Tools", isPro: true },
  { id: 78, name: "Insurance Verification Workspace", slug: "insurance-verification-workspace", category: "Healthcare Administration Tools", isPro: true },
  { id: 79, name: "Claims Operations Workspace", slug: "claims-operations-workspace", category: "Healthcare Administration Tools", isPro: true },
  { id: 80, name: "Claims Follow-Up Workspace", slug: "claims-follow-up-workspace", category: "Healthcare Administration Tools", isPro: true },
  { id: 81, name: "Denial Management Workspace", slug: "denial-management-workspace", category: "Healthcare Administration Tools", isPro: true },
  { id: 82, name: "Prior Authorization Workspace", slug: "prior-authorization-workspace", category: "Healthcare Administration Tools", isPro: true },
  { id: 83, name: "Healthcare Billing Analytics", slug: "healthcare-billing-analytics", category: "Healthcare Administration Tools", isPro: true },
  { id: 84, name: "Revenue Cycle Dashboard", slug: "revenue-cycle-dashboard", category: "Healthcare Administration Tools", isPro: true },
  { id: 85, name: "Accounts Receivable Dashboard", slug: "accounts-receivable-dashboard", category: "Healthcare Administration Tools", isPro: true },
  { id: 86, name: "Clinic Revenue Analytics", slug: "clinic-revenue-analytics", category: "Healthcare Administration Tools", isPro: true },
  { id: 87, name: "Healthcare Cost Analytics", slug: "healthcare-cost-analytics", category: "Healthcare Administration Tools", isPro: true },
  { id: 88, name: "Medical Supply Management", slug: "medical-supply-management", category: "Healthcare Administration Tools", isPro: true },
  { id: 89, name: "Healthcare Vendor Management", slug: "healthcare-vendor-management", category: "Healthcare Administration Tools", isPro: true },
  { id: 90, name: "Clinic KPI Dashboard", slug: "clinic-kpi-dashboard", category: "Healthcare Administration Tools", isPro: true },
  { id: 91, name: "Healthcare Reporting Workspace", slug: "healthcare-reporting-workspace", category: "Healthcare Administration Tools", isPro: true },
  { id: 92, name: "Healthcare Data Import Workspace", slug: "healthcare-data-import-workspace", category: "Healthcare Administration Tools", isPro: true },
  { id: 93, name: "Healthcare Data Export Workspace", slug: "healthcare-data-export-workspace", category: "Healthcare Administration Tools", isPro: true },
  { id: 94, name: "Healthcare API Workspace", slug: "healthcare-api-workspace", category: "Healthcare Administration Tools", isPro: true },
  { id: 95, name: "Healthcare Workflow Automation", slug: "healthcare-workflow-automation", category: "Healthcare Administration Tools", isPro: true },
  { id: 96, name: "Healthcare Operations Analytics", slug: "healthcare-operations-analytics", category: "Healthcare Administration Tools", isPro: true },
  { id: 97, name: "Multi-Clinic Management Workspace", slug: "multi-clinic-management-workspace", category: "Healthcare Administration Tools", isPro: true },
  { id: 98, name: "Healthcare Administration Platform", slug: "healthcare-administration-platform", category: "Healthcare Administration Tools", isPro: true },
  { id: 99, name: "Healthcare Operations Intelligence", slug: "healthcare-operations-intelligence", category: "Healthcare Administration Tools", isPro: true },
  { id: 100, name: "Healthcare Command Center", slug: "healthcare-command-center", category: "Healthcare Administration Tools", isPro: true }
];