export interface HRCareerTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const hrCareerToolsList: HRCareerTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-15) ---
  { id: 1, name: "Resume Builder", slug: "resume-builder", category: "HR & Career Tools", isPro: false },
  { id: 2, name: "ATS Resume Checker", slug: "ats-resume-checker", category: "HR & Career Tools", isPro: false },
  { id: 3, name: "Job Description Analyzer", slug: "job-description-analyzer", category: "HR & Career Tools", isPro: false },
  { id: 4, name: "Resume Job Match Analyzer", slug: "resume-job-match-analyzer", category: "HR & Career Tools", isPro: false },
  { id: 5, name: "Cover Letter Builder", slug: "cover-letter-builder", category: "HR & Career Tools", isPro: false },
  { id: 6, name: "Interview Practice Tool", slug: "interview-practice-tool", category: "HR & Career Tools", isPro: false },
  { id: 7, name: "Interview Question Generator", slug: "interview-question-generator", category: "HR & Career Tools", isPro: false },
  { id: 8, name: "Salary Comparison Tool", slug: "salary-comparison-tool", category: "HR & Career Tools", isPro: false },
  { id: 9, name: "Salary Negotiation Calculator", slug: "salary-negotiation-calculator", category: "HR & Career Tools", isPro: false },
  { id: 10, name: "Career Skills Gap Analyzer", slug: "career-skills-gap-analyzer", category: "HR & Career Tools", isPro: false },
  { id: 11, name: "ATS Keyword Matcher", slug: "ats-keyword-matcher", category: "HR & Career Tools", isPro: false },
  { id: 12, name: "Professional Summary Generator", slug: "professional-summary-generator", category: "HR & Career Tools", isPro: false },
  { id: 13, name: "Behavioral Interview Practice", slug: "behavioral-interview-practice", category: "HR & Career Tools", isPro: false },
  { id: 14, name: "STAR Answer Builder", slug: "star-answer-builder", category: "HR & Career Tools", isPro: false },
  { id: 15, name: "Career Path Generator", slug: "career-path-generator", category: "HR & Career Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (16-60) ---
  { id: 16, name: "Resume Formatter", slug: "resume-formatter", category: "HR & Career Tools", isPro: false },
  { id: 17, name: "Resume Template Builder", slug: "resume-template-builder", category: "HR & Career Tools", isPro: false },
  { id: 18, name: "Resume Keyword Extractor", slug: "resume-keyword-extractor", category: "HR & Career Tools", isPro: false },
  { id: 19, name: "Resume Score Analyzer", slug: "resume-score-analyzer", category: "HR & Career Tools", isPro: false },
  { id: 20, name: "Resume Section Analyzer", slug: "resume-section-analyzer", category: "HR & Career Tools", isPro: false },
  { id: 21, name: "Resume Skills Extractor", slug: "resume-skills-extractor", category: "HR & Career Tools", isPro: false },
  { id: 22, name: "Resume Experience Analyzer", slug: "resume-experience-analyzer", category: "HR & Career Tools", isPro: false },
  { id: 23, name: "Resume Achievement Generator", slug: "resume-achievement-generator", category: "HR & Career Tools", isPro: false },
  { id: 24, name: "Resume Bullet Improver", slug: "resume-bullet-improver", category: "HR & Career Tools", isPro: false },
  { id: 25, name: "Resume Summary Generator", slug: "resume-summary-generator", category: "HR & Career Tools", isPro: false },
  { id: 26, name: "Career Objective Generator", slug: "career-objective-generator", category: "HR & Career Tools", isPro: false },
  { id: 27, name: "Cover Letter Personalizer", slug: "cover-letter-personalizer", category: "HR & Career Tools", isPro: false },
  { id: 28, name: "Job Application Tracker", slug: "job-application-tracker", category: "HR & Career Tools", isPro: false },
  { id: 29, name: "Job Requirement Extractor", slug: "job-requirement-extractor", category: "HR & Career Tools", isPro: false },
  { id: 30, name: "Job Skills Extractor", slug: "job-skills-extractor", category: "HR & Career Tools", isPro: false },
  { id: 31, name: "Job Qualification Matcher", slug: "job-qualification-matcher", category: "HR & Career Tools", isPro: false },
  { id: 32, name: "Job Fit Score Calculator", slug: "job-fit-score-calculator", category: "HR & Career Tools", isPro: false },
  { id: 33, name: "Skill Assessment Generator", slug: "skill-assessment-generator", category: "HR & Career Tools", isPro: false },
  { id: 34, name: "Interview Answer Generator", slug: "interview-answer-generator", category: "HR & Career Tools", isPro: false },
  { id: 35, name: "Technical Interview Planner", slug: "technical-interview-planner", category: "HR & Career Tools", isPro: false },
  { id: 36, name: "Interview Feedback Form", slug: "interview-feedback-form", category: "HR & Career Tools", isPro: false },
  { id: 37, name: "Interview Scorecard", slug: "interview-scorecard", category: "HR & Career Tools", isPro: false },
  { id: 38, name: "Salary Range Analyzer", slug: "salary-range-analyzer", category: "HR & Career Tools", isPro: false },
  { id: 39, name: "Raise Calculator", slug: "raise-calculator", category: "HR & Career Tools", isPro: false },
  { id: 40, name: "Promotion Calculator", slug: "promotion-calculator", category: "HR & Career Tools", isPro: false },
  { id: 41, name: "Compensation Calculator", slug: "compensation-calculator", category: "HR & Career Tools", isPro: false },
  { id: 42, name: "Total Compensation Calculator", slug: "total-compensation-calculator", category: "HR & Career Tools", isPro: false },
  { id: 43, name: "Benefits Value Calculator", slug: "benefits-value-calculator", category: "HR & Career Tools", isPro: false },
  { id: 44, name: "Hourly-to-Salary Converter", slug: "hourly-to-salary-converter", category: "HR & Career Tools", isPro: false },
  { id: 45, name: "Salary-to-Hourly Converter", slug: "salary-to-hourly-converter", category: "HR & Career Tools", isPro: false },
  { id: 46, name: "Notice Period Calculator", slug: "notice-period-calculator-hr", category: "HR & Career Tools", isPro: false },
  { id: 47, name: "Career Change Planner", slug: "career-change-planner", category: "HR & Career Tools", isPro: false },
  { id: 48, name: "Career Goal Planner", slug: "career-goal-planner", category: "HR & Career Tools", isPro: false },
  { id: 49, name: "Career Development Planner", slug: "career-development-planner", category: "HR & Career Tools", isPro: false },
  { id: 50, name: "Skill Development Planner", slug: "skill-development-planner", category: "HR & Career Tools", isPro: false },
  { id: 51, name: "Professional Bio Generator", slug: "professional-bio-generator", category: "HR & Career Tools", isPro: false },
  { id: 52, name: "LinkedIn Resume Converter", slug: "linkedin-resume-converter", category: "HR & Career Tools", isPro: false },
  { id: 53, name: "Resume PDF Exporter", slug: "resume-pdf-exporter", category: "HR & Career Tools", isPro: false },
  { id: 54, name: "Job Application Email Builder", slug: "job-application-email-builder", category: "HR & Career Tools", isPro: false },
  { id: 55, name: "Recruiter Message Generator", slug: "recruiter-message-generator", category: "HR & Career Tools", isPro: false },
  { id: 56, name: "Networking Message Generator", slug: "networking-message-generator", category: "HR & Career Tools", isPro: false },
  { id: 57, name: "Reference Request Generator", slug: "reference-request-generator", category: "HR & Career Tools", isPro: false },
  { id: 58, name: "Resignation Letter Builder", slug: "resignation-letter-builder", category: "HR & Career Tools", isPro: false },
  { id: 59, name: "Promotion Request Letter Generator", slug: "promotion-request-letter-generator", category: "HR & Career Tools", isPro: false },
  { id: 60, name: "Performance Review Generator", slug: "performance-review-generator", category: "HR & Career Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "AI Resume Optimization Engine", slug: "ai-resume-optimization-engine", category: "HR & Career Tools", isPro: true },
  { id: 62, name: "Candidate Ranking Engine", slug: "candidate-ranking-engine", category: "HR & Career Tools", isPro: true },
  { id: 63, name: "Recruitment Funnel Analyzer", slug: "recruitment-funnel-analyzer", category: "HR & Career Tools", isPro: true },
  { id: 64, name: "Employee Performance Dashboard", slug: "employee-performance-dashboard", category: "HR & Career Tools", isPro: true },
  { id: 65, name: "Workforce Planning Dashboard", slug: "workforce-planning-dashboard", category: "HR & Career Tools", isPro: true },
  { id: 66, name: "Multi-Job Resume Matcher", slug: "multi-job-resume-matcher", category: "HR & Career Tools", isPro: true },
  { id: 67, name: "Resume Version Manager", slug: "resume-version-manager", category: "HR & Career Tools", isPro: true },
  { id: 68, name: "Resume A/B Testing Tool", slug: "resume-ab-testing-tool", category: "HR & Career Tools", isPro: true },
  { id: 69, name: "Career Path Intelligence Engine", slug: "career-path-intelligence-engine", category: "HR & Career Tools", isPro: true },
  { id: 70, name: "Career Transition Analyzer", slug: "career-transition-analyzer", category: "HR & Career Tools", isPro: true },
  { id: 71, name: "Skills Gap Intelligence Platform", slug: "skills-gap-intelligence-platform", category: "HR & Career Tools", isPro: true },
  { id: 72, name: "Workforce Skills Analyzer", slug: "workforce-skills-analyzer", category: "HR & Career Tools", isPro: true },
  { id: 73, name: "Employee Skills Matrix", slug: "employee-skills-matrix", category: "HR & Career Tools", isPro: true },
  { id: 74, name: "Competency Matrix Builder", slug: "competency-matrix-builder", category: "HR & Career Tools", isPro: true },
  { id: 75, name: "Performance Review Analyzer", slug: "performance-review-analyzer", category: "HR & Career Tools", isPro: true },
  { id: 76, name: "360-Degree Feedback Analyzer", slug: "360-degree-feedback-analyzer", category: "HR & Career Tools", isPro: true },
  { id: 77, name: "Employee Engagement Survey Analyzer", slug: "employee-engagement-survey-analyzer", category: "HR & Career Tools", isPro: true },
  { id: 78, name: "Employee Retention Risk Analyzer", slug: "employee-retention-risk-analyzer", category: "HR & Career Tools", isPro: true },
  { id: 79, name: "Employee Turnover Calculator", slug: "employee-turnover-calculator", category: "HR & Career Tools", isPro: true },
  { id: 80, name: "Workforce Cost Calculator", slug: "workforce-cost-calculator", category: "HR & Career Tools", isPro: true },
  { id: 81, name: "Headcount Planning Tool", slug: "headcount-planning-tool", category: "HR & Career Tools", isPro: true },
  { id: 82, name: "Hiring Cost Calculator", slug: "hiring-cost-calculator", category: "HR & Career Tools", isPro: true },
  { id: 83, name: "Cost-per-Hire Calculator", slug: "cost-per-hire-calculator", category: "HR & Career Tools", isPro: true },
  { id: 84, name: "Time-to-Hire Calculator", slug: "time-to-hire-calculator", category: "HR & Career Tools", isPro: true },
  { id: 85, name: "Applicant Pipeline Dashboard", slug: "applicant-pipeline-dashboard", category: "HR & Career Tools", isPro: true },
  { id: 86, name: "Candidate Comparison Tool", slug: "candidate-comparison-tool", category: "HR & Career Tools", isPro: true },
  { id: 87, name: "Interview Pipeline Manager", slug: "interview-pipeline-manager", category: "HR & Career Tools", isPro: true },
  { id: 88, name: "Interview Scheduling Planner", slug: "interview-scheduling-planner", category: "HR & Career Tools", isPro: true },
  { id: 89, name: "Onboarding Checklist Builder", slug: "onboarding-checklist-builder", category: "HR & Career Tools", isPro: true },
  { id: 90, name: "Employee Onboarding Planner", slug: "employee-onboarding-planner", category: "HR & Career Tools", isPro: true },
  { id: 91, name: "Offboarding Checklist Builder", slug: "offboarding-checklist-builder", category: "HR & Career Tools", isPro: true },
  { id: 92, name: "HR Policy Generator", slug: "hr-policy-generator", category: "HR & Career Tools", isPro: true },
  { id: 93, name: "Employee Handbook Builder", slug: "employee-handbook-builder", category: "HR & Career Tools", isPro: true },
  { id: 94, name: "HR Compliance Checklist", slug: "hr-compliance-checklist", category: "HR & Career Tools", isPro: true },
  { id: 95, name: "Compensation Benchmarking Tool", slug: "compensation-benchmarking-tool", category: "HR & Career Tools", isPro: true },
  { id: 96, name: "Workforce Analytics Dashboard", slug: "workforce-analytics-dashboard", category: "HR & Career Tools", isPro: true },
  { id: 97, name: "HR KPI Dashboard", slug: "hr-kpi-dashboard", category: "HR & Career Tools", isPro: true },
  { id: 98, name: "Talent Intelligence Dashboard", slug: "talent-intelligence-dashboard", category: "HR & Career Tools", isPro: true },
  { id: 99, name: "Career Intelligence Workspace", slug: "career-intelligence-workspace", category: "HR & Career Tools", isPro: true },
  { id: 100, name: "HR Management Workspace", slug: "hr-management-workspace", category: "HR & Career Tools", isPro: true },
];