export interface InsuranceTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const insuranceToolsList: InsuranceTool[] = [
  // --- 🔥 PRIORITY 20 FREE TOOLS (IDs 1-20 | isPro: false) ---
  { id: 1, name: "Insurance Coverage Gap Calculator", slug: "insurance-coverage-gap-calculator", category: "Insurance Tools", isPro: false },
  { id: 2, name: "Life Insurance Coverage Calculator", slug: "life-insurance-coverage-calculator", category: "Insurance Tools", isPro: false },
  { id: 3, name: "Income Replacement Calculator", slug: "income-replacement-calculator", category: "Insurance Tools", isPro: false },
  { id: 4, name: "Insurance Need Estimator", slug: "insurance-need-estimator", category: "Insurance Tools", isPro: false },
  { id: 5, name: "Deductible Comparison Calculator", slug: "deductible-comparison-calculator", category: "Insurance Tools", isPro: false },
  { id: 6, name: "Premium Comparison Calculator", slug: "premium-comparison-calculator", category: "Insurance Tools", isPro: false },
  { id: 7, name: "Out-of-Pocket Cost Estimator", slug: "out-of-pocket-cost-estimator", category: "Insurance Tools", isPro: false },
  { id: 8, name: "Coverage Limit Comparison", slug: "coverage-limit-comparison", category: "Insurance Tools", isPro: false },
  { id: 9, name: "Co-Insurance Calculator", slug: "co-insurance-calculator", category: "Insurance Tools", isPro: false },
  { id: 10, name: "Deductible Break-Even Calculator", slug: "deductible-break-even-calculator", category: "Insurance Tools", isPro: false },
  { id: 11, name: "Policy Cost Comparison", slug: "policy-cost-comparison", category: "Insurance Tools", isPro: false },
  { id: 12, name: "Insurance Quote Comparison", slug: "insurance-quote-comparison", category: "Insurance Tools", isPro: false },
  { id: 13, name: "Multi-Policy Comparison", slug: "multi-policy-comparison", category: "Insurance Tools", isPro: false },
  { id: 14, name: "Replacement Cost Calculator", slug: "replacement-cost-calculator", category: "Insurance Tools", isPro: false },
  { id: 15, name: "Business Insurance Coverage Planner", slug: "business-insurance-coverage-planner", category: "Insurance Tools", isPro: false },
  { id: 16, name: "Policy Review Checklist", slug: "policy-review-checklist", category: "Insurance Tools", isPro: false },
  { id: 17, name: "Claim Preparation Checklist", slug: "claim-preparation-checklist", category: "Insurance Tools", isPro: false },
  { id: 18, name: "Policy Renewal Tracker", slug: "policy-renewal-tracker", category: "Insurance Tools", isPro: false },
  { id: 19, name: "Coverage Gap Dashboard", slug: "coverage-gap-dashboard-free", category: "Insurance Tools", isPro: false },
  { id: 20, name: "Insurance Planning Workspace", slug: "insurance-planning-workspace-free", category: "Insurance Tools", isPro: false },

  // --- REMAINING 40 CORE FREE TOOLS (IDs 21-60 | isPro: false) ---
  { id: 21, name: "Term Insurance Coverage Planner", slug: "term-insurance-coverage-planner", category: "Insurance Tools", isPro: false },
  { id: 22, name: "Annual Premium Calculator", slug: "annual-premium-calculator", category: "Insurance Tools", isPro: false },
  { id: 23, name: "Monthly Premium Calculator", slug: "monthly-premium-calculator", category: "Insurance Tools", isPro: false },
  { id: 24, name: "Total Premium Cost Calculator", slug: "total-premium-cost-calculator", category: "Insurance Tools", isPro: false },
  { id: 25, name: "Policy Limit Comparison", slug: "policy-limit-comparison", category: "Insurance Tools", isPro: false },
  { id: 26, name: "Co-Pay Cost Calculator", slug: "co-pay-cost-calculator", category: "Insurance Tools", isPro: false },
  { id: 27, name: "Insurance Bundle Comparison", slug: "insurance-bundle-comparison", category: "Insurance Tools", isPro: false },
  { id: 28, name: "Life Insurance Term Comparison", slug: "life-insurance-term-comparison", category: "Insurance Tools", isPro: false },
  { id: 29, name: "Coverage Duration Calculator", slug: "coverage-duration-calculator", category: "Insurance Tools", isPro: false },
  { id: 30, name: "Insurance Inflation Calculator", slug: "insurance-inflation-calculator", category: "Insurance Tools", isPro: false },
  { id: 31, name: "Home Contents Coverage Calculator", slug: "home-contents-coverage-calculator", category: "Insurance Tools", isPro: false },
  { id: 32, name: "Small Business Insurance Checklist", slug: "small-business-insurance-checklist", category: "Insurance Tools", isPro: false },
  { id: 33, name: "Insurance Policy Checklist", slug: "insurance-policy-checklist", category: "Insurance Tools", isPro: false },
  { id: 34, name: "Renewal Review Checklist", slug: "renewal-review-checklist", category: "Insurance Tools", isPro: false },
  { id: 35, name: "Insurance Document Checklist", slug: "insurance-document-checklist", category: "Insurance Tools", isPro: false },
  { id: 36, name: "Claim Document Checklist", slug: "claim-document-checklist", category: "Insurance Tools", isPro: false },
  { id: 37, name: "Claim Submission Checklist", slug: "claim-submission-checklist", category: "Insurance Tools", isPro: false },
  { id: 38, name: "Claim Follow-Up Checklist", slug: "claim-follow-up-checklist", category: "Insurance Tools", isPro: false },
  { id: 39, name: "Claim Timeline Tracker", slug: "claim-timeline-tracker", category: "Insurance Tools", isPro: false },
  { id: 40, name: "Premium Due Date Tracker", slug: "premium-due-date-tracker", category: "Insurance Tools", isPro: false },
  { id: 41, name: "Policy Expiration Tracker", slug: "policy-expiration-tracker", category: "Insurance Tools", isPro: false },
  { id: 42, name: "Insurance Portfolio Tracker", slug: "insurance-portfolio-tracker", category: "Insurance Tools", isPro: false },
  { id: 43, name: "Beneficiary Checklist", slug: "beneficiary-checklist", category: "Insurance Tools", isPro: false },
  { id: 44, name: "Coverage Inventory Builder", slug: "coverage-inventory-builder", category: "Insurance Tools", isPro: false },
  { id: 45, name: "Asset Coverage Inventory", slug: "asset-coverage-inventory", category: "Insurance Tools", isPro: false },
  { id: 46, name: "Insurance Needs Questionnaire", slug: "insurance-needs-questionnaire", category: "Insurance Tools", isPro: false },
  { id: 47, name: "Policy Comparison Questionnaire", slug: "policy-comparison-questionnaire", category: "Insurance Tools", isPro: false },
  { id: 48, name: "Insurance Quote Request Builder", slug: "insurance-quote-request-builder", category: "Insurance Tools", isPro: false },
  { id: 49, name: "Agent Meeting Checklist", slug: "agent-meeting-checklist", category: "Insurance Tools", isPro: false },
  { id: 50, name: "Insurance Review Meeting Planner", slug: "insurance-review-meeting-planner", category: "Insurance Tools", isPro: false },
  { id: 51, name: "Claim Call Checklist", slug: "claim-call-checklist", category: "Insurance Tools", isPro: false },
  { id: 52, name: "Policy Change Checklist", slug: "policy-change-checklist", category: "Insurance Tools", isPro: false },
  { id: 53, name: "Insurance Cost Calculator", slug: "insurance-cost-calculator", category: "Insurance Tools", isPro: false },
  { id: 54, name: "Coverage Ratio Calculator", slug: "coverage-ratio-calculator", category: "Insurance Tools", isPro: false },
  { id: 55, name: "Insurance Expense Tracker", slug: "insurance-expense-tracker", category: "Insurance Tools", isPro: false },
  { id: 56, name: "Premium Payment Planner", slug: "premium-payment-planner", category: "Insurance Tools", isPro: false },
  { id: 57, name: "Policy Savings Calculator", slug: "policy-savings-calculator", category: "Insurance Tools", isPro: false },
  { id: 58, name: "Claim Status Tracker", slug: "claim-status-tracker", category: "Insurance Tools", isPro: false },
  { id: 59, name: "Insurance Document Organizer", slug: "insurance-document-organizer", category: "Insurance Tools", isPro: false },
  { id: 60, name: "Insurance Summary Generator", slug: "insurance-summary-generator", category: "Insurance Tools", isPro: false },

  // --- ⚡ 40 PRO / SAAS TOOLS (IDs 61-100 | isPro: true) ---
  { id: 61, name: "Insurance Planning Workspace", slug: "insurance-planning-workspace", category: "Insurance Tools", isPro: true },
  { id: 62, name: "Policy Management Workspace", slug: "policy-management-workspace", category: "Insurance Tools", isPro: true },
  { id: 63, name: "Insurance Portfolio Dashboard", slug: "insurance-portfolio-dashboard", category: "Insurance Tools", isPro: true },
  { id: 64, name: "Coverage Analysis Workspace", slug: "coverage-analysis-workspace", category: "Insurance Tools", isPro: true },
  { id: 65, name: "Coverage Gap Dashboard", slug: "coverage-gap-dashboard", category: "Insurance Tools", isPro: true },
  { id: 66, name: "Policy Comparison Workspace", slug: "policy-comparison-workspace", category: "Insurance Tools", isPro: true },
  { id: 67, name: "Quote Comparison Workspace", slug: "quote-comparison-workspace", category: "Insurance Tools", isPro: true },
  { id: 68, name: "Premium Analytics Workspace", slug: "premium-analytics-workspace", category: "Insurance Tools", isPro: true },
  { id: 69, name: "Deductible Optimization Workspace", slug: "deductible-optimization-workspace", category: "Insurance Tools", isPro: true },
  { id: 70, name: "Out-of-Pocket Planning Workspace", slug: "out-of-pocket-planning-workspace", category: "Insurance Tools", isPro: true },
  { id: 71, name: "Life Insurance Planning Workspace", slug: "life-insurance-planning-workspace", category: "Insurance Tools", isPro: true },
  { id: 72, name: "Business Insurance Planning Workspace", slug: "business-insurance-planning-workspace", category: "Insurance Tools", isPro: true },
  { id: 73, name: "Asset Coverage Workspace", slug: "asset-coverage-workspace", category: "Insurance Tools", isPro: true },
  { id: 74, name: "Insurance Renewal Workspace", slug: "insurance-renewal-workspace", category: "Insurance Tools", isPro: true },
  { id: 75, name: "Policy Expiration Management", slug: "policy-expiration-management", category: "Insurance Tools", isPro: true },
  { id: 76, name: "Premium Payment Management", slug: "premium-payment-management", category: "Insurance Tools", isPro: true },
  { id: 77, name: "Claims Management Workspace", slug: "claims-management-workspace", category: "Insurance Tools", isPro: true },
  { id: 78, name: "Claim Documentation Workspace", slug: "claim-documentation-workspace", category: "Insurance Tools", isPro: true },
  { id: 79, name: "Claim Timeline Management", slug: "claim-timeline-management", category: "Insurance Tools", isPro: true },
  { id: 80, name: "Claim Follow-Up Workspace", slug: "claim-follow-up-workspace", category: "Insurance Tools", isPro: true },
  { id: 81, name: "Insurance Document Management", slug: "insurance-document-management", category: "Insurance Tools", isPro: true },
  { id: 82, name: "Beneficiary Management Workspace", slug: "beneficiary-management-workspace", category: "Insurance Tools", isPro: true },
  { id: 83, name: "Insurance Cost Dashboard", slug: "insurance-cost-dashboard", category: "Insurance Tools", isPro: true },
  { id: 84, name: "Policy Savings Dashboard", slug: "policy-savings-dashboard", category: "Insurance Tools", isPro: true },
  { id: 85, name: "Coverage Analytics", slug: "coverage-analytics", category: "Insurance Tools", isPro: true },
  { id: 86, name: "Insurance Portfolio Analytics", slug: "insurance-portfolio-analytics", category: "Insurance Tools", isPro: true },
  { id: 87, name: "Customer Policy Review Workspace", slug: "customer-policy-review-workspace", category: "Insurance Tools", isPro: true },
  { id: 88, name: "Agent Client Workspace", slug: "agent-client-workspace", category: "Insurance Tools", isPro: true },
  { id: 89, name: "Broker Policy Workspace", slug: "broker-policy-workspace", category: "Insurance Tools", isPro: true },
  { id: 90, name: "Insurance Customer Dashboard", slug: "insurance-customer-dashboard", category: "Insurance Tools", isPro: true },
  { id: 91, name: "Insurance Data Import Workspace", slug: "insurance-data-import-workspace", category: "Insurance Tools", isPro: true },
  { id: 92, name: "Insurance Data Export Workspace", slug: "insurance-data-export-workspace", category: "Insurance Tools", isPro: true },
  { id: 93, name: "Insurance API Workspace", slug: "insurance-api-workspace", category: "Insurance Tools", isPro: true },
  { id: 94, name: "Insurance Workflow Automation", slug: "insurance-workflow-automation", category: "Insurance Tools", isPro: true },
  { id: 95, name: "Insurance Reporting Engine", slug: "insurance-reporting-engine", category: "Insurance Tools", isPro: true },
  { id: 96, name: "Policy Intelligence Workspace", slug: "policy-intelligence-workspace", category: "Insurance Tools", isPro: true },
  { id: 97, name: "Insurance Comparison Platform", slug: "insurance-comparison-platform", category: "Insurance Tools", isPro: true },
  { id: 98, name: "Insurance Planning Platform", slug: "insurance-planning-platform", category: "Insurance Tools", isPro: true },
  { id: 99, name: "Insurance Management Platform", slug: "insurance-management-platform", category: "Insurance Tools", isPro: true },
  { id: 100, name: "Insurance Command Center", slug: "insurance-command-center", category: "Insurance Tools", isPro: true }
];