export interface LanguageTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const languageToolsList: LanguageTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-10) ---
  { id: 1, name: "Language Translator", slug: "language-translator", category: "Language Tools", isPro: false },
  { id: 2, name: "Document Translator", slug: "document-translator-lang", category: "Language Tools", isPro: false },
  { id: 3, name: "Language Detector", slug: "language-detector", category: "Language Tools", isPro: false },
  { id: 4, name: "Dictionary Lookup", slug: "dictionary-lookup", category: "Language Tools", isPro: false },
  { id: 5, name: "Grammar Checker", slug: "grammar-checker-lang", category: "Language Tools", isPro: false },
  { id: 6, name: "Spelling Checker", slug: "spelling-checker-lang", category: "Language Tools", isPro: false },
  { id: 7, name: "Sentence Rephraser", slug: "sentence-rephraser", category: "Language Tools", isPro: false },
  { id: 8, name: "Sentence Simplifier", slug: "sentence-simplifier", category: "Language Tools", isPro: false },
  { id: 9, name: "Pronunciation Guide", slug: "pronunciation-guide", category: "Language Tools", isPro: false },
  { id: 10, name: "Transliteration Tool", slug: "transliteration-tool", category: "Language Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (11-60) ---
  { id: 11, name: "Word Translator", slug: "word-translator", category: "Language Tools", isPro: false },
  { id: 12, name: "Sentence Translator", slug: "sentence-translator", category: "Language Tools", isPro: false },
  { id: 13, name: "Paragraph Translator", slug: "paragraph-translator", category: "Language Tools", isPro: false },
  { id: 14, name: "Website Translator", slug: "website-translator", category: "Language Tools", isPro: false },
  { id: 15, name: "Translation Comparison Tool", slug: "translation-comparison-tool", category: "Language Tools", isPro: false },
  { id: 16, name: "Definition Finder", slug: "definition-finder-lang", category: "Language Tools", isPro: false },
  { id: 17, name: "Synonym Finder", slug: "synonym-finder-lang", category: "Language Tools", isPro: false },
  { id: 18, name: "Antonym Finder", slug: "antonym-finder-lang", category: "Language Tools", isPro: false },
  { id: 19, name: "Homonym Finder", slug: "homonym-finder", category: "Language Tools", isPro: false },
  { id: 20, name: "Homophone Finder", slug: "homophone-finder", category: "Language Tools", isPro: false },
  { id: 21, name: "Word Meaning Finder", slug: "word-meaning-finder", category: "Language Tools", isPro: false },
  { id: 22, name: "Phonetic Converter", slug: "phonetic-converter", category: "Language Tools", isPro: false },
  { id: 23, name: "IPA Converter", slug: "ipa-converter", category: "Language Tools", isPro: false },
  { id: 24, name: "Romanization Converter", slug: "romanization-converter", category: "Language Tools", isPro: false },
  { id: 25, name: "Sentence Corrector", slug: "sentence-corrector", category: "Language Tools", isPro: false },
  { id: 26, name: "Punctuation Checker", slug: "punctuation-checker", category: "Language Tools", isPro: false },
  { id: 27, name: "Vocabulary Checker", slug: "vocabulary-checker", category: "Language Tools", isPro: false },
  { id: 28, name: "Vocabulary Builder", slug: "vocabulary-builder-lang", category: "Language Tools", isPro: false },
  { id: 29, name: "Word Difficulty Checker", slug: "word-difficulty-checker", category: "Language Tools", isPro: false },
  { id: 30, name: "Word Frequency Analyzer", slug: "word-frequency-analyzer-lang", category: "Language Tools", isPro: false },
  { id: 31, name: "Word Finder", slug: "word-finder", category: "Language Tools", isPro: false },
  { id: 32, name: "Anagram Solver", slug: "anagram-solver", category: "Language Tools", isPro: false },
  { id: 33, name: "Word Unscrambler", slug: "word-unscrambler", category: "Language Tools", isPro: false },
  { id: 34, name: "Crossword Solver", slug: "crossword-solver", category: "Language Tools", isPro: false },
  { id: 35, name: "Word Scrambler", slug: "word-scrambler", category: "Language Tools", isPro: false },
  { id: 36, name: "Rhyming Word Finder", slug: "rhyming-word-finder", category: "Language Tools", isPro: false },
  { id: 37, name: "Rhyme Generator", slug: "rhyme-generator", category: "Language Tools", isPro: false },
  { id: 38, name: "Prefix Finder", slug: "prefix-finder", category: "Language Tools", isPro: false },
  { id: 39, name: "Suffix Finder", slug: "suffix-finder", category: "Language Tools", isPro: false },
  { id: 40, name: "Root Word Finder", slug: "root-word-finder", category: "Language Tools", isPro: false },
  { id: 41, name: "Compound Word Finder", slug: "compound-word-finder", category: "Language Tools", isPro: false },
  { id: 42, name: "Word Family Finder", slug: "word-family-finder", category: "Language Tools", isPro: false },
  { id: 43, name: "Sentence Expander", slug: "sentence-expander", category: "Language Tools", isPro: false },
  { id: 44, name: "Formal Language Converter", slug: "formal-language-converter", category: "Language Tools", isPro: false },
  { id: 45, name: "Casual Language Converter", slug: "casual-language-converter", category: "Language Tools", isPro: false },
  { id: 46, name: "Active Voice Converter", slug: "active-voice-converter", category: "Language Tools", isPro: false },
  { id: 47, name: "Passive Voice Converter", slug: "passive-voice-converter", category: "Language Tools", isPro: false },
  { id: 48, name: "Gender-Neutral Language Checker", slug: "gender-neutral-language-checker", category: "Language Tools", isPro: false },
  { id: 49, name: "Inclusive Language Checker", slug: "inclusive-language-checker-lang", category: "Language Tools", isPro: false },
  { id: 50, name: "Professional Language Converter", slug: "professional-language-converter", category: "Language Tools", isPro: false },
  { id: 51, name: "Academic Language Converter", slug: "academic-language-converter", category: "Language Tools", isPro: false },
  { id: 52, name: "Business Language Converter", slug: "business-language-converter", category: "Language Tools", isPro: false },
  { id: 53, name: "Plain English Converter", slug: "plain-english-converter", category: "Language Tools", isPro: false },
  { id: 54, name: "Reading Level Checker", slug: "reading-level-checker", category: "Language Tools", isPro: false },
  { id: 55, name: "CEFR Level Checker", slug: "cefr-level-checker", category: "Language Tools", isPro: false },
  { id: 56, name: "English Fluency Estimator", slug: "english-fluency-estimator", category: "Language Tools", isPro: false },
  { id: 57, name: "Writing Level Checker", slug: "writing-level-checker", category: "Language Tools", isPro: false },
  { id: 58, name: "Vocabulary Level Test", slug: "vocabulary-level-test", category: "Language Tools", isPro: false },
  { id: 59, name: "Grammar Practice Generator", slug: "grammar-practice-generator", category: "Language Tools", isPro: false },
  { id: 60, name: "Language Practice Quiz", slug: "language-practice-quiz", category: "Language Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-65) ---
  { id: 61, name: "AI Language Tutor", slug: "ai-language-tutor", category: "Language Tools", isPro: true },
  { id: 62, name: "AI Conversation Partner", slug: "ai-conversation-partner", category: "Language Tools", isPro: true },
  { id: 63, name: "AI Writing Coach", slug: "ai-writing-coach", category: "Language Tools", isPro: true },
  { id: 64, name: "IELTS Writing Analyzer", slug: "ielts-writing-analyzer", category: "Language Tools", isPro: true },
  { id: 65, name: "English Interview Practice", slug: "english-interview-practice", category: "Language Tools", isPro: true },

  // --- REMAINING PRO LEVEL TOOLS (66-100) ---
  { id: 66, name: "AI Speaking Practice", slug: "ai-speaking-practice", category: "Language Tools", isPro: true },
  { id: 67, name: "AI Pronunciation Coach", slug: "ai-pronunciation-coach", category: "Language Tools", isPro: true },
  { id: 68, name: "AI Grammar Coach", slug: "ai-grammar-coach", category: "Language Tools", isPro: true },
  { id: 69, name: "Personalized Language Learning Planner", slug: "personalized-language-learning-planner", category: "Language Tools", isPro: true },
  { id: 70, name: "Adaptive Language Quiz", slug: "adaptive-language-quiz", category: "Language Tools", isPro: true },
  { id: 71, name: "Language Proficiency Assessment", slug: "language-proficiency-assessment", category: "Language Tools", isPro: true },
  { id: 72, name: "CEFR Assessment Tool", slug: "cefr-assessment-tool", category: "Language Tools", isPro: true },
  { id: 73, name: "IELTS Speaking Practice", slug: "ielts-speaking-practice", category: "Language Tools", isPro: true },
  { id: 74, name: "TOEFL Writing Analyzer", slug: "toefl-writing-analyzer", category: "Language Tools", isPro: true },
  { id: 75, name: "TOEFL Speaking Practice", slug: "toefl-speaking-practice", category: "Language Tools", isPro: true },
  { id: 76, name: "PTE Writing Analyzer", slug: "pte-writing-analyzer", category: "Language Tools", isPro: true },
  { id: 77, name: "PTE Speaking Practice", slug: "pte-speaking-practice", category: "Language Tools", isPro: true },
  { id: 78, name: "Business English Assessment", slug: "business-english-assessment", category: "Language Tools", isPro: true },
  { id: 79, name: "Academic English Assessment", slug: "academic-english-assessment", category: "Language Tools", isPro: true },
  { id: 80, name: "Job Interview Language Coach", slug: "job-interview-language-coach", category: "Language Tools", isPro: true },
  { id: 81, name: "Multilingual Subtitle Translator", slug: "multilingual-subtitle-translator", category: "Language Tools", isPro: true },
  { id: 82, name: "Multilingual Document Translator", slug: "multilingual-document-translator", category: "Language Tools", isPro: true },
  { id: 83, name: "Translation Quality Checker", slug: "translation-quality-checker", category: "Language Tools", isPro: true },
  { id: 84, name: "Translation Consistency Checker", slug: "translation-consistency-checker", category: "Language Tools", isPro: true },
  { id: 85, name: "Terminology Management Tool", slug: "terminology-management-tool", category: "Language Tools", isPro: true },
  { id: 86, name: "Glossary Generator", slug: "glossary-generator", category: "Language Tools", isPro: true },
  { id: 87, name: "Multilingual Glossary Manager", slug: "multilingual-glossary-manager", category: "Language Tools", isPro: true },
  { id: 88, name: "Translation Memory Tool", slug: "translation-memory-tool", category: "Language Tools", isPro: true },
  { id: 89, name: "Localization Checker", slug: "localization-checker", category: "Language Tools", isPro: true },
  { id: 90, name: "Website Localization Analyzer", slug: "website-localization-analyzer", category: "Language Tools", isPro: true },
  { id: 91, name: "Multilingual SEO Analyzer", slug: "multilingual-seo-analyzer", category: "Language Tools", isPro: true },
  { id: 92, name: "Multilingual Keyword Translator", slug: "multilingual-keyword-translator", category: "Language Tools", isPro: true },
  { id: 93, name: "Cross-Language Keyword Analyzer", slug: "cross-language-keyword-analyzer", category: "Language Tools", isPro: true },
  { id: 94, name: "Language Learning Progress Tracker", slug: "language-learning-progress-tracker", category: "Language Tools", isPro: true },
  { id: 95, name: "Vocabulary Retention Tracker", slug: "vocabulary-retention-tracker", category: "Language Tools", isPro: true },
  { id: 96, name: "Spaced Repetition Planner", slug: "spaced-repetition-planner", category: "Language Tools", isPro: true },
  { id: 97, name: "Language Curriculum Generator", slug: "language-curriculum-generator", category: "Language Tools", isPro: true },
  { id: 98, name: "Multilingual Content QA Tool", slug: "multilingual-content-qa-tool", category: "Language Tools", isPro: true },
  { id: 99, name: "Professional Translation Workspace", slug: "professional-translation-workspace", category: "Language Tools", isPro: true },
  { id: 100, name: "AI Language Learning Workspace", slug: "ai-language-learning-workspace", category: "Language Tools", isPro: true },
];