export interface LogisticsShippingTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const logisticsShippingToolsList: LogisticsShippingTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "Shipping Cost Calculator", slug: "shipping-cost-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 2, name: "Delivery Cost Calculator", slug: "delivery-cost-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 3, name: "Dimensional Weight Calculator", slug: "dimensional-weight-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 4, name: "Volumetric Weight Calculator", slug: "volumetric-weight-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 5, name: "Chargeable Weight Calculator", slug: "chargeable-weight-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 6, name: "Package Volume Calculator", slug: "package-volume-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 7, name: "Pallet Capacity Calculator", slug: "pallet-capacity-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 8, name: "Container Capacity Calculator", slug: "container-capacity-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 9, name: "CBM Calculator", slug: "cbm-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 10, name: "Freight Class Calculator", slug: "freight-class-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 11, name: "LTL Shipping Calculator", slug: "ltl-shipping-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 12, name: "Air Freight Calculator", slug: "air-freight-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 13, name: "Ocean Freight Calculator", slug: "ocean-freight-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 14, name: "Delivery Time Calculator", slug: "delivery-time-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 15, name: "Shipping Zone Calculator", slug: "shipping-zone-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 16, name: "Fuel Surcharge Calculator", slug: "fuel-surcharge-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 17, name: "Customs Duty Calculator", slug: "customs-duty-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 18, name: "Landed Cost Calculator", slug: "landed-cost-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 19, name: "Multi-Carrier Rate Comparison", slug: "multi-carrier-rate-comparison", category: "Logistics & Shipping Tools", isPro: true },
  { id: 20, name: "Advanced Shipping Cost Engine", slug: "advanced-shipping-cost-engine", category: "Logistics & Shipping Tools", isPro: true },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Freight Cost Calculator", slug: "freight-cost-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 22, name: "Parcel Cost Calculator", slug: "parcel-cost-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 23, name: "Shipping Rate Calculator", slug: "shipping-rate-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 24, name: "Billable Weight Calculator", slug: "billable-weight-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 25, name: "Package Weight Calculator", slug: "package-weight-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 26, name: "Box Volume Calculator", slug: "box-volume-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 27, name: "Shipping Box Size Calculator", slug: "shipping-box-size-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 28, name: "Pallet Load Calculator", slug: "pallet-load-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 29, name: "Container Load Calculator", slug: "container-load-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 30, name: "Container Volume Calculator", slug: "container-volume-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 31, name: "CFT Calculator", slug: "cft-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 32, name: "NMFC Freight Class Helper", slug: "nmfc-freight-class-helper", category: "Logistics & Shipping Tools", isPro: false },
  { id: 33, name: "FTL Shipping Calculator", slug: "ftl-shipping-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 34, name: "Sea Freight Cost Calculator", slug: "sea-freight-cost-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 35, name: "Courier Cost Calculator", slug: "courier-cost-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 36, name: "Last Mile Cost Calculator", slug: "last-mile-cost-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 37, name: "Shipping Time Calculator", slug: "shipping-time-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 38, name: "Transit Time Calculator", slug: "transit-time-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 39, name: "ETA Calculator", slug: "eta-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 40, name: "Shipping Deadline Calculator", slug: "shipping-deadline-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 41, name: "Dispatch Date Calculator", slug: "dispatch-date-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 42, name: "Delivery Date Calculator", slug: "delivery-date-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 43, name: "Business Day Delivery Calculator", slug: "business-day-delivery-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 44, name: "Delivery Zone Calculator", slug: "delivery-zone-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 45, name: "Distance Shipping Calculator", slug: "distance-shipping-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 46, name: "Freight Fuel Cost Calculator", slug: "freight-fuel-cost-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 47, name: "Import Duty Calculator", slug: "import-duty-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 48, name: "Shipping Tax Calculator", slug: "shipping-tax-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 49, name: "Total Delivered Cost Calculator", slug: "total-delivered-cost-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 50, name: "Shipping Margin Calculator", slug: "shipping-margin-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 51, name: "Shipping Profit Calculator", slug: "shipping-profit-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 52, name: "Return Shipping Cost Calculator", slug: "return-shipping-cost-calculator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 53, name: "Package Tracking Organizer", slug: "package-tracking-organizer", category: "Logistics & Shipping Tools", isPro: false },
  { id: 54, name: "Tracking Number Validator", slug: "tracking-number-validator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 55, name: "Shipment Status Tracker", slug: "shipment-status-tracker", category: "Logistics & Shipping Tools", isPro: false },
  { id: 56, name: "Delivery Route Planner", slug: "delivery-route-planner", category: "Logistics & Shipping Tools", isPro: false },
  { id: 57, name: "Multi-Stop Delivery Planner", slug: "multi-stop-delivery-planner", category: "Logistics & Shipping Tools", isPro: false },
  { id: 58, name: "Shipment Label Generator", slug: "shipment-label-generator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 59, name: "Commercial Invoice Generator", slug: "commercial-invoice-generator", category: "Logistics & Shipping Tools", isPro: false },
  { id: 60, name: "Export Shipping Checklist", slug: "export-shipping-checklist", category: "Logistics & Shipping Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Carrier Rate Analyzer", slug: "carrier-rate-analyzer", category: "Logistics & Shipping Tools", isPro: true },
  { id: 62, name: "Shipping Rate Management Workspace", slug: "shipping-rate-management-workspace", category: "Logistics & Shipping Tools", isPro: true },
  { id: 63, name: "Freight Quote Comparison Workspace", slug: "freight-quote-comparison-workspace", category: "Logistics & Shipping Tools", isPro: true },
  { id: 64, name: "Logistics Cost Dashboard", slug: "logistics-cost-dashboard", category: "Logistics & Shipping Tools", isPro: true },
  { id: 65, name: "Shipping Profitability Dashboard", slug: "shipping-profitability-dashboard", category: "Logistics & Shipping Tools", isPro: true },
  { id: 66, name: "Landed Cost Intelligence", slug: "landed-cost-intelligence", category: "Logistics & Shipping Tools", isPro: true },
  { id: 67, name: "International Shipping Cost Engine", slug: "international-shipping-cost-engine", category: "Logistics & Shipping Tools", isPro: true },
  { id: 68, name: "Cross-Border Shipping Workspace", slug: "cross-border-shipping-workspace", category: "Logistics & Shipping Tools", isPro: true },
  { id: 69, name: "Customs Documentation Workspace", slug: "customs-documentation-workspace", category: "Logistics & Shipping Tools", isPro: true },
  { id: 70, name: "Import Cost Analysis", slug: "import-cost-analysis", category: "Logistics & Shipping Tools", isPro: true },
  { id: 71, name: "Export Cost Analysis", slug: "export-cost-analysis", category: "Logistics & Shipping Tools", isPro: true },
  { id: 72, name: "Freight Class Management Workspace", slug: "freight-class-management-workspace", category: "Logistics & Shipping Tools", isPro: true },
  { id: 73, name: "Container Optimization Engine", slug: "container-optimization-engine", category: "Logistics & Shipping Tools", isPro: true },
  { id: 74, name: "Pallet Optimization Engine", slug: "pallet-optimization-engine", category: "Logistics & Shipping Tools", isPro: true },
  { id: 75, name: "Load Planning Workspace", slug: "load-planning-workspace", category: "Logistics & Shipping Tools", isPro: true },
  { id: 76, name: "Truck Load Optimization", slug: "truck-load-optimization", category: "Logistics & Shipping Tools", isPro: true },
  { id: 77, name: "Warehouse Shipping Planner", slug: "warehouse-shipping-planner", category: "Logistics & Shipping Tools", isPro: true },
  { id: 78, name: "Dispatch Management Workspace", slug: "dispatch-management-workspace", category: "Logistics & Shipping Tools", isPro: true },
  { id: 79, name: "Delivery Operations Dashboard", slug: "delivery-operations-dashboard", category: "Logistics & Shipping Tools", isPro: true },
  { id: 80, name: "Last-Mile Optimization Engine", slug: "last-mile-optimization-engine", category: "Logistics & Shipping Tools", isPro: true },
  { id: 81, name: "Delivery Route Optimization", slug: "delivery-route-optimization", category: "Logistics & Shipping Tools", isPro: true },
  { id: 82, name: "Multi-Vehicle Delivery Planner", slug: "multi-vehicle-delivery-planner", category: "Logistics & Shipping Tools", isPro: true },
  { id: 83, name: "Fleet Delivery Workspace", slug: "fleet-delivery-workspace", category: "Logistics & Shipping Tools", isPro: true },
  { id: 84, name: "Shipment Tracking Dashboard", slug: "shipment-tracking-dashboard", category: "Logistics & Shipping Tools", isPro: true },
  { id: 85, name: "Multi-Carrier Tracking Workspace", slug: "multi-carrier-tracking-workspace", category: "Logistics & Shipping Tools", isPro: true },
  { id: 86, name: "Shipment Exception Dashboard", slug: "shipment-exception-dashboard", category: "Logistics & Shipping Tools", isPro: true },
  { id: 87, name: "Delivery Performance Analytics", slug: "delivery-performance-analytics", category: "Logistics & Shipping Tools", isPro: true },
  { id: 88, name: "Carrier Performance Dashboard", slug: "carrier-performance-dashboard", category: "Logistics & Shipping Tools", isPro: true },
  { id: 89, name: "Shipping SLA Dashboard", slug: "shipping-sla-dashboard", category: "Logistics & Shipping Tools", isPro: true },
  { id: 90, name: "Logistics KPI Dashboard", slug: "logistics-kpi-dashboard", category: "Logistics & Shipping Tools", isPro: true },
  { id: 91, name: "Shipping Data Import Workspace", slug: "shipping-data-import-workspace", category: "Logistics & Shipping Tools", isPro: true },
  { id: 92, name: "Logistics CSV Analyzer", slug: "logistics-csv-analyzer", category: "Logistics & Shipping Tools", isPro: true },
  { id: 93, name: "Shipping API Workspace", slug: "shipping-api-workspace", category: "Logistics & Shipping Tools", isPro: true },
  { id: 94, name: "Carrier API Integration Workspace", slug: "carrier-api-integration-workspace", category: "Logistics & Shipping Tools", isPro: true },
  { id: 95, name: "Logistics Report Generator", slug: "logistics-report-generator", category: "Logistics & Shipping Tools", isPro: true },
  { id: 96, name: "Logistics Business Intelligence", slug: "logistics-business-intelligence", category: "Logistics & Shipping Tools", isPro: true },
  { id: 97, name: "Supply Chain Shipping Intelligence", slug: "supply-chain-shipping-intelligence", category: "Logistics & Shipping Tools", isPro: true },
  { id: 98, name: "Packing Slip Generator", slug: "packing-slip-generator", category: "Logistics & Shipping Tools", isPro: true },
  { id: 99, name: "Shipping Checklist Generator", slug: "shipping-checklist-generator", category: "Logistics & Shipping Tools", isPro: true },
  { id: 100, name: "Professional Logistics Command Center", slug: "professional-logistics-command-center", category: "Logistics & Shipping Tools", isPro: true }
];