export interface MachineLearningTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const machineLearningToolsList: MachineLearningTool[] = [
  // --- 🔥 PRIORITY 20 FREE TOOLS (IDs 1-20 | isPro: false) ---
  { id: 1, name: "Dataset Quality Checker", slug: "dataset-quality-checker", category: "Machine Learning Tools", isPro: false },
  { id: 2, name: "Dataset Schema Analyzer", slug: "dataset-schema-analyzer", category: "Machine Learning Tools", isPro: false },
  { id: 3, name: "Dataset Missing Value Analyzer", slug: "dataset-missing-value-analyzer", category: "Machine Learning Tools", isPro: false },
  { id: 4, name: "Dataset Outlier Detector", slug: "dataset-outlier-detector", category: "Machine Learning Tools", isPro: false },
  { id: 5, name: "Dataset Class Balance Analyzer", slug: "dataset-class-balance-analyzer", category: "Machine Learning Tools", isPro: false },
  { id: 6, name: "Feature Type Detector", slug: "feature-type-detector", category: "Machine Learning Tools", isPro: false },
  { id: 7, name: "Feature Correlation Analyzer", slug: "feature-correlation-analyzer", category: "Machine Learning Tools", isPro: false },
  { id: 8, name: "Feature Importance Calculator", slug: "feature-importance-calculator", category: "Machine Learning Tools", isPro: false },
  { id: 9, name: "Train-Test Split Calculator", slug: "train-test-split-calculator", category: "Machine Learning Tools", isPro: false },
  { id: 10, name: "Cross-Validation Fold Calculator", slug: "cross-validation-fold-calculator", category: "Machine Learning Tools", isPro: false },
  { id: 11, name: "Confusion Matrix Generator", slug: "confusion-matrix-generator", category: "Machine Learning Tools", isPro: false },
  { id: 12, name: "Precision-Recall Calculator", slug: "precision-recall-calculator", category: "Machine Learning Tools", isPro: false },
  { id: 13, name: "F1 Score Calculator", slug: "f1-score-calculator", category: "Machine Learning Tools", isPro: false },
  { id: 14, name: "RMSE Calculator", slug: "rmse-calculator", category: "Machine Learning Tools", isPro: false },
  { id: 15, name: "Parameter Count Calculator", slug: "parameter-count-calculator", category: "Machine Learning Tools", isPro: false },
  { id: 16, name: "GPU Memory Estimator", slug: "gpu-memory-estimator", category: "Machine Learning Tools", isPro: false },
  { id: 17, name: "GPU Training Cost Calculator", slug: "gpu-training-cost-calculator", category: "Machine Learning Tools", isPro: false },
  { id: 18, name: "Model Evaluation Report", slug: "model-evaluation-report", category: "Machine Learning Tools", isPro: false },
  { id: 19, name: "Model Benchmarking Workspace", slug: "model-benchmarking-workspace-free", category: "Machine Learning Tools", isPro: false },
  { id: 20, name: "ML Experiment Workspace", slug: "ml-experiment-workspace-free", category: "Machine Learning Tools", isPro: false },

  // --- REMAINING 40 CORE FREE TOOLS (IDs 21-60 | isPro: false) ---
  { id: 21, name: "Dataset Column Profiler", slug: "dataset-column-profiler", category: "Machine Learning Tools", isPro: false },
  { id: 22, name: "Dataset Duplicate Row Analyzer", slug: "dataset-duplicate-row-analyzer", category: "Machine Learning Tools", isPro: false },
  { id: 23, name: "Dataset Distribution Analyzer", slug: "dataset-distribution-analyzer", category: "Machine Learning Tools", isPro: false },
  { id: 24, name: "Dataset Cardinality Analyzer", slug: "dataset-cardinality-analyzer", category: "Machine Learning Tools", isPro: false },
  { id: 25, name: "Dataset Feature Summary", slug: "dataset-feature-summary", category: "Machine Learning Tools", isPro: false },
  { id: 26, name: "Feature Distribution Checker", slug: "feature-distribution-checker", category: "Machine Learning Tools", isPro: false },
  { id: 27, name: "Feature Missingness Analyzer", slug: "feature-missingness-analyzer", category: "Machine Learning Tools", isPro: false },
  { id: 28, name: "Feature Variance Analyzer", slug: "feature-variance-analyzer", category: "Machine Learning Tools", isPro: false },
  { id: 29, name: "Feature Skewness Analyzer", slug: "feature-skewness-analyzer", category: "Machine Learning Tools", isPro: false },
  { id: 30, name: "Feature Outlier Analyzer", slug: "feature-outlier-analyzer", category: "Machine Learning Tools", isPro: false },
  { id: 31, name: "Categorical Feature Analyzer", slug: "categorical-feature-analyzer", category: "Machine Learning Tools", isPro: false },
  { id: 32, name: "Numerical Feature Analyzer", slug: "numerical-feature-analyzer", category: "Machine Learning Tools", isPro: false },
  { id: 33, name: "Train-Validation-Test Split Calculator", slug: "train-validation-test-split-calculator", category: "Machine Learning Tools", isPro: false },
  { id: 34, name: "Stratified Split Calculator", slug: "stratified-split-calculator", category: "Machine Learning Tools", isPro: false },
  { id: 35, name: "Sampling Size Calculator", slug: "sampling-size-calculator-ml", category: "Machine Learning Tools", isPro: false },
  { id: 36, name: "ML Class Weight Calculator", slug: "ml-class-weight-calculator", category: "Machine Learning Tools", isPro: false },
  { id: 37, name: "Imbalanced Dataset Calculator", slug: "imbalanced-dataset-calculator", category: "Machine Learning Tools", isPro: false },
  { id: 38, name: "Classification Metrics Calculator", slug: "classification-metrics-calculator", category: "Machine Learning Tools", isPro: false },
  { id: 39, name: "Regression Metrics Calculator", slug: "regression-metrics-calculator", category: "Machine Learning Tools", isPro: false },
  { id: 40, name: "ROC Curve Data Generator", slug: "roc-curve-data-generator", category: "Machine Learning Tools", isPro: false },
  { id: 41, name: "Accuracy Calculator", slug: "accuracy-calculator-ml", category: "Machine Learning Tools", isPro: false },
  { id: 42, name: "Log Loss Calculator", slug: "log-loss-calculator", category: "Machine Learning Tools", isPro: false },
  { id: 43, name: "MAE Calculator", slug: "mae-calculator", category: "Machine Learning Tools", isPro: false },
  { id: 44, name: "MSE Calculator", slug: "mse-calculator", category: "Machine Learning Tools", isPro: false },
  { id: 45, name: "R-Squared Calculator", slug: "r-squared-calculator", category: "Machine Learning Tools", isPro: false },
  { id: 46, name: "Model Error Analyzer", slug: "model-error-analyzer", category: "Machine Learning Tools", isPro: false },
  { id: 47, name: "Hyperparameter Range Planner", slug: "hyperparameter-range-planner", category: "Machine Learning Tools", isPro: false },
  { id: 48, name: "Learning Rate Calculator", slug: "learning-rate-calculator", category: "Machine Learning Tools", isPro: false },
  { id: 49, name: "Batch Size Calculator", slug: "batch-size-calculator", category: "Machine Learning Tools", isPro: false },
  { id: 50, name: "Epoch Planning Calculator", slug: "epoch-planning-calculator", category: "Machine Learning Tools", isPro: false },
  { id: 51, name: "Training Time Estimator", slug: "training-time-estimator", category: "Machine Learning Tools", isPro: false },
  { id: 52, name: "Model Size Calculator", slug: "model-size-calculator", category: "Machine Learning Tools", isPro: false },
  { id: 53, name: "Inference Cost Calculator", slug: "inference-cost-calculator", category: "Machine Learning Tools", isPro: false },
  { id: 54, name: "ML Experiment Tracker", slug: "ml-experiment-tracker", category: "Machine Learning Tools", isPro: false },
  { id: 55, name: "Model Comparison Table", slug: "model-comparison-table", category: "Machine Learning Tools", isPro: false },
  { id: 56, name: "Dataset Documentation Generator", slug: "dataset-documentation-generator", category: "Machine Learning Tools", isPro: false },
  { id: 57, name: "Model Card Generator", slug: "model-card-generator", category: "Machine Learning Tools", isPro: false },
  { id: 58, name: "ML Project Checklist", slug: "ml-project-checklist", category: "Machine Learning Tools", isPro: false },
  { id: 59, name: "ML Deployment Checklist", slug: "ml-deployment-checklist", category: "Machine Learning Tools", isPro: false },
  { id: 60, name: "Model Monitoring Checklist", slug: "model-monitoring-checklist", category: "Machine Learning Tools", isPro: false },

  // --- ⚡ 40 PRO / SAAS TOOLS (IDs 61-100 | isPro: true) ---
  { id: 61, name: "Data Drift Checklist", slug: "data-drift-checklist", category: "Machine Learning Tools", isPro: true },
  { id: 62, name: "ML Experiment Report Generator", slug: "ml-experiment-report-generator", category: "Machine Learning Tools", isPro: true },
  { id: 63, name: "Dataset Profiling Workspace", slug: "dataset-profiling-workspace", category: "Machine Learning Tools", isPro: true },
  { id: 64, name: "Feature Engineering Workspace", slug: "feature-engineering-workspace", category: "Machine Learning Tools", isPro: true },
  { id: 65, name: "Feature Selection Workspace", slug: "feature-selection-workspace", category: "Machine Learning Tools", isPro: true },
  { id: 66, name: "Dataset Quality Intelligence", slug: "dataset-quality-intelligence", category: "Machine Learning Tools", isPro: true },
  { id: 67, name: "Data Drift Monitoring Workspace", slug: "data-drift-monitoring-workspace", category: "Machine Learning Tools", isPro: true },
  { id: 68, name: "Model Drift Monitoring Workspace", slug: "model-drift-monitoring-workspace", category: "Machine Learning Tools", isPro: true },
  { id: 69, name: "Model Evaluation Dashboard", slug: "model-evaluation-dashboard", category: "Machine Learning Tools", isPro: true },
  { id: 70, name: "Model Comparison Workspace", slug: "model-comparison-workspace", category: "Machine Learning Tools", isPro: true },
  { id: 71, name: "Hyperparameter Optimization Workspace", slug: "hyperparameter-optimization-workspace", category: "Machine Learning Tools", isPro: true },
  { id: 72, name: "Experiment Management Dashboard", slug: "experiment-management-dashboard", category: "Machine Learning Tools", isPro: true },
  { id: 73, name: "Training Cost Optimization", slug: "training-cost-optimization", category: "Machine Learning Tools", isPro: true },
  { id: 74, name: "GPU Resource Planning Workspace", slug: "gpu-resource-planning-workspace", category: "Machine Learning Tools", isPro: true },
  { id: 75, name: "ML Infrastructure Cost Dashboard", slug: "ml-infrastructure-cost-dashboard", category: "Machine Learning Tools", isPro: true },
  { id: 76, name: "Model Registry Workspace", slug: "model-registry-workspace", category: "Machine Learning Tools", isPro: true },
  { id: 77, name: "Model Version Management", slug: "model-version-management", category: "Machine Learning Tools", isPro: true },
  { id: 78, name: "Model Deployment Workspace", slug: "model-deployment-workspace", category: "Machine Learning Tools", isPro: true },
  { id: 79, name: "Model Rollback Manager", slug: "model-rollback-manager", category: "Machine Learning Tools", isPro: true },
  { id: 80, name: "Model Performance Monitoring", slug: "model-performance-monitoring", category: "Machine Learning Tools", isPro: true },
  { id: 81, name: "Model Explainability Workspace", slug: "model-explainability-workspace", category: "Machine Learning Tools", isPro: true },
  { id: 82, name: "Feature Importance Dashboard", slug: "feature-importance-dashboard-pro", category: "Machine Learning Tools", isPro: true },
  { id: 83, name: "Prediction Error Analysis", slug: "prediction-error-analysis", category: "Machine Learning Tools", isPro: true },
  { id: 84, name: "Bias Evaluation Workspace", slug: "bias-evaluation-workspace", category: "Machine Learning Tools", isPro: true },
  { id: 85, name: "ML Fairness Monitoring", slug: "ml-fairness-monitoring", category: "Machine Learning Tools", isPro: true },
  { id: 86, name: "ML Data Lineage Workspace", slug: "ml-data-lineage-workspace", category: "Machine Learning Tools", isPro: true },
  { id: 87, name: "Dataset Version Management", slug: "dataset-version-management", category: "Machine Learning Tools", isPro: true },
  { id: 88, name: "ML Pipeline Builder", slug: "ml-pipeline-builder", category: "Machine Learning Tools", isPro: true },
  { id: 89, name: "ML Pipeline Monitoring", slug: "ml-pipeline-monitoring", category: "Machine Learning Tools", isPro: true },
  { id: 90, name: "ML Deployment Monitoring", slug: "ml-deployment-monitoring", category: "Machine Learning Tools", isPro: true },
  { id: 91, name: "Inference Analytics Dashboard", slug: "inference-analytics-dashboard", category: "Machine Learning Tools", isPro: true },
  { id: 92, name: "Model API Management", slug: "model-api-management", category: "Machine Learning Tools", isPro: true },
  { id: 93, name: "ML Batch Prediction Workspace", slug: "ml-batch-prediction-workspace", category: "Machine Learning Tools", isPro: true },
  { id: 94, name: "ML Data Import Workspace", slug: "ml-data-import-workspace", category: "Machine Learning Tools", isPro: true },
  { id: 95, name: "ML Experiment Exporter", slug: "ml-experiment-exporter", category: "Machine Learning Tools", isPro: true },
  { id: 96, name: "ML Reporting Workspace", slug: "ml-reporting-workspace", category: "Machine Learning Tools", isPro: true },
  { id: 97, name: "ML Automation Workspace", slug: "ml-automation-workspace", category: "Machine Learning Tools", isPro: true },
  { id: 98, name: "ML Operations Dashboard", slug: "ml-operations-dashboard", category: "Machine Learning Tools", isPro: true },
  { id: 99, name: "ML Intelligence Platform", slug: "ml-intelligence-platform", category: "Machine Learning Tools", isPro: true },
  { id: 100, name: "Enterprise ML Command Center", slug: "enterprise-ml-command-center", category: "Machine Learning Tools", isPro: true }
];