export interface ManufacturingTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const manufacturingToolsList: ManufacturingTool[] = [
  // --- 🔥 PRIORITY 20 FREE TOOLS (IDs 1-20 | isPro: false) ---
  { id: 1, name: "Production Capacity Calculator", slug: "production-capacity-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 2, name: "Machine Capacity Calculator", slug: "machine-capacity-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 3, name: "Production Rate Calculator", slug: "production-rate-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 4, name: "Cycle Time Calculator", slug: "cycle-time-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 5, name: "Takt Time Calculator", slug: "takt-time-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 6, name: "Throughput Calculator", slug: "throughput-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 7, name: "OEE Calculator", slug: "oee-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 8, name: "Machine Utilization Calculator", slug: "machine-utilization-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 9, name: "Production Yield Calculator", slug: "production-yield-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 10, name: "Scrap Rate Calculator", slug: "scrap-rate-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 11, name: "First Pass Yield Calculator", slug: "first-pass-yield-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 12, name: "Safety Stock Calculator", slug: "safety-stock-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 13, name: "Reorder Point Calculator", slug: "reorder-point-calculator-manufacturing", category: "Manufacturing Tools", isPro: false },
  { id: 14, name: "Manufacturing Cost Calculator", slug: "manufacturing-cost-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 15, name: "Unit Manufacturing Cost Calculator", slug: "unit-manufacturing-cost-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 16, name: "BOM Cost Calculator", slug: "bom-cost-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 17, name: "Production Schedule Calculator", slug: "production-schedule-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 18, name: "Cp/Cpk Calculator", slug: "cp-cpk-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 19, name: "Labor Utilization Calculator", slug: "labor-utilization-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 20, name: "Break-Even Production Calculator", slug: "break-even-production-calculator", category: "Manufacturing Tools", isPro: false },

  // --- REMAINING 40 CORE FREE TOOLS (IDs 21-60 | isPro: false) ---
  { id: 21, name: "Lead Time Calculator", slug: "lead-time-calculator-manufacturing", category: "Manufacturing Tools", isPro: false },
  { id: 22, name: "Availability Calculator", slug: "availability-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 23, name: "Performance Efficiency Calculator", slug: "performance-efficiency-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 24, name: "Quality Rate Calculator", slug: "quality-rate-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 25, name: "Downtime Calculator", slug: "downtime-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 26, name: "Planned Downtime Calculator", slug: "planned-downtime-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 27, name: "Unplanned Downtime Calculator", slug: "unplanned-downtime-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 28, name: "Defect Rate Calculator", slug: "defect-rate-calculator-manufacturing", category: "Manufacturing Tools", isPro: false },
  { id: 29, name: "Rework Rate Calculator", slug: "rework-rate-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 30, name: "Batch Size Calculator", slug: "batch-size-calculator-manufacturing", category: "Manufacturing Tools", isPro: false },
  { id: 31, name: "Economic Batch Quantity Calculator", slug: "economic-batch-quantity-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 32, name: "Manufacturing Inventory Calculator", slug: "manufacturing-inventory-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 33, name: "Inventory Carrying Cost Calculator", slug: "inventory-carrying-cost-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 34, name: "Raw Material Cost Calculator", slug: "raw-material-cost-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 35, name: "Labor Cost Calculator", slug: "labor-cost-calculator-manufacturing", category: "Manufacturing Tools", isPro: false },
  { id: 36, name: "Machine Hour Cost Calculator", slug: "machine-hour-cost-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 37, name: "Overhead Allocation Calculator", slug: "overhead-allocation-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 38, name: "Cost Per Unit Calculator", slug: "cost-per-unit-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 39, name: "Production Profit Calculator", slug: "production-profit-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 40, name: "Production Margin Calculator", slug: "production-margin-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 41, name: "Material Usage Calculator", slug: "material-usage-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 42, name: "Material Yield Calculator", slug: "material-yield-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 43, name: "Material Waste Calculator", slug: "material-waste-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 44, name: "BOM Quantity Calculator", slug: "bom-quantity-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 45, name: "Shift Capacity Calculator", slug: "shift-capacity-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 46, name: "Workforce Requirement Calculator", slug: "workforce-requirement-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 47, name: "Machine Requirement Calculator", slug: "machine-requirement-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 48, name: "Maintenance Interval Calculator", slug: "maintenance-interval-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 49, name: "Preventive Maintenance Planner", slug: "preventive-maintenance-planner", category: "Manufacturing Tools", isPro: false },
  { id: 50, name: "Mean Time Between Failures Calculator", slug: "mean-time-between-failures-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 51, name: "Mean Time To Repair Calculator", slug: "mean-time-to-repair-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 52, name: "Quality Inspection Sample Size Calculator", slug: "quality-inspection-sample-size-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 53, name: "Acceptance Sampling Calculator", slug: "acceptance-sampling-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 54, name: "Process Capability Calculator", slug: "process-capability-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 55, name: "Cp Calculator", slug: "cp-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 56, name: "Cpk Calculator", slug: "cpk-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 57, name: "Six Sigma Sigma Level Calculator", slug: "six-sigma-sigma-level-calculator", category: "Manufacturing Tools", isPro: false },
  { id: 58, name: "Pareto Analysis Generator", slug: "pareto-analysis-generator", category: "Manufacturing Tools", isPro: false },
  { id: 59, name: "Fishbone Diagram Generator", slug: "fishbone-diagram-generator", category: "Manufacturing Tools", isPro: false },
  { id: 60, name: "Manufacturing KPI Generator", slug: "manufacturing-kpi-generator", category: "Manufacturing Tools", isPro: false },

  // --- ⚡ 40 PRO / SAAS TOOLS (IDs 61-100 | isPro: true) ---
  { id: 61, name: "Manufacturing Operations Dashboard", slug: "manufacturing-operations-dashboard", category: "Manufacturing Tools", isPro: true },
  { id: 62, name: "Production Planning Workspace", slug: "production-planning-workspace", category: "Manufacturing Tools", isPro: true },
  { id: 63, name: "Production Scheduling Workspace", slug: "production-scheduling-workspace", category: "Manufacturing Tools", isPro: true },
  { id: 64, name: "Capacity Planning Engine", slug: "capacity-planning-engine", category: "Manufacturing Tools", isPro: true },
  { id: 65, name: "Machine Capacity Dashboard", slug: "machine-capacity-dashboard", category: "Manufacturing Tools", isPro: true },
  { id: 66, name: "Workforce Planning Workspace", slug: "workforce-planning-workspace-manufacturing", category: "Manufacturing Tools", isPro: true },
  { id: 67, name: "Manufacturing Cost Dashboard", slug: "manufacturing-cost-dashboard", category: "Manufacturing Tools", isPro: true },
  { id: 68, name: "Manufacturing Profitability Workspace", slug: "manufacturing-profitability-workspace", category: "Manufacturing Tools", isPro: true },
  { id: 69, name: "OEE Intelligence Dashboard", slug: "oee-intelligence-dashboard", category: "Manufacturing Tools", isPro: true },
  { id: 70, name: "Downtime Analytics Workspace", slug: "downtime-analytics-workspace", category: "Manufacturing Tools", isPro: true },
  { id: 71, name: "Production Yield Dashboard", slug: "production-yield-dashboard", category: "Manufacturing Tools", isPro: true },
  { id: 72, name: "Quality Management Workspace", slug: "quality-management-workspace", category: "Manufacturing Tools", isPro: true },
  { id: 73, name: "Defect Analytics Workspace", slug: "defect-analytics-workspace", category: "Manufacturing Tools", isPro: true },
  { id: 74, name: "Scrap Reduction Workspace", slug: "scrap-reduction-workspace", category: "Manufacturing Tools", isPro: true },
  { id: 75, name: "Process Capability Dashboard", slug: "process-capability-dashboard", category: "Manufacturing Tools", isPro: true },
  { id: 76, name: "Six Sigma Analysis Workspace", slug: "six-sigma-analysis-workspace", category: "Manufacturing Tools", isPro: true },
  { id: 77, name: "SPC Analytics Workspace", slug: "spc-analytics-workspace", category: "Manufacturing Tools", isPro: true },
  { id: 78, name: "Maintenance Management Workspace", slug: "maintenance-management-workspace", category: "Manufacturing Tools", isPro: true },
  { id: 79, name: "Preventive Maintenance Dashboard", slug: "preventive-maintenance-dashboard", category: "Manufacturing Tools", isPro: true },
  { id: 80, name: "Predictive Maintenance Workspace", slug: "predictive-maintenance-workspace", category: "Manufacturing Tools", isPro: true },
  { id: 81, name: "Machine Health Dashboard", slug: "machine-health-dashboard", category: "Manufacturing Tools", isPro: true },
  { id: 82, name: "Asset Performance Workspace", slug: "asset-performance-workspace", category: "Manufacturing Tools", isPro: true },
  { id: 83, name: "Manufacturing Inventory Workspace", slug: "manufacturing-inventory-workspace", category: "Manufacturing Tools", isPro: true },
  { id: 84, name: "Raw Material Planning Workspace", slug: "raw-material-planning-workspace", category: "Manufacturing Tools", isPro: true },
  { id: 85, name: "BOM Management Workspace", slug: "bom-management-workspace", category: "Manufacturing Tools", isPro: true },
  { id: 86, name: "Material Requirement Planning Workspace", slug: "material-requirement-planning-workspace", category: "Manufacturing Tools", isPro: true },
  { id: 87, name: "Procurement Planning Workspace", slug: "procurement-planning-workspace", category: "Manufacturing Tools", isPro: true },
  { id: 88, name: "Supplier Performance Dashboard", slug: "supplier-performance-dashboard", category: "Manufacturing Tools", isPro: true },
  { id: 89, name: "Production Cost Optimization", slug: "production-cost-optimization", category: "Manufacturing Tools", isPro: true },
  { id: 90, name: "Factory Performance Dashboard", slug: "factory-performance-dashboard", category: "Manufacturing Tools", isPro: true },
  { id: 91, name: "Shift Management Workspace", slug: "shift-management-workspace-manufacturing", category: "Manufacturing Tools", isPro: true },
  { id: 92, name: "Manufacturing Workforce Dashboard", slug: "manufacturing-workforce-dashboard", category: "Manufacturing Tools", isPro: true },
  { id: 93, name: "Production Quality Reporting", slug: "production-quality-reporting", category: "Manufacturing Tools", isPro: true },
  { id: 94, name: "Manufacturing Data Import Workspace", slug: "manufacturing-data-import-workspace", category: "Manufacturing Tools", isPro: true },
  { id: 95, name: "Manufacturing Data Export Workspace", slug: "manufacturing-data-export-workspace", category: "Manufacturing Tools", isPro: true },
  { id: 96, name: "Manufacturing API Workspace", slug: "manufacturing-api-workspace", category: "Manufacturing Tools", isPro: true },
  { id: 97, name: "Factory Automation Workspace", slug: "factory-automation-workspace", category: "Manufacturing Tools", isPro: true },
  { id: 98, name: "Manufacturing Analytics Platform", slug: "manufacturing-analytics-platform", category: "Manufacturing Tools", isPro: true },
  { id: 99, name: "Smart Factory Intelligence Platform", slug: "smart-factory-intelligence-platform", category: "Manufacturing Tools", isPro: true },
  { id: 100, name: "Enterprise Manufacturing Command Center", slug: "enterprise-manufacturing-command-center", category: "Manufacturing Tools", isPro: true }
];