export interface MapsLocationTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const mapsLocationToolsList: MapsLocationTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "Distance Between Locations", slug: "distance-between-locations", category: "Maps & Location Tools", isPro: false },
  { id: 2, name: "Driving Distance Calculator", slug: "driving-distance-calculator", category: "Maps & Location Tools", isPro: false },
  { id: 3, name: "Walking Distance Calculator", slug: "walking-distance-calculator", category: "Maps & Location Tools", isPro: false },
  { id: 4, name: "Route Duration Calculator", slug: "route-duration-calculator", category: "Maps & Location Tools", isPro: false },
  { id: 5, name: "ETA Calculator", slug: "eta-calculator", category: "Maps & Location Tools", isPro: false },
  { id: 6, name: "Fuel Cost Calculator", slug: "fuel-cost-calculator", category: "Maps & Location Tools", isPro: false },
  { id: 7, name: "Multi-Stop Route Planner", slug: "multi-stop-route-planner", category: "Maps & Location Tools", isPro: false },
  { id: 8, name: "Route Optimization Calculator", slug: "route-optimization-calculator", category: "Maps & Location Tools", isPro: false },
  { id: 9, name: "Delivery Route Planner", slug: "delivery-route-planner", category: "Maps & Location Tools", isPro: false },
  { id: 10, name: "Distance Matrix Calculator", slug: "distance-matrix-calculator", category: "Maps & Location Tools", isPro: false },
  { id: 11, name: "Address to Coordinates Tool", slug: "address-to-coordinates-tool", category: "Maps & Location Tools", isPro: false },
  { id: 12, name: "Coordinates to Address Tool", slug: "coordinates-to-address-tool", category: "Maps & Location Tools", isPro: false },
  { id: 13, name: "Nearby Places Finder", slug: "nearby-places-finder", category: "Maps & Location Tools", isPro: false },
  { id: 14, name: "Radius Search Tool", slug: "radius-search-tool", category: "Maps & Location Tools", isPro: false },
  { id: 15, name: "Geofence Generator", slug: "geofence-generator", category: "Maps & Location Tools", isPro: false },
  { id: 16, name: "Delivery Area Calculator", slug: "delivery-area-calculator", category: "Maps & Location Tools", isPro: false },
  { id: 17, name: "Nearest Location Finder", slug: "nearest-location-finder", category: "Maps & Location Tools", isPro: false },
  { id: 18, name: "Toll Cost Calculator", slug: "toll-cost-calculator", category: "Maps & Location Tools", isPro: false },
  { id: 19, name: "Commute Cost Calculator", slug: "commute-cost-calculator", category: "Maps & Location Tools", isPro: false },
  { id: 20, name: "GeoJSON Viewer", slug: "geojson-viewer", category: "Maps & Location Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Cycling Distance Calculator", slug: "cycling-distance-calculator", category: "Maps & Location Tools", isPro: false },
  { id: 22, name: "Route Distance Calculator", slug: "route-distance-calculator", category: "Maps & Location Tools", isPro: false },
  { id: 23, name: "Travel Time Calculator", slug: "travel-time-calculator", category: "Maps & Location Tools", isPro: false },
  { id: 24, name: "Fuel Cost by Distance Calculator", slug: "fuel-cost-by-distance-calculator", category: "Maps & Location Tools", isPro: false },
  { id: 25, name: "Route Fuel Calculator", slug: "route-fuel-calculator", category: "Maps & Location Tools", isPro: false },
  { id: 26, name: "Coordinate Distance Calculator", slug: "coordinate-distance-calculator", category: "Maps & Location Tools", isPro: false },
  { id: 27, name: "GPS Coordinate Converter", slug: "gps-coordinate-converter", category: "Maps & Location Tools", isPro: false },
  { id: 28, name: "ZIP Code Location Finder", slug: "zip-code-location-finder", category: "Maps & Location Tools", isPro: false },
  { id: 29, name: "Postal Code Location Finder", slug: "postal-code-location-finder", category: "Maps & Location Tools", isPro: false },
  { id: 30, name: "PIN Code Location Finder", slug: "pin-code-location-finder", category: "Maps & Location Tools", isPro: false },
  { id: 31, name: "City Location Finder", slug: "city-location-finder", category: "Maps & Location Tools", isPro: false },
  { id: 32, name: "Location Radius Calculator", slug: "location-radius-calculator", category: "Maps & Location Tools", isPro: false },
  { id: 33, name: "Geofence Radius Calculator", slug: "geofence-radius-calculator", category: "Maps & Location Tools", isPro: false },
  { id: 34, name: "Map Radius Generator", slug: "map-radius-generator", category: "Maps & Location Tools", isPro: false },
  { id: 35, name: "Travel Radius Calculator", slug: "travel-radius-calculator", category: "Maps & Location Tools", isPro: false },
  { id: 36, name: "Service Area Calculator", slug: "service-area-calculator", category: "Maps & Location Tools", isPro: false },
  { id: 37, name: "Store Coverage Calculator", slug: "store-coverage-calculator", category: "Maps & Location Tools", isPro: false },
  { id: 38, name: "Location Catchment Calculator", slug: "location-catchment-calculator", category: "Maps & Location Tools", isPro: false },
  { id: 39, name: "Nearest Store Finder", slug: "nearest-store-finder", category: "Maps & Location Tools", isPro: false },
  { id: 40, name: "Nearest Service Finder", slug: "nearest-service-finder", category: "Maps & Location Tools", isPro: false },
  { id: 41, name: "Route Waypoint Planner", slug: "route-waypoint-planner", category: "Maps & Location Tools", isPro: false },
  { id: 42, name: "Travel Route Comparison", slug: "travel-route-comparison", category: "Maps & Location Tools", isPro: false },
  { id: 43, name: "Route Cost Comparison", slug: "route-cost-comparison", category: "Maps & Location Tools", isPro: false },
  { id: 44, name: "Parking Cost Calculator", slug: "parking-cost-calculator", category: "Maps & Location Tools", isPro: false },
  { id: 45, name: "Trip Distance Calculator", slug: "trip-distance-calculator", category: "Maps & Location Tools", isPro: false },
  { id: 46, name: "Trip Time Calculator", slug: "trip-time-calculator", category: "Maps & Location Tools", isPro: false },
  { id: 47, name: "Commute Time Calculator", slug: "commute-time-calculator", category: "Maps & Location Tools", isPro: false },
  { id: 48, name: "Location Sharing Tool", slug: "location-sharing-tool", category: "Maps & Location Tools", isPro: false },
  { id: 49, name: "Coordinate Sharing Generator", slug: "coordinate-sharing-generator", category: "Maps & Location Tools", isPro: false },
  { id: 50, name: "Map Link Generator", slug: "map-link-generator", category: "Maps & Location Tools", isPro: false },
  { id: 51, name: "Static Map Generator", slug: "static-map-generator", category: "Maps & Location Tools", isPro: false },
  { id: 52, name: "Map Marker Generator", slug: "map-marker-generator", category: "Maps & Location Tools", isPro: false },
  { id: 53, name: "Map Coordinate Validator", slug: "map-coordinate-validator", category: "Maps & Location Tools", isPro: false },
  { id: 54, name: "GPS Format Converter", slug: "gps-format-converter", category: "Maps & Location Tools", isPro: false },
  { id: 55, name: "GPX File Analyzer", slug: "gpx-file-analyzer", category: "Maps & Location Tools", isPro: false },
  { id: 56, name: "KML File Analyzer", slug: "kml-file-analyzer", category: "Maps & Location Tools", isPro: false },
  { id: 57, name: "GeoJSON Validator", slug: "geojson-validator", category: "Maps & Location Tools", isPro: false },
  { id: 58, name: "GeoJSON Converter", slug: "geojson-converter", category: "Maps & Location Tools", isPro: false },
  { id: 59, name: "Route File Converter", slug: "route-file-converter", category: "Maps & Location Tools", isPro: false },
  { id: 60, name: "Location Data Cleaner", slug: "location-data-cleaner", category: "Maps & Location Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Advanced Route Optimization Engine", slug: "advanced-route-optimization-engine", category: "Maps & Location Tools", isPro: true },
  { id: 62, name: "Multi-Vehicle Route Planner", slug: "multi-vehicle-route-planner", category: "Maps & Location Tools", isPro: true },
  { id: 63, name: "Delivery Fleet Route Optimizer", slug: "delivery-fleet-route-optimizer", category: "Maps & Location Tools", isPro: true },
  { id: 64, name: "Logistics Route Intelligence", slug: "logistics-route-intelligence", category: "Maps & Location Tools", isPro: true },
  { id: 65, name: "Last-Mile Delivery Optimizer", slug: "last-mile-delivery-optimizer", category: "Maps & Location Tools", isPro: true },
  { id: 66, name: "Territory Planning Workspace", slug: "territory-planning-workspace", category: "Maps & Location Tools", isPro: true },
  { id: 67, name: "Sales Territory Mapper", slug: "sales-territory-mapper", category: "Maps & Location Tools", isPro: true },
  { id: 68, name: "Service Territory Planner", slug: "service-territory-planner", category: "Maps & Location Tools", isPro: true },
  { id: 69, name: "Store Coverage Analyzer", slug: "store-coverage-analyzer", category: "Maps & Location Tools", isPro: true },
  { id: 70, name: "Delivery Coverage Analyzer", slug: "delivery-coverage-analyzer", category: "Maps & Location Tools", isPro: true },
  { id: 71, name: "Customer Location Analyzer", slug: "customer-location-analyzer", category: "Maps & Location Tools", isPro: true },
  { id: 72, name: "Location Intelligence Dashboard", slug: "location-intelligence-dashboard", category: "Maps & Location Tools", isPro: true },
  { id: 73, name: "Catchment Area Analyzer", slug: "catchment-area-analyzer", category: "Maps & Location Tools", isPro: true },
  { id: 74, name: "Trade Area Analyzer", slug: "trade-area-analyzer", category: "Maps & Location Tools", isPro: true },
  { id: 75, name: "Retail Location Analyzer", slug: "retail-location-analyzer", category: "Maps & Location Tools", isPro: true },
  { id: 76, name: "Franchise Location Analyzer", slug: "franchise-location-analyzer", category: "Maps & Location Tools", isPro: true },
  { id: 77, name: "Business Site Selection Tool", slug: "business-site-selection-tool", category: "Maps & Location Tools", isPro: true },
  { id: 78, name: "New Store Location Analyzer", slug: "new-store-location-analyzer", category: "Maps & Location Tools", isPro: true },
  { id: 79, name: "Competitor Location Analyzer", slug: "competitor-location-analyzer", category: "Maps & Location Tools", isPro: true },
  { id: 80, name: "Market Radius Analyzer", slug: "market-radius-analyzer", category: "Maps & Location Tools", isPro: true },
  { id: 81, name: "Geographic Customer Segmentation", slug: "geographic-customer-segmentation", category: "Maps & Location Tools", isPro: true },
  { id: 82, name: "Sales Territory Optimization", slug: "sales-territory-optimization", category: "Maps & Location Tools", isPro: true },
  { id: 83, name: "Field Service Route Planner", slug: "field-service-route-planner", category: "Maps & Location Tools", isPro: true },
  { id: 84, name: "Technician Route Optimizer", slug: "technician-route-optimizer", category: "Maps & Location Tools", isPro: true },
  { id: 85, name: "Fleet Distance Analyzer", slug: "fleet-distance-analyzer", category: "Maps & Location Tools", isPro: true },
  { id: 86, name: "Fleet Fuel Cost Analyzer", slug: "fleet-fuel-cost-analyzer", category: "Maps & Location Tools", isPro: true },
  { id: 87, name: "Fleet Travel Time Analyzer", slug: "fleet-travel-time-analyzer", category: "Maps & Location Tools", isPro: true },
  { id: 88, name: "GPS Data Analyzer", slug: "gps-data-analyzer", category: "Maps & Location Tools", isPro: true },
  { id: 89, name: "GPX Route Intelligence", slug: "gpx-route-intelligence", category: "Maps & Location Tools", isPro: true },
  { id: 90, name: "GeoJSON Data Workspace", slug: "geojson-data-workspace", category: "Maps & Location Tools", isPro: true },
  { id: 91, name: "Geospatial Data Cleaning Tool", slug: "geospatial-data-cleaning-tool", category: "Maps & Location Tools", isPro: true },
  { id: 92, name: "Geospatial Dataset Analyzer", slug: "geospatial-dataset-analyzer", category: "Maps & Location Tools", isPro: true },
  { id: 93, name: "Location API Workspace", slug: "location-api-workspace", category: "Maps & Location Tools", isPro: true },
  { id: 94, name: "Mapping Data Dashboard", slug: "mapping-data-dashboard", category: "Maps & Location Tools", isPro: true },
  { id: 95, name: "Logistics Location Intelligence Platform", slug: "logistics-location-intelligence-platform", category: "Maps & Location Tools", isPro: true },
  { id: 96, name: "Retail Location Intelligence Platform", slug: "retail-location-intelligence-platform", category: "Maps & Location Tools", isPro: true },
  { id: 97, name: "Field Operations Location Platform", slug: "field-operations-location-platform", category: "Maps & Location Tools", isPro: true },
  { id: 98, name: "Territory Intelligence Platform", slug: "territory-intelligence-platform", category: "Maps & Location Tools", isPro: true },
  { id: 99, name: "Geospatial Business Intelligence", slug: "geospatial-business-intelligence", category: "Maps & Location Tools", isPro: true },
  { id: 100, name: "Professional Location Command Center", slug: "professional-location-command-center", category: "Maps & Location Tools", isPro: true }
];