export interface MarketingTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const marketingToolsList: MarketingTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-10) ---
  { id: 1, name: "Marketing ROI Calculator", slug: "marketing-roi-calculator", category: "Marketing Tools", isPro: false },
  { id: 2, name: "ROAS Calculator", slug: "roas-calculator", category: "Marketing Tools", isPro: false },
  { id: 3, name: "CAC Calculator", slug: "cac-calculator", category: "Marketing Tools", isPro: false },
  { id: 4, name: "LTV:CAC Calculator", slug: "ltv-cac-calculator", category: "Marketing Tools", isPro: false },
  { id: 5, name: "CPM Calculator", slug: "cpm-calculator", category: "Marketing Tools", isPro: false },
  { id: 6, name: "CPC Calculator", slug: "cpc-calculator", category: "Marketing Tools", isPro: false },
  { id: 7, name: "CTR Calculator", slug: "ctr-calculator", category: "Marketing Tools", isPro: false },
  { id: 8, name: "CPA Calculator", slug: "cpa-calculator", category: "Marketing Tools", isPro: false },
  { id: 9, name: "CPL Calculator", slug: "cpl-calculator", category: "Marketing Tools", isPro: false },
  { id: 10, name: "Customer Persona Generator", slug: "customer-persona-generator", category: "Marketing Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (11-60) ---
  { id: 11, name: "Marketing Plan Generator", slug: "marketing-plan-generator", category: "Marketing Tools", isPro: false },
  { id: 12, name: "Marketing Strategy Generator", slug: "marketing-strategy-generator", category: "Marketing Tools", isPro: false },
  { id: 13, name: "Marketing Campaign Planner", slug: "marketing-campaign-planner", category: "Marketing Tools", isPro: false },
  { id: 14, name: "Marketing Calendar", slug: "marketing-calendar", category: "Marketing Tools", isPro: false },
  { id: 15, name: "Content Marketing Planner", slug: "content-marketing-planner", category: "Marketing Tools", isPro: false },
  { id: 16, name: "Content Calendar Generator", slug: "content-calendar-generator", category: "Marketing Tools", isPro: false },
  { id: 17, name: "Content Brief Generator", slug: "content-brief-generator-marketing", category: "Marketing Tools", isPro: false },
  { id: 18, name: "Ad Copy Generator", slug: "ad-copy-generator", category: "Marketing Tools", isPro: false },
  { id: 19, name: "Ad Headline Generator", slug: "ad-headline-generator", category: "Marketing Tools", isPro: false },
  { id: 20, name: "Ad Description Generator", slug: "ad-description-generator", category: "Marketing Tools", isPro: false },
  { id: 21, name: "Call-to-Action Generator", slug: "call-to-action-generator", category: "Marketing Tools", isPro: false },
  { id: 22, name: "Landing Page Copy Generator", slug: "landing-page-copy-generator", category: "Marketing Tools", isPro: false },
  { id: 23, name: "Sales Copy Generator", slug: "sales-copy-generator", category: "Marketing Tools", isPro: false },
  { id: 24, name: "Product Copy Generator", slug: "product-copy-generator", category: "Marketing Tools", isPro: false },
  { id: 25, name: "Promotional Copy Generator", slug: "promotional-copy-generator", category: "Marketing Tools", isPro: false },
  { id: 26, name: "Offer Generator", slug: "offer-generator", category: "Marketing Tools", isPro: false },
  { id: 27, name: "Lead Magnet Generator", slug: "lead-magnet-generator", category: "Marketing Tools", isPro: false },
  { id: 28, name: "Lead Generation Ideas Tool", slug: "lead-generation-ideas-tool", category: "Marketing Tools", isPro: false },
  { id: 29, name: "Buyer Persona Generator", slug: "buyer-persona-generator", category: "Marketing Tools", isPro: false },
  { id: 30, name: "Customer Avatar Generator", slug: "customer-avatar-generator", category: "Marketing Tools", isPro: false },
  { id: 31, name: "Target Audience Generator", slug: "target-audience-generator", category: "Marketing Tools", isPro: false },
  { id: 32, name: "Value Proposition Generator", slug: "value-proposition-generator", category: "Marketing Tools", isPro: false },
  { id: 33, name: "Unique Selling Proposition Generator", slug: "unique-selling-proposition-generator", category: "Marketing Tools", isPro: false },
  { id: 34, name: "Marketing Slogan Generator", slug: "marketing-slogan-generator", category: "Marketing Tools", isPro: false },
  { id: 35, name: "Brand Message Generator", slug: "brand-message-generator", category: "Marketing Tools", isPro: false },
  { id: 36, name: "Campaign Name Generator", slug: "campaign-name-generator", category: "Marketing Tools", isPro: false },
  { id: 37, name: "Campaign Brief Generator", slug: "campaign-brief-generator", category: "Marketing Tools", isPro: false },
  { id: 38, name: "Marketing Hook Generator", slug: "marketing-hook-generator", category: "Marketing Tools", isPro: false },
  { id: 39, name: "Marketing Angle Generator", slug: "marketing-angle-generator", category: "Marketing Tools", isPro: false },
  { id: 40, name: "A/B Test Idea Generator", slug: "ab-test-idea-generator", category: "Marketing Tools", isPro: false },
  { id: 41, name: "Email Campaign Planner", slug: "email-campaign-planner", category: "Marketing Tools", isPro: false },
  { id: 42, name: "Newsletter Content Generator", slug: "newsletter-content-generator", category: "Marketing Tools", isPro: false },
  { id: 43, name: "Lead Scoring Calculator", slug: "lead-scoring-calculator", category: "Marketing Tools", isPro: false },
  { id: 44, name: "Conversion Rate Calculator", slug: "conversion-rate-calculator-marketing", category: "Marketing Tools", isPro: false },
  { id: 45, name: "LTV Calculator", slug: "ltv-calculator-marketing", category: "Marketing Tools", isPro: false },
  { id: 46, name: "Marketing Budget Calculator", slug: "marketing-budget-calculator", category: "Marketing Tools", isPro: false },
  { id: 47, name: "Ad Budget Calculator", slug: "ad-budget-calculator", category: "Marketing Tools", isPro: false },
  { id: 48, name: "Conversion Funnel Calculator", slug: "conversion-funnel-calculator", category: "Marketing Tools", isPro: false },
  { id: 49, name: "Sales Funnel Calculator", slug: "sales-funnel-calculator", category: "Marketing Tools", isPro: false },
  { id: 50, name: "Landing Page Conversion Calculator", slug: "landing-page-conversion-calculator", category: "Marketing Tools", isPro: false },
  { id: 51, name: "Email Conversion Calculator", slug: "email-conversion-calculator", category: "Marketing Tools", isPro: false },
  { id: 52, name: "Campaign Profit Calculator", slug: "campaign-profit-calculator", category: "Marketing Tools", isPro: false },
  { id: 53, name: "Affiliate Commission Calculator", slug: "affiliate-commission-calculator-marketing", category: "Marketing Tools", isPro: false },
  { id: 54, name: "Influencer Marketing Calculator", slug: "influencer-marketing-calculator-marketing", category: "Marketing Tools", isPro: false },
  { id: 55, name: "Social Media ROI Calculator", slug: "social-media-roi-calculator-marketing", category: "Marketing Tools", isPro: false },
  { id: 56, name: "Content ROI Calculator", slug: "content-roi-calculator", category: "Marketing Tools", isPro: false },
  { id: 57, name: "Customer Acquisition Calculator", slug: "customer-acquisition-calculator", category: "Marketing Tools", isPro: false },
  { id: 58, name: "Marketing Break-Even Calculator", slug: "marketing-break-even-calculator", category: "Marketing Tools", isPro: false },
  { id: 59, name: "Promotion ROI Calculator", slug: "promotion-roi-calculator", category: "Marketing Tools", isPro: false },
  { id: 60, name: "Campaign Performance Calculator", slug: "campaign-performance-calculator", category: "Marketing Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "UTM Builder", slug: "utm-builder", category: "Marketing Tools", isPro: true },
  { id: 62, name: "UTM Campaign Manager", slug: "utm-campaign-manager", category: "Marketing Tools", isPro: true },
  { id: 63, name: "Competitor Marketing Analyzer", slug: "competitor-marketing-analyzer", category: "Marketing Tools", isPro: true },
  { id: 64, name: "Marketing Funnel Analyzer", slug: "marketing-funnel-analyzer", category: "Marketing Tools", isPro: true },
  { id: 65, name: "Customer Journey Mapper", slug: "customer-journey-mapper", category: "Marketing Tools", isPro: true },
  { id: 66, name: "Conversion Funnel Analyzer", slug: "conversion-funnel-analyzer", category: "Marketing Tools", isPro: true },
  { id: 67, name: "Marketing Attribution Calculator", slug: "marketing-attribution-calculator", category: "Marketing Tools", isPro: true },
  { id: 68, name: "Multi-Touch Attribution Tool", slug: "multi-touch-attribution-tool", category: "Marketing Tools", isPro: true },
  { id: 69, name: "UTM Validator", slug: "utm-validator", category: "Marketing Tools", isPro: true },
  { id: 70, name: "Campaign Tracking Dashboard", slug: "campaign-tracking-dashboard", category: "Marketing Tools", isPro: true },
  { id: 71, name: "Marketing Channel Analyzer", slug: "marketing-channel-analyzer", category: "Marketing Tools", isPro: true },
  { id: 72, name: "Channel Performance Benchmark", slug: "channel-performance-benchmark", category: "Marketing Tools", isPro: true },
  { id: 73, name: "Competitor Ad Analyzer", slug: "competitor-ad-analyzer", category: "Marketing Tools", isPro: true },
  { id: 74, name: "Competitor Content Analyzer", slug: "competitor-content-analyzer", category: "Marketing Tools", isPro: true },
  { id: 75, name: "Competitor Funnel Analyzer", slug: "competitor-funnel-analyzer", category: "Marketing Tools", isPro: true },
  { id: 76, name: "Market Positioning Analyzer", slug: "market-positioning-analyzer", category: "Marketing Tools", isPro: true },
  { id: 77, name: "Brand Positioning Tool", slug: "brand-positioning-tool", category: "Marketing Tools", isPro: true },
  { id: 78, name: "Market Segmentation Tool", slug: "market-segmentation-tool", category: "Marketing Tools", isPro: true },
  { id: 79, name: "Audience Segmentation Tool", slug: "audience-segmentation-tool", category: "Marketing Tools", isPro: true },
  { id: 80, name: "Behavioral Segmentation Tool", slug: "behavioral-segmentation-tool", category: "Marketing Tools", isPro: true },
  { id: 81, name: "Lead Scoring Engine", slug: "lead-scoring-engine", category: "Marketing Tools", isPro: true },
  { id: 82, name: "Lead Qualification Tool", slug: "lead-qualification-tool", category: "Marketing Tools", isPro: true },
  { id: 83, name: "Lead Prioritization Tool", slug: "lead-prioritization-tool", category: "Marketing Tools", isPro: true },
  { id: 84, name: "Marketing Mix Calculator", slug: "marketing-mix-calculator", category: "Marketing Tools", isPro: true },
  { id: 85, name: "Marketing Forecasting Tool", slug: "marketing-forecasting-tool", category: "Marketing Tools", isPro: true },
  { id: 86, name: "Demand Generation Planner", slug: "demand-generation-planner", category: "Marketing Tools", isPro: true },
  { id: 87, name: "Growth Experiment Planner", slug: "growth-experiment-planner", category: "Marketing Tools", isPro: true },
  { id: 88, name: "Growth Marketing Calculator", slug: "growth-marketing-calculator", category: "Marketing Tools", isPro: true },
  { id: 89, name: "Product-Market Fit Survey Analyzer", slug: "product-market-fit-survey-analyzer", category: "Marketing Tools", isPro: true },
  { id: 90, name: "Customer Feedback Analyzer", slug: "customer-feedback-analyzer", category: "Marketing Tools", isPro: true },
  { id: 91, name: "Customer Sentiment Analyzer", slug: "customer-sentiment-analyzer", category: "Marketing Tools", isPro: true },
  { id: 92, name: "Survey Response Analyzer", slug: "survey-response-analyzer", category: "Marketing Tools", isPro: true },
  { id: 93, name: "NPS Calculator", slug: "nps-calculator", category: "Marketing Tools", isPro: true },
  { id: 94, name: "NPS Analyzer", slug: "nps-analyzer", category: "Marketing Tools", isPro: true },
  { id: 95, name: "Churn Impact Calculator", slug: "churn-impact-calculator", category: "Marketing Tools", isPro: true },
  { id: 96, name: "Retention Revenue Calculator", slug: "retention-revenue-calculator", category: "Marketing Tools", isPro: true },
  { id: 97, name: "Marketing Attribution Dashboard", slug: "marketing-attribution-dashboard", category: "Marketing Tools", isPro: true },
  { id: 98, name: "Campaign Reporting Generator", slug: "campaign-reporting-generator", category: "Marketing Tools", isPro: true },
  { id: 99, name: "Marketing Executive Dashboard", slug: "marketing-executive-dashboard", category: "Marketing Tools", isPro: true },
  { id: 100, name: "Marketing Intelligence Platform", slug: "marketing-intelligence-platform", category: "Marketing Tools", isPro: true },
];