export interface MedicalTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const medicalToolsList: MedicalTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "BMI Calculator", slug: "bmi-calculator", category: "Medical Tools", isPro: false },
  { id: 2, name: "BMR Calculator", slug: "bmr-calculator", category: "Medical Tools", isPro: false },
  { id: 3, name: "Body Fat Calculator", slug: "body-fat-calculator", category: "Medical Tools", isPro: false },
  { id: 4, name: "Ideal Weight Calculator", slug: "ideal-weight-calculator", category: "Medical Tools", isPro: false },
  { id: 5, name: "Calorie Needs Calculator", slug: "calorie-needs-calculator", category: "Medical Tools", isPro: false },
  { id: 6, name: "Macro Calculator", slug: "macro-calculator", category: "Medical Tools", isPro: false },
  { id: 7, name: "Water Intake Calculator", slug: "water-intake-calculator", category: "Medical Tools", isPro: false },
  { id: 8, name: "Target Heart Rate Calculator", slug: "target-heart-rate-calculator", category: "Medical Tools", isPro: false },
  { id: 9, name: "Body Surface Area Calculator", slug: "body-surface-area-calculator", category: "Medical Tools", isPro: false },
  { id: 10, name: "eGFR Calculator", slug: "egfr-calculator", category: "Medical Tools", isPro: false },
  { id: 11, name: "Anion Gap Calculator", slug: "anion-gap-calculator", category: "Medical Tools", isPro: false },
  { id: 12, name: "Mean Arterial Pressure Calculator", slug: "mean-arterial-pressure-calculator", category: "Medical Tools", isPro: false },
  { id: 13, name: "QTc Calculator", slug: "qtc-calculator", category: "Medical Tools", isPro: false },
  { id: 14, name: "Medical Unit Converter", slug: "medical-unit-converter", category: "Medical Tools", isPro: false },
  { id: 15, name: "Medication Schedule Planner", slug: "medication-schedule-planner", category: "Medical Tools", isPro: false },
  { id: 16, name: "Blood Pressure Log", slug: "blood-pressure-log", category: "Medical Tools", isPro: false },
  { id: 17, name: "Blood Glucose Log", slug: "blood-glucose-log", category: "Medical Tools", isPro: false },
  { id: 18, name: "Medical History Organizer", slug: "medical-history-organizer", category: "Medical Tools", isPro: false },
  { id: 19, name: "Lab Result Organizer", slug: "lab-result-organizer", category: "Medical Tools", isPro: false },
  { id: 20, name: "Personal Health Record Workspace", slug: "personal-health-record-workspace", category: "Medical Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Body Fat Percentage Calculator", slug: "body-fat-percentage-calculator", category: "Medical Tools", isPro: false },
  { id: 22, name: "Healthy Weight Range Calculator", slug: "healthy-weight-range-calculator", category: "Medical Tools", isPro: false },
  { id: 23, name: "Protein Requirement Calculator", slug: "protein-requirement-calculator", category: "Medical Tools", isPro: false },
  { id: 24, name: "Heart Rate Calculator", slug: "heart-rate-calculator", category: "Medical Tools", isPro: false },
  { id: 25, name: "Resting Heart Rate Calculator", slug: "resting-heart-rate-calculator", category: "Medical Tools", isPro: false },
  { id: 26, name: "Heart Rate Zone Calculator", slug: "heart-rate-zone-calculator", category: "Medical Tools", isPro: false },
  { id: 27, name: "Creatinine Clearance Calculator", slug: "creatinine-clearance-calculator", category: "Medical Tools", isPro: false },
  { id: 28, name: "Corrected Calcium Calculator", slug: "corrected-calcium-calculator", category: "Medical Tools", isPro: false },
  { id: 29, name: "Pulse Pressure Calculator", slug: "pulse-pressure-calculator", category: "Medical Tools", isPro: false },
  { id: 30, name: "Osmolality Calculator", slug: "osmolality-calculator", category: "Medical Tools", isPro: false },
  { id: 31, name: "Sodium Correction Calculator", slug: "sodium-correction-calculator", category: "Medical Tools", isPro: false },
  { id: 32, name: "Temperature Converter for Medicine", slug: "temperature-converter-for-medicine", category: "Medical Tools", isPro: false },
  { id: 33, name: "Weight Dose Conversion Tool", slug: "weight-dose-conversion-tool", category: "Medical Tools", isPro: false },
  { id: 34, name: "Height Converter", slug: "height-converter", category: "Medical Tools", isPro: false },
  { id: 35, name: "Weight Converter", slug: "weight-converter", category: "Medical Tools", isPro: false },
  { id: 36, name: "Medication Reminder Generator", slug: "medication-reminder-generator", category: "Medical Tools", isPro: false },
  { id: 37, name: "Appointment Reminder Planner", slug: "appointment-reminder-planner", category: "Medical Tools", isPro: false },
  { id: 38, name: "Medical Appointment Tracker", slug: "medical-appointment-tracker", category: "Medical Tools", isPro: false },
  { id: 39, name: "Health Measurement Tracker", slug: "health-measurement-tracker", category: "Medical Tools", isPro: false },
  { id: 40, name: "Heart Rate Log", slug: "heart-rate-log", category: "Medical Tools", isPro: false },
  { id: 41, name: "Weight Tracking Tool", slug: "weight-tracking-tool", category: "Medical Tools", isPro: false },
  { id: 42, name: "Symptom Journal", slug: "symptom-journal", category: "Medical Tools", isPro: false },
  { id: 43, name: "Medication List Organizer", slug: "medication-list-organizer", category: "Medical Tools", isPro: false },
  { id: 44, name: "Allergy List Organizer", slug: "allergy-list-organizer", category: "Medical Tools", isPro: false },
  { id: 45, name: "Vaccination Record Organizer", slug: "vaccination-record-organizer", category: "Medical Tools", isPro: false },
  { id: 46, name: "Medical Document Organizer", slug: "medical-document-organizer", category: "Medical Tools", isPro: false },
  { id: 47, name: "Doctor Visit Checklist", slug: "doctor-visit-checklist", category: "Medical Tools", isPro: false },
  { id: 48, name: "Patient Question Generator", slug: "patient-question-generator", category: "Medical Tools", isPro: false },
  { id: 49, name: "Medication Question Checklist", slug: "medication-question-checklist", category: "Medical Tools", isPro: false },
  { id: 50, name: "Medical Appointment Checklist", slug: "medical-appointment-checklist", category: "Medical Tools", isPro: false },
  { id: 51, name: "Health Report Generator", slug: "health-report-generator", category: "Medical Tools", isPro: false },
  { id: 52, name: "Medical Timeline Generator", slug: "medical-timeline-generator", category: "Medical Tools", isPro: false },
  { id: 53, name: "Emergency Information Card", slug: "emergency-information-card", category: "Medical Tools", isPro: false },
  { id: 54, name: "Medical ID Card Generator", slug: "medical-id-card-generator", category: "Medical Tools", isPro: false },
  { id: 55, name: "Health Record Summary", slug: "health-record-summary", category: "Medical Tools", isPro: false },
  { id: 56, name: "Lab Value Reference Tool", slug: "lab-value-reference-tool", category: "Medical Tools", isPro: false },
  { id: 57, name: "Medical Abbreviation Finder", slug: "medical-abbreviation-finder", category: "Medical Tools", isPro: false },
  { id: 58, name: "Medical Terminology Dictionary", slug: "medical-terminology-dictionary", category: "Medical Tools", isPro: false },
  { id: 59, name: "Anatomy Reference Tool", slug: "anatomy-reference-tool", category: "Medical Tools", isPro: false },
  { id: 60, name: "Medical Conversion Calculator", slug: "medical-conversion-calculator", category: "Medical Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Medical Document Dashboard", slug: "medical-document-dashboard", category: "Medical Tools", isPro: true },
  { id: 62, name: "Health Timeline Workspace", slug: "health-timeline-workspace", category: "Medical Tools", isPro: true },
  { id: 63, name: "Medication Management Workspace", slug: "medication-management-workspace", category: "Medical Tools", isPro: true },
  { id: 64, name: "Appointment Management Workspace", slug: "appointment-management-workspace", category: "Medical Tools", isPro: true },
  { id: 65, name: "Lab Results Dashboard", slug: "lab-results-dashboard", category: "Medical Tools", isPro: true },
  { id: 66, name: "Health Metrics Dashboard", slug: "health-metrics-dashboard", category: "Medical Tools", isPro: true },
  { id: 67, name: "Blood Pressure Tracking Dashboard", slug: "blood-pressure-tracking-dashboard", category: "Medical Tools", isPro: true },
  { id: 68, name: "Blood Glucose Tracking Dashboard", slug: "blood-glucose-tracking-dashboard", category: "Medical Tools", isPro: true },
  { id: 69, name: "Weight Trend Analyzer", slug: "weight-trend-analyzer", category: "Medical Tools", isPro: true },
  { id: 70, name: "Heart Rate Trend Analyzer", slug: "heart-rate-trend-analyzer", category: "Medical Tools", isPro: true },
  { id: 71, name: "Health Measurement Trend Analyzer", slug: "health-measurement-trend-analyzer", category: "Medical Tools", isPro: true },
  { id: 72, name: "Medication Schedule Dashboard", slug: "medication-schedule-dashboard", category: "Medical Tools", isPro: true },
  { id: 73, name: "Medication Adherence Tracker", slug: "medication-adherence-tracker", category: "Medical Tools", isPro: true },
  { id: 74, name: "Medical Appointment Planner", slug: "medical-appointment-planner", category: "Medical Tools", isPro: true },
  { id: 75, name: "Doctor Visit Preparation Workspace", slug: "doctor-visit-preparation-workspace", category: "Medical Tools", isPro: true },
  { id: 76, name: "Medical Question Planner", slug: "medical-question-planner", category: "Medical Tools", isPro: true },
  { id: 77, name: "Patient Report Builder", slug: "patient-report-builder", category: "Medical Tools", isPro: true },
  { id: 78, name: "Medical History Builder", slug: "medical-history-builder", category: "Medical Tools", isPro: true },
  { id: 79, name: "Family Medical History Workspace", slug: "family-medical-history-workspace", category: "Medical Tools", isPro: true },
  { id: 80, name: "Vaccination Record Workspace", slug: "vaccination-record-workspace", category: "Medical Tools", isPro: true },
  { id: 81, name: "Allergy Management Workspace", slug: "allergy-management-workspace", category: "Medical Tools", isPro: true },
  { id: 82, name: "Medical Document OCR Organizer", slug: "medical-document-ocr-organizer", category: "Medical Tools", isPro: true },
  { id: 83, name: "Lab Report Data Organizer", slug: "lab-report-data-organizer", category: "Medical Tools", isPro: true },
  { id: 84, name: "Health Data Import Workspace", slug: "health-data-import-workspace", category: "Medical Tools", isPro: true },
  { id: 85, name: "Personal Health Data Exporter", slug: "personal-health-data-exporter", category: "Medical Tools", isPro: true },
  { id: 86, name: "Health Data Visualization Dashboard", slug: "health-data-visualization-dashboard", category: "Medical Tools", isPro: true },
  { id: 87, name: "Medical Record Timeline Generator", slug: "medical-record-timeline-generator", category: "Medical Tools", isPro: true },
  { id: 88, name: "Clinical Calculation Workspace", slug: "clinical-calculation-workspace", category: "Medical Tools", isPro: true },
  { id: 89, name: "Medical Formula Library", slug: "medical-formula-library", category: "Medical Tools", isPro: true },
  { id: 90, name: "Medical Reference Workspace", slug: "medical-reference-workspace", category: "Medical Tools", isPro: true },
  { id: 91, name: "Healthcare Practice Documentation Workspace", slug: "healthcare-practice-documentation-workspace", category: "Medical Tools", isPro: true },
  { id: 92, name: "Patient Intake Form Builder", slug: "patient-intake-form-builder", category: "Medical Tools", isPro: true },
  { id: 93, name: "Healthcare Form Generator", slug: "healthcare-form-generator", category: "Medical Tools", isPro: true },
  { id: 94, name: "Medical Practice Operations Dashboard", slug: "medical-practice-operations-dashboard", category: "Medical Tools", isPro: true },
  { id: 95, name: "Healthcare Data Management Workspace", slug: "healthcare-data-management-workspace", category: "Medical Tools", isPro: true },
  { id: 96, name: "Patient Communication Workspace", slug: "patient-communication-workspace", category: "Medical Tools", isPro: true },
  { id: 97, name: "Healthcare Documentation Platform", slug: "healthcare-documentation-platform", category: "Medical Tools", isPro: true },
  { id: 98, name: "Personal Health Intelligence Workspace", slug: "personal-health-intelligence-workspace", category: "Medical Tools", isPro: true },
  { id: 99, name: "Professional Healthcare Operations Platform", slug: "professional-healthcare-operations-platform", category: "Medical Tools", isPro: true },
  { id: 100, name: "ICD Code Lookup Tool", slug: "icd-code-lookup-tool", category: "Medical Tools", isPro: true }
];