export interface MobileAppTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const mobileAppToolsList: MobileAppTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "App Icon Generator", slug: "app-icon-generator", category: "Mobile App Tools", isPro: false },
  { id: 2, name: "App Screenshot Resizer", slug: "app-screenshot-resizer", category: "Mobile App Tools", isPro: false },
  { id: 3, name: "APK Size Analyzer", slug: "apk-size-analyzer", category: "Mobile App Tools", isPro: false },
  { id: 4, name: "App Download Size Calculator", slug: "app-download-size-calculator", category: "Mobile App Tools", isPro: false },
  { id: 5, name: "Mobile Data Usage Calculator", slug: "mobile-data-usage-calculator", category: "Mobile App Tools", isPro: false },
  { id: 6, name: "App Revenue Calculator", slug: "app-revenue-calculator", category: "Mobile App Tools", isPro: false },
  { id: 7, name: "App Ad Revenue Calculator", slug: "app-ad-revenue-calculator", category: "Mobile App Tools", isPro: false },
  { id: 8, name: "App LTV Calculator", slug: "app-ltv-calculator", category: "Mobile App Tools", isPro: false },
  { id: 9, name: "App CAC Calculator", slug: "app-cac-calculator", category: "Mobile App Tools", isPro: false },
  { id: 10, name: "App Churn Calculator", slug: "app-churn-calculator", category: "Mobile App Tools", isPro: false },
  { id: 11, name: "App Retention Calculator", slug: "app-retention-calculator", category: "Mobile App Tools", isPro: false },
  { id: 12, name: "App Conversion Rate Calculator", slug: "app-conversion-rate-calculator", category: "Mobile App Tools", isPro: false },
  { id: 13, name: "DAU/MAU Ratio Calculator", slug: "dau-mau-ratio-calculator", category: "Mobile App Tools", isPro: false },
  { id: 14, name: "Mobile Screen Resolution Calculator", slug: "mobile-screen-resolution-calculator", category: "Mobile App Tools", isPro: false },
  { id: 15, name: "App Permissions Checker", slug: "app-permissions-checker", category: "Mobile App Tools", isPro: false },
  { id: 16, name: "Deep Link Tester", slug: "deep-link-tester", category: "Mobile App Tools", isPro: false },
  { id: 17, name: "App Store Submission Checklist", slug: "app-store-submission-checklist", category: "Mobile App Tools", isPro: false },
  { id: 18, name: "Google Play Submission Checklist", slug: "google-play-submission-checklist", category: "Mobile App Tools", isPro: false },
  { id: 19, name: "Mobile App Test Case Generator", slug: "mobile-app-test-case-generator", category: "Mobile App Tools", isPro: false },
  { id: 20, name: "App Store Optimization Workspace", slug: "app-store-optimization-workspace", category: "Mobile App Tools", isPro: true },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "App Icon Size Checker", slug: "app-icon-size-checker", category: "Mobile App Tools", isPro: false },
  { id: 22, name: "Android Icon Generator", slug: "android-icon-generator", category: "Mobile App Tools", isPro: false },
  { id: 23, name: "iOS Icon Generator", slug: "ios-icon-generator", category: "Mobile App Tools", isPro: false },
  { id: 24, name: "App Screenshot Size Checker", slug: "app-screenshot-size-checker", category: "Mobile App Tools", isPro: false },
  { id: 25, name: "App Screenshot Generator", slug: "app-screenshot-generator", category: "Mobile App Tools", isPro: false },
  { id: 26, name: "Google Play Screenshot Resizer", slug: "google-play-screenshot-resizer", category: "Mobile App Tools", isPro: false },
  { id: 27, name: "App Banner Resizer", slug: "app-banner-resizer", category: "Mobile App Tools", isPro: false },
  { id: 28, name: "App Store Image Resizer", slug: "app-store-image-resizer", category: "Mobile App Tools", isPro: false },
  { id: 29, name: "AAB Size Analyzer", slug: "aab-size-analyzer", category: "Mobile App Tools", isPro: false },
  { id: 30, name: "IPA Size Analyzer", slug: "ipa-size-analyzer", category: "Mobile App Tools", isPro: false },
  { id: 31, name: "App Storage Calculator", slug: "app-storage-calculator", category: "Mobile App Tools", isPro: false },
  { id: 32, name: "App Bandwidth Calculator", slug: "app-bandwidth-calculator", category: "Mobile App Tools", isPro: false },
  { id: 33, name: "Mobile API Cost Calculator", slug: "mobile-api-cost-calculator", category: "Mobile App Tools", isPro: false },
  { id: 34, name: "Push Notification Cost Calculator", slug: "push-notification-cost-calculator", category: "Mobile App Tools", isPro: false },
  { id: 35, name: "Firebase Cost Calculator", slug: "firebase-cost-calculator", category: "Mobile App Tools", isPro: false },
  { id: 36, name: "App Hosting Cost Calculator", slug: "app-hosting-cost-calculator", category: "Mobile App Tools", isPro: false },
  { id: 37, name: "Mobile Backend Cost Calculator", slug: "mobile-backend-cost-calculator", category: "Mobile App Tools", isPro: false },
  { id: 38, name: "App Subscription Revenue Calculator", slug: "app-subscription-revenue-calculator", category: "Mobile App Tools", isPro: false },
  { id: 39, name: "App ARPU Calculator", slug: "app-arpu-calculator", category: "Mobile App Tools", isPro: false },
  { id: 40, name: "App Install Rate Calculator", slug: "app-install-rate-calculator", category: "Mobile App Tools", isPro: false },
  { id: 41, name: "App Crash Rate Calculator", slug: "app-crash-rate-calculator", category: "Mobile App Tools", isPro: false },
  { id: 42, name: "App Session Duration Calculator", slug: "app-session-duration-calculator", category: "Mobile App Tools", isPro: false },
  { id: 43, name: "DAU Calculator", slug: "dau-calculator", category: "Mobile App Tools", isPro: false },
  { id: 44, name: "MAU Calculator", slug: "mau-calculator", category: "Mobile App Tools", isPro: false },
  { id: 45, name: "App Engagement Calculator", slug: "app-engagement-calculator", category: "Mobile App Tools", isPro: false },
  { id: 46, name: "Mobile DPI Calculator", slug: "mobile-dpi-calculator", category: "Mobile App Tools", isPro: false },
  { id: 47, name: "Mobile PPI Calculator", slug: "mobile-ppi-calculator", category: "Mobile App Tools", isPro: false },
  { id: 48, name: "Device Screen Size Calculator", slug: "device-screen-size-calculator", category: "Mobile App Tools", isPro: false },
  { id: 49, name: "Mobile Aspect Ratio Calculator", slug: "mobile-aspect-ratio-calculator", category: "Mobile App Tools", isPro: false },
  { id: 50, name: "Touch Target Size Checker", slug: "touch-target-size-checker", category: "Mobile App Tools", isPro: false },
  { id: 51, name: "Mobile Accessibility Checker", slug: "mobile-accessibility-checker", category: "Mobile App Tools", isPro: false },
  { id: 52, name: "Android Manifest Validator", slug: "android-manifest-validator", category: "Mobile App Tools", isPro: false },
  { id: 53, name: "iOS Info.plist Validator", slug: "ios-info-plist-validator", category: "Mobile App Tools", isPro: false },
  { id: 54, name: "App URL Scheme Generator", slug: "app-url-scheme-generator", category: "Mobile App Tools", isPro: false },
  { id: 55, name: "Universal Link Validator", slug: "universal-link-validator", category: "Mobile App Tools", isPro: false },
  { id: 56, name: "App Bundle Identifier Generator", slug: "app-bundle-identifier-generator", category: "Mobile App Tools", isPro: false },
  { id: 57, name: "Package Name Generator", slug: "package-name-generator", category: "Mobile App Tools", isPro: false },
  { id: 58, name: "App Version Generator", slug: "app-version-generator", category: "Mobile App Tools", isPro: false },
  { id: 59, name: "Version Code Calculator", slug: "version-code-calculator", category: "Mobile App Tools", isPro: false },
  { id: 60, name: "App Release Checklist", slug: "app-release-checklist", category: "Mobile App Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "App QA Checklist", slug: "app-qa-checklist", category: "Mobile App Tools", isPro: true },
  { id: 62, name: "Mobile App Product Workspace", slug: "mobile-app-product-workspace", category: "Mobile App Tools", isPro: true },
  { id: 63, name: "App Release Management Workspace", slug: "app-release-management-workspace", category: "Mobile App Tools", isPro: true },
  { id: 64, name: "ASO Keyword Research Workspace", slug: "aso-keyword-research-workspace", category: "Mobile App Tools", isPro: true },
  { id: 65, name: "App Metadata Optimization Engine", slug: "app-metadata-optimization-engine", category: "Mobile App Tools", isPro: true },
  { id: 66, name: "App Screenshot Optimization Workspace", slug: "app-screenshot-optimization-workspace", category: "Mobile App Tools", isPro: true },
  { id: 67, name: "App Icon Optimization Tool", slug: "app-icon-optimization-tool", category: "Mobile App Tools", isPro: true },
  { id: 68, name: "Mobile App Revenue Dashboard", slug: "mobile-app-revenue-dashboard", category: "Mobile App Tools", isPro: true },
  { id: 69, name: "Mobile App Growth Dashboard", slug: "mobile-app-growth-dashboard", category: "Mobile App Tools", isPro: true },
  { id: 70, name: "App Retention Analytics", slug: "app-retention-analytics", category: "Mobile App Tools", isPro: true },
  { id: 71, name: "App Engagement Analytics", slug: "app-engagement-analytics", category: "Mobile App Tools", isPro: true },
  { id: 72, name: "App Monetization Dashboard", slug: "app-monetization-dashboard", category: "Mobile App Tools", isPro: true },
  { id: 73, name: "Subscription Analytics Workspace", slug: "subscription-analytics-workspace", category: "Mobile App Tools", isPro: true },
  { id: 74, name: "App LTV Analytics", slug: "app-ltv-analytics", category: "Mobile App Tools", isPro: true },
  { id: 75, name: "App CAC Analytics", slug: "app-cac-analytics", category: "Mobile App Tools", isPro: true },
  { id: 76, name: "App Funnel Analytics", slug: "app-funnel-analytics", category: "Mobile App Tools", isPro: true },
  { id: 77, name: "App Conversion Analytics", slug: "app-conversion-analytics", category: "Mobile App Tools", isPro: true },
  { id: 78, name: "Mobile Product Analytics", slug: "mobile-product-analytics", category: "Mobile App Tools", isPro: true },
  { id: 79, name: "Crash Analytics Workspace", slug: "crash-analytics-workspace", category: "Mobile App Tools", isPro: true },
  { id: 80, name: "App Performance Dashboard", slug: "app-performance-dashboard", category: "Mobile App Tools", isPro: true },
  { id: 81, name: "Mobile API Monitoring Workspace", slug: "mobile-api-monitoring-workspace", category: "Mobile App Tools", isPro: true },
  { id: 82, name: "Mobile Backend Cost Dashboard", slug: "mobile-backend-cost-dashboard", category: "Mobile App Tools", isPro: true },
  { id: 83, name: "Firebase Cost Optimization", slug: "firebase-cost-optimization", category: "Mobile App Tools", isPro: true },
  { id: 84, name: "Mobile Cloud Cost Optimization", slug: "mobile-cloud-cost-optimization", category: "Mobile App Tools", isPro: true },
  { id: 85, name: "App Release Calendar", slug: "app-release-calendar", category: "Mobile App Tools", isPro: true },
  { id: 86, name: "Mobile QA Management Workspace", slug: "mobile-qa-management-workspace", category: "Mobile App Tools", isPro: true },
  { id: 87, name: "Test Case Management Workspace", slug: "test-case-management-workspace", category: "Mobile App Tools", isPro: true },
  { id: 88, name: "Device Testing Matrix", slug: "device-testing-matrix", category: "Mobile App Tools", isPro: true },
  { id: 89, name: "Mobile Compatibility Workspace", slug: "mobile-compatibility-workspace", category: "Mobile App Tools", isPro: true },
  { id: 90, name: "App Permission Audit Workspace", slug: "app-permission-audit-workspace", category: "Mobile App Tools", isPro: true },
  { id: 91, name: "Deep Link Management Workspace", slug: "deep-link-management-workspace", category: "Mobile App Tools", isPro: true },
  { id: 92, name: "App Version Management Workspace", slug: "app-version-management-workspace", category: "Mobile App Tools", isPro: true },
  { id: 93, name: "App Localization Workspace", slug: "app-localization-workspace", category: "Mobile App Tools", isPro: true },
  { id: 94, name: "Mobile App Data Importer", slug: "mobile-app-data-importer", category: "Mobile App Tools", isPro: true },
  { id: 95, name: "Mobile Analytics Report Generator", slug: "mobile-analytics-report-generator", category: "Mobile App Tools", isPro: true },
  { id: 96, name: "App Store Data Dashboard", slug: "app-store-data-dashboard", category: "Mobile App Tools", isPro: true },
  { id: 97, name: "Mobile App API Workspace", slug: "mobile-app-api-workspace", category: "Mobile App Tools", isPro: true },
  { id: 98, name: "App Growth Intelligence Platform", slug: "app-growth-intelligence-platform", category: "Mobile App Tools", isPro: true },
  { id: 99, name: "Mobile Product Intelligence Platform", slug: "mobile-product-intelligence-platform", category: "Mobile App Tools", isPro: true },
  { id: 100, name: "Professional Mobile App Command Center", slug: "professional-mobile-app-command-center", category: "Mobile App Tools", isPro: true }
];