export interface NewsMediaTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const newsMediaToolsList: NewsMediaTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "News Search Tool", slug: "news-search-tool", category: "News & Media Tools", isPro: false },
  { id: 2, name: "News Archive Search", slug: "news-archive-search", category: "News & Media Tools", isPro: false },
  { id: 3, name: "Headline Analyzer", slug: "headline-analyzer", category: "News & Media Tools", isPro: false },
  { id: 4, name: "Article Summary Generator", slug: "article-summary-generator", category: "News & Media Tools", isPro: false },
  { id: 5, name: "Article Key Points Extractor", slug: "article-key-points-extractor", category: "News & Media Tools", isPro: false },
  { id: 6, name: "News Keyword Tracker", slug: "news-keyword-tracker", category: "News & Media Tools", isPro: false },
  { id: 7, name: "News Topic Tracker", slug: "news-topic-tracker", category: "News & Media Tools", isPro: false },
  { id: 8, name: "Brand Mention Tracker", slug: "brand-mention-tracker", category: "News & Media Tools", isPro: false },
  { id: 9, name: "Competitor News Tracker", slug: "competitor-news-tracker", category: "News & Media Tools", isPro: false },
  { id: 10, name: "Industry News Tracker", slug: "industry-news-tracker", category: "News & Media Tools", isPro: false },
  { id: 11, name: "RSS Feed Reader", slug: "rss-feed-reader", category: "News & Media Tools", isPro: false },
  { id: 12, name: "RSS Feed Validator", slug: "rss-feed-validator", category: "News & Media Tools", isPro: false },
  { id: 13, name: "RSS Feed Generator", slug: "rss-feed-generator", category: "News & Media Tools", isPro: false },
  { id: 14, name: "News Digest Generator", slug: "news-digest-generator", category: "News & Media Tools", isPro: false },
  { id: 15, name: "News Newsletter Generator", slug: "news-newsletter-generator", category: "News & Media Tools", isPro: false },
  { id: 16, name: "Press Release Generator", slug: "press-release-generator", category: "News & Media Tools", isPro: false },
  { id: 17, name: "Fact-Checking Checklist", slug: "fact-checking-checklist", category: "News & Media Tools", isPro: false },
  { id: 18, name: "Content Freshness Checker", slug: "content-freshness-checker", category: "News & Media Tools", isPro: false },
  { id: 19, name: "News Topic Search", slug: "news-topic-search", category: "News & Media Tools", isPro: false },
  { id: 20, name: "News Source Finder", slug: "news-source-finder", category: "News & Media Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "News Article Finder", slug: "news-article-finder", category: "News & Media Tools", isPro: false },
  { id: 22, name: "Headline Generator", slug: "headline-generator", category: "News & Media Tools", isPro: false },
  { id: 23, name: "Headline Length Checker", slug: "headline-length-checker", category: "News & Media Tools", isPro: false },
  { id: 24, name: "Article Word Count", slug: "article-word-count", category: "News & Media Tools", isPro: false },
  { id: 25, name: "Article Reading Time Calculator", slug: "article-reading-time-calculator", category: "News & Media Tools", isPro: false },
  { id: 26, name: "News Summary Generator", slug: "news-summary-generator", category: "News & Media Tools", isPro: false },
  { id: 27, name: "Article Topic Extractor", slug: "article-topic-extractor", category: "News & Media Tools", isPro: false },
  { id: 28, name: "Article Keyword Extractor", slug: "article-keyword-extractor", category: "News & Media Tools", isPro: false },
  { id: 29, name: "Article Entity Extractor", slug: "article-entity-extractor", category: "News & Media Tools", isPro: false },
  { id: 30, name: "Article Date Extractor", slug: "article-date-extractor", category: "News & Media Tools", isPro: false },
  { id: 31, name: "Article Source Checker", slug: "article-source-checker", category: "News & Media Tools", isPro: false },
  { id: 32, name: "Article URL Analyzer", slug: "article-url-analyzer", category: "News & Media Tools", isPro: false },
  { id: 33, name: "Article Metadata Extractor", slug: "article-metadata-extractor", category: "News & Media Tools", isPro: false },
  { id: 34, name: "News Source Monitor", slug: "news-source-monitor", category: "News & Media Tools", isPro: false },
  { id: 35, name: "News Mention Tracker", slug: "news-mention-tracker", category: "News & Media Tools", isPro: false },
  { id: 36, name: "Company Mention Tracker", slug: "company-mention-tracker", category: "News & Media Tools", isPro: false },
  { id: 37, name: "Market News Tracker", slug: "market-news-tracker", category: "News & Media Tools", isPro: false },
  { id: 38, name: "Technology News Tracker", slug: "technology-news-tracker", category: "News & Media Tools", isPro: false },
  { id: 39, name: "Finance News Tracker", slug: "finance-news-tracker", category: "News & Media Tools", isPro: false },
  { id: 40, name: "Sports News Tracker", slug: "sports-news-tracker", category: "News & Media Tools", isPro: false },
  { id: 41, name: "Local News Tracker", slug: "local-news-tracker", category: "News & Media Tools", isPro: false },
  { id: 42, name: "RSS to Email Converter", slug: "rss-to-email-converter", category: "News & Media Tools", isPro: false },
  { id: 43, name: "RSS to Social Post Generator", slug: "rss-to-social-post-generator", category: "News & Media Tools", isPro: false },
  { id: 44, name: "RSS Feed Merger", slug: "rss-feed-merger", category: "News & Media Tools", isPro: false },
  { id: 45, name: "RSS Feed Filter", slug: "rss-feed-filter", category: "News & Media Tools", isPro: false },
  { id: 46, name: "Daily News Digest", slug: "daily-news-digest", category: "News & Media Tools", isPro: false },
  { id: 47, name: "Weekly News Digest", slug: "weekly-news-digest", category: "News & Media Tools", isPro: false },
  { id: 48, name: "Newsletter Subject Generator", slug: "newsletter-subject-generator", category: "News & Media Tools", isPro: false },
  { id: 49, name: "Press Release Headline Generator", slug: "press-release-headline-generator", category: "News & Media Tools", isPro: false },
  { id: 50, name: "Media Pitch Generator", slug: "media-pitch-generator", category: "News & Media Tools", isPro: false },
  { id: 51, name: "Journalist Pitch Generator", slug: "journalist-pitch-generator", category: "News & Media Tools", isPro: false },
  { id: 52, name: "News Story Outline Generator", slug: "news-story-outline-generator", category: "News & Media Tools", isPro: false },
  { id: 53, name: "News Article Outline Generator", slug: "news-article-outline-generator", category: "News & Media Tools", isPro: false },
  { id: 54, name: "Source Comparison Tool", slug: "source-comparison-tool", category: "News & Media Tools", isPro: false },
  { id: 55, name: "Claim Comparison Tool", slug: "claim-comparison-tool", category: "News & Media Tools", isPro: false },
  { id: 56, name: "Citation Organizer", slug: "citation-organizer", category: "News & Media Tools", isPro: false },
  { id: 57, name: "Media Contact Organizer", slug: "media-contact-organizer", category: "News & Media Tools", isPro: false },
  { id: 58, name: "Editorial Calendar", slug: "editorial-calendar", category: "News & Media Tools", isPro: false },
  { id: 59, name: "News Publishing Checklist", slug: "news-publishing-checklist", category: "News & Media Tools", isPro: false },
  { id: 60, name: "Article Update Tracker", slug: "article-update-tracker", category: "News & Media Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "News Intelligence Dashboard", slug: "news-intelligence-dashboard", category: "News & Media Tools", isPro: true },
  { id: 62, name: "Real-Time Topic Monitoring", slug: "real-time-topic-monitoring", category: "News & Media Tools", isPro: true },
  { id: 63, name: "Breaking News Monitor", slug: "breaking-news-monitor", category: "News & Media Tools", isPro: true },
  { id: 64, name: "Industry Intelligence Monitor", slug: "industry-intelligence-monitor", category: "News & Media Tools", isPro: true },
  { id: 65, name: "Competitor Intelligence Monitor", slug: "competitor-intelligence-monitor", category: "News & Media Tools", isPro: true },
  { id: 66, name: "Brand Reputation News Monitor", slug: "brand-reputation-news-monitor", category: "News & Media Tools", isPro: true },
  { id: 67, name: "Media Mention Analytics", slug: "media-mention-analytics", category: "News & Media Tools", isPro: true },
  { id: 68, name: "News Sentiment Analyzer", slug: "news-sentiment-analyzer", category: "News & Media Tools", isPro: true },
  { id: 69, name: "News Trend Analyzer", slug: "news-trend-analyzer", category: "News & Media Tools", isPro: true },
  { id: 70, name: "Topic Trend Forecast", slug: "topic-trend-forecast", category: "News & Media Tools", isPro: true },
  { id: 71, name: "Story Trend Detector", slug: "story-trend-detector", category: "News & Media Tools", isPro: true },
  { id: 72, name: "Emerging Topic Detector", slug: "emerging-topic-detector", category: "News & Media Tools", isPro: true },
  { id: 73, name: "News Volume Analyzer", slug: "news-volume-analyzer", category: "News & Media Tools", isPro: true },
  { id: 74, name: "Source Bias Comparison Workspace", slug: "source-bias-comparison-workspace", category: "News & Media Tools", isPro: true },
  { id: 75, name: "Multi-Source News Comparison", slug: "multi-source-news-comparison", category: "News & Media Tools", isPro: true },
  { id: 76, name: "News Timeline Builder", slug: "news-timeline-builder", category: "News & Media Tools", isPro: true },
  { id: 77, name: "Event Timeline Generator", slug: "event-timeline-generator", category: "News & Media Tools", isPro: true },
  { id: 78, name: "Story Cluster Analyzer", slug: "story-cluster-analyzer", category: "News & Media Tools", isPro: true },
  { id: 79, name: "Duplicate Story Detector", slug: "duplicate-story-detector", category: "News & Media Tools", isPro: true },
  { id: 80, name: "Similar Article Detector", slug: "similar-article-detector", category: "News & Media Tools", isPro: true },
  { id: 81, name: "Article Originality Analyzer", slug: "article-originality-analyzer", category: "News & Media Tools", isPro: true },
  { id: 82, name: "News Research Workspace", slug: "news-research-workspace", category: "News & Media Tools", isPro: true },
  { id: 83, name: "Journalist Research Workspace", slug: "journalist-research-workspace", category: "News & Media Tools", isPro: true },
  { id: 84, name: "Editorial Planning Workspace", slug: "editorial-planning-workspace", category: "News & Media Tools", isPro: true },
  { id: 85, name: "Newsroom Dashboard", slug: "newsroom-dashboard", category: "News & Media Tools", isPro: true },
  { id: 86, name: "Media Monitoring Workspace", slug: "media-monitoring-workspace", category: "News & Media Tools", isPro: true },
  { id: 87, name: "Press Relations Workspace", slug: "press-relations-workspace", category: "News & Media Tools", isPro: true },
  { id: 88, name: "Newsletter Intelligence Workspace", slug: "newsletter-intelligence-workspace", category: "News & Media Tools", isPro: true },
  { id: 89, name: "News SEO Analyzer", slug: "news-seo-analyzer", category: "News & Media Tools", isPro: true },
  { id: 90, name: "News Article Optimization Workspace", slug: "news-article-optimization-workspace", category: "News & Media Tools", isPro: true },
  { id: 91, name: "Content Update Intelligence", slug: "content-update-intelligence", category: "News & Media Tools", isPro: true },
  { id: 92, name: "News Archive Intelligence", slug: "news-archive-intelligence", category: "News & Media Tools", isPro: true },
  { id: 93, name: "Media Database Workspace", slug: "media-database-workspace", category: "News & Media Tools", isPro: true },
  { id: 94, name: "News API Testing Workspace", slug: "news-api-testing-workspace", category: "News & Media Tools", isPro: true },
  { id: 95, name: "News Data Export Workspace", slug: "news-data-export-workspace", category: "News & Media Tools", isPro: true },
  { id: 96, name: "Enterprise Media Monitoring", slug: "enterprise-media-monitoring", category: "News & Media Tools", isPro: true },
  { id: 97, name: "News Intelligence Platform", slug: "news-intelligence-platform", category: "News & Media Tools", isPro: true },
  { id: 98, name: "Global Media Intelligence Workspace", slug: "global-media-intelligence-workspace", category: "News & Media Tools", isPro: true },
  { id: 99, name: "Editorial Operations Platform", slug: "editorial-operations-platform", category: "News & Media Tools", isPro: true },
  { id: 100, name: "Media Research Command Center", slug: "media-research-command-center", category: "News & Media Tools", isPro: true }
];