export interface NutritionTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const nutritionToolsList: NutritionTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "Calorie Calculator", slug: "calorie-calculator", category: "Nutrition Tools", isPro: false },
  { id: 2, name: "Daily Calorie Needs Calculator", slug: "daily-calorie-needs-calculator", category: "Nutrition Tools", isPro: false },
  { id: 3, name: "BMR Calculator", slug: "bmr-calculator", category: "Nutrition Tools", isPro: false },
  { id: 4, name: "TDEE Calculator", slug: "tdee-calculator", category: "Nutrition Tools", isPro: false },
  { id: 5, name: "Macronutrient Calculator", slug: "macronutrient-calculator", category: "Nutrition Tools", isPro: false },
  { id: 6, name: "Protein Intake Calculator", slug: "protein-intake-calculator", category: "Nutrition Tools", isPro: false },
  { id: 7, name: "Water Intake Calculator", slug: "water-intake-calculator", category: "Nutrition Tools", isPro: false },
  { id: 8, name: "BMI Calculator", slug: "bmi-calculator", category: "Nutrition Tools", isPro: false },
  { id: 9, name: "Calorie Deficit Calculator", slug: "calorie-deficit-calculator", category: "Nutrition Tools", isPro: false },
  { id: 10, name: "Weight Loss Calorie Calculator", slug: "weight-loss-calorie-calculator", category: "Nutrition Tools", isPro: false },
  { id: 11, name: "Recipe Calorie Calculator", slug: "recipe-calorie-calculator", category: "Nutrition Tools", isPro: false },
  { id: 12, name: "Nutrition Label Analyzer", slug: "nutrition-label-analyzer", category: "Nutrition Tools", isPro: false },
  { id: 13, name: "Recipe Nutrition Analyzer", slug: "recipe-nutrition-analyzer", category: "Nutrition Tools", isPro: false },
  { id: 14, name: "Food Portion Calculator", slug: "food-portion-calculator", category: "Nutrition Tools", isPro: false },
  { id: 15, name: "Serving Size Calculator", slug: "serving-size-calculator", category: "Nutrition Tools", isPro: false },
  { id: 16, name: "Grocery Budget Calculator", slug: "grocery-budget-calculator", category: "Nutrition Tools", isPro: false },
  { id: 17, name: "Meal Planner", slug: "meal-planner", category: "Nutrition Tools", isPro: false },
  { id: 18, name: "Weekly Meal Planner", slug: "weekly-meal-planner", category: "Nutrition Tools", isPro: false },
  { id: 19, name: "Grocery List Generator", slug: "grocery-list-generator", category: "Nutrition Tools", isPro: false },
  { id: 20, name: "Meal Prep Calculator", slug: "meal-prep-calculator", category: "Nutrition Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Carbohydrate Intake Calculator", slug: "carbohydrate-intake-calculator", category: "Nutrition Tools", isPro: false },
  { id: 22, name: "Fat Intake Calculator", slug: "fat-intake-calculator", category: "Nutrition Tools", isPro: false },
  { id: 23, name: "Fiber Intake Calculator", slug: "fiber-intake-calculator", category: "Nutrition Tools", isPro: false },
  { id: 24, name: "Ideal Weight Calculator", slug: "ideal-weight-calculator", category: "Nutrition Tools", isPro: false },
  { id: 25, name: "Healthy Weight Range Calculator", slug: "healthy-weight-range-calculator", category: "Nutrition Tools", isPro: false },
  { id: 26, name: "Calorie Surplus Calculator", slug: "calorie-surplus-calculator", category: "Nutrition Tools", isPro: false },
  { id: 27, name: "Weight Gain Calorie Calculator", slug: "weight-gain-calorie-calculator", category: "Nutrition Tools", isPro: false },
  { id: 28, name: "Meal Calorie Calculator", slug: "meal-calorie-calculator", category: "Nutrition Tools", isPro: false },
  { id: 29, name: "Food Cost Calculator", slug: "food-cost-calculator", category: "Nutrition Tools", isPro: false },
  { id: 30, name: "Meal Budget Calculator", slug: "meal-budget-calculator", category: "Nutrition Tools", isPro: false },
  { id: 31, name: "Daily Macro Tracker", slug: "daily-macro-tracker", category: "Nutrition Tools", isPro: false },
  { id: 32, name: "Meal Macro Calculator", slug: "meal-macro-calculator", category: "Nutrition Tools", isPro: false },
  { id: 33, name: "Protein Per Meal Calculator", slug: "protein-per-meal-calculator", category: "Nutrition Tools", isPro: false },
  { id: 34, name: "Net Carb Calculator", slug: "net-carb-calculator", category: "Nutrition Tools", isPro: false },
  { id: 35, name: "Total Carb Calculator", slug: "total-carb-calculator", category: "Nutrition Tools", isPro: false },
  { id: 36, name: "Sugar Intake Calculator", slug: "sugar-intake-calculator", category: "Nutrition Tools", isPro: false },
  { id: 37, name: "Sodium Intake Calculator", slug: "sodium-intake-calculator", category: "Nutrition Tools", isPro: false },
  { id: 38, name: "Cholesterol Intake Calculator", slug: "cholesterol-intake-calculator", category: "Nutrition Tools", isPro: false },
  { id: 39, name: "Added Sugar Calculator", slug: "added-sugar-calculator", category: "Nutrition Tools", isPro: false },
  { id: 40, name: "Fiber Intake Tracker", slug: "fiber-intake-tracker", category: "Nutrition Tools", isPro: false },
  { id: 41, name: "Water Intake Tracker", slug: "water-intake-tracker", category: "Nutrition Tools", isPro: false },
  { id: 42, name: "Food Calorie Lookup", slug: "food-calorie-lookup", category: "Nutrition Tools", isPro: false },
  { id: 43, name: "Food Macro Lookup", slug: "food-macro-lookup", category: "Nutrition Tools", isPro: false },
  { id: 44, name: "Nutrition Label Calculator", slug: "nutrition-label-calculator", category: "Nutrition Tools", isPro: false },
  { id: 45, name: "Recipe Serving Calculator", slug: "recipe-serving-calculator", category: "Nutrition Tools", isPro: false },
  { id: 46, name: "Ingredient Scaling Calculator", slug: "ingredient-scaling-calculator", category: "Nutrition Tools", isPro: false },
  { id: 47, name: "Meal Portion Scaler", slug: "meal-portion-scaler", category: "Nutrition Tools", isPro: false },
  { id: 48, name: "Food Unit Converter", slug: "food-unit-converter", category: "Nutrition Tools", isPro: false },
  { id: 49, name: "Cooking Measurement Converter", slug: "cooking-measurement-converter", category: "Nutrition Tools", isPro: false },
  { id: 50, name: "Recipe Cost Calculator", slug: "recipe-cost-calculator", category: "Nutrition Tools", isPro: false },
  { id: 51, name: "Monthly Meal Planner", slug: "monthly-meal-planner", category: "Nutrition Tools", isPro: false },
  { id: 52, name: "Nutrition Goal Tracker", slug: "nutrition-goal-tracker", category: "Nutrition Tools", isPro: false },
  { id: 53, name: "Weight Goal Calculator", slug: "weight-goal-calculator", category: "Nutrition Tools", isPro: false },
  { id: 54, name: "Nutrition Progress Tracker", slug: "nutrition-progress-tracker", category: "Nutrition Tools", isPro: false },
  { id: 55, name: "Food Journal", slug: "food-journal", category: "Nutrition Tools", isPro: false },
  { id: 56, name: "Meal Journal", slug: "meal-journal", category: "Nutrition Tools", isPro: false },
  { id: 57, name: "Calorie Journal", slug: "calorie-journal", category: "Nutrition Tools", isPro: false },
  { id: 58, name: "Macro Journal", slug: "macro-journal", category: "Nutrition Tools", isPro: false },
  { id: 59, name: "Hydration Journal", slug: "hydration-journal", category: "Nutrition Tools", isPro: false },
  { id: 60, name: "Nutrition Summary Generator", slug: "nutrition-summary-generator", category: "Nutrition Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Personalized Meal Planning Workspace", slug: "personalized-meal-planning-workspace", category: "Nutrition Tools", isPro: true },
  { id: 62, name: "Advanced Macro Planning Engine", slug: "advanced-macro-planning-engine", category: "Nutrition Tools", isPro: true },
  { id: 63, name: "Nutrition Goal Optimization Tool", slug: "nutrition-goal-optimization-tool", category: "Nutrition Tools", isPro: true },
  { id: 64, name: "Weight Management Planning Workspace", slug: "weight-management-planning-workspace", category: "Nutrition Tools", isPro: true },
  { id: 65, name: "Weekly Nutrition Dashboard", slug: "weekly-nutrition-dashboard", category: "Nutrition Tools", isPro: true },
  { id: 66, name: "Monthly Nutrition Dashboard", slug: "monthly-nutrition-dashboard", category: "Nutrition Tools", isPro: true },
  { id: 67, name: "Meal Prep Planning Workspace", slug: "meal-prep-planning-workspace", category: "Nutrition Tools", isPro: true },
  { id: 68, name: "Grocery Optimization Engine", slug: "grocery-optimization-engine", category: "Nutrition Tools", isPro: true },
  { id: 69, name: "Grocery Cost Optimization Tool", slug: "grocery-cost-optimization-tool", category: "Nutrition Tools", isPro: true },
  { id: 70, name: "Recipe Optimization Engine", slug: "recipe-optimization-engine", category: "Nutrition Tools", isPro: true },
  { id: 71, name: "Recipe Nutrition Optimization Tool", slug: "recipe-nutrition-optimization-tool", category: "Nutrition Tools", isPro: true },
  { id: 72, name: "Multi-Recipe Nutrition Analyzer", slug: "multi-recipe-nutrition-analyzer", category: "Nutrition Tools", isPro: true },
  { id: 73, name: "Meal Combination Analyzer", slug: "meal-combination-analyzer", category: "Nutrition Tools", isPro: true },
  { id: 74, name: "Daily Nutrition Balance Analyzer", slug: "daily-nutrition-balance-analyzer", category: "Nutrition Tools", isPro: true },
  { id: 75, name: "Weekly Nutrition Balance Analyzer", slug: "weekly-nutrition-balance-analyzer", category: "Nutrition Tools", isPro: true },
  { id: 76, name: "Nutrient Intake Dashboard", slug: "nutrient-intake-dashboard", category: "Nutrition Tools", isPro: true },
  { id: 77, name: "Micronutrient Tracking Workspace", slug: "micronutrient-tracking-workspace", category: "Nutrition Tools", isPro: true },
  { id: 78, name: "Dietary Pattern Analyzer", slug: "dietary-pattern-analyzer", category: "Nutrition Tools", isPro: true },
  { id: 79, name: "Food Preference Planner", slug: "food-preference-planner", category: "Nutrition Tools", isPro: true },
  { id: 80, name: "Dietary Restriction Meal Planner", slug: "dietary-restriction-meal-planner", category: "Nutrition Tools", isPro: true },
  { id: 81, name: "Allergy-Aware Meal Planning Workspace", slug: "allergy-aware-meal-planning-workspace", category: "Nutrition Tools", isPro: true },
  { id: 82, name: "Family Meal Planning Workspace", slug: "family-meal-planning-workspace", category: "Nutrition Tools", isPro: true },
  { id: 83, name: "Bulk Meal Prep Planner", slug: "bulk-meal-prep-planner", category: "Nutrition Tools", isPro: true },
  { id: 84, name: "Meal Calendar Workspace", slug: "meal-calendar-workspace", category: "Nutrition Tools", isPro: true },
  { id: 85, name: "Grocery Inventory Workspace", slug: "grocery-inventory-workspace", category: "Nutrition Tools", isPro: true },
  { id: 86, name: "Pantry Management Workspace", slug: "pantry-management-workspace", category: "Nutrition Tools", isPro: true },
  { id: 87, name: "Food Cost Intelligence Dashboard", slug: "food-cost-intelligence-dashboard", category: "Nutrition Tools", isPro: true },
  { id: 88, name: "Nutrition Data Import Workspace", slug: "nutrition-data-import-workspace", category: "Nutrition Tools", isPro: true },
  { id: 89, name: "Nutrition CSV Analyzer", slug: "nutrition-csv-analyzer", category: "Nutrition Tools", isPro: true },
  { id: 90, name: "Nutrition Report Generator", slug: "nutrition-report-generator", category: "Nutrition Tools", isPro: true },
  { id: 91, name: "Nutrition Progress Analytics", slug: "nutrition-progress-analytics", category: "Nutrition Tools", isPro: true },
  { id: 92, name: "Food Journal Analytics", slug: "food-journal-analytics", category: "Nutrition Tools", isPro: true },
  { id: 93, name: "Meal Planning Automation Workspace", slug: "meal-planning-automation-workspace", category: "Nutrition Tools", isPro: true },
  { id: 94, name: "Nutrition API Workspace", slug: "nutrition-api-workspace", category: "Nutrition Tools", isPro: true },
  { id: 95, name: "Nutrition Database Workspace", slug: "nutrition-database-workspace", category: "Nutrition Tools", isPro: true },
  { id: 96, name: "Professional Nutrition Planning Workspace", slug: "professional-nutrition-planning-workspace", category: "Nutrition Tools", isPro: true },
  { id: 97, name: "Nutrition Business Dashboard", slug: "nutrition-business-dashboard", category: "Nutrition Tools", isPro: true },
  { id: 98, name: "Nutrition Coaching Workspace", slug: "nutrition-coaching-workspace", category: "Nutrition Tools", isPro: true },
  { id: 99, name: "Nutrition Intelligence Platform", slug: "nutrition-intelligence-platform", category: "Nutrition Tools", isPro: true },
  { id: 100, name: "Nutrition Operations Command Center", slug: "nutrition-operations-command-center", category: "Nutrition Tools", isPro: true }
];