export interface OsTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const osToolsList: OsTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "File Hash Generator", slug: "file-hash-generator", category: "Operating System Tools", isPro: false },
  { id: 2, name: "SHA-256 Hash Generator", slug: "sha-256-hash-generator", category: "Operating System Tools", isPro: false },
  { id: 3, name: "File Checksum Validator", slug: "file-checksum-validator", category: "Operating System Tools", isPro: false },
  { id: 4, name: "Disk Space Calculator", slug: "disk-space-calculator", category: "Operating System Tools", isPro: false },
  { id: 5, name: "Storage Capacity Calculator", slug: "storage-capacity-calculator", category: "Operating System Tools", isPro: false },
  { id: 6, name: "Data Transfer Time Calculator", slug: "data-transfer-time-calculator", category: "Operating System Tools", isPro: false },
  { id: 7, name: "Download Time Calculator", slug: "download-time-calculator", category: "Operating System Tools", isPro: false },
  { id: 8, name: "Upload Time Calculator", slug: "upload-time-calculator", category: "Operating System Tools", isPro: false },
  { id: 9, name: "Backup Storage Calculator", slug: "backup-storage-calculator", category: "Operating System Tools", isPro: false },
  { id: 10, name: "RAID Capacity Calculator", slug: "raid-capacity-calculator", category: "Operating System Tools", isPro: false },
  { id: 11, name: "SSD Endurance Calculator", slug: "ssd-endurance-calculator", category: "Operating System Tools", isPro: false },
  { id: 12, name: "Partition Size Calculator", slug: "partition-size-calculator", category: "Operating System Tools", isPro: false },
  { id: 13, name: "Battery Runtime Calculator", slug: "battery-runtime-calculator", category: "Operating System Tools", isPro: false },
  { id: 14, name: "Power Consumption Calculator", slug: "power-consumption-calculator", category: "Operating System Tools", isPro: false },
  { id: 15, name: "chmod Calculator", slug: "chmod-calculator", category: "Operating System Tools", isPro: false },
  { id: 16, name: "Unix Timestamp Tool", slug: "unix-timestamp-tool", category: "Operating System Tools", isPro: false },
  { id: 17, name: "Base64 File Encoder", slug: "base64-file-encoder", category: "Operating System Tools", isPro: false },
  { id: 18, name: "MIME Type Lookup", slug: "mime-type-lookup", category: "Operating System Tools", isPro: false },
  { id: 19, name: "System Performance Dashboard", slug: "system-performance-dashboard", category: "Operating System Tools", isPro: true },
  { id: 20, name: "Hardware Inventory Workspace", slug: "hardware-inventory-workspace", category: "Operating System Tools", isPro: true },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "MD5 Hash Generator", slug: "md5-hash-generator", category: "Operating System Tools", isPro: false },
  { id: 22, name: "SHA-1 Hash Generator", slug: "sha-1-hash-generator", category: "Operating System Tools", isPro: false },
  { id: 23, name: "SHA-512 Hash Generator", slug: "sha-512-hash-generator", category: "Operating System Tools", isPro: false },
  { id: 24, name: "File Size Converter", slug: "file-size-converter", category: "Operating System Tools", isPro: false },
  { id: 25, name: "Folder Size Calculator", slug: "folder-size-calculator", category: "Operating System Tools", isPro: false },
  { id: 26, name: "File Size Calculator", slug: "file-size-calculator", category: "Operating System Tools", isPro: false },
  { id: 27, name: "CPU Usage Calculator", slug: "cpu-usage-calculator", category: "Operating System Tools", isPro: false },
  { id: 28, name: "RAM Usage Calculator", slug: "ram-usage-calculator", category: "Operating System Tools", isPro: false },
  { id: 29, name: "Memory Conversion Tool", slug: "memory-conversion-tool", category: "Operating System Tools", isPro: false },
  { id: 30, name: "Disk Usage Calculator", slug: "disk-usage-calculator", category: "Operating System Tools", isPro: false },
  { id: 31, name: "Storage Planning Calculator", slug: "storage-planning-calculator", category: "Operating System Tools", isPro: false },
  { id: 32, name: "Backup Frequency Calculator", slug: "backup-frequency-calculator", category: "Operating System Tools", isPro: false },
  { id: 33, name: "RAID Storage Calculator", slug: "raid-storage-calculator", category: "Operating System Tools", isPro: false },
  { id: 34, name: "RAID Level Comparison", slug: "raid-level-comparison", category: "Operating System Tools", isPro: false },
  { id: 35, name: "Hard Drive Capacity Calculator", slug: "hard-drive-capacity-calculator", category: "Operating System Tools", isPro: false },
  { id: 36, name: "Swap Size Calculator", slug: "swap-size-calculator", category: "Operating System Tools", isPro: false },
  { id: 37, name: "Virtual Memory Calculator", slug: "virtual-memory-calculator", category: "Operating System Tools", isPro: false },
  { id: 38, name: "Screen Resolution Calculator", slug: "screen-resolution-calculator", category: "Operating System Tools", isPro: false },
  { id: 39, name: "Screen DPI Calculator", slug: "screen-dpi-calculator", category: "Operating System Tools", isPro: false },
  { id: 40, name: "Monitor PPI Calculator", slug: "monitor-ppi-calculator", category: "Operating System Tools", isPro: false },
  { id: 41, name: "Display Scaling Calculator", slug: "display-scaling-calculator", category: "Operating System Tools", isPro: false },
  { id: 42, name: "Battery Capacity Converter", slug: "battery-capacity-converter", category: "Operating System Tools", isPro: false },
  { id: 43, name: "Electricity Usage Calculator", slug: "electricity-usage-calculator", category: "Operating System Tools", isPro: false },
  { id: 44, name: "Computer Power Cost Calculator", slug: "computer-power-cost-calculator", category: "Operating System Tools", isPro: false },
  { id: 45, name: "File Permission Calculator", slug: "file-permission-calculator", category: "Operating System Tools", isPro: false },
  { id: 46, name: "Linux Permission Converter", slug: "linux-permission-converter", category: "Operating System Tools", isPro: false },
  { id: 47, name: "Process Priority Calculator", slug: "process-priority-calculator", category: "Operating System Tools", isPro: false },
  { id: 48, name: "CPU Core Calculator", slug: "cpu-core-calculator", category: "Operating System Tools", isPro: false },
  { id: 49, name: "Thread Count Calculator", slug: "thread-count-calculator", category: "Operating System Tools", isPro: false },
  { id: 50, name: "System Uptime Calculator", slug: "system-uptime-calculator", category: "Operating System Tools", isPro: false },
  { id: 51, name: "Boot Time Calculator", slug: "boot-time-calculator", category: "Operating System Tools", isPro: false },
  { id: 52, name: "Path Formatter", slug: "path-formatter", category: "Operating System Tools", isPro: false },
  { id: 53, name: "File Path Converter", slug: "file-path-converter", category: "Operating System Tools", isPro: false },
  { id: 54, name: "Line Ending Converter", slug: "line-ending-converter", category: "Operating System Tools", isPro: false },
  { id: 55, name: "Text Encoding Converter", slug: "text-encoding-converter", category: "Operating System Tools", isPro: false },
  { id: 56, name: "Base64 File Decoder", slug: "base64-file-decoder", category: "Operating System Tools", isPro: false },
  { id: 57, name: "Archive Size Calculator", slug: "archive-size-calculator", category: "Operating System Tools", isPro: false },
  { id: 58, name: "Compression Ratio Calculator", slug: "compression-ratio-calculator", category: "Operating System Tools", isPro: false },
  { id: 59, name: "File Extension Finder", slug: "file-extension-finder", category: "Operating System Tools", isPro: false },
  { id: 60, name: "System Information Formatter", slug: "system-information-formatter", category: "Operating System Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Environment Variable Formatter", slug: "environment-variable-formatter", category: "Operating System Tools", isPro: true },
  { id: 62, name: "Command History Organizer", slug: "command-history-organizer", category: "Operating System Tools", isPro: true },
  { id: 63, name: "Storage Management Workspace", slug: "storage-management-workspace", category: "Operating System Tools", isPro: true },
  { id: 64, name: "Disk Health Dashboard", slug: "disk-health-dashboard", category: "Operating System Tools", isPro: true },
  { id: 65, name: "Backup Planning Workspace", slug: "backup-planning-workspace", category: "Operating System Tools", isPro: true },
  { id: 66, name: "Backup Strategy Analyzer", slug: "backup-strategy-analyzer", category: "Operating System Tools", isPro: true },
  { id: 67, name: "RAID Planning Workspace", slug: "raid-planning-workspace", category: "Operating System Tools", isPro: true },
  { id: 68, name: "Storage Optimization Engine", slug: "storage-optimization-engine", category: "Operating System Tools", isPro: true },
  { id: 69, name: "Server Storage Planner", slug: "server-storage-planner", category: "Operating System Tools", isPro: true },
  { id: 70, name: "Workstation Performance Analyzer", slug: "workstation-performance-analyzer", category: "Operating System Tools", isPro: true },
  { id: 71, name: "CPU Performance Workspace", slug: "cpu-performance-workspace", category: "Operating System Tools", isPro: true },
  { id: 72, name: "Memory Performance Analyzer", slug: "memory-performance-analyzer", category: "Operating System Tools", isPro: true },
  { id: 73, name: "Disk Performance Analyzer", slug: "disk-performance-analyzer", category: "Operating System Tools", isPro: true },
  { id: 74, name: "System Resource Dashboard", slug: "system-resource-dashboard", category: "Operating System Tools", isPro: true },
  { id: 75, name: "Battery Health Workspace", slug: "battery-health-workspace", category: "Operating System Tools", isPro: true },
  { id: 76, name: "Power Consumption Dashboard", slug: "power-consumption-dashboard", category: "Operating System Tools", isPro: true },
  { id: 77, name: "Application Resource Analyzer", slug: "application-resource-analyzer", category: "Operating System Tools", isPro: true },
  { id: 78, name: "Process Monitoring Workspace", slug: "process-monitoring-workspace", category: "Operating System Tools", isPro: true },
  { id: 79, name: "System Log Analyzer", slug: "system-log-analyzer", category: "Operating System Tools", isPro: true },
  { id: 80, name: "Log File Intelligence Workspace", slug: "log-file-intelligence-workspace", category: "Operating System Tools", isPro: true },
  { id: 81, name: "File Permission Audit Workspace", slug: "file-permission-audit-workspace", category: "Operating System Tools", isPro: true },
  { id: 82, name: "Linux Administration Workspace", slug: "linux-administration-workspace", category: "Operating System Tools", isPro: true },
  { id: 83, name: "Windows Administration Workspace", slug: "windows-administration-workspace", category: "Operating System Tools", isPro: true },
  { id: 84, name: "macOS Administration Workspace", slug: "macos-administration-workspace", category: "Operating System Tools", isPro: true },
  { id: 85, name: "Cross-Platform System Workspace", slug: "cross-platform-system-workspace", category: "Operating System Tools", isPro: true },
  { id: 86, name: "System Configuration Workspace", slug: "system-configuration-workspace", category: "Operating System Tools", isPro: true },
  { id: 87, name: "Environment Configuration Manager", slug: "environment-configuration-manager", category: "Operating System Tools", isPro: true },
  { id: 88, name: "System Backup Dashboard", slug: "system-backup-dashboard", category: "Operating System Tools", isPro: true },
  { id: 89, name: "Disaster Recovery Planner", slug: "disaster-recovery-planner", category: "Operating System Tools", isPro: true },
  { id: 90, name: "System Migration Planner", slug: "system-migration-planner", category: "Operating System Tools", isPro: true },
  { id: 91, name: "Server Migration Workspace", slug: "server-migration-workspace", category: "Operating System Tools", isPro: true },
  { id: 92, name: "System Data Importer", slug: "system-data-importer", category: "Operating System Tools", isPro: true },
  { id: 93, name: "System Data Exporter", slug: "system-data-exporter", category: "Operating System Tools", isPro: true },
  { id: 94, name: "IT Asset Management Workspace", slug: "it-asset-management-workspace", category: "Operating System Tools", isPro: true },
  { id: 95, name: "Endpoint Inventory Dashboard", slug: "endpoint-inventory-dashboard", category: "Operating System Tools", isPro: true },
  { id: 96, name: "System Automation Workspace", slug: "system-automation-workspace", category: "Operating System Tools", isPro: true },
  { id: 97, name: "System Administration API", slug: "system-administration-api", category: "Operating System Tools", isPro: true },
  { id: 98, name: "Infrastructure Operations Dashboard", slug: "infrastructure-operations-dashboard", category: "Operating System Tools", isPro: true },
  { id: 99, name: "System Intelligence Platform", slug: "system-intelligence-platform", category: "Operating System Tools", isPro: true },
  { id: 100, name: "Professional IT Operations Command Center", slug: "professional-it-operations-command-center", category: "Operating System Tools", isPro: true }
];