export interface ParentingTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const parentingToolsList: ParentingTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "Baby Age Calculator", slug: "baby-age-calculator", category: "Parenting Tools", isPro: false },
  { id: 2, name: "Pregnancy Due Date Calculator", slug: "pregnancy-due-date-calculator", category: "Parenting Tools", isPro: false },
  { id: 3, name: "Pregnancy Week Calculator", slug: "pregnancy-week-calculator", category: "Parenting Tools", isPro: false },
  { id: 4, name: "Baby Milestone Tracker", slug: "baby-milestone-tracker", category: "Parenting Tools", isPro: false },
  { id: 5, name: "Baby Sleep Tracker", slug: "baby-sleep-tracker", category: "Parenting Tools", isPro: false },
  { id: 6, name: "Baby Feeding Tracker", slug: "baby-feeding-tracker", category: "Parenting Tools", isPro: false },
  { id: 7, name: "Baby Growth Tracker", slug: "baby-growth-tracker", category: "Parenting Tools", isPro: false },
  { id: 8, name: "Child Growth Tracker", slug: "child-growth-tracker", category: "Parenting Tools", isPro: false },
  { id: 9, name: "Childcare Cost Calculator", slug: "childcare-cost-calculator", category: "Parenting Tools", isPro: false },
  { id: 10, name: "Daycare Cost Calculator", slug: "daycare-cost-calculator", category: "Parenting Tools", isPro: false },
  { id: 11, name: "Family Budget Calculator", slug: "family-budget-calculator", category: "Parenting Tools", isPro: false },
  { id: 12, name: "Family Calendar", slug: "family-calendar", category: "Parenting Tools", isPro: false },
  { id: 13, name: "Baby Routine Planner", slug: "baby-routine-planner", category: "Parenting Tools", isPro: false },
  { id: 14, name: "Bedtime Planner", slug: "bedtime-planner", category: "Parenting Tools", isPro: false },
  { id: 15, name: "Feeding Schedule Planner", slug: "feeding-schedule-planner", category: "Parenting Tools", isPro: false },
  { id: 16, name: "Babysitter Checklist", slug: "babysitter-checklist", category: "Parenting Tools", isPro: false },
  { id: 17, name: "Hospital Bag Checklist", slug: "hospital-bag-checklist", category: "Parenting Tools", isPro: false },
  { id: 18, name: "Chore Chart Generator", slug: "chore-chart-generator", category: "Parenting Tools", isPro: false },
  { id: 19, name: "Screen Time Planner", slug: "screen-time-planner", category: "Parenting Tools", isPro: false },
  { id: 20, name: "Family Management Workspace", slug: "family-management-workspace", category: "Parenting Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Child Age Calculator", slug: "child-age-calculator", category: "Parenting Tools", isPro: false },
  { id: 22, name: "Pregnancy Countdown", slug: "pregnancy-countdown", category: "Parenting Tools", isPro: false },
  { id: 23, name: "Child Milestone Tracker", slug: "child-milestone-tracker", category: "Parenting Tools", isPro: false },
  { id: 24, name: "Baby Diaper Tracker", slug: "baby-diaper-tracker", category: "Parenting Tools", isPro: false },
  { id: 25, name: "Height Percentile Calculator", slug: "height-percentile-calculator", category: "Parenting Tools", isPro: false },
  { id: 26, name: "Weight Percentile Calculator", slug: "weight-percentile-calculator", category: "Parenting Tools", isPro: false },
  { id: 27, name: "Growth Chart Tool", slug: "growth-chart-tool", category: "Parenting Tools", isPro: false },
  { id: 28, name: "Baby Name Generator", slug: "baby-name-generator", category: "Parenting Tools", isPro: false },
  { id: 29, name: "Baby Name Finder", slug: "baby-name-finder", category: "Parenting Tools", isPro: false },
  { id: 30, name: "Baby Name Meaning Finder", slug: "baby-name-meaning-finder", category: "Parenting Tools", isPro: false },
  { id: 31, name: "Baby Name Popularity Tool", slug: "baby-name-popularity-tool", category: "Parenting Tools", isPro: false },
  { id: 32, name: "Sibling Name Matcher", slug: "sibling-name-matcher", category: "Parenting Tools", isPro: false },
  { id: 33, name: "Baby Budget Calculator", slug: "baby-budget-calculator", category: "Parenting Tools", isPro: false },
  { id: 34, name: "Babysitter Cost Calculator", slug: "babysitter-cost-calculator", category: "Parenting Tools", isPro: false },
  { id: 35, name: "Child Education Cost Calculator", slug: "child-education-cost-calculator", category: "Parenting Tools", isPro: false },
  { id: 36, name: "Child Allowance Calculator", slug: "child-allowance-calculator", category: "Parenting Tools", isPro: false },
  { id: 37, name: "School Cost Calculator", slug: "school-cost-calculator", category: "Parenting Tools", isPro: false },
  { id: 38, name: "School Commute Calculator", slug: "school-commute-calculator", category: "Parenting Tools", isPro: false },
  { id: 39, name: "School Calendar Planner", slug: "school-calendar-planner", category: "Parenting Tools", isPro: false },
  { id: 40, name: "Family Schedule Planner", slug: "family-schedule-planner", category: "Parenting Tools", isPro: false },
  { id: 41, name: "Toddler Routine Planner", slug: "toddler-routine-planner", category: "Parenting Tools", isPro: false },
  { id: 42, name: "Child Routine Planner", slug: "child-routine-planner", category: "Parenting Tools", isPro: false },
  { id: 43, name: "Nap Schedule Planner", slug: "nap-schedule-planner", category: "Parenting Tools", isPro: false },
  { id: 44, name: "Diaper Schedule Tracker", slug: "diaper-schedule-tracker", category: "Parenting Tools", isPro: false },
  { id: 45, name: "Pediatric Appointment Planner", slug: "pediatric-appointment-planner", category: "Parenting Tools", isPro: false },
  { id: 46, name: "Vaccination Record Organizer", slug: "vaccination-record-organizer", category: "Parenting Tools", isPro: false },
  { id: 47, name: "Child Medical Record Organizer", slug: "child-medical-record-organizer", category: "Parenting Tools", isPro: false },
  { id: 48, name: "Emergency Contact Card", slug: "emergency-contact-card", category: "Parenting Tools", isPro: false },
  { id: 49, name: "Babysitter Information Sheet", slug: "babysitter-information-sheet", category: "Parenting Tools", isPro: false },
  { id: 50, name: "Baby Packing Checklist", slug: "baby-packing-checklist", category: "Parenting Tools", isPro: false },
  { id: 51, name: "Daycare Packing Checklist", slug: "daycare-packing-checklist", category: "Parenting Tools", isPro: false },
  { id: 52, name: "School Packing Checklist", slug: "school-packing-checklist", category: "Parenting Tools", isPro: false },
  { id: 53, name: "Family Travel Checklist", slug: "family-travel-checklist", category: "Parenting Tools", isPro: false },
  { id: 54, name: "Family Chore Planner", slug: "family-chore-planner", category: "Parenting Tools", isPro: false },
  { id: 55, name: "Reward Chart Generator", slug: "reward-chart-generator", category: "Parenting Tools", isPro: false },
  { id: 56, name: "Homework Schedule Planner", slug: "homework-schedule-planner", category: "Parenting Tools", isPro: false },
  { id: 57, name: "Family Meal Planner", slug: "family-meal-planner", category: "Parenting Tools", isPro: false },
  { id: 58, name: "Lunchbox Planner", slug: "lunchbox-planner", category: "Parenting Tools", isPro: false },
  { id: 59, name: "School Supply Checklist", slug: "school-supply-checklist", category: "Parenting Tools", isPro: false },
  { id: 60, name: "Birthday Party Planner", slug: "birthday-party-planner", category: "Parenting Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Multi-Child Dashboard", slug: "multi-child-dashboard", category: "Parenting Tools", isPro: true },
  { id: 62, name: "Child Development Journal", slug: "child-development-journal", category: "Parenting Tools", isPro: true },
  { id: 63, name: "Baby Milestone Analytics", slug: "baby-milestone-analytics", category: "Parenting Tools", isPro: true },
  { id: 64, name: "Growth Tracking Dashboard", slug: "growth-tracking-dashboard", category: "Parenting Tools", isPro: true },
  { id: 65, name: "Family Calendar Workspace", slug: "family-calendar-workspace", category: "Parenting Tools", isPro: true },
  { id: 66, name: "Family Routine Optimization Tool", slug: "family-routine-optimization-tool", category: "Parenting Tools", isPro: true },
  { id: 67, name: "Household Task Management Workspace", slug: "household-task-management-workspace", category: "Parenting Tools", isPro: true },
  { id: 68, name: "Family Budget Workspace", slug: "family-budget-workspace", category: "Parenting Tools", isPro: true },
  { id: 69, name: "Childcare Budget Planner", slug: "childcare-budget-planner", category: "Parenting Tools", isPro: true },
  { id: 70, name: "Education Cost Planning Workspace", slug: "education-cost-planning-workspace", category: "Parenting Tools", isPro: true },
  { id: 71, name: "School Comparison Workspace", slug: "school-comparison-workspace", category: "Parenting Tools", isPro: true },
  { id: 72, name: "Child Activity Planner", slug: "child-activity-planner", category: "Parenting Tools", isPro: true },
  { id: 73, name: "School Year Planner", slug: "school-year-planner", category: "Parenting Tools", isPro: true },
  { id: 74, name: "Homework Management Workspace", slug: "homework-management-workspace", category: "Parenting Tools", isPro: true },
  { id: 75, name: "Family Meal Planning Workspace", slug: "family-meal-planning-workspace", category: "Parenting Tools", isPro: true },
  { id: 76, name: "Child Nutrition Planning Workspace", slug: "child-nutrition-planning-workspace", category: "Parenting Tools", isPro: true },
  { id: 77, name: "Parenting Routine Builder", slug: "parenting-routine-builder", category: "Parenting Tools", isPro: true },
  { id: 78, name: "Bedtime Routine Optimization Tool", slug: "bedtime-routine-optimization-tool", category: "Parenting Tools", isPro: true },
  { id: 79, name: "Screen Time Management Workspace", slug: "screen-time-management-workspace", category: "Parenting Tools", isPro: true },
  { id: 80, name: "Chore Management Dashboard", slug: "chore-management-dashboard", category: "Parenting Tools", isPro: true },
  { id: 81, name: "Family Reward System Workspace", slug: "family-reward-system-workspace", category: "Parenting Tools", isPro: true },
  { id: 82, name: "Babysitter Management Workspace", slug: "babysitter-management-workspace", category: "Parenting Tools", isPro: true },
  { id: 83, name: "Daycare Management Workspace", slug: "daycare-management-workspace", category: "Parenting Tools", isPro: true },
  { id: 84, name: "Child Emergency Information Workspace", slug: "child-emergency-information-workspace", category: "Parenting Tools", isPro: true },
  { id: 85, name: "Family Document Organizer", slug: "family-document-organizer", category: "Parenting Tools", isPro: true },
  { id: 86, name: "Child Medical Record Workspace", slug: "child-medical-record-workspace", category: "Parenting Tools", isPro: true },
  { id: 87, name: "Vaccination Record Workspace", slug: "vaccination-record-workspace", category: "Parenting Tools", isPro: true },
  { id: 88, name: "Family Travel Planning Workspace", slug: "family-travel-planning-workspace", category: "Parenting Tools", isPro: true },
  { id: 89, name: "Birthday/Event Planning Workspace", slug: "birthday-event-planning-workspace", category: "Parenting Tools", isPro: true },
  { id: 90, name: "Family Shopping Planner", slug: "family-shopping-planner", category: "Parenting Tools", isPro: true },
  { id: 91, name: "School Preparation Workspace", slug: "school-preparation-workspace", category: "Parenting Tools", isPro: true },
  { id: 92, name: "Parenting Journal Workspace", slug: "parenting-journal-workspace", category: "Parenting Tools", isPro: true },
  { id: 93, name: "Family Communication Workspace", slug: "family-communication-workspace", category: "Parenting Tools", isPro: true },
  { id: 94, name: "Co-Parenting Schedule Workspace", slug: "co-parenting-schedule-workspace", category: "Parenting Tools", isPro: true },
  { id: 95, name: "Family Productivity Dashboard", slug: "family-productivity-dashboard", category: "Parenting Tools", isPro: true },
  { id: 96, name: "Parenting Analytics Workspace", slug: "parenting-analytics-workspace", category: "Parenting Tools", isPro: true },
  { id: 97, name: "Family Operations Platform", slug: "family-operations-platform", category: "Parenting Tools", isPro: true },
  { id: 98, name: "Parenting Intelligence Platform", slug: "parenting-intelligence-platform", category: "Parenting Tools", isPro: true },
  { id: 99, name: "Family Event Planner", slug: "family-event-planner", category: "Parenting Tools", isPro: true },
  { id: 100, name: "Family Command Center", slug: "family-command-center", category: "Parenting Tools", isPro: true }
];