export interface PayrollCompensationTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const payrollCompensationToolsList: PayrollCompensationTool[] = [
  // --- 🔥 PRIORITY 20 FREE TOOLS (IDs 1-20 | isPro: false) ---
  { id: 1, name: "Total Compensation Calculator", slug: "total-compensation-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 2, name: "Employer Payroll Cost Calculator", slug: "employer-payroll-cost-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 3, name: "Overtime Pay Calculator", slug: "overtime-pay-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 4, name: "Commission Pay Calculator", slug: "commission-pay-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 5, name: "Bonus Calculator", slug: "bonus-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 6, name: "Salary Increase Calculator", slug: "salary-increase-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 7, name: "Promotion Increase Calculator", slug: "promotion-increase-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 8, name: "Pay Ratio Calculator", slug: "pay-ratio-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 9, name: "Compa-Ratio Calculator", slug: "compa-ratio-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 10, name: "Salary Range Calculator", slug: "salary-range-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 11, name: "Pay Band Calculator", slug: "pay-band-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 12, name: "Compensation Benchmark Calculator", slug: "compensation-benchmark-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 13, name: "Pay Equity Comparison Calculator", slug: "pay-equity-comparison-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 14, name: "Bonus Pool Calculator", slug: "bonus-pool-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 15, name: "Equity Grant Calculator", slug: "equity-grant-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 16, name: "Vesting Schedule Calculator", slug: "vesting-schedule-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 17, name: "Compensation Budget Calculator", slug: "compensation-budget-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 18, name: "Compensation Scenario Calculator", slug: "compensation-scenario-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 19, name: "Gross Pay Planner", slug: "gross-pay-planner", category: "Payroll & Compensation Tools", isPro: false },
  { id: 20, name: "Net Pay Estimator", slug: "net-pay-estimator", category: "Payroll & Compensation Tools", isPro: false },

  // --- REMAINING 40 CORE FREE TOOLS (IDs 21-60 | isPro: false) ---
  { id: 21, name: "Pay Period Calculator", slug: "pay-period-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 22, name: "Annual Salary Breakdown", slug: "annual-salary-breakdown", category: "Payroll & Compensation Tools", isPro: false },
  { id: 23, name: "Hourly-to-Salary Converter", slug: "hourly-to-salary-converter", category: "Payroll & Compensation Tools", isPro: false },
  { id: 24, name: "Salary-to-Hourly Converter", slug: "salary-to-hourly-converter", category: "Payroll & Compensation Tools", isPro: false },
  { id: 25, name: "Monthly-to-Annual Pay Calculator", slug: "monthly-to-annual-pay-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 26, name: "Annual-to-Monthly Pay Calculator", slug: "annual-to-monthly-pay-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 27, name: "Weekly Pay Calculator", slug: "weekly-pay-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 28, name: "Biweekly Pay Calculator", slug: "biweekly-pay-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 29, name: "Semi-Monthly Pay Calculator", slug: "semi-monthly-pay-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 30, name: "Daily Pay Calculator", slug: "daily-pay-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 31, name: "Working Days Pay Calculator", slug: "working-days-pay-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 32, name: "Double-Time Pay Calculator", slug: "double-time-pay-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 33, name: "Shift Differential Calculator", slug: "shift-differential-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 34, name: "Holiday Pay Calculator", slug: "holiday-pay-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 35, name: "Weekend Pay Calculator", slug: "weekend-pay-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 36, name: "Night Shift Pay Calculator", slug: "night-shift-pay-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 37, name: "Performance Bonus Calculator", slug: "performance-bonus-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 38, name: "Annual Bonus Planner", slug: "annual-bonus-planner", category: "Payroll & Compensation Tools", isPro: false },
  { id: 39, name: "Merit Increase Calculator", slug: "merit-increase-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 40, name: "Compensation Change Calculator", slug: "compensation-change-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 41, name: "Employee Cost Calculator", slug: "employee-cost-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 42, name: "Payroll Tax Cost Estimator", slug: "payroll-tax-cost-estimator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 43, name: "Benefits Cost Calculator", slug: "benefits-cost-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 44, name: "Employer Benefits Calculator", slug: "employer-benefits-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 45, name: "Compensation Package Calculator", slug: "compensation-package-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 46, name: "Total Rewards Calculator", slug: "total-rewards-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 47, name: "Salary Band Midpoint Calculator", slug: "salary-band-midpoint-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 48, name: "Salary Range Penetration Calculator", slug: "salary-range-penetration-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 49, name: "Internal Pay Comparison", slug: "internal-pay-comparison", category: "Payroll & Compensation Tools", isPro: false },
  { id: 50, name: "Department Compensation Calculator", slug: "department-compensation-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 51, name: "Team Payroll Calculator", slug: "team-payroll-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 52, name: "Workforce Payroll Calculator", slug: "workforce-payroll-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 53, name: "Incentive Pool Calculator", slug: "incentive-pool-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 54, name: "Commission Pool Calculator", slug: "commission-pool-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 55, name: "Stock Grant Value Calculator", slug: "stock-grant-value-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 56, name: "Annual Compensation Budget", slug: "annual-compensation-budget", category: "Payroll & Compensation Tools", isPro: false },
  { id: 57, name: "Payroll Forecast Calculator", slug: "payroll-forecast-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 58, name: "Pay Change Impact Calculator", slug: "pay-change-impact-calculator", category: "Payroll & Compensation Tools", isPro: false },
  { id: 59, name: "Compensation Planning Checklist", slug: "compensation-planning-checklist", category: "Payroll & Compensation Tools", isPro: false },
  { id: 60, name: "Compensation Review Checklist", slug: "compensation-review-checklist", category: "Payroll & Compensation Tools", isPro: false },

  // --- ⚡ 40 PRO / SAAS TOOLS (IDs 61-100 | isPro: true) ---
  { id: 61, name: "Compensation Planning Workspace", slug: "compensation-planning-workspace", category: "Payroll & Compensation Tools", isPro: true },
  { id: 62, name: "Payroll Planning Workspace", slug: "payroll-planning-workspace", category: "Payroll & Compensation Tools", isPro: true },
  { id: 63, name: "Salary Structure Manager", slug: "salary-structure-manager", category: "Payroll & Compensation Tools", isPro: true },
  { id: 64, name: "Pay Band Management Workspace", slug: "pay-band-management-workspace", category: "Payroll & Compensation Tools", isPro: true },
  { id: 65, name: "Compensation Benchmarking Workspace", slug: "compensation-benchmarking-workspace", category: "Payroll & Compensation Tools", isPro: true },
  { id: 66, name: "Compensation Budget Dashboard", slug: "compensation-budget-dashboard", category: "Payroll & Compensation Tools", isPro: true },
  { id: 67, name: "Workforce Compensation Dashboard", slug: "workforce-compensation-dashboard", category: "Payroll & Compensation Tools", isPro: true },
  { id: 68, name: "Payroll Cost Dashboard", slug: "payroll-cost-dashboard", category: "Payroll & Compensation Tools", isPro: true },
  { id: 69, name: "Total Compensation Dashboard", slug: "total-compensation-dashboard", category: "Payroll & Compensation Tools", isPro: true },
  { id: 70, name: "Bonus Planning Workspace", slug: "bonus-planning-workspace", category: "Payroll & Compensation Tools", isPro: true },
  { id: 71, name: "Incentive Planning Workspace", slug: "incentive-planning-workspace", category: "Payroll & Compensation Tools", isPro: true },
  { id: 72, name: "Commission Planning Workspace", slug: "commission-planning-workspace", category: "Payroll & Compensation Tools", isPro: true },
  { id: 73, name: "Merit Increase Workspace", slug: "merit-increase-workspace", category: "Payroll & Compensation Tools", isPro: true },
  { id: 74, name: "Promotion Compensation Workspace", slug: "promotion-compensation-workspace", category: "Payroll & Compensation Tools", isPro: true },
  { id: 75, name: "Pay Equity Analytics Workspace", slug: "pay-equity-analytics-workspace", category: "Payroll & Compensation Tools", isPro: true },
  { id: 76, name: "Compa-Ratio Analytics", slug: "compa-ratio-analytics", category: "Payroll & Compensation Tools", isPro: true },
  { id: 77, name: "Salary Range Analytics", slug: "salary-range-analytics", category: "Payroll & Compensation Tools", isPro: true },
  { id: 78, name: "Compensation Scenario Planner", slug: "compensation-scenario-planner-pro", category: "Payroll & Compensation Tools", isPro: true },
  { id: 79, name: "Compensation Forecasting Workspace", slug: "compensation-forecasting-workspace", category: "Payroll & Compensation Tools", isPro: true },
  { id: 80, name: "Payroll Forecasting Workspace", slug: "payroll-forecasting-workspace", category: "Payroll & Compensation Tools", isPro: true },
  { id: 81, name: "Compensation Change Management", slug: "compensation-change-management", category: "Payroll & Compensation Tools", isPro: true },
  { id: 82, name: "Compensation Approval Workspace", slug: "compensation-approval-workspace", category: "Payroll & Compensation Tools", isPro: true },
  { id: 83, name: "Compensation Cycle Manager", slug: "compensation-cycle-manager", category: "Payroll & Compensation Tools", isPro: true },
  { id: 84, name: "Annual Pay Review Workspace", slug: "annual-pay-review-workspace", category: "Payroll & Compensation Tools", isPro: true },
  { id: 85, name: "Bonus Cycle Management", slug: "bonus-cycle-management", category: "Payroll & Compensation Tools", isPro: true },
  { id: 86, name: "Equity Compensation Workspace", slug: "equity-compensation-workspace", category: "Payroll & Compensation Tools", isPro: true },
  { id: 87, name: "Vesting Management Workspace", slug: "vesting-management-workspace", category: "Payroll & Compensation Tools", isPro: true },
  { id: 88, name: "Compensation Data Importer", slug: "compensation-data-importer", category: "Payroll & Compensation Tools", isPro: true },
  { id: 89, name: "Compensation Data Exporter", slug: "compensation-data-exporter", category: "Payroll & Compensation Tools", isPro: true },
  { id: 90, name: "Payroll Data Workspace", slug: "payroll-data-workspace", category: "Payroll & Compensation Tools", isPro: true },
  { id: 91, name: "Compensation Reporting Engine", slug: "compensation-reporting-engine", category: "Payroll & Compensation Tools", isPro: true },
  { id: 92, name: "Payroll Reporting Workspace", slug: "payroll-reporting-workspace", category: "Payroll & Compensation Tools", isPro: true },
  { id: 93, name: "Compensation Analytics API", slug: "compensation-analytics-api", category: "Payroll & Compensation Tools", isPro: true },
  { id: 94, name: "Payroll Integration Workspace", slug: "payroll-integration-workspace", category: "Payroll & Compensation Tools", isPro: true },
  { id: 95, name: "Compensation Workflow Automation", slug: "compensation-workflow-automation", category: "Payroll & Compensation Tools", isPro: true },
  { id: 96, name: "Compensation Alert Engine", slug: "compensation-alert-engine", category: "Payroll & Compensation Tools", isPro: true },
  { id: 97, name: "Compensation Intelligence Platform", slug: "compensation-intelligence-platform", category: "Payroll & Compensation Tools", isPro: true },
  { id: 98, name: "Enterprise Compensation Platform", slug: "enterprise-compensation-platform", category: "Payroll & Compensation Tools", isPro: true },
  { id: 99, name: "Total Rewards Management Platform", slug: "total-rewards-management-platform", category: "Payroll & Compensation Tools", isPro: true },
  { id: 100, name: "Compensation Command Center", slug: "compensation-command-center", category: "Payroll & Compensation Tools", isPro: true }
];