export interface PetCareTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const petCareToolsList: PetCareTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "Pet Age Calculator", slug: "pet-age-calculator", category: "Pet Care Tools", isPro: false },
  { id: 2, name: "Dog Age Calculator", slug: "dog-age-calculator", category: "Pet Care Tools", isPro: false },
  { id: 3, name: "Cat Age Calculator", slug: "cat-age-calculator", category: "Pet Care Tools", isPro: false },
  { id: 4, name: "Pet Calorie Calculator", slug: "pet-calorie-calculator", category: "Pet Care Tools", isPro: false },
  { id: 5, name: "Dog Calorie Calculator", slug: "dog-calorie-calculator", category: "Pet Care Tools", isPro: false },
  { id: 6, name: "Cat Calorie Calculator", slug: "cat-calorie-calculator", category: "Pet Care Tools", isPro: false },
  { id: 7, name: "Pet Water Intake Calculator", slug: "pet-water-intake-calculator", category: "Pet Care Tools", isPro: false },
  { id: 8, name: "Pet Feeding Calculator", slug: "pet-feeding-calculator", category: "Pet Care Tools", isPro: false },
  { id: 9, name: "Pet Care Cost Calculator", slug: "pet-care-cost-calculator", category: "Pet Care Tools", isPro: false },
  { id: 10, name: "Pet Insurance Cost Calculator", slug: "pet-insurance-cost-calculator", category: "Pet Care Tools", isPro: false },
  { id: 11, name: "Pet Vaccination Tracker", slug: "pet-vaccination-tracker", category: "Pet Care Tools", isPro: false },
  { id: 12, name: "Pet Medication Schedule", slug: "pet-medication-schedule", category: "Pet Care Tools", isPro: false },
  { id: 13, name: "Pet Weight Tracker", slug: "pet-weight-tracker", category: "Pet Care Tools", isPro: false },
  { id: 14, name: "Dog Walking Tracker", slug: "dog-walking-tracker", category: "Pet Care Tools", isPro: false },
  { id: 15, name: "Pet Grooming Schedule", slug: "pet-grooming-schedule", category: "Pet Care Tools", isPro: false },
  { id: 16, name: "Puppy Training Planner", slug: "puppy-training-planner", category: "Pet Care Tools", isPro: false },
  { id: 17, name: "Pet Travel Checklist", slug: "pet-travel-checklist", category: "Pet Care Tools", isPro: false },
  { id: 18, name: "Pet Name Generator", slug: "pet-name-generator", category: "Pet Care Tools", isPro: false },
  { id: 19, name: "Pet Emergency Card", slug: "pet-emergency-card", category: "Pet Care Tools", isPro: false },
  { id: 20, name: "Complete Pet Management Workspace", slug: "complete-pet-management-workspace", category: "Pet Care Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Pet Growth Tracker", slug: "pet-growth-tracker", category: "Pet Care Tools", isPro: false },
  { id: 22, name: "Puppy Growth Calculator", slug: "puppy-growth-calculator", category: "Pet Care Tools", isPro: false },
  { id: 23, name: "Kitten Growth Calculator", slug: "kitten-growth-calculator", category: "Pet Care Tools", isPro: false },
  { id: 24, name: "Dog Feeding Calculator", slug: "dog-feeding-calculator", category: "Pet Care Tools", isPro: false },
  { id: 25, name: "Cat Feeding Calculator", slug: "cat-feeding-calculator", category: "Pet Care Tools", isPro: false },
  { id: 26, name: "Pet Food Portion Calculator", slug: "pet-food-portion-calculator", category: "Pet Care Tools", isPro: false },
  { id: 27, name: "Pet Food Cost Calculator", slug: "pet-food-cost-calculator", category: "Pet Care Tools", isPro: false },
  { id: 28, name: "Annual Pet Cost Calculator", slug: "annual-pet-cost-calculator", category: "Pet Care Tools", isPro: false },
  { id: 29, name: "Pet Appointment Tracker", slug: "pet-appointment-tracker", category: "Pet Care Tools", isPro: false },
  { id: 30, name: "Pet Health Journal", slug: "pet-health-journal", category: "Pet Care Tools", isPro: false },
  { id: 31, name: "Pet Weight Journal", slug: "pet-weight-journal", category: "Pet Care Tools", isPro: false },
  { id: 32, name: "Pet Feeding Journal", slug: "pet-feeding-journal", category: "Pet Care Tools", isPro: false },
  { id: 33, name: "Pet Medication Journal", slug: "pet-medication-journal", category: "Pet Care Tools", isPro: false },
  { id: 34, name: "Pet Activity Tracker", slug: "pet-activity-tracker", category: "Pet Care Tools", isPro: false },
  { id: 35, name: "Pet Exercise Tracker", slug: "pet-exercise-tracker", category: "Pet Care Tools", isPro: false },
  { id: 36, name: "Pet Grooming Cost Calculator", slug: "pet-grooming-cost-calculator", category: "Pet Care Tools", isPro: false },
  { id: 37, name: "Flea Treatment Reminder", slug: "flea-treatment-reminder", category: "Pet Care Tools", isPro: false },
  { id: 38, name: "Pet Parasite Treatment Reminder", slug: "pet-parasite-treatment-reminder", category: "Pet Care Tools", isPro: false },
  { id: 39, name: "Pet Dental Care Reminder", slug: "pet-dental-care-reminder", category: "Pet Care Tools", isPro: false },
  { id: 40, name: "Pet Nail Trimming Reminder", slug: "pet-nail-trimming-reminder", category: "Pet Care Tools", isPro: false },
  { id: 41, name: "Pet Bathing Schedule", slug: "pet-bathing-schedule", category: "Pet Care Tools", isPro: false },
  { id: 42, name: "Pet Training Schedule", slug: "pet-training-schedule", category: "Pet Care Tools", isPro: false },
  { id: 43, name: "Dog Training Planner", slug: "dog-training-planner", category: "Pet Care Tools", isPro: false },
  { id: 44, name: "Cat Care Planner", slug: "cat-care-planner", category: "Pet Care Tools", isPro: false },
  { id: 45, name: "Pet Routine Planner", slug: "pet-routine-planner", category: "Pet Care Tools", isPro: false },
  { id: 46, name: "Pet Daily Checklist", slug: "pet-daily-checklist", category: "Pet Care Tools", isPro: false },
  { id: 47, name: "Pet Sitter Checklist", slug: "pet-sitter-checklist", category: "Pet Care Tools", isPro: false },
  { id: 48, name: "Pet Boarding Checklist", slug: "pet-boarding-checklist", category: "Pet Care Tools", isPro: false },
  { id: 49, name: "Pet Travel Cost Calculator", slug: "pet-travel-cost-calculator", category: "Pet Care Tools", isPro: false },
  { id: 50, name: "Pet Carrier Size Calculator", slug: "pet-carrier-size-calculator", category: "Pet Care Tools", isPro: false },
  { id: 51, name: "Dog Crate Size Calculator", slug: "dog-crate-size-calculator", category: "Pet Care Tools", isPro: false },
  { id: 52, name: "Aquarium Volume Calculator", slug: "aquarium-volume-calculator", category: "Pet Care Tools", isPro: false },
  { id: 53, name: "Fish Tank Volume Calculator", slug: "fish-tank-volume-calculator", category: "Pet Care Tools", isPro: false },
  { id: 54, name: "Aquarium Maintenance Planner", slug: "aquarium-maintenance-planner", category: "Pet Care Tools", isPro: false },
  { id: 55, name: "Dog Name Generator", slug: "dog-name-generator", category: "Pet Care Tools", isPro: false },
  { id: 56, name: "Cat Name Generator", slug: "cat-name-generator", category: "Pet Care Tools", isPro: false },
  { id: 57, name: "Pet Name Finder", slug: "pet-name-finder", category: "Pet Care Tools", isPro: false },
  { id: 58, name: "Pet Information Card", slug: "pet-information-card", category: "Pet Care Tools", isPro: false },
  { id: 59, name: "Pet Profile Generator", slug: "pet-profile-generator", category: "Pet Care Tools", isPro: false },
  { id: 60, name: "Pet Care Calendar", slug: "pet-care-calendar", category: "Pet Care Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Multi-Pet Dashboard", slug: "multi-pet-dashboard", category: "Pet Care Tools", isPro: true },
  { id: 62, name: "Pet Health Record Workspace", slug: "pet-health-record-workspace", category: "Pet Care Tools", isPro: true },
  { id: 63, name: "Pet Medical Timeline", slug: "pet-medical-timeline", category: "Pet Care Tools", isPro: true },
  { id: 64, name: "Pet Medication Management Workspace", slug: "pet-medication-management-workspace", category: "Pet Care Tools", isPro: true },
  { id: 65, name: "Pet Vaccination Management Workspace", slug: "pet-vaccination-management-workspace", category: "Pet Care Tools", isPro: true },
  { id: 66, name: "Pet Weight Analytics", slug: "pet-weight-analytics", category: "Pet Care Tools", isPro: true },
  { id: 67, name: "Pet Activity Analytics", slug: "pet-activity-analytics", category: "Pet Care Tools", isPro: true },
  { id: 68, name: "Pet Feeding Analytics", slug: "pet-feeding-analytics", category: "Pet Care Tools", isPro: true },
  { id: 69, name: "Pet Care Cost Dashboard", slug: "pet-care-cost-dashboard", category: "Pet Care Tools", isPro: true },
  { id: 70, name: "Pet Budget Planner", slug: "pet-budget-planner", category: "Pet Care Tools", isPro: true },
  { id: 71, name: "Pet Insurance Comparison Workspace", slug: "pet-insurance-comparison-workspace", category: "Pet Care Tools", isPro: true },
  { id: 72, name: "Pet Food Budget Optimizer", slug: "pet-food-budget-optimizer", category: "Pet Care Tools", isPro: true },
  { id: 73, name: "Pet Meal Planning Workspace", slug: "pet-meal-planning-workspace", category: "Pet Care Tools", isPro: true },
  { id: 74, name: "Pet Routine Optimization Tool", slug: "pet-routine-optimization-tool", category: "Pet Care Tools", isPro: true },
  { id: 75, name: "Dog Training Program Builder", slug: "dog-training-program-builder", category: "Pet Care Tools", isPro: true },
  { id: 76, name: "Puppy Training Program Builder", slug: "puppy-training-program-builder", category: "Pet Care Tools", isPro: true },
  { id: 77, name: "Cat Behavior Routine Planner", slug: "cat-behavior-routine-planner", category: "Pet Care Tools", isPro: true },
  { id: 78, name: "Pet Exercise Planning Workspace", slug: "pet-exercise-planning-workspace", category: "Pet Care Tools", isPro: true },
  { id: 79, name: "Dog Walking Schedule Workspace", slug: "dog-walking-schedule-workspace", category: "Pet Care Tools", isPro: true },
  { id: 80, name: "Pet Grooming Management Workspace", slug: "pet-grooming-management-workspace", category: "Pet Care Tools", isPro: true },
  { id: 81, name: "Pet Sitter Management Workspace", slug: "pet-sitter-management-workspace", category: "Pet Care Tools", isPro: true },
  { id: 82, name: "Pet Boarding Management Workspace", slug: "pet-boarding-management-workspace", category: "Pet Care Tools", isPro: true },
  { id: 83, name: "Pet Travel Planning Workspace", slug: "pet-travel-planning-workspace", category: "Pet Care Tools", isPro: true },
  { id: 84, name: "Multi-Pet Calendar", slug: "multi-pet-calendar", category: "Pet Care Tools", isPro: true },
  { id: 85, name: "Pet Document Organizer", slug: "pet-document-organizer", category: "Pet Care Tools", isPro: true },
  { id: 86, name: "Pet Emergency Information Workspace", slug: "pet-emergency-information-workspace", category: "Pet Care Tools", isPro: true },
  { id: 87, name: "Pet Care Report Generator", slug: "pet-care-report-generator", category: "Pet Care Tools", isPro: true },
  { id: 88, name: "Pet Data Import Workspace", slug: "pet-data-import-workspace", category: "Pet Care Tools", isPro: true },
  { id: 89, name: "Pet Data Export Tool", slug: "pet-data-export-tool", category: "Pet Care Tools", isPro: true },
  { id: 90, name: "Veterinary Visit Preparation Workspace", slug: "veterinary-visit-preparation-workspace", category: "Pet Care Tools", isPro: true },
  { id: 91, name: "Vet Question Planner", slug: "vet-question-planner", category: "Pet Care Tools", isPro: true },
  { id: 92, name: "Pet Care History Analyzer", slug: "pet-care-history-analyzer", category: "Pet Care Tools", isPro: true },
  { id: 93, name: "Pet Service Business Workspace", slug: "pet-service-business-workspace", category: "Pet Care Tools", isPro: true },
  { id: 94, name: "Pet Care Professional Dashboard", slug: "pet-care-professional-dashboard", category: "Pet Care Tools", isPro: true },
  { id: 95, name: "Pet Boarding Operations Workspace", slug: "pet-boarding-operations-workspace", category: "Pet Care Tools", isPro: true },
  { id: 96, name: "Pet Grooming Business Workspace", slug: "pet-grooming-business-workspace", category: "Pet Care Tools", isPro: true },
  { id: 97, name: "Pet Care API Workspace", slug: "pet-care-api-workspace", category: "Pet Care Tools", isPro: true },
  { id: 98, name: "Pet Intelligence Platform", slug: "pet-intelligence-platform", category: "Pet Care Tools", isPro: true },
  { id: 99, name: "Professional Pet Management Command Center", slug: "professional-pet-management-command-center", category: "Pet Care Tools", isPro: true },
  { id: 100, name: "Pet Medication Analyzer", slug: "pet-medication-analyzer", category: "Pet Care Tools", isPro: true }
];