export interface ProcurementPurchasingTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const procurementPurchasingToolsList: ProcurementPurchasingTool[] = [
  // --- 🔥 PRIORITY 20 FREE TOOLS (IDs 1-20 | isPro: false) ---
  { id: 1, name: "Supplier Quote Comparison", slug: "supplier-quote-comparison", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 2, name: "Vendor Quote Comparison", slug: "vendor-quote-comparison", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 3, name: "Unit Price Comparison", slug: "unit-price-comparison", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 4, name: "Bulk Purchase Savings Calculator", slug: "bulk-purchase-savings-calculator", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 5, name: "Volume Discount Calculator", slug: "volume-discount-calculator", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 6, name: "Early Payment Discount Calculator", slug: "early-payment-discount-calculator", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 7, name: "Procurement Savings Calculator", slug: "procurement-savings-calculator", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 8, name: "Total Purchase Cost Calculator", slug: "total-purchase-cost-calculator", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 9, name: "Supplier Price Comparison", slug: "supplier-price-comparison", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 10, name: "Purchase Price Variance Calculator", slug: "purchase-price-variance-calculator", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 11, name: "Purchase Budget Calculator", slug: "purchase-budget-calculator", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 12, name: "Procurement Spend Calculator", slug: "procurement-spend-calculator", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 13, name: "Purchase Request Generator", slug: "purchase-request-generator", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 14, name: "Purchase Approval Matrix", slug: "purchase-approval-matrix", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 15, name: "Purchase Order Generator", slug: "purchase-order-generator", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 16, name: "RFQ Builder", slug: "rfq-builder", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 17, name: "Vendor Evaluation Scorecard", slug: "vendor-evaluation-scorecard", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 18, name: "Vendor Comparison Matrix", slug: "vendor-comparison-matrix", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 19, name: "Procurement Spend Dashboard", slug: "procurement-spend-dashboard-free", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 20, name: "Purchase Order Management", slug: "purchase-order-management-free", category: "Procurement & Purchasing Tools", isPro: false },

  // --- REMAINING 40 CORE FREE TOOLS (IDs 21-60 | isPro: false) ---
  { id: 21, name: "Purchase Cost Calculator", slug: "purchase-cost-calculator", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 22, name: "Purchase Quantity Calculator", slug: "purchase-quantity-calculator", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 23, name: "Purchase Order Amount Calculator", slug: "purchase-order-amount-calculator", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 24, name: "Quote Variance Calculator", slug: "quote-variance-calculator", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 25, name: "Purchase Discount Calculator", slug: "purchase-discount-calculator", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 26, name: "Payment Term Savings Calculator", slug: "payment-term-savings-calculator", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 27, name: "Purchase Savings Percentage", slug: "purchase-savings-percentage", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 28, name: "Procurement Cost Comparison", slug: "procurement-cost-comparison", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 29, name: "Vendor Price Comparison", slug: "vendor-price-comparison", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 30, name: "Budget vs Purchase Calculator", slug: "budget-vs-purchase-calculator", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 31, name: "Department Purchase Budget", slug: "department-purchase-budget", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 32, name: "Category Spend Calculator", slug: "category-spend-calculator", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 33, name: "Supplier Spend Calculator", slug: "supplier-spend-calculator", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 34, name: "Annual Purchase Spend", slug: "annual-purchase-spend", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 35, name: "Purchase Frequency Calculator", slug: "purchase-frequency-calculator", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 36, name: "Reorder Purchase Planner", slug: "reorder-purchase-planner", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 37, name: "Purchase Request Checklist", slug: "purchase-request-checklist", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 38, name: "Purchase Approval Checklist", slug: "purchase-approval-checklist", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 39, name: "Purchase Order Checklist", slug: "purchase-order-checklist", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 40, name: "Purchase Order Number Generator", slug: "purchase-order-number-generator", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 41, name: "RFQ Checklist", slug: "rfq-checklist", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 42, name: "RFP Checklist", slug: "rfp-checklist", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 43, name: "RFP Requirement Builder", slug: "rfp-requirement-builder", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 44, name: "Supplier Selection Scorecard", slug: "supplier-selection-scorecard", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 45, name: "Supplier Comparison Matrix", slug: "supplier-comparison-matrix", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 46, name: "Procurement Evaluation Matrix", slug: "procurement-evaluation-matrix", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 47, name: "Vendor Qualification Checklist", slug: "vendor-qualification-checklist", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 48, name: "Supplier Qualification Checklist", slug: "supplier-qualification-checklist", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 49, name: "Procurement Due Diligence Checklist", slug: "procurement-due-diligence-checklist", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 50, name: "Purchase Contract Checklist", slug: "purchase-contract-checklist", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 51, name: "Procurement Policy Checklist", slug: "procurement-policy-checklist", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 52, name: "Procurement Audit Checklist", slug: "procurement-audit-checklist", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 53, name: "Vendor Onboarding Checklist", slug: "vendor-onboarding-checklist", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 54, name: "Supplier Onboarding Checklist", slug: "supplier-onboarding-checklist", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 55, name: "Purchase Documentation Checklist", slug: "purchase-documentation-checklist", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 56, name: "Procurement KPI Calculator", slug: "procurement-kpi-calculator", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 57, name: "Procurement Savings Report", slug: "procurement-savings-report", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 58, name: "Supplier Spend Report", slug: "supplier-spend-report", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 59, name: "Purchase Order Report", slug: "purchase-order-report", category: "Procurement & Purchasing Tools", isPro: false },
  { id: 60, name: "Procurement Planning Checklist", slug: "procurement-planning-checklist", category: "Procurement & Purchasing Tools", isPro: false },

  // --- ⚡ 40 PRO / SAAS TOOLS (IDs 61-100 | isPro: true) ---
  { id: 61, name: "Procurement Management Workspace", slug: "procurement-management-workspace", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 62, name: "Purchasing Management Workspace", slug: "purchasing-management-workspace", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 63, name: "Purchase Request Management", slug: "purchase-request-management", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 64, name: "Purchase Order Management", slug: "purchase-order-management", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 65, name: "RFQ Management Workspace", slug: "rfq-management-workspace", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 66, name: "RFP Management Workspace", slug: "rfp-management-workspace", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 67, name: "Vendor Evaluation Workspace", slug: "vendor-evaluation-workspace", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 68, name: "Supplier Selection Workspace", slug: "supplier-selection-workspace", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 69, name: "Vendor Qualification Workspace", slug: "vendor-qualification-workspace", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 70, name: "Supplier Qualification Workspace", slug: "supplier-qualification-workspace", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 71, name: "Vendor Onboarding Workspace", slug: "vendor-onboarding-workspace", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 72, name: "Supplier Onboarding Workspace", slug: "supplier-onboarding-workspace", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 73, name: "Procurement Approval Workspace", slug: "procurement-approval-workspace", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 74, name: "Procurement Workflow Workspace", slug: "procurement-workflow-workspace", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 75, name: "Procurement Budget Dashboard", slug: "procurement-budget-dashboard", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 76, name: "Procurement Spend Dashboard", slug: "procurement-spend-dashboard", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 77, name: "Supplier Spend Analytics", slug: "supplier-spend-analytics", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 78, name: "Category Spend Analytics", slug: "category-spend-analytics", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 79, name: "Purchase Price Analytics", slug: "purchase-price-analytics", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 80, name: "Procurement Savings Dashboard", slug: "procurement-savings-dashboard", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 81, name: "Vendor Performance Dashboard", slug: "vendor-performance-dashboard", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 82, name: "Procurement KPI Dashboard", slug: "procurement-kpi-dashboard", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 83, name: "Procurement Compliance Workspace", slug: "procurement-compliance-workspace", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 84, name: "Procurement Audit Workspace", slug: "procurement-audit-workspace", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 85, name: "Procurement Contract Workspace", slug: "procurement-contract-workspace", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 86, name: "Procurement Document Workspace", slug: "procurement-document-workspace", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 87, name: "Procurement Reporting Engine", slug: "procurement-reporting-engine", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 88, name: "Procurement Data Importer", slug: "procurement-data-importer", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 89, name: "Procurement Data Exporter", slug: "procurement-data-exporter", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 90, name: "Procurement API Workspace", slug: "procurement-api-workspace", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 91, name: "Procurement Workflow Automation", slug: "procurement-workflow-automation", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 92, name: "Purchase Approval Automation", slug: "purchase-approval-automation", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 93, name: "Vendor Alert Engine", slug: "vendor-alert-engine", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 94, name: "Procurement Forecasting Workspace", slug: "procurement-forecasting-workspace", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 95, name: "Procurement Intelligence Platform", slug: "procurement-intelligence-platform", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 96, name: "Digital Procurement Platform", slug: "digital-procurement-platform", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 97, name: "Enterprise Purchasing Platform", slug: "enterprise-purchasing-platform", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 98, name: "Strategic Procurement Platform", slug: "strategic-procurement-platform", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 99, name: "Procurement Operations Platform", slug: "procurement-operations-platform", category: "Procurement & Purchasing Tools", isPro: true },
  { id: 100, name: "Procurement Command Center", slug: "procurement-command-center", category: "Procurement & Purchasing Tools", isPro: true }
];