export interface ProjectManagementTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const projectManagementToolsList: ProjectManagementTool[] = [
  // --- 🔥 PRIORITY 20 FREE TOOLS (IDs 1-20 | isPro: false) ---
  { id: 1, name: "Project Cost Calculator", slug: "project-cost-calculator", category: "Project Management Tools", isPro: false },
  { id: 2, name: "Project Budget Calculator", slug: "project-budget-calculator", category: "Project Management Tools", isPro: false },
  { id: 3, name: "Project Duration Calculator", slug: "project-duration-calculator", category: "Project Management Tools", isPro: false },
  { id: 4, name: "Project Deadline Calculator", slug: "project-deadline-calculator", category: "Project Management Tools", isPro: false },
  { id: 5, name: "Resource Capacity Calculator", slug: "resource-capacity-calculator", category: "Project Management Tools", isPro: false },
  { id: 6, name: "Team Capacity Calculator", slug: "team-capacity-calculator", category: "Project Management Tools", isPro: false },
  { id: 7, name: "Resource Allocation Calculator", slug: "resource-allocation-calculator", category: "Project Management Tools", isPro: false },
  { id: 8, name: "Project Burn Rate Calculator", slug: "project-burn-rate-calculator", category: "Project Management Tools", isPro: false },
  { id: 9, name: "Cost Performance Index Calculator", slug: "cost-performance-index-calculator", category: "Project Management Tools", isPro: false },
  { id: 10, name: "Schedule Performance Index Calculator", slug: "schedule-performance-index-calculator", category: "Project Management Tools", isPro: false },
  { id: 11, name: "Project Health Score", slug: "project-health-score", category: "Project Management Tools", isPro: false },
  { id: 12, name: "Project Risk Score", slug: "project-risk-score", category: "Project Management Tools", isPro: false },
  { id: 13, name: "Critical Path Calculator", slug: "critical-path-calculator", category: "Project Management Tools", isPro: false },
  { id: 14, name: "Project Timeline Builder", slug: "project-timeline-builder", category: "Project Management Tools", isPro: false },
  { id: 15, name: "Project Schedule Builder", slug: "project-schedule-builder", category: "Project Management Tools", isPro: false },
  { id: 16, name: "Work Breakdown Structure Builder", slug: "work-breakdown-structure-builder", category: "Project Management Tools", isPro: false },
  { id: 17, name: "Project Risk Register", slug: "project-risk-register", category: "Project Management Tools", isPro: false },
  { id: 18, name: "Project Change Request Tracker", slug: "project-change-request-tracker", category: "Project Management Tools", isPro: false },
  { id: 19, name: "Project Progress Dashboard", slug: "project-progress-dashboard-free", category: "Project Management Tools", isPro: false },
  { id: 20, name: "Project Management Workspace", slug: "project-management-workspace-free", category: "Project Management Tools", isPro: false },

  // --- REMAINING 40 CORE FREE TOOLS (IDs 21-60 | isPro: false) ---
  { id: 21, name: "Workday Project Calculator", slug: "workday-project-calculator", category: "Project Management Tools", isPro: false },
  { id: 22, name: "Task Duration Calculator", slug: "task-duration-calculator", category: "Project Management Tools", isPro: false },
  { id: 23, name: "Task Effort Calculator", slug: "task-effort-calculator", category: "Project Management Tools", isPro: false },
  { id: 24, name: "Project Resource Calculator", slug: "project-resource-calculator", category: "Project Management Tools", isPro: false },
  { id: 25, name: "Project Staffing Calculator", slug: "project-staffing-calculator", category: "Project Management Tools", isPro: false },
  { id: 26, name: "Project Utilization Calculator", slug: "project-utilization-calculator", category: "Project Management Tools", isPro: false },
  { id: 27, name: "Project Cost Variance Calculator", slug: "project-cost-variance-calculator", category: "Project Management Tools", isPro: false },
  { id: 28, name: "Schedule Variance Calculator", slug: "schedule-variance-calculator", category: "Project Management Tools", isPro: false },
  { id: 29, name: "Earned Value Calculator", slug: "earned-value-calculator", category: "Project Management Tools", isPro: false },
  { id: 30, name: "Planned Value Calculator", slug: "planned-value-calculator", category: "Project Management Tools", isPro: false },
  { id: 31, name: "Actual Cost Calculator", slug: "actual-cost-calculator", category: "Project Management Tools", isPro: false },
  { id: 32, name: "Project Completion Calculator", slug: "project-completion-calculator", category: "Project Management Tools", isPro: false },
  { id: 33, name: "Project Progress Calculator", slug: "project-progress-calculator", category: "Project Management Tools", isPro: false },
  { id: 34, name: "Milestone Progress Calculator", slug: "milestone-progress-calculator", category: "Project Management Tools", isPro: false },
  { id: 35, name: "Task Progress Calculator", slug: "task-progress-calculator", category: "Project Management Tools", isPro: false },
  { id: 36, name: "Project Priority Score", slug: "project-priority-score", category: "Project Management Tools", isPro: false },
  { id: 37, name: "Task Priority Matrix", slug: "task-priority-matrix", category: "Project Management Tools", isPro: false },
  { id: 38, name: "Project Dependency Mapper", slug: "project-dependency-mapper", category: "Project Management Tools", isPro: false },
  { id: 39, name: "Task Dependency Mapper", slug: "task-dependency-mapper", category: "Project Management Tools", isPro: false },
  { id: 40, name: "Critical Path Planner", slug: "critical-path-planner", category: "Project Management Tools", isPro: false },
  { id: 41, name: "Milestone Planner", slug: "milestone-planner", category: "Project Management Tools", isPro: false },
  { id: 42, name: "Project Gantt Planner", slug: "project-gantt-planner", category: "Project Management Tools", isPro: false },
  { id: 43, name: "Task Breakdown Builder", slug: "task-breakdown-builder", category: "Project Management Tools", isPro: false },
  { id: 44, name: "Project Scope Builder", slug: "project-scope-builder", category: "Project Management Tools", isPro: false },
  { id: 45, name: "Project Charter Builder", slug: "project-charter-builder", category: "Project Management Tools", isPro: false },
  { id: 46, name: "Project Brief Builder", slug: "project-brief-builder", category: "Project Management Tools", isPro: false },
  { id: 47, name: "Project Objective Builder", slug: "project-objective-builder", category: "Project Management Tools", isPro: false },
  { id: 48, name: "Project Assumption Log", slug: "project-assumption-log", category: "Project Management Tools", isPro: false },
  { id: 49, name: "Project Issue Register", slug: "project-issue-register", category: "Project Management Tools", isPro: false },
  { id: 50, name: "Project Decision Log", slug: "project-decision-log", category: "Project Management Tools", isPro: false },
  { id: 51, name: "Project Action Item Tracker", slug: "project-action-item-tracker", category: "Project Management Tools", isPro: false },
  { id: 52, name: "Project Meeting Planner", slug: "project-meeting-planner", category: "Project Management Tools", isPro: false },
  { id: 53, name: "Project Status Report Generator", slug: "project-status-report-generator", category: "Project Management Tools", isPro: false },
  { id: 54, name: "Project Progress Report", slug: "project-progress-report", category: "Project Management Tools", isPro: false },
  { id: 55, name: "Project Risk Report", slug: "project-risk-report", category: "Project Management Tools", isPro: false },
  { id: 56, name: "Project Budget Report", slug: "project-budget-report", category: "Project Management Tools", isPro: false },
  { id: 57, name: "Project Schedule Report", slug: "project-schedule-report", category: "Project Management Tools", isPro: false },
  { id: 58, name: "Project Closure Checklist", slug: "project-closure-checklist", category: "Project Management Tools", isPro: false },
  { id: 59, name: "Project Kickoff Checklist", slug: "project-kickoff-checklist", category: "Project Management Tools", isPro: false },
  { id: 60, name: "Project Retrospective Checklist", slug: "project-retrospective-checklist", category: "Project Management Tools", isPro: false },

  // --- ⚡ 40 PRO / SAAS TOOLS (IDs 61-100 | isPro: true) ---
  { id: 61, name: "Project Management Workspace", slug: "project-management-workspace", category: "Project Management Tools", isPro: true },
  { id: 62, name: "Project Portfolio Workspace", slug: "project-portfolio-workspace", category: "Project Management Tools", isPro: true },
  { id: 63, name: "Project Planning Workspace", slug: "project-planning-workspace", category: "Project Management Tools", isPro: true },
  { id: 64, name: "Project Scheduling Workspace", slug: "project-scheduling-workspace", category: "Project Management Tools", isPro: true },
  { id: 65, name: "Task Management Workspace", slug: "task-management-workspace", category: "Project Management Tools", isPro: true },
  { id: 66, name: "Milestone Management Workspace", slug: "milestone-management-workspace", category: "Project Management Tools", isPro: true },
  { id: 67, name: "Resource Management Workspace", slug: "resource-management-workspace", category: "Project Management Tools", isPro: true },
  { id: 68, name: "Resource Allocation Workspace", slug: "resource-allocation-workspace", category: "Project Management Tools", isPro: true },
  { id: 69, name: "Project Budget Workspace", slug: "project-budget-workspace", category: "Project Management Tools", isPro: true },
  { id: 70, name: "Project Cost Control Workspace", slug: "project-cost-control-workspace", category: "Project Management Tools", isPro: true },
  { id: 71, name: "Project Risk Management", slug: "project-risk-management", category: "Project Management Tools", isPro: true },
  { id: 72, name: "Project Issue Management", slug: "project-issue-management", category: "Project Management Tools", isPro: true },
  { id: 73, name: "Project Change Management", slug: "project-change-management", category: "Project Management Tools", isPro: true },
  { id: 74, name: "Project Dependency Management", slug: "project-dependency-management", category: "Project Management Tools", isPro: true },
  { id: 75, name: "Project Critical Path Workspace", slug: "project-critical-path-workspace", category: "Project Management Tools", isPro: true },
  { id: 76, name: "Project Timeline Dashboard", slug: "project-timeline-dashboard", category: "Project Management Tools", isPro: true },
  { id: 77, name: "Project Progress Dashboard", slug: "project-progress-dashboard", category: "Project Management Tools", isPro: true },
  { id: 78, name: "Project Health Dashboard", slug: "project-health-dashboard", category: "Project Management Tools", isPro: true },
  { id: 79, name: "Project Financial Dashboard", slug: "project-financial-dashboard", category: "Project Management Tools", isPro: true },
  { id: 80, name: "Project Resource Dashboard", slug: "project-resource-dashboard", category: "Project Management Tools", isPro: true },
  { id: 81, name: "Project Portfolio Dashboard", slug: "project-portfolio-dashboard", category: "Project Management Tools", isPro: true },
  { id: 82, name: "Project Status Reporting", slug: "project-status-reporting", category: "Project Management Tools", isPro: true },
  { id: 83, name: "Project Governance Workspace", slug: "project-governance-workspace", category: "Project Management Tools", isPro: true },
  { id: 84, name: "Project Approval Workspace", slug: "project-approval-workspace", category: "Project Management Tools", isPro: true },
  { id: 85, name: "Project Documentation Workspace", slug: "project-documentation-workspace", category: "Project Management Tools", isPro: true },
  { id: 86, name: "Project Collaboration Workspace", slug: "project-collaboration-workspace", category: "Project Management Tools", isPro: true },
  { id: 87, name: "Project Data Importer", slug: "project-data-importer", category: "Project Management Tools", isPro: true },
  { id: 88, name: "Project Data Exporter", slug: "project-data-exporter", category: "Project Management Tools", isPro: true },
  { id: 89, name: "Project Management API", slug: "project-management-api", category: "Project Management Tools", isPro: true },
  { id: 90, name: "Project Workflow Automation", slug: "project-workflow-automation", category: "Project Management Tools", isPro: true },
  { id: 91, name: "Project Alert Engine", slug: "project-alert-engine", category: "Project Management Tools", isPro: true },
  { id: 92, name: "Project Forecasting Workspace", slug: "project-forecasting-workspace", category: "Project Management Tools", isPro: true },
  { id: 93, name: "Project Performance Analytics", slug: "project-performance-analytics", category: "Project Management Tools", isPro: true },
  { id: 94, name: "Project Portfolio Analytics", slug: "project-portfolio-analytics", category: "Project Management Tools", isPro: true },
  { id: 95, name: "Project Delivery Analytics", slug: "project-delivery-analytics", category: "Project Management Tools", isPro: true },
  { id: 96, name: "Project Knowledge Base", slug: "project-knowledge-base", category: "Project Management Tools", isPro: true },
  { id: 97, name: "Project Intelligence Platform", slug: "project-intelligence-platform", category: "Project Management Tools", isPro: true },
  { id: 98, name: "Enterprise Project Platform", slug: "enterprise-project-platform", category: "Project Management Tools", isPro: true },
  { id: 99, name: "Project Operations Platform", slug: "project-operations-platform", category: "Project Management Tools", isPro: true },
  { id: 100, name: "Project Command Center", slug: "project-command-center", category: "Project Management Tools", isPro: true }
];