export interface RealEstateTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const realEstateToolsList: RealEstateTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "Mortgage Payment Calculator", slug: "mortgage-payment-calculator", category: "Real Estate Tools", isPro: false },
  { id: 2, name: "Home Affordability Calculator", slug: "home-affordability-calculator", category: "Real Estate Tools", isPro: false },
  { id: 3, name: "Mortgage Amortization Calculator", slug: "mortgage-amortization-calculator", category: "Real Estate Tools", isPro: false },
  { id: 4, name: "Mortgage Refinance Calculator", slug: "mortgage-refinance-calculator", category: "Real Estate Tools", isPro: false },
  { id: 5, name: "Home Equity Calculator", slug: "home-equity-calculator", category: "Real Estate Tools", isPro: false },
  { id: 6, name: "HELOC Calculator", slug: "heloc-calculator", category: "Real Estate Tools", isPro: false },
  { id: 7, name: "Loan-to-Value Calculator", slug: "ltv-calculator", category: "Real Estate Tools", isPro: false },
  { id: 8, name: "Debt-to-Income Calculator", slug: "debt-to-income-calculator", category: "Real Estate Tools", isPro: false },
  { id: 9, name: "Property Investment Calculator", slug: "property-investment-calculator", category: "Real Estate Tools", isPro: false },
  { id: 10, name: "Rental Property Calculator", slug: "rental-property-calculator", category: "Real Estate Tools", isPro: false },
  { id: 11, name: "Rental Yield Calculator", slug: "rental-yield-calculator", category: "Real Estate Tools", isPro: false },
  { id: 12, name: "Cap Rate Calculator", slug: "cap-rate-calculator", category: "Real Estate Tools", isPro: false },
  { id: 13, name: "Cash-on-Cash Return Calculator", slug: "cash-on-cash-return-calculator", category: "Real Estate Tools", isPro: false },
  { id: 14, name: "Property ROI Calculator", slug: "property-roi-calculator", category: "Real Estate Tools", isPro: false },
  { id: 15, name: "Rental Cash Flow Calculator", slug: "rental-cash-flow-calculator", category: "Real Estate Tools", isPro: false },
  { id: 16, name: "Closing Cost Calculator", slug: "closing-cost-calculator", category: "Real Estate Tools", isPro: false },
  { id: 17, name: "Property Tax Calculator", slug: "property-tax-calculator", category: "Real Estate Tools", isPro: false },
  { id: 18, name: "Rent vs Buy Calculator", slug: "rent-vs-buy-calculator", category: "Real Estate Tools", isPro: false },
  { id: 19, name: "Property Listing Description Generator", slug: "property-listing-description-generator", category: "Real Estate Tools", isPro: false },
  { id: 20, name: "Down Payment Calculator", slug: "down-payment-calculator", category: "Real Estate Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "House Payment Calculator", slug: "house-payment-calculator", category: "Real Estate Tools", isPro: false },
  { id: 22, name: "Mortgage Interest Calculator", slug: "mortgage-interest-calculator", category: "Real Estate Tools", isPro: false },
  { id: 23, name: "Refinance Savings Calculator", slug: "refinance-savings-calculator", category: "Real Estate Tools", isPro: false },
  { id: 24, name: "Home Equity Loan Calculator", slug: "home-equity-loan-calculator", category: "Real Estate Tools", isPro: false },
  { id: 25, name: "Mortgage Rate Comparison Tool", slug: "mortgage-rate-comparison-tool", category: "Real Estate Tools", isPro: false },
  { id: 26, name: "Gross Rental Yield Calculator", slug: "gross-rental-yield-calculator", category: "Real Estate Tools", isPro: false },
  { id: 27, name: "Net Rental Yield Calculator", slug: "net-rental-yield-calculator", category: "Real Estate Tools", isPro: false },
  { id: 28, name: "Real Estate ROI Calculator", slug: "real-estate-roi-calculator", category: "Real Estate Tools", isPro: false },
  { id: 29, name: "Property Appreciation Calculator", slug: "property-appreciation-calculator", category: "Real Estate Tools", isPro: false },
  { id: 30, name: "Property Depreciation Calculator", slug: "property-depreciation-calculator", category: "Real Estate Tools", isPro: false },
  { id: 31, name: "Rental Income Calculator", slug: "rental-income-calculator", category: "Real Estate Tools", isPro: false },
  { id: 32, name: "Rental Expense Calculator", slug: "rental-expense-calculator", category: "Real Estate Tools", isPro: false },
  { id: 33, name: "Property Operating Expense Calculator", slug: "property-operating-expense-calculator", category: "Real Estate Tools", isPro: false },
  { id: 34, name: "Vacancy Rate Calculator", slug: "vacancy-rate-calculator", category: "Real Estate Tools", isPro: false },
  { id: 35, name: "Property Management Fee Calculator", slug: "property-management-fee-calculator", category: "Real Estate Tools", isPro: false },
  { id: 36, name: "Transfer Tax Calculator", slug: "transfer-tax-calculator", category: "Real Estate Tools", isPro: false },
  { id: 37, name: "Stamp Duty Calculator", slug: "stamp-duty-calculator", category: "Real Estate Tools", isPro: false },
  { id: 38, name: "Real Estate Commission Calculator", slug: "real-estate-commission-calculator", category: "Real Estate Tools", isPro: false },
  { id: 39, name: "Buyer Agent Commission Calculator", slug: "buyer-agent-commission-calculator", category: "Real Estate Tools", isPro: false },
  { id: 40, name: "Seller Net Proceeds Calculator", slug: "seller-net-proceeds-calculator", category: "Real Estate Tools", isPro: false },
  { id: 41, name: "Home Sale Profit Calculator", slug: "home-sale-profit-calculator", category: "Real Estate Tools", isPro: false },
  { id: 42, name: "Break-Even Sale Price Calculator", slug: "break-even-sale-price-calculator", category: "Real Estate Tools", isPro: false },
  { id: 43, name: "Buy vs Rent Comparison", slug: "buy-vs-rent-comparison", category: "Real Estate Tools", isPro: false },
  { id: 44, name: "Mortgage vs Rent Comparison", slug: "mortgage-vs-rent-comparison", category: "Real Estate Tools", isPro: false },
  { id: 45, name: "Property Price per Sq Ft Calculator", slug: "property-price-per-sq-ft-calculator", category: "Real Estate Tools", isPro: false },
  { id: 46, name: "Square Footage Calculator", slug: "square-footage-calculator", category: "Real Estate Tools", isPro: false },
  { id: 47, name: "Acreage Calculator", slug: "acreage-calculator", category: "Real Estate Tools", isPro: false },
  { id: 48, name: "Lot Size Calculator", slug: "lot-size-calculator", category: "Real Estate Tools", isPro: false },
  { id: 49, name: "Land Area Calculator", slug: "land-area-calculator", category: "Real Estate Tools", isPro: false },
  { id: 50, name: "Property Renovation Budget Calculator", slug: "property-renovation-budget-calculator", category: "Real Estate Tools", isPro: false },
  { id: 51, name: "Home Improvement ROI Calculator", slug: "home-improvement-roi-calculator", category: "Real Estate Tools", isPro: false },
  { id: 52, name: "Construction Cost Calculator", slug: "construction-cost-calculator", category: "Real Estate Tools", isPro: false },
  { id: 53, name: "Property Listing Title Generator", slug: "property-listing-title-generator", category: "Real Estate Tools", isPro: false },
  { id: 54, name: "Property Ad Copy Generator", slug: "property-ad-copy-generator", category: "Real Estate Tools", isPro: false },
  { id: 55, name: "Open House Checklist", slug: "open-house-checklist", category: "Real Estate Tools", isPro: false },
  { id: 56, name: "Property Viewing Checklist", slug: "property-viewing-checklist", category: "Real Estate Tools", isPro: false },
  { id: 57, name: "Home Inspection Checklist", slug: "home-inspection-checklist", category: "Real Estate Tools", isPro: false },
  { id: 58, name: "Rental Inspection Checklist", slug: "rental-inspection-checklist", category: "Real Estate Tools", isPro: false },
  { id: 59, name: "Tenant Screening Checklist", slug: "tenant-screening-checklist", category: "Real Estate Tools", isPro: false },
  { id: 60, name: "Capitalization Rate Calculator", slug: "capitalization-rate-calculator", category: "Real Estate Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Real Estate Investment Analyzer", slug: "real-estate-investment-analyzer", category: "Real Estate Tools", isPro: true },
  { id: 62, name: "Rental Property Investment Analyzer", slug: "rental-property-investment-analyzer", category: "Real Estate Tools", isPro: true },
  { id: 63, name: "Multifamily Investment Analyzer", slug: "multifamily-investment-analyzer", category: "Real Estate Tools", isPro: true },
  { id: 64, name: "Commercial Property Analyzer", slug: "commercial-property-analyzer", category: "Real Estate Tools", isPro: true },
  { id: 65, name: "Airbnb Investment Analyzer", slug: "airbnb-investment-analyzer", category: "Real Estate Tools", isPro: true },
  { id: 66, name: "Short-Term Rental ROI Analyzer", slug: "short-term-rental-roi-analyzer", category: "Real Estate Tools", isPro: true },
  { id: 67, name: "Property Cash Flow Model", slug: "property-cash-flow-model", category: "Real Estate Tools", isPro: true },
  { id: 68, name: "Property Pro Forma Generator", slug: "property-pro-forma-generator", category: "Real Estate Tools", isPro: true },
  { id: 69, name: "Real Estate Pro Forma Analyzer", slug: "real-estate-pro-forma-analyzer", category: "Real Estate Tools", isPro: true },
  { id: 70, name: "Development Feasibility Calculator", slug: "development-feasibility-calculator", category: "Real Estate Tools", isPro: true },
  { id: 71, name: "Land Development ROI Calculator", slug: "land-development-roi-calculator", category: "Real Estate Tools", isPro: true },
  { id: 72, name: "Construction Development Model", slug: "construction-development-model", category: "Real Estate Tools", isPro: true },
  { id: 73, name: "Property Flip Calculator", slug: "property-flip-calculator", category: "Real Estate Tools", isPro: true },
  { id: 74, name: "House Flipping ROI Analyzer", slug: "house-flipping-roi-analyzer", category: "Real Estate Tools", isPro: true },
  { id: 75, name: "BRRRR Strategy Calculator", slug: "brrrr-strategy-calculator", category: "Real Estate Tools", isPro: true },
  { id: 76, name: "Buy-Rehab-Rent-Refinance Analyzer", slug: "buy-rehab-rent-refinance-analyzer", category: "Real Estate Tools", isPro: true },
  { id: 77, name: "DSCR Calculator", slug: "dscr-calculator", category: "Real Estate Tools", isPro: true },
  { id: 78, name: "Debt Service Calculator", slug: "debt-service-calculator", category: "Real Estate Tools", isPro: true },
  { id: 79, name: "Mortgage Stress Test", slug: "mortgage-stress-test", category: "Real Estate Tools", isPro: true },
  { id: 80, name: "Interest Rate Scenario Analyzer", slug: "interest-rate-scenario-analyzer", category: "Real Estate Tools", isPro: true },
  { id: 81, name: "Property Appreciation Forecast", slug: "property-appreciation-forecast", category: "Real Estate Tools", isPro: true },
  { id: 82, name: "Rental Growth Forecast", slug: "rental-growth-forecast", category: "Real Estate Tools", isPro: true },
  { id: 83, name: "Property Market Comparison Tool", slug: "property-market-comparison-tool", category: "Real Estate Tools", isPro: true },
  { id: 84, name: "Neighborhood Comparison Tool", slug: "neighborhood-comparison-tool", category: "Real Estate Tools", isPro: true },
  { id: 85, name: "Property Investment Score", slug: "property-investment-score", category: "Real Estate Tools", isPro: true },
  { id: 86, name: "Property Risk Analyzer", slug: "property-risk-analyzer", category: "Real Estate Tools", isPro: true },
  { id: 87, name: "Tenant Cash Flow Analyzer", slug: "tenant-cash-flow-analyzer", category: "Real Estate Tools", isPro: true },
  { id: 88, name: "Portfolio Property Analyzer", slug: "portfolio-property-analyzer", category: "Real Estate Tools", isPro: true },
  { id: 89, name: "Multi-Property Portfolio Dashboard", slug: "multi-property-portfolio-dashboard", category: "Real Estate Tools", isPro: true },
  { id: 90, name: "Rental Portfolio Tracker", slug: "rental-portfolio-tracker", category: "Real Estate Tools", isPro: true },
  { id: 91, name: "Property Expense Tracker", slug: "property-expense-tracker", category: "Real Estate Tools", isPro: true },
  { id: 92, name: "Property Maintenance Tracker", slug: "property-maintenance-tracker", category: "Real Estate Tools", isPro: true },
  { id: 93, name: "Lease Expiration Tracker", slug: "lease-expiration-tracker", category: "Real Estate Tools", isPro: true },
  { id: 94, name: "Tenant Rent Increase Calculator", slug: "tenant-rent-increase-calculator", category: "Real Estate Tools", isPro: true },
  { id: 95, name: "Property Manager Dashboard", slug: "property-manager-dashboard", category: "Real Estate Tools", isPro: true },
  { id: 96, name: "Real Estate Agent CRM Workspace", slug: "real-estate-agent-crm-workspace", category: "Real Estate Tools", isPro: true },
  { id: 97, name: "Real Estate Investment Workspace", slug: "real-estate-investment-workspace", category: "Real Estate Tools", isPro: true },
  { id: 98, name: "Property Portfolio Intelligence Platform", slug: "property-portfolio-intelligence-platform", category: "Real Estate Tools", isPro: true },
  { id: 99, name: "Real Estate Deal Analyzer", slug: "real-estate-deal-analyzer", category: "Real Estate Tools", isPro: true },
  { id: 100, name: "Real Estate Investment Intelligence Workspace", slug: "real-estate-investment-intelligence-workspace", category: "Real Estate Tools", isPro: true },
];