export interface RetailOperationsTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const retailOperationsToolsList: RetailOperationsTool[] = [
  // --- 🔥 PRIORITY 20 FREE TOOLS (IDs 1-20 | isPro: false) ---
  { id: 1, name: "Average Transaction Value Calculator", slug: "average-transaction-value-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 2, name: "Sales Per Square Foot Calculator", slug: "sales-per-square-foot-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 3, name: "Store Conversion Rate Calculator", slug: "store-conversion-rate-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 4, name: "Retail Margin Calculator", slug: "retail-margin-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 5, name: "Retail Markup Calculator", slug: "retail-markup-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 6, name: "Markdown Calculator", slug: "markdown-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 7, name: "Gross Margin Return Calculator", slug: "gross-margin-return-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 8, name: "Inventory Turnover Calculator", slug: "inventory-turnover-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 9, name: "Sell-Through Rate Calculator", slug: "sell-through-rate-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 10, name: "Shrinkage Rate Calculator", slug: "shrinkage-rate-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 11, name: "Retail Reorder Calculator", slug: "retail-reorder-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 12, name: "Store Space Allocation Calculator", slug: "store-space-allocation-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 13, name: "Retail Staffing Calculator", slug: "retail-staffing-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 14, name: "Labor Cost Percentage", slug: "labor-cost-percentage", category: "Retail Operations Tools", isPro: false },
  { id: 15, name: "Store Break-Even Calculator", slug: "store-break-even-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 16, name: "Store Profit Calculator", slug: "store-profit-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 17, name: "Promotion ROI Calculator", slug: "promotion-roi-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 18, name: "Customer Basket Value Calculator", slug: "customer-basket-value-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 19, name: "Store Sales Dashboard", slug: "store-sales-dashboard-free", category: "Retail Operations Tools", isPro: false },
  { id: 20, name: "Retail Operations Workspace", slug: "retail-operations-workspace-free", category: "Retail Operations Tools", isPro: false },

  // --- REMAINING 40 CORE FREE TOOLS (IDs 21-60 | isPro: false) ---
  { id: 21, name: "Retail Sales Calculator", slug: "retail-sales-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 22, name: "Store Revenue Calculator", slug: "store-revenue-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 23, name: "Daily Sales Calculator", slug: "daily-sales-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 24, name: "Weekly Sales Calculator", slug: "weekly-sales-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 25, name: "Monthly Store Sales Calculator", slug: "monthly-store-sales-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 26, name: "Units Per Transaction Calculator", slug: "units-per-transaction-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 27, name: "Sales Per Employee Calculator", slug: "sales-per-employee-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 28, name: "Foot Traffic Conversion Calculator", slug: "foot-traffic-conversion-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 29, name: "Store Traffic Calculator", slug: "store-traffic-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 30, name: "Customer Count Calculator", slug: "customer-count-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 31, name: "Retail Discount Calculator", slug: "retail-discount-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 32, name: "Clearance Pricing Calculator", slug: "clearance-pricing-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 33, name: "Stock Availability Calculator", slug: "stock-availability-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 34, name: "Stockout Rate Calculator", slug: "stockout-rate-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 35, name: "Inventory Accuracy Calculator", slug: "inventory-accuracy-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 36, name: "Store Replenishment Planner", slug: "store-replenishment-planner", category: "Retail Operations Tools", isPro: false },
  { id: 37, name: "Shelf Capacity Calculator", slug: "shelf-capacity-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 38, name: "Display Capacity Calculator", slug: "display-capacity-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 39, name: "Shelf Space Planner", slug: "shelf-space-planner", category: "Retail Operations Tools", isPro: false },
  { id: 40, name: "Store Layout Planner", slug: "store-layout-planner", category: "Retail Operations Tools", isPro: false },
  { id: 41, name: "Staff Scheduling Calculator", slug: "staff-scheduling-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 42, name: "Labor Cost Calculator", slug: "labor-cost-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 43, name: "Store Payroll Calculator", slug: "store-payroll-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 44, name: "Store Operating Cost Calculator", slug: "store-operating-cost-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 45, name: "Store Budget Calculator", slug: "store-budget-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 46, name: "Store Expense Tracker", slug: "store-expense-tracker", category: "Retail Operations Tools", isPro: false },
  { id: 47, name: "Retail Promotion Calculator", slug: "retail-promotion-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 48, name: "Coupon Impact Calculator", slug: "coupon-impact-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 49, name: "Discount Profit Impact", slug: "discount-profit-impact", category: "Retail Operations Tools", isPro: false },
  { id: 50, name: "Customer Purchase Frequency", slug: "customer-purchase-frequency", category: "Retail Operations Tools", isPro: false },
  { id: 51, name: "Repeat Customer Rate", slug: "repeat-customer-rate", category: "Retail Operations Tools", isPro: false },
  { id: 52, name: "Retail KPI Calculator", slug: "retail-kpi-calculator", category: "Retail Operations Tools", isPro: false },
  { id: 53, name: "Store Opening Checklist", slug: "store-opening-checklist", category: "Retail Operations Tools", isPro: false },
  { id: 54, name: "Store Closing Checklist", slug: "store-closing-checklist", category: "Retail Operations Tools", isPro: false },
  { id: 55, name: "Store Audit Checklist", slug: "store-audit-checklist", category: "Retail Operations Tools", isPro: false },
  { id: 56, name: "Merchandising Checklist", slug: "merchandising-checklist", category: "Retail Operations Tools", isPro: false },
  { id: 57, name: "Retail Staff Checklist", slug: "retail-staff-checklist", category: "Retail Operations Tools", isPro: false },
  { id: 58, name: "Inventory Count Checklist", slug: "inventory-count-checklist", category: "Retail Operations Tools", isPro: false },
  { id: 59, name: "Store Maintenance Checklist", slug: "store-maintenance-checklist", category: "Retail Operations Tools", isPro: false },
  { id: 60, name: "Store Performance Report", slug: "store-performance-report", category: "Retail Operations Tools", isPro: false },

  // --- ⚡ 40 PRO / SAAS TOOLS (IDs 61-100 | isPro: true) ---
  { id: 61, name: "Retail Operations Workspace", slug: "retail-operations-workspace", category: "Retail Operations Tools", isPro: true },
  { id: 62, name: "Store Management Workspace", slug: "store-management-workspace", category: "Retail Operations Tools", isPro: true },
  { id: 63, name: "Multi-Store Management Workspace", slug: "multi-store-management-workspace", category: "Retail Operations Tools", isPro: true },
  { id: 64, name: "Store Sales Dashboard", slug: "store-sales-dashboard", category: "Retail Operations Tools", isPro: true },
  { id: 65, name: "Store Traffic Dashboard", slug: "store-traffic-dashboard", category: "Retail Operations Tools", isPro: true },
  { id: 66, name: "Conversion Analytics Workspace", slug: "conversion-analytics-workspace", category: "Retail Operations Tools", isPro: true },
  { id: 67, name: "Retail Margin Dashboard", slug: "retail-margin-dashboard", category: "Retail Operations Tools", isPro: true },
  { id: 68, name: "Inventory Performance Workspace", slug: "inventory-performance-workspace", category: "Retail Operations Tools", isPro: true },
  { id: 69, name: "Sell-Through Analytics", slug: "sell-through-analytics", category: "Retail Operations Tools", isPro: true },
  { id: 70, name: "Inventory Turnover Dashboard", slug: "inventory-turnover-dashboard", category: "Retail Operations Tools", isPro: true },
  { id: 71, name: "Shrinkage Management Workspace", slug: "shrinkage-management-workspace", category: "Retail Operations Tools", isPro: true },
  { id: 72, name: "Store Replenishment Workspace", slug: "store-replenishment-workspace", category: "Retail Operations Tools", isPro: true },
  { id: 73, name: "Shelf Planning Workspace", slug: "shelf-planning-workspace", category: "Retail Operations Tools", isPro: true },
  { id: 74, name: "Store Layout Workspace", slug: "store-layout-workspace", category: "Retail Operations Tools", isPro: true },
  { id: 75, name: "Merchandising Workspace", slug: "merchandising-workspace", category: "Retail Operations Tools", isPro: true },
  { id: 76, name: "Retail Staffing Workspace", slug: "retail-staffing-workspace", category: "Retail Operations Tools", isPro: true },
  { id: 77, name: "Staff Scheduling Workspace", slug: "staff-scheduling-workspace", category: "Retail Operations Tools", isPro: true },
  { id: 78, name: "Retail Labor Dashboard", slug: "retail-labor-dashboard", category: "Retail Operations Tools", isPro: true },
  { id: 79, name: "Store Cost Dashboard", slug: "store-cost-dashboard", category: "Retail Operations Tools", isPro: true },
  { id: 80, name: "Store Profitability Workspace", slug: "store-profitability-workspace", category: "Retail Operations Tools", isPro: true },
  { id: 81, name: "Retail Promotion Workspace", slug: "retail-promotion-workspace", category: "Retail Operations Tools", isPro: true },
  { id: 82, name: "Promotion Performance Dashboard", slug: "promotion-performance-dashboard", category: "Retail Operations Tools", isPro: true },
  { id: 83, name: "Customer Basket Analytics", slug: "customer-basket-analytics", category: "Retail Operations Tools", isPro: true },
  { id: 84, name: "Repeat Customer Analytics", slug: "repeat-customer-analytics", category: "Retail Operations Tools", isPro: true },
  { id: 85, name: "Store KPI Dashboard", slug: "store-kpi-dashboard", category: "Retail Operations Tools", isPro: true },
  { id: 86, name: "Retail Audit Workspace", slug: "retail-audit-workspace", category: "Retail Operations Tools", isPro: true },
  { id: 87, name: "Store Inspection Workspace", slug: "store-inspection-workspace", category: "Retail Operations Tools", isPro: true },
  { id: 88, name: "Retail Incident Management", slug: "retail-incident-management", category: "Retail Operations Tools", isPro: true },
  { id: 89, name: "Store Budget Workspace", slug: "store-budget-workspace", category: "Retail Operations Tools", isPro: true },
  { id: 90, name: "Retail Forecasting Workspace", slug: "retail-forecasting-workspace", category: "Retail Operations Tools", isPro: true },
  { id: 91, name: "Retail Data Importer", slug: "retail-data-importer", category: "Retail Operations Tools", isPro: true },
  { id: 92, name: "Retail Data Exporter", slug: "retail-data-exporter", category: "Retail Operations Tools", isPro: true },
  { id: 93, name: "Retail API Workspace", slug: "retail-api-workspace", category: "Retail Operations Tools", isPro: true },
  { id: 94, name: "Retail Workflow Automation", slug: "retail-workflow-automation", category: "Retail Operations Tools", isPro: true },
  { id: 95, name: "Store Alert Engine", slug: "store-alert-engine", category: "Retail Operations Tools", isPro: true },
  { id: 96, name: "Retail Intelligence Platform", slug: "retail-intelligence-platform", category: "Retail Operations Tools", isPro: true },
  { id: 97, name: "Multi-Store Analytics Platform", slug: "multi-store-analytics-platform", category: "Retail Operations Tools", isPro: true },
  { id: 98, name: "Enterprise Retail Platform", slug: "enterprise-retail-platform", category: "Retail Operations Tools", isPro: true },
  { id: 99, name: "Retail Operations Platform", slug: "retail-operations-platform", category: "Retail Operations Tools", isPro: true },
  { id: 100, name: "Retail Command Center", slug: "retail-command-center", category: "Retail Operations Tools", isPro: true }
];