export interface ScienceTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const scienceToolsList: ScienceTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "Scientific Calculator", slug: "scientific-calculator", category: "Science Tools", isPro: false },
  { id: 2, name: "Scientific Notation Converter", slug: "scientific-notation-converter", category: "Science Tools", isPro: false },
  { id: 3, name: "Significant Figures Calculator", slug: "significant-figures-calculator", category: "Science Tools", isPro: false },
  { id: 4, name: "Molar Mass Calculator", slug: "molar-mass-calculator", category: "Science Tools", isPro: false },
  { id: 5, name: "Mole Calculator", slug: "mole-calculator", category: "Science Tools", isPro: false },
  { id: 6, name: "Molarity Calculator", slug: "molarity-calculator", category: "Science Tools", isPro: false },
  { id: 7, name: "Dilution Calculator", slug: "dilution-calculator", category: "Science Tools", isPro: false },
  { id: 8, name: "Stoichiometry Calculator", slug: "stoichiometry-calculator", category: "Science Tools", isPro: false },
  { id: 9, name: "Chemical Equation Balancer", slug: "chemical-equation-balancer", category: "Science Tools", isPro: false },
  { id: 10, name: "Limiting Reagent Calculator", slug: "limiting-reagent-calculator", category: "Science Tools", isPro: false },
  { id: 11, name: "Percent Yield Calculator", slug: "percent-yield-calculator", category: "Science Tools", isPro: false },
  { id: 12, name: "pH Calculator", slug: "ph-calculator", category: "Science Tools", isPro: false },
  { id: 13, name: "Buffer Calculator", slug: "buffer-calculator", category: "Science Tools", isPro: false },
  { id: 14, name: "Ideal Gas Law Calculator", slug: "ideal-gas-law-calculator", category: "Science Tools", isPro: false },
  { id: 15, name: "Specific Heat Calculator", slug: "specific-heat-calculator", category: "Science Tools", isPro: false },
  { id: 16, name: "Wavelength Calculator", slug: "wavelength-calculator", category: "Science Tools", isPro: false },
  { id: 17, name: "Photon Energy Calculator", slug: "photon-energy-calculator", category: "Science Tools", isPro: false },
  { id: 18, name: "Lens Formula Calculator", slug: "lens-formula-calculator", category: "Science Tools", isPro: false },
  { id: 19, name: "Half-Life Calculator", slug: "half-life-calculator", category: "Science Tools", isPro: false },
  { id: 20, name: "Scientific Data Analyzer", slug: "scientific-data-analyzer", category: "Science Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Significant Figures Counter", slug: "significant-figures-counter", category: "Science Tools", isPro: false },
  { id: 22, name: "Scientific Unit Converter", slug: "scientific-unit-converter", category: "Science Tools", isPro: false },
  { id: 23, name: "SI Unit Converter", slug: "si-unit-converter", category: "Science Tools", isPro: false },
  { id: 24, name: "Prefix Converter", slug: "prefix-converter", category: "Science Tools", isPro: false },
  { id: 25, name: "Density Calculator", slug: "density-calculator", category: "Science Tools", isPro: false },
  { id: 26, name: "Mass Calculator", slug: "mass-calculator", category: "Science Tools", isPro: false },
  { id: 27, name: "Volume Calculator", slug: "volume-calculator", category: "Science Tools", isPro: false },
  { id: 28, name: "Molality Calculator", slug: "molality-calculator", category: "Science Tools", isPro: false },
  { id: 29, name: "Normality Calculator", slug: "normality-calculator", category: "Science Tools", isPro: false },
  { id: 30, name: "Concentration Calculator", slug: "concentration-calculator", category: "Science Tools", isPro: false },
  { id: 31, name: "Solution Preparation Calculator", slug: "solution-preparation-calculator", category: "Science Tools", isPro: false },
  { id: 32, name: "Percent Composition Calculator", slug: "percent-composition-calculator", category: "Science Tools", isPro: false },
  { id: 33, name: "Empirical Formula Calculator", slug: "empirical-formula-calculator", category: "Science Tools", isPro: false },
  { id: 34, name: "Molecular Formula Calculator", slug: "molecular-formula-calculator", category: "Science Tools", isPro: false },
  { id: 35, name: "Theoretical Yield Calculator", slug: "theoretical-yield-calculator", category: "Science Tools", isPro: false },
  { id: 36, name: "pOH Calculator", slug: "poh-calculator", category: "Science Tools", isPro: false },
  { id: 37, name: "H+ Concentration Calculator", slug: "h-plus-concentration-calculator", category: "Science Tools", isPro: false },
  { id: 38, name: "OH- Concentration Calculator", slug: "oh-minus-concentration-calculator", category: "Science Tools", isPro: false },
  { id: 39, name: "Henderson-Hasselbalch Calculator", slug: "henderson-hasselbalch-calculator", category: "Science Tools", isPro: false },
  { id: 40, name: "Gas Law Calculator", slug: "gas-law-calculator", category: "Science Tools", isPro: false },
  { id: 41, name: "Combined Gas Law Calculator", slug: "combined-gas-law-calculator", category: "Science Tools", isPro: false },
  { id: 42, name: "Boyle's Law Calculator", slug: "boyles-law-calculator", category: "Science Tools", isPro: false },
  { id: 43, name: "Charles's Law Calculator", slug: "charles-law-calculator", category: "Science Tools", isPro: false },
  { id: 44, name: "Avogadro's Law Calculator", slug: "avogadros-law-calculator", category: "Science Tools", isPro: false },
  { id: 45, name: "Thermodynamics Calculator", slug: "thermodynamics-calculator", category: "Science Tools", isPro: false },
  { id: 46, name: "Heat Capacity Calculator", slug: "heat-capacity-calculator", category: "Science Tools", isPro: false },
  { id: 47, name: "Heat Energy Calculator", slug: "heat-energy-calculator", category: "Science Tools", isPro: false },
  { id: 48, name: "Frequency Calculator", slug: "frequency-calculator", category: "Science Tools", isPro: false },
  { id: 49, name: "Wave Speed Calculator", slug: "wave-speed-calculator", category: "Science Tools", isPro: false },
  { id: 50, name: "Light Speed Calculator", slug: "light-speed-calculator", category: "Science Tools", isPro: false },
  { id: 51, name: "Optics Calculator", slug: "optics-calculator", category: "Science Tools", isPro: false },
  { id: 52, name: "Magnification Calculator", slug: "magnification-calculator", category: "Science Tools", isPro: false },
  { id: 53, name: "Radioactive Decay Calculator", slug: "radioactive-decay-calculator", category: "Science Tools", isPro: false },
  { id: 54, name: "Nuclear Energy Calculator", slug: "nuclear-energy-calculator", category: "Science Tools", isPro: false },
  { id: 55, name: "Force Calculator", slug: "force-calculator", category: "Science Tools", isPro: false },
  { id: 56, name: "Acceleration Calculator", slug: "acceleration-calculator", category: "Science Tools", isPro: false },
  { id: 57, name: "Momentum Calculator", slug: "momentum-calculator", category: "Science Tools", isPro: false },
  { id: 58, name: "Kinetic Energy Calculator", slug: "kinetic-energy-calculator", category: "Science Tools", isPro: false },
  { id: 59, name: "Potential Energy Calculator", slug: "potential-energy-calculator", category: "Science Tools", isPro: false },
  { id: 60, name: "Gravitational Force Calculator", slug: "gravitational-force-calculator", category: "Science Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Chemistry Calculation Workspace", slug: "chemistry-calculation-workspace", category: "Science Tools", isPro: true },
  { id: 62, name: "Stoichiometry Workspace", slug: "stoichiometry-workspace", category: "Science Tools", isPro: true },
  { id: 63, name: "Chemical Reaction Analyzer", slug: "chemical-reaction-analyzer", category: "Science Tools", isPro: true },
  { id: 64, name: "Solution Preparation Workspace", slug: "solution-preparation-workspace", category: "Science Tools", isPro: true },
  { id: 65, name: "Laboratory Dilution Planner", slug: "laboratory-dilution-planner", category: "Science Tools", isPro: true },
  { id: 66, name: "Laboratory Concentration Analyzer", slug: "laboratory-concentration-analyzer", category: "Science Tools", isPro: true },
  { id: 67, name: "Chemical Property Lookup Workspace", slug: "chemical-property-lookup-workspace", category: "Science Tools", isPro: true },
  { id: 68, name: "Molecular Weight Database", slug: "molecular-weight-database", category: "Science Tools", isPro: true },
  { id: 69, name: "Periodic Table Intelligence", slug: "periodic-table-intelligence", category: "Science Tools", isPro: true },
  { id: 70, name: "Chemical Formula Analyzer", slug: "chemical-formula-analyzer", category: "Science Tools", isPro: true },
  { id: 71, name: "Reaction Equation Workspace", slug: "reaction-equation-workspace", category: "Science Tools", isPro: true },
  { id: 72, name: "Thermodynamics Analysis Workspace", slug: "thermodynamics-analysis-workspace", category: "Science Tools", isPro: true },
  { id: 73, name: "Gas Law Analysis Workspace", slug: "gas-law-analysis-workspace", category: "Science Tools", isPro: true },
  { id: 74, name: "Physics Calculation Workspace", slug: "physics-calculation-workspace", category: "Science Tools", isPro: true },
  { id: 75, name: "Mechanics Analysis Workspace", slug: "mechanics-analysis-workspace", category: "Science Tools", isPro: true },
  { id: 76, name: "Energy Analysis Workspace", slug: "energy-analysis-workspace", category: "Science Tools", isPro: true },
  { id: 77, name: "Wave Analysis Workspace", slug: "wave-analysis-workspace", category: "Science Tools", isPro: true },
  { id: 78, name: "Optics Analysis Workspace", slug: "optics-analysis-workspace", category: "Science Tools", isPro: true },
  { id: 79, name: "Nuclear Decay Analysis", slug: "nuclear-decay-analysis", category: "Science Tools", isPro: true },
  { id: 80, name: "Radiation Calculation Workspace", slug: "radiation-calculation-workspace", category: "Science Tools", isPro: true },
  { id: 81, name: "Scientific Data Converter", slug: "scientific-data-converter", category: "Science Tools", isPro: true },
  { id: 82, name: "Experimental Data Calculator", slug: "experimental-data-calculator", category: "Science Tools", isPro: true },
  { id: 83, name: "Error Propagation Calculator", slug: "error-propagation-calculator", category: "Science Tools", isPro: true },
  { id: 84, name: "Measurement Uncertainty Analyzer", slug: "measurement-uncertainty-analyzer", category: "Science Tools", isPro: true },
  { id: 85, name: "Statistical Significance Calculator", slug: "statistical-significance-calculator", category: "Science Tools", isPro: true },
  { id: 86, name: "Experimental Design Planner", slug: "experimental-design-planner", category: "Science Tools", isPro: true },
  { id: 87, name: "Laboratory Notebook Workspace", slug: "laboratory-notebook-workspace", category: "Science Tools", isPro: true },
  { id: 88, name: "Research Data Workspace", slug: "research-data-workspace", category: "Science Tools", isPro: true },
  { id: 89, name: "Scientific Graph Generator", slug: "scientific-graph-generator", category: "Science Tools", isPro: true },
  { id: 90, name: "Scientific Report Generator", slug: "scientific-report-generator", category: "Science Tools", isPro: true },
  { id: 91, name: "Scientific Formula Library", slug: "scientific-formula-library", category: "Science Tools", isPro: true },
  { id: 92, name: "Scientific Reference Workspace", slug: "scientific-reference-workspace", category: "Science Tools", isPro: true },
  { id: 93, name: "Research Calculation Dashboard", slug: "research-calculation-dashboard", category: "Science Tools", isPro: true },
  { id: 94, name: "Laboratory Operations Workspace", slug: "laboratory-operations-workspace", category: "Science Tools", isPro: true },
  { id: 95, name: "Science Education Workspace", slug: "science-education-workspace", category: "Science Tools", isPro: true },
  { id: 96, name: "Scientific Data Intelligence Platform", slug: "scientific-data-intelligence-platform", category: "Science Tools", isPro: true },
  { id: 97, name: "Research Analysis Command Center", slug: "research-analysis-command-center", category: "Science Tools", isPro: true },
  { id: 98, name: "Laboratory Intelligence Workspace", slug: "laboratory-intelligence-workspace", category: "Science Tools", isPro: true },
  { id: 99, name: "Scientific Computing Workspace", slug: "scientific-computing-workspace", category: "Science Tools", isPro: true },
  { id: 100, name: "Professional Science Research Platform", slug: "professional-science-research-platform", category: "Science Tools", isPro: true }
];