export interface SearchResearchTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const searchResearchToolsList: SearchResearchTool[] = [
  // --- 🔥 PRIORITY 20 FREE TOOLS (IDs 1-20 | isPro: false) ---
  { id: 1, name: "Advanced Search Query Generator", slug: "advanced-search-query-generator", category: "Search & Research Tools", isPro: false },
  { id: 2, name: "Boolean Search Generator", slug: "boolean-search-generator", category: "Search & Research Tools", isPro: false },
  { id: 3, name: "Google Search Operator Builder", slug: "google-search-operator-builder", category: "Search & Research Tools", isPro: false },
  { id: 4, name: "Search Intent Analyzer", slug: "search-intent-analyzer", category: "Search & Research Tools", isPro: false },
  { id: 5, name: "Query Expansion Tool", slug: "query-expansion-tool", category: "Search & Research Tools", isPro: false },
  { id: 6, name: "Related Query Generator", slug: "related-query-generator", category: "Search & Research Tools", isPro: false },
  { id: 7, name: "Research Question Generator", slug: "research-question-generator-search", category: "Search & Research Tools", isPro: false },
  { id: 8, name: "Research Keyword Mapper", slug: "research-keyword-mapper", category: "Search & Research Tools", isPro: false },
  { id: 9, name: "Search Result Organizer", slug: "search-result-organizer", category: "Search & Research Tools", isPro: false },
  { id: 10, name: "Source Comparison Tool", slug: "source-comparison-tool", category: "Search & Research Tools", isPro: false },
  { id: 11, name: "Source Evaluation Tool", slug: "source-evaluation-tool", category: "Search & Research Tools", isPro: false },
  { id: 12, name: "Research Source Tracker", slug: "research-source-tracker", category: "Search & Research Tools", isPro: false },
  { id: 13, name: "Evidence Tracker", slug: "evidence-tracker", category: "Search & Research Tools", isPro: false },
  { id: 14, name: "Public Dataset Finder", slug: "public-dataset-finder", category: "Search & Research Tools", isPro: false },
  { id: 15, name: "Dataset Comparison Tool", slug: "dataset-comparison-tool", category: "Search & Research Tools", isPro: false },
  { id: 16, name: "Competitor Research Tracker", slug: "competitor-research-tracker", category: "Search & Research Tools", isPro: false },
  { id: 17, name: "Market Research Question Generator", slug: "market-research-question-generator", category: "Search & Research Tools", isPro: false },
  { id: 18, name: "Fact Verification Tool", slug: "fact-verification-tool", category: "Search & Research Tools", isPro: false },
  { id: 19, name: "Competitive Intelligence Tracker", slug: "competitive-intelligence-tracker", category: "Search & Research Tools", isPro: false },
  { id: 20, name: "Web Research Planner", slug: "web-research-planner", category: "Search & Research Tools", isPro: false },

  // --- REMAINING 40 CORE FREE TOOLS (IDs 21-60 | isPro: false) ---
  { id: 21, name: "Search Query Builder", slug: "search-query-builder", category: "Search & Research Tools", isPro: false },
  { id: 22, name: "Boolean Search String Builder", slug: "boolean-search-string-builder", category: "Search & Research Tools", isPro: false },
  { id: 23, name: "Search Operator Reference", slug: "search-operator-reference", category: "Search & Research Tools", isPro: false },
  { id: 24, name: "Exact Match Search Builder", slug: "exact-match-search-builder", category: "Search & Research Tools", isPro: false },
  { id: 25, name: "Exclusion Search Builder", slug: "exclusion-search-builder", category: "Search & Research Tools", isPro: false },
  { id: 26, name: "Site Search Query Builder", slug: "site-search-query-builder", category: "Search & Research Tools", isPro: false },
  { id: 27, name: "Filetype Search Builder", slug: "filetype-search-builder", category: "Search & Research Tools", isPro: false },
  { id: 28, name: "Search Intent Classifier", slug: "search-intent-classifier", category: "Search & Research Tools", isPro: false },
  { id: 29, name: "Search Query Expander", slug: "search-query-expander", category: "Search & Research Tools", isPro: false },
  { id: 30, name: "Keyword Question Finder", slug: "keyword-question-finder", category: "Search & Research Tools", isPro: false },
  { id: 31, name: "Search Topic Generator", slug: "search-topic-generator", category: "Search & Research Tools", isPro: false },
  { id: 32, name: "Research Topic Generator", slug: "research-topic-generator", category: "Search & Research Tools", isPro: false },
  { id: 33, name: "Search Result Notes", slug: "search-result-notes", category: "Search & Research Tools", isPro: false },
  { id: 34, name: "Research Notes Organizer", slug: "research-notes-organizer", category: "Search & Research Tools", isPro: false },
  { id: 35, name: "Source List Organizer", slug: "source-list-organizer", category: "Search & Research Tools", isPro: false },
  { id: 36, name: "Source Credibility Checklist", slug: "source-credibility-checklist", category: "Search & Research Tools", isPro: false },
  { id: 37, name: "Research Citation Tracker", slug: "research-citation-tracker", category: "Search & Research Tools", isPro: false },
  { id: 38, name: "Research Reading Tracker", slug: "research-reading-tracker", category: "Search & Research Tools", isPro: false },
  { id: 39, name: "Research Timeline Generator", slug: "research-timeline-generator", category: "Search & Research Tools", isPro: false },
  { id: 40, name: "Research Project Planner", slug: "research-project-planner", category: "Search & Research Tools", isPro: false },
  { id: 41, name: "Literature Search Planner", slug: "literature-search-planner", category: "Search & Research Tools", isPro: false },
  { id: 42, name: "Literature Review Tracker", slug: "literature-review-tracker", category: "Search & Research Tools", isPro: false },
  { id: 43, name: "Market Research Checklist", slug: "market-research-checklist", category: "Search & Research Tools", isPro: false },
  { id: 44, name: "Survey Question Generator", slug: "survey-question-generator", category: "Search & Research Tools", isPro: false },
  { id: 45, name: "Interview Question Generator", slug: "interview-question-generator", category: "Search & Research Tools", isPro: false },
  { id: 46, name: "Interview Research Planner", slug: "interview-research-planner", category: "Search & Research Tools", isPro: false },
  { id: 47, name: "Fact-Checking Checklist", slug: "fact-checking-checklist", category: "Search & Research Tools", isPro: false },
  { id: 48, name: "Claim Verification Tracker", slug: "claim-verification-tracker", category: "Search & Research Tools", isPro: false },
  { id: 49, name: "Research Evidence Matrix", slug: "research-evidence-matrix", category: "Search & Research Tools", isPro: false },
  { id: 50, name: "Data Source Directory", slug: "data-source-directory", category: "Search & Research Tools", isPro: false },
  { id: 51, name: "Research Dataset Organizer", slug: "research-dataset-organizer", category: "Search & Research Tools", isPro: false },
  { id: 52, name: "Research File Organizer", slug: "research-file-organizer", category: "Search & Research Tools", isPro: false },
  { id: 53, name: "Web Research Checklist", slug: "web-research-checklist", category: "Search & Research Tools", isPro: false },
  { id: 54, name: "Research Session Timer", slug: "research-session-timer", category: "Search & Research Tools", isPro: false },
  { id: 55, name: "Research Progress Tracker", slug: "research-progress-tracker", category: "Search & Research Tools", isPro: false },
  { id: 56, name: "Research Task Tracker", slug: "research-task-tracker", category: "Search & Research Tools", isPro: false },
  { id: 57, name: "Research Bookmark Organizer", slug: "research-bookmark-organizer", category: "Search & Research Tools", isPro: false },
  { id: 58, name: "Research Link Organizer", slug: "research-link-organizer", category: "Search & Research Tools", isPro: false },
  { id: 59, name: "Research Tag Generator", slug: "research-tag-generator", category: "Search & Research Tools", isPro: false },
  { id: 60, name: "Research Report Outline Generator", slug: "research-report-outline-generator", category: "Search & Research Tools", isPro: false },

  // --- ⚡ 40 PRO / SAAS TOOLS (IDs 61-100 | isPro: true) ---
  { id: 61, name: "Professional Research Workspace", slug: "professional-research-workspace", category: "Search & Research Tools", isPro: true },
  { id: 62, name: "Fact Verification Workspace", slug: "fact-verification-workspace", category: "Search & Research Tools", isPro: true },
  { id: 63, name: "Competitive Intelligence Dashboard", slug: "competitive-intelligence-dashboard", category: "Search & Research Tools", isPro: true },
  { id: 64, name: "Advanced Web Research Dashboard", slug: "advanced-web-research-dashboard", category: "Search & Research Tools", isPro: true },
  { id: 65, name: "Research Intelligence Dashboard", slug: "research-intelligence-dashboard", category: "Search & Research Tools", isPro: true },
  { id: 66, name: "Multi-Source Research Workspace", slug: "multi-source-research-workspace", category: "Search & Research Tools", isPro: true },
  { id: 67, name: "Competitive Research Workspace", slug: "competitive-research-workspace", category: "Search & Research Tools", isPro: true },
  { id: 68, name: "Market Intelligence Workspace", slug: "market-intelligence-workspace", category: "Search & Research Tools", isPro: true },
  { id: 69, name: "Industry Research Workspace", slug: "industry-research-workspace", category: "Search & Research Tools", isPro: true },
  { id: 70, name: "Company Research Workspace", slug: "company-research-workspace", category: "Search & Research Tools", isPro: true },
  { id: 71, name: "Customer Research Workspace", slug: "customer-research-workspace", category: "Search & Research Tools", isPro: true },
  { id: 72, name: "Product Research Workspace", slug: "product-research-workspace", category: "Search & Research Tools", isPro: true },
  { id: 73, name: "Topic Intelligence Dashboard", slug: "topic-intelligence-dashboard", category: "Search & Research Tools", isPro: true },
  { id: 74, name: "Search Intent Intelligence Engine", slug: "search-intent-intelligence-engine", category: "Search & Research Tools", isPro: true },
  { id: 75, name: "Query Intelligence Workspace", slug: "query-intelligence-workspace", category: "Search & Research Tools", isPro: true },
  { id: 76, name: "Search Landscape Analyzer", slug: "search-landscape-analyzer", category: "Search & Research Tools", isPro: true },
  { id: 77, name: "Source Intelligence Dashboard", slug: "source-intelligence-dashboard", category: "Search & Research Tools", isPro: true },
  { id: 78, name: "Source Reliability Scoring Engine", slug: "source-reliability-scoring-engine", category: "Search & Research Tools", isPro: true },
  { id: 79, name: "Evidence Management Workspace", slug: "evidence-management-workspace", category: "Search & Research Tools", isPro: true },
  { id: 80, name: "Claim-Evidence Mapping Workspace", slug: "claim-evidence-mapping-workspace", category: "Search & Research Tools", isPro: true },
  { id: 81, name: "Research Knowledge Base", slug: "research-knowledge-base", category: "Search & Research Tools", isPro: true },
  { id: 82, name: "Research Bookmark Database", slug: "research-bookmark-database", category: "Search & Research Tools", isPro: true },
  { id: 83, name: "Research Dataset Management", slug: "research-dataset-management", category: "Search & Research Tools", isPro: true },
  { id: 84, name: "Dataset Discovery Workspace", slug: "dataset-discovery-workspace", category: "Search & Research Tools", isPro: true },
  { id: 85, name: "Research Collaboration Workspace", slug: "research-collaboration-workspace", category: "Search & Research Tools", isPro: true },
  { id: 86, name: "Literature Review Management", slug: "literature-review-management", category: "Search & Research Tools", isPro: true },
  { id: 87, name: "Research Citation Management", slug: "research-citation-management", category: "Search & Research Tools", isPro: true },
  { id: 88, name: "Research Project Management", slug: "research-project-management", category: "Search & Research Tools", isPro: true },
  { id: 89, name: "Research Timeline Dashboard", slug: "research-timeline-dashboard", category: "Search & Research Tools", isPro: true },
  { id: 90, name: "Research Report Builder", slug: "research-report-builder", category: "Search & Research Tools", isPro: true },
  { id: 91, name: "Research Brief Generator", slug: "research-brief-generator", category: "Search & Research Tools", isPro: true },
  { id: 92, name: "Market Research Analytics", slug: "market-research-analytics", category: "Search & Research Tools", isPro: true },
  { id: 93, name: "Research Data Import Workspace", slug: "research-data-import-workspace", category: "Search & Research Tools", isPro: true },
  { id: 94, name: "Research Data Export Workspace", slug: "research-data-export-workspace", category: "Search & Research Tools", isPro: true },
  { id: 95, name: "Research API Workspace", slug: "research-api-workspace", category: "Search & Research Tools", isPro: true },
  { id: 96, name: "Research Automation Workspace", slug: "research-automation-workspace", category: "Search & Research Tools", isPro: true },
  { id: 97, name: "Research Monitoring Workspace", slug: "research-monitoring-workspace", category: "Search & Research Tools", isPro: true },
  { id: 98, name: "Research Alert Engine", slug: "research-alert-engine", category: "Search & Research Tools", isPro: true },
  { id: 99, name: "Research Intelligence Platform", slug: "research-intelligence-platform", category: "Search & Research Tools", isPro: true },
  { id: 100, name: "Professional Research Command Center", slug: "professional-research-command-center", category: "Search & Research Tools", isPro: true }
];