export interface SecurityTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const securityToolsList: SecurityTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-16) ---
  { id: 1, name: "Password Strength Checker", slug: "password-strength-checker", category: "Security Tools", isPro: false },
  { id: 2, name: "Password Generator", slug: "password-generator-security", category: "Security Tools", isPro: false },
  { id: 3, name: "Website Security Scanner", slug: "website-security-scanner", category: "Security Tools", isPro: false },
  { id: 4, name: "SSL Security Checker", slug: "ssl-security-checker", category: "Security Tools", isPro: false },
  { id: 5, name: "Security Header Checker", slug: "security-header-checker", category: "Security Tools", isPro: false },
  { id: 6, name: "Domain Reputation Checker", slug: "domain-reputation-checker", category: "Security Tools", isPro: false },
  { id: 7, name: "IP Reputation Checker", slug: "ip-reputation-checker", category: "Security Tools", isPro: false },
  { id: 8, name: "Phishing URL Analyzer", slug: "phishing-url-analyzer", category: "Security Tools", isPro: false },
  { id: 9, name: "Website Malware Checker", slug: "website-malware-checker", category: "Security Tools", isPro: false },
  { id: 10, name: "DNSSEC Checker", slug: "dnssec-checker", category: "Security Tools", isPro: false },
  { id: 11, name: "SPF Security Checker", slug: "spf-security-checker", category: "Security Tools", isPro: false },
  { id: 12, name: "DKIM Security Checker", slug: "dkim-security-checker", category: "Security Tools", isPro: false },
  { id: 13, name: "DMARC Security Checker", slug: "dmarc-security-checker", category: "Security Tools", isPro: false },
  { id: 14, name: "Email Security Analyzer", slug: "email-security-analyzer", category: "Security Tools", isPro: false },
  { id: 15, name: "Breach Exposure Checker", slug: "breach-exposure-checker", category: "Security Tools", isPro: false },
  { id: 16, name: "JWT Security Analyzer", slug: "jwt-security-analyzer", category: "Security Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (17-60) ---
  { id: 17, name: "Passphrase Generator", slug: "passphrase-generator", category: "Security Tools", isPro: false },
  { id: 18, name: "Secure Username Generator", slug: "secure-username-generator", category: "Security Tools", isPro: false },
  { id: 19, name: "Random Token Generator", slug: "random-token-generator", category: "Security Tools", isPro: false },
  { id: 20, name: "Random String Generator", slug: "random-string-generator-security", category: "Security Tools", isPro: false },
  { id: 21, name: "HTTP Security Header Analyzer", slug: "http-security-header-analyzer", category: "Security Tools", isPro: false },
  { id: 22, name: "CSP Checker", slug: "csp-checker", category: "Security Tools", isPro: false },
  { id: 23, name: "HSTS Checker", slug: "hsts-checker", category: "Security Tools", isPro: false },
  { id: 24, name: "CORS Checker", slug: "cors-checker", category: "Security Tools", isPro: false },
  { id: 25, name: "Cookie Security Checker", slug: "cookie-security-checker", category: "Security Tools", isPro: false },
  { id: 26, name: "Secure Cookie Checker", slug: "secure-cookie-checker", category: "Security Tools", isPro: false },
  { id: 27, name: "TLS Version Checker", slug: "tls-version-checker", category: "Security Tools", isPro: false },
  { id: 28, name: "Certificate Chain Checker", slug: "certificate-chain-checker", category: "Security Tools", isPro: false },
  { id: 29, name: "Certificate Transparency Checker", slug: "certificate-transparency-checker", category: "Security Tools", isPro: false },
  { id: 30, name: "Certificate Expiration Monitor", slug: "certificate-expiration-monitor", category: "Security Tools", isPro: false },
  { id: 31, name: "Domain Security Checker", slug: "domain-security-checker", category: "Security Tools", isPro: false },
  { id: 32, name: "IP Blacklist Checker", slug: "ip-blacklist-checker", category: "Security Tools", isPro: false },
  { id: 33, name: "Email Blacklist Checker", slug: "email-blacklist-checker", category: "Security Tools", isPro: false },
  { id: 34, name: "URL Reputation Checker", slug: "url-reputation-checker", category: "Security Tools", isPro: false },
  { id: 35, name: "Malicious URL Checker", slug: "malicious-url-checker", category: "Security Tools", isPro: false },
  { id: 36, name: "Web Security Headers Report", slug: "web-security-headers-report", category: "Security Tools", isPro: false },
  { id: 37, name: "DNS Security Checker", slug: "dns-security-checker", category: "Security Tools", isPro: false },
  { id: 38, name: "Email Spoofing Checker", slug: "email-spoofing-checker", category: "Security Tools", isPro: false },
  { id: 39, name: "Password Breach Checker", slug: "password-breach-checker", category: "Security Tools", isPro: false },
  { id: 40, name: "Username Exposure Checker", slug: "username-exposure-checker", category: "Security Tools", isPro: false },
  { id: 41, name: "Privacy Risk Checker", slug: "privacy-risk-checker", category: "Security Tools", isPro: false },
  { id: 42, name: "Tracking Technology Detector", slug: "tracking-technology-detector", category: "Security Tools", isPro: false },
  { id: 43, name: "Third-Party Tracker Detector", slug: "third-party-tracker-detector", category: "Security Tools", isPro: false },
  { id: 44, name: "Cookie Scanner", slug: "cookie-scanner", category: "Security Tools", isPro: false },
  { id: 45, name: "Cookie Risk Analyzer", slug: "cookie-risk-analyzer", category: "Security Tools", isPro: false },
  { id: 46, name: "Privacy Header Checker", slug: "privacy-header-checker", category: "Security Tools", isPro: false },
  { id: 47, name: "Robots Security Checker", slug: "robots-security-checker", category: "Security Tools", isPro: false },
  { id: 48, name: "Security.txt Validator", slug: "security-txt-validator", category: "Security Tools", isPro: false },
  { id: 49, name: "Security.txt Generator", slug: "security-txt-generator", category: "Security Tools", isPro: false },
  { id: 50, name: "Subresource Integrity Generator", slug: "subresource-integrity-generator", category: "Security Tools", isPro: false },
  { id: 51, name: "SRI Hash Generator", slug: "sri-hash-generator", category: "Security Tools", isPro: false },
  { id: 52, name: "File Hash Checker", slug: "file-hash-checker", category: "Security Tools", isPro: false },
  { id: 53, name: "File Integrity Checker", slug: "file-integrity-checker", category: "Security Tools", isPro: false },
  { id: 54, name: "Hash Comparison Tool", slug: "hash-comparison-tool", category: "Security Tools", isPro: false },
  { id: 55, name: "Digital Signature Checker", slug: "digital-signature-checker", category: "Security Tools", isPro: false },
  { id: 56, name: "Certificate Fingerprint Generator", slug: "certificate-fingerprint-generator", category: "Security Tools", isPro: false },
  { id: 57, name: "Base64 Security Decoder", slug: "base64-security-decoder", category: "Security Tools", isPro: false },
  { id: 58, name: "JWT Claims Inspector", slug: "jwt-claims-inspector", category: "Security Tools", isPro: false },
  { id: 59, name: "API Security Header Checker", slug: "api-security-header-checker", category: "Security Tools", isPro: false },
  { id: 60, name: "Webhook Signature Validator", slug: "webhook-signature-validator", category: "Security Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "API Security Audit", slug: "api-security-audit", category: "Security Tools", isPro: true },
  { id: 62, name: "Dependency Vulnerability Checker", slug: "dependency-vulnerability-checker", category: "Security Tools", isPro: true },
  { id: 63, name: "OWASP Risk Assessment", slug: "owasp-risk-assessment", category: "Security Tools", isPro: true },
  { id: 64, name: "Security Risk Scoring Engine", slug: "security-risk-scoring-engine", category: "Security Tools", isPro: true },
  { id: 65, name: "Website Vulnerability Assessment", slug: "website-vulnerability-assessment", category: "Security Tools", isPro: true },
  { id: 66, name: "Web Application Security Audit", slug: "web-application-security-audit", category: "Security Tools", isPro: true },
  { id: 67, name: "OWASP Checklist Generator", slug: "owasp-checklist-generator", category: "Security Tools", isPro: true },
  { id: 68, name: "Security Misconfiguration Scanner", slug: "security-misconfiguration-scanner", category: "Security Tools", isPro: true },
  { id: 69, name: "Package Security Audit", slug: "package-security-audit", category: "Security Tools", isPro: true },
  { id: 70, name: "Container Security Checker", slug: "container-security-checker", category: "Security Tools", isPro: true },
  { id: 71, name: "Docker Image Security Analyzer", slug: "docker-image-security-analyzer", category: "Security Tools", isPro: true },
  { id: 72, name: "Kubernetes Security Analyzer", slug: "kubernetes-security-analyzer", category: "Security Tools", isPro: true },
  { id: 73, name: "Cloud Security Configuration Checker", slug: "cloud-security-configuration-checker", category: "Security Tools", isPro: true },
  { id: 74, name: "API Authentication Tester", slug: "api-authentication-tester", category: "Security Tools", isPro: true },
  { id: 75, name: "OAuth Security Analyzer", slug: "oauth-security-analyzer", category: "Security Tools", isPro: true },
  { id: 76, name: "JWT Vulnerability Analyzer", slug: "jwt-vulnerability-analyzer", category: "Security Tools", isPro: true },
  { id: 77, name: "TLS Configuration Analyzer", slug: "tls-configuration-analyzer", category: "Security Tools", isPro: true },
  { id: 78, name: "SSL/TLS Security Audit", slug: "ssl-tls-security-audit", category: "Security Tools", isPro: true },
  { id: 79, name: "Certificate Inventory Manager", slug: "certificate-inventory-manager", category: "Security Tools", isPro: true },
  { id: 80, name: "Domain Security Monitoring", slug: "domain-security-monitoring", category: "Security Tools", isPro: true },
  { id: 81, name: "Attack Surface Inventory", slug: "attack-surface-inventory", category: "Security Tools", isPro: true },
  { id: 82, name: "Asset Discovery Dashboard", slug: "asset-discovery-dashboard", category: "Security Tools", isPro: true },
  { id: 83, name: "Vulnerability Risk Prioritizer", slug: "vulnerability-risk-prioritizer", category: "Security Tools", isPro: true },
  { id: 84, name: "Security Compliance Checklist", slug: "security-compliance-checklist", category: "Security Tools", isPro: true },
  { id: 85, name: "Security Policy Generator", slug: "security-policy-generator", category: "Security Tools", isPro: true },
  { id: 86, name: "Incident Response Checklist", slug: "incident-response-checklist", category: "Security Tools", isPro: true },
  { id: 87, name: "Security Incident Timeline", slug: "security-incident-timeline", category: "Security Tools", isPro: true },
  { id: 88, name: "Security Evidence Organizer", slug: "security-evidence-organizer", category: "Security Tools", isPro: true },
  { id: 89, name: "Security Audit Report Generator", slug: "security-audit-report-generator", category: "Security Tools", isPro: true },
  { id: 90, name: "Security Questionnaire Generator", slug: "security-questionnaire-generator", category: "Security Tools", isPro: true },
  { id: 91, name: "Vendor Security Assessment", slug: "vendor-security-assessment", category: "Security Tools", isPro: true },
  { id: 92, name: "Third-Party Risk Assessment", slug: "third-party-risk-assessment", category: "Security Tools", isPro: true },
  { id: 93, name: "SaaS Security Assessment", slug: "saas-security-assessment", category: "Security Tools", isPro: true },
  { id: 94, name: "Security Awareness Quiz Generator", slug: "security-awareness-quiz-generator", category: "Security Tools", isPro: true },
  { id: 95, name: "Phishing Simulation Planner", slug: "phishing-simulation-planner", category: "Security Tools", isPro: true },
  { id: 96, name: "Security Training Planner", slug: "security-training-planner", category: "Security Tools", isPro: true },
  { id: 97, name: "Security Monitoring Dashboard", slug: "security-monitoring-dashboard", category: "Security Tools", isPro: true },
  { id: 98, name: "Vulnerability Management Dashboard", slug: "vulnerability-management-dashboard", category: "Security Tools", isPro: true },
  { id: 99, name: "Security Operations Workspace", slug: "security-operations-workspace", category: "Security Tools", isPro: true },
  { id: 100, name: "Cyber Risk Intelligence Workspace", slug: "cyber-risk-intelligence-workspace", category: "Security Tools", isPro: true },
];