export interface SEOTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const seoToolsList: SEOTool[] = [
  // --- TOP 10 PRIORITY TOOLS ---
  { id: 1, name: "Keyword Generator", slug: "keyword-generator", category: "SEO Tools", isPro: false },
  { id: 2, name: "Keyword Difficulty Checker", slug: "keyword-difficulty-checker", category: "SEO Tools", isPro: false },
  { id: 3, name: "SEO Analyzer", slug: "seo-analyzer", category: "SEO Tools", isPro: false },
  { id: 4, name: "SERP Checker", slug: "serp-checker", category: "SEO Tools", isPro: false },
  { id: 5, name: "Backlink Checker", slug: "backlink-checker", category: "SEO Tools", isPro: false },
  { id: 6, name: "Website SEO Audit", slug: "website-seo-audit", category: "SEO Tools", isPro: false },
  { id: 7, name: "Schema Generator", slug: "schema-generator", category: "SEO Tools", isPro: false },
  { id: 8, name: "Sitemap Generator", slug: "sitemap-generator", category: "SEO Tools", isPro: false },
  { id: 9, name: "Meta Description Generator", slug: "meta-description-generator", category: "SEO Tools", isPro: false },
  { id: 10, name: "Page Speed Checker", slug: "page-speed-checker", category: "SEO Tools", isPro: false },

  // --- REMAINING CORE / HIGH-DEMAND (FREE TOOLS: 11-60) ---
  { id: 11, name: "Keyword Research Tool", slug: "keyword-research-tool", category: "SEO Tools", isPro: false },
  { id: 12, name: "Keyword Density Checker", slug: "keyword-density-checker", category: "SEO Tools", isPro: false },
  { id: 13, name: "Search Volume Checker", slug: "search-volume-checker", category: "SEO Tools", isPro: false },
  { id: 14, name: "Long-Tail Keyword Generator", slug: "long-tail-keyword-generator", category: "SEO Tools", isPro: false },
  { id: 15, name: "Related Keywords Generator", slug: "related-keywords-generator", category: "SEO Tools", isPro: false },
  { id: 16, name: "Question Keyword Generator", slug: "question-keyword-generator", category: "SEO Tools", isPro: false },
  { id: 17, name: "Keyword Clustering Tool", slug: "keyword-clustering-tool", category: "SEO Tools", isPro: false },
  { id: 18, name: "Keyword Grouping Tool", slug: "keyword-grouping-tool", category: "SEO Tools", isPro: false },
  { id: 19, name: "Keyword Intent Classifier", slug: "keyword-intent-classifier", category: "SEO Tools", isPro: false },
  { id: 20, name: "SERP Preview Tool", slug: "serp-preview-tool", category: "SEO Tools", isPro: false },
  { id: 21, name: "Google SERP Simulator", slug: "google-serp-simulator", category: "SEO Tools", isPro: false },
  { id: 22, name: "Meta Title Generator", slug: "meta-title-generator", category: "SEO Tools", isPro: false },
  { id: 23, name: "Title Tag Checker", slug: "title-tag-checker", category: "SEO Tools", isPro: false },
  { id: 24, name: "Meta Tag Analyzer", slug: "meta-tag-analyzer", category: "SEO Tools", isPro: false },
  { id: 25, name: "On-Page SEO Checker", slug: "on-page-seo-checker", category: "SEO Tools", isPro: false },
  { id: 26, name: "Page SEO Audit", slug: "page-seo-audit", category: "SEO Tools", isPro: false },
  { id: 27, name: "Technical SEO Checker", slug: "technical-seo-checker", category: "SEO Tools", isPro: false },
  { id: 28, name: "Broken Link Checker", slug: "broken-link-checker", category: "SEO Tools", isPro: false },
  { id: 29, name: "Backlink Analyzer", slug: "backlink-analyzer", category: "SEO Tools", isPro: false },
  { id: 30, name: "Link Counter", slug: "link-counter", category: "SEO Tools", isPro: false },
  { id: 31, name: "Internal Link Checker", slug: "internal-link-checker", category: "SEO Tools", isPro: false },
  { id: 32, name: "External Link Checker", slug: "external-link-checker", category: "SEO Tools", isPro: false },
  { id: 33, name: "Redirect Checker", slug: "redirect-checker", category: "SEO Tools", isPro: false },
  { id: 34, name: "HTTP Status Checker", slug: "http-status-checker", category: "SEO Tools", isPro: false },
  { id: 35, name: "Canonical URL Checker", slug: "canonical-url-checker", category: "SEO Tools", isPro: false },
  { id: 36, name: "Robots.txt Tester", slug: "robots-txt-tester", category: "SEO Tools", isPro: false },
  { id: 37, name: "Robots.txt Generator", slug: "robots-txt-generator", category: "SEO Tools", isPro: false },
  { id: 38, name: "Sitemap Validator", slug: "sitemap-validator", category: "SEO Tools", isPro: false },
  { id: 39, name: "Sitemap URL Extractor", slug: "sitemap-url-extractor", category: "SEO Tools", isPro: false },
  { id: 40, name: "Schema Validator", slug: "schema-validator", category: "SEO Tools", isPro: false },
  { id: 41, name: "Open Graph Generator", slug: "open-graph-generator", category: "SEO Tools", isPro: false },
  { id: 42, name: "Twitter Card Generator", slug: "twitter-card-generator", category: "SEO Tools", isPro: false },
  { id: 43, name: "Hreflang Generator", slug: "hreflang-generator", category: "SEO Tools", isPro: false },
  { id: 44, name: "URL Slug Generator", slug: "url-slug-generator", category: "SEO Tools", isPro: false },
  { id: 45, name: "URL Encoder", slug: "url-encoder", category: "SEO Tools", isPro: false },
  { id: 46, name: "URL Decoder", slug: "url-decoder", category: "SEO Tools", isPro: false },
  { id: 47, name: "Word Counter for SEO", slug: "word-counter-for-seo", category: "SEO Tools", isPro: false },
  { id: 48, name: "Readability Checker", slug: "readability-checker", category: "SEO Tools", isPro: false },
  { id: 49, name: "Content Optimization Checker", slug: "content-optimization-checker", category: "SEO Tools", isPro: false },
  { id: 50, name: "Duplicate Content Checker", slug: "duplicate-content-checker", category: "SEO Tools", isPro: false },
  { id: 51, name: "Plagiarism Checker", slug: "plagiarism-checker", category: "SEO Tools", isPro: false },
  { id: 52, name: "Image SEO Checker", slug: "image-seo-checker", category: "SEO Tools", isPro: false },
  { id: 53, name: "Alt Text Generator", slug: "alt-text-generator", category: "SEO Tools", isPro: false },
  { id: 54, name: "Image Filename Generator", slug: "image-filename-generator", category: "SEO Tools", isPro: false },
  { id: 55, name: "Core Web Vitals Checker", slug: "core-web-vitals-checker", category: "SEO Tools", isPro: false },
  { id: 56, name: "Mobile-Friendly Checker", slug: "mobile-friendly-checker", category: "SEO Tools", isPro: false },
  { id: 57, name: "Domain Authority Checker", slug: "domain-authority-checker", category: "SEO Tools", isPro: false },
  { id: 58, name: "Page Authority Checker", slug: "page-authority-checker", category: "SEO Tools", isPro: false },
  { id: 59, name: "Website Traffic Estimator", slug: "website-traffic-estimator", category: "SEO Tools", isPro: false },
  { id: 60, name: "Competitor SEO Analyzer", slug: "competitor-seo-analyzer", category: "SEO Tools", isPro: false },

  // --- PRO LEVEL (PAID TOOLS: 61-100) ---
  { id: 61, name: "SERP Position Tracker", slug: "serp-position-tracker", category: "SEO Tools", isPro: true },
  { id: 62, name: "Rank Tracking Dashboard", slug: "rank-tracking-dashboard", category: "SEO Tools", isPro: true },
  { id: 63, name: "Local Rank Tracker", slug: "local-rank-tracker", category: "SEO Tools", isPro: true },
  { id: 64, name: "Keyword Cannibalization Checker", slug: "keyword-cannibalization-checker", category: "SEO Tools", isPro: true },
  { id: 65, name: "Content Gap Analyzer", slug: "content-gap-analyzer", category: "SEO Tools", isPro: true },
  { id: 66, name: "Keyword Gap Analyzer", slug: "keyword-gap-analyzer", category: "SEO Tools", isPro: true },
  { id: 67, name: "Competitor Keyword Finder", slug: "competitor-keyword-finder", category: "SEO Tools", isPro: true },
  { id: 68, name: "Competitor Backlink Gap Analyzer", slug: "competitor-backlink-gap-analyzer", category: "SEO Tools", isPro: true },
  { id: 69, name: "Backlink Gap Tool", slug: "backlink-gap-tool", category: "SEO Tools", isPro: true },
  { id: 70, name: "Link Toxicity Analyzer", slug: "link-toxicity-analyzer", category: "SEO Tools", isPro: true },
  { id: 71, name: "Anchor Text Analyzer", slug: "anchor-text-analyzer", category: "SEO Tools", isPro: true },
  { id: 72, name: "Referring Domain Analyzer", slug: "referring-domain-analyzer", category: "SEO Tools", isPro: true },
  { id: 73, name: "Orphan Page Finder", slug: "orphan-page-finder", category: "SEO Tools", isPro: true },
  { id: 74, name: "Internal Link Opportunity Finder", slug: "internal-link-opportunity-finder", category: "SEO Tools", isPro: true },
  { id: 75, name: "Crawlability Analyzer", slug: "crawlability-analyzer", category: "SEO Tools", isPro: true },
  { id: 76, name: "Indexability Checker", slug: "indexability-checker", category: "SEO Tools", isPro: true },
  { id: 77, name: "Noindex Checker", slug: "noindex-checker", category: "SEO Tools", isPro: true },
  { id: 78, name: "Nofollow Link Analyzer", slug: "nofollow-link-analyzer", category: "SEO Tools", isPro: true },
  { id: 79, name: "JavaScript SEO Tester", slug: "javascript-seo-tester", category: "SEO Tools", isPro: true },
  { id: 80, name: "Rendering SEO Tester", slug: "rendering-seo-tester", category: "SEO Tools", isPro: true },
  { id: 81, name: "Log File SEO Analyzer", slug: "log-file-seo-analyzer", category: "SEO Tools", isPro: true },
  { id: 82, name: "Redirect Chain Checker", slug: "redirect-chain-checker", category: "SEO Tools", isPro: true },
  { id: 83, name: "Redirect Mapping Generator", slug: "redirect-mapping-generator", category: "SEO Tools", isPro: true },
  { id: 84, name: "Pagination SEO Checker", slug: "pagination-seo-checker", category: "SEO Tools", isPro: true },
  { id: 85, name: "Faceted Navigation SEO Checker", slug: "faceted-navigation-seo-checker", category: "SEO Tools", isPro: true },
  { id: 86, name: "International SEO Checker", slug: "international-seo-checker", category: "SEO Tools", isPro: true },
  { id: 87, name: "Local SEO Audit", slug: "local-seo-audit", category: "SEO Tools", isPro: true },
  { id: 88, name: "Google Business SEO Analyzer", slug: "google-business-seo-analyzer", category: "SEO Tools", isPro: true },
  { id: 89, name: "Review SEO Analyzer", slug: "review-seo-analyzer", category: "SEO Tools", isPro: true },
  { id: 90, name: "E-E-A-T Content Checker", slug: "e-e-a-t-content-checker", category: "SEO Tools", isPro: true },
  { id: 91, name: "Topical Authority Analyzer", slug: "topical-authority-analyzer", category: "SEO Tools", isPro: true },
  { id: 92, name: "Semantic Keyword Analyzer", slug: "semantic-keyword-analyzer", category: "SEO Tools", isPro: true },
  { id: 93, name: "Content Brief Generator", slug: "content-brief-generator", category: "SEO Tools", isPro: true },
  { id: 94, name: "SEO Content Score Analyzer", slug: "seo-content-score-analyzer", category: "SEO Tools", isPro: true },
  { id: 95, name: "Content Decay Detector", slug: "content-decay-detector", category: "SEO Tools", isPro: true },
  { id: 96, name: "Search Intent Analyzer", slug: "search-intent-analyzer", category: "SEO Tools", isPro: true },
  { id: 97, name: "SERP Feature Analyzer", slug: "serp-feature-analyzer", category: "SEO Tools", isPro: true },
  { id: 98, name: "Featured Snippet Opportunity Finder", slug: "featured-snippet-opportunity-finder", category: "SEO Tools", isPro: true },
  { id: 99, name: "Programmatic SEO Page Generator", slug: "programmatic-seo-page-generator", category: "SEO Tools", isPro: true },
  { id: 100, name: "SEO Reporting Dashboard", slug: "seo-reporting-dashboard", category: "SEO Tools", isPro: true },
];