export interface SpreadsheetTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const spreadsheetToolsList: SpreadsheetTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-16) ---
  { id: 1, name: "Spreadsheet Formula Generator", slug: "spreadsheet-formula-generator", category: "Spreadsheet Tools", isPro: false },
  { id: 2, name: "Excel Formula Generator", slug: "excel-formula-generator", category: "Spreadsheet Tools", isPro: false },
  { id: 3, name: "Formula Explainer", slug: "formula-explainer", category: "Spreadsheet Tools", isPro: false },
  { id: 4, name: "Formula Debugger", slug: "formula-debugger", category: "Spreadsheet Tools", isPro: false },
  { id: 5, name: "Formula Translator", slug: "formula-translator", category: "Spreadsheet Tools", isPro: false },
  { id: 6, name: "Spreadsheet Error Checker", slug: "spreadsheet-error-checker", category: "Spreadsheet Tools", isPro: false },
  { id: 7, name: "CSV to Excel Converter", slug: "csv-to-excel-converter", category: "Spreadsheet Tools", isPro: false },
  { id: 8, name: "Excel to CSV Converter", slug: "excel-to-csv-converter", category: "Spreadsheet Tools", isPro: false },
  { id: 9, name: "Excel Data Cleaner", slug: "excel-data-cleaner", category: "Spreadsheet Tools", isPro: false },
  { id: 10, name: "Excel Duplicate Remover", slug: "excel-duplicate-remover", category: "Spreadsheet Tools", isPro: false },
  { id: 11, name: "Excel Sheet Merger", slug: "excel-sheet-merger", category: "Spreadsheet Tools", isPro: false },
  { id: 12, name: "Excel Chart Generator", slug: "excel-chart-generator", category: "Spreadsheet Tools", isPro: false },
  { id: 13, name: "Excel Pivot Table Helper", slug: "excel-pivot-table-helper", category: "Spreadsheet Tools", isPro: false },
  { id: 14, name: "Excel XLOOKUP Generator", slug: "excel-xlookup-generator", category: "Spreadsheet Tools", isPro: false },
  { id: 15, name: "Excel INDEX MATCH Generator", slug: "excel-index-match-generator", category: "Spreadsheet Tools", isPro: false },
  { id: 16, name: "Excel SUMIFS Generator", slug: "excel-sumifs-generator", category: "Spreadsheet Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (17-60) ---
  { id: 17, name: "Formula Converter", slug: "formula-converter", category: "Spreadsheet Tools", isPro: false },
  { id: 18, name: "Formula Cleaner", slug: "formula-cleaner", category: "Spreadsheet Tools", isPro: false },
  { id: 19, name: "Formula Validator", slug: "formula-validator", category: "Spreadsheet Tools", isPro: false },
  { id: 20, name: "Formula Optimizer", slug: "formula-optimizer", category: "Spreadsheet Tools", isPro: false },
  { id: 21, name: "Cell Reference Converter", slug: "cell-reference-converter", category: "Spreadsheet Tools", isPro: false },
  { id: 22, name: "Excel Function Finder", slug: "excel-function-finder", category: "Spreadsheet Tools", isPro: false },
  { id: 23, name: "Excel Function Explainer", slug: "excel-function-explainer", category: "Spreadsheet Tools", isPro: false },
  { id: 24, name: "Excel Error Explainer", slug: "excel-error-explainer", category: "Spreadsheet Tools", isPro: false },
  { id: 25, name: "Excel to JSON Converter", slug: "excel-to-json-converter", category: "Spreadsheet Tools", isPro: false },
  { id: 26, name: "JSON to Excel Converter", slug: "json-to-excel-converter", category: "Spreadsheet Tools", isPro: false },
  { id: 27, name: "Excel to XML Converter", slug: "excel-to-xml-converter", category: "Spreadsheet Tools", isPro: false },
  { id: 28, name: "XML to Excel Converter", slug: "xml-to-excel-converter", category: "Spreadsheet Tools", isPro: false },
  { id: 29, name: "Excel to HTML Converter", slug: "excel-to-html-converter", category: "Spreadsheet Tools", isPro: false },
  { id: 30, name: "HTML to Excel Converter", slug: "html-to-excel-converter", category: "Spreadsheet Tools", isPro: false },
  { id: 31, name: "Excel to PDF Converter", slug: "excel-to-pdf-converter", category: "Spreadsheet Tools", isPro: false },
  { id: 32, name: "Excel File Merger", slug: "excel-file-merger", category: "Spreadsheet Tools", isPro: false },
  { id: 33, name: "Excel Sheet Splitter", slug: "excel-sheet-splitter", category: "Spreadsheet Tools", isPro: false },
  { id: 34, name: "Excel Column Splitter", slug: "excel-column-splitter", category: "Spreadsheet Tools", isPro: false },
  { id: 35, name: "Excel Row Splitter", slug: "excel-row-splitter", category: "Spreadsheet Tools", isPro: false },
  { id: 36, name: "Excel Blank Cell Cleaner", slug: "excel-blank-cell-cleaner", category: "Spreadsheet Tools", isPro: false },
  { id: 37, name: "Excel Whitespace Cleaner", slug: "excel-whitespace-cleaner", category: "Spreadsheet Tools", isPro: false },
  { id: 38, name: "Excel Case Converter", slug: "excel-case-converter", category: "Spreadsheet Tools", isPro: false },
  { id: 39, name: "Excel Text Extractor", slug: "excel-text-extractor", category: "Spreadsheet Tools", isPro: false },
  { id: 40, name: "Excel Column Formatter", slug: "excel-column-formatter", category: "Spreadsheet Tools", isPro: false },
  { id: 41, name: "Excel Date Formatter", slug: "excel-date-formatter", category: "Spreadsheet Tools", isPro: false },
  { id: 42, name: "Excel Number Formatter", slug: "excel-number-formatter", category: "Spreadsheet Tools", isPro: false },
  { id: 43, name: "Excel Currency Formatter", slug: "excel-currency-formatter", category: "Spreadsheet Tools", isPro: false },
  { id: 44, name: "Excel Percentage Formatter", slug: "excel-percentage-formatter", category: "Spreadsheet Tools", isPro: false },
  { id: 45, name: "Excel Sorter", slug: "excel-sorter", category: "Spreadsheet Tools", isPro: false },
  { id: 46, name: "Excel Filter Generator", slug: "excel-filter-generator", category: "Spreadsheet Tools", isPro: false },
  { id: 47, name: "Excel Data Validator", slug: "excel-data-validator", category: "Spreadsheet Tools", isPro: false },
  { id: 48, name: "Excel Dropdown Generator", slug: "excel-dropdown-generator", category: "Spreadsheet Tools", isPro: false },
  { id: 49, name: "Excel Data Validation Builder", slug: "excel-data-validation-builder", category: "Spreadsheet Tools", isPro: false },
  { id: 50, name: "Excel Conditional Formatting Generator", slug: "excel-conditional-formatting-generator", category: "Spreadsheet Tools", isPro: false },
  { id: 51, name: "Excel Lookup Helper", slug: "excel-lookup-helper", category: "Spreadsheet Tools", isPro: false },
  { id: 52, name: "Excel VLOOKUP Generator", slug: "excel-vlookup-generator", category: "Spreadsheet Tools", isPro: false },
  { id: 53, name: "Excel COUNTIFS Generator", slug: "excel-countifs-generator", category: "Spreadsheet Tools", isPro: false },
  { id: 54, name: "Excel IF Formula Generator", slug: "excel-if-formula-generator", category: "Spreadsheet Tools", isPro: false },
  { id: 55, name: "Excel Date Formula Generator", slug: "excel-date-formula-generator", category: "Spreadsheet Tools", isPro: false },
  { id: 56, name: "Excel Text Formula Generator", slug: "excel-text-formula-generator", category: "Spreadsheet Tools", isPro: false },
  { id: 57, name: "Excel Financial Formula Generator", slug: "excel-financial-formula-generator", category: "Spreadsheet Tools", isPro: false },
  { id: 58, name: "Excel Statistical Formula Generator", slug: "excel-statistical-formula-generator", category: "Spreadsheet Tools", isPro: false },
  { id: 59, name: "Excel Math Formula Generator", slug: "excel-math-formula-generator", category: "Spreadsheet Tools", isPro: false },
  { id: 60, name: "Spreadsheet Template Generator", slug: "spreadsheet-template-generator", category: "Spreadsheet Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Spreadsheet Formula Auditor", slug: "spreadsheet-formula-auditor", category: "Spreadsheet Tools", isPro: true },
  { id: 62, name: "Spreadsheet Forecasting Tool", slug: "spreadsheet-forecasting-tool", category: "Spreadsheet Tools", isPro: true },
  { id: 63, name: "Excel Financial Model Builder", slug: "excel-financial-model-builder", category: "Spreadsheet Tools", isPro: true },
  { id: 64, name: "AI Spreadsheet Analyst", slug: "ai-spreadsheet-analyst", category: "Spreadsheet Tools", isPro: true },
  { id: 65, name: "Intelligent Spreadsheet Workspace", slug: "intelligent-spreadsheet-workspace", category: "Spreadsheet Tools", isPro: true },
  { id: 66, name: "Workbook Dependency Analyzer", slug: "workbook-dependency-analyzer", category: "Spreadsheet Tools", isPro: true },
  { id: 67, name: "Formula Dependency Mapper", slug: "formula-dependency-mapper", category: "Spreadsheet Tools", isPro: true },
  { id: 68, name: "Spreadsheet Error Audit", slug: "spreadsheet-error-audit", category: "Spreadsheet Tools", isPro: true },
  { id: 69, name: "Spreadsheet Performance Optimizer", slug: "spreadsheet-performance-optimizer", category: "Spreadsheet Tools", isPro: true },
  { id: 70, name: "Workbook Size Optimizer", slug: "workbook-size-optimizer", category: "Spreadsheet Tools", isPro: true },
  { id: 71, name: "Spreadsheet Duplicate Analyzer", slug: "spreadsheet-duplicate-analyzer", category: "Spreadsheet Tools", isPro: true },
  { id: 72, name: "Spreadsheet Data Quality Analyzer", slug: "spreadsheet-data-quality-analyzer", category: "Spreadsheet Tools", isPro: true },
  { id: 73, name: "Spreadsheet Data Profiling Tool", slug: "spreadsheet-data-profiling-tool", category: "Spreadsheet Tools", isPro: true },
  { id: 74, name: "Spreadsheet Anomaly Detector", slug: "spreadsheet-anomaly-detector", category: "Spreadsheet Tools", isPro: true },
  { id: 75, name: "Spreadsheet Outlier Detector", slug: "spreadsheet-outlier-detector", category: "Spreadsheet Tools", isPro: true },
  { id: 76, name: "Excel Trend Analyzer", slug: "excel-trend-analyzer", category: "Spreadsheet Tools", isPro: true },
  { id: 77, name: "Excel Scenario Manager", slug: "excel-scenario-manager", category: "Spreadsheet Tools", isPro: true },
  { id: 78, name: "Excel What-If Analyzer", slug: "excel-what-if-analyzer", category: "Spreadsheet Tools", isPro: true },
  { id: 79, name: "Excel Sensitivity Analysis", slug: "excel-sensitivity-analysis", category: "Spreadsheet Tools", isPro: true },
  { id: 80, name: "Excel Goal Seek Assistant", slug: "excel-goal-seek-assistant", category: "Spreadsheet Tools", isPro: true },
  { id: 81, name: "Monte Carlo Spreadsheet Simulator", slug: "monte-carlo-spreadsheet-simulator", category: "Spreadsheet Tools", isPro: true },
  { id: 82, name: "Excel Budget Model Builder", slug: "excel-budget-model-builder", category: "Spreadsheet Tools", isPro: true },
  { id: 83, name: "Excel Forecast Model Builder", slug: "excel-forecast-model-builder", category: "Spreadsheet Tools", isPro: true },
  { id: 84, name: "Excel KPI Dashboard Builder", slug: "excel-kpi-dashboard-builder", category: "Spreadsheet Tools", isPro: true },
  { id: 85, name: "Excel Executive Dashboard Builder", slug: "excel-executive-dashboard-builder", category: "Spreadsheet Tools", isPro: true },
  { id: 86, name: "Excel Sales Dashboard Builder", slug: "excel-sales-dashboard-builder", category: "Spreadsheet Tools", isPro: true },
  { id: 87, name: "Excel Marketing Dashboard Builder", slug: "excel-marketing-dashboard-builder", category: "Spreadsheet Tools", isPro: true },
  { id: 88, name: "Excel HR Dashboard Builder", slug: "excel-hr-dashboard-builder", category: "Spreadsheet Tools", isPro: true },
  { id: 89, name: "Excel Inventory Dashboard Builder", slug: "excel-inventory-dashboard-builder", category: "Spreadsheet Tools", isPro: true },
  { id: 90, name: "Excel Project Dashboard Builder", slug: "excel-project-dashboard-builder", category: "Spreadsheet Tools", isPro: true },
  { id: 91, name: "Spreadsheet Data Consolidation Engine", slug: "spreadsheet-data-consolidation-engine", category: "Spreadsheet Tools", isPro: true },
  { id: 92, name: "Multi-Workbook Reconciliation Tool", slug: "multi-workbook-reconciliation-tool", category: "Spreadsheet Tools", isPro: true },
  { id: 93, name: "Spreadsheet Version Comparator", slug: "spreadsheet-version-comparator", category: "Spreadsheet Tools", isPro: true },
  { id: 94, name: "Spreadsheet Change Tracker", slug: "spreadsheet-change-tracker", category: "Spreadsheet Tools", isPro: true },
  { id: 95, name: "Spreadsheet Access Audit", slug: "spreadsheet-access-audit", category: "Spreadsheet Tools", isPro: true },
  { id: 96, name: "Spreadsheet Privacy Scanner", slug: "spreadsheet-privacy-scanner", category: "Spreadsheet Tools", isPro: true },
  { id: 97, name: "Sensitive Data Detector", slug: "sensitive-data-detector-spreadsheet", category: "Spreadsheet Tools", isPro: true },
  { id: 98, name: "AI Formula Assistant", slug: "ai-formula-assistant", category: "Spreadsheet Tools", isPro: true },
  { id: 99, name: "AI Spreadsheet Cleanup Assistant", slug: "ai-spreadsheet-cleanup-assistant", category: "Spreadsheet Tools", isPro: true },
  { id: 100, name: "AI Spreadsheet Report Generator", slug: "ai-spreadsheet-report-generator", category: "Spreadsheet Tools", isPro: true },
];