export interface StartupResourcesTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const startupResourcesToolsList: StartupResourcesTool[] = [
  // --- 🔥 PRIORITY 20 FREE TOOLS (IDs 1-20 | isPro: false) ---
  { id: 1, name: "Business Idea Validator", slug: "business-idea-validator", category: "Startup Resources Tools", isPro: false },
  { id: 2, name: "Startup Name Generator", slug: "startup-name-generator", category: "Startup Resources Tools", isPro: false },
  { id: 3, name: "Value Proposition Builder", slug: "value-proposition-builder", category: "Startup Resources Tools", isPro: false },
  { id: 4, name: "Customer Persona Builder", slug: "customer-persona-builder", category: "Startup Resources Tools", isPro: false },
  { id: 5, name: "Ideal Customer Profile Builder", slug: "ideal-customer-profile-builder", category: "Startup Resources Tools", isPro: false },
  { id: 6, name: "TAM Calculator", slug: "tam-calculator", category: "Startup Resources Tools", isPro: false },
  { id: 7, name: "SAM Calculator", slug: "sam-calculator", category: "Startup Resources Tools", isPro: false },
  { id: 8, name: "SOM Calculator", slug: "som-calculator", category: "Startup Resources Tools", isPro: false },
  { id: 9, name: "Startup Revenue Calculator", slug: "startup-revenue-calculator", category: "Startup Resources Tools", isPro: false },
  { id: 10, name: "Startup Runway Calculator", slug: "startup-runway-calculator", category: "Startup Resources Tools", isPro: false },
  { id: 11, name: "Burn Rate Calculator", slug: "burn-rate-calculator-startup", category: "Startup Resources Tools", isPro: false },
  { id: 12, name: "Break-Even Calculator", slug: "break-even-calculator-startup", category: "Startup Resources Tools", isPro: false },
  { id: 13, name: "LTV:CAC Calculator", slug: "ltv-cac-calculator", category: "Startup Resources Tools", isPro: false },
  { id: 14, name: "MRR Calculator", slug: "mrr-calculator", category: "Startup Resources Tools", isPro: false },
  { id: 15, name: "ARR Calculator", slug: "arr-calculator", category: "Startup Resources Tools", isPro: false },
  { id: 16, name: "Startup Valuation Calculator", slug: "startup-valuation-calculator", category: "Startup Resources Tools", isPro: false },
  { id: 17, name: "Dilution Calculator", slug: "dilution-calculator", category: "Startup Resources Tools", isPro: false },
  { id: 18, name: "Cap Table Calculator", slug: "cap-table-calculator-startup", category: "Startup Resources Tools", isPro: false },
  { id: 19, name: "Business Model Canvas", slug: "business-model-canvas", category: "Startup Resources Tools", isPro: false },
  { id: 20, name: "Lean Canvas Generator", slug: "lean-canvas-generator-startup", category: "Startup Resources Tools", isPro: false },

  // --- REMAINING 40 CORE FREE TOOLS (IDs 21-60 | isPro: false) ---
  { id: 21, name: "Startup Idea Generator", slug: "startup-idea-generator-tool", category: "Startup Resources Tools", isPro: false },
  { id: 22, name: "Business Name Generator", slug: "business-name-generator-startup", category: "Startup Resources Tools", isPro: false },
  { id: 23, name: "Startup Tagline Generator", slug: "startup-tagline-generator", category: "Startup Resources Tools", isPro: false },
  { id: 24, name: "Startup Elevator Pitch Generator", slug: "startup-elevator-pitch-generator", category: "Startup Resources Tools", isPro: false },
  { id: 25, name: "Problem Statement Generator", slug: "problem-statement-generator", category: "Startup Resources Tools", isPro: false },
  { id: 26, name: "Solution Statement Builder", slug: "solution-statement-builder", category: "Startup Resources Tools", isPro: false },
  { id: 27, name: "Market Size Calculator", slug: "market-size-calculator", category: "Startup Resources Tools", isPro: false },
  { id: 28, name: "Market Growth Calculator", slug: "market-growth-calculator", category: "Startup Resources Tools", isPro: false },
  { id: 29, name: "Startup Cost Calculator", slug: "startup-cost-calculator", category: "Startup Resources Tools", isPro: false },
  { id: 30, name: "Startup Budget Calculator", slug: "startup-budget-calculator", category: "Startup Resources Tools", isPro: false },
  { id: 31, name: "Gross Margin Calculator", slug: "gross-margin-calculator", category: "Startup Resources Tools", isPro: false },
  { id: 32, name: "Net Margin Calculator", slug: "net-margin-calculator", category: "Startup Resources Tools", isPro: false },
  { id: 33, name: "CAC Calculator", slug: "cac-calculator-startup", category: "Startup Resources Tools", isPro: false },
  { id: 34, name: "LTV Calculator", slug: "ltv-calculator-startup", category: "Startup Resources Tools", isPro: false },
  { id: 35, name: "ARPU Calculator", slug: "arpu-calculator-startup", category: "Startup Resources Tools", isPro: false },
  { id: 36, name: "Churn Calculator", slug: "churn-calculator-startup", category: "Startup Resources Tools", isPro: false },
  { id: 37, name: "Retention Calculator", slug: "retention-calculator-startup", category: "Startup Resources Tools", isPro: false },
  { id: 38, name: "Conversion Rate Calculator", slug: "conversion-rate-calculator-startup", category: "Startup Resources Tools", isPro: false },
  { id: 39, name: "Pre-Money Valuation Calculator", slug: "pre-money-valuation-calculator", category: "Startup Resources Tools", isPro: false },
  { id: 40, name: "Post-Money Valuation Calculator", slug: "post-money-valuation-calculator", category: "Startup Resources Tools", isPro: false },
  { id: 41, name: "Equity Split Calculator", slug: "equity-split-calculator", category: "Startup Resources Tools", isPro: false },
  { id: 42, name: "Founder Equity Calculator", slug: "founder-equity-calculator", category: "Startup Resources Tools", isPro: false },
  { id: 43, name: "Employee Option Pool Calculator", slug: "employee-option-pool-calculator", category: "Startup Resources Tools", isPro: false },
  { id: 44, name: "SAFE Calculator", slug: "safe-calculator", category: "Startup Resources Tools", isPro: false },
  { id: 45, name: "Startup Funding Calculator", slug: "startup-funding-calculator", category: "Startup Resources Tools", isPro: false },
  { id: 46, name: "Fundraising Target Calculator", slug: "fundraising-target-calculator", category: "Startup Resources Tools", isPro: false },
  { id: 47, name: "Funding Runway Calculator", slug: "funding-runway-calculator", category: "Startup Resources Tools", isPro: false },
  { id: 48, name: "Pitch Deck Checklist", slug: "pitch-deck-checklist", category: "Startup Resources Tools", isPro: false },
  { id: 49, name: "Investor Meeting Checklist", slug: "investor-meeting-checklist", category: "Startup Resources Tools", isPro: false },
  { id: 50, name: "Due Diligence Checklist", slug: "due-diligence-checklist", category: "Startup Resources Tools", isPro: false },
  { id: 51, name: "Startup Launch Checklist", slug: "startup-launch-checklist", category: "Startup Resources Tools", isPro: false },
  { id: 52, name: "MVP Planning Checklist", slug: "mvp-planning-checklist", category: "Startup Resources Tools", isPro: false },
  { id: 53, name: "Product Validation Checklist", slug: "product-validation-checklist", category: "Startup Resources Tools", isPro: false },
  { id: 54, name: "Customer Interview Checklist", slug: "customer-interview-checklist", category: "Startup Resources Tools", isPro: false },
  { id: 55, name: "Competitor Research Checklist", slug: "competitor-research-checklist-startup", category: "Startup Resources Tools", isPro: false },
  { id: 56, name: "SWOT Analysis Generator", slug: "swot-analysis-generator-startup", category: "Startup Resources Tools", isPro: false },
  { id: 57, name: "Competitive Analysis Matrix", slug: "competitive-analysis-matrix", category: "Startup Resources Tools", isPro: false },
  { id: 58, name: "Startup Milestone Planner", slug: "startup-milestone-planner", category: "Startup Resources Tools", isPro: false },
  { id: 59, name: "Founder Task Planner", slug: "founder-task-planner", category: "Startup Resources Tools", isPro: false },
  { id: 60, name: "Startup KPI Tracker", slug: "startup-kpi-tracker", category: "Startup Resources Tools", isPro: false },

  // --- ⚡ 40 PRO / SAAS TOOLS (IDs 61-100 | isPro: true) ---
  { id: 61, name: "Startup Financial Dashboard", slug: "startup-financial-dashboard", category: "Startup Resources Tools", isPro: true },
  { id: 62, name: "Startup Command Center", slug: "startup-command-center", category: "Startup Resources Tools", isPro: true },
  { id: 63, name: "Startup Planning Workspace", slug: "startup-planning-workspace", category: "Startup Resources Tools", isPro: true },
  { id: 64, name: "Business Validation Workspace", slug: "business-validation-workspace", category: "Startup Resources Tools", isPro: true },
  { id: 65, name: "Market Intelligence Workspace", slug: "market-intelligence-workspace-startup", category: "Startup Resources Tools", isPro: true },
  { id: 66, name: "Customer Discovery Workspace", slug: "customer-discovery-workspace", category: "Startup Resources Tools", isPro: true },
  { id: 67, name: "Customer Persona Intelligence", slug: "customer-persona-intelligence", category: "Startup Resources Tools", isPro: true },
  { id: 68, name: "ICP Management Workspace", slug: "icp-management-workspace", category: "Startup Resources Tools", isPro: true },
  { id: 69, name: "TAM/SAM/SOM Intelligence", slug: "tam-sam-som-intelligence", category: "Startup Resources Tools", isPro: true },
  { id: 70, name: "Startup Runway Dashboard", slug: "startup-runway-dashboard", category: "Startup Resources Tools", isPro: true },
  { id: 71, name: "Burn Rate Analytics", slug: "burn-rate-analytics", category: "Startup Resources Tools", isPro: true },
  { id: 72, name: "Startup Unit Economics Workspace", slug: "startup-unit-economics-workspace", category: "Startup Resources Tools", isPro: true },
  { id: 73, name: "SaaS Metrics Dashboard", slug: "saas-metrics-dashboard", category: "Startup Resources Tools", isPro: true },
  { id: 74, name: "MRR/ARR Analytics Workspace", slug: "mrr-arr-analytics-workspace", category: "Startup Resources Tools", isPro: true },
  { id: 75, name: "Churn & Retention Analytics", slug: "churn-retention-analytics", category: "Startup Resources Tools", isPro: true },
  { id: 76, name: "CAC/LTV Intelligence Workspace", slug: "cac-ltv-intelligence-workspace", category: "Startup Resources Tools", isPro: true },
  { id: 77, name: "Startup Valuation Workspace", slug: "startup-valuation-workspace", category: "Startup Resources Tools", isPro: true },
  { id: 78, name: "Cap Table Management Workspace", slug: "cap-table-management-workspace", category: "Startup Resources Tools", isPro: true },
  { id: 79, name: "Equity Planning Workspace", slug: "equity-planning-workspace", category: "Startup Resources Tools", isPro: true },
  { id: 80, name: "Founder Equity Management", slug: "founder-equity-management", category: "Startup Resources Tools", isPro: true },
  { id: 81, name: "Fundraising Management Workspace", slug: "fundraising-management-workspace", category: "Startup Resources Tools", isPro: true },
  { id: 82, name: "Investor Pipeline Workspace", slug: "investor-pipeline-workspace", category: "Startup Resources Tools", isPro: true },
  { id: 83, name: "Investor Research Workspace", slug: "investor-research-workspace", category: "Startup Resources Tools", isPro: true },
  { id: 84, name: "Due Diligence Workspace", slug: "due-diligence-workspace", category: "Startup Resources Tools", isPro: true },
  { id: 85, name: "Pitch Deck Planning Workspace", slug: "pitch-deck-planning-workspace", category: "Startup Resources Tools", isPro: true },
  { id: 86, name: "Startup KPI Dashboard", slug: "startup-kpi-dashboard", category: "Startup Resources Tools", isPro: true },
  { id: 87, name: "Startup Milestone Dashboard", slug: "startup-milestone-dashboard", category: "Startup Resources Tools", isPro: true },
  { id: 88, name: "Product Validation Dashboard", slug: "product-validation-dashboard", category: "Startup Resources Tools", isPro: true },
  { id: 89, name: "MVP Management Workspace", slug: "mvp-management-workspace", category: "Startup Resources Tools", isPro: true },
  { id: 90, name: "Competitive Intelligence Workspace", slug: "competitive-intelligence-workspace", category: "Startup Resources Tools", isPro: true },
  { id: 91, name: "Business Model Workspace", slug: "business-model-workspace", category: "Startup Resources Tools", isPro: true },
  { id: 92, name: "Lean Canvas Workspace", slug: "lean-canvas-workspace", category: "Startup Resources Tools", isPro: true },
  { id: 93, name: "Startup Scenario Planner", slug: "startup-scenario-planner", category: "Startup Resources Tools", isPro: true },
  { id: 94, name: "Startup Financial Forecast Workspace", slug: "startup-financial-forecast-workspace", category: "Startup Resources Tools", isPro: true },
  { id: 95, name: "Startup Data Import Workspace", slug: "startup-data-import-workspace", category: "Startup Resources Tools", isPro: true },
  { id: 96, name: "Startup Report Generator", slug: "startup-report-generator", category: "Startup Resources Tools", isPro: true },
  { id: 97, name: "Startup API Workspace", slug: "startup-api-workspace", category: "Startup Resources Tools", isPro: true },
  { id: 98, name: "Founder Automation Workspace", slug: "founder-automation-workspace", category: "Startup Resources Tools", isPro: true },
  { id: 99, name: "Startup Intelligence Platform", slug: "startup-intelligence-platform", category: "Startup Resources Tools", isPro: true },
  { id: 100, name: "Venture Building Command Center", slug: "venture-building-command-center", category: "Startup Resources Tools", isPro: true }
];