export interface StockMarketTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const stockMarketToolsList: StockMarketTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "Stock Profit Calculator", slug: "stock-profit-calculator", category: "Stock Market Tools", isPro: false },
  { id: 2, name: "Stock ROI Calculator", slug: "stock-roi-calculator", category: "Stock Market Tools", isPro: false },
  { id: 3, name: "Stock Average Price Calculator", slug: "stock-average-price-calculator", category: "Stock Market Tools", isPro: false },
  { id: 4, name: "Stock Position Size Calculator", slug: "stock-position-size-calculator", category: "Stock Market Tools", isPro: false },
  { id: 5, name: "Risk-to-Reward Calculator", slug: "risk-to-reward-calculator", category: "Stock Market Tools", isPro: false },
  { id: 6, name: "Stock Portfolio Calculator", slug: "stock-portfolio-calculator", category: "Stock Market Tools", isPro: false },
  { id: 7, name: "Dividend Calculator", slug: "dividend-calculator", category: "Stock Market Tools", isPro: false },
  { id: 8, name: "Dividend Yield Calculator", slug: "dividend-yield-calculator", category: "Stock Market Tools", isPro: false },
  { id: 9, name: "Dividend Reinvestment Calculator", slug: "dividend-reinvestment-calculator", category: "Stock Market Tools", isPro: false },
  { id: 10, name: "SIP Calculator", slug: "sip-calculator", category: "Stock Market Tools", isPro: false },
  { id: 11, name: "CAGR Calculator", slug: "cagr-calculator", category: "Stock Market Tools", isPro: false },
  { id: 12, name: "Stock Valuation Calculator", slug: "stock-valuation-calculator", category: "Stock Market Tools", isPro: false },
  { id: 13, name: "P/E Ratio Calculator", slug: "pe-ratio-calculator", category: "Stock Market Tools", isPro: false },
  { id: 14, name: "EPS Calculator", slug: "eps-calculator", category: "Stock Market Tools", isPro: false },
  { id: 15, name: "EV/EBITDA Calculator", slug: "ev-ebitda-calculator", category: "Stock Market Tools", isPro: false },
  { id: 16, name: "Free Cash Flow Yield Calculator", slug: "free-cash-flow-yield-calculator", category: "Stock Market Tools", isPro: false },
  { id: 17, name: "Capital Gains Calculator", slug: "capital-gains-calculator", category: "Stock Market Tools", isPro: false },
  { id: 18, name: "Stock Comparison Tool", slug: "stock-comparison-tool", category: "Stock Market Tools", isPro: false },
  { id: 19, name: "Stock Loss Calculator", slug: "stock-loss-calculator", category: "Stock Market Tools", isPro: false },
  { id: 20, name: "Stock Return Calculator", slug: "stock-return-calculator", category: "Stock Market Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Stock Break-Even Calculator", slug: "stock-break-even-calculator", category: "Stock Market Tools", isPro: false },
  { id: 22, name: "Stock Risk Calculator", slug: "stock-risk-calculator", category: "Stock Market Tools", isPro: false },
  { id: 23, name: "Portfolio Allocation Calculator", slug: "portfolio-allocation-calculator", category: "Stock Market Tools", isPro: false },
  { id: 24, name: "Portfolio Rebalancing Calculator", slug: "portfolio-rebalancing-calculator", category: "Stock Market Tools", isPro: false },
  { id: 25, name: "Dividend Income Calculator", slug: "dividend-income-calculator", category: "Stock Market Tools", isPro: false },
  { id: 26, name: "Dividend Growth Calculator", slug: "dividend-growth-calculator", category: "Stock Market Tools", isPro: false },
  { id: 27, name: "DRIP Calculator", slug: "drip-calculator", category: "Stock Market Tools", isPro: false },
  { id: 28, name: "Compound Investment Calculator", slug: "compound-investment-calculator", category: "Stock Market Tools", isPro: false },
  { id: 29, name: "Lump Sum Investment Calculator", slug: "lump-sum-investment-calculator", category: "Stock Market Tools", isPro: false },
  { id: 30, name: "Dollar Cost Averaging Calculator", slug: "dollar-cost-averaging-calculator", category: "Stock Market Tools", isPro: false },
  { id: 31, name: "Investment Goal Calculator", slug: "investment-goal-calculator", category: "Stock Market Tools", isPro: false },
  { id: 32, name: "Retirement Investment Calculator", slug: "retirement-investment-calculator", category: "Stock Market Tools", isPro: false },
  { id: 33, name: "PEG Ratio Calculator", slug: "peg-ratio-calculator", category: "Stock Market Tools", isPro: false },
  { id: 34, name: "Price-to-Book Calculator", slug: "price-to-book-calculator", category: "Stock Market Tools", isPro: false },
  { id: 35, name: "Price-to-Sales Calculator", slug: "price-to-sales-calculator", category: "Stock Market Tools", isPro: false },
  { id: 36, name: "Enterprise Value Calculator", slug: "enterprise-value-calculator", category: "Stock Market Tools", isPro: false },
  { id: 37, name: "Dividend Payout Ratio Calculator", slug: "dividend-payout-ratio-calculator", category: "Stock Market Tools", isPro: false },
  { id: 38, name: "Return on Equity Calculator", slug: "return-on-equity-calculator", category: "Stock Market Tools", isPro: false },
  { id: 39, name: "Return on Assets Calculator", slug: "return-on-assets-calculator", category: "Stock Market Tools", isPro: false },
  { id: 40, name: "Debt-to-Equity Calculator", slug: "debt-to-equity-calculator", category: "Stock Market Tools", isPro: false },
  { id: 41, name: "Current Ratio Calculator", slug: "current-ratio-calculator", category: "Stock Market Tools", isPro: false },
  { id: 42, name: "Quick Ratio Calculator", slug: "quick-ratio-calculator", category: "Stock Market Tools", isPro: false },
  { id: 43, name: "Gross Margin Calculator", slug: "gross-margin-calculator", category: "Stock Market Tools", isPro: false },
  { id: 44, name: "Operating Margin Calculator", slug: "operating-margin-calculator", category: "Stock Market Tools", isPro: false },
  { id: 45, name: "Net Profit Margin Calculator", slug: "net-profit-margin-calculator", category: "Stock Market Tools", isPro: false },
  { id: 46, name: "Earnings Growth Calculator", slug: "earnings-growth-calculator", category: "Stock Market Tools", isPro: false },
  { id: 47, name: "Revenue Growth Calculator", slug: "revenue-growth-calculator", category: "Stock Market Tools", isPro: false },
  { id: 48, name: "Stock Split Calculator", slug: "stock-split-calculator", category: "Stock Market Tools", isPro: false },
  { id: 49, name: "Stock Dilution Calculator", slug: "stock-dilution-calculator", category: "Stock Market Tools", isPro: false },
  { id: 50, name: "Market Cap Calculator", slug: "market-cap-calculator", category: "Stock Market Tools", isPro: false },
  { id: 51, name: "Shares Outstanding Calculator", slug: "shares-outstanding-calculator", category: "Stock Market Tools", isPro: false },
  { id: 52, name: "Position Cost Calculator", slug: "position-cost-calculator", category: "Stock Market Tools", isPro: false },
  { id: 53, name: "Brokerage Fee Calculator", slug: "brokerage-fee-calculator", category: "Stock Market Tools", isPro: false },
  { id: 54, name: "Trading Cost Calculator", slug: "trading-cost-calculator", category: "Stock Market Tools", isPro: false },
  { id: 55, name: "Stock Tax Calculator", slug: "stock-tax-calculator", category: "Stock Market Tools", isPro: false },
  { id: 56, name: "Portfolio Tax Calculator", slug: "portfolio-tax-calculator", category: "Stock Market Tools", isPro: false },
  { id: 57, name: "Stock Performance Comparison", slug: "stock-performance-comparison", category: "Stock Market Tools", isPro: false },
  { id: 58, name: "Dividend Stock Comparison", slug: "dividend-stock-comparison", category: "Stock Market Tools", isPro: false },
  { id: 59, name: "Investment Checklist", slug: "investment-checklist", category: "Stock Market Tools", isPro: false },
  { id: 60, name: "Stock Research Checklist", slug: "stock-research-checklist", category: "Stock Market Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Stock Portfolio Intelligence Dashboard", slug: "stock-portfolio-intelligence-dashboard", category: "Stock Market Tools", isPro: true },
  { id: 62, name: "Fundamental Analysis Workspace", slug: "fundamental-analysis-workspace", category: "Stock Market Tools", isPro: true },
  { id: 63, name: "Portfolio Risk Analyzer", slug: "portfolio-risk-analyzer", category: "Stock Market Tools", isPro: true },
  { id: 64, name: "Portfolio Performance Analyzer", slug: "portfolio-performance-analyzer", category: "Stock Market Tools", isPro: true },
  { id: 65, name: "Portfolio Allocation Optimizer", slug: "portfolio-allocation-optimizer", category: "Stock Market Tools", isPro: true },
  { id: 66, name: "Portfolio Rebalancing Engine", slug: "portfolio-rebalancing-engine", category: "Stock Market Tools", isPro: true },
  { id: 67, name: "Dividend Portfolio Analyzer", slug: "dividend-portfolio-analyzer", category: "Stock Market Tools", isPro: true },
  { id: 68, name: "Dividend Income Forecast", slug: "dividend-income-forecast", category: "Stock Market Tools", isPro: true },
  { id: 69, name: "Dividend Growth Forecast", slug: "dividend-growth-forecast", category: "Stock Market Tools", isPro: true },
  { id: 70, name: "DRIP Forecast Engine", slug: "drip-forecast-engine", category: "Stock Market Tools", isPro: true },
  { id: 71, name: "Investment Goal Planner", slug: "investment-goal-planner", category: "Stock Market Tools", isPro: true },
  { id: 72, name: "Retirement Portfolio Planner", slug: "retirement-portfolio-planner", category: "Stock Market Tools", isPro: true },
  { id: 73, name: "Stock Valuation Engine", slug: "stock-valuation-engine", category: "Stock Market Tools", isPro: true },
  { id: 74, name: "Financial Statement Analyzer", slug: "financial-statement-analyzer", category: "Stock Market Tools", isPro: true },
  { id: 75, name: "Earnings Analysis Workspace", slug: "earnings-analysis-workspace", category: "Stock Market Tools", isPro: true },
  { id: 76, name: "Revenue Growth Analyzer", slug: "revenue-growth-analyzer", category: "Stock Market Tools", isPro: true },
  { id: 77, name: "Profitability Analyzer", slug: "profitability-analyzer", category: "Stock Market Tools", isPro: true },
  { id: 78, name: "Balance Sheet Analyzer", slug: "balance-sheet-analyzer", category: "Stock Market Tools", isPro: true },
  { id: 79, name: "Cash Flow Analyzer", slug: "cash-flow-analyzer", category: "Stock Market Tools", isPro: true },
  { id: 80, name: "Company Financial Health Score", slug: "company-financial-health-score", category: "Stock Market Tools", isPro: true },
  { id: 81, name: "Stock Quality Score", slug: "stock-quality-score", category: "Stock Market Tools", isPro: true },
  { id: 82, name: "Stock Risk Score", slug: "stock-risk-score", category: "Stock Market Tools", isPro: true },
  { id: 83, name: "Stock Valuation Score", slug: "stock-valuation-score", category: "Stock Market Tools", isPro: true },
  { id: 84, name: "Stock Comparison Engine", slug: "stock-comparison-engine", category: "Stock Market Tools", isPro: true },
  { id: 85, name: "Peer Comparison Analyzer", slug: "peer-comparison-analyzer", category: "Stock Market Tools", isPro: true },
  { id: 86, name: "Sector Comparison Workspace", slug: "sector-comparison-workspace", category: "Stock Market Tools", isPro: true },
  { id: 87, name: "Investment Scenario Analyzer", slug: "investment-scenario-analyzer", category: "Stock Market Tools", isPro: true },
  { id: 88, name: "Bull/Base/Bear Scenario Model", slug: "bull-base-bear-scenario-model", category: "Stock Market Tools", isPro: true },
  { id: 89, name: "Portfolio Stress Tester", slug: "portfolio-stress-tester", category: "Stock Market Tools", isPro: true },
  { id: 90, name: "Drawdown Analyzer", slug: "drawdown-analyzer", category: "Stock Market Tools", isPro: true },
  { id: 91, name: "Correlation Analyzer", slug: "correlation-analyzer", category: "Stock Market Tools", isPro: true },
  { id: 92, name: "Factor Exposure Analyzer", slug: "factor-exposure-analyzer", category: "Stock Market Tools", isPro: true },
  { id: 93, name: "Investment Tax Planning Workspace", slug: "investment-tax-planning-workspace", category: "Stock Market Tools", isPro: true },
  { id: 94, name: "Stock Research Workspace", slug: "stock-research-workspace", category: "Stock Market Tools", isPro: true },
  { id: 95, name: "Portfolio Journal Workspace", slug: "portfolio-journal-workspace", category: "Stock Market Tools", isPro: true },
  { id: 96, name: "Watchlist Intelligence Dashboard", slug: "watchlist-intelligence-dashboard", category: "Stock Market Tools", isPro: true },
  { id: 97, name: "Earnings Calendar Workspace", slug: "earnings-calendar-workspace", category: "Stock Market Tools", isPro: true },
  { id: 98, name: "Investment Decision Workspace", slug: "investment-decision-workspace", category: "Stock Market Tools", isPro: true },
  { id: 99, name: "Equity Research Intelligence Platform", slug: "equity-research-intelligence-platform", category: "Stock Market Tools", isPro: true },
  { id: 100, name: "Professional Portfolio Command Center", slug: "professional-portfolio-command-center", category: "Stock Market Tools", isPro: true }
];