export interface SupplyChainTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const supplyChainToolsList: SupplyChainTool[] = [
  // --- 🔥 PRIORITY 20 FREE TOOLS (IDs 1-20 | isPro: false) ---
  { id: 1, name: "Supply-Demand Balance Calculator", slug: "supply-demand-balance-calculator", category: "Supply Chain Management Tools", isPro: false },
  { id: 2, name: "Demand Coverage Calculator", slug: "demand-coverage-calculator", category: "Supply Chain Management Tools", isPro: false },
  { id: 3, name: "Lead Time Demand Calculator", slug: "lead-time-demand-calculator", category: "Supply Chain Management Tools", isPro: false },
  { id: 4, name: "Supplier Lead Time Calculator", slug: "supplier-lead-time-calculator", category: "Supply Chain Management Tools", isPro: false },
  { id: 5, name: "Supplier Reliability Calculator", slug: "supplier-reliability-calculator", category: "Supply Chain Management Tools", isPro: false },
  { id: 6, name: "Supplier On-Time Rate", slug: "supplier-on-time-rate", category: "Supply Chain Management Tools", isPro: false },
  { id: 7, name: "Supplier Fill Rate", slug: "supplier-fill-rate", category: "Supply Chain Management Tools", isPro: false },
  { id: 8, name: "Supply Risk Score", slug: "supply-risk-score", category: "Supply Chain Management Tools", isPro: false },
  { id: 9, name: "Supplier Concentration Calculator", slug: "supplier-concentration-calculator", category: "Supply Chain Management Tools", isPro: false },
  { id: 10, name: "Multi-Supplier Allocation Calculator", slug: "multi-supplier-allocation-calculator", category: "Supply Chain Management Tools", isPro: false },
  { id: 11, name: "Warehouse Capacity Planner", slug: "warehouse-capacity-planner", category: "Supply Chain Management Tools", isPro: false },
  { id: 12, name: "Container Utilization Calculator", slug: "container-utilization-calculator", category: "Supply Chain Management Tools", isPro: false },
  { id: 13, name: "Landed Cost Calculator", slug: "landed-cost-calculator", category: "Supply Chain Management Tools", isPro: false },
  { id: 14, name: "Order Fulfillment Rate", slug: "order-fulfillment-rate", category: "Supply Chain Management Tools", isPro: false },
  { id: 15, name: "Perfect Order Rate", slug: "perfect-order-rate", category: "Supply Chain Management Tools", isPro: false },
  { id: 16, name: "Stockout Rate Calculator", slug: "stockout-rate-calculator", category: "Supply Chain Management Tools", isPro: false },
  { id: 17, name: "Inventory Coverage Days", slug: "inventory-coverage-days", category: "Supply Chain Management Tools", isPro: false },
  { id: 18, name: "Demand Forecast Accuracy", slug: "demand-forecast-accuracy", category: "Supply Chain Management Tools", isPro: false },
  { id: 19, name: "Supplier Performance Dashboard", slug: "supplier-performance-dashboard-free", category: "Supply Chain Management Tools", isPro: false },
  { id: 20, name: "Supply Chain Control Tower", slug: "supply-chain-control-tower-free", category: "Supply Chain Management Tools", isPro: false },

  // --- REMAINING 40 CORE FREE TOOLS (IDs 21-60 | isPro: false) ---
  { id: 21, name: "Supply Planning Calculator", slug: "supply-planning-calculator", category: "Supply Chain Management Tools", isPro: false },
  { id: 22, name: "Supply Coverage Calculator", slug: "supply-coverage-calculator", category: "Supply Chain Management Tools", isPro: false },
  { id: 23, name: "Safety Stock Planning Calculator", slug: "safety-stock-planning-calculator", category: "Supply Chain Management Tools", isPro: false },
  { id: 24, name: "Replenishment Quantity Calculator", slug: "replenishment-quantity-calculator", category: "Supply Chain Management Tools", isPro: false },
  { id: 25, name: "Replenishment Frequency Calculator", slug: "replenishment-frequency-calculator", category: "Supply Chain Management Tools", isPro: false },
  { id: 26, name: "Order Cycle Calculator", slug: "order-cycle-calculator", category: "Supply Chain Management Tools", isPro: false },
  { id: 27, name: "Supplier Defect Rate", slug: "supplier-defect-rate", category: "Supply Chain Management Tools", isPro: false },
  { id: 28, name: "Supplier Quality Score", slug: "supplier-quality-score", category: "Supply Chain Management Tools", isPro: false },
  { id: 29, name: "Supplier Delivery Score", slug: "supplier-delivery-score", category: "Supply Chain Management Tools", isPro: false },
  { id: 30, name: "Supply Risk Matrix", slug: "supply-risk-matrix", category: "Supply Chain Management Tools", isPro: false },
  { id: 31, name: "Supply Chain Risk Checklist", slug: "supply-chain-risk-checklist", category: "Supply Chain Management Tools", isPro: false },
  { id: 32, name: "Supply Continuity Checklist", slug: "supply-continuity-checklist", category: "Supply Chain Management Tools", isPro: false },
  { id: 33, name: "Single Source Risk Checker", slug: "single-source-risk-checker", category: "Supply Chain Management Tools", isPro: false },
  { id: 34, name: "Supplier Dependency Calculator", slug: "supplier-dependency-calculator", category: "Supply Chain Management Tools", isPro: false },
  { id: 35, name: "Supply Allocation Planner", slug: "supply-allocation-planner", category: "Supply Chain Management Tools", isPro: false },
  { id: 36, name: "Demand Allocation Planner", slug: "demand-allocation-planner", category: "Supply Chain Management Tools", isPro: false },
  { id: 37, name: "Inventory Allocation Planner", slug: "inventory-allocation-planner", category: "Supply Chain Management Tools", isPro: false },
  { id: 38, name: "Distribution Allocation Planner", slug: "distribution-allocation-planner", category: "Supply Chain Management Tools", isPro: false },
  { id: 39, name: "Network Capacity Calculator", slug: "network-capacity-calculator", category: "Supply Chain Management Tools", isPro: false },
  { id: 40, name: "Storage Capacity Calculator", slug: "storage-capacity-calculator", category: "Supply Chain Management Tools", isPro: false },
  { id: 41, name: "Pallet Capacity Calculator", slug: "pallet-capacity-calculator", category: "Supply Chain Management Tools", isPro: false },
  { id: 42, name: "Transport Capacity Planner", slug: "transport-capacity-planner", category: "Supply Chain Management Tools", isPro: false },
  { id: 43, name: "Supply Chain Cost Calculator", slug: "supply-chain-cost-calculator", category: "Supply Chain Management Tools", isPro: false },
  { id: 44, name: "Procurement-to-Delivery Cost", slug: "procurement-to-delivery-cost", category: "Supply Chain Management Tools", isPro: false },
  { id: 45, name: "Freight Cost Allocation", slug: "freight-cost-allocation", category: "Supply Chain Management Tools", isPro: false },
  { id: 46, name: "Supply Chain Margin Calculator", slug: "supply-chain-margin-calculator", category: "Supply Chain Management Tools", isPro: false },
  { id: 47, name: "Backorder Rate Calculator", slug: "backorder-rate-calculator", category: "Supply Chain Management Tools", isPro: false },
  { id: 48, name: "Inventory Availability Calculator", slug: "inventory-availability-calculator", category: "Supply Chain Management Tools", isPro: false },
  { id: 49, name: "Supply Forecast Accuracy", slug: "supply-forecast-accuracy", category: "Supply Chain Management Tools", isPro: false },
  { id: 50, name: "Supplier Forecast Accuracy", slug: "supplier-forecast-accuracy", category: "Supply Chain Management Tools", isPro: false },
  { id: 51, name: "Order Lead Time Analyzer", slug: "order-lead-time-analyzer", category: "Supply Chain Management Tools", isPro: false },
  { id: 52, name: "Supply Cycle Time Calculator", slug: "supply-cycle-time-calculator", category: "Supply Chain Management Tools", isPro: false },
  { id: 53, name: "Supply Chain KPI Generator", slug: "supply-chain-kpi-generator", category: "Supply Chain Management Tools", isPro: false },
  { id: 54, name: "Supplier KPI Generator", slug: "supplier-kpi-generator", category: "Supply Chain Management Tools", isPro: false },
  { id: 55, name: "Supply Chain Report Generator", slug: "supply-chain-report-generator", category: "Supply Chain Management Tools", isPro: false },
  { id: 56, name: "Supplier Performance Report", slug: "supplier-performance-report", category: "Supply Chain Management Tools", isPro: false },
  { id: 57, name: "Supply Risk Report", slug: "supply-risk-report", category: "Supply Chain Management Tools", isPro: false },
  { id: 58, name: "Supply Planning Checklist", slug: "supply-planning-checklist", category: "Supply Chain Management Tools", isPro: false },
  { id: 59, name: "S&OP Checklist", slug: "sop-checklist", category: "Supply Chain Management Tools", isPro: false },
  { id: 60, name: "Supply Chain Audit Checklist", slug: "supply-chain-audit-checklist", category: "Supply Chain Management Tools", isPro: false },

  // --- ⚡ 40 PRO / SAAS TOOLS (IDs 61-100 | isPro: true) ---
  { id: 61, name: "Supply Chain Planning Workspace", slug: "supply-chain-planning-workspace", category: "Supply Chain Management Tools", isPro: true },
  { id: 62, name: "Supply-Demand Planning Dashboard", slug: "supply-demand-planning-dashboard", category: "Supply Chain Management Tools", isPro: true },
  { id: 63, name: "S&OP Workspace", slug: "sop-workspace", category: "Supply Chain Management Tools", isPro: true },
  { id: 64, name: "Supply Network Planning", slug: "supply-network-planning", category: "Supply Chain Management Tools", isPro: true },
  { id: 65, name: "Demand Allocation Workspace", slug: "demand-allocation-workspace", category: "Supply Chain Management Tools", isPro: true },
  { id: 66, name: "Supply Allocation Workspace", slug: "supply-allocation-workspace", category: "Supply Chain Management Tools", isPro: true },
  { id: 67, name: "Supplier Performance Dashboard", slug: "supplier-performance-dashboard", category: "Supply Chain Management Tools", isPro: true },
  { id: 68, name: "Supplier Risk Dashboard", slug: "supplier-risk-dashboard", category: "Supply Chain Management Tools", isPro: true },
  { id: 69, name: "Supplier Reliability Analytics", slug: "supplier-reliability-analytics", category: "Supply Chain Management Tools", isPro: true },
  { id: 70, name: "Supply Continuity Workspace", slug: "supply-continuity-workspace", category: "Supply Chain Management Tools", isPro: true },
  { id: 71, name: "Supply Risk Management", slug: "supply-risk-management", category: "Supply Chain Management Tools", isPro: true },
  { id: 72, name: "Supplier Dependency Analytics", slug: "supplier-dependency-analytics", category: "Supply Chain Management Tools", isPro: true },
  { id: 73, name: "Multi-Supplier Planning", slug: "multi-supplier-planning", category: "Supply Chain Management Tools", isPro: true },
  { id: 74, name: "Inventory Allocation Workspace", slug: "inventory-allocation-workspace", category: "Supply Chain Management Tools", isPro: true },
  { id: 75, name: "Warehouse Capacity Workspace", slug: "warehouse-capacity-workspace", category: "Supply Chain Management Tools", isPro: true },
  { id: 76, name: "Network Capacity Dashboard", slug: "network-capacity-dashboard", category: "Supply Chain Management Tools", isPro: true },
  { id: 77, name: "Supply Chain Cost Dashboard", slug: "supply-chain-cost-dashboard", category: "Supply Chain Management Tools", isPro: true },
  { id: 78, name: "Landed Cost Intelligence", slug: "landed-cost-intelligence", category: "Supply Chain Management Tools", isPro: true },
  { id: 79, name: "Supply Chain Profitability Workspace", slug: "supply-chain-profitability-workspace", category: "Supply Chain Management Tools", isPro: true },
  { id: 80, name: "Order Fulfillment Analytics", slug: "order-fulfillment-analytics", category: "Supply Chain Management Tools", isPro: true },
  { id: 81, name: "Stockout Analytics", slug: "stockout-analytics", category: "Supply Chain Management Tools", isPro: true },
  { id: 82, name: "Backorder Analytics", slug: "backorder-analytics", category: "Supply Chain Management Tools", isPro: true },
  { id: 83, name: "Supply Forecasting Workspace", slug: "supply-forecasting-workspace", category: "Supply Chain Management Tools", isPro: true },
  { id: 84, name: "Demand-Supply Scenario Planner", slug: "demand-supply-scenario-planner", category: "Supply Chain Management Tools", isPro: true },
  { id: 85, name: "Supply Chain Simulation Workspace", slug: "supply-chain-simulation-workspace", category: "Supply Chain Management Tools", isPro: true },
  { id: 86, name: "Supply Chain KPI Dashboard", slug: "supply-chain-kpi-dashboard", category: "Supply Chain Management Tools", isPro: true },
  { id: 87, name: "Supplier Scorecard Workspace", slug: "supplier-scorecard-workspace", category: "Supply Chain Management Tools", isPro: true },
  { id: 88, name: "Supplier Collaboration Workspace", slug: "supplier-collaboration-workspace", category: "Supply Chain Management Tools", isPro: true },
  { id: 89, name: "Supply Chain Audit Workspace", slug: "supply-chain-audit-workspace", category: "Supply Chain Management Tools", isPro: true },
  { id: 90, name: "Supply Chain Reporting Engine", slug: "supply-chain-reporting-engine", category: "Supply Chain Management Tools", isPro: true },
  { id: 91, name: "Supply Chain Data Importer", slug: "supply-chain-data-importer", category: "Supply Chain Management Tools", isPro: true },
  { id: 92, name: "Supply Chain Data Exporter", slug: "supply-chain-data-exporter", category: "Supply Chain Management Tools", isPro: true },
  { id: 93, name: "Supply Chain API Workspace", slug: "supply-chain-api-workspace", category: "Supply Chain Management Tools", isPro: true },
  { id: 94, name: "Supply Chain Automation", slug: "supply-chain-automation", category: "Supply Chain Management Tools", isPro: true },
  { id: 95, name: "Supply Chain Alert Engine", slug: "supply-chain-alert-engine", category: "Supply Chain Management Tools", isPro: true },
  { id: 96, name: "Supply Chain Control Tower Pro", slug: "supply-chain-control-tower-pro", category: "Supply Chain Management Tools", isPro: true },
  { id: 97, name: "Supply Chain Intelligence Platform", slug: "supply-chain-intelligence-platform", category: "Supply Chain Management Tools", isPro: true },
  { id: 98, name: "Digital Supply Chain Workspace", slug: "digital-supply-chain-workspace", category: "Supply Chain Management Tools", isPro: true },
  { id: 99, name: "Enterprise Supply Chain Platform", slug: "enterprise-supply-chain-platform", category: "Supply Chain Management Tools", isPro: true },
  { id: 100, name: "Supply Chain Command Center", slug: "supply-chain-command-center", category: "Supply Chain Management Tools", isPro: true }
];