export interface TextTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const textToolsList: TextTool[] = [
  // --- TOP PRIORITY (FREE CORE TOOLS) ---
  { id: 1, name: "Word Counter", slug: "word-counter", category: "Text Tools", isPro: false },
  { id: 2, name: "Character Counter", slug: "character-counter", category: "Text Tools", isPro: false },
  { id: 3, name: "Text Case Converter", slug: "text-case-converter", category: "Text Tools", isPro: false },
  { id: 4, name: "Text Compare Tool", slug: "text-compare-tool", category: "Text Tools", isPro: false },
  { id: 5, name: "Find and Replace Text", slug: "find-and-replace-text", category: "Text Tools", isPro: false },
  { id: 6, name: "Remove Duplicate Lines", slug: "remove-duplicate-lines", category: "Text Tools", isPro: false },
  { id: 7, name: "Markdown Formatter", slug: "markdown-formatter", category: "Text Tools", isPro: false },
  { id: 8, name: "Markdown to HTML Converter", slug: "markdown-to-html-converter", category: "Text Tools", isPro: false },
  { id: 9, name: "HTML to Markdown Converter", slug: "html-to-markdown-converter", category: "Text Tools", isPro: false },
  { id: 10, name: "Text Statistics Analyzer", slug: "text-statistics-analyzer", category: "Text Tools", isPro: false },
  { id: 11, name: "Readability Score Checker", slug: "readability-score-checker", category: "Text Tools", isPro: false },
  { id: 12, name: "Keyword Extractor", slug: "keyword-extractor", category: "Text Tools", isPro: false },
  { id: 13, name: "Keyword Frequency Analyzer", slug: "keyword-frequency-analyzer", category: "Text Tools", isPro: false },

  // --- REMAINING CORE / HIGH-DEMAND (FREE TOOLS: 14-60) ---
  { id: 14, name: "Sentence Counter", slug: "sentence-counter", category: "Text Tools", isPro: false },
  { id: 15, name: "Paragraph Counter", slug: "paragraph-counter", category: "Text Tools", isPro: false },
  { id: 16, name: "Letter Counter", slug: "letter-counter", category: "Text Tools", isPro: false },
  { id: 17, name: "Line Counter", slug: "line-counter", category: "Text Tools", isPro: false },
  { id: 18, name: "Reading Time Calculator", slug: "reading-time-calculator", category: "Text Tools", isPro: false },
  { id: 19, name: "Speaking Time Calculator", slug: "speaking-time-calculator", category: "Text Tools", isPro: false },
  { id: 20, name: "Uppercase Converter", slug: "uppercase-converter", category: "Text Tools", isPro: false },
  { id: 21, name: "Lowercase Converter", slug: "lowercase-converter", category: "Text Tools", isPro: false },
  { id: 22, name: "Title Case Converter", slug: "title-case-converter", category: "Text Tools", isPro: false },
  { id: 23, name: "Sentence Case Converter", slug: "sentence-case-converter", category: "Text Tools", isPro: false },
  { id: 24, name: "Capitalization Fixer", slug: "capitalization-fixer", category: "Text Tools", isPro: false },
  { id: 25, name: "Remove Extra Spaces", slug: "remove-extra-spaces", category: "Text Tools", isPro: false },
  { id: 26, name: "Remove Blank Lines", slug: "remove-blank-lines", category: "Text Tools", isPro: false },
  { id: 27, name: "Sort Lines Alphabetically", slug: "sort-lines-alphabetically", category: "Text Tools", isPro: false },
  { id: 28, name: "Reverse Text", slug: "reverse-text", category: "Text Tools", isPro: false },
  { id: 29, name: "Reverse Words", slug: "reverse-words", category: "Text Tools", isPro: false },
  { id: 30, name: "Reverse Letters", slug: "reverse-letters", category: "Text Tools", isPro: false },
  { id: 31, name: "Text Repeater", slug: "text-repeater", category: "Text Tools", isPro: false },
  { id: 32, name: "Text Separator", slug: "text-separator", category: "Text Tools", isPro: false },
  { id: 33, name: "Text Joiner", slug: "text-joiner", category: "Text Tools", isPro: false },
  { id: 34, name: "Text Splitter", slug: "text-splitter", category: "Text Tools", isPro: false },
  { id: 35, name: "Text Cleaner", slug: "text-cleaner", category: "Text Tools", isPro: false },
  { id: 36, name: "Text Normalizer", slug: "text-normalizer", category: "Text Tools", isPro: false },
  { id: 37, name: "Whitespace Cleaner", slug: "whitespace-cleaner", category: "Text Tools", isPro: false },
  { id: 38, name: "Line Break Remover", slug: "line-break-remover", category: "Text Tools", isPro: false },
  { id: 39, name: "Newline Converter", slug: "newline-converter", category: "Text Tools", isPro: false },
  { id: 40, name: "Tab to Space Converter", slug: "tab-to-space-converter", category: "Text Tools", isPro: false },
  { id: 41, name: "Space to Tab Converter", slug: "space-to-tab-converter", category: "Text Tools", isPro: false },
  { id: 42, name: "Text Difference Checker", slug: "text-difference-checker", category: "Text Tools", isPro: false },
  { id: 43, name: "Word Frequency Counter", slug: "word-frequency-counter", category: "Text Tools", isPro: false },
  { id: 44, name: "Character Frequency Counter", slug: "character-frequency-counter", category: "Text Tools", isPro: false },
  { id: 45, name: "Duplicate Word Finder", slug: "duplicate-word-finder", category: "Text Tools", isPro: false },
  { id: 46, name: "Repeated Phrase Finder", slug: "repeated-phrase-finder", category: "Text Tools", isPro: false },
  { id: 47, name: "Text Extractor", slug: "text-extractor", category: "Text Tools", isPro: false },
  { id: 48, name: "Plain Text Converter", slug: "plain-text-converter", category: "Text Tools", isPro: false },
  { id: 49, name: "Rich Text Cleaner", slug: "rich-text-cleaner", category: "Text Tools", isPro: false },
  { id: 50, name: "Markdown Previewer", slug: "markdown-previewer", category: "Text Tools", isPro: false },
  { id: 51, name: "Markdown Table Generator", slug: "markdown-table-generator", category: "Text Tools", isPro: false },
  { id: 52, name: "HTML Text Extractor", slug: "html-text-extractor", category: "Text Tools", isPro: false },
  { id: 53, name: "URL Text Extractor", slug: "url-text-extractor", category: "Text Tools", isPro: false },
  { id: 54, name: "Text to URL Slug", slug: "text-to-url-slug", category: "Text Tools", isPro: false },
  { id: 55, name: "Text to Hashtag Converter", slug: "text-to-hashtag-converter", category: "Text Tools", isPro: false },
  { id: 56, name: "Text to Bullet List", slug: "text-to-bullet-list", category: "Text Tools", isPro: false },
  { id: 57, name: "Text to Numbered List", slug: "text-to-numbered-list", category: "Text Tools", isPro: false },
  { id: 58, name: "List to Paragraph Converter", slug: "list-to-paragraph-converter", category: "Text Tools", isPro: false },
  { id: 59, name: "Paragraph to List Converter", slug: "paragraph-to-list-converter", category: "Text Tools", isPro: false },
  { id: 60, name: "Writing Time Estimator", slug: "writing-time-estimator", category: "Text Tools", isPro: false },

  // --- TOP PRIORITY (PRO LEVEL TOOLS) ---
  { id: 61, name: "Document Comparison Tool", slug: "document-comparison-tool", category: "Text Tools", isPro: true },
  { id: 62, name: "Semantic Text Comparison", slug: "semantic-text-comparison", category: "Text Tools", isPro: true },
  { id: 63, name: "Regex Tester", slug: "regex-tester", category: "Text Tools", isPro: true },
  { id: 64, name: "Regex Find & Replace", slug: "regex-find-and-replace", category: "Text Tools", isPro: true },
  { id: 65, name: "Structured Text Parser", slug: "structured-text-parser", category: "Text Tools", isPro: true },
  { id: 66, name: "Text Encoding Detector", slug: "text-encoding-detector", category: "Text Tools", isPro: true },
  { id: 67, name: "Unicode Inspector", slug: "unicode-inspector", category: "Text Tools", isPro: true },
  { id: 68, name: "Text Entropy Analyzer", slug: "text-entropy-analyzer", category: "Text Tools", isPro: true },
  { id: 69, name: "Keyword Density Analyzer", slug: "keyword-density-analyzer", category: "Text Tools", isPro: true },
  { id: 70, name: "Writing Complexity Analyzer", slug: "writing-complexity-analyzer", category: "Text Tools", isPro: true },
  { id: 71, name: "Professional Writing Analyzer", slug: "professional-writing-analyzer", category: "Text Tools", isPro: true },

  // --- REMAINING PRO LEVEL TOOLS (72-100) ---
  { id: 72, name: "Text Diff Analyzer", slug: "text-diff-analyzer", category: "Text Tools", isPro: true },
  { id: 73, name: "Multi-Document Text Compare", slug: "multi-document-text-compare", category: "Text Tools", isPro: true },
  { id: 74, name: "Regex Text Extractor", slug: "regex-text-extractor", category: "Text Tools", isPro: true },
  { id: 75, name: "Regex Match Analyzer", slug: "regex-match-analyzer", category: "Text Tools", isPro: true },
  { id: 76, name: "Pattern Extractor", slug: "pattern-extractor", category: "Text Tools", isPro: true },
  { id: 77, name: "CSV Text Parser", slug: "csv-text-parser", category: "Text Tools", isPro: true },
  { id: 78, name: "Delimited Text Converter", slug: "delimited-text-converter", category: "Text Tools", isPro: true },
  { id: 79, name: "Fixed-Width Text Parser", slug: "fixed-width-text-parser", category: "Text Tools", isPro: true },
  { id: 80, name: "UTF-8 Validator", slug: "utf-8-validator", category: "Text Tools", isPro: true },
  { id: 81, name: "Unicode Normalizer", slug: "unicode-normalizer", category: "Text Tools", isPro: true },
  { id: 82, name: "Unicode Character Search", slug: "unicode-character-search", category: "Text Tools", isPro: true },
  { id: 83, name: "Unicode Escape Converter", slug: "unicode-escape-converter", category: "Text Tools", isPro: true },
  { id: 84, name: "ASCII Art Generator", slug: "ascii-art-generator", category: "Text Tools", isPro: true },
  { id: 85, name: "Text to ASCII Converter", slug: "text-to-ascii-converter", category: "Text Tools", isPro: true },
  { id: 86, name: "Text to Binary Converter", slug: "text-to-binary-converter", category: "Text Tools", isPro: true },
  { id: 87, name: "Binary to Text Converter", slug: "binary-to-text-converter", category: "Text Tools", isPro: true },
  { id: 88, name: "Text to Hex Converter", slug: "text-to-hex-converter", category: "Text Tools", isPro: true },
  { id: 89, name: "Hex to Text Converter", slug: "hex-to-text-converter", category: "Text Tools", isPro: true },
  { id: 90, name: "Text to Base64 Converter", slug: "text-to-base64-converter", category: "Text Tools", isPro: true },
  { id: 91, name: "Base64 to Text Converter", slug: "base64-to-text-converter", category: "Text Tools", isPro: true },
  { id: 92, name: "ROT13 Encoder", slug: "rot13-encoder", category: "Text Tools", isPro: true },
  { id: 93, name: "ROT13 Decoder", slug: "rot13-decoder", category: "Text Tools", isPro: true },
  { id: 94, name: "Morse Code Converter", slug: "morse-code-converter", category: "Text Tools", isPro: true },
  { id: 95, name: "Vocabulary Analyzer", slug: "vocabulary-analyzer", category: "Text Tools", isPro: true },
  { id: 96, name: "Sentence Structure Analyzer", slug: "sentence-structure-analyzer", category: "Text Tools", isPro: true },
  { id: 97, name: "Passive Voice Detector", slug: "passive-voice-detector", category: "Text Tools", isPro: true },
  { id: 98, name: "Filler Word Detector", slug: "filler-word-detector", category: "Text Tools", isPro: true },
  { id: 99, name: "Cliché Detector", slug: "cliche-detector", category: "Text Tools", isPro: true },
  { id: 100, name: "Inclusive Language Checker", slug: "inclusive-language-checker", category: "Text Tools", isPro: true },
];