export interface TravelTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const travelToolsList: TravelTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "Trip Budget Calculator", slug: "trip-budget-calculator", category: "Travel Tools", isPro: false },
  { id: 2, name: "Vacation Cost Calculator", slug: "vacation-cost-calculator", category: "Travel Tools", isPro: false },
  { id: 3, name: "Daily Travel Budget Calculator", slug: "daily-travel-budget-calculator", category: "Travel Tools", isPro: false },
  { id: 4, name: "Trip Duration Calculator", slug: "trip-duration-calculator", category: "Travel Tools", isPro: false },
  { id: 5, name: "Flight Duration Calculator", slug: "flight-duration-calculator", category: "Travel Tools", isPro: false },
  { id: 6, name: "Time Zone Difference Calculator", slug: "time-zone-difference-calculator", category: "Travel Tools", isPro: false },
  { id: 7, name: "Jet Lag Calculator", slug: "jet-lag-calculator", category: "Travel Tools", isPro: false },
  { id: 8, name: "Travel Currency Budget Planner", slug: "travel-currency-budget-planner", category: "Travel Tools", isPro: false },
  { id: 9, name: "Group Travel Expense Splitter", slug: "group-travel-expense-splitter", category: "Travel Tools", isPro: false },
  { id: 10, name: "Road Trip Planner", slug: "road-trip-planner", category: "Travel Tools", isPro: false },
  { id: 11, name: "Road Trip Fuel Cost Calculator", slug: "road-trip-fuel-cost-calculator", category: "Travel Tools", isPro: false },
  { id: 12, name: "Travel Packing List Generator", slug: "travel-packing-list-generator", category: "Travel Tools", isPro: false },
  { id: 13, name: "Passport Validity Checker", slug: "passport-validity-checker", category: "Travel Tools", isPro: false },
  { id: 14, name: "Visa Stay Calculator", slug: "visa-stay-calculator", category: "Travel Tools", isPro: false },
  { id: 15, name: "Travel Insurance Cost Calculator", slug: "travel-insurance-cost-calculator", category: "Travel Tools", isPro: false },
  { id: 16, name: "Rental Car Cost Calculator", slug: "rental-car-cost-calculator", category: "Travel Tools", isPro: false },
  { id: 17, name: "Travel Itinerary Generator", slug: "travel-itinerary-generator", category: "Travel Tools", isPro: false },
  { id: 18, name: "Destination Comparison Tool", slug: "destination-comparison-tool", category: "Travel Tools", isPro: false },
  { id: 19, name: "Complete Trip Planner", slug: "complete-trip-planner", category: "Travel Tools", isPro: false },
  { id: 20, name: "Travel Budget Optimizer", slug: "travel-budget-optimizer", category: "Travel Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Travel Budget Planner", slug: "travel-budget-planner", category: "Travel Tools", isPro: false },
  { id: 22, name: "Flight Cost Splitter", slug: "flight-cost-splitter", category: "Travel Tools", isPro: false },
  { id: 23, name: "Hotel Cost Calculator", slug: "hotel-cost-calculator", category: "Travel Tools", isPro: false },
  { id: 24, name: "Accommodation Cost Splitter", slug: "accommodation-cost-splitter", category: "Travel Tools", isPro: false },
  { id: 25, name: "Travel Expense Splitter", slug: "travel-expense-splitter", category: "Travel Tools", isPro: false },
  { id: 26, name: "Per-Day Travel Cost Calculator", slug: "per-day-travel-cost-calculator", category: "Travel Tools", isPro: false },
  { id: 27, name: "Travel Date Calculator", slug: "travel-date-calculator", category: "Travel Tools", isPro: false },
  { id: 28, name: "Days Until Trip Calculator", slug: "days-until-trip-calculator", category: "Travel Tools", isPro: false },
  { id: 29, name: "Departure Time Calculator", slug: "departure-time-calculator", category: "Travel Tools", isPro: false },
  { id: 30, name: "Arrival Time Calculator", slug: "arrival-time-calculator", category: "Travel Tools", isPro: false },
  { id: 31, name: "Layover Duration Calculator", slug: "layover-duration-calculator", category: "Travel Tools", isPro: false },
  { id: 32, name: "Jet Lag Planner", slug: "jet-lag-planner", category: "Travel Tools", isPro: false },
  { id: 33, name: "Currency Conversion Calculator", slug: "currency-conversion-calculator", category: "Travel Tools", isPro: false },
  { id: 34, name: "Foreign Exchange Fee Calculator", slug: "foreign-exchange-fee-calculator", category: "Travel Tools", isPro: false },
  { id: 35, name: "Travel Tip Calculator", slug: "travel-tip-calculator", category: "Travel Tools", isPro: false },
  { id: 36, name: "Restaurant Tip Splitter", slug: "restaurant-tip-splitter", category: "Travel Tools", isPro: false },
  { id: 37, name: "Road Trip Distance Calculator", slug: "road-trip-distance-calculator", category: "Travel Tools", isPro: false },
  { id: 38, name: "Road Trip Stop Planner", slug: "road-trip-stop-planner", category: "Travel Tools", isPro: false },
  { id: 39, name: "Business Travel Packing List", slug: "business-travel-packing-list", category: "Travel Tools", isPro: false },
  { id: 40, name: "Vacation Packing List", slug: "vacation-packing-list", category: "Travel Tools", isPro: false },
  { id: 41, name: "Beach Trip Packing List", slug: "beach-trip-packing-list", category: "Travel Tools", isPro: false },
  { id: 42, name: "Winter Trip Packing List", slug: "winter-trip-packing-list", category: "Travel Tools", isPro: false },
  { id: 43, name: "Family Travel Packing List", slug: "family-travel-packing-list", category: "Travel Tools", isPro: false },
  { id: 44, name: "Carry-On Packing Checklist", slug: "carry-on-packing-checklist", category: "Travel Tools", isPro: false },
  { id: 45, name: "Travel Document Checklist", slug: "travel-document-checklist", category: "Travel Tools", isPro: false },
  { id: 46, name: "Visa Requirement Checklist", slug: "visa-requirement-checklist", category: "Travel Tools", isPro: false },
  { id: 47, name: "Travel Insurance Coverage Checklist", slug: "travel-insurance-coverage-checklist", category: "Travel Tools", isPro: false },
  { id: 48, name: "Visa Duration Calculator", slug: "visa-duration-calculator", category: "Travel Tools", isPro: false },
  { id: 49, name: "Hotel Room Split Calculator", slug: "hotel-room-split-calculator", category: "Travel Tools", isPro: false },
  { id: 50, name: "Accommodation Comparison Calculator", slug: "accommodation-comparison-calculator", category: "Travel Tools", isPro: false },
  { id: 51, name: "Flight Layover Planner", slug: "flight-layover-planner", category: "Travel Tools", isPro: false },
  { id: 52, name: "Airport Transfer Cost Calculator", slug: "airport-transfer-cost-calculator", category: "Travel Tools", isPro: false },
  { id: 53, name: "Airport Parking Cost Calculator", slug: "airport-parking-cost-calculator", category: "Travel Tools", isPro: false },
  { id: 54, name: "Rental Car Fuel Calculator", slug: "rental-car-fuel-calculator", category: "Travel Tools", isPro: false },
  { id: 55, name: "Daily Itinerary Planner", slug: "daily-itinerary-planner", category: "Travel Tools", isPro: false },
  { id: 56, name: "Multi-City Trip Planner", slug: "multi-city-trip-planner", category: "Travel Tools", isPro: false },
  { id: 57, name: "Travel Distance Calculator", slug: "travel-distance-calculator", category: "Travel Tools", isPro: false },
  { id: 58, name: "Great Circle Distance Calculator", slug: "great-circle-distance-calculator", category: "Travel Tools", isPro: false },
  { id: 59, name: "Country Travel Information Finder", slug: "country-travel-information-finder", category: "Travel Tools", isPro: false },
  { id: 60, name: "Airport Code Finder", slug: "airport-code-finder", category: "Travel Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Flight Time Zone Planner", slug: "flight-time-zone-planner", category: "Travel Tools", isPro: true },
  { id: 62, name: "Travel Checklist Generator", slug: "travel-checklist-generator", category: "Travel Tools", isPro: true },
  { id: 63, name: "AI Itinerary Optimizer", slug: "ai-itinerary-optimizer", category: "Travel Tools", isPro: true },
  { id: 64, name: "Multi-City Route Optimizer", slug: "multi-city-route-optimizer", category: "Travel Tools", isPro: true },
  { id: 65, name: "Group Trip Planner", slug: "group-trip-planner", category: "Travel Tools", isPro: true },
  { id: 66, name: "Family Trip Planner", slug: "family-trip-planner", category: "Travel Tools", isPro: true },
  { id: 67, name: "Business Travel Planner", slug: "business-travel-planner", category: "Travel Tools", isPro: true },
  { id: 68, name: "Corporate Travel Budget Analyzer", slug: "corporate-travel-budget-analyzer", category: "Travel Tools", isPro: true },
  { id: 69, name: "Travel Expense Management Workspace", slug: "travel-expense-management-workspace", category: "Travel Tools", isPro: true },
  { id: 70, name: "Travel Policy Compliance Checker", slug: "travel-policy-compliance-checker", category: "Travel Tools", isPro: true },
  { id: 71, name: "Destination Cost Analyzer", slug: "destination-cost-analyzer", category: "Travel Tools", isPro: true },
  { id: 72, name: "Destination Comparison Engine", slug: "destination-comparison-engine", category: "Travel Tools", isPro: true },
  { id: 73, name: "Flight Connection Risk Analyzer", slug: "flight-connection-risk-analyzer", category: "Travel Tools", isPro: true },
  { id: 74, name: "Layover Optimization Engine", slug: "layover-optimization-engine", category: "Travel Tools", isPro: true },
  { id: 75, name: "Travel Time Optimization Tool", slug: "travel-time-optimization-tool", category: "Travel Tools", isPro: true },
  { id: 76, name: "Hotel Value Analyzer", slug: "hotel-value-analyzer", category: "Travel Tools", isPro: true },
  { id: 77, name: "Accommodation Deal Analyzer", slug: "accommodation-deal-analyzer", category: "Travel Tools", isPro: true },
  { id: 78, name: "Rental Car Deal Analyzer", slug: "rental-car-deal-analyzer", category: "Travel Tools", isPro: true },
  { id: 79, name: "Travel Insurance Comparison Engine", slug: "travel-insurance-comparison-engine", category: "Travel Tools", isPro: true },
  { id: 80, name: "Trip Risk Analyzer", slug: "trip-risk-analyzer", category: "Travel Tools", isPro: true },
  { id: 81, name: "Travel Document Manager", slug: "travel-document-manager", category: "Travel Tools", isPro: true },
  { id: 82, name: "Visa Planning Workspace", slug: "visa-planning-workspace", category: "Travel Tools", isPro: true },
  { id: 83, name: "Passport Travel Planner", slug: "passport-travel-planner", category: "Travel Tools", isPro: true },
  { id: 84, name: "Travel Currency Intelligence", slug: "travel-currency-intelligence", category: "Travel Tools", isPro: true },
  { id: 85, name: "Group Expense Settlement Workspace", slug: "group-expense-settlement-workspace", category: "Travel Tools", isPro: true },
  { id: 86, name: "Trip Expense Dashboard", slug: "trip-expense-dashboard", category: "Travel Tools", isPro: true },
  { id: 87, name: "Travel Itinerary Workspace", slug: "travel-itinerary-workspace", category: "Travel Tools", isPro: true },
  { id: 88, name: "Travel Booking Organizer", slug: "travel-booking-organizer", category: "Travel Tools", isPro: true },
  { id: 89, name: "Frequent Traveler Dashboard", slug: "frequent-traveler-dashboard", category: "Travel Tools", isPro: true },
  { id: 90, name: "Business Trip Intelligence Workspace", slug: "business-trip-intelligence-workspace", category: "Travel Tools", isPro: true },
  { id: 91, name: "Family Travel Workspace", slug: "family-travel-workspace", category: "Travel Tools", isPro: true },
  { id: 92, name: "Multi-Destination Travel Workspace", slug: "multi-destination-travel-workspace", category: "Travel Tools", isPro: true },
  { id: 93, name: "Travel Cost Forecasting Engine", slug: "travel-cost-forecasting-engine", category: "Travel Tools", isPro: true },
  { id: 94, name: "Destination Intelligence Dashboard", slug: "destination-intelligence-dashboard", category: "Travel Tools", isPro: true },
  { id: 95, name: "Travel Planning Assistant", slug: "travel-planning-assistant", category: "Travel Tools", isPro: true },
  { id: 96, name: "Global Trip Intelligence Workspace", slug: "global-trip-intelligence-workspace", category: "Travel Tools", isPro: true },
  { id: 97, name: "Corporate Travel Management Workspace", slug: "corporate-travel-management-workspace", category: "Travel Tools", isPro: true },
  { id: 98, name: "Travel Operations Dashboard", slug: "travel-operations-dashboard", category: "Travel Tools", isPro: true },
  { id: 99, name: "Travel Budget Intelligence Platform", slug: "travel-budget-intelligence-platform", category: "Travel Tools", isPro: true },
  { id: 100, name: "Complete Travel Command Center", slug: "complete-travel-command-center", category: "Travel Tools", isPro: true }
];