export interface UtilityCalculatorTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const utilityCalculatorsList: UtilityCalculatorTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "Percentage Calculator", slug: "percentage-calculator", category: "Utility Calculators", isPro: false },
  { id: 2, name: "Percentage Increase Calculator", slug: "percentage-increase-calculator", category: "Utility Calculators", isPro: false },
  { id: 3, name: "Percentage Decrease Calculator", slug: "percentage-decrease-calculator", category: "Utility Calculators", isPro: false },
  { id: 4, name: "Age Calculator", slug: "age-calculator", category: "Utility Calculators", isPro: false },
  { id: 5, name: "Date Difference Calculator", slug: "date-difference-calculator", category: "Utility Calculators", isPro: false },
  { id: 6, name: "Time Duration Calculator", slug: "time-duration-calculator", category: "Utility Calculators", isPro: false },
  { id: 7, name: "Business Days Calculator", slug: "business-days-calculator", category: "Utility Calculators", isPro: false },
  { id: 8, name: "Salary Calculator", slug: "salary-calculator", category: "Utility Calculators", isPro: false },
  { id: 9, name: "Overtime Calculator", slug: "overtime-calculator", category: "Utility Calculators", isPro: false },
  { id: 10, name: "Discount Calculator", slug: "discount-calculator-utility", category: "Utility Calculators", isPro: false },
  { id: 11, name: "Tip Calculator", slug: "tip-calculator", category: "Utility Calculators", isPro: false },
  { id: 12, name: "Fuel Cost Calculator", slug: "fuel-cost-calculator", category: "Utility Calculators", isPro: false },
  { id: 13, name: "Electricity Cost Calculator", slug: "electricity-cost-calculator", category: "Utility Calculators", isPro: false },
  { id: 14, name: "Currency Converter", slug: "currency-converter", category: "Utility Calculators", isPro: false },
  { id: 15, name: "Unit Converter", slug: "unit-converter", category: "Utility Calculators", isPro: false },
  { id: 16, name: "BMI Calculator", slug: "bmi-calculator", category: "Utility Calculators", isPro: false },
  { id: 17, name: "Calorie Calculator", slug: "calorie-calculator", category: "Utility Calculators", isPro: false },
  { id: 18, name: "Investment Return Calculator", slug: "investment-return-calculator-utility", category: "Utility Calculators", isPro: false },
  { id: 19, name: "Ratio Calculator", slug: "ratio-calculator", category: "Utility Calculators", isPro: false },
  { id: 20, name: "Proportion Calculator", slug: "proportion-calculator", category: "Utility Calculators", isPro: false },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Average Calculator", slug: "average-calculator", category: "Utility Calculators", isPro: false },
  { id: 22, name: "Mean Calculator", slug: "mean-calculator", category: "Utility Calculators", isPro: false },
  { id: 23, name: "Median Calculator", slug: "median-calculator", category: "Utility Calculators", isPro: false },
  { id: 24, name: "Mode Calculator", slug: "mode-calculator", category: "Utility Calculators", isPro: false },
  { id: 25, name: "Weighted Average Calculator", slug: "weighted-average-calculator", category: "Utility Calculators", isPro: false },
  { id: 26, name: "Fraction Calculator", slug: "fraction-calculator", category: "Utility Calculators", isPro: false },
  { id: 27, name: "Decimal Calculator", slug: "decimal-calculator", category: "Utility Calculators", isPro: false },
  { id: 28, name: "Mixed Number Calculator", slug: "mixed-number-calculator", category: "Utility Calculators", isPro: false },
  { id: 29, name: "Markup Calculator", slug: "markup-calculator-utility", category: "Utility Calculators", isPro: false },
  { id: 30, name: "Tax Calculator", slug: "tax-calculator", category: "Utility Calculators", isPro: false },
  { id: 31, name: "Split Bill Calculator", slug: "split-bill-calculator", category: "Utility Calculators", isPro: false },
  { id: 32, name: "Time Difference Calculator", slug: "time-difference-calculator", category: "Utility Calculators", isPro: false },
  { id: 33, name: "Countdown Calculator", slug: "countdown-calculator", category: "Utility Calculators", isPro: false },
  { id: 34, name: "Workdays Calculator", slug: "workdays-calculator", category: "Utility Calculators", isPro: false },
  { id: 35, name: "Days Between Dates Calculator", slug: "days-between-dates-calculator", category: "Utility Calculators", isPro: false },
  { id: 36, name: "Week Number Calculator", slug: "week-number-calculator", category: "Utility Calculators", isPro: false },
  { id: 37, name: "Weekday Calculator", slug: "weekday-calculator", category: "Utility Calculators", isPro: false },
  { id: 38, name: "Leap Year Calculator", slug: "leap-year-calculator", category: "Utility Calculators", isPro: false },
  { id: 39, name: "Hourly Wage Calculator", slug: "hourly-wage-calculator-utility", category: "Utility Calculators", isPro: false },
  { id: 40, name: "Work Hours Calculator", slug: "work-hours-calculator-utility", category: "Utility Calculators", isPro: false },
  { id: 41, name: "Pace Calculator", slug: "pace-calculator", category: "Utility Calculators", isPro: false },
  { id: 42, name: "Speed Calculator", slug: "speed-calculator", category: "Utility Calculators", isPro: false },
  { id: 43, name: "Distance Calculator", slug: "distance-calculator", category: "Utility Calculators", isPro: false },
  { id: 44, name: "Travel Time Calculator", slug: "travel-time-calculator", category: "Utility Calculators", isPro: false },
  { id: 45, name: "Fuel Consumption Calculator", slug: "fuel-consumption-calculator", category: "Utility Calculators", isPro: false },
  { id: 46, name: "Energy Consumption Calculator", slug: "energy-consumption-calculator", category: "Utility Calculators", isPro: false },
  { id: 47, name: "Power Calculator", slug: "power-calculator", category: "Utility Calculators", isPro: false },
  { id: 48, name: "BMR Calculator", slug: "bmr-calculator", category: "Utility Calculators", isPro: false },
  { id: 49, name: "Water Intake Calculator", slug: "water-intake-calculator", category: "Utility Calculators", isPro: false },
  { id: 50, name: "Body Fat Calculator", slug: "body-fat-calculator", category: "Utility Calculators", isPro: false },
  { id: 51, name: "Ideal Weight Calculator", slug: "ideal-weight-calculator", category: "Utility Calculators", isPro: false },
  { id: 52, name: "Mortgage Calculator", slug: "mortgage-calculator-utility", category: "Utility Calculators", isPro: false },
  { id: 53, name: "Loan Calculator", slug: "loan-calculator-utility", category: "Utility Calculators", isPro: false },
  { id: 54, name: "Compound Interest Calculator", slug: "compound-interest-calculator-utility", category: "Utility Calculators", isPro: false },
  { id: 55, name: "Simple Interest Calculator", slug: "simple-interest-calculator-utility", category: "Utility Calculators", isPro: false },
  { id: 56, name: "ROI Calculator", slug: "roi-calculator-utility", category: "Utility Calculators", isPro: false },
  { id: 57, name: "Break-Even Calculator", slug: "break-even-calculator-utility", category: "Utility Calculators", isPro: false },
  { id: 58, name: "Inflation Calculator", slug: "inflation-calculator", category: "Utility Calculators", isPro: false },
  { id: 59, name: "Temperature Converter", slug: "temperature-converter", category: "Utility Calculators", isPro: false },
  { id: 60, name: "Data Storage Converter", slug: "data-storage-converter", category: "Utility Calculators", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Scientific Calculator", slug: "scientific-calculator", category: "Utility Calculators", isPro: true },
  { id: 62, name: "Statistics Calculator", slug: "statistics-calculator", category: "Utility Calculators", isPro: true },
  { id: 63, name: "Graphing Calculator", slug: "graphing-calculator", category: "Utility Calculators", isPro: true },
  { id: 64, name: "Standard Deviation Calculator", slug: "standard-deviation-calculator", category: "Utility Calculators", isPro: true },
  { id: 65, name: "Variance Calculator", slug: "variance-calculator", category: "Utility Calculators", isPro: true },
  { id: 66, name: "Z-Score Calculator", slug: "z-score-calculator", category: "Utility Calculators", isPro: true },
  { id: 67, name: "Probability Calculator", slug: "probability-calculator", category: "Utility Calculators", isPro: true },
  { id: 68, name: "Permutation Calculator", slug: "permutation-calculator", category: "Utility Calculators", isPro: true },
  { id: 69, name: "Combination Calculator", slug: "combination-calculator", category: "Utility Calculators", isPro: true },
  { id: 70, name: "Confidence Interval Calculator", slug: "confidence-interval-calculator", category: "Utility Calculators", isPro: true },
  { id: 71, name: "Linear Regression Calculator", slug: "linear-regression-calculator", category: "Utility Calculators", isPro: true },
  { id: 72, name: "Quadratic Equation Calculator", slug: "quadratic-equation-calculator", category: "Utility Calculators", isPro: true },
  { id: 73, name: "Equation Solver", slug: "equation-solver", category: "Utility Calculators", isPro: true },
  { id: 74, name: "Matrix Calculator", slug: "matrix-calculator", category: "Utility Calculators", isPro: true },
  { id: 75, name: "Determinant Calculator", slug: "determinant-calculator", category: "Utility Calculators", isPro: true },
  { id: 76, name: "Vector Calculator", slug: "vector-calculator", category: "Utility Calculators", isPro: true },
  { id: 77, name: "Geometry Calculator", slug: "geometry-calculator", category: "Utility Calculators", isPro: true },
  { id: 78, name: "Triangle Calculator", slug: "triangle-calculator", category: "Utility Calculators", isPro: true },
  { id: 79, name: "Circle Calculator", slug: "circle-calculator", category: "Utility Calculators", isPro: true },
  { id: 80, name: "Area Calculator", slug: "area-calculator", category: "Utility Calculators", isPro: true },
  { id: 81, name: "Volume Calculator", slug: "volume-calculator", category: "Utility Calculators", isPro: true },
  { id: 82, name: "Surface Area Calculator", slug: "surface-area-calculator", category: "Utility Calculators", isPro: true },
  { id: 83, name: "Pythagorean Theorem Calculator", slug: "pythagorean-theorem-calculator", category: "Utility Calculators", isPro: true },
  { id: 84, name: "Mortgage Affordability Calculator", slug: "mortgage-affordability-calculator", category: "Utility Calculators", isPro: true },
  { id: 85, name: "Retirement Calculator", slug: "retirement-calculator-utility", category: "Utility Calculators", isPro: true },
  { id: 86, name: "Savings Goal Calculator", slug: "savings-goal-calculator-utility", category: "Utility Calculators", isPro: true },
  { id: 87, name: "Debt Payoff Calculator", slug: "debt-payoff-calculator-utility", category: "Utility Calculators", isPro: true },
  { id: 88, name: "Net Worth Calculator", slug: "net-worth-calculator-utility", category: "Utility Calculators", isPro: true },
  { id: 89, name: "FIRE Calculator", slug: "fire-calculator-utility", category: "Utility Calculators", isPro: true },
  { id: 90, name: "Carbon Footprint Calculator", slug: "carbon-footprint-calculator", category: "Utility Calculators", isPro: true },
  { id: 91, name: "Solar Savings Calculator", slug: "solar-savings-calculator", category: "Utility Calculators", isPro: true },
  { id: 92, name: "Electricity Bill Estimator", slug: "electricity-bill-estimator", category: "Utility Calculators", isPro: true },
  { id: 93, name: "Internet Data Usage Calculator", slug: "internet-data-usage-calculator", category: "Utility Calculators", isPro: true },
  { id: 94, name: "Bandwidth Calculator", slug: "bandwidth-calculator", category: "Utility Calculators", isPro: true },
  { id: 95, name: "Download Time Calculator", slug: "download-time-calculator", category: "Utility Calculators", isPro: true },
  { id: 96, name: "Screen Size Calculator", slug: "screen-size-calculator", category: "Utility Calculators", isPro: true },
  { id: 97, name: "Aspect Ratio Calculator", slug: "aspect-ratio-calculator", category: "Utility Calculators", isPro: true },
  { id: 98, name: "Resolution Calculator", slug: "resolution-calculator", category: "Utility Calculators", isPro: true },
  { id: 99, name: "Printing Cost Calculator", slug: "printing-cost-calculator", category: "Utility Calculators", isPro: true },
  { id: 100, name: "Universal Calculator Workspace", slug: "universal-calculator-workspace", category: "Utility Calculators", isPro: true },
];