export interface WebsiteTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const websiteToolsList: WebsiteTool[] = [
  // --- TOP 10 PRIORITY TOOLS ---
  { id: 1, name: "Website Speed Test", slug: "website-speed-test", category: "Website Tools", isPro: false },
  { id: 2, name: "Website SEO Checker", slug: "website-seo-checker", category: "Website Tools", isPro: false },
  { id: 3, name: "SSL Checker", slug: "ssl-checker", category: "Website Tools", isPro: false },
  { id: 4, name: "DNS Lookup", slug: "dns-lookup", category: "Website Tools", isPro: false },
  { id: 5, name: "Website Domain Checker", slug: "website-domain-checker", category: "Website Tools", isPro: false },
  { id: 6, name: "Broken Link Checker", slug: "broken-link-checker", category: "Website Tools", isPro: false },
  { id: 7, name: "QR Code Generator", slug: "qr-code-generator", category: "Website Tools", isPro: false },
  { id: 8, name: "JSON Formatter", slug: "json-formatter", category: "Website Tools", isPro: false },
  { id: 9, name: "HTML Formatter", slug: "html-formatter", category: "Website Tools", isPro: false },
  { id: 10, name: "Website Accessibility Checker", slug: "website-accessibility-checker", category: "Website Tools", isPro: false },

  // --- REMAINING CORE / HIGH-DEMAND (FREE TOOLS: 11-60) ---
  { id: 11, name: "Website Performance Checker", slug: "website-performance-checker", category: "Website Tools", isPro: false },
  { id: 12, name: "Website Uptime Checker", slug: "website-uptime-checker", category: "Website Tools", isPro: false },
  { id: 13, name: "Website Status Checker", slug: "website-status-checker", category: "Website Tools", isPro: false },
  { id: 14, name: "Website Security Checker", slug: "website-security-checker", category: "Website Tools", isPro: false },
  { id: 15, name: "Website Mobile-Friendly Checker", slug: "website-mobile-friendly-checker", category: "Website Tools", isPro: false },
  { id: 16, name: "Website Technology Checker", slug: "website-technology-checker", category: "Website Tools", isPro: false },
  { id: 17, name: "Website Hosting Checker", slug: "website-hosting-checker", category: "Website Tools", isPro: false },
  { id: 18, name: "Website IP Checker", slug: "website-ip-checker", category: "Website Tools", isPro: false },
  { id: 19, name: "Domain Availability Checker", slug: "domain-availability-checker", category: "Website Tools", isPro: false },
  { id: 20, name: "Domain Age Checker", slug: "domain-age-checker", category: "Website Tools", isPro: false },
  { id: 21, name: "Domain WHOIS Lookup", slug: "domain-whois-lookup", category: "Website Tools", isPro: false },
  { id: 22, name: "DNS Propagation Checker", slug: "dns-propagation-checker", category: "Website Tools", isPro: false },
  { id: 23, name: "SSL Certificate Checker", slug: "ssl-certificate-checker", category: "Website Tools", isPro: false },
  { id: 24, name: "SSL Expiry Checker", slug: "ssl-expiry-checker", category: "Website Tools", isPro: false },
  { id: 25, name: "HTTP Header Checker", slug: "http-header-checker", category: "Website Tools", isPro: false },
  { id: 26, name: "HTTP Status Code Checker", slug: "http-status-code-checker", category: "Website Tools", isPro: false },
  { id: 27, name: "Redirect Checker", slug: "redirect-checker", category: "Website Tools", isPro: false },
  { id: 28, name: "Redirect Chain Checker", slug: "redirect-chain-checker", category: "Website Tools", isPro: false },
  { id: 29, name: "Sitemap Checker", slug: "sitemap-checker", category: "Website Tools", isPro: false },
  { id: 30, name: "Robots.txt Checker", slug: "robots-txt-checker", category: "Website Tools", isPro: false },
  { id: 31, name: "Robots.txt Generator", slug: "robots-txt-generator", category: "Website Tools", isPro: false },
  { id: 32, name: "Favicon Generator", slug: "favicon-generator", category: "Website Tools", isPro: false },
  { id: 33, name: "Web Manifest Generator", slug: "web-manifest-generator", category: "Website Tools", isPro: false },
  { id: 34, name: "HTML Minifier", slug: "html-minifier", category: "Website Tools", isPro: false },
  { id: 35, name: "CSS Formatter", slug: "css-formatter", category: "Website Tools", isPro: false },
  { id: 36, name: "CSS Minifier", slug: "css-minifier", category: "Website Tools", isPro: false },
  { id: 37, name: "JavaScript Minifier", slug: "javascript-minifier", category: "Website Tools", isPro: false },
  { id: 38, name: "JSON Validator", slug: "json-validator", category: "Website Tools", isPro: false },
  { id: 39, name: "XML Formatter", slug: "xml-formatter", category: "Website Tools", isPro: false },
  { id: 40, name: "XML Validator", slug: "xml-validator", category: "Website Tools", isPro: false },
  { id: 41, name: "YAML Validator", slug: "yaml-validator", category: "Website Tools", isPro: false },
  { id: 42, name: "URL Encoder", slug: "url-encoder", category: "Website Tools", isPro: false },
  { id: 43, name: "URL Decoder", slug: "url-decoder", category: "Website Tools", isPro: false },
  { id: 44, name: "HTML Entity Encoder", slug: "html-entity-encoder", category: "Website Tools", isPro: false },
  { id: 45, name: "HTML Entity Decoder", slug: "html-entity-decoder", category: "Website Tools", isPro: false },
  { id: 46, name: "Barcode Generator", slug: "barcode-generator", category: "Website Tools", isPro: false },
  { id: 47, name: "Color Picker", slug: "color-picker", category: "Website Tools", isPro: false },
  { id: 48, name: "Color Converter", slug: "color-converter", category: "Website Tools", isPro: false },
  { id: 49, name: "Gradient Generator", slug: "gradient-generator", category: "Website Tools", isPro: false },
  { id: 50, name: "CSS Gradient Generator", slug: "css-gradient-generator", category: "Website Tools", isPro: false },
  { id: 51, name: "Box Shadow Generator", slug: "box-shadow-generator", category: "Website Tools", isPro: false },
  { id: 52, name: "CSS Border Radius Generator", slug: "css-border-radius-generator", category: "Website Tools", isPro: false },
  { id: 53, name: "CSS Button Generator", slug: "css-button-generator", category: "Website Tools", isPro: false },
  { id: 54, name: "CSS Glassmorphism Generator", slug: "css-glassmorphism-generator", category: "Website Tools", isPro: false },
  { id: 55, name: "CSS Animation Generator", slug: "css-animation-generator", category: "Website Tools", isPro: false },
  { id: 56, name: "CSS Flexbox Generator", slug: "css-flexbox-generator", category: "Website Tools", isPro: false },
  { id: 57, name: "CSS Grid Generator", slug: "css-grid-generator", category: "Website Tools", isPro: false },
  { id: 58, name: "Responsive Breakpoint Generator", slug: "responsive-breakpoint-generator", category: "Website Tools", isPro: false },
  { id: 59, name: "Lorem Ipsum Generator", slug: "lorem-ipsum-generator", category: "Website Tools", isPro: false },
  { id: 60, name: "Placeholder Image Generator", slug: "placeholder-image-generator", category: "Website Tools", isPro: false },

  // --- PRO LEVEL (PAID TOOLS: 61-100) ---
  { id: 61, name: "Website Architecture Analyzer", slug: "website-architecture-analyzer", category: "Website Tools", isPro: true },
  { id: 62, name: "Website Crawl Tester", slug: "website-crawl-tester", category: "Website Tools", isPro: true },
  { id: 63, name: "Website Crawl Simulator", slug: "website-crawl-simulator", category: "Website Tools", isPro: true },
  { id: 64, name: "Website Indexability Checker", slug: "website-indexability-checker", category: "Website Tools", isPro: true },
  { id: 65, name: "Website Canonical Checker", slug: "website-canonical-checker", category: "Website Tools", isPro: true },
  { id: 66, name: "Website Hreflang Checker", slug: "website-hreflang-checker", category: "Website Tools", isPro: true },
  { id: 67, name: "Website Structured Data Tester", slug: "website-structured-data-tester", category: "Website Tools", isPro: true },
  { id: 68, name: "Website Open Graph Tester", slug: "website-open-graph-tester", category: "Website Tools", isPro: true },
  { id: 69, name: "Website Social Preview Generator", slug: "website-social-preview-generator", category: "Website Tools", isPro: true },
  { id: 70, name: "Website Core Web Vitals Analyzer", slug: "website-core-web-vitals-analyzer", category: "Website Tools", isPro: true },
  { id: 71, name: "Website Lighthouse Report Analyzer", slug: "website-lighthouse-report-analyzer", category: "Website Tools", isPro: true },
  { id: 72, name: "Website JavaScript Error Checker", slug: "website-javascript-error-checker", category: "Website Tools", isPro: true },
  { id: 73, name: "Website Console Error Analyzer", slug: "website-console-error-analyzer", category: "Website Tools", isPro: true },
  { id: 74, name: "Website Resource Analyzer", slug: "website-resource-analyzer", category: "Website Tools", isPro: true },
  { id: 75, name: "Website Asset Size Analyzer", slug: "website-asset-size-analyzer", category: "Website Tools", isPro: true },
  { id: 76, name: "Website Image Optimization Analyzer", slug: "website-image-optimization-analyzer", category: "Website Tools", isPro: true },
  { id: 77, name: "Website Font Performance Analyzer", slug: "website-font-performance-analyzer", category: "Website Tools", isPro: true },
  { id: 78, name: "Website Third-Party Script Analyzer", slug: "website-third-party-script-analyzer", category: "Website Tools", isPro: true },
  { id: 79, name: "Website Cookie Checker", slug: "website-cookie-checker", category: "Website Tools", isPro: true },
  { id: 80, name: "Website Privacy Compliance Checker", slug: "website-privacy-compliance-checker", category: "Website Tools", isPro: true },
  { id: 81, name: "Website Cookie Policy Generator", slug: "website-cookie-policy-generator", category: "Website Tools", isPro: true },
  { id: 82, name: "Website Privacy Policy Generator", slug: "website-privacy-policy-generator", category: "Website Tools", isPro: true },
  { id: 83, name: "Website Terms Generator", slug: "website-terms-generator", category: "Website Tools", isPro: true },
  { id: 84, name: "Website Disclaimer Generator", slug: "website-disclaimer-generator", category: "Website Tools", isPro: true },
  { id: 85, name: "Website Accessibility Statement Generator", slug: "website-accessibility-statement-generator", category: "Website Tools", isPro: true },
  { id: 86, name: "Website Security Headers Analyzer", slug: "website-security-headers-analyzer", category: "Website Tools", isPro: true },
  { id: 87, name: "CSP Header Generator", slug: "csp-header-generator", category: "Website Tools", isPro: true },
  { id: 88, name: "Security.txt Generator", slug: "security-txt-generator", category: "Website Tools", isPro: true },
  { id: 89, name: "Web App Manifest Generator", slug: "web-app-manifest-generator", category: "Website Tools", isPro: true },
  { id: 90, name: "PWA Audit Tool", slug: "pwa-audit-tool", category: "Website Tools", isPro: true },
  { id: 91, name: "Website Carbon Footprint Calculator", slug: "website-carbon-footprint-calculator", category: "Website Tools", isPro: true },
  { id: 92, name: "Website Page Weight Analyzer", slug: "website-page-weight-analyzer", category: "Website Tools", isPro: true },
  { id: 93, name: "Website Technology Stack Analyzer", slug: "website-technology-stack-analyzer", category: "Website Tools", isPro: true },
  { id: 94, name: "Website Migration Checklist Generator", slug: "website-migration-checklist-generator", category: "Website Tools", isPro: true },
  { id: 95, name: "Website Redirect Map Generator", slug: "website-redirect-map-generator", category: "Website Tools", isPro: true },
  { id: 96, name: "Website Launch Checklist", slug: "website-launch-checklist", category: "Website Tools", isPro: true },
  { id: 97, name: "Website QA Checklist Generator", slug: "website-qa-checklist-generator", category: "Website Tools", isPro: true },
  { id: 98, name: "Website Maintenance Checklist", slug: "website-maintenance-checklist", category: "Website Tools", isPro: true },
  { id: 99, name: "Website Cost Calculator", slug: "website-cost-calculator", category: "Website Tools", isPro: true },
  { id: 100, name: "Website ROI Calculator", slug: "website-roi-calculator", category: "Website Tools", isPro: true },
];