export interface YouTubeTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const youtubeToolsList: YouTubeTool[] = [
  // --- TOP 10 PRIORITY TOOLS ---
  { id: 1, name: "YouTube Title Generator", slug: "youtube-title-generator", category: "YouTube Tools", isPro: false },
  { id: 2, name: "YouTube Thumbnail Downloader", slug: "youtube-thumbnail-downloader", category: "YouTube Tools", isPro: false },
  { id: 3, name: "YouTube Script Generator", slug: "youtube-script-generator", category: "YouTube Tools", isPro: false },
  { id: 4, name: "YouTube SEO Analyzer", slug: "youtube-seo-analyzer", category: "YouTube Tools", isPro: false },
  { id: 5, name: "YouTube Revenue Calculator", slug: "youtube-revenue-calculator", category: "YouTube Tools", isPro: false },
  { id: 6, name: "YouTube CPM Calculator", slug: "youtube-cpm-calculator", category: "YouTube Tools", isPro: false },
  { id: 7, name: "YouTube RPM Calculator", slug: "youtube-rpm-calculator", category: "YouTube Tools", isPro: false },
  { id: 8, name: "YouTube Keyword Generator", slug: "youtube-keyword-generator", category: "YouTube Tools", isPro: false },
  { id: 9, name: "YouTube Channel Audit", slug: "youtube-channel-audit", category: "YouTube Tools", isPro: false },
  { id: 10, name: "YouTube Video Idea Generator", slug: "youtube-video-idea-generator", category: "YouTube Tools", isPro: false },

  // --- REMAINING CORE / HIGH-DEMAND (FREE TOOLS: 11-60) ---
  { id: 11, name: "YouTube Description Generator", slug: "youtube-description-generator", category: "YouTube Tools", isPro: false },
  { id: 12, name: "YouTube Tag Generator", slug: "youtube-tag-generator", category: "YouTube Tools", isPro: false },
  { id: 13, name: "YouTube Hashtag Generator", slug: "youtube-hashtag-generator", category: "YouTube Tools", isPro: false },
  { id: 14, name: "YouTube Hook Generator", slug: "youtube-hook-generator", category: "YouTube Tools", isPro: false },
  { id: 15, name: "YouTube Intro Generator", slug: "youtube-intro-generator", category: "YouTube Tools", isPro: false },
  { id: 16, name: "YouTube Outro Generator", slug: "youtube-outro-generator", category: "YouTube Tools", isPro: false },
  { id: 17, name: "YouTube Thumbnail Idea Generator", slug: "youtube-thumbnail-idea-generator", category: "YouTube Tools", isPro: false },
  { id: 18, name: "YouTube Thumbnail Text Generator", slug: "youtube-thumbnail-text-generator", category: "YouTube Tools", isPro: false },
  { id: 19, name: "YouTube Title Analyzer", slug: "youtube-title-analyzer", category: "YouTube Tools", isPro: false },
  { id: 20, name: "YouTube Description Analyzer", slug: "youtube-description-analyzer", category: "YouTube Tools", isPro: false },
  { id: 21, name: "YouTube Tag Analyzer", slug: "youtube-tag-analyzer", category: "YouTube Tools", isPro: false },
  { id: 22, name: "YouTube Keyword Analyzer", slug: "youtube-keyword-analyzer", category: "YouTube Tools", isPro: false },
  { id: 23, name: "YouTube Channel Name Generator", slug: "youtube-channel-name-generator", category: "YouTube Tools", isPro: false },
  { id: 24, name: "YouTube Channel Description Generator", slug: "youtube-channel-description-generator", category: "YouTube Tools", isPro: false },
  { id: 25, name: "YouTube Handle Generator", slug: "youtube-handle-generator", category: "YouTube Tools", isPro: false },
  { id: 26, name: "YouTube Bio Generator", slug: "youtube-bio-generator", category: "YouTube Tools", isPro: false },
  { id: 27, name: "YouTube Playlist Name Generator", slug: "youtube-playlist-name-generator", category: "YouTube Tools", isPro: false },
  { id: 28, name: "YouTube Playlist Description Generator", slug: "youtube-playlist-description-generator", category: "YouTube Tools", isPro: false },
  { id: 29, name: "YouTube Comment Generator", slug: "youtube-comment-generator", category: "YouTube Tools", isPro: false },
  { id: 30, name: "YouTube Comment Reply Generator", slug: "youtube-comment-reply-generator", category: "YouTube Tools", isPro: false },
  { id: 31, name: "YouTube Community Post Generator", slug: "youtube-community-post-generator", category: "YouTube Tools", isPro: false },
  { id: 32, name: "YouTube Shorts Idea Generator", slug: "youtube-shorts-idea-generator", category: "YouTube Tools", isPro: false },
  { id: 33, name: "YouTube Shorts Script Generator", slug: "youtube-shorts-script-generator", category: "YouTube Tools", isPro: false },
  { id: 34, name: "YouTube Shorts Title Generator", slug: "youtube-shorts-title-generator", category: "YouTube Tools", isPro: false },
  { id: 35, name: "YouTube Shorts Hashtag Generator", slug: "youtube-shorts-hashtag-generator", category: "YouTube Tools", isPro: false },
  { id: 36, name: "YouTube Video Outline Generator", slug: "youtube-video-outline-generator", category: "YouTube Tools", isPro: false },
  { id: 37, name: "YouTube Storyboard Generator", slug: "youtube-storyboard-generator", category: "YouTube Tools", isPro: false },
  { id: 38, name: "YouTube Content Calendar", slug: "youtube-content-calendar", category: "YouTube Tools", isPro: false },
  { id: 39, name: "YouTube Upload Planner", slug: "youtube-upload-planner", category: "YouTube Tools", isPro: false },
  { id: 40, name: "YouTube Video Checklist", slug: "youtube-video-checklist", category: "YouTube Tools", isPro: false },
  { id: 41, name: "YouTube Transcript Extractor", slug: "youtube-transcript-extractor", category: "YouTube Tools", isPro: false },
  { id: 42, name: "YouTube Transcript Summarizer", slug: "youtube-transcript-summarizer", category: "YouTube Tools", isPro: false },
  { id: 43, name: "YouTube Video Summarizer", slug: "youtube-video-summarizer", category: "YouTube Tools", isPro: false },
  { id: 44, name: "YouTube Chapter Generator", slug: "youtube-chapter-generator", category: "YouTube Tools", isPro: false },
  { id: 45, name: "YouTube Timestamp Generator", slug: "youtube-timestamp-generator", category: "YouTube Tools", isPro: false },
  { id: 46, name: "YouTube Subtitle Formatter", slug: "youtube-subtitle-formatter", category: "YouTube Tools", isPro: false },
  { id: 47, name: "YouTube Subtitle Converter", slug: "youtube-subtitle-converter", category: "YouTube Tools", isPro: false },
  { id: 48, name: "YouTube SRT Generator", slug: "youtube-srt-generator", category: "YouTube Tools", isPro: false },
  { id: 49, name: "YouTube SRT Validator", slug: "youtube-srt-validator", category: "YouTube Tools", isPro: false },
  { id: 50, name: "YouTube Channel Banner Generator", slug: "youtube-channel-banner-generator", category: "YouTube Tools", isPro: false },
  { id: 51, name: "YouTube Profile Picture Generator", slug: "youtube-profile-picture-generator", category: "YouTube Tools", isPro: false },
  { id: 52, name: "YouTube End Screen Planner", slug: "youtube-end-screen-planner", category: "YouTube Tools", isPro: false },
  { id: 53, name: "YouTube Card Planner", slug: "youtube-card-planner", category: "YouTube Tools", isPro: false },
  { id: 54, name: "YouTube Description Formatter", slug: "youtube-description-formatter", category: "YouTube Tools", isPro: false },
  { id: 55, name: "YouTube Earnings Estimator", slug: "youtube-earnings-estimator", category: "YouTube Tools", isPro: false },
  { id: 56, name: "YouTube Watch Time Calculator", slug: "youtube-watch-time-calculator", category: "YouTube Tools", isPro: false },
  { id: 57, name: "YouTube Engagement Rate Calculator", slug: "youtube-engagement-rate-calculator", category: "YouTube Tools", isPro: false },
  { id: 58, name: "YouTube CTR Calculator", slug: "youtube-ctr-calculator", category: "YouTube Tools", isPro: false },
  { id: 59, name: "YouTube Subscriber Growth Calculator", slug: "youtube-subscriber-growth-calculator", category: "YouTube Tools", isPro: false },
  { id: 60, name: "YouTube Views-to-Earnings Calculator", slug: "youtube-views-to-earnings-calculator", category: "YouTube Tools", isPro: false },

  // --- PRO LEVEL (PAID TOOLS: 61-100) ---
  { id: 61, name: "YouTube Competitor Analyzer", slug: "youtube-competitor-analyzer", category: "YouTube Tools", isPro: true },
  { id: 62, name: "YouTube Competitor Channel Finder", slug: "youtube-competitor-channel-finder", category: "YouTube Tools", isPro: true },
  { id: 63, name: "YouTube Competitor Video Analyzer", slug: "youtube-competitor-video-analyzer", category: "YouTube Tools", isPro: true },
  { id: 64, name: "YouTube Keyword Gap Analyzer", slug: "youtube-keyword-gap-analyzer", category: "YouTube Tools", isPro: true },
  { id: 65, name: "YouTube Content Gap Analyzer", slug: "youtube-content-gap-analyzer", category: "YouTube Tools", isPro: true },
  { id: 66, name: "YouTube Topic Research Tool", slug: "youtube-topic-research-tool", category: "YouTube Tools", isPro: true },
  { id: 67, name: "YouTube Trend Research Tool", slug: "youtube-trend-research-tool", category: "YouTube Tools", isPro: true },
  { id: 68, name: "YouTube Search Intent Analyzer", slug: "youtube-search-intent-analyzer", category: "YouTube Tools", isPro: true },
  { id: 69, name: "YouTube SERP Analyzer", slug: "youtube-serp-analyzer", category: "YouTube Tools", isPro: true },
  { id: 70, name: "YouTube Ranking Opportunity Finder", slug: "youtube-ranking-opportunity-finder", category: "YouTube Tools", isPro: true },
  { id: 71, name: "YouTube Viral Topic Analyzer", slug: "youtube-viral-topic-analyzer", category: "YouTube Tools", isPro: true },
  { id: 72, name: "YouTube Viral Video Analyzer", slug: "youtube-viral-video-analyzer", category: "YouTube Tools", isPro: true },
  { id: 73, name: "YouTube Thumbnail CTR Analyzer", slug: "youtube-thumbnail-ctr-analyzer", category: "YouTube Tools", isPro: true },
  { id: 74, name: "YouTube Thumbnail A/B Testing Planner", slug: "youtube-thumbnail-ab-testing-planner", category: "YouTube Tools", isPro: true },
  { id: 75, name: "YouTube Title A/B Testing Tool", slug: "youtube-title-ab-testing-tool", category: "YouTube Tools", isPro: true },
  { id: 76, name: "YouTube Hook Analyzer", slug: "youtube-hook-analyzer", category: "YouTube Tools", isPro: true },
  { id: 77, name: "YouTube Retention Analyzer", slug: "youtube-retention-analyzer", category: "YouTube Tools", isPro: true },
  { id: 78, name: "YouTube Audience Retention Calculator", slug: "youtube-audience-retention-calculator", category: "YouTube Tools", isPro: true },
  { id: 79, name: "YouTube Engagement Analyzer", slug: "youtube-engagement-analyzer", category: "YouTube Tools", isPro: true },
  { id: 80, name: "YouTube Channel Growth Analyzer", slug: "youtube-channel-growth-analyzer", category: "YouTube Tools", isPro: true },
  { id: 81, name: "YouTube Upload Frequency Analyzer", slug: "youtube-upload-frequency-analyzer", category: "YouTube Tools", isPro: true },
  { id: 82, name: "YouTube Best Posting Time Analyzer", slug: "youtube-best-posting-time-analyzer", category: "YouTube Tools", isPro: true },
  { id: 83, name: "YouTube Content Pillar Planner", slug: "youtube-content-pillar-planner", category: "YouTube Tools", isPro: true },
  { id: 84, name: "YouTube Niche Research Tool", slug: "youtube-niche-research-tool", category: "YouTube Tools", isPro: true },
  { id: 85, name: "YouTube Niche Profitability Calculator", slug: "youtube-niche-profitability-calculator", category: "YouTube Tools", isPro: true },
  { id: 86, name: "YouTube CPM Niche Analyzer", slug: "youtube-cpm-niche-analyzer", category: "YouTube Tools", isPro: true },
  { id: 87, name: "YouTube RPM Niche Analyzer", slug: "youtube-rpm-niche-analyzer", category: "YouTube Tools", isPro: true },
  { id: 88, name: "YouTube Sponsorship Rate Calculator", slug: "youtube-sponsorship-rate-calculator", category: "YouTube Tools", isPro: true },
  { id: 89, name: "YouTube Brand Deal Calculator", slug: "youtube-brand-deal-calculator", category: "YouTube Tools", isPro: true },
  { id: 90, name: "YouTube Affiliate Revenue Calculator", slug: "youtube-affiliate-revenue-calculator", category: "YouTube Tools", isPro: true },
  { id: 91, name: "YouTube Content ROI Calculator", slug: "youtube-content-roi-calculator", category: "YouTube Tools", isPro: true },
  { id: 92, name: "YouTube Production Cost Calculator", slug: "youtube-production-cost-calculator", category: "YouTube Tools", isPro: true },
  { id: 93, name: "YouTube Video ROI Calculator", slug: "youtube-video-roi-calculator", category: "YouTube Tools", isPro: true },
  { id: 94, name: "YouTube Multi-Channel Planner", slug: "youtube-multi-channel-planner", category: "YouTube Tools", isPro: true },
  { id: 95, name: "YouTube Faceless Channel Planner", slug: "youtube-faceless-channel-planner", category: "YouTube Tools", isPro: true },
  { id: 96, name: "YouTube Channel Monetization Planner", slug: "youtube-channel-monetization-planner", category: "YouTube Tools", isPro: true },
  { id: 97, name: "YouTube Monetization Eligibility Tracker", slug: "youtube-monetization-eligibility-tracker", category: "YouTube Tools", isPro: true },
  { id: 98, name: "YouTube Analytics Report Generator", slug: "youtube-analytics-report-generator", category: "YouTube Tools", isPro: true },
  { id: 99, name: "YouTube Performance Forecasting Tool", slug: "youtube-performance-forecasting-tool", category: "YouTube Tools", isPro: true },
  { id: 100, name: "YouTube Content Strategy Dashboard", slug: "youtube-content-strategy-dashboard", category: "YouTube Tools", isPro: true },
];