export interface AIAutomationTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const aiAutomationToolsList: AIAutomationTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-15) ---
  { id: 1, name: "AI Workflow Generator", slug: "ai-workflow-generator", category: "AI Automation Tools", isPro: false },
  { id: 2, name: "AI Task Automation Builder", slug: "ai-task-automation-builder", category: "AI Automation Tools", isPro: false },
  { id: 3, name: "AI Document Workflow Builder", slug: "ai-document-workflow-builder", category: "AI Automation Tools", isPro: false },
  { id: 4, name: "AI Email Workflow Builder", slug: "ai-email-workflow-builder", category: "AI Automation Tools", isPro: false },
  { id: 5, name: "AI Data Processing Workflow", slug: "ai-data-processing-workflow", category: "AI Automation Tools", isPro: false },
  { id: 6, name: "AI Research Workflow", slug: "ai-research-workflow", category: "AI Automation Tools", isPro: false },
  { id: 7, name: "AI Social Media Workflow", slug: "ai-social-media-workflow", category: "AI Automation Tools", isPro: false },
  { id: 8, name: "AI Marketing Workflow", slug: "ai-marketing-workflow", category: "AI Automation Tools", isPro: false },
  { id: 9, name: "AI Lead Processing Workflow", slug: "ai-lead-processing-workflow", category: "AI Automation Tools", isPro: false },
  { id: 10, name: "AI PDF Processing Workflow", slug: "ai-pdf-processing-workflow", category: "AI Automation Tools", isPro: false },
  { id: 11, name: "AI Spreadsheet Workflow", slug: "ai-spreadsheet-workflow", category: "AI Automation Tools", isPro: false },
  { id: 12, name: "AI Chatbot Builder", slug: "ai-chatbot-builder", category: "AI Automation Tools", isPro: false },
  { id: 13, name: "AI Customer Support Bot", slug: "ai-customer-support-bot", category: "AI Automation Tools", isPro: false },
  { id: 14, name: "AI Knowledge Base Builder", slug: "ai-knowledge-base-builder", category: "AI Automation Tools", isPro: false },
  { id: 15, name: "AI Research Agent Builder", slug: "ai-research-agent-builder", category: "AI Automation Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (16-60) ---
  { id: 16, name: "AI Prompt Workflow Builder", slug: "ai-prompt-workflow-builder", category: "AI Automation Tools", isPro: false },
  { id: 17, name: "AI Content Workflow Builder", slug: "ai-content-workflow-builder", category: "AI Automation Tools", isPro: false },
  { id: 18, name: "AI Sales Workflow", slug: "ai-sales-workflow", category: "AI Automation Tools", isPro: false },
  { id: 19, name: "AI Customer Support Workflow", slug: "ai-customer-support-workflow", category: "AI Automation Tools", isPro: false },
  { id: 20, name: "AI Meeting Workflow", slug: "ai-meeting-workflow", category: "AI Automation Tools", isPro: false },
  { id: 21, name: "AI Reporting Workflow", slug: "ai-reporting-workflow", category: "AI Automation Tools", isPro: false },
  { id: 22, name: "AI Translation Workflow", slug: "ai-translation-workflow", category: "AI Automation Tools", isPro: false },
  { id: 23, name: "AI Summarization Workflow", slug: "ai-summarization-workflow", category: "AI Automation Tools", isPro: false },
  { id: 24, name: "AI Classification Workflow", slug: "ai-classification-workflow", category: "AI Automation Tools", isPro: false },
  { id: 25, name: "AI Extraction Workflow", slug: "ai-extraction-workflow", category: "AI Automation Tools", isPro: false },
  { id: 26, name: "AI Data Cleaning Workflow", slug: "ai-data-cleaning-workflow", category: "AI Automation Tools", isPro: false },
  { id: 27, name: "AI Form Processing Workflow", slug: "ai-form-processing-workflow", category: "AI Automation Tools", isPro: false },
  { id: 28, name: "AI Image Processing Workflow", slug: "ai-image-processing-workflow", category: "AI Automation Tools", isPro: false },
  { id: 29, name: "AI Audio Processing Workflow", slug: "ai-audio-processing-workflow", category: "AI Automation Tools", isPro: false },
  { id: 30, name: "AI Video Processing Workflow", slug: "ai-video-processing-workflow", category: "AI Automation Tools", isPro: false },
  { id: 31, name: "AI Database Workflow", slug: "ai-database-workflow", category: "AI Automation Tools", isPro: false },
  { id: 32, name: "AI API Workflow", slug: "ai-api-workflow", category: "AI Automation Tools", isPro: false },
  { id: 33, name: "AI Webhook Workflow", slug: "ai-webhook-workflow", category: "AI Automation Tools", isPro: false },
  { id: 34, name: "AI Notification Workflow", slug: "ai-notification-workflow", category: "AI Automation Tools", isPro: false },
  { id: 35, name: "AI Approval Workflow", slug: "ai-approval-workflow", category: "AI Automation Tools", isPro: false },
  { id: 36, name: "AI Content Repurposing Workflow", slug: "ai-content-repurposing-workflow", category: "AI Automation Tools", isPro: false },
  { id: 37, name: "AI Blog Publishing Workflow", slug: "ai-blog-publishing-workflow", category: "AI Automation Tools", isPro: false },
  { id: 38, name: "AI Social Publishing Workflow", slug: "ai-social-publishing-workflow", category: "AI Automation Tools", isPro: false },
  { id: 39, name: "AI Newsletter Workflow", slug: "ai-newsletter-workflow", category: "AI Automation Tools", isPro: false },
  { id: 40, name: "AI Lead Nurturing Workflow", slug: "ai-lead-nurturing-workflow", category: "AI Automation Tools", isPro: false },
  { id: 41, name: "AI Customer Onboarding Workflow", slug: "ai-customer-onboarding-workflow", category: "AI Automation Tools", isPro: false },
  { id: 42, name: "AI Employee Onboarding Workflow", slug: "ai-employee-onboarding-workflow", category: "AI Automation Tools", isPro: false },
  { id: 43, name: "AI Resume Screening Workflow", slug: "ai-resume-screening-workflow", category: "AI Automation Tools", isPro: false },
  { id: 44, name: "AI Candidate Ranking Workflow", slug: "ai-candidate-ranking-workflow", category: "AI Automation Tools", isPro: false },
  { id: 45, name: "AI Invoice Processing Workflow", slug: "ai-invoice-processing-workflow", category: "AI Automation Tools", isPro: false },
  { id: 46, name: "AI Receipt Processing Workflow", slug: "ai-receipt-processing-workflow", category: "AI Automation Tools", isPro: false },
  { id: 47, name: "AI Expense Processing Workflow", slug: "ai-expense-processing-workflow", category: "AI Automation Tools", isPro: false },
  { id: 48, name: "AI Contract Processing Workflow", slug: "ai-contract-processing-workflow", category: "AI Automation Tools", isPro: false },
  { id: 49, name: "AI Compliance Workflow", slug: "ai-compliance-workflow", category: "AI Automation Tools", isPro: false },
  { id: 50, name: "AI FAQ Automation", slug: "ai-faq-automation", category: "AI Automation Tools", isPro: false },
  { id: 51, name: "AI Website Assistant Builder", slug: "ai-website-assistant-builder", category: "AI Automation Tools", isPro: false },
  { id: 52, name: "AI Internal Assistant Builder", slug: "ai-internal-assistant-builder", category: "AI Automation Tools", isPro: false },
  { id: 53, name: "AI Data Agent Builder", slug: "ai-data-agent-builder", category: "AI Automation Tools", isPro: false },
  { id: 54, name: "AI Reporting Agent Builder", slug: "ai-reporting-agent-builder", category: "AI Automation Tools", isPro: false },
  { id: 55, name: "AI Monitoring Agent Builder", slug: "ai-monitoring-agent-builder", category: "AI Automation Tools", isPro: false },
  { id: 56, name: "AI Notification Agent Builder", slug: "ai-notification-agent-builder", category: "AI Automation Tools", isPro: false },
  { id: 57, name: "AI Scheduled Task Agent", slug: "ai-scheduled-task-agent", category: "AI Automation Tools", isPro: false },
  { id: 58, name: "AI Email Agent", slug: "ai-email-agent", category: "AI Automation Tools", isPro: false },
  { id: 59, name: "AI Document Agent", slug: "ai-document-agent", category: "AI Automation Tools", isPro: false },
  { id: 60, name: "AI Workflow Template Library", slug: "ai-workflow-template-library", category: "AI Automation Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Multi-Agent Workflow Builder", slug: "multi-agent-workflow-builder", category: "AI Automation Tools", isPro: true },
  { id: 62, name: "AI Agent Orchestrator", slug: "ai-agent-orchestrator", category: "AI Automation Tools", isPro: true },
  { id: 63, name: "AI Workflow Scheduler", slug: "ai-workflow-scheduler", category: "AI Automation Tools", isPro: true },
  { id: 64, name: "AI Workflow Analytics", slug: "ai-workflow-analytics", category: "AI Automation Tools", isPro: true },
  { id: 65, name: "Enterprise AI Automation Workspace", slug: "enterprise-ai-automation-workspace", category: "AI Automation Tools", isPro: true },
  { id: 66, name: "Autonomous Research Agent", slug: "autonomous-research-agent", category: "AI Automation Tools", isPro: true },
  { id: 67, name: "Autonomous Data Analyst", slug: "autonomous-data-analyst", category: "AI Automation Tools", isPro: true },
  { id: 68, name: "Autonomous Reporting Agent", slug: "autonomous-reporting-agent", category: "AI Automation Tools", isPro: true },
  { id: 69, name: "Autonomous Customer Support Agent", slug: "autonomous-customer-support-agent", category: "AI Automation Tools", isPro: true },
  { id: 70, name: "Autonomous Sales Agent", slug: "autonomous-sales-agent", category: "AI Automation Tools", isPro: true },
  { id: 71, name: "Autonomous Marketing Agent", slug: "autonomous-marketing-agent", category: "AI Automation Tools", isPro: true },
  { id: 72, name: "Autonomous Recruiting Agent", slug: "autonomous-recruiting-agent", category: "AI Automation Tools", isPro: true },
  { id: 73, name: "Autonomous Finance Agent", slug: "autonomous-finance-agent", category: "AI Automation Tools", isPro: true },
  { id: 74, name: "AI Decision Workflow Engine", slug: "ai-decision-workflow-engine", category: "AI Automation Tools", isPro: true },
  { id: 75, name: "Human-in-the-Loop Workflow", slug: "human-in-the-loop-workflow", category: "AI Automation Tools", isPro: true },
  { id: 76, name: "Conditional AI Workflow Engine", slug: "conditional-ai-workflow-engine", category: "AI Automation Tools", isPro: true },
  { id: 77, name: "Multi-Step AI Pipeline Builder", slug: "multi-step-ai-pipeline-builder", category: "AI Automation Tools", isPro: true },
  { id: 78, name: "AI Model Routing Engine", slug: "ai-model-routing-engine", category: "AI Automation Tools", isPro: true },
  { id: 79, name: "AI Cost Optimization Router", slug: "ai-cost-optimization-router", category: "AI Automation Tools", isPro: true },
  { id: 80, name: "AI Prompt Version Manager", slug: "ai-prompt-version-manager", category: "AI Automation Tools", isPro: true },
  { id: 81, name: "Prompt Testing Framework", slug: "prompt-testing-framework", category: "AI Automation Tools", isPro: true },
  { id: 82, name: "Prompt Evaluation Tool", slug: "prompt-evaluation-tool", category: "AI Automation Tools", isPro: true },
  { id: 83, name: "AI Output Quality Evaluator", slug: "ai-output-quality-evaluator", category: "AI Automation Tools", isPro: true },
  { id: 84, name: "AI Hallucination Detection Workflow", slug: "ai-hallucination-detection-workflow", category: "AI Automation Tools", isPro: true },
  { id: 85, name: "AI Guardrail Builder", slug: "ai-guardrail-builder", category: "AI Automation Tools", isPro: true },
  { id: 86, name: "AI Data Privacy Workflow", slug: "ai-data-privacy-workflow", category: "AI Automation Tools", isPro: true },
  { id: 87, name: "AI PII Redaction Pipeline", slug: "ai-pii-redaction-pipeline", category: "AI Automation Tools", isPro: true },
  { id: 88, name: "AI Approval & Review Engine", slug: "ai-approval-review-engine", category: "AI Automation Tools", isPro: true },
  { id: 89, name: "AI Workflow Monitoring", slug: "ai-workflow-monitoring", category: "AI Automation Tools", isPro: true },
  { id: 90, name: "AI Workflow Error Handler", slug: "ai-workflow-error-handler", category: "AI Automation Tools", isPro: true },
  { id: 91, name: "AI Workflow Retry Engine", slug: "ai-workflow-retry-engine", category: "AI Automation Tools", isPro: true },
  { id: 92, name: "AI Agent Memory Manager", slug: "ai-agent-memory-manager", category: "AI Automation Tools", isPro: true },
  { id: 93, name: "AI Knowledge Retrieval Builder", slug: "ai-knowledge-retrieval-builder", category: "AI Automation Tools", isPro: true },
  { id: 94, name: "RAG Workflow Builder", slug: "rag-workflow-builder", category: "AI Automation Tools", isPro: true },
  { id: 95, name: "Vector Search Workflow Builder", slug: "vector-search-workflow-builder", category: "AI Automation Tools", isPro: true },
  { id: 96, name: "AI API Gateway", slug: "ai-api-gateway", category: "AI Automation Tools", isPro: true },
  { id: 97, name: "AI Automation Cost Calculator", slug: "ai-automation-cost-calculator", category: "AI Automation Tools", isPro: true },
  { id: 98, name: "AI Agent ROI Calculator", slug: "ai-agent-roi-calculator", category: "AI Automation Tools", isPro: true },
  { id: 99, name: "AI Automation Marketplace", slug: "ai-automation-marketplace", category: "AI Automation Tools", isPro: true },
  { id: 100, name: "AI Automation Template Marketplace", slug: "ai-automation-template-marketplace", category: "AI Automation Tools", isPro: true },
];