export interface AnalyticsSaasTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const analyticsSaasToolsList: AnalyticsSaasTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "MRR Calculator", slug: "mrr-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 2, name: "ARR Calculator", slug: "arr-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 3, name: "Churn Rate Calculator", slug: "churn-rate-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 4, name: "Customer Acquisition Cost Calculator", slug: "cac-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 5, name: "Customer Lifetime Value Calculator", slug: "ltv-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 6, name: "LTV to CAC Calculator", slug: "ltv-to-cac-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 7, name: "SaaS Valuation Calculator", slug: "saas-valuation-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 8, name: "Burn Rate Calculator", slug: "burn-rate-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 9, name: "Runway Calculator", slug: "runway-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 10, name: "Conversion Rate Calculator", slug: "conversion-rate-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 11, name: "Retention Rate Calculator", slug: "retention-rate-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 12, name: "Net Revenue Retention Calculator", slug: "nrr-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 13, name: "Gross Margin Calculator", slug: "gross-margin-calculator-saas", category: "Analytics & SaaS Tools", isPro: false },
  { id: 14, name: "Rule of 40 Calculator", slug: "rule-of-40-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 15, name: "Pricing Calculator", slug: "saas-pricing-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 16, name: "Cohort Analysis Tool", slug: "cohort-analysis-tool", category: "Analytics & SaaS Tools", isPro: false },
  { id: 17, name: "Funnel Conversion Calculator", slug: "funnel-conversion-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 18, name: "KPI Calculator", slug: "kpi-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 19, name: "Average Revenue Per User Calculator", slug: "arpu-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 20, name: "SaaS Growth Calculator", slug: "saas-growth-calculator", category: "Analytics & SaaS Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "KPI Target Calculator", slug: "kpi-target-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 22, name: "KPI Growth Calculator", slug: "kpi-growth-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 23, name: "KPI Comparison Tool", slug: "kpi-comparison-tool", category: "Analytics & SaaS Tools", isPro: false },
  { id: 24, name: "Click-Through Rate Calculator", slug: "ctr-calculator-saas", category: "Analytics & SaaS Tools", isPro: false },
  { id: 25, name: "Engagement Rate Calculator", slug: "engagement-rate-calculator-saas", category: "Analytics & SaaS Tools", isPro: false },
  { id: 26, name: "Customer Growth Calculator", slug: "customer-growth-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 27, name: "CAC Payback Calculator", slug: "cac-payback-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 28, name: "MRR Growth Calculator", slug: "mrr-growth-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 29, name: "Revenue Growth Calculator", slug: "revenue-growth-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 30, name: "Gross Revenue Retention Calculator", slug: "grr-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 31, name: "Logo Churn Calculator", slug: "logo-churn-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 32, name: "Revenue Churn Calculator", slug: "revenue-churn-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 33, name: "Expansion Revenue Calculator", slug: "expansion-revenue-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 34, name: "SaaS Margin Calculator", slug: "saas-margin-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 35, name: "Operating Margin Calculator", slug: "operating-margin-calculator-saas", category: "Analytics & SaaS Tools", isPro: false },
  { id: 36, name: "Break-Even Calculator", slug: "break-even-calculator-saas", category: "Analytics & SaaS Tools", isPro: false },
  { id: 37, name: "Profit Margin Calculator", slug: "profit-margin-calculator-saas", category: "Analytics & SaaS Tools", isPro: false },
  { id: 38, name: "Startup Valuation Calculator", slug: "startup-valuation-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 39, name: "Revenue Forecast Calculator", slug: "revenue-forecast-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 40, name: "Subscription Revenue Calculator", slug: "subscription-revenue-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 41, name: "SaaS Pricing Comparison Tool", slug: "saas-pricing-comparison-tool", category: "Analytics & SaaS Tools", isPro: false },
  { id: 42, name: "Free Trial Conversion Calculator", slug: "free-trial-conversion-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 43, name: "Trial-to-Paid Calculator", slug: "trial-to-paid-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 44, name: "Lead-to-Customer Calculator", slug: "lead-to-customer-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 45, name: "Funnel Drop-Off Analyzer", slug: "funnel-drop-off-analyzer", category: "Analytics & SaaS Tools", isPro: false },
  { id: 46, name: "Cohort Retention Calculator", slug: "cohort-retention-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 47, name: "Customer Segmentation Tool", slug: "customer-segmentation-tool", category: "Analytics & SaaS Tools", isPro: false },
  { id: 48, name: "Revenue Cohort Analyzer", slug: "revenue-cohort-analyzer", category: "Analytics & SaaS Tools", isPro: false },
  { id: 49, name: "User Growth Analyzer", slug: "user-growth-analyzer", category: "Analytics & SaaS Tools", isPro: false },
  { id: 50, name: "Product Adoption Calculator", slug: "product-adoption-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 51, name: "Feature Adoption Calculator", slug: "feature-adoption-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 52, name: "Activation Rate Calculator", slug: "activation-rate-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 53, name: "DAU MAU Calculator", slug: "dau-mau-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 54, name: "Stickiness Calculator", slug: "stickiness-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 55, name: "Session Analysis Calculator", slug: "session-analysis-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 56, name: "Product Usage Calculator", slug: "product-usage-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 57, name: "A/B Test Sample Size Calculator", slug: "ab-test-sample-size-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 58, name: "A/B Test Significance Calculator", slug: "ab-test-significance-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 59, name: "Statistical Significance Calculator", slug: "statistical-significance-calculator", category: "Analytics & SaaS Tools", isPro: false },
  { id: 60, name: "Experiment Calculator", slug: "experiment-calculator", category: "Analytics & SaaS Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "SaaS Metrics Dashboard", slug: "saas-metrics-dashboard", category: "Analytics & SaaS Tools", isPro: true },
  { id: 62, name: "Churn Prediction Dashboard", slug: "churn-prediction-dashboard", category: "Analytics & SaaS Tools", isPro: true },
  { id: 63, name: "Revenue Forecasting Engine", slug: "revenue-forecasting-engine", category: "Analytics & SaaS Tools", isPro: true },
  { id: 64, name: "Revenue Intelligence Dashboard", slug: "revenue-intelligence-dashboard", category: "Analytics & SaaS Tools", isPro: true },
  { id: 65, name: "Customer Intelligence Dashboard", slug: "customer-intelligence-dashboard", category: "Analytics & SaaS Tools", isPro: true },
  { id: 66, name: "Product Analytics Dashboard", slug: "product-analytics-dashboard", category: "Analytics & SaaS Tools", isPro: true },
  { id: 67, name: "Growth Analytics Dashboard", slug: "growth-analytics-dashboard", category: "Analytics & SaaS Tools", isPro: true },
  { id: 68, name: "Funnel Intelligence Platform", slug: "funnel-intelligence-platform", category: "Analytics & SaaS Tools", isPro: true },
  { id: 69, name: "Cohort Intelligence Platform", slug: "cohort-intelligence-platform", category: "Analytics & SaaS Tools", isPro: true },
  { id: 70, name: "Subscription Analytics Platform", slug: "subscription-analytics-platform", category: "Analytics & SaaS Tools", isPro: true },
  { id: 71, name: "Customer Health Score Engine", slug: "customer-health-score-engine", category: "Analytics & SaaS Tools", isPro: true },
  { id: 72, name: "Customer Lifetime Value Model", slug: "customer-lifetime-value-model", category: "Analytics & SaaS Tools", isPro: true },
  { id: 73, name: "Pricing Intelligence Engine", slug: "pricing-intelligence-engine", category: "Analytics & SaaS Tools", isPro: true },
  { id: 74, name: "SaaS Pricing Simulator", slug: "saas-pricing-simulator", category: "Analytics & SaaS Tools", isPro: true },
  { id: 75, name: "SaaS Unit Economics Model", slug: "saas-unit-economics-model", category: "Analytics & SaaS Tools", isPro: true },
  { id: 76, name: "SaaS Financial Model", slug: "saas-financial-model", category: "Analytics & SaaS Tools", isPro: true },
  { id: 77, name: "SaaS Scenario Planner", slug: "saas-scenario-planner", category: "Analytics & SaaS Tools", isPro: true },
  { id: 78, name: "Startup Runway Dashboard", slug: "startup-runway-dashboard", category: "Analytics & SaaS Tools", isPro: true },
  { id: 79, name: "Startup KPI Dashboard", slug: "startup-kpi-dashboard", category: "Analytics & SaaS Tools", isPro: true },
  { id: 80, name: "Executive Metrics Dashboard", slug: "executive-metrics-dashboard", category: "Analytics & SaaS Tools", isPro: true },
  { id: 81, name: "Product KPI Dashboard", slug: "product-kpi-dashboard", category: "Analytics & SaaS Tools", isPro: true },
  { id: 82, name: "Marketing Attribution Dashboard", slug: "marketing-attribution-dashboard", category: "Analytics & SaaS Tools", isPro: true },
  { id: 83, name: "Customer Journey Analyzer", slug: "customer-journey-analyzer", category: "Analytics & SaaS Tools", isPro: true },
  { id: 84, name: "Conversion Funnel Analyzer", slug: "conversion-funnel-analyzer", category: "Analytics & SaaS Tools", isPro: true },
  { id: 85, name: "Experiment Management Platform", slug: "experiment-management-platform", category: "Analytics & SaaS Tools", isPro: true },
  { id: 86, name: "A/B Testing Dashboard", slug: "ab-testing-dashboard", category: "Analytics & SaaS Tools", isPro: true },
  { id: 87, name: "Feature Experiment Tracker", slug: "feature-experiment-tracker", category: "Analytics & SaaS Tools", isPro: true },
  { id: 88, name: "Product Analytics Workspace", slug: "product-analytics-workspace", category: "Analytics & SaaS Tools", isPro: true },
  { id: 89, name: "Revenue Analytics Workspace", slug: "revenue-analytics-workspace", category: "Analytics & SaaS Tools", isPro: true },
  { id: 90, name: "Customer Analytics Workspace", slug: "customer-analytics-workspace", category: "Analytics & SaaS Tools", isPro: true },
  { id: 91, name: "Growth Intelligence Workspace", slug: "growth-intelligence-workspace", category: "Analytics & SaaS Tools", isPro: true },
  { id: 92, name: "SaaS Benchmarking Tool", slug: "saas-benchmarking-tool", category: "Analytics & SaaS Tools", isPro: true },
  { id: 93, name: "SaaS Peer Comparison Tool", slug: "saas-peer-comparison-tool", category: "Analytics & SaaS Tools", isPro: true },
  { id: 94, name: "SaaS Health Score", slug: "saas-health-score", category: "Analytics & SaaS Tools", isPro: true },
  { id: 95, name: "SaaS Forecasting Workspace", slug: "saas-forecasting-workspace", category: "Analytics & SaaS Tools", isPro: true },
  { id: 96, name: "Business Performance Intelligence", slug: "business-performance-intelligence", category: "Analytics & SaaS Tools", isPro: true },
  { id: 97, name: "Executive Business Intelligence Workspace", slug: "executive-business-intelligence-workspace", category: "Analytics & SaaS Tools", isPro: true },
  { id: 98, name: "SaaS Operations Dashboard", slug: "saas-operations-dashboard", category: "Analytics & SaaS Tools", isPro: true },
  { id: 99, name: "SaaS Intelligence Platform", slug: "saas-intelligence-platform", category: "Analytics & SaaS Tools", isPro: true },
  { id: 100, name: "Business Analytics Workspace", slug: "business-analytics-workspace", category: "Analytics & SaaS Tools", isPro: true },
];