export interface AudioTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const audioToolsList: AudioTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-14) ---
  { id: 1, name: "Audio Compressor", slug: "audio-compressor", category: "Audio Tools", isPro: false },
  { id: 2, name: "Audio Cutter", slug: "audio-cutter", category: "Audio Tools", isPro: false },
  { id: 3, name: "Audio Converter", slug: "audio-converter", category: "Audio Tools", isPro: false },
  { id: 4, name: "MP3 Converter", slug: "mp3-converter", category: "Audio Tools", isPro: false },
  { id: 5, name: "Audio Normalizer", slug: "audio-normalizer", category: "Audio Tools", isPro: false },
  { id: 6, name: "Audio Noise Reducer", slug: "audio-noise-reducer", category: "Audio Tools", isPro: false },
  { id: 7, name: "Audio Silence Remover", slug: "audio-silence-remover", category: "Audio Tools", isPro: false },
  { id: 8, name: "Audio Volume Changer", slug: "audio-volume-changer", category: "Audio Tools", isPro: false },
  { id: 9, name: "Audio Speed Changer", slug: "audio-speed-changer", category: "Audio Tools", isPro: false },
  { id: 10, name: "Audio Pitch Changer", slug: "audio-pitch-changer", category: "Audio Tools", isPro: false },
  { id: 11, name: "Audio Metadata Editor", slug: "audio-metadata-editor", category: "Audio Tools", isPro: false },
  { id: 12, name: "ID3 Tag Editor", slug: "id3-tag-editor", category: "Audio Tools", isPro: false },
  { id: 13, name: "LUFS Calculator", slug: "lufs-calculator", category: "Audio Tools", isPro: false },
  { id: 14, name: "Microphone Test", slug: "microphone-test", category: "Audio Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (15-60) ---
  { id: 15, name: "Audio Trimmer", slug: "audio-trimmer", category: "Audio Tools", isPro: false },
  { id: 16, name: "Audio Merger", slug: "audio-merger", category: "Audio Tools", isPro: false },
  { id: 17, name: "Audio Splitter", slug: "audio-splitter", category: "Audio Tools", isPro: false },
  { id: 18, name: "Audio Joiner", slug: "audio-joiner", category: "Audio Tools", isPro: false },
  { id: 19, name: "WAV Converter", slug: "wav-converter", category: "Audio Tools", isPro: false },
  { id: 20, name: "AAC Converter", slug: "aac-converter", category: "Audio Tools", isPro: false },
  { id: 21, name: "FLAC Converter", slug: "flac-converter", category: "Audio Tools", isPro: false },
  { id: 22, name: "OGG Converter", slug: "ogg-converter", category: "Audio Tools", isPro: false },
  { id: 23, name: "M4A Converter", slug: "m4a-converter", category: "Audio Tools", isPro: false },
  { id: 24, name: "MP3 to WAV Converter", slug: "mp3-to-wav-converter", category: "Audio Tools", isPro: false },
  { id: 25, name: "WAV to MP3 Converter", slug: "wav-to-mp3-converter", category: "Audio Tools", isPro: false },
  { id: 26, name: "MP3 to AAC Converter", slug: "mp3-to-aac-converter", category: "Audio Tools", isPro: false },
  { id: 27, name: "MP3 to FLAC Converter", slug: "mp3-to-flac-converter", category: "Audio Tools", isPro: false },
  { id: 28, name: "M4A to MP3 Converter", slug: "m4a-to-mp3-converter", category: "Audio Tools", isPro: false },
  { id: 29, name: "OGG to MP3 Converter", slug: "ogg-to-mp3-converter", category: "Audio Tools", isPro: false },
  { id: 30, name: "Audio Format Detector", slug: "audio-format-detector", category: "Audio Tools", isPro: false },
  { id: 31, name: "Audio Bitrate Converter", slug: "audio-bitrate-converter", category: "Audio Tools", isPro: false },
  { id: 32, name: "Audio Sample Rate Converter", slug: "audio-sample-rate-converter", category: "Audio Tools", isPro: false },
  { id: 33, name: "Audio Fade In Generator", slug: "audio-fade-in-generator", category: "Audio Tools", isPro: false },
  { id: 34, name: "Audio Fade Out Generator", slug: "audio-fade-out-generator", category: "Audio Tools", isPro: false },
  { id: 35, name: "Audio Loop Maker", slug: "audio-loop-maker", category: "Audio Tools", isPro: false },
  { id: 36, name: "Audio Reverse Tool", slug: "audio-reverse-tool", category: "Audio Tools", isPro: false },
  { id: 37, name: "Audio Equalizer", slug: "audio-equalizer", category: "Audio Tools", isPro: false },
  { id: 38, name: "Bass Booster", slug: "bass-booster", category: "Audio Tools", isPro: false },
  { id: 39, name: "Treble Booster", slug: "treble-booster", category: "Audio Tools", isPro: false },
  { id: 40, name: "Audio Hum Remover", slug: "audio-hum-remover", category: "Audio Tools", isPro: false },
  { id: 41, name: "Audio Click Remover", slug: "audio-click-remover", category: "Audio Tools", isPro: false },
  { id: 42, name: "Audio Clipper Detector", slug: "audio-clipper-detector", category: "Audio Tools", isPro: false },
  { id: 43, name: "Audio Loudness Meter", slug: "audio-loudness-meter", category: "Audio Tools", isPro: false },
  { id: 44, name: "Audio Duration Calculator", slug: "audio-duration-calculator", category: "Audio Tools", isPro: false },
  { id: 45, name: "Audio File Size Calculator", slug: "audio-file-size-calculator", category: "Audio Tools", isPro: false },
  { id: 46, name: "Audio Waveform Generator", slug: "audio-waveform-generator", category: "Audio Tools", isPro: false },
  { id: 47, name: "Audio Spectrogram Generator", slug: "audio-spectrogram-generator", category: "Audio Tools", isPro: false },
  { id: 48, name: "Audio Metadata Viewer", slug: "audio-metadata-viewer", category: "Audio Tools", isPro: false },
  { id: 49, name: "Album Artwork Embedder", slug: "album-artwork-embedder", category: "Audio Tools", isPro: false },
  { id: 50, name: "Audio Chapter Marker", slug: "audio-chapter-marker", category: "Audio Tools", isPro: false },
  { id: 51, name: "Audio Bookmark Generator", slug: "audio-bookmark-generator", category: "Audio Tools", isPro: false },
  { id: 52, name: "Podcast Audio Converter", slug: "podcast-audio-converter", category: "Audio Tools", isPro: false },
  { id: 53, name: "Podcast Audio Compressor", slug: "podcast-audio-compressor", category: "Audio Tools", isPro: false },
  { id: 54, name: "Podcast Intro Maker", slug: "podcast-intro-maker", category: "Audio Tools", isPro: false },
  { id: 55, name: "Podcast Outro Maker", slug: "podcast-outro-maker", category: "Audio Tools", isPro: false },
  { id: 56, name: "Voice Recorder", slug: "voice-recorder", category: "Audio Tools", isPro: false },
  { id: 57, name: "Audio Recorder", slug: "audio-recorder", category: "Audio Tools", isPro: false },
  { id: 58, name: "Audio Test Generator", slug: "audio-test-generator", category: "Audio Tools", isPro: false },
  { id: 59, name: "Stereo/Mono Converter", slug: "stereo-mono-converter", category: "Audio Tools", isPro: false },
  { id: 60, name: "Channel Converter", slug: "channel-converter", category: "Audio Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "AI Audio Enhancer", slug: "ai-audio-enhancer", category: "Audio Tools", isPro: true },
  { id: 62, name: "AI Voice Cleaner", slug: "ai-voice-cleaner", category: "Audio Tools", isPro: true },
  { id: 63, name: "AI Background Noise Remover", slug: "ai-background-noise-remover", category: "Audio Tools", isPro: true },
  { id: 64, name: "AI Vocal Remover", slug: "ai-vocal-remover", category: "Audio Tools", isPro: true },
  { id: 65, name: "AI Stem Separator", slug: "ai-stem-separator", category: "Audio Tools", isPro: true },
  { id: 66, name: "AI Podcast Editor", slug: "ai-podcast-editor", category: "Audio Tools", isPro: true },
  { id: 67, name: "AI Echo Remover", slug: "ai-echo-remover", category: "Audio Tools", isPro: true },
  { id: 68, name: "AI Reverb Remover", slug: "ai-reverb-remover", category: "Audio Tools", isPro: true },
  { id: 69, name: "AI Voice Isolator", slug: "ai-voice-isolator", category: "Audio Tools", isPro: true },
  { id: 70, name: "AI Instrumental Extractor", slug: "ai-instrumental-extractor", category: "Audio Tools", isPro: true },
  { id: 71, name: "AI Music Stem Splitter", slug: "ai-music-stem-splitter", category: "Audio Tools", isPro: true },
  { id: 72, name: "AI Speech Enhancer", slug: "ai-speech-enhancer", category: "Audio Tools", isPro: true },
  { id: 73, name: "AI Podcast Chapter Generator", slug: "ai-podcast-chapter-generator", category: "Audio Tools", isPro: true },
  { id: 74, name: "AI Podcast Show Notes Generator", slug: "ai-podcast-show-notes-generator", category: "Audio Tools", isPro: true },
  { id: 75, name: "AI Podcast Transcript Cleaner", slug: "ai-podcast-transcript-cleaner", category: "Audio Tools", isPro: true },
  { id: 76, name: "AI Podcast Clip Finder", slug: "ai-podcast-clip-finder", category: "Audio Tools", isPro: true },
  { id: 77, name: "AI Audio Summarizer", slug: "ai-audio-summarizer", category: "Audio Tools", isPro: true },
  { id: 78, name: "AI Audio Translator", slug: "ai-audio-translator", category: "Audio Tools", isPro: true },
  { id: 79, name: "AI Audio Dubbing Planner", slug: "ai-audio-dubbing-planner", category: "Audio Tools", isPro: true },
  { id: 80, name: "AI Voiceover Studio", slug: "ai-voiceover-studio", category: "Audio Tools", isPro: true },
  { id: 81, name: "Multi-Track Audio Mixer", slug: "multi-track-audio-mixer", category: "Audio Tools", isPro: true },
  { id: 82, name: "Professional Audio Mastering Tool", slug: "professional-audio-mastering-tool", category: "Audio Tools", isPro: true },
  { id: 83, name: "Loudness Compliance Analyzer", slug: "loudness-compliance-analyzer", category: "Audio Tools", isPro: true },
  { id: 84, name: "Broadcast Audio Analyzer", slug: "broadcast-audio-analyzer", category: "Audio Tools", isPro: true },
  { id: 85, name: "Podcast Quality Analyzer", slug: "podcast-quality-analyzer", category: "Audio Tools", isPro: true },
  { id: 86, name: "Audio Quality Scoring Engine", slug: "audio-quality-scoring-engine", category: "Audio Tools", isPro: true },
  { id: 87, name: "Voice Quality Analyzer", slug: "voice-quality-analyzer", category: "Audio Tools", isPro: true },
  { id: 88, name: "Microphone Quality Analyzer", slug: "microphone-quality-analyzer", category: "Audio Tools", isPro: true },
  { id: 89, name: "Audio Frequency Analyzer", slug: "audio-frequency-analyzer", category: "Audio Tools", isPro: true },
  { id: 90, name: "Audio Dynamic Range Analyzer", slug: "audio-dynamic-range-analyzer", category: "Audio Tools", isPro: true },
  { id: 91, name: "Audio Phase Analyzer", slug: "audio-phase-analyzer", category: "Audio Tools", isPro: true },
  { id: 92, name: "Audio Channel Analyzer", slug: "audio-channel-analyzer", category: "Audio Tools", isPro: true },
  { id: 93, name: "Audio Production Checklist", slug: "audio-production-checklist", category: "Audio Tools", isPro: true },
  { id: 94, name: "Podcast Production Workspace", slug: "podcast-production-workspace", category: "Audio Tools", isPro: true },
  { id: 95, name: "Audio Content Repurposing Engine", slug: "audio-content-repurposing-engine", category: "Audio Tools", isPro: true },
  { id: 96, name: "Voice Content Analytics", slug: "voice-content-analytics", category: "Audio Tools", isPro: true },
  { id: 97, name: "Audio Asset Manager", slug: "audio-asset-manager", category: "Audio Tools", isPro: true },
  { id: 98, name: "Audio Processing Pipeline", slug: "audio-processing-pipeline", category: "Audio Tools", isPro: true },
  { id: 99, name: "Creator Audio Workspace", slug: "creator-audio-workspace", category: "Audio Tools", isPro: true },
  { id: 100, name: "Professional Audio Intelligence Workspace", slug: "professional-audio-intelligence-workspace", category: "Audio Tools", isPro: true },
];