export interface AutomobileTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const automobileToolsList: AutomobileTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "Car Loan Payment Calculator", slug: "car-loan-payment-calculator", category: "Automobile Tools", isPro: false },
  { id: 2, name: "Auto Loan Affordability Calculator", slug: "auto-loan-affordability-calculator", category: "Automobile Tools", isPro: false },
  { id: 3, name: "Car Lease Payment Calculator", slug: "car-lease-payment-calculator", category: "Automobile Tools", isPro: false },
  { id: 4, name: "Lease vs Buy Calculator", slug: "lease-vs-buy-calculator", category: "Automobile Tools", isPro: false },
  { id: 5, name: "Car Trade-In Value Calculator", slug: "car-trade-in-value-calculator", category: "Automobile Tools", isPro: false },
  { id: 6, name: "Car Depreciation Calculator", slug: "car-depreciation-calculator", category: "Automobile Tools", isPro: false },
  { id: 7, name: "Total Cost of Car Ownership Calculator", slug: "total-cost-of-car-ownership-calculator", category: "Automobile Tools", isPro: false },
  { id: 8, name: "Fuel Cost Calculator", slug: "fuel-cost-calculator", category: "Automobile Tools", isPro: false },
  { id: 9, name: "EV Charging Cost Calculator", slug: "ev-charging-cost-calculator", category: "Automobile Tools", isPro: false },
  { id: 10, name: "EV vs Gas Cost Calculator", slug: "ev-vs-gas-cost-calculator", category: "Automobile Tools", isPro: false },
  { id: 11, name: "Road Trip Fuel Calculator", slug: "road-trip-fuel-calculator", category: "Automobile Tools", isPro: false },
  { id: 12, name: "Car Insurance Cost Estimator", slug: "car-insurance-cost-estimator", category: "Automobile Tools", isPro: false },
  { id: 13, name: "Vehicle Maintenance Cost Calculator", slug: "vehicle-maintenance-cost-calculator", category: "Automobile Tools", isPro: false },
  { id: 14, name: "Tire Size Calculator", slug: "tire-size-calculator", category: "Automobile Tools", isPro: false },
  { id: 15, name: "Towing Capacity Calculator", slug: "towing-capacity-calculator", category: "Automobile Tools", isPro: false },
  { id: 16, name: "VIN Decoder", slug: "vin-decoder", category: "Automobile Tools", isPro: false },
  { id: 17, name: "Used Car Inspection Checklist", slug: "used-car-inspection-checklist", category: "Automobile Tools", isPro: false },
  { id: 18, name: "Car Down Payment Calculator", slug: "car-down-payment-calculator", category: "Automobile Tools", isPro: false },
  { id: 19, name: "Car Loan Amortization Calculator", slug: "car-loan-amortization-calculator", category: "Automobile Tools", isPro: false },
  { id: 20, name: "Car Refinance Calculator", slug: "car-refinance-calculator", category: "Automobile Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Auto Loan Interest Calculator", slug: "auto-loan-interest-calculator", category: "Automobile Tools", isPro: false },
  { id: 22, name: "Vehicle Resale Value Calculator", slug: "vehicle-resale-value-calculator", category: "Automobile Tools", isPro: false },
  { id: 23, name: "Fuel Consumption Calculator", slug: "fuel-consumption-calculator", category: "Automobile Tools", isPro: false },
  { id: 24, name: "Fuel Economy Converter", slug: "fuel-economy-converter", category: "Automobile Tools", isPro: false },
  { id: 25, name: "MPG to L/100km Converter", slug: "mpg-to-l-100km-converter", category: "Automobile Tools", isPro: false },
  { id: 26, name: "L/100km to MPG Converter", slug: "l-100km-to-mpg-converter", category: "Automobile Tools", isPro: false },
  { id: 27, name: "EV Range Calculator", slug: "ev-range-calculator", category: "Automobile Tools", isPro: false },
  { id: 28, name: "EV Charging Time Calculator", slug: "ev-charging-time-calculator", category: "Automobile Tools", isPro: false },
  { id: 29, name: "Trip Mileage Calculator", slug: "trip-mileage-calculator", category: "Automobile Tools", isPro: false },
  { id: 30, name: "Driving Cost Calculator", slug: "driving-cost-calculator", category: "Automobile Tools", isPro: false },
  { id: 31, name: "Toll Cost Calculator", slug: "toll-cost-calculator", category: "Automobile Tools", isPro: false },
  { id: 32, name: "Auto Insurance Deductible Calculator", slug: "auto-insurance-deductible-calculator", category: "Automobile Tools", isPro: false },
  { id: 33, name: "Vehicle Registration Cost Estimator", slug: "vehicle-registration-cost-estimator", category: "Automobile Tools", isPro: false },
  { id: 34, name: "Vehicle Tax Calculator", slug: "vehicle-tax-calculator", category: "Automobile Tools", isPro: false },
  { id: 35, name: "Car Import Duty Calculator", slug: "car-import-duty-calculator", category: "Automobile Tools", isPro: false },
  { id: 36, name: "Car Service Interval Calculator", slug: "car-service-interval-calculator", category: "Automobile Tools", isPro: false },
  { id: 37, name: "Oil Change Interval Calculator", slug: "oil-change-interval-calculator", category: "Automobile Tools", isPro: false },
  { id: 38, name: "Tire Replacement Calculator", slug: "tire-replacement-calculator", category: "Automobile Tools", isPro: false },
  { id: 39, name: "Tire Pressure Converter", slug: "tire-pressure-converter", category: "Automobile Tools", isPro: false },
  { id: 40, name: "Wheel Offset Calculator", slug: "wheel-offset-calculator", category: "Automobile Tools", isPro: false },
  { id: 41, name: "Wheel Size Calculator", slug: "wheel-size-calculator", category: "Automobile Tools", isPro: false },
  { id: 42, name: "Engine Displacement Calculator", slug: "engine-displacement-calculator", category: "Automobile Tools", isPro: false },
  { id: 43, name: "Horsepower Converter", slug: "horsepower-converter", category: "Automobile Tools", isPro: false },
  { id: 44, name: "Torque Converter", slug: "torque-converter", category: "Automobile Tools", isPro: false },
  { id: 45, name: "Horsepower-to-Weight Calculator", slug: "horsepower-to-weight-calculator", category: "Automobile Tools", isPro: false },
  { id: 46, name: "Vehicle Power-to-Weight Calculator", slug: "vehicle-power-to-weight-calculator", category: "Automobile Tools", isPro: false },
  { id: 47, name: "Gear Ratio Calculator", slug: "gear-ratio-calculator", category: "Automobile Tools", isPro: false },
  { id: 48, name: "RPM Calculator", slug: "rpm-calculator", category: "Automobile Tools", isPro: false },
  { id: 49, name: "Speedometer Error Calculator", slug: "speedometer-error-calculator", category: "Automobile Tools", isPro: false },
  { id: 50, name: "Braking Distance Calculator", slug: "braking-distance-calculator", category: "Automobile Tools", isPro: false },
  { id: 51, name: "Stopping Distance Calculator", slug: "stopping-distance-calculator", category: "Automobile Tools", isPro: false },
  { id: 52, name: "Following Distance Calculator", slug: "following-distance-calculator", category: "Automobile Tools", isPro: false },
  { id: 53, name: "Vehicle Load Calculator", slug: "vehicle-load-calculator", category: "Automobile Tools", isPro: false },
  { id: 54, name: "Trailer Weight Calculator", slug: "trailer-weight-calculator", category: "Automobile Tools", isPro: false },
  { id: 55, name: "Payload Capacity Calculator", slug: "payload-capacity-calculator", category: "Automobile Tools", isPro: false },
  { id: 56, name: "VIN Validator", slug: "vin-validator", category: "Automobile Tools", isPro: false },
  { id: 57, name: "License Plate Format Checker", slug: "license-plate-format-checker", category: "Automobile Tools", isPro: false },
  { id: 58, name: "Car Maintenance Checklist", slug: "car-maintenance-checklist", category: "Automobile Tools", isPro: false },
  { id: 59, name: "Pre-Purchase Car Checklist", slug: "pre-purchase-car-checklist", category: "Automobile Tools", isPro: false },
  { id: 60, name: "Road Trip Car Checklist", slug: "road-trip-car-checklist", category: "Automobile Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Used Car Deal Analyzer", slug: "used-car-deal-analyzer", category: "Automobile Tools", isPro: true },
  { id: 62, name: "Used Car Price Analyzer", slug: "used-car-price-analyzer", category: "Automobile Tools", isPro: true },
  { id: 63, name: "Vehicle Ownership Dashboard", slug: "vehicle-ownership-dashboard", category: "Automobile Tools", isPro: true },
  { id: 64, name: "Vehicle Ownership Cost Analyzer", slug: "vehicle-ownership-cost-analyzer", category: "Automobile Tools", isPro: true },
  { id: 65, name: "Fleet Cost Analyzer", slug: "fleet-cost-analyzer", category: "Automobile Tools", isPro: true },
  { id: 66, name: "Fleet Fuel Cost Analyzer", slug: "fleet-fuel-cost-analyzer", category: "Automobile Tools", isPro: true },
  { id: 67, name: "Fleet Maintenance Planner", slug: "fleet-maintenance-planner", category: "Automobile Tools", isPro: true },
  { id: 68, name: "Fleet Replacement Planner", slug: "fleet-replacement-planner", category: "Automobile Tools", isPro: true },
  { id: 69, name: "Vehicle Depreciation Forecast", slug: "vehicle-depreciation-forecast", category: "Automobile Tools", isPro: true },
  { id: 70, name: "Vehicle Resale Forecast", slug: "vehicle-resale-forecast", category: "Automobile Tools", isPro: true },
  { id: 71, name: "EV Total Cost Analyzer", slug: "ev-total-cost-analyzer", category: "Automobile Tools", isPro: true },
  { id: 72, name: "EV Fleet Cost Analyzer", slug: "ev-fleet-cost-analyzer", category: "Automobile Tools", isPro: true },
  { id: 73, name: "Car Financing Comparison Engine", slug: "car-financing-comparison-engine", category: "Automobile Tools", isPro: true },
  { id: 74, name: "Auto Loan Scenario Planner", slug: "auto-loan-scenario-planner", category: "Automobile Tools", isPro: true },
  { id: 75, name: "Lease Scenario Analyzer", slug: "lease-scenario-analyzer", category: "Automobile Tools", isPro: true },
  { id: 76, name: "Vehicle Insurance Comparison Workspace", slug: "vehicle-insurance-comparison-workspace", category: "Automobile Tools", isPro: true },
  { id: 77, name: "Vehicle Maintenance Forecast", slug: "vehicle-maintenance-forecast", category: "Automobile Tools", isPro: true },
  { id: 78, name: "Predictive Maintenance Planner", slug: "predictive-maintenance-planner", category: "Automobile Tools", isPro: true },
  { id: 79, name: "Vehicle Service History Analyzer", slug: "vehicle-service-history-analyzer", category: "Automobile Tools", isPro: true },
  { id: 80, name: "Vehicle Recall Lookup Workspace", slug: "vehicle-recall-lookup-workspace", category: "Automobile Tools", isPro: true },
  { id: 81, name: "VIN Intelligence Workspace", slug: "vin-intelligence-workspace", category: "Automobile Tools", isPro: true },
  { id: 82, name: "Used Car Risk Analyzer", slug: "used-car-risk-analyzer", category: "Automobile Tools", isPro: true },
  { id: 83, name: "Vehicle Market Value Analyzer", slug: "vehicle-market-value-analyzer", category: "Automobile Tools", isPro: true },
  { id: 84, name: "Car Deal Score", slug: "car-deal-score", category: "Automobile Tools", isPro: true },
  { id: 85, name: "Vehicle Condition Scoring Tool", slug: "vehicle-condition-scoring-tool", category: "Automobile Tools", isPro: true },
  { id: 86, name: "Tire Replacement Planner", slug: "tire-replacement-planner", category: "Automobile Tools", isPro: true },
  { id: 87, name: "Fleet Driver Cost Analyzer", slug: "fleet-driver-cost-analyzer", category: "Automobile Tools", isPro: true },
  { id: 88, name: "Fleet Utilization Analyzer", slug: "fleet-utilization-analyzer", category: "Automobile Tools", isPro: true },
  { id: 89, name: "Fleet ROI Calculator", slug: "fleet-roi-calculator", category: "Automobile Tools", isPro: true },
  { id: 90, name: "Commercial Vehicle Cost Analyzer", slug: "commercial-vehicle-cost-analyzer", category: "Automobile Tools", isPro: true },
  { id: 91, name: "Delivery Vehicle Cost Planner", slug: "delivery-vehicle-cost-planner", category: "Automobile Tools", isPro: true },
  { id: 92, name: "EV Charging Route Planner", slug: "ev-charging-route-planner", category: "Automobile Tools", isPro: true },
  { id: 93, name: "EV Charging Cost Planner", slug: "ev-charging-cost-planner", category: "Automobile Tools", isPro: true },
  { id: 94, name: "Road Trip Cost Planner", slug: "road-trip-cost-planner", category: "Automobile Tools", isPro: true },
  { id: 95, name: "Car Maintenance Dashboard", slug: "car-maintenance-dashboard", category: "Automobile Tools", isPro: true },
  { id: 96, name: "Fleet Management Workspace", slug: "fleet-management-workspace", category: "Automobile Tools", isPro: true },
  { id: 97, name: "Vehicle Expense Workspace", slug: "vehicle-expense-workspace", category: "Automobile Tools", isPro: true },
  { id: 98, name: "Automotive Deal Intelligence Workspace", slug: "automotive-deal-intelligence-workspace", category: "Automobile Tools", isPro: true },
  { id: 99, name: "Vehicle Investment Analyzer", slug: "vehicle-investment-analyzer", category: "Automobile Tools", isPro: true },
  { id: 100, name: "Automotive Operations Intelligence Workspace", slug: "automotive-operations-intelligence-workspace", category: "Automobile Tools", isPro: true }
];