export interface BankingTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const bankingToolsList: BankingTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "Savings Interest Calculator", slug: "savings-interest-calculator", category: "Banking Tools", isPro: false },
  { id: 2, name: "Compound Interest Calculator", slug: "compound-interest-calculator", category: "Banking Tools", isPro: false },
  { id: 3, name: "Savings Goal Calculator", slug: "savings-goal-calculator", category: "Banking Tools", isPro: false },
  { id: 4, name: "Emergency Fund Calculator", slug: "emergency-fund-calculator", category: "Banking Tools", isPro: false },
  { id: 5, name: "Fixed Deposit Calculator", slug: "fixed-deposit-calculator", category: "Banking Tools", isPro: false },
  { id: 6, name: "Recurring Deposit Calculator", slug: "recurring-deposit-calculator", category: "Banking Tools", isPro: false },
  { id: 7, name: "Loan Payment Calculator", slug: "loan-payment-calculator", category: "Banking Tools", isPro: false },
  { id: 8, name: "Personal Loan Calculator", slug: "personal-loan-calculator", category: "Banking Tools", isPro: false },
  { id: 9, name: "Home Loan Calculator", slug: "home-loan-calculator", category: "Banking Tools", isPro: false },
  { id: 10, name: "Loan Amortization Calculator", slug: "loan-amortization-calculator", category: "Banking Tools", isPro: false },
  { id: 11, name: "Loan Eligibility Calculator", slug: "loan-eligibility-calculator", category: "Banking Tools", isPro: false },
  { id: 12, name: "Debt-to-Income Calculator", slug: "debt-to-income-calculator", category: "Banking Tools", isPro: false },
  { id: 13, name: "Debt Repayment Calculator", slug: "debt-repayment-calculator", category: "Banking Tools", isPro: false },
  { id: 14, name: "Early Loan Repayment Calculator", slug: "early-loan-repayment-calculator", category: "Banking Tools", isPro: false },
  { id: 15, name: "Refinance Savings Calculator", slug: "refinance-savings-calculator", category: "Banking Tools", isPro: false },
  { id: 16, name: "EMI Calculator", slug: "emi-calculator", category: "Banking Tools", isPro: false },
  { id: 17, name: "Bank Fee Calculator", slug: "bank-fee-calculator", category: "Banking Tools", isPro: false },
  { id: 18, name: "International Transfer Fee Calculator", slug: "international-transfer-fee-calculator", category: "Banking Tools", isPro: false },
  { id: 19, name: "Exchange Rate Calculator", slug: "exchange-rate-calculator", category: "Banking Tools", isPro: false },
  { id: 20, name: "Simple Interest Calculator", slug: "simple-interest-calculator", category: "Banking Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Monthly Savings Calculator", slug: "monthly-savings-calculator", category: "Banking Tools", isPro: false },
  { id: 22, name: "Annual Savings Calculator", slug: "annual-savings-calculator", category: "Banking Tools", isPro: false },
  { id: 23, name: "Certificate of Deposit Calculator", slug: "certificate-of-deposit-calculator", category: "Banking Tools", isPro: false },
  { id: 24, name: "Bank Deposit Calculator", slug: "bank-deposit-calculator", category: "Banking Tools", isPro: false },
  { id: 25, name: "Deposit Maturity Calculator", slug: "deposit-maturity-calculator", category: "Banking Tools", isPro: false },
  { id: 26, name: "Auto Loan Calculator", slug: "auto-loan-calculator", category: "Banking Tools", isPro: false },
  { id: 27, name: "Education Loan Calculator", slug: "education-loan-calculator", category: "Banking Tools", isPro: false },
  { id: 28, name: "Business Loan Calculator", slug: "business-loan-calculator", category: "Banking Tools", isPro: false },
  { id: 29, name: "Loan Interest Calculator", slug: "loan-interest-calculator", category: "Banking Tools", isPro: false },
  { id: 30, name: "Loan Tenure Calculator", slug: "loan-tenure-calculator", category: "Banking Tools", isPro: false },
  { id: 31, name: "Debt Snowball Calculator", slug: "debt-snowball-calculator", category: "Banking Tools", isPro: false },
  { id: 32, name: "Debt Avalanche Calculator", slug: "debt-avalanche-calculator", category: "Banking Tools", isPro: false },
  { id: 33, name: "Loan Prepayment Calculator", slug: "loan-prepayment-calculator", category: "Banking Tools", isPro: false },
  { id: 34, name: "Interest Rate Comparison Calculator", slug: "interest-rate-comparison-calculator", category: "Banking Tools", isPro: false },
  { id: 35, name: "EMI vs Interest Calculator", slug: "emi-vs-interest-calculator", category: "Banking Tools", isPro: false },
  { id: 36, name: "Overdraft Cost Calculator", slug: "overdraft-cost-calculator", category: "Banking Tools", isPro: false },
  { id: 37, name: "Account Fee Comparison Calculator", slug: "account-fee-comparison-calculator", category: "Banking Tools", isPro: false },
  { id: 38, name: "ATM Fee Calculator", slug: "atm-fee-calculator", category: "Banking Tools", isPro: false },
  { id: 39, name: "Bank Transfer Cost Calculator", slug: "bank-transfer-cost-calculator", category: "Banking Tools", isPro: false },
  { id: 40, name: "Wire Transfer Fee Calculator", slug: "wire-transfer-fee-calculator", category: "Banking Tools", isPro: false },
  { id: 41, name: "Foreign Exchange Fee Calculator", slug: "foreign-exchange-fee-calculator", category: "Banking Tools", isPro: false },
  { id: 42, name: "Currency Conversion Calculator", slug: "currency-conversion-calculator", category: "Banking Tools", isPro: false },
  { id: 43, name: "Inflation Impact Calculator", slug: "inflation-impact-calculator", category: "Banking Tools", isPro: false },
  { id: 44, name: "Purchasing Power Calculator", slug: "purchasing-power-calculator", category: "Banking Tools", isPro: false },
  { id: 45, name: "Bank Interest Rate Comparison", slug: "bank-interest-rate-comparison", category: "Banking Tools", isPro: false },
  { id: 46, name: "Savings Account Comparison", slug: "savings-account-comparison", category: "Banking Tools", isPro: false },
  { id: 47, name: "Checking Account Comparison", slug: "checking-account-comparison", category: "Banking Tools", isPro: false },
  { id: 48, name: "Deposit Account Comparison", slug: "deposit-account-comparison", category: "Banking Tools", isPro: false },
  { id: 49, name: "Loan Comparison Calculator", slug: "loan-comparison-calculator", category: "Banking Tools", isPro: false },
  { id: 50, name: "Bank Account Budget Planner", slug: "bank-account-budget-planner", category: "Banking Tools", isPro: false },
  { id: 51, name: "Monthly Cash Flow Planner", slug: "monthly-cash-flow-planner", category: "Banking Tools", isPro: false },
  { id: 52, name: "Bank Balance Forecast", slug: "bank-balance-forecast", category: "Banking Tools", isPro: false },
  { id: 53, name: "Savings Rate Calculator", slug: "savings-rate-calculator", category: "Banking Tools", isPro: false },
  { id: 54, name: "Financial Goal Timeline Calculator", slug: "financial-goal-timeline-calculator", category: "Banking Tools", isPro: false },
  { id: 55, name: "Deposit Ladder Calculator", slug: "deposit-ladder-calculator", category: "Banking Tools", isPro: false },
  { id: 56, name: "CD Ladder Calculator", slug: "cd-ladder-calculator", category: "Banking Tools", isPro: false },
  { id: 57, name: "Loan-to-Income Calculator", slug: "loan-to-income-calculator", category: "Banking Tools", isPro: false },
  { id: 58, name: "Payment-to-Income Calculator", slug: "payment-to-income-calculator", category: "Banking Tools", isPro: false },
  { id: 59, name: "Banking Checklist", slug: "banking-checklist", category: "Banking Tools", isPro: false },
  { id: 60, name: "Personal Banking Planner", slug: "personal-banking-planner", category: "Banking Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Personal Banking Dashboard", slug: "personal-banking-dashboard", category: "Banking Tools", isPro: true },
  { id: 62, name: "Bank Account Comparison Engine", slug: "bank-account-comparison-engine", category: "Banking Tools", isPro: true },
  { id: 63, name: "Savings Optimization Engine", slug: "savings-optimization-engine", category: "Banking Tools", isPro: true },
  { id: 64, name: "Deposit Optimization Tool", slug: "deposit-optimization-tool", category: "Banking Tools", isPro: true },
  { id: 65, name: "Interest Rate Intelligence Dashboard", slug: "interest-rate-intelligence-dashboard", category: "Banking Tools", isPro: true },
  { id: 66, name: "Loan Comparison Engine", slug: "loan-comparison-engine", category: "Banking Tools", isPro: true },
  { id: 67, name: "Loan Scenario Analyzer", slug: "loan-scenario-analyzer", category: "Banking Tools", isPro: true },
  { id: 68, name: "Debt Repayment Optimizer", slug: "debt-repayment-optimizer", category: "Banking Tools", isPro: true },
  { id: 69, name: "Debt Consolidation Analyzer", slug: "debt-consolidation-analyzer", category: "Banking Tools", isPro: true },
  { id: 70, name: "Refinancing Decision Engine", slug: "refinancing-decision-engine", category: "Banking Tools", isPro: true },
  { id: 71, name: "Cash Flow Forecasting Engine", slug: "cash-flow-forecasting-engine", category: "Banking Tools", isPro: true },
  { id: 72, name: "Savings Forecasting Engine", slug: "savings-forecasting-engine", category: "Banking Tools", isPro: true },
  { id: 73, name: "Financial Goal Planner", slug: "financial-goal-planner", category: "Banking Tools", isPro: true },
  { id: 74, name: "Emergency Fund Planner", slug: "emergency-fund-planner", category: "Banking Tools", isPro: true },
  { id: 75, name: "Deposit Ladder Planner", slug: "deposit-ladder-planner", category: "Banking Tools", isPro: true },
  { id: 76, name: "Interest Income Forecast", slug: "interest-income-forecast", category: "Banking Tools", isPro: true },
  { id: 77, name: "Banking Fee Analyzer", slug: "banking-fee-analyzer", category: "Banking Tools", isPro: true },
  { id: 78, name: "Bank Fee Optimization Tool", slug: "bank-fee-optimization-tool", category: "Banking Tools", isPro: true },
  { id: 79, name: "International Transfer Optimizer", slug: "international-transfer-optimizer", category: "Banking Tools", isPro: true },
  { id: 80, name: "FX Cost Analyzer", slug: "fx-cost-analyzer", category: "Banking Tools", isPro: true },
  { id: 81, name: "Banking Cost Comparison Workspace", slug: "banking-cost-comparison-workspace", category: "Banking Tools", isPro: true },
  { id: 82, name: "Loan Affordability Analyzer", slug: "loan-affordability-analyzer", category: "Banking Tools", isPro: true },
  { id: 83, name: "Borrowing Risk Analyzer", slug: "borrowing-risk-analyzer", category: "Banking Tools", isPro: true },
  { id: 84, name: "Repayment Stress Tester", slug: "repayment-stress-tester", category: "Banking Tools", isPro: true },
  { id: 85, name: "Interest Rate Stress Tester", slug: "interest-rate-stress-tester", category: "Banking Tools", isPro: true },
  { id: 86, name: "Household Banking Planner", slug: "household-banking-planner", category: "Banking Tools", isPro: true },
  { id: 87, name: "Personal Finance Banking Workspace", slug: "personal-finance-banking-workspace", category: "Banking Tools", isPro: true },
  { id: 88, name: "Small Business Banking Planner", slug: "small-business-banking-planner", category: "Banking Tools", isPro: true },
  { id: 89, name: "Business Cash Flow Workspace", slug: "business-cash-flow-workspace", category: "Banking Tools", isPro: true },
  { id: 90, name: "Business Loan Analyzer", slug: "business-loan-analyzer", category: "Banking Tools", isPro: true },
  { id: 91, name: "Treasury Cash Planner", slug: "treasury-cash-planner", category: "Banking Tools", isPro: true },
  { id: 92, name: "Multi-Account Cash Flow Dashboard", slug: "multi-account-cash-flow-dashboard", category: "Banking Tools", isPro: true },
  { id: 93, name: "Banking Scenario Workspace", slug: "banking-scenario-workspace", category: "Banking Tools", isPro: true },
  { id: 94, name: "Financial Planning Dashboard", slug: "financial-planning-dashboard", category: "Banking Tools", isPro: true },
  { id: 95, name: "Banking Intelligence Workspace", slug: "banking-intelligence-workspace", category: "Banking Tools", isPro: true },
  { id: 96, name: "Personal Financial Operations Center", slug: "personal-financial-operations-center", category: "Banking Tools", isPro: true },
  { id: 97, name: "Small Business Finance Command Center", slug: "small-business-finance-command-center", category: "Banking Tools", isPro: true },
  { id: 98, name: "Banking Decision Intelligence Platform", slug: "banking-decision-intelligence-platform", category: "Banking Tools", isPro: true },
  { id: 99, name: "Cash Management Intelligence Workspace", slug: "cash-management-intelligence-workspace", category: "Banking Tools", isPro: true },
  { id: 100, name: "Financial Banking Command Center", slug: "financial-banking-command-center", category: "Banking Tools", isPro: true }
];