export interface BookReadingTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const bookReadingToolsList: BookReadingTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "Reading Time Calculator", slug: "reading-time-calculator", category: "Book & Reading Tools", isPro: false },
  { id: 2, name: "Reading Speed Calculator", slug: "reading-speed-calculator", category: "Book & Reading Tools", isPro: false },
  { id: 3, name: "Daily Reading Goal Calculator", slug: "daily-reading-goal-calculator", category: "Book & Reading Tools", isPro: false },
  { id: 4, name: "Book Completion Calculator", slug: "book-completion-calculator", category: "Book & Reading Tools", isPro: false },
  { id: 5, name: "Books Per Year Calculator", slug: "books-per-year-calculator", category: "Book & Reading Tools", isPro: false },
  { id: 6, name: "Reading Progress Tracker", slug: "reading-progress-tracker", category: "Book & Reading Tools", isPro: false },
  { id: 7, name: "Book Tracker", slug: "book-tracker", category: "Book & Reading Tools", isPro: false },
  { id: 8, name: "Reading List Generator", slug: "reading-list-generator", category: "Book & Reading Tools", isPro: false },
  { id: 9, name: "Book Notes Organizer", slug: "book-notes-organizer", category: "Book & Reading Tools", isPro: false },
  { id: 10, name: "Citation Generator", slug: "citation-generator", category: "Book & Reading Tools", isPro: false },
  { id: 11, name: "ISBN Validator", slug: "isbn-validator", category: "Book & Reading Tools", isPro: false },
  { id: 12, name: "ISBN Lookup", slug: "isbn-lookup", category: "Book & Reading Tools", isPro: false },
  { id: 13, name: "Bibliography Formatter", slug: "bibliography-formatter", category: "Book & Reading Tools", isPro: false },
  { id: 14, name: "Book Comparison Tool", slug: "book-comparison-tool", category: "Book & Reading Tools", isPro: false },
  { id: 15, name: "Book Page Count Estimator", slug: "book-page-count-estimator", category: "Book & Reading Tools", isPro: false },
  { id: 16, name: "Reading Level Calculator", slug: "reading-level-calculator", category: "Book & Reading Tools", isPro: false },
  { id: 17, name: "Flesch Reading Ease Calculator", slug: "flesch-reading-ease-calculator", category: "Book & Reading Tools", isPro: false },
  { id: 18, name: "Book Price Calculator", slug: "book-price-calculator", category: "Book & Reading Tools", isPro: false },
  { id: 19, name: "Book Royalty Calculator", slug: "book-royalty-calculator", category: "Book & Reading Tools", isPro: false },
  { id: 20, name: "Personal Library Management Workspace", slug: "personal-library-management-workspace", category: "Book & Reading Tools", isPro: true },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Book Reading Time Calculator", slug: "book-reading-time-calculator", category: "Book & Reading Tools", isPro: false },
  { id: 22, name: "Words Per Minute Calculator", slug: "words-per-minute-calculator", category: "Book & Reading Tools", isPro: false },
  { id: 23, name: "Pages Per Hour Calculator", slug: "pages-per-hour-calculator", category: "Book & Reading Tools", isPro: false },
  { id: 24, name: "Reading Goal Calculator", slug: "reading-goal-calculator", category: "Book & Reading Tools", isPro: false },
  { id: 25, name: "Book Completion Date Calculator", slug: "book-completion-date-calculator", category: "Book & Reading Tools", isPro: false },
  { id: 26, name: "Annual Reading Goal Calculator", slug: "annual-reading-goal-calculator", category: "Book & Reading Tools", isPro: false },
  { id: 27, name: "Book Progress Tracker", slug: "book-progress-tracker", category: "Book & Reading Tools", isPro: false },
  { id: 28, name: "Reading Streak Tracker", slug: "reading-streak-tracker", category: "Book & Reading Tools", isPro: false },
  { id: 29, name: "Reading Challenge Tracker", slug: "reading-challenge-tracker", category: "Book & Reading Tools", isPro: false },
  { id: 30, name: "Book List Organizer", slug: "book-list-organizer", category: "Book & Reading Tools", isPro: false },
  { id: 31, name: "To-Be-Read List", slug: "to-be-read-list", category: "Book & Reading Tools", isPro: false },
  { id: 32, name: "Book Wishlist Organizer", slug: "book-wishlist-organizer", category: "Book & Reading Tools", isPro: false },
  { id: 33, name: "Reading Journal", slug: "reading-journal", category: "Book & Reading Tools", isPro: false },
  { id: 34, name: "Book Journal", slug: "book-journal", category: "Book & Reading Tools", isPro: false },
  { id: 35, name: "Quote Collection Organizer", slug: "quote-collection-organizer", category: "Book & Reading Tools", isPro: false },
  { id: 36, name: "Book Quote Formatter", slug: "book-quote-formatter", category: "Book & Reading Tools", isPro: false },
  { id: 37, name: "ISBN-10 to ISBN-13 Converter", slug: "isbn-10-to-isbn-13-converter", category: "Book & Reading Tools", isPro: false },
  { id: 38, name: "ISBN-13 to ISBN-10 Converter", slug: "isbn-13-to-isbn-10-converter", category: "Book & Reading Tools", isPro: false },
  { id: 39, name: "Book Metadata Formatter", slug: "book-metadata-formatter", category: "Book & Reading Tools", isPro: false },
  { id: 40, name: "Book Title Formatter", slug: "book-title-formatter", category: "Book & Reading Tools", isPro: false },
  { id: 41, name: "Author Name Formatter", slug: "author-name-formatter", category: "Book & Reading Tools", isPro: false },
  { id: 42, name: "Reference List Generator", slug: "reference-list-generator", category: "Book & Reading Tools", isPro: false },
  { id: 43, name: "Book Summary Workspace", slug: "book-summary-workspace", category: "Book & Reading Tools", isPro: false },
  { id: 44, name: "Chapter Summary Workspace", slug: "chapter-summary-workspace", category: "Book & Reading Tools", isPro: false },
  { id: 45, name: "Reading Notes Generator", slug: "reading-notes-generator", category: "Book & Reading Tools", isPro: false },
  { id: 46, name: "Book Length Calculator", slug: "book-length-calculator", category: "Book & Reading Tools", isPro: false },
  { id: 47, name: "Manuscript Word Count", slug: "manuscript-word-count", category: "Book & Reading Tools", isPro: false },
  { id: 48, name: "Manuscript Page Count", slug: "manuscript-page-count", category: "Book & Reading Tools", isPro: false },
  { id: 49, name: "Print Book Spine Calculator", slug: "print-book-spine-calculator", category: "Book & Reading Tools", isPro: false },
  { id: 50, name: "Book Formatting Checker", slug: "book-formatting-checker", category: "Book & Reading Tools", isPro: false },
  { id: 51, name: "eBook File Size Calculator", slug: "ebook-file-size-calculator", category: "Book & Reading Tools", isPro: false },
  { id: 52, name: "eBook Word Count Calculator", slug: "ebook-word-count-calculator", category: "Book & Reading Tools", isPro: false },
  { id: 53, name: "Flesch-Kincaid Calculator", slug: "flesch-kincaid-calculator", category: "Book & Reading Tools", isPro: false },
  { id: 54, name: "Gunning Fog Index Calculator", slug: "gunning-fog-index-calculator", category: "Book & Reading Tools", isPro: false },
  { id: 55, name: "SMOG Index Calculator", slug: "smog-index-calculator", category: "Book & Reading Tools", isPro: false },
  { id: 56, name: "Coleman-Liau Index Calculator", slug: "coleman-liau-index-calculator", category: "Book & Reading Tools", isPro: false },
  { id: 57, name: "Automated Readability Index", slug: "automated-readability-index", category: "Book & Reading Tools", isPro: false },
  { id: 58, name: "Publishing Cost Calculator", slug: "publishing-cost-calculator", category: "Book & Reading Tools", isPro: false },
  { id: 59, name: "Book Break-Even Calculator", slug: "book-break-even-calculator", category: "Book & Reading Tools", isPro: false },
  { id: 60, name: "Reading Schedule Planner", slug: "reading-schedule-planner", category: "Book & Reading Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Book Club Planner", slug: "book-club-planner", category: "Book & Reading Tools", isPro: true },
  { id: 62, name: "Digital Library Dashboard", slug: "digital-library-dashboard", category: "Book & Reading Tools", isPro: true },
  { id: 63, name: "Reading Analytics Dashboard", slug: "reading-analytics-dashboard", category: "Book & Reading Tools", isPro: true },
  { id: 64, name: "Reading Habit Analytics", slug: "reading-habit-analytics", category: "Book & Reading Tools", isPro: true },
  { id: 65, name: "Book Recommendation Workspace", slug: "book-recommendation-workspace", category: "Book & Reading Tools", isPro: true },
  { id: 66, name: "Reading Goal Optimization", slug: "reading-goal-optimization", category: "Book & Reading Tools", isPro: true },
  { id: 67, name: "Annual Reading Planner", slug: "annual-reading-planner", category: "Book & Reading Tools", isPro: true },
  { id: 68, name: "Multi-Book Reading Planner", slug: "multi-book-reading-planner", category: "Book & Reading Tools", isPro: true },
  { id: 69, name: "Research Reading Workspace", slug: "research-reading-workspace", category: "Book & Reading Tools", isPro: true },
  { id: 70, name: "Academic Reading Workspace", slug: "academic-reading-workspace", category: "Book & Reading Tools", isPro: true },
  { id: 71, name: "Literature Review Workspace", slug: "literature-review-workspace", category: "Book & Reading Tools", isPro: true },
  { id: 72, name: "Citation Management Workspace", slug: "citation-management-workspace", category: "Book & Reading Tools", isPro: true },
  { id: 73, name: "Bibliography Management Workspace", slug: "bibliography-management-workspace", category: "Book & Reading Tools", isPro: true },
  { id: 74, name: "Reference Database Workspace", slug: "reference-database-workspace", category: "Book & Reading Tools", isPro: true },
  { id: 75, name: "ISBN Database Workspace", slug: "isbn-database-workspace", category: "Book & Reading Tools", isPro: true },
  { id: 76, name: "Book Metadata Management", slug: "book-metadata-management", category: "Book & Reading Tools", isPro: true },
  { id: 77, name: "Author Research Workspace", slug: "author-research-workspace", category: "Book & Reading Tools", isPro: true },
  { id: 78, name: "Book Comparison Dashboard", slug: "book-comparison-dashboard", category: "Book & Reading Tools", isPro: true },
  { id: 79, name: "Book Notes Intelligence Workspace", slug: "book-notes-intelligence-workspace", category: "Book & Reading Tools", isPro: true },
  { id: 80, name: "Reading Notes Analytics", slug: "reading-notes-analytics", category: "Book & Reading Tools", isPro: true },
  { id: 81, name: "Manuscript Analysis Workspace", slug: "manuscript-analysis-workspace", category: "Book & Reading Tools", isPro: true },
  { id: 82, name: "Book Formatting Workspace", slug: "book-formatting-workspace", category: "Book & Reading Tools", isPro: true },
  { id: 83, name: "Publishing Cost Workspace", slug: "publishing-cost-workspace", category: "Book & Reading Tools", isPro: true },
  { id: 84, name: "Book Pricing Workspace", slug: "book-pricing-workspace", category: "Book & Reading Tools", isPro: true },
  { id: 85, name: "Royalty Analytics Dashboard", slug: "royalty-analytics-dashboard", category: "Book & Reading Tools", isPro: true },
  { id: 86, name: "Publishing Revenue Calculator", slug: "publishing-revenue-calculator", category: "Book & Reading Tools", isPro: true },
  { id: 87, name: "Book Sales Break-Even Analyzer", slug: "book-sales-break-even-analyzer", category: "Book & Reading Tools", isPro: true },
  { id: 88, name: "Book Portfolio Dashboard", slug: "book-portfolio-dashboard", category: "Book & Reading Tools", isPro: true },
  { id: 89, name: "Reading Challenge Management", slug: "reading-challenge-management", category: "Book & Reading Tools", isPro: true },
  { id: 90, name: "Book Club Management Workspace", slug: "book-club-management-workspace", category: "Book & Reading Tools", isPro: true },
  { id: 91, name: "Library Inventory Analyzer", slug: "library-inventory-analyzer", category: "Book & Reading Tools", isPro: true },
  { id: 92, name: "Library CSV Importer", slug: "library-csv-importer", category: "Book & Reading Tools", isPro: true },
  { id: 93, name: "Library Data Cleaner", slug: "library-data-cleaner", category: "Book & Reading Tools", isPro: true },
  { id: 94, name: "Library Data Exporter", slug: "library-data-exporter", category: "Book & Reading Tools", isPro: true },
  { id: 95, name: "Reading API Workspace", slug: "reading-api-workspace", category: "Book & Reading Tools", isPro: true },
  { id: 96, name: "Book Data API", slug: "book-data-api", category: "Book & Reading Tools", isPro: true },
  { id: 97, name: "Professional Publishing Dashboard", slug: "professional-publishing-dashboard", category: "Book & Reading Tools", isPro: true },
  { id: 98, name: "Author Business Workspace", slug: "author-business-workspace", category: "Book & Reading Tools", isPro: true },
  { id: 99, name: "Book Intelligence Platform", slug: "book-intelligence-platform", category: "Book & Reading Tools", isPro: true },
  { id: 100, name: "Professional Library Command Center", slug: "professional-library-command-center", category: "Book & Reading Tools", isPro: true }
];