export interface BusinessIntelligenceTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const businessIntelligenceToolsList: BusinessIntelligenceTool[] = [
  // --- 🔥 PRIORITY 20 FREE TOOLS (IDs 1-20 | isPro: false) ---
  { id: 1, name: "KPI Calculator", slug: "kpi-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 2, name: "KPI Variance Calculator", slug: "kpi-variance-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 3, name: "Revenue Growth Calculator", slug: "revenue-growth-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 4, name: "Gross Margin Analyzer", slug: "gross-margin-analyzer", category: "Business Intelligence Tools", isPro: false },
  { id: 5, name: "Budget Variance Calculator", slug: "budget-variance-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 6, name: "Sales Target Calculator", slug: "sales-target-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 7, name: "Sales Conversion Calculator", slug: "sales-conversion-calculator-bi", category: "Business Intelligence Tools", isPro: false },
  { id: 8, name: "Customer Retention Calculator", slug: "customer-retention-calculator-bi", category: "Business Intelligence Tools", isPro: false },
  { id: 9, name: "Customer Acquisition Cost Calculator", slug: "customer-acquisition-cost-calculator-bi", category: "Business Intelligence Tools", isPro: false },
  { id: 10, name: "Customer Lifetime Value Calculator", slug: "customer-lifetime-value-calculator-bi", category: "Business Intelligence Tools", isPro: false },
  { id: 11, name: "Inventory Turnover Calculator", slug: "inventory-turnover-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 12, name: "Revenue Per Employee Calculator", slug: "revenue-per-employee-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 13, name: "Capacity Utilization Calculator", slug: "capacity-utilization-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 14, name: "Operational Efficiency Calculator", slug: "operational-efficiency-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 15, name: "SLA Compliance Calculator", slug: "sla-compliance-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 16, name: "Forecast Accuracy Calculator", slug: "forecast-accuracy-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 17, name: "Scenario Comparison Calculator", slug: "scenario-comparison-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 18, name: "Profit Growth Calculator", slug: "profit-growth-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 19, name: "Average Order Value Calculator", slug: "average-order-value-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 20, name: "Business Growth Rate Calculator", slug: "business-growth-rate-calculator", category: "Business Intelligence Tools", isPro: false },

  // --- REMAINING 40 CORE FREE TOOLS (IDs 21-60 | isPro: false) ---
  { id: 21, name: "KPI Target Calculator", slug: "kpi-target-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 22, name: "KPI Growth Calculator", slug: "kpi-growth-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 23, name: "KPI Achievement Calculator", slug: "kpi-achievement-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 24, name: "Revenue Variance Calculator", slug: "revenue-variance-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 25, name: "Operating Margin Analyzer", slug: "operating-margin-analyzer", category: "Business Intelligence Tools", isPro: false },
  { id: 26, name: "EBITDA Margin Calculator", slug: "ebitda-margin-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 27, name: "Cost Variance Calculator", slug: "cost-variance-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 28, name: "Forecast Variance Calculator", slug: "forecast-variance-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 29, name: "Sales Growth Calculator", slug: "sales-growth-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 30, name: "Sales Achievement Calculator", slug: "sales-achievement-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 31, name: "Lead Conversion Calculator", slug: "lead-conversion-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 32, name: "Customer Growth Calculator", slug: "customer-growth-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 33, name: "Customer Churn Analyzer", slug: "customer-churn-analyzer", category: "Business Intelligence Tools", isPro: false },
  { id: 34, name: "Revenue Per Customer Calculator", slug: "revenue-per-customer-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 35, name: "Asset Turnover Calculator", slug: "asset-turnover-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 36, name: "Employee Productivity Calculator", slug: "employee-productivity-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 37, name: "Cost Per Employee Calculator", slug: "cost-per-employee-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 38, name: "Utilization Rate Calculator", slug: "utilization-rate-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 39, name: "Productivity Rate Calculator", slug: "productivity-rate-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 40, name: "Process Cycle Time Calculator", slug: "process-cycle-time-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 41, name: "Service Level Calculator", slug: "service-level-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 42, name: "On-Time Delivery Rate Calculator", slug: "on-time-delivery-rate-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 43, name: "Defect Rate Calculator", slug: "defect-rate-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 44, name: "Return Rate Calculator", slug: "return-rate-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 45, name: "Refund Rate Calculator", slug: "refund-rate-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 46, name: "Customer Satisfaction Score Calculator", slug: "customer-satisfaction-score-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 47, name: "NPS Calculator", slug: "nps-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 48, name: "CSAT Calculator", slug: "csat-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 49, name: "Survey Response Rate Calculator", slug: "survey-response-rate-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 50, name: "Budget Accuracy Calculator", slug: "budget-accuracy-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 51, name: "Compound Business Growth Calculator", slug: "compound-business-growth-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 52, name: "What-If Analysis Calculator", slug: "what-if-analysis-calculator", category: "Business Intelligence Tools", isPro: false },
  { id: 53, name: "Business Dashboard KPI List Generator", slug: "business-dashboard-kpi-list-generator", category: "Business Intelligence Tools", isPro: false },
  { id: 54, name: "KPI Definition Generator", slug: "kpi-definition-generator", category: "Business Intelligence Tools", isPro: false },
  { id: 55, name: "KPI Report Template Generator", slug: "kpi-report-template-generator", category: "Business Intelligence Tools", isPro: false },
  { id: 56, name: "Executive Summary Generator", slug: "executive-summary-generator-bi", category: "Business Intelligence Tools", isPro: false },
  { id: 57, name: "Business Report Outline Generator", slug: "business-report-outline-generator", category: "Business Intelligence Tools", isPro: false },
  { id: 58, name: "Management Report Generator", slug: "management-report-generator", category: "Business Intelligence Tools", isPro: false },
  { id: 59, name: "KPI Tracking Sheet Generator", slug: "kpi-tracking-sheet-generator", category: "Business Intelligence Tools", isPro: false },
  { id: 60, name: "Business Metrics Dictionary", slug: "business-metrics-dictionary", category: "Business Intelligence Tools", isPro: false },

  // --- ⚡ 40 PRO / SAAS TOOLS (IDs 61-100 | isPro: true) ---
  { id: 61, name: "Business Intelligence Dashboard", slug: "business-intelligence-dashboard", category: "Business Intelligence Tools", isPro: true },
  { id: 62, name: "Executive Dashboard", slug: "executive-dashboard", category: "Business Intelligence Tools", isPro: true },
  { id: 63, name: "KPI Management Workspace", slug: "kpi-management-workspace", category: "Business Intelligence Tools", isPro: true },
  { id: 64, name: "Business Performance Dashboard", slug: "business-performance-dashboard", category: "Business Intelligence Tools", isPro: true },
  { id: 65, name: "Revenue Intelligence Dashboard", slug: "revenue-intelligence-dashboard", category: "Business Intelligence Tools", isPro: true },
  { id: 66, name: "Profitability Intelligence Workspace", slug: "profitability-intelligence-workspace", category: "Business Intelligence Tools", isPro: true },
  { id: 67, name: "Sales Intelligence Dashboard", slug: "sales-intelligence-dashboard", category: "Business Intelligence Tools", isPro: true },
  { id: 68, name: "Customer Intelligence Dashboard", slug: "customer-intelligence-dashboard", category: "Business Intelligence Tools", isPro: true },
  { id: 69, name: "Operations Intelligence Dashboard", slug: "operations-intelligence-dashboard", category: "Business Intelligence Tools", isPro: true },
  { id: 70, name: "Workforce Intelligence Dashboard", slug: "workforce-intelligence-dashboard", category: "Business Intelligence Tools", isPro: true },
  { id: 71, name: "Financial Performance Dashboard", slug: "financial-performance-dashboard", category: "Business Intelligence Tools", isPro: true },
  { id: 72, name: "Budget Intelligence Workspace", slug: "budget-intelligence-workspace", category: "Business Intelligence Tools", isPro: true },
  { id: 73, name: "Forecasting Workspace", slug: "forecasting-workspace", category: "Business Intelligence Tools", isPro: true },
  { id: 74, name: "Scenario Planning Workspace", slug: "scenario-planning-workspace", category: "Business Intelligence Tools", isPro: true },
  { id: 75, name: "What-If Analysis Workspace", slug: "what-if-analysis-workspace", category: "Business Intelligence Tools", isPro: true },
  { id: 76, name: "Business Planning Workspace", slug: "business-planning-workspace", category: "Business Intelligence Tools", isPro: true },
  { id: 77, name: "KPI Monitoring Workspace", slug: "kpi-monitoring-workspace", category: "Business Intelligence Tools", isPro: true },
  { id: 78, name: "KPI Alert Engine", slug: "kpi-alert-engine", category: "Business Intelligence Tools", isPro: true },
  { id: 79, name: "KPI Benchmarking Workspace", slug: "kpi-benchmarking-workspace", category: "Business Intelligence Tools", isPro: true },
  { id: 80, name: "Business Benchmarking Dashboard", slug: "business-benchmarking-dashboard", category: "Business Intelligence Tools", isPro: true },
  { id: 81, name: "Department Performance Dashboard", slug: "department-performance-dashboard", category: "Business Intelligence Tools", isPro: true },
  { id: 82, name: "Multi-Department Analytics", slug: "multi-department-analytics", category: "Business Intelligence Tools", isPro: true },
  { id: 83, name: "Multi-Location Business Dashboard", slug: "multi-location-business-dashboard", category: "Business Intelligence Tools", isPro: true },
  { id: 84, name: "Executive Reporting Workspace", slug: "executive-reporting-workspace", category: "Business Intelligence Tools", isPro: true },
  { id: 85, name: "Automated Management Reporting", slug: "automated-management-reporting", category: "Business Intelligence Tools", isPro: true },
  { id: 86, name: "Business Data Import Workspace", slug: "business-data-import-workspace", category: "Business Intelligence Tools", isPro: true },
  { id: 87, name: "Business Data Cleaning Workspace", slug: "business-data-cleaning-workspace", category: "Business Intelligence Tools", isPro: true },
  { id: 88, name: "Business Data Transformation Workspace", slug: "business-data-transformation-workspace", category: "Business Intelligence Tools", isPro: true },
  { id: 89, name: "Business Metrics Modeling Workspace", slug: "business-metrics-modeling-workspace", category: "Business Intelligence Tools", isPro: true },
  { id: 90, name: "Business Analytics Report Builder", slug: "business-analytics-report-builder", category: "Business Intelligence Tools", isPro: true },
  { id: 91, name: "BI Data Visualization Workspace", slug: "bi-data-visualization-workspace", category: "Business Intelligence Tools", isPro: true },
  { id: 92, name: "BI Query Workspace", slug: "bi-query-workspace", category: "Business Intelligence Tools", isPro: true },
  { id: 93, name: "Business Intelligence API", slug: "business-intelligence-api", category: "Business Intelligence Tools", isPro: true },
  { id: 94, name: "Data Warehouse KPI Workspace", slug: "data-warehouse-kpi-workspace", category: "Business Intelligence Tools", isPro: true },
  { id: 95, name: "Business Intelligence Automation", slug: "business-intelligence-automation", category: "Business Intelligence Tools", isPro: true },
  { id: 96, name: "Business Alert & Notification Engine", slug: "business-alert-notification-engine", category: "Business Intelligence Tools", isPro: true },
  { id: 97, name: "Enterprise Analytics Workspace", slug: "enterprise-analytics-workspace", category: "Business Intelligence Tools", isPro: true },
  { id: 98, name: "Business Intelligence SaaS Platform", slug: "business-intelligence-saas-platform", category: "Business Intelligence Tools", isPro: true },
  { id: 99, name: "Decision Intelligence Platform", slug: "decision-intelligence-platform", category: "Business Intelligence Tools", isPro: true },
  { id: 100, name: "Enterprise Business Command Center", slug: "enterprise-business-command-center", category: "Business Intelligence Tools", isPro: true }
];