export interface BusinessTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const businessToolsList: BusinessTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "Business Name Generator", slug: "business-name-generator", category: "Business Tools", isPro: false },
  { id: 2, name: "Slogan Generator", slug: "slogan-generator", category: "Business Tools", isPro: false },
  { id: 3, name: "Mission Statement Generator", slug: "mission-statement-generator", category: "Business Tools", isPro: false },
  { id: 4, name: "Vision Statement Generator", slug: "vision-statement-generator", category: "Business Tools", isPro: false },
  { id: 5, name: "Value Proposition Generator", slug: "value-proposition-generator", category: "Business Tools", isPro: false },
  { id: 6, name: "Business Plan Generator", slug: "business-plan-generator", category: "Business Tools", isPro: false },
  { id: 7, name: "Executive Summary Generator", slug: "executive-summary-generator", category: "Business Tools", isPro: false },
  { id: 8, name: "SWOT Analysis Generator", slug: "swot-analysis-generator", category: "Business Tools", isPro: false },
  { id: 9, name: "PESTLE Analysis Generator", slug: "pestle-analysis-generator", category: "Business Tools", isPro: false },
  { id: 10, name: "Business Model Canvas Generator", slug: "business-model-canvas-generator", category: "Business Tools", isPro: false },
  { id: 11, name: "Lean Canvas Generator", slug: "lean-canvas-generator", category: "Business Tools", isPro: false },
  { id: 12, name: "Profit Margin Calculator", slug: "profit-margin-calculator-business", category: "Business Tools", isPro: false },
  { id: 13, name: "Markup Calculator", slug: "markup-calculator", category: "Business Tools", isPro: false },
  { id: 14, name: "Break-Even Calculator", slug: "break-even-calculator-business", category: "Business Tools", isPro: false },
  { id: 15, name: "ROI Calculator", slug: "roi-calculator-business", category: "Business Tools", isPro: false },
  { id: 16, name: "Customer Acquisition Cost Calculator", slug: "customer-acquisition-cost-calculator", category: "Business Tools", isPro: false },
  { id: 17, name: "Customer Lifetime Value Calculator", slug: "customer-lifetime-value-calculator", category: "Business Tools", isPro: false },
  { id: 18, name: "Churn Rate Calculator", slug: "churn-rate-calculator-business", category: "Business Tools", isPro: false },
  { id: 19, name: "Burn Rate Calculator", slug: "burn-rate-calculator", category: "Business Tools", isPro: false },
  { id: 20, name: "Runway Calculator", slug: "runway-calculator", category: "Business Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Startup Idea Generator", slug: "startup-idea-generator", category: "Business Tools", isPro: false },
  { id: 22, name: "Target Audience Generator", slug: "target-audience-generator", category: "Business Tools", isPro: false },
  { id: 23, name: "Buyer Persona Generator", slug: "buyer-persona-generator", category: "Business Tools", isPro: false },
  { id: 24, name: "Competitor Analysis Generator", slug: "competitor-analysis-generator", category: "Business Tools", isPro: false },
  { id: 25, name: "Market Research Generator", slug: "market-research-generator", category: "Business Tools", isPro: false },
  { id: 26, name: "Elevator Pitch Generator", slug: "elevator-pitch-generator", category: "Business Tools", isPro: false },
  { id: 27, name: "Pitch Deck Outline Generator", slug: "pitch-deck-outline-generator", category: "Business Tools", isPro: false },
  { id: 28, name: "Brand Voice Generator", slug: "brand-voice-generator", category: "Business Tools", isPro: false },
  { id: 29, name: "Brand Story Generator", slug: "brand-story-generator", category: "Business Tools", isPro: false },
  { id: 30, name: "Company Bio Generator", slug: "company-bio-generator", category: "Business Tools", isPro: false },
  { id: 31, name: "About Us Page Generator", slug: "about-us-page-generator-business", category: "Business Tools", isPro: false },
  { id: 32, name: "Founder Bio Generator", slug: "founder-bio-generator", category: "Business Tools", isPro: false },
  { id: 33, name: "Press Release Generator", slug: "press-release-generator-business", category: "Business Tools", isPro: false },
  { id: 34, name: "Job Description Generator", slug: "job-description-generator-business", category: "Business Tools", isPro: false },
  { id: 35, name: "Offer Letter Generator", slug: "offer-letter-generator", category: "Business Tools", isPro: false },
  { id: 36, name: "Resignation Letter Generator", slug: "resignation-letter-generator", category: "Business Tools", isPro: false },
  { id: 37, name: "Termination Letter Generator", slug: "termination-letter-generator", category: "Business Tools", isPro: false },
  { id: 38, name: "Recommendation Letter Generator", slug: "recommendation-letter-generator", category: "Business Tools", isPro: false },
  { id: 39, name: "Performance Review Generator", slug: "performance-review-generator", category: "Business Tools", isPro: false },
  { id: 40, name: "Employee Handbook Outline Generator", slug: "employee-handbook-outline-generator", category: "Business Tools", isPro: false },
  { id: 41, name: "Company Policy Generator", slug: "company-policy-generator", category: "Business Tools", isPro: false },
  { id: 42, name: "Standard Operating Procedure Generator", slug: "sop-generator", category: "Business Tools", isPro: false },
  { id: 43, name: "Meeting Agenda Generator", slug: "meeting-agenda-generator-business", category: "Business Tools", isPro: false },
  { id: 44, name: "Meeting Minutes Generator", slug: "meeting-minutes-generator-business", category: "Business Tools", isPro: false },
  { id: 45, name: "Memo Generator", slug: "memo-generator", category: "Business Tools", isPro: false },
  { id: 46, name: "Business Proposal Generator", slug: "business-proposal-generator", category: "Business Tools", isPro: false },
  { id: 47, name: "Invoice Generator", slug: "invoice-generator-business", category: "Business Tools", isPro: false },
  { id: 48, name: "Receipt Generator", slug: "receipt-generator", category: "Business Tools", isPro: false },
  { id: 49, name: "Purchase Order Generator", slug: "purchase-order-generator", category: "Business Tools", isPro: false },
  { id: 50, name: "Quote Generator", slug: "quote-generator", category: "Business Tools", isPro: false },
  { id: 51, name: "Estimate Generator", slug: "estimate-generator", category: "Business Tools", isPro: false },
  { id: 52, name: "Business Card Generator", slug: "business-card-generator", category: "Business Tools", isPro: false },
  { id: 53, name: "Letterhead Generator", slug: "letterhead-generator", category: "Business Tools", isPro: false },
  { id: 54, name: "Envelope Generator", slug: "envelope-generator", category: "Business Tools", isPro: false },
  { id: 55, name: "Fax Cover Sheet Generator", slug: "fax-cover-sheet-generator", category: "Business Tools", isPro: false },
  { id: 56, name: "Non-Disclosure Agreement Generator", slug: "nda-generator", category: "Business Tools", isPro: false },
  { id: 57, name: "Independent Contractor Agreement Generator", slug: "contractor-agreement-generator", category: "Business Tools", isPro: false },
  { id: 58, name: "Partnership Agreement Generator", slug: "partnership-agreement-generator", category: "Business Tools", isPro: false },
  { id: 59, name: "Terms of Service Generator", slug: "tos-generator", category: "Business Tools", isPro: false },
  { id: 60, name: "Privacy Policy Generator", slug: "privacy-policy-generator", category: "Business Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Comprehensive Business Plan Builder", slug: "comprehensive-business-plan-builder", category: "Business Tools", isPro: true },
  { id: 62, name: "Financial Projection Generator", slug: "financial-projection-generator", category: "Business Tools", isPro: true },
  { id: 63, name: "Cap Table Calculator", slug: "cap-table-calculator", category: "Business Tools", isPro: true },
  { id: 64, name: "Valuation Calculator", slug: "valuation-calculator", category: "Business Tools", isPro: true },
  { id: 65, name: "Equity Dilution Calculator", slug: "equity-dilution-calculator", category: "Business Tools", isPro: true },
  { id: 66, name: "Employee Stock Option Plan Generator", slug: "esop-generator", category: "Business Tools", isPro: true },
  { id: 67, name: "Vesting Schedule Generator", slug: "vesting-schedule-generator", category: "Business Tools", isPro: true },
  { id: 68, name: "Term Sheet Generator", slug: "term-sheet-generator", category: "Business Tools", isPro: true },
  { id: 69, name: "Convertible Note Generator", slug: "convertible-note-generator", category: "Business Tools", isPro: true },
  { id: 70, name: "SAFE Agreement Generator", slug: "safe-agreement-generator", category: "Business Tools", isPro: true },
  { id: 71, name: "Board Resolution Generator", slug: "board-resolution-generator", category: "Business Tools", isPro: true },
  { id: 72, name: "Shareholder Agreement Generator", slug: "shareholder-agreement-generator", category: "Business Tools", isPro: true },
  { id: 73, name: "Operating Agreement Generator", slug: "operating-agreement-generator", category: "Business Tools", isPro: true },
  { id: 74, name: "Bylaws Generator", slug: "bylaws-generator", category: "Business Tools", isPro: true },
  { id: 75, name: "Articles of Incorporation Generator", slug: "articles-of-incorporation-generator", category: "Business Tools", isPro: true },
  { id: 76, name: "Memorandum of Understanding Generator", slug: "mou-generator", category: "Business Tools", isPro: true },
  { id: 77, name: "Letter of Intent Generator", slug: "loi-generator", category: "Business Tools", isPro: true },
  { id: 78, name: "Joint Venture Agreement Generator", slug: "joint-venture-agreement-generator", category: "Business Tools", isPro: true },
  { id: 79, name: "Franchise Agreement Generator", slug: "franchise-agreement-generator", category: "Business Tools", isPro: true },
  { id: 80, name: "Licensing Agreement Generator", slug: "licensing-agreement-generator", category: "Business Tools", isPro: true },
  { id: 81, name: "Distribution Agreement Generator", slug: "distribution-agreement-generator", category: "Business Tools", isPro: true },
  { id: 82, name: "Manufacturing Agreement Generator", slug: "manufacturing-agreement-generator", category: "Business Tools", isPro: true },
  { id: 83, name: "Supply Agreement Generator", slug: "supply-agreement-generator", category: "Business Tools", isPro: true },
  { id: 84, name: "Service Level Agreement Generator", slug: "sla-generator", category: "Business Tools", isPro: true },
  { id: 85, name: "Master Service Agreement Generator", slug: "msa-generator", category: "Business Tools", isPro: true },
  { id: 86, name: "Statement of Work Generator", slug: "sow-generator", category: "Business Tools", isPro: true },
  { id: 87, name: "Software License Agreement Generator", slug: "software-license-agreement-generator", category: "Business Tools", isPro: true },
  { id: 88, name: "End User License Agreement Generator", slug: "eula-generator", category: "Business Tools", isPro: true },
  { id: 89, name: "Affiliate Agreement Generator", slug: "affiliate-agreement-generator", category: "Business Tools", isPro: true },
  { id: 90, name: "Referral Agreement Generator", slug: "referral-agreement-generator", category: "Business Tools", isPro: true },
  { id: 91, name: "Sponsorship Agreement Generator", slug: "sponsorship-agreement-generator", category: "Business Tools", isPro: true },
  { id: 92, name: "Influencer Agreement Generator", slug: "influencer-agreement-generator", category: "Business Tools", isPro: true },
  { id: 93, name: "Brand Ambassador Agreement Generator", slug: "brand-ambassador-agreement-generator", category: "Business Tools", isPro: true },
  { id: 94, name: "Guest Blogger Agreement Generator", slug: "guest-blogger-agreement-generator", category: "Business Tools", isPro: true },
  { id: 95, name: "Content Creator Agreement Generator", slug: "content-creator-agreement-generator", category: "Business Tools", isPro: true },
  { id: 96, name: "Podcast Guest Agreement Generator", slug: "podcast-guest-agreement-generator", category: "Business Tools", isPro: true },
  { id: 97, name: "Photography Agreement Generator", slug: "photography-agreement-generator", category: "Business Tools", isPro: true },
  { id: 98, name: "Videography Agreement Generator", slug: "videography-agreement-generator", category: "Business Tools", isPro: true },
  { id: 99, name: "Graphic Design Agreement Generator", slug: "graphic-design-agreement-generator", category: "Business Tools", isPro: true },
  { id: 100, name: "Web Development Agreement Generator", slug: "web-development-agreement-generator", category: "Business Tools", isPro: true }
];