export interface CameraPhotoTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const cameraPhotoToolsList: CameraPhotoTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "Image Compressor", slug: "image-compressor", category: "Camera & Photo Tools", isPro: false },
  { id: 2, name: "Image Resizer", slug: "image-resizer", category: "Camera & Photo Tools", isPro: false },
  { id: 3, name: "Image Cropper", slug: "image-cropper", category: "Camera & Photo Tools", isPro: false },
  { id: 4, name: "Image Format Converter", slug: "image-format-converter", category: "Camera & Photo Tools", isPro: false },
  { id: 5, name: "WebP Converter", slug: "webp-converter", category: "Camera & Photo Tools", isPro: false },
  { id: 6, name: "HEIC to JPG Converter", slug: "heic-to-jpg-converter", category: "Camera & Photo Tools", isPro: false },
  { id: 7, name: "Image DPI Checker", slug: "image-dpi-checker", category: "Camera & Photo Tools", isPro: false },
  { id: 8, name: "Passport Photo Maker", slug: "passport-photo-maker", category: "Camera & Photo Tools", isPro: false },
  { id: 9, name: "Social Media Image Resizer", slug: "social-media-image-resizer", category: "Camera & Photo Tools", isPro: false },
  { id: 10, name: "Image Background Remover", slug: "image-background-remover", category: "Camera & Photo Tools", isPro: false },
  { id: 11, name: "Image Watermark Tool", slug: "image-watermark-tool", category: "Camera & Photo Tools", isPro: false },
  { id: 12, name: "EXIF Viewer", slug: "exif-viewer", category: "Camera & Photo Tools", isPro: false },
  { id: 13, name: "EXIF Cleaner", slug: "exif-cleaner", category: "Camera & Photo Tools", isPro: false },
  { id: 14, name: "GPS Metadata Remover", slug: "gps-metadata-remover", category: "Camera & Photo Tools", isPro: false },
  { id: 15, name: "Image Quality Checker", slug: "image-quality-checker", category: "Camera & Photo Tools", isPro: false },
  { id: 16, name: "Aspect Ratio Calculator", slug: "aspect-ratio-calculator", category: "Camera & Photo Tools", isPro: false },
  { id: 17, name: "Print Size Calculator", slug: "print-size-calculator", category: "Camera & Photo Tools", isPro: false },
  { id: 18, name: "Image Color Picker", slug: "image-color-picker", category: "Camera & Photo Tools", isPro: false },
  { id: 19, name: "Image Blur Tool", slug: "image-blur-tool", category: "Camera & Photo Tools", isPro: false },
  { id: 20, name: "Image Rotator", slug: "image-rotator", category: "Camera & Photo Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Image Flipper", slug: "image-flipper", category: "Camera & Photo Tools", isPro: false },
  { id: 22, name: "JPG Converter", slug: "jpg-converter", category: "Camera & Photo Tools", isPro: false },
  { id: 23, name: "PNG Converter", slug: "png-converter", category: "Camera & Photo Tools", isPro: false },
  { id: 24, name: "AVIF Converter", slug: "avif-converter", category: "Camera & Photo Tools", isPro: false },
  { id: 25, name: "HEIC Converter", slug: "heic-converter", category: "Camera & Photo Tools", isPro: false },
  { id: 26, name: "TIFF Converter", slug: "tiff-converter", category: "Camera & Photo Tools", isPro: false },
  { id: 27, name: "BMP Converter", slug: "bmp-converter", category: "Camera & Photo Tools", isPro: false },
  { id: 28, name: "JPG to PNG Converter", slug: "jpg-to-png-converter", category: "Camera & Photo Tools", isPro: false },
  { id: 29, name: "PNG to JPG Converter", slug: "png-to-jpg-converter", category: "Camera & Photo Tools", isPro: false },
  { id: 30, name: "WebP to JPG Converter", slug: "webp-to-jpg-converter", category: "Camera & Photo Tools", isPro: false },
  { id: 31, name: "HEIC to PNG Converter", slug: "heic-to-png-converter", category: "Camera & Photo Tools", isPro: false },
  { id: 32, name: "Image Resolution Checker", slug: "image-resolution-checker", category: "Camera & Photo Tools", isPro: false },
  { id: 33, name: "Image Dimensions Checker", slug: "image-dimensions-checker", category: "Camera & Photo Tools", isPro: false },
  { id: 34, name: "DPI Calculator", slug: "dpi-calculator", category: "Camera & Photo Tools", isPro: false },
  { id: 35, name: "Image File Size Calculator", slug: "image-file-size-calculator", category: "Camera & Photo Tools", isPro: false },
  { id: 36, name: "Image Aspect Ratio Converter", slug: "image-aspect-ratio-converter", category: "Camera & Photo Tools", isPro: false },
  { id: 37, name: "ID Photo Maker", slug: "id-photo-maker", category: "Camera & Photo Tools", isPro: false },
  { id: 38, name: "Profile Picture Resizer", slug: "profile-picture-resizer", category: "Camera & Photo Tools", isPro: false },
  { id: 39, name: "Website Image Resizer", slug: "website-image-resizer", category: "Camera & Photo Tools", isPro: false },
  { id: 40, name: "Favicon Image Generator", slug: "favicon-image-generator", category: "Camera & Photo Tools", isPro: false },
  { id: 41, name: "Image Background Changer", slug: "image-background-changer", category: "Camera & Photo Tools", isPro: false },
  { id: 42, name: "Image Color Extractor", slug: "image-color-extractor", category: "Camera & Photo Tools", isPro: false },
  { id: 43, name: "Image Palette Generator", slug: "image-palette-generator", category: "Camera & Photo Tools", isPro: false },
  { id: 44, name: "Image Sharpen Tool", slug: "image-sharpen-tool", category: "Camera & Photo Tools", isPro: false },
  { id: 45, name: "Image Brightness Adjuster", slug: "image-brightness-adjuster", category: "Camera & Photo Tools", isPro: false },
  { id: 46, name: "Image Contrast Adjuster", slug: "image-contrast-adjuster", category: "Camera & Photo Tools", isPro: false },
  { id: 47, name: "Image Saturation Adjuster", slug: "image-saturation-adjuster", category: "Camera & Photo Tools", isPro: false },
  { id: 48, name: "Image Grayscale Converter", slug: "image-grayscale-converter", category: "Camera & Photo Tools", isPro: false },
  { id: 49, name: "Image Inverter", slug: "image-inverter", category: "Camera & Photo Tools", isPro: false },
  { id: 50, name: "Image Watermark Remover", slug: "image-watermark-remover", category: "Camera & Photo Tools", isPro: false },
  { id: 51, name: "Image Border Generator", slug: "image-border-generator", category: "Camera & Photo Tools", isPro: false },
  { id: 52, name: "Image Rounded Corner Generator", slug: "image-rounded-corner-generator", category: "Camera & Photo Tools", isPro: false },
  { id: 53, name: "Image Frame Generator", slug: "image-frame-generator", category: "Camera & Photo Tools", isPro: false },
  { id: 54, name: "Image Collage Maker", slug: "image-collage-maker", category: "Camera & Photo Tools", isPro: false },
  { id: 55, name: "Photo Grid Maker", slug: "photo-grid-maker", category: "Camera & Photo Tools", isPro: false },
  { id: 56, name: "Contact Sheet Generator", slug: "contact-sheet-generator", category: "Camera & Photo Tools", isPro: false },
  { id: 57, name: "Image Sequence Maker", slug: "image-sequence-maker", category: "Camera & Photo Tools", isPro: false },
  { id: 58, name: "Photo Metadata Viewer", slug: "photo-metadata-viewer", category: "Camera & Photo Tools", isPro: false },
  { id: 59, name: "Photo Filename Generator", slug: "photo-filename-generator", category: "Camera & Photo Tools", isPro: false },
  { id: 60, name: "Batch Photo Renamer", slug: "batch-photo-renamer", category: "Camera & Photo Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "AI Image Upscaler", slug: "ai-image-upscaler", category: "Camera & Photo Tools", isPro: true },
  { id: 62, name: "AI Photo Enhancer", slug: "ai-photo-enhancer", category: "Camera & Photo Tools", isPro: true },
  { id: 63, name: "AI Photo Restoration", slug: "ai-photo-restoration", category: "Camera & Photo Tools", isPro: true },
  { id: 64, name: "AI Object Remover", slug: "ai-object-remover", category: "Camera & Photo Tools", isPro: true },
  { id: 65, name: "AI Background Replacement", slug: "ai-background-replacement", category: "Camera & Photo Tools", isPro: true },
  { id: 66, name: "AI Product Photo Enhancer", slug: "ai-product-photo-enhancer", category: "Camera & Photo Tools", isPro: true },
  { id: 67, name: "AI Face Enhancement", slug: "ai-face-enhancement", category: "Camera & Photo Tools", isPro: true },
  { id: 68, name: "AI Portrait Enhancer", slug: "ai-portrait-enhancer", category: "Camera & Photo Tools", isPro: true },
  { id: 69, name: "AI Old Photo Restorer", slug: "ai-old-photo-restorer", category: "Camera & Photo Tools", isPro: true },
  { id: 70, name: "AI Image Denoiser", slug: "ai-image-denoiser", category: "Camera & Photo Tools", isPro: true },
  { id: 71, name: "AI Image Deblurring", slug: "ai-image-deblurring", category: "Camera & Photo Tools", isPro: true },
  { id: 72, name: "AI Sky Replacement", slug: "ai-sky-replacement", category: "Camera & Photo Tools", isPro: true },
  { id: 73, name: "AI Photo Relighting", slug: "ai-photo-relighting", category: "Camera & Photo Tools", isPro: true },
  { id: 74, name: "AI Colorization", slug: "ai-colorization", category: "Camera & Photo Tools", isPro: true },
  { id: 75, name: "AI Image Color Correction", slug: "ai-image-color-correction", category: "Camera & Photo Tools", isPro: true },
  { id: 76, name: "AI Face Retouching", slug: "ai-face-retouching", category: "Camera & Photo Tools", isPro: true },
  { id: 77, name: "AI Skin Retouching", slug: "ai-skin-retouching", category: "Camera & Photo Tools", isPro: true },
  { id: 78, name: "AI Eye Enhancement", slug: "ai-eye-enhancement", category: "Camera & Photo Tools", isPro: true },
  { id: 79, name: "AI Teeth Enhancement", slug: "ai-teeth-enhancement", category: "Camera & Photo Tools", isPro: true },
  { id: 80, name: "AI Hair Enhancement", slug: "ai-hair-enhancement", category: "Camera & Photo Tools", isPro: true },
  { id: 81, name: "AI Portrait Background Generator", slug: "ai-portrait-background-generator", category: "Camera & Photo Tools", isPro: true },
  { id: 82, name: "AI Product Background Generator", slug: "ai-product-background-generator", category: "Camera & Photo Tools", isPro: true },
  { id: 83, name: "AI Photo Culling Assistant", slug: "ai-photo-culling-assistant", category: "Camera & Photo Tools", isPro: true },
  { id: 84, name: "AI Duplicate Photo Detector", slug: "ai-duplicate-photo-detector", category: "Camera & Photo Tools", isPro: true },
  { id: 85, name: "AI Similar Photo Finder", slug: "ai-similar-photo-finder", category: "Camera & Photo Tools", isPro: true },
  { id: 86, name: "AI Photo Quality Scorer", slug: "ai-photo-quality-scorer", category: "Camera & Photo Tools", isPro: true },
  { id: 87, name: "AI Composition Analyzer", slug: "ai-composition-analyzer", category: "Camera & Photo Tools", isPro: true },
  { id: 88, name: "AI Exposure Analyzer", slug: "ai-exposure-analyzer", category: "Camera & Photo Tools", isPro: true },
  { id: 89, name: "AI Lighting Analyzer", slug: "ai-lighting-analyzer", category: "Camera & Photo Tools", isPro: true },
  { id: 90, name: "AI Focus Quality Analyzer", slug: "ai-focus-quality-analyzer", category: "Camera & Photo Tools", isPro: true },
  { id: 91, name: "AI Portrait Composition Analyzer", slug: "ai-portrait-composition-analyzer", category: "Camera & Photo Tools", isPro: true },
  { id: 92, name: "Batch Photo Enhancement", slug: "batch-photo-enhancement", category: "Camera & Photo Tools", isPro: true },
  { id: 93, name: "Batch Background Removal", slug: "batch-background-removal", category: "Camera & Photo Tools", isPro: true },
  { id: 94, name: "Batch Image Optimization", slug: "batch-image-optimization", category: "Camera & Photo Tools", isPro: true },
  { id: 95, name: "Professional Photo Workflow", slug: "professional-photo-workflow", category: "Camera & Photo Tools", isPro: true },
  { id: 96, name: "Photo Asset Management Workspace", slug: "photo-asset-management-workspace", category: "Camera & Photo Tools", isPro: true },
  { id: 97, name: "AI Photography Assistant", slug: "ai-photography-assistant", category: "Camera & Photo Tools", isPro: true },
  { id: 98, name: "Photo Quality Intelligence Platform", slug: "photo-quality-intelligence-platform", category: "Camera & Photo Tools", isPro: true },
  { id: 99, name: "Professional Photo Processing Workspace", slug: "professional-photo-processing-workspace", category: "Camera & Photo Tools", isPro: true },
  { id: 100, name: "AI Photo Production Workspace", slug: "ai-photo-production-workspace", category: "Camera & Photo Tools", isPro: true },
];