export interface CloudDevOpsTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const cloudDevopsToolsList: CloudDevOpsTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "JSON Formatter", slug: "json-formatter", category: "Cloud & DevOps Tools", isPro: false },
  { id: 2, name: "JSON Validator", slug: "json-validator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 3, name: "YAML Validator", slug: "yaml-validator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 4, name: "Dockerfile Validator", slug: "dockerfile-validator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 5, name: "Docker Compose Validator", slug: "docker-compose-validator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 6, name: "Kubernetes YAML Validator", slug: "kubernetes-yaml-validator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 7, name: "Cron Expression Generator", slug: "cron-expression-generator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 8, name: "Cron Expression Validator", slug: "cron-expression-validator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 9, name: "GitHub Actions YAML Validator", slug: "github-actions-yaml-validator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 10, name: "Terraform Validator", slug: "terraform-validator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 11, name: "Cloud Cost Calculator", slug: "cloud-cost-calculator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 12, name: "AWS Cost Calculator", slug: "aws-cost-calculator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 13, name: "Azure Cost Calculator", slug: "azure-cost-calculator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 14, name: "Google Cloud Cost Calculator", slug: "google-cloud-cost-calculator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 15, name: "Storage Cost Calculator", slug: "storage-cost-calculator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 16, name: "Bandwidth Cost Calculator", slug: "bandwidth-cost-calculator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 17, name: "CDN Cost Calculator", slug: "cdn-cost-calculator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 18, name: "Database Cost Calculator", slug: "database-cost-calculator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 19, name: "Kubernetes Cost Optimization", slug: "kubernetes-cost-optimization", category: "Cloud & DevOps Tools", isPro: true },
  { id: 20, name: "Cloud Cost Optimization Engine", slug: "cloud-cost-optimization-engine", category: "Cloud & DevOps Tools", isPro: true },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "YAML Formatter", slug: "yaml-formatter", category: "Cloud & DevOps Tools", isPro: false },
  { id: 22, name: "XML Formatter", slug: "xml-formatter", category: "Cloud & DevOps Tools", isPro: false },
  { id: 23, name: "XML Validator", slug: "xml-validator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 24, name: "TOML Validator", slug: "toml-validator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 25, name: "ENV File Validator", slug: "env-file-validator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 26, name: "Docker Image Size Calculator", slug: "docker-image-size-calculator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 27, name: "Docker Resource Calculator", slug: "docker-resource-calculator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 28, name: "Kubernetes Manifest Validator", slug: "kubernetes-manifest-validator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 29, name: "Kubernetes Resource Calculator", slug: "kubernetes-resource-calculator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 30, name: "Kubernetes CPU Request Calculator", slug: "kubernetes-cpu-request-calculator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 31, name: "Kubernetes Memory Request Calculator", slug: "kubernetes-memory-request-calculator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 32, name: "Kubernetes Pod Resource Calculator", slug: "kubernetes-pod-resource-calculator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 33, name: "Cron Expression Explainer", slug: "cron-expression-explainer", category: "Cloud & DevOps Tools", isPro: false },
  { id: 34, name: "Linux Command Generator", slug: "linux-command-generator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 35, name: "Shell Command Formatter", slug: "shell-command-formatter", category: "Cloud & DevOps Tools", isPro: false },
  { id: 36, name: "Bash Script Validator", slug: "bash-script-validator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 37, name: "Shell Script Formatter", slug: "shell-script-formatter", category: "Cloud & DevOps Tools", isPro: false },
  { id: 38, name: "Regex Validator", slug: "regex-validator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 39, name: "Environment Variable Generator", slug: "environment-variable-generator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 40, name: "Environment Variable Validator", slug: "environment-variable-validator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 41, name: ".gitignore Generator", slug: "gitignore-generator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 42, name: ".dockerignore Generator", slug: "dockerignore-generator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 43, name: "CI Configuration Validator", slug: "ci-configuration-validator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 44, name: "GitLab CI YAML Validator", slug: "gitlab-ci-yaml-validator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 45, name: "Jenkinsfile Validator", slug: "jenkinsfile-validator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 46, name: "Terraform Formatter", slug: "terraform-formatter", category: "Cloud & DevOps Tools", isPro: false },
  { id: 47, name: "Terraform Syntax Validator", slug: "terraform-syntax-validator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 48, name: "Terraform Variable Generator", slug: "terraform-variable-generator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 49, name: "Terraform Resource Generator", slug: "terraform-resource-generator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 50, name: "Infrastructure Cost Calculator", slug: "infrastructure-cost-calculator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 51, name: "Server Cost Calculator", slug: "server-cost-calculator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 52, name: "Cloud Backup Cost Calculator", slug: "cloud-backup-cost-calculator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 53, name: "Serverless Cost Calculator", slug: "serverless-cost-calculator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 54, name: "API Response Formatter", slug: "api-response-formatter", category: "Cloud & DevOps Tools", isPro: false },
  { id: 55, name: "API Request Builder", slug: "api-request-builder", category: "Cloud & DevOps Tools", isPro: false },
  { id: 56, name: "HTTP Header Generator", slug: "http-header-generator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 57, name: "HTTP Status Code Lookup", slug: "http-status-code-lookup", category: "Cloud & DevOps Tools", isPro: false },
  { id: 58, name: "Port Number Lookup", slug: "port-number-lookup", category: "Cloud & DevOps Tools", isPro: false },
  { id: 59, name: "DNS Record Generator", slug: "dns-record-generator", category: "Cloud & DevOps Tools", isPro: false },
  { id: 60, name: "Deployment Checklist Generator", slug: "deployment-checklist-generator", category: "Cloud & DevOps Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "DevOps Checklist Generator", slug: "devops-checklist-generator", category: "Cloud & DevOps Tools", isPro: true },
  { id: 62, name: "Incident Checklist Generator", slug: "incident-checklist-generator", category: "Cloud & DevOps Tools", isPro: true },
  { id: 63, name: "Uptime Calculator", slug: "uptime-calculator", category: "Cloud & DevOps Tools", isPro: true },
  { id: 64, name: "Multi-Cloud Cost Comparison", slug: "multi-cloud-cost-comparison", category: "Cloud & DevOps Tools", isPro: true },
  { id: 65, name: "Cloud Architecture Cost Planner", slug: "cloud-architecture-cost-planner", category: "Cloud & DevOps Tools", isPro: true },
  { id: 66, name: "Infrastructure Cost Dashboard", slug: "infrastructure-cost-dashboard", category: "Cloud & DevOps Tools", isPro: true },
  { id: 67, name: "AWS Cost Optimization Workspace", slug: "aws-cost-optimization-workspace", category: "Cloud & DevOps Tools", isPro: true },
  { id: 68, name: "Azure Cost Optimization Workspace", slug: "azure-cost-optimization-workspace", category: "Cloud & DevOps Tools", isPro: true },
  { id: 69, name: "Google Cloud Cost Optimization Workspace", slug: "google-cloud-cost-optimization-workspace", category: "Cloud & DevOps Tools", isPro: true },
  { id: 70, name: "Kubernetes Cluster Planning Workspace", slug: "kubernetes-cluster-planning-workspace", category: "Cloud & DevOps Tools", isPro: true },
  { id: 71, name: "Kubernetes Resource Optimization", slug: "kubernetes-resource-optimization", category: "Cloud & DevOps Tools", isPro: true },
  { id: 72, name: "Container Optimization Workspace", slug: "container-optimization-workspace", category: "Cloud & DevOps Tools", isPro: true },
  { id: 73, name: "Docker Image Optimization", slug: "docker-image-optimization", category: "Cloud & DevOps Tools", isPro: true },
  { id: 74, name: "CI/CD Pipeline Builder", slug: "ci-cd-pipeline-builder", category: "Cloud & DevOps Tools", isPro: true },
  { id: 75, name: "CI/CD Pipeline Analyzer", slug: "ci-cd-pipeline-analyzer", category: "Cloud & DevOps Tools", isPro: true },
  { id: 76, name: "Deployment Pipeline Workspace", slug: "deployment-pipeline-workspace", category: "Cloud & DevOps Tools", isPro: true },
  { id: 77, name: "Infrastructure as Code Workspace", slug: "infrastructure-as-code-workspace", category: "Cloud & DevOps Tools", isPro: true },
  { id: 78, name: "Terraform Project Workspace", slug: "terraform-project-workspace", category: "Cloud & DevOps Tools", isPro: true },
  { id: 79, name: "Infrastructure Configuration Manager", slug: "infrastructure-configuration-manager", category: "Cloud & DevOps Tools", isPro: true },
  { id: 80, name: "Environment Configuration Workspace", slug: "environment-configuration-workspace", category: "Cloud & DevOps Tools", isPro: true },
  { id: 81, name: "Secrets Configuration Workspace", slug: "secrets-configuration-workspace", category: "Cloud & DevOps Tools", isPro: true },
  { id: 82, name: "DevOps Monitoring Dashboard", slug: "devops-monitoring-dashboard", category: "Cloud & DevOps Tools", isPro: true },
  { id: 83, name: "Deployment Monitoring Workspace", slug: "deployment-monitoring-workspace", category: "Cloud & DevOps Tools", isPro: true },
  { id: 84, name: "Incident Management Workspace", slug: "incident-management-workspace", category: "Cloud & DevOps Tools", isPro: true },
  { id: 85, name: "Incident Timeline Workspace", slug: "incident-timeline-workspace", category: "Cloud & DevOps Tools", isPro: true },
  { id: 86, name: "SRE Operations Dashboard", slug: "sre-operations-dashboard", category: "Cloud & DevOps Tools", isPro: true },
  { id: 87, name: "SLA Monitoring Workspace", slug: "sla-monitoring-workspace", category: "Cloud & DevOps Tools", isPro: true },
  { id: 88, name: "Uptime Monitoring Dashboard", slug: "uptime-monitoring-dashboard", category: "Cloud & DevOps Tools", isPro: true },
  { id: 89, name: "API Monitoring Workspace", slug: "api-monitoring-workspace", category: "Cloud & DevOps Tools", isPro: true },
  { id: 90, name: "Cloud Resource Inventory", slug: "cloud-resource-inventory", category: "Cloud & DevOps Tools", isPro: true },
  { id: 91, name: "Cloud Infrastructure Dashboard", slug: "cloud-infrastructure-dashboard", category: "Cloud & DevOps Tools", isPro: true },
  { id: 92, name: "Multi-Cloud Resource Dashboard", slug: "multi-cloud-resource-dashboard", category: "Cloud & DevOps Tools", isPro: true },
  { id: 93, name: "DevOps Analytics Workspace", slug: "devops-analytics-workspace", category: "Cloud & DevOps Tools", isPro: true },
  { id: 94, name: "Cloud Security Configuration Checker", slug: "cloud-security-configuration-checker", category: "Cloud & DevOps Tools", isPro: true },
  { id: 95, name: "Infrastructure Compliance Workspace", slug: "infrastructure-compliance-workspace", category: "Cloud & DevOps Tools", isPro: true },
  { id: 96, name: "Cloud Data Import Workspace", slug: "cloud-data-import-workspace", category: "Cloud & DevOps Tools", isPro: true },
  { id: 97, name: "Cloud Cost Reporting Engine", slug: "cloud-cost-reporting-engine", category: "Cloud & DevOps Tools", isPro: true },
  { id: 98, name: "DevOps API Workspace", slug: "devops-api-workspace", category: "Cloud & DevOps Tools", isPro: true },
  { id: 99, name: "Cloud Automation Workspace", slug: "cloud-automation-workspace", category: "Cloud & DevOps Tools", isPro: true },
  { id: 100, name: "Cloud Operations Command Center", slug: "cloud-operations-command-center", category: "Cloud & DevOps Tools", isPro: true }
];