export interface ComplianceManagementTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const complianceManagementToolsList: ComplianceManagementTool[] = [
  // --- 🔥 PRIORITY 20 FREE TOOLS (IDs 1-20 | isPro: false) ---
  { id: 1, name: "Compliance Requirement Tracker", slug: "compliance-requirement-tracker", category: "Compliance Management Tools", isPro: false },
  { id: 2, name: "Compliance Deadline Calculator", slug: "compliance-deadline-calculator", category: "Compliance Management Tools", isPro: false },
  { id: 3, name: "Compliance Calendar Generator", slug: "compliance-calendar-generator", category: "Compliance Management Tools", isPro: false },
  { id: 4, name: "Compliance Evidence Checklist", slug: "compliance-evidence-checklist", category: "Compliance Management Tools", isPro: false },
  { id: 5, name: "Policy Review Checklist", slug: "policy-review-checklist-compliance", category: "Compliance Management Tools", isPro: false },
  { id: 6, name: "Policy Renewal Tracker", slug: "policy-renewal-tracker-compliance", category: "Compliance Management Tools", isPro: false },
  { id: 7, name: "Control Testing Checklist", slug: "control-testing-checklist", category: "Compliance Management Tools", isPro: false },
  { id: 8, name: "Control Owner Tracker", slug: "control-owner-tracker", category: "Compliance Management Tools", isPro: false },
  { id: 9, name: "Compliance Gap Tracker", slug: "compliance-gap-tracker", category: "Compliance Management Tools", isPro: false },
  { id: 10, name: "Compliance Risk Matrix", slug: "compliance-risk-matrix", category: "Compliance Management Tools", isPro: false },
  { id: 11, name: "Audit Readiness Checklist", slug: "audit-readiness-checklist", category: "Compliance Management Tools", isPro: false },
  { id: 12, name: "Audit Request Tracker", slug: "audit-request-tracker", category: "Compliance Management Tools", isPro: false },
  { id: 13, name: "Audit Finding Tracker", slug: "audit-finding-tracker", category: "Compliance Management Tools", isPro: false },
  { id: 14, name: "Corrective Action Tracker", slug: "corrective-action-tracker", category: "Compliance Management Tools", isPro: false },
  { id: 15, name: "Remediation Deadline Calculator", slug: "remediation-deadline-calculator", category: "Compliance Management Tools", isPro: false },
  { id: 16, name: "Regulatory Change Tracker", slug: "regulatory-change-tracker", category: "Compliance Management Tools", isPro: false },
  { id: 17, name: "Requirement Mapping Tool", slug: "requirement-mapping-tool", category: "Compliance Management Tools", isPro: false },
  { id: 18, name: "Policy-to-Control Mapper", slug: "policy-to-control-mapper", category: "Compliance Management Tools", isPro: false },
  { id: 19, name: "Compliance Risk Dashboard", slug: "compliance-risk-dashboard-free", category: "Compliance Management Tools", isPro: false },
  { id: 20, name: "Compliance Management Workspace", slug: "compliance-management-workspace-free", category: "Compliance Management Tools", isPro: false },

  // --- REMAINING 40 CORE FREE TOOLS (IDs 21-60 | isPro: false) ---
  { id: 21, name: "Compliance Checklist Builder", slug: "compliance-checklist-builder", category: "Compliance Management Tools", isPro: false },
  { id: 22, name: "Compliance Renewal Calculator", slug: "compliance-renewal-calculator", category: "Compliance Management Tools", isPro: false },
  { id: 23, name: "Compliance Task Planner", slug: "compliance-task-planner", category: "Compliance Management Tools", isPro: false },
  { id: 24, name: "Evidence Collection Checklist", slug: "evidence-collection-checklist", category: "Compliance Management Tools", isPro: false },
  { id: 25, name: "Compliance Document Checklist", slug: "compliance-document-checklist", category: "Compliance Management Tools", isPro: false },
  { id: 26, name: "Policy Approval Checklist", slug: "policy-approval-checklist", category: "Compliance Management Tools", isPro: false },
  { id: 27, name: "Policy Expiration Tracker", slug: "policy-expiration-tracker-compliance", category: "Compliance Management Tools", isPro: false },
  { id: 28, name: "Control Checklist Builder", slug: "control-checklist-builder", category: "Compliance Management Tools", isPro: false },
  { id: 29, name: "Control Review Checklist", slug: "control-review-checklist", category: "Compliance Management Tools", isPro: false },
  { id: 30, name: "Compliance Responsibility Matrix", slug: "compliance-responsibility-matrix", category: "Compliance Management Tools", isPro: false },
  { id: 31, name: "Compliance Role Matrix", slug: "compliance-role-matrix", category: "Compliance Management Tools", isPro: false },
  { id: 32, name: "Compliance Gap Checklist", slug: "compliance-gap-checklist", category: "Compliance Management Tools", isPro: false },
  { id: 33, name: "Compliance Risk Score", slug: "compliance-risk-score", category: "Compliance Management Tools", isPro: false },
  { id: 34, name: "Compliance Priority Calculator", slug: "compliance-priority-calculator", category: "Compliance Management Tools", isPro: false },
  { id: 35, name: "Compliance Maturity Score", slug: "compliance-maturity-score", category: "Compliance Management Tools", isPro: false },
  { id: 36, name: "Compliance Readiness Score", slug: "compliance-readiness-score", category: "Compliance Management Tools", isPro: false },
  { id: 37, name: "Internal Audit Checklist", slug: "internal-audit-checklist", category: "Compliance Management Tools", isPro: false },
  { id: 38, name: "External Audit Checklist", slug: "external-audit-checklist", category: "Compliance Management Tools", isPro: false },
  { id: 39, name: "Audit Evidence Checklist", slug: "audit-evidence-checklist", category: "Compliance Management Tools", isPro: false },
  { id: 40, name: "Remediation Priority Calculator", slug: "remediation-priority-calculator", category: "Compliance Management Tools", isPro: false },
  { id: 41, name: "Exception Request Tracker", slug: "exception-request-tracker", category: "Compliance Management Tools", isPro: false },
  { id: 42, name: "Compliance Exception Checklist", slug: "compliance-exception-checklist", category: "Compliance Management Tools", isPro: false },
  { id: 43, name: "Compliance Issue Tracker", slug: "compliance-issue-tracker", category: "Compliance Management Tools", isPro: false },
  { id: 44, name: "Control Mapping Tool", slug: "control-mapping-tool", category: "Compliance Management Tools", isPro: false },
  { id: 45, name: "Evidence-to-Control Mapper", slug: "evidence-to-control-mapper", category: "Compliance Management Tools", isPro: false },
  { id: 46, name: "Compliance Crosswalk Builder", slug: "compliance-crosswalk-builder", category: "Compliance Management Tools", isPro: false },
  { id: 47, name: "Compliance Questionnaire Builder", slug: "compliance-questionnaire-builder", category: "Compliance Management Tools", isPro: false },
  { id: 48, name: "Vendor Compliance Questionnaire", slug: "vendor-compliance-questionnaire-comp", category: "Compliance Management Tools", isPro: false },
  { id: 49, name: "Compliance Attestation Checklist", slug: "compliance-attestation-checklist", category: "Compliance Management Tools", isPro: false },
  { id: 50, name: "Compliance Certification Tracker", slug: "compliance-certification-tracker", category: "Compliance Management Tools", isPro: false },
  { id: 51, name: "Compliance Training Tracker", slug: "compliance-training-tracker", category: "Compliance Management Tools", isPro: false },
  { id: 52, name: "Compliance Acknowledgment Tracker", slug: "compliance-acknowledgment-tracker", category: "Compliance Management Tools", isPro: false },
  { id: 53, name: "Compliance Meeting Planner", slug: "compliance-meeting-planner", category: "Compliance Management Tools", isPro: false },
  { id: 54, name: "Compliance Review Agenda", slug: "compliance-review-agenda", category: "Compliance Management Tools", isPro: false },
  { id: 55, name: "Compliance Status Report", slug: "compliance-status-report", category: "Compliance Management Tools", isPro: false },
  { id: 56, name: "Compliance Gap Report", slug: "compliance-gap-report", category: "Compliance Management Tools", isPro: false },
  { id: 57, name: "Audit Readiness Report", slug: "audit-readiness-report", category: "Compliance Management Tools", isPro: false },
  { id: 58, name: "Compliance Evidence Report", slug: "compliance-evidence-report", category: "Compliance Management Tools", isPro: false },
  { id: 59, name: "Remediation Report", slug: "remediation-report", category: "Compliance Management Tools", isPro: false },
  { id: 60, name: "Compliance KPI Calculator", slug: "compliance-kpi-calculator-comp", category: "Compliance Management Tools", isPro: false },

  // --- ⚡ 40 PRO / SAAS TOOLS (IDs 61-100 | isPro: true) ---
  { id: 61, name: "Compliance Management Workspace", slug: "compliance-management-workspace", category: "Compliance Management Tools", isPro: true },
  { id: 62, name: "Compliance Program Workspace", slug: "compliance-program-workspace", category: "Compliance Management Tools", isPro: true },
  { id: 63, name: "Compliance Requirement Workspace", slug: "compliance-requirement-workspace", category: "Compliance Management Tools", isPro: true },
  { id: 64, name: "Compliance Calendar Workspace", slug: "compliance-calendar-workspace", category: "Compliance Management Tools", isPro: true },
  { id: 65, name: "Evidence Management Workspace", slug: "evidence-management-workspace", category: "Compliance Management Tools", isPro: true },
  { id: 66, name: "Policy Management Workspace", slug: "policy-management-workspace-comp", category: "Compliance Management Tools", isPro: true },
  { id: 67, name: "Control Management Workspace", slug: "control-management-workspace", category: "Compliance Management Tools", isPro: true },
  { id: 68, name: "Control Testing Workspace", slug: "control-testing-workspace", category: "Compliance Management Tools", isPro: true },
  { id: 69, name: "Compliance Risk Workspace", slug: "compliance-risk-workspace", category: "Compliance Management Tools", isPro: true },
  { id: 70, name: "Compliance Gap Management", slug: "compliance-gap-management", category: "Compliance Management Tools", isPro: true },
  { id: 71, name: "Audit Management Workspace", slug: "audit-management-workspace", category: "Compliance Management Tools", isPro: true },
  { id: 72, name: "Audit Evidence Workspace", slug: "audit-evidence-workspace", category: "Compliance Management Tools", isPro: true },
  { id: 73, name: "Audit Finding Management", slug: "audit-finding-management", category: "Compliance Management Tools", isPro: true },
  { id: 74, name: "Remediation Management Workspace", slug: "remediation-management-workspace", category: "Compliance Management Tools", isPro: true },
  { id: 75, name: "Corrective Action Workspace", slug: "corrective-action-workspace", category: "Compliance Management Tools", isPro: true },
  { id: 76, name: "Compliance Exception Management", slug: "compliance-exception-management", category: "Compliance Management Tools", isPro: true },
  { id: 77, name: "Regulatory Change Workspace", slug: "regulatory-change-workspace", category: "Compliance Management Tools", isPro: true },
  { id: 78, name: "Requirement Mapping Workspace", slug: "requirement-mapping-workspace", category: "Compliance Management Tools", isPro: true },
  { id: 79, name: "Control Mapping Workspace", slug: "control-mapping-workspace", category: "Compliance Management Tools", isPro: true },
  { id: 80, name: "Compliance Crosswalk Workspace", slug: "compliance-crosswalk-workspace", category: "Compliance Management Tools", isPro: true },
  { id: 81, name: "Compliance Questionnaire Workspace", slug: "compliance-questionnaire-workspace", category: "Compliance Management Tools", isPro: true },
  { id: 82, name: "Vendor Compliance Workspace", slug: "vendor-compliance-workspace", category: "Compliance Management Tools", isPro: true },
  { id: 83, name: "Compliance Certification Workspace", slug: "compliance-certification-workspace", category: "Compliance Management Tools", isPro: true },
  { id: 84, name: "Compliance Training Workspace", slug: "compliance-training-workspace", category: "Compliance Management Tools", isPro: true },
  { id: 85, name: "Compliance Attestation Workspace", slug: "compliance-attestation-workspace", category: "Compliance Management Tools", isPro: true },
  { id: 86, name: "Compliance KPI Dashboard", slug: "compliance-kpi-dashboard-comp", category: "Compliance Management Tools", isPro: true },
  { id: 87, name: "Compliance Risk Dashboard", slug: "compliance-risk-dashboard", category: "Compliance Management Tools", isPro: true },
  { id: 88, name: "Audit Readiness Dashboard", slug: "audit-readiness-dashboard", category: "Compliance Management Tools", isPro: true },
  { id: 89, name: "Compliance Evidence Dashboard", slug: "compliance-evidence-dashboard", category: "Compliance Management Tools", isPro: true },
  { id: 90, name: "Remediation Dashboard", slug: "remediation-dashboard", category: "Compliance Management Tools", isPro: true },
  { id: 91, name: "Compliance Reporting Engine", slug: "compliance-reporting-engine", category: "Compliance Management Tools", isPro: true },
  { id: 92, name: "Compliance Data Importer", slug: "compliance-data-importer", category: "Compliance Management Tools", isPro: true },
  { id: 93, name: "Compliance Data Exporter", slug: "compliance-data-exporter", category: "Compliance Management Tools", isPro: true },
  { id: 94, name: "Compliance API Workspace", slug: "compliance-api-workspace", category: "Compliance Management Tools", isPro: true },
  { id: 95, name: "Compliance Workflow Automation", slug: "compliance-workflow-automation", category: "Compliance Management Tools", isPro: true },
  { id: 96, name: "Compliance Alert Engine", slug: "compliance-alert-engine", category: "Compliance Management Tools", isPro: true },
  { id: 97, name: "Compliance Intelligence Platform", slug: "compliance-intelligence-platform", category: "Compliance Management Tools", isPro: true },
  { id: 98, name: "Enterprise Compliance Platform", slug: "enterprise-compliance-platform", category: "Compliance Management Tools", isPro: true },
  { id: 99, name: "Compliance Operations Platform", slug: "compliance-operations-platform", category: "Compliance Management Tools", isPro: true },
  { id: 100, name: "Compliance Command Center", slug: "compliance-command-center", category: "Compliance Management Tools", isPro: true }
];