export interface ConsultingTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const consultingProfessionalServicesToolsList: ConsultingTool[] = [
  // --- 🔥 PRIORITY 20 FREE TOOLS (IDs 1-20 | isPro: false) ---
  { id: 1, name: "Consulting Fee Calculator", slug: "consulting-fee-calculator", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 2, name: "Consulting Hourly Rate Calculator", slug: "consulting-hourly-rate-calculator", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 3, name: "Consulting Project Fee Calculator", slug: "consulting-project-fee-calculator", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 4, name: "Consulting Retainer Calculator", slug: "consulting-retainer-calculator", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 5, name: "Consulting Profit Calculator", slug: "consulting-profit-calculator", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 6, name: "Billable Rate Calculator", slug: "billable-rate-calculator", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 7, name: "Billable Hours Calculator", slug: "billable-hours-calculator", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 8, name: "Utilization Rate Calculator", slug: "utilization-rate-calculator", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 9, name: "Effective Hourly Rate Calculator", slug: "effective-hourly-rate-calculator", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 10, name: "Client Profitability Calculator", slug: "client-profitability-calculator", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 11, name: "Engagement Profitability Calculator", slug: "engagement-profitability-calculator", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 12, name: "Scope Change Cost Calculator", slug: "scope-change-cost-calculator", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 13, name: "Proposal Pricing Calculator", slug: "proposal-pricing-calculator", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 14, name: "Proposal Builder", slug: "proposal-builder", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 15, name: "Statement of Work Builder", slug: "statement-of-work-builder", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 16, name: "Scope of Work Builder", slug: "scope-of-work-builder", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 17, name: "Client Intake Form Builder", slug: "client-intake-form-builder", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 18, name: "Retainer Management Workspace", slug: "retainer-management-workspace-free", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 19, name: "Client Profitability Dashboard", slug: "client-profitability-dashboard-free", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 20, name: "Consulting Management Workspace", slug: "consulting-management-workspace-free", category: "Consulting & Professional Services Tools", isPro: false },

  // --- REMAINING 40 CORE FREE TOOLS (IDs 21-60 | isPro: false) ---
  { id: 21, name: "Consulting Daily Rate Calculator", slug: "consulting-daily-rate-calculator", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 22, name: "Consulting Package Pricing Calculator", slug: "consulting-package-pricing-calculator", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 23, name: "Consulting Margin Calculator", slug: "consulting-margin-calculator", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 24, name: "Project Margin Calculator", slug: "project-margin-calculator", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 25, name: "Consultant Capacity Calculator", slug: "consultant-capacity-calculator", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 26, name: "Consultant Workload Calculator", slug: "consultant-workload-calculator", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 27, name: "Client Capacity Calculator", slug: "client-capacity-calculator", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 28, name: "Retainer Capacity Calculator", slug: "retainer-capacity-calculator", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 29, name: "Service Capacity Planner", slug: "service-capacity-planner", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 30, name: "Proposal Scope Calculator", slug: "proposal-scope-calculator", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 31, name: "Change Request Cost Calculator", slug: "change-request-cost-calculator", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 32, name: "Engagement Budget Calculator", slug: "engagement-budget-calculator", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 33, name: "Engagement Timeline Calculator", slug: "engagement-timeline-calculator", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 34, name: "Project Estimate Calculator", slug: "project-estimate-calculator", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 35, name: "Consulting ROI Calculator", slug: "consulting-roi-calculator", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 36, name: "Client ROI Calculator", slug: "client-roi-calculator", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 37, name: "Service ROI Calculator", slug: "service-roi-calculator", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 38, name: "Break-Even Client Calculator", slug: "break-even-client-calculator", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 39, name: "Revenue Per Consultant Calculator", slug: "revenue-per-consultant-calculator", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 40, name: "Revenue Per Client Calculator", slug: "revenue-per-client-calculator", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 41, name: "Monthly Retainer Revenue Calculator", slug: "monthly-retainer-revenue-calculator", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 42, name: "Annual Consulting Revenue Calculator", slug: "annual-consulting-revenue-calculator", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 43, name: "Consulting Forecast Calculator", slug: "consulting-forecast-calculator", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 44, name: "Consulting Brief Builder", slug: "consulting-brief-builder", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 45, name: "Client Discovery Questionnaire", slug: "client-discovery-questionnaire", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 46, name: "Engagement Checklist", slug: "engagement-checklist", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 47, name: "Project Kickoff Checklist", slug: "project-kickoff-checklist", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 48, name: "Client Onboarding Checklist", slug: "client-onboarding-checklist-consulting", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 49, name: "Client Offboarding Checklist", slug: "client-offboarding-checklist", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 50, name: "Consulting Deliverables Checklist", slug: "consulting-deliverables-checklist", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 51, name: "Scope Management Checklist", slug: "scope-management-checklist", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 52, name: "Change Request Checklist", slug: "change-request-checklist", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 53, name: "Client Review Checklist", slug: "client-review-checklist", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 54, name: "Engagement Risk Checklist", slug: "engagement-risk-checklist", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 55, name: "Client Communication Planner", slug: "client-communication-planner", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 56, name: "Client Meeting Planner", slug: "client-meeting-planner", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 57, name: "Consulting Timeline Builder", slug: "consulting-timeline-builder", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 58, name: "Consulting Milestone Planner", slug: "consulting-milestone-planner", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 59, name: "Client Status Report", slug: "client-status-report", category: "Consulting & Professional Services Tools", isPro: false },
  { id: 60, name: "Consulting Operations Checklist", slug: "consulting-operations-checklist", category: "Consulting & Professional Services Tools", isPro: false },

  // --- ⚡ 40 PRO / SAAS TOOLS (IDs 61-100 | isPro: true) ---
  { id: 61, name: "Consulting Management Workspace", slug: "consulting-management-workspace", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 62, name: "Professional Services Workspace", slug: "professional-services-workspace", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 63, name: "Client Engagement Workspace", slug: "client-engagement-workspace", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 64, name: "Client Portfolio Workspace", slug: "client-portfolio-workspace", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 65, name: "Proposal Management Workspace", slug: "proposal-management-workspace", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 66, name: "Statement of Work Workspace", slug: "statement-of-work-workspace", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 67, name: "Scope Management Workspace", slug: "scope-management-workspace", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 68, name: "Change Request Workspace", slug: "change-request-workspace", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 69, name: "Client Onboarding Workspace", slug: "client-onboarding-workspace", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 70, name: "Client Offboarding Workspace", slug: "client-offboarding-workspace", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 71, name: "Engagement Planning Workspace", slug: "engagement-planning-workspace", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 72, name: "Engagement Delivery Workspace", slug: "engagement-delivery-workspace", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 73, name: "Consultant Capacity Workspace", slug: "consultant-capacity-workspace", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 74, name: "Billable Hours Workspace", slug: "billable-hours-workspace", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 75, name: "Utilization Dashboard", slug: "utilization-dashboard", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 76, name: "Client Profitability Dashboard", slug: "client-profitability-dashboard", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 77, name: "Engagement Profitability Dashboard", slug: "engagement-profitability-dashboard", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 78, name: "Consulting Revenue Dashboard", slug: "consulting-revenue-dashboard", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 79, name: "Retainer Management Workspace", slug: "retainer-management-workspace", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 80, name: "Service Package Management", slug: "service-package-management", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 81, name: "Client Communication Workspace", slug: "client-communication-workspace", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 82, name: "Client Meeting Workspace", slug: "client-meeting-workspace", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 83, name: "Deliverables Management Workspace", slug: "deliverables-management-workspace", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 84, name: "Consulting Milestone Workspace", slug: "consulting-milestone-workspace", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 85, name: "Consulting Risk Workspace", slug: "consulting-risk-workspace", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 86, name: "Consulting Reporting Workspace", slug: "consulting-reporting-workspace", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 87, name: "Professional Services Analytics", slug: "professional-services-analytics", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 88, name: "Consulting Forecasting Workspace", slug: "consulting-forecasting-workspace", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 89, name: "Client Health Dashboard", slug: "client-health-dashboard", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 90, name: "Consulting KPI Dashboard", slug: "consulting-kpi-dashboard", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 91, name: "Consulting Data Importer", slug: "consulting-data-importer", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 92, name: "Consulting Data Exporter", slug: "consulting-data-exporter", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 93, name: "Professional Services API", slug: "professional-services-api", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 94, name: "Consulting Workflow Automation", slug: "consulting-workflow-automation", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 95, name: "Client Alert Engine", slug: "client-alert-engine", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 96, name: "Consulting Intelligence Platform", slug: "consulting-intelligence-platform", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 97, name: "Professional Services Platform", slug: "professional-services-platform", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 98, name: "Enterprise Consulting Platform", slug: "enterprise-consulting-platform", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 99, name: "Client Engagement Platform", slug: "client-engagement-platform", category: "Consulting & Professional Services Tools", isPro: true },
  { id: 100, name: "Consulting Command Center", slug: "consulting-command-center", category: "Consulting & Professional Services Tools", isPro: true }
];