export interface CustomerSuccessTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const customerSuccessToolsList: CustomerSuccessTool[] = [
  // --- 🔥 PRIORITY 20 FREE TOOLS (IDs 1-20 | isPro: false) ---
  { id: 1, name: "Customer Health Score Calculator", slug: "customer-health-score-calculator", category: "Customer Success Tools", isPro: false },
  { id: 2, name: "Churn Risk Scorer", slug: "churn-risk-scorer", category: "Customer Success Tools", isPro: false },
  { id: 3, name: "Renewal Probability Calculator", slug: "renewal-probability-calculator", category: "Customer Success Tools", isPro: false },
  { id: 4, name: "Product Adoption Calculator", slug: "product-adoption-calculator", category: "Customer Success Tools", isPro: false },
  { id: 5, name: "Customer Success Plan Builder", slug: "customer-success-plan-builder", category: "Customer Success Tools", isPro: false },
  { id: 6, name: "Customer QBR Planner", slug: "customer-qbr-planner", category: "Customer Success Tools", isPro: false },
  { id: 7, name: "Customer Risk Register", slug: "customer-risk-register", category: "Customer Success Tools", isPro: false },
  { id: 8, name: "Renewal Forecast Calculator", slug: "renewal-forecast-calculator", category: "Customer Success Tools", isPro: false },
  { id: 9, name: "Expansion Opportunity Calculator", slug: "expansion-opportunity-calculator", category: "Customer Success Tools", isPro: false },
  { id: 10, name: "Feature Adoption Calculator", slug: "feature-adoption-calculator", category: "Customer Success Tools", isPro: false },
  { id: 11, name: "Customer Engagement Score", slug: "customer-engagement-score", category: "Customer Success Tools", isPro: false },
  { id: 12, name: "Onboarding Progress Tracker", slug: "onboarding-progress-tracker", category: "Customer Success Tools", isPro: false },
  { id: 13, name: "Account Plan Builder", slug: "account-plan-builder", category: "Customer Success Tools", isPro: false },
  { id: 14, name: "Customer Value Tracker", slug: "customer-value-tracker", category: "Customer Success Tools", isPro: false },
  { id: 15, name: "Customer Lifecycle Planner", slug: "customer-lifecycle-planner", category: "Customer Success Tools", isPro: false },
  { id: 16, name: "Customer Tiering Calculator", slug: "customer-tiering-calculator", category: "Customer Success Tools", isPro: false },
  { id: 17, name: "Customer Success KPI Generator", slug: "customer-success-kpi-generator", category: "Customer Success Tools", isPro: false },
  { id: 18, name: "Customer Success Playbook Builder", slug: "customer-success-playbook-builder", category: "Customer Success Tools", isPro: false },
  { id: 19, name: "Customer Escalation Tracker", slug: "customer-escalation-tracker", category: "Customer Success Tools", isPro: false },
  { id: 20, name: "Success Milestone Planner", slug: "success-milestone-planner", category: "Customer Success Tools", isPro: false },

  // --- REMAINING 40 CORE FREE TOOLS (IDs 21-60 | isPro: false) ---
  { id: 21, name: "Customer Health Score Builder", slug: "customer-health-score-builder", category: "Customer Success Tools", isPro: false },
  { id: 22, name: "Renewal Date Calculator", slug: "renewal-date-calculator", category: "Customer Success Tools", isPro: false },
  { id: 23, name: "Customer Risk Score Calculator", slug: "customer-risk-score-calculator", category: "Customer Success Tools", isPro: false },
  { id: 24, name: "Customer Adoption Score", slug: "customer-adoption-score", category: "Customer Success Tools", isPro: false },
  { id: 25, name: "Customer Success Scorecard", slug: "customer-success-scorecard", category: "Customer Success Tools", isPro: false },
  { id: 26, name: "Customer Onboarding Checklist", slug: "customer-onboarding-checklist", category: "Customer Success Tools", isPro: false },
  { id: 27, name: "Customer Goal Tracker", slug: "customer-goal-tracker", category: "Customer Success Tools", isPro: false },
  { id: 28, name: "Customer Outcome Tracker", slug: "customer-outcome-tracker", category: "Customer Success Tools", isPro: false },
  { id: 29, name: "Renewal Checklist", slug: "renewal-checklist", category: "Customer Success Tools", isPro: false },
  { id: 30, name: "QBR Agenda Builder", slug: "qbr-agenda-builder", category: "Customer Success Tools", isPro: false },
  { id: 31, name: "Customer Review Planner", slug: "customer-review-planner", category: "Customer Success Tools", isPro: false },
  { id: 32, name: "Account Review Checklist", slug: "account-review-checklist", category: "Customer Success Tools", isPro: false },
  { id: 33, name: "Customer Issue Tracker", slug: "customer-issue-tracker", category: "Customer Success Tools", isPro: false },
  { id: 34, name: "Customer Request Tracker", slug: "customer-request-tracker", category: "Customer Success Tools", isPro: false },
  { id: 35, name: "Customer Feedback Log", slug: "customer-feedback-log", category: "Customer Success Tools", isPro: false },
  { id: 36, name: "Customer Feature Request Organizer", slug: "customer-feature-request-organizer", category: "Customer Success Tools", isPro: false },
  { id: 37, name: "Customer Communication Planner", slug: "customer-communication-planner", category: "Customer Success Tools", isPro: false },
  { id: 38, name: "Customer Touchpoint Planner", slug: "customer-touchpoint-planner", category: "Customer Success Tools", isPro: false },
  { id: 39, name: "Customer Follow-Up Planner", slug: "customer-follow-up-planner", category: "Customer Success Tools", isPro: false },
  { id: 40, name: "Customer Meeting Planner", slug: "customer-meeting-planner", category: "Customer Success Tools", isPro: false },
  { id: 41, name: "Customer Success Notes", slug: "customer-success-notes", category: "Customer Success Tools", isPro: false },
  { id: 42, name: "Customer Success Timeline", slug: "customer-success-timeline", category: "Customer Success Tools", isPro: false },
  { id: 43, name: "Customer Journey Checklist", slug: "customer-journey-checklist", category: "Customer Success Tools", isPro: false },
  { id: 44, name: "Customer Segment Planner", slug: "customer-segment-planner", category: "Customer Success Tools", isPro: false },
  { id: 45, name: "Account Prioritization Calculator", slug: "account-prioritization-calculator", category: "Customer Success Tools", isPro: false },
  { id: 46, name: "Customer Portfolio Scorer", slug: "customer-portfolio-scorer", category: "Customer Success Tools", isPro: false },
  { id: 47, name: "Expansion Forecast Calculator", slug: "expansion-forecast-calculator", category: "Customer Success Tools", isPro: false },
  { id: 48, name: "Customer Value Calculator", slug: "customer-value-calculator", category: "Customer Success Tools", isPro: false },
  { id: 49, name: "Customer Success Report Generator", slug: "customer-success-report-generator", category: "Customer Success Tools", isPro: false },
  { id: 50, name: "QBR Report Generator", slug: "qbr-report-generator", category: "Customer Success Tools", isPro: false },
  { id: 51, name: "Account Summary Generator", slug: "account-summary-generator", category: "Customer Success Tools", isPro: false },
  { id: 52, name: "Customer Success Brief Generator", slug: "customer-success-brief-generator", category: "Customer Success Tools", isPro: false },
  { id: 53, name: "Onboarding Report Generator", slug: "onboarding-report-generator", category: "Customer Success Tools", isPro: false },
  { id: 54, name: "Renewal Report Generator", slug: "renewal-report-generator", category: "Customer Success Tools", isPro: false },
  { id: 55, name: "Customer Health Report", slug: "customer-health-report", category: "Customer Success Tools", isPro: false },
  { id: 56, name: "Customer Success Checklist Generator", slug: "customer-success-checklist-generator", category: "Customer Success Tools", isPro: false },
  { id: 57, name: "Customer Escalation Playbook", slug: "customer-escalation-playbook", category: "Customer Success Tools", isPro: false },
  { id: 58, name: "Customer Renewal Playbook", slug: "customer-renewal-playbook", category: "Customer Success Tools", isPro: false },
  { id: 59, name: "Customer Onboarding Playbook", slug: "customer-onboarding-playbook", category: "Customer Success Tools", isPro: false },
  { id: 60, name: "Customer Success Calendar", slug: "customer-success-calendar", category: "Customer Success Tools", isPro: false },

  // --- ⚡ 40 PRO / SAAS TOOLS (IDs 61-100 | isPro: true) ---
  { id: 61, name: "Customer Success Workspace", slug: "customer-success-workspace", category: "Customer Success Tools", isPro: true },
  { id: 62, name: "Customer Health Dashboard", slug: "customer-health-dashboard", category: "Customer Success Tools", isPro: true },
  { id: 63, name: "Customer Portfolio Dashboard", slug: "customer-portfolio-dashboard", category: "Customer Success Tools", isPro: true },
  { id: 64, name: "Account Management Workspace", slug: "account-management-workspace", category: "Customer Success Tools", isPro: true },
  { id: 65, name: "Customer Lifecycle Dashboard", slug: "customer-lifecycle-dashboard", category: "Customer Success Tools", isPro: true },
  { id: 66, name: "Renewal Management Workspace", slug: "renewal-management-workspace", category: "Customer Success Tools", isPro: true },
  { id: 67, name: "Churn Prevention Workspace", slug: "churn-prevention-workspace", category: "Customer Success Tools", isPro: true },
  { id: 68, name: "Expansion Management Workspace", slug: "expansion-management-workspace", category: "Customer Success Tools", isPro: true },
  { id: 69, name: "Customer Adoption Dashboard", slug: "customer-adoption-dashboard", category: "Customer Success Tools", isPro: true },
  { id: 70, name: "Product Adoption Intelligence", slug: "product-adoption-intelligence", category: "Customer Success Tools", isPro: true },
  { id: 71, name: "Customer Engagement Dashboard", slug: "customer-engagement-dashboard", category: "Customer Success Tools", isPro: true },
  { id: 72, name: "Customer Outcome Management", slug: "customer-outcome-management", category: "Customer Success Tools", isPro: true },
  { id: 73, name: "Customer Success Planning Workspace", slug: "customer-success-planning-workspace", category: "Customer Success Tools", isPro: true },
  { id: 74, name: "QBR Management Workspace", slug: "qbr-management-workspace", category: "Customer Success Tools", isPro: true },
  { id: 75, name: "Account Review Workspace", slug: "account-review-workspace", category: "Customer Success Tools", isPro: true },
  { id: 76, name: "Customer Risk Management", slug: "customer-risk-management", category: "Customer Success Tools", isPro: true },
  { id: 77, name: "Customer Escalation Workspace", slug: "customer-escalation-workspace", category: "Customer Success Tools", isPro: true },
  { id: 78, name: "Customer Feedback Intelligence", slug: "customer-feedback-intelligence", category: "Customer Success Tools", isPro: true },
  { id: 79, name: "Feature Request Intelligence", slug: "feature-request-intelligence", category: "Customer Success Tools", isPro: true },
  { id: 80, name: "Customer Journey Workspace", slug: "customer-journey-workspace", category: "Customer Success Tools", isPro: true },
  { id: 81, name: "Customer Touchpoint Management", slug: "customer-touchpoint-management", category: "Customer Success Tools", isPro: true },
  { id: 82, name: "Customer Communication Workspace", slug: "customer-communication-workspace", category: "Customer Success Tools", isPro: true },
  { id: 83, name: "Customer Success Playbook Platform", slug: "customer-success-playbook-platform", category: "Customer Success Tools", isPro: true },
  { id: 84, name: "Customer Success Reporting", slug: "customer-success-reporting", category: "Customer Success Tools", isPro: true },
  { id: 85, name: "Customer Health Alert Engine", slug: "customer-health-alert-engine", category: "Customer Success Tools", isPro: true },
  { id: 86, name: "Renewal Alert Engine", slug: "renewal-alert-engine", category: "Customer Success Tools", isPro: true },
  { id: 87, name: "Customer Risk Alert Engine", slug: "customer-risk-alert-engine", category: "Customer Success Tools", isPro: true },
  { id: 88, name: "Customer Success Analytics", slug: "customer-success-analytics", category: "Customer Success Tools", isPro: true },
  { id: 89, name: "Customer Portfolio Analytics", slug: "customer-portfolio-analytics", category: "Customer Success Tools", isPro: true },
  { id: 90, name: "Account Performance Analytics", slug: "account-performance-analytics", category: "Customer Success Tools", isPro: true },
  { id: 91, name: "Customer Success Automation", slug: "customer-success-automation", category: "Customer Success Tools", isPro: true },
  { id: 92, name: "Customer Success API", slug: "customer-success-api", category: "Customer Success Tools", isPro: true },
  { id: 93, name: "Customer Data Import Workspace", slug: "customer-data-import-workspace", category: "Customer Success Tools", isPro: true },
  { id: 94, name: "Customer Data Export Workspace", slug: "customer-data-export-workspace", category: "Customer Success Tools", isPro: true },
  { id: 95, name: "Customer Success Forecasting", slug: "customer-success-forecasting", category: "Customer Success Tools", isPro: true },
  { id: 96, name: "Customer Success Benchmarking", slug: "customer-success-benchmarking", category: "Customer Success Tools", isPro: true },
  { id: 97, name: "Customer Success Knowledge Base", slug: "customer-success-knowledge-base", category: "Customer Success Tools", isPro: true },
  { id: 98, name: "Customer Success Intelligence Platform", slug: "customer-success-intelligence-platform", category: "Customer Success Tools", isPro: true },
  { id: 99, name: "Enterprise Customer Success Platform", slug: "enterprise-customer-success-platform", category: "Customer Success Tools", isPro: true },
  { id: 100, name: "Customer Success Command Center", slug: "customer-success-command-center", category: "Customer Success Tools", isPro: true }
];