export interface EcommerceTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const ecommerceToolsList: EcommerceTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-15) ---
  { id: 1, name: "Product Description Generator", slug: "product-description-generator", category: "eCommerce Tools", isPro: false },
  { id: 2, name: "Product Pricing Calculator", slug: "product-pricing-calculator", category: "eCommerce Tools", isPro: false },
  { id: 3, name: "Product Profit Calculator", slug: "product-profit-calculator", category: "eCommerce Tools", isPro: false },
  { id: 4, name: "Amazon Fee Calculator", slug: "amazon-fee-calculator", category: "eCommerce Tools", isPro: false },
  { id: 5, name: "Shopify Profit Calculator", slug: "shopify-profit-calculator", category: "eCommerce Tools", isPro: false },
  { id: 6, name: "eBay Fee Calculator", slug: "ebay-fee-calculator", category: "eCommerce Tools", isPro: false },
  { id: 7, name: "Etsy Fee Calculator", slug: "etsy-fee-calculator", category: "eCommerce Tools", isPro: false },
  { id: 8, name: "Inventory Calculator", slug: "inventory-calculator", category: "eCommerce Tools", isPro: false },
  { id: 9, name: "Shipping Cost Calculator", slug: "shipping-cost-calculator", category: "eCommerce Tools", isPro: false },
  { id: 10, name: "Customer Lifetime Value Calculator", slug: "customer-lifetime-value-calculator", category: "eCommerce Tools", isPro: false },
  // Moving some Tier A Pro tools to the top of Pro section later, but keeping their IDs organized.
  
  // --- REMAINING CORE FREE TOOLS (11-60) ---
  { id: 11, name: "Product Title Generator", slug: "product-title-generator", category: "eCommerce Tools", isPro: false },
  { id: 12, name: "Product Feature Generator", slug: "product-feature-generator", category: "eCommerce Tools", isPro: false },
  { id: 13, name: "Product Benefits Generator", slug: "product-benefits-generator", category: "eCommerce Tools", isPro: false },
  { id: 14, name: "Product Bullet Point Generator", slug: "product-bullet-point-generator", category: "eCommerce Tools", isPro: false },
  { id: 15, name: "Product Specification Formatter", slug: "product-specification-formatter", category: "eCommerce Tools", isPro: false },
  { id: 16, name: "Product SKU Generator", slug: "product-sku-generator", category: "eCommerce Tools", isPro: false },
  { id: 17, name: "SKU Validator", slug: "sku-validator", category: "eCommerce Tools", isPro: false },
  { id: 18, name: "Barcode Generator", slug: "barcode-generator-ecommerce", category: "eCommerce Tools", isPro: false },
  { id: 19, name: "Product URL Slug Generator", slug: "product-url-slug-generator", category: "eCommerce Tools", isPro: false },
  { id: 20, name: "Product Category Generator", slug: "product-category-generator", category: "eCommerce Tools", isPro: false },
  { id: 21, name: "Product Tag Generator", slug: "product-tag-generator", category: "eCommerce Tools", isPro: false },
  { id: 22, name: "Product Attribute Generator", slug: "product-attribute-generator", category: "eCommerce Tools", isPro: false },
  { id: 23, name: "Product Variant Generator", slug: "product-variant-generator", category: "eCommerce Tools", isPro: false },
  { id: 24, name: "Product Review Request Generator", slug: "product-review-request-generator", category: "eCommerce Tools", isPro: false },
  { id: 25, name: "Product Review Response Generator", slug: "product-review-response-generator", category: "eCommerce Tools", isPro: false },
  { id: 26, name: "Product FAQ Generator", slug: "product-faq-generator", category: "eCommerce Tools", isPro: false },
  { id: 27, name: "Product Comparison Generator", slug: "product-comparison-generator", category: "eCommerce Tools", isPro: false },
  { id: 28, name: "Product Bundle Generator", slug: "product-bundle-generator", category: "eCommerce Tools", isPro: false },
  { id: 29, name: "Product Naming Tool", slug: "product-naming-tool", category: "eCommerce Tools", isPro: false },
  { id: 30, name: "Product Margin Calculator", slug: "product-margin-calculator", category: "eCommerce Tools", isPro: false },
  { id: 31, name: "Product Markup Calculator", slug: "product-markup-calculator", category: "eCommerce Tools", isPro: false },
  { id: 32, name: "Discount Price Calculator", slug: "discount-price-calculator", category: "eCommerce Tools", isPro: false },
  { id: 33, name: "Sale Price Calculator", slug: "sale-price-calculator", category: "eCommerce Tools", isPro: false },
  { id: 34, name: "Wholesale Price Calculator", slug: "wholesale-price-calculator", category: "eCommerce Tools", isPro: false },
  { id: 35, name: "Retail Price Calculator", slug: "retail-price-calculator", category: "eCommerce Tools", isPro: false },
  { id: 36, name: "Free Shipping Threshold Calculator", slug: "free-shipping-threshold-calculator", category: "eCommerce Tools", isPro: false },
  { id: 37, name: "Break-Even Product Calculator", slug: "break-even-product-calculator", category: "eCommerce Tools", isPro: false },
  { id: 38, name: "Inventory Reorder Calculator", slug: "inventory-reorder-calculator", category: "eCommerce Tools", isPro: false },
  { id: 39, name: "Safety Stock Calculator", slug: "safety-stock-calculator", category: "eCommerce Tools", isPro: false },
  { id: 40, name: "Economic Order Quantity Calculator", slug: "economic-order-quantity-calculator", category: "eCommerce Tools", isPro: false },
  { id: 41, name: "Stock Turnover Calculator", slug: "stock-turnover-calculator", category: "eCommerce Tools", isPro: false },
  { id: 42, name: "Sell-Through Rate Calculator", slug: "sell-through-rate-calculator", category: "eCommerce Tools", isPro: false },
  { id: 43, name: "Conversion Rate Calculator", slug: "conversion-rate-calculator", category: "eCommerce Tools", isPro: false },
  { id: 44, name: "Average Order Value Calculator", slug: "average-order-value-calculator", category: "eCommerce Tools", isPro: false },
  { id: 45, name: "Customer Acquisition Cost Calculator", slug: "customer-acquisition-cost-calculator", category: "eCommerce Tools", isPro: false },
  { id: 46, name: "Return Rate Calculator", slug: "return-rate-calculator", category: "eCommerce Tools", isPro: false },
  { id: 47, name: "Refund Rate Calculator", slug: "refund-rate-calculator", category: "eCommerce Tools", isPro: false },
  { id: 48, name: "Cart Abandonment Calculator", slug: "cart-abandonment-calculator", category: "eCommerce Tools", isPro: false },
  { id: 49, name: "Revenue Calculator", slug: "revenue-calculator-ecommerce", category: "eCommerce Tools", isPro: false },
  { id: 50, name: "Ecommerce ROI Calculator", slug: "ecommerce-roi-calculator", category: "eCommerce Tools", isPro: false },
  { id: 51, name: "Ecommerce Profit Calculator", slug: "ecommerce-profit-calculator", category: "eCommerce Tools", isPro: false },
  { id: 52, name: "Marketplace Fee Calculator", slug: "marketplace-fee-calculator", category: "eCommerce Tools", isPro: false },
  { id: 53, name: "Payment Processing Fee Calculator", slug: "payment-processing-fee-calculator", category: "eCommerce Tools", isPro: false },
  { id: 54, name: "WooCommerce Cost Calculator", slug: "woocommerce-cost-calculator", category: "eCommerce Tools", isPro: false },
  { id: 55, name: "Shipping Rate Comparison Calculator", slug: "shipping-rate-comparison-calculator", category: "eCommerce Tools", isPro: false },
  { id: 56, name: "Product Dimension Calculator", slug: "product-dimension-calculator", category: "eCommerce Tools", isPro: false },
  { id: 57, name: "Volumetric Weight Calculator", slug: "volumetric-weight-calculator", category: "eCommerce Tools", isPro: false },
  { id: 58, name: "Package Weight Calculator", slug: "package-weight-calculator", category: "eCommerce Tools", isPro: false },
  { id: 59, name: "Order Profit Calculator", slug: "order-profit-calculator", category: "eCommerce Tools", isPro: false },
  { id: 60, name: "Ecommerce Sales Forecast Calculator", slug: "ecommerce-sales-forecast-calculator", category: "eCommerce Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Product Research Analyzer", slug: "product-research-analyzer", category: "eCommerce Tools", isPro: true },
  { id: 62, name: "Competitor Price Monitor", slug: "competitor-price-monitor", category: "eCommerce Tools", isPro: true },
  { id: 63, name: "Product Review Analyzer", slug: "product-review-analyzer", category: "eCommerce Tools", isPro: true },
  { id: 64, name: "Demand Forecasting Tool", slug: "demand-forecasting-tool", category: "eCommerce Tools", isPro: true },
  { id: 65, name: "Product Feed Validator", slug: "product-feed-validator", category: "eCommerce Tools", isPro: true },
  { id: 66, name: "Product Demand Analyzer", slug: "product-demand-analyzer", category: "eCommerce Tools", isPro: true },
  { id: 67, name: "Product Competition Analyzer", slug: "product-competition-analyzer", category: "eCommerce Tools", isPro: true },
  { id: 68, name: "Product Opportunity Score", slug: "product-opportunity-score", category: "eCommerce Tools", isPro: true },
  { id: 69, name: "Product Market Gap Analyzer", slug: "product-market-gap-analyzer", category: "eCommerce Tools", isPro: true },
  { id: 70, name: "Competitor Product Analyzer", slug: "competitor-product-analyzer", category: "eCommerce Tools", isPro: true },
  { id: 71, name: "Competitor Store Analyzer", slug: "competitor-store-analyzer", category: "eCommerce Tools", isPro: true },
  { id: 72, name: "Review Sentiment Analyzer", slug: "review-sentiment-analyzer", category: "eCommerce Tools", isPro: true },
  { id: 73, name: "Review Keyword Extractor", slug: "review-keyword-extractor", category: "eCommerce Tools", isPro: true },
  { id: 74, name: "Product Pricing Intelligence Tool", slug: "product-pricing-intelligence-tool", category: "eCommerce Tools", isPro: true },
  { id: 75, name: "Dynamic Pricing Simulator", slug: "dynamic-pricing-simulator", category: "eCommerce Tools", isPro: true },
  { id: 76, name: "Price Elasticity Calculator", slug: "price-elasticity-calculator", category: "eCommerce Tools", isPro: true },
  { id: 77, name: "Inventory Forecasting Tool", slug: "inventory-forecasting-tool", category: "eCommerce Tools", isPro: true },
  { id: 78, name: "Stockout Risk Calculator", slug: "stockout-risk-calculator", category: "eCommerce Tools", isPro: true },
  { id: 79, name: "Overstock Risk Calculator", slug: "overstock-risk-calculator", category: "eCommerce Tools", isPro: true },
  { id: 80, name: "Reorder Point Optimizer", slug: "reorder-point-optimizer", category: "eCommerce Tools", isPro: true },
  { id: 81, name: "Inventory ABC Analyzer", slug: "inventory-abc-analyzer", category: "eCommerce Tools", isPro: true },
  { id: 82, name: "Purchase Order Generator", slug: "purchase-order-generator", category: "eCommerce Tools", isPro: true },
  { id: 83, name: "Supplier Comparison Tool", slug: "supplier-comparison-tool", category: "eCommerce Tools", isPro: true },
  { id: 84, name: "Supplier Quote Analyzer", slug: "supplier-quote-analyzer", category: "eCommerce Tools", isPro: true },
  { id: 85, name: "Wholesale Margin Analyzer", slug: "wholesale-margin-analyzer", category: "eCommerce Tools", isPro: true },
  { id: 86, name: "Marketplace Profit Analyzer", slug: "marketplace-profit-analyzer", category: "eCommerce Tools", isPro: true },
  { id: 87, name: "Multi-Marketplace Fee Analyzer", slug: "multi-marketplace-fee-analyzer", category: "eCommerce Tools", isPro: true },
  { id: 88, name: "Ecommerce Cohort Analyzer", slug: "ecommerce-cohort-analyzer", category: "eCommerce Tools", isPro: true },
  { id: 89, name: "Customer Retention Analyzer", slug: "customer-retention-analyzer", category: "eCommerce Tools", isPro: true },
  { id: 90, name: "Repeat Purchase Rate Analyzer", slug: "repeat-purchase-rate-analyzer", category: "eCommerce Tools", isPro: true },
  { id: 91, name: "Customer Lifetime Value Analyzer", slug: "customer-lifetime-value-analyzer-pro", category: "eCommerce Tools", isPro: true },
  { id: 92, name: "Ecommerce Funnel Analyzer", slug: "ecommerce-funnel-analyzer", category: "eCommerce Tools", isPro: true },
  { id: 93, name: "Product Conversion Optimizer", slug: "product-conversion-optimizer", category: "eCommerce Tools", isPro: true },
  { id: 94, name: "Cart Abandonment Analyzer", slug: "cart-abandonment-analyzer", category: "eCommerce Tools", isPro: true },
  { id: 95, name: "Ecommerce Pricing Experiment Tool", slug: "ecommerce-pricing-experiment-tool", category: "eCommerce Tools", isPro: true },
  { id: 96, name: "Product Feed Optimizer", slug: "product-feed-optimizer", category: "eCommerce Tools", isPro: true },
  { id: 97, name: "Google Shopping Feed Generator", slug: "google-shopping-feed-generator", category: "eCommerce Tools", isPro: true },
  { id: 98, name: "Merchant Center Feed Checker", slug: "merchant-center-feed-checker", category: "eCommerce Tools", isPro: true },
  { id: 99, name: "Ecommerce Analytics Dashboard", slug: "ecommerce-analytics-dashboard", category: "eCommerce Tools", isPro: true },
  { id: 100, name: "Ecommerce Profit Intelligence Dashboard", slug: "ecommerce-profit-intelligence-dashboard", category: "eCommerce Tools", isPro: true },
];