export interface Tool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const energySustainabilityToolsList: Tool[] = [
  // --- 🔥 PRIORITY 20 FREE TOOLS (isPro: false) ---
  { id: 1, name: "Carbon Footprint Calculator", slug: "carbon-footprint-calculator-sustainability", category: "Energy & Sustainability Tools", isPro: false },
  { id: 2, name: "Solar Panel ROI Calculator", slug: "solar-panel-roi-calculator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 3, name: "Energy Consumption Cost Estimator", slug: "energy-consumption-cost-estimator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 4, name: "Scope 1 GHG Emissions Calculator", slug: "scope-1-ghg-emissions-calculator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 5, name: "Scope 2 GHG Emissions Calculator", slug: "scope-2-ghg-emissions-calculator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 6, name: "Scope 3 Supply Chain Emissions Calculator", slug: "scope-3-supply-chain-emissions-calculator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 7, name: "Commercial Energy Audit Calculator", slug: "commercial-energy-audit-calculator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 8, name: "LED Lighting Energy Savings Calculator", slug: "led-lighting-energy-savings-calculator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 9, name: "EV Fleet Savings Calculator", slug: "ev-fleet-savings-calculator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 10, name: "HVAC Energy Efficiency Calculator", slug: "hvac-energy-efficiency-calculator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 11, name: "Water Conservation Savings Estimator", slug: "water-conservation-savings-estimator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 12, name: "Waste Diversion Rate Calculator", slug: "waste-diversion-rate-calculator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 13, name: "Renewable Energy Payback Calculator", slug: "renewable-energy-payback-calculator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 14, name: "Carbon Offset Cost Calculator", slug: "carbon-offset-cost-calculator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 15, name: "Building Energy Star Score Estimator", slug: "building-energy-star-score-estimator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 16, name: "Peak Demand Charge Calculator", slug: "peak-demand-charge-calculator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 17, name: "Power Factor Penalty Calculator", slug: "power-factor-penalty-calculator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 18, name: "Green Business Checklist", slug: "green-business-checklist", category: "Energy & Sustainability Tools", isPro: false },
  { id: 19, name: "ESG Compliance Readiness Checklist", slug: "esg-compliance-readiness-checklist", category: "Energy & Sustainability Tools", isPro: false },
  { id: 20, name: "Corporate Sustainability Assessment Tool", slug: "corporate-sustainability-assessment-tool", category: "Energy & Sustainability Tools", isPro: false },

  // --- CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Wind Turbine Output Estimator", slug: "wind-turbine-output-estimator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 22, name: "Battery Energy Storage Payback Tool", slug: "battery-energy-storage-payback-tool", category: "Energy & Sustainability Tools", isPro: false },
  { id: 23, name: "Compressed Air Energy Loss Calculator", slug: "compressed-air-energy-loss-calculator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 24, name: "Boiler Efficiency Calculator", slug: "boiler-efficiency-calculator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 25, name: "Paper Waste Reduction Estimator", slug: "paper-waste-reduction-estimator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 26, name: "Single-Use Plastic Reduction Tracker", slug: "single-use-plastic-reduction-tracker", category: "Energy & Sustainability Tools", isPro: false },
  { id: 27, name: "Data Center PUE Calculator", slug: "data-center-pue-calculator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 28, name: "Green Commute Emissions Savings Calculator", slug: "green-commute-emissions-savings-calculator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 29, name: "Landfill Waste Cost Calculator", slug: "landfill-waste-cost-calculator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 30, name: "Corporate Travel Emissions Calculator", slug: "corporate-travel-emissions-calculator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 31, name: "Solar Battery Sizing Calculator", slug: "solar-battery-sizing-calculator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 32, name: "Thermal Insulation Heat Loss Calculator", slug: "thermal-insulation-heat-loss-calculator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 33, name: "Smart Thermostat Energy Savings Tool", slug: "smart-thermostat-energy-savings-tool", category: "Energy & Sustainability Tools", isPro: false },
  { id: 34, name: "Rainwater Harvesting Yield Calculator", slug: "rainwater-harvesting-yield-calculator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 35, name: "Zero-Waste Event Planner", slug: "zero-waste-event-planner", category: "Energy & Sustainability Tools", isPro: false },
  { id: 36, name: "Composting Benefit Calculator", slug: "composting-benefit-calculator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 37, name: "Energy Unit Conversion Tool", slug: "energy-unit-conversion-tool-sustainability", category: "Energy & Sustainability Tools", isPro: false },
  { id: 38, name: "Carbon Tax Impact Estimator", slug: "carbon-tax-impact-estimator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 39, name: "REC Value Calculator", slug: "rec-value-calculator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 40, name: "Appliance Phantom Load Calculator", slug: "appliance-phantom-load-calculator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 41, name: "Tree Planting Carbon Offset Estimator", slug: "tree-planting-carbon-offset-estimator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 42, name: "Green Packaging Cost Impact Calculator", slug: "green-packaging-cost-impact-calculator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 43, name: "Facility Water Footprint Tool", slug: "facility-water-footprint-tool", category: "Energy & Sustainability Tools", isPro: false },
  { id: 44, name: "Cogeneration (CHP) Savings Calculator", slug: "cogeneration-chp-savings-calculator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 45, name: "Geothermal Heat Pump ROI Calculator", slug: "geothermal-heat-pump-roi-calculator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 46, name: "Industrial Waste Heat Recovery Estimator", slug: "industrial-waste-heat-recovery-estimator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 47, name: "Sustainable Procurement Checklist", slug: "sustainable-procurement-checklist", category: "Energy & Sustainability Tools", isPro: false },
  { id: 48, name: "LEED Certification Scorecard Estimator", slug: "leed-certification-scorecard-estimator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 49, name: "Energy Tariff Comparison Tool", slug: "energy-tariff-comparison-tool", category: "Energy & Sustainability Tools", isPro: false },
  { id: 50, name: "Circular Economy Lifecycle Matrix", slug: "circular-economy-lifecycle-matrix", category: "Energy & Sustainability Tools", isPro: false },
  { id: 51, name: "Sustainable Office Checklist", slug: "sustainable-office-checklist", category: "Energy & Sustainability Tools", isPro: false },
  { id: 52, name: "Eco-Friendly Supplier Evaluation Tool", slug: "eco-friendly-supplier-evaluation-tool", category: "Energy & Sustainability Tools", isPro: false },
  { id: 53, name: "Natural Gas to Electric Conversion Estimator", slug: "natural-gas-to-electric-conversion-estimator", category: "Energy & Sustainability Tools", isPro: false },
  { id: 54, name: "Solar Inverter Efficiency Tool", slug: "solar-inverter-efficiency-tool", category: "Energy & Sustainability Tools", isPro: false },
  { id: 55, name: "GHG Equivalency Converter", slug: "ghg-equivalency-converter", category: "Energy & Sustainability Tools", isPro: false },
  { id: 56, name: "Corporate Carbon Target Roadmap Planner", slug: "corporate-carbon-target-roadmap-planner", category: "Energy & Sustainability Tools", isPro: false },
  { id: 57, name: "Sustainability Audit Log", slug: "sustainability-audit-log", category: "Energy & Sustainability Tools", isPro: false },
  { id: 58, name: "ISO 50001 Energy Checklist", slug: "iso-50001-energy-checklist", category: "Energy & Sustainability Tools", isPro: false },
  { id: 59, name: "Environmental Incident Log", slug: "environmental-incident-log", category: "Energy & Sustainability Tools", isPro: false },
  { id: 60, name: "Facility Decarbonization Checklist", slug: "facility-decarbonization-checklist", category: "Energy & Sustainability Tools", isPro: false },

  // --- ⚡ PRO / SAAS TOOLS (61-100) ---
  { id: 61, name: "Enterprise Carbon Accounting Workspace", slug: "enterprise-carbon-accounting-workspace", category: "Energy & Sustainability Tools", isPro: true },
  { id: 62, name: "ESG Reporting & Disclosure Hub", slug: "esg-reporting-disclosure-hub", category: "Energy & Sustainability Tools", isPro: true },
  { id: 63, name: "Facility Energy Intelligence Engine", slug: "facility-energy-intelligence-engine", category: "Energy & Sustainability Tools", isPro: true },
  { id: 64, name: "Multi-Site Decarbonization Dashboard", slug: "multi-site-decarbonization-dashboard", category: "Energy & Sustainability Tools", isPro: true },
  { id: 65, name: "Scope 1, 2, 3 Emissions Automation Hub", slug: "scope-1-2-3-emissions-automation-hub", category: "Energy & Sustainability Tools", isPro: true },
  { id: 66, name: "Corporate Net-Zero Modeling Workspace", slug: "corporate-net-zero-modeling-workspace", category: "Energy & Sustainability Tools", isPro: true },
  { id: 67, name: "Renewable Energy Portfolio Manager", slug: "renewable-energy-portfolio-manager", category: "Energy & Sustainability Tools", isPro: true },
  { id: 68, name: "Automated Utility Bill Scraping Engine", slug: "automated-utility-bill-scraping-engine", category: "Energy & Sustainability Tools", isPro: true },
  { id: 69, name: "Supply Chain ESG Risk Radar", slug: "supply-chain-esg-risk-radar", category: "Energy & Sustainability Tools", isPro: true },
  { id: 70, name: "Water & Waste Resource Management Hub", slug: "water-waste-resource-management-hub", category: "Energy & Sustainability Tools", isPro: true },
  { id: 71, name: "Real-Time Power Demand Optimization Tool", slug: "real-time-power-demand-optimization-tool", category: "Energy & Sustainability Tools", isPro: true },
  { id: 72, name: "Corporate Carbon Offset Portfolio Manager", slug: "corporate-carbon-offset-portfolio-manager", category: "Energy & Sustainability Tools", isPro: true },
  { id: 73, name: "Sustainability KPI & Target Dashboard", slug: "sustainability-kpi-target-dashboard", category: "Energy & Sustainability Tools", isPro: true },
  { id: 74, name: "AI Energy Anomaly Detection Engine", slug: "ai-energy-anomaly-detection-engine", category: "Energy & Sustainability Tools", isPro: true },
  { id: 75, name: "Climate Risk Scenario Analysis Tool", slug: "climate-risk-scenario-analysis-tool", category: "Energy & Sustainability Tools", isPro: true },
  { id: 76, name: "Green Building Certification Manager", slug: "green-building-certification-manager", category: "Energy & Sustainability Tools", isPro: true },
  { id: 77, name: "Circular Economy Material Flow Tracker", slug: "circular-economy-material-flow-tracker", category: "Energy & Sustainability Tools", isPro: true },
  { id: 78, name: "Corporate Decarbonization Capex Planner", slug: "corporate-decarbonization-capex-planner", category: "Energy & Sustainability Tools", isPro: true },
  { id: 79, name: "Solar & Storage Microgrid Optimizer", slug: "solar-storage-microgrid-optimizer", category: "Energy & Sustainability Tools", isPro: true },
  { id: 80, name: "CSRD & SEC Climate Disclosure Generator", slug: "csrd-sec-climate-disclosure-generator", category: "Energy & Sustainability Tools", isPro: true },
  { id: 81, name: "Energy Procurement & Hedging Platform", slug: "energy-procurement-hedging-platform", category: "Energy & Sustainability Tools", isPro: true },
  { id: 82, name: "Fleet Electrification Transition Workspace", slug: "fleet-electrification-transition-workspace", category: "Energy & Sustainability Tools", isPro: true },
  { id: 83, name: "Environmental Compliance Audit Engine", slug: "environmental-compliance-audit-engine", category: "Energy & Sustainability Tools", isPro: true },
  { id: 84, name: "Product Life Cycle Carbon Assessment (LCA)", slug: "product-life-cycle-carbon-assessment-lca", category: "Energy & Sustainability Tools", isPro: true },
  { id: 85, name: "Sustainable Supply Chain Scorecard Platform", slug: "sustainable-supply-chain-scorecard-platform", category: "Energy & Sustainability Tools", isPro: true },
  { id: 86, name: "Energy Peak Shaving Optimization Hub", slug: "energy-peak-shaving-optimization-hub", category: "Energy & Sustainability Tools", isPro: true },
  { id: 87, name: "Executive Sustainability Dashboard Pro", slug: "executive-sustainability-dashboard-pro", category: "Energy & Sustainability Tools", isPro: true },
  { id: 88, name: "Carbon Tax & Compliance Forecaster", slug: "carbon-tax-compliance-forecaster", category: "Energy & Sustainability Tools", isPro: true },
  { id: 89, name: "Zero-Waste Corporate Audit Workspace", slug: "zero-waste-corporate-audit-workspace", category: "Energy & Sustainability Tools", isPro: true },
  { id: 90, name: "Sustainability Workflow Automation Engine", slug: "sustainability-workflow-automation-engine", category: "Energy & Sustainability Tools", isPro: true },
  { id: 91, name: "Energy Data Migration & Importer", slug: "energy-data-migration-importer", category: "Energy & Sustainability Tools", isPro: true },
  { id: 92, name: "ESG Data Export & Verification Hub", slug: "esg-data-export-verification-hub", category: "Energy & Sustainability Tools", isPro: true },
  { id: 93, name: "Smart Meter IoT & Energy API Hub", slug: "smart-meter-iot-energy-api-hub", category: "Energy & Sustainability Tools", isPro: true },
  { id: 94, name: "Grid Carbon Intensity Sync Engine", slug: "grid-carbon-intensity-sync-engine", category: "Energy & Sustainability Tools", isPro: true },
  { id: 95, name: "High Energy Consumption Alert Engine", slug: "high-energy-consumption-alert-engine", category: "Energy & Sustainability Tools", isPro: true },
  { id: 96, name: "Sustainability AI Analytics Copilot", slug: "sustainability-ai-analytics-copilot", category: "Energy & Sustainability Tools", isPro: true },
  { id: 97, name: "Corporate Decarbonization Intelligence Hub", slug: "corporate-decarbonization-intelligence-hub", category: "Energy & Sustainability Tools", isPro: true },
  { id: 98, name: "Enterprise ESG Operations Platform", slug: "enterprise-esg-operations-platform", category: "Energy & Sustainability Tools", isPro: true },
  { id: 99, name: "Global Sustainability Command Center", slug: "global-sustainability-command-center", category: "Energy & Sustainability Tools", isPro: true },
  { id: 100, name: "Net-Zero Enterprise Platform Pro", slug: "net-zero-enterprise-platform-pro", category: "Energy & Sustainability Tools", isPro: true }
];