export interface Tool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const eventManagementToolsList: Tool[] = [
  // --- 🔥 PRIORITY 20 FREE TOOLS (isPro: false) ---
  { id: 1, name: "Event Budget Calculator", slug: "event-budget-calculator", category: "Event Management & Planning Tools", isPro: false },
  { id: 2, name: "Guest List Estimator", slug: "guest-list-estimator", category: "Event Management & Planning Tools", isPro: false },
  { id: 3, name: "Venue Capacity Planner", slug: "venue-capacity-planner", category: "Event Management & Planning Tools", isPro: false },
  { id: 4, name: "Catering Quantity Calculator", slug: "catering-quantity-calculator", category: "Event Management & Planning Tools", isPro: false },
  { id: 5, name: "Beverage Quantity Estimator", slug: "beverage-quantity-estimator", category: "Event Management & Planning Tools", isPro: false },
  { id: 6, name: "Event Ticket Pricing Calculator", slug: "event-ticket-pricing-calculator", category: "Event Management & Planning Tools", isPro: false },
  { id: 7, name: "Speaker Fee Calculator", slug: "speaker-fee-calculator", category: "Event Management & Planning Tools", isPro: false },
  { id: 8, name: "Sponsorship ROI Estimator", slug: "sponsorship-roi-estimator", category: "Event Management & Planning Tools", isPro: false },
  { id: 9, name: "Event Timeline Generator", slug: "event-timeline-generator", category: "Event Management & Planning Tools", isPro: false },
  { id: 10, name: "AV Equipment Checklist", slug: "av-equipment-checklist", category: "Event Management & Planning Tools", isPro: false },
  { id: 11, name: "Seating Chart Planner", slug: "seating-chart-planner", category: "Event Management & Planning Tools", isPro: false },
  { id: 12, name: "Event Wi-Fi Bandwidth Calculator", slug: "event-wi-fi-bandwidth-calculator", category: "Event Management & Planning Tools", isPro: false },
  { id: 13, name: "Event Break-Even Calculator", slug: "event-break-even-calculator", category: "Event Management & Planning Tools", isPro: false },
  { id: 14, name: "Staffing Requirements Estimator", slug: "staffing-requirements-estimator-event", category: "Event Management & Planning Tools", isPro: false },
  { id: 15, name: "Event Lighting Calculator", slug: "event-lighting-calculator", category: "Event Management & Planning Tools", isPro: false },
  { id: 16, name: "Stage Size Calculator", slug: "stage-size-calculator", category: "Event Management & Planning Tools", isPro: false },
  { id: 17, name: "Event Marketing ROI Calculator", slug: "event-marketing-roi-calculator", category: "Event Management & Planning Tools", isPro: false },
  { id: 18, name: "Swag Bag Cost Calculator", slug: "swag-bag-cost-calculator", category: "Event Management & Planning Tools", isPro: false },
  { id: 19, name: "Event Registration Pace Calculator", slug: "event-registration-pace-calculator", category: "Event Management & Planning Tools", isPro: false },
  { id: 20, name: "VIP Invite Ratio Calculator", slug: "vip-invite-ratio-calculator", category: "Event Management & Planning Tools", isPro: false },

  // --- CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Event Planner Checklist", slug: "event-planner-checklist", category: "Event Management & Planning Tools", isPro: false },
  { id: 22, name: "Conference Agenda Builder", slug: "conference-agenda-builder", category: "Event Management & Planning Tools", isPro: false },
  { id: 23, name: "Trade Show Booth ROI Calculator", slug: "trade-show-booth-roi-calculator", category: "Event Management & Planning Tools", isPro: false },
  { id: 24, name: "Event App Engagement Estimator", slug: "event-app-engagement-estimator", category: "Event Management & Planning Tools", isPro: false },
  { id: 25, name: "Hybrid Event Cost Calculator", slug: "hybrid-event-cost-calculator", category: "Event Management & Planning Tools", isPro: false },
  { id: 26, name: "Virtual Event Bandwidth Tester", slug: "virtual-event-bandwidth-tester", category: "Event Management & Planning Tools", isPro: false },
  { id: 27, name: "Event Feedback Score Calculator", slug: "event-feedback-score-calculator", category: "Event Management & Planning Tools", isPro: false },
  { id: 28, name: "Post-Event Survey Analyzer", slug: "post-event-survey-analyzer", category: "Event Management & Planning Tools", isPro: false },
  { id: 29, name: "Name Badge Generator", slug: "name-badge-generator", category: "Event Management & Planning Tools", isPro: false },
  { id: 30, name: "Lanyard Size Guide", slug: "lanyard-size-guide", category: "Event Management & Planning Tools", isPro: false },
  { id: 31, name: "Table Centerpiece Cost Calculator", slug: "table-centerpiece-cost-calculator", category: "Event Management & Planning Tools", isPro: false },
  { id: 32, name: "Event Floral Budgeter", slug: "event-floral-budgeter", category: "Event Management & Planning Tools", isPro: false },
  { id: 33, name: "Dance Floor Size Calculator", slug: "dance-floor-size-calculator", category: "Event Management & Planning Tools", isPro: false },
  { id: 34, name: "Tent Size Estimator", slug: "tent-size-estimator", category: "Event Management & Planning Tools", isPro: false },
  { id: 35, name: "Event Security Staffing Calculator", slug: "event-security-staffing-calculator", category: "Event Management & Planning Tools", isPro: false },
  { id: 36, name: "Valet Parking Capacity Planner", slug: "valet-parking-capacity-planner", category: "Event Management & Planning Tools", isPro: false },
  { id: 37, name: "Coat Check Staffing Calculator", slug: "coat-check-staffing-calculator", category: "Event Management & Planning Tools", isPro: false },
  { id: 38, name: "Restroom Requirement Estimator", slug: "restroom-requirement-estimator", category: "Event Management & Planning Tools", isPro: false },
  { id: 39, name: "Power Drop Calculator", slug: "power-drop-calculator", category: "Event Management & Planning Tools", isPro: false },
  { id: 40, name: "Generator Sizing Tool", slug: "generator-sizing-tool", category: "Event Management & Planning Tools", isPro: false },
  { id: 41, name: "Stage Rigging Weight Calculator", slug: "stage-rigging-weight-calculator", category: "Event Management & Planning Tools", isPro: false },
  { id: 42, name: "Event Drone Permit Checker", slug: "event-drone-permit-checker", category: "Event Management & Planning Tools", isPro: false },
  { id: 43, name: "Temporary Wi-Fi Cost Estimator", slug: "temporary-wi-fi-cost-estimator", category: "Event Management & Planning Tools", isPro: false },
  { id: 44, name: "Event Videography Budgeter", slug: "event-videography-budgeter", category: "Event Management & Planning Tools", isPro: false },
  { id: 45, name: "Photography Shot List Generator", slug: "photography-shot-list-generator", category: "Event Management & Planning Tools", isPro: false },
  { id: 46, name: "Event PR Timeline Builder", slug: "event-pr-timeline-builder", category: "Event Management & Planning Tools", isPro: false },
  { id: 47, name: "Press Release Reach Estimator", slug: "press-release-reach-estimator", category: "Event Management & Planning Tools", isPro: false },
  { id: 48, name: "Media Credential Manager", slug: "media-credential-manager", category: "Event Management & Planning Tools", isPro: false },
  { id: 49, name: "Green Room Requirements Planner", slug: "green-room-requirements-planner", category: "Event Management & Planning Tools", isPro: false },
  { id: 50, name: "Speaker Rider Checklist", slug: "speaker-rider-checklist", category: "Event Management & Planning Tools", isPro: false },
  { id: 51, name: "Talent Rider Cost Calculator", slug: "talent-rider-cost-calculator", category: "Event Management & Planning Tools", isPro: false },
  { id: 52, name: "Event Transport Logistics Planner", slug: "event-transport-logistics-planner", category: "Event Management & Planning Tools", isPro: false },
  { id: 53, name: "Shuttle Bus Capacity Estimator", slug: "shuttle-bus-capacity-estimator", category: "Event Management & Planning Tools", isPro: false },
  { id: 54, name: "Flight Carbon Offset Calculator", slug: "flight-carbon-offset-calculator", category: "Event Management & Planning Tools", isPro: false },
  { id: 55, name: "Hotel Block Room Calculator", slug: "hotel-block-room-calculator", category: "Event Management & Planning Tools", isPro: false },
  { id: 56, name: "Attrition Rate Estimator", slug: "attrition-rate-estimator", category: "Event Management & Planning Tools", isPro: false },
  { id: 57, name: "Event Liability Insurance Calculator", slug: "event-liability-insurance-calculator", category: "Event Management & Planning Tools", isPro: false },
  { id: 58, name: "Permit Fee Estimator", slug: "permit-fee-estimator", category: "Event Management & Planning Tools", isPro: false },
  { id: 59, name: "Liquor License Cost Calculator", slug: "liquor-license-cost-calculator", category: "Event Management & Planning Tools", isPro: false },
  { id: 60, name: "Sound Permit Decibel Limit Checker", slug: "sound-permit-decibel-limit-checker", category: "Event Management & Planning Tools", isPro: false },

  // --- ⚡ PRO / SAAS TOOLS (61-100) ---
  { id: 61, name: "Enterprise Event Management Workspace", slug: "enterprise-event-management-workspace", category: "Event Management & Planning Tools", isPro: true },
  { id: 62, name: "Global Conference Planning Platform", slug: "global-conference-planning-platform", category: "Event Management & Planning Tools", isPro: true },
  { id: 63, name: "Virtual Event Streaming Dashboard", slug: "virtual-event-streaming-dashboard", category: "Event Management & Planning Tools", isPro: true },
  { id: 64, name: "Hybrid Event Production Workspace", slug: "hybrid-event-production-workspace", category: "Event Management & Planning Tools", isPro: true },
  { id: 65, name: "Trade Show Lead Retrieval System", slug: "trade-show-lead-retrieval-system", category: "Event Management & Planning Tools", isPro: true },
  { id: 66, name: "Event Sponsorship Management Pro", slug: "event-sponsorship-management-pro", category: "Event Management & Planning Tools", isPro: true },
  { id: 67, name: "VIP Guest Lifecycle Manager", slug: "vip-guest-lifecycle-manager", category: "Event Management & Planning Tools", isPro: true },
  { id: 68, name: "Automated Event Ticketing Engine", slug: "automated-event-ticketing-engine", category: "Event Management & Planning Tools", isPro: true },
  { id: 69, name: "Event Marketing Automation Hub", slug: "event-marketing-automation-hub", category: "Event Management & Planning Tools", isPro: true },
  { id: 70, name: "Real-Time Event Analytics Dashboard", slug: "real-time-event-analytics-dashboard", category: "Event Management & Planning Tools", isPro: true },
  { id: 71, name: "Enterprise Venue Sourcing Platform", slug: "enterprise-venue-sourcing-platform", category: "Event Management & Planning Tools", isPro: true },
  { id: 72, name: "B2B Matchmaking Event Platform", slug: "b2b-matchmaking-event-platform", category: "Event Management & Planning Tools", isPro: true },
  { id: 73, name: "Event Budget Tracking Pro", slug: "event-budget-tracking-pro", category: "Event Management & Planning Tools", isPro: true },
  { id: 74, name: "Post-Event ROI Intelligence Engine", slug: "post-event-roi-intelligence-engine", category: "Event Management & Planning Tools", isPro: true },
  { id: 75, name: "Event Speaker Management Workspace", slug: "event-speaker-management-workspace", category: "Event Management & Planning Tools", isPro: true },
  { id: 76, name: "Call for Papers (CFP) Automation", slug: "call-for-papers-cfp-automation", category: "Event Management & Planning Tools", isPro: true },
  { id: 77, name: "Event Abstract Review System", slug: "event-abstract-review-system", category: "Event Management & Planning Tools", isPro: true },
  { id: 78, name: "Event Accommodations & Housing Pro", slug: "event-accommodations-housing-pro", category: "Event Management & Planning Tools", isPro: true },
  { id: 79, name: "Enterprise Event Travel Planner", slug: "enterprise-event-travel-planner", category: "Event Management & Planning Tools", isPro: true },
  { id: 80, name: "Corporate Retreat Management Hub", slug: "corporate-retreat-management-hub", category: "Event Management & Planning Tools", isPro: true },
  { id: 81, name: "Festival Logistics & Operations Platform", slug: "festival-logistics-operations-platform", category: "Event Management & Planning Tools", isPro: true },
  { id: 82, name: "Mega-Event Security Planning Workspace", slug: "mega-event-security-planning-workspace", category: "Event Management & Planning Tools", isPro: true },
  { id: 83, name: "Event Floor Plan & CAD Builder", slug: "event-floor-plan-cad-builder", category: "Event Management & Planning Tools", isPro: true },
  { id: 84, name: "3D Venue Visualization Engine", slug: "3d-venue-visualization-engine", category: "Event Management & Planning Tools", isPro: true },
  { id: 85, name: "Exhibitor Portal & Manual Builder", slug: "exhibitor-portal-manual-builder", category: "Event Management & Planning Tools", isPro: true },
  { id: 86, name: "Sponsor Deliverables Tracking System", slug: "sponsor-deliverables-tracking-system", category: "Event Management & Planning Tools", isPro: true },
  { id: 87, name: "Event Sustainability Audit Workspace", slug: "event-sustainability-audit-workspace", category: "Event Management & Planning Tools", isPro: true },
  { id: 88, name: "Zero-Waste Event Carbon Tracker", slug: "zero-waste-event-carbon-tracker", category: "Event Management & Planning Tools", isPro: true },
  { id: 89, name: "Multi-Lingual Event App Builder", slug: "multi-lingual-event-app-builder", category: "Event Management & Planning Tools", isPro: true },
  { id: 90, name: "AI Event Networking Matchmaker", slug: "ai-event-networking-matchmaker", category: "Event Management & Planning Tools", isPro: true },
  { id: 91, name: "Contactless Check-In Kiosk System", slug: "contactless-check-in-kiosk-system", category: "Event Management & Planning Tools", isPro: true },
  { id: 92, name: "RFID Attendee Tracking Engine", slug: "rfid-attendee-tracking-engine", category: "Event Management & Planning Tools", isPro: true },
  { id: 93, name: "Event Lead Scoring & CRM Sync", slug: "event-lead-scoring-crm-sync", category: "Event Management & Planning Tools", isPro: true },
  { id: 94, name: "Enterprise Event Data Exporter", slug: "enterprise-event-data-exporter", category: "Event Management & Planning Tools", isPro: true },
  { id: 95, name: "Event Gamification Engine", slug: "event-gamification-engine", category: "Event Management & Planning Tools", isPro: true },
  { id: 96, name: "Live Q&A and Polling Platform", slug: "live-qa-and-polling-platform", category: "Event Management & Planning Tools", isPro: true },
  { id: 97, name: "Interactive Event Map Builder", slug: "interactive-event-map-builder", category: "Event Management & Planning Tools", isPro: true },
  { id: 98, name: "Multi-Session Track Manager", slug: "multi-session-track-manager", category: "Event Management & Planning Tools", isPro: true },
  { id: 99, name: "CEU Credit Tracker Engine", slug: "ceu-credit-tracker-engine", category: "Event Management & Planning Tools", isPro: true },
  { id: 100, name: "Executive Event Command Center", slug: "executive-event-command-center", category: "Event Management & Planning Tools", isPro: true }
];