export interface FileTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const fileToolsList: FileTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-13) ---
  { id: 1, name: "File Converter", slug: "file-converter", category: "File & Document Tools", isPro: false },
  { id: 2, name: "File Compressor", slug: "file-compressor", category: "File & Document Tools", isPro: false },
  { id: 3, name: "ZIP Creator", slug: "zip-creator", category: "File & Document Tools", isPro: false },
  { id: 4, name: "ZIP Extractor", slug: "zip-extractor", category: "File & Document Tools", isPro: false },
  { id: 5, name: "File Renamer", slug: "file-renamer", category: "File & Document Tools", isPro: false },
  { id: 6, name: "Batch File Renamer", slug: "batch-file-renamer", category: "File & Document Tools", isPro: false },
  { id: 7, name: "File Type Identifier", slug: "file-type-identifier", category: "File & Document Tools", isPro: false },
  { id: 8, name: "File Duplicate Finder", slug: "file-duplicate-finder", category: "File & Document Tools", isPro: false },
  { id: 9, name: "File Metadata Viewer", slug: "file-metadata-viewer", category: "File & Document Tools", isPro: false },
  { id: 10, name: "File Metadata Cleaner", slug: "file-metadata-cleaner", category: "File & Document Tools", isPro: false },
  { id: 11, name: "Document Text Extractor", slug: "document-text-extractor", category: "File & Document Tools", isPro: false },
  { id: 12, name: "Document Comparison Tool", slug: "document-comparison-tool-file", category: "File & Document Tools", isPro: false },
  { id: 13, name: "Document Merger", slug: "document-merger", category: "File & Document Tools", isPro: false },
  { id: 14, name: "Document Splitter", slug: "document-splitter", category: "File & Document Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (15-60) ---
  { id: 15, name: "File Decompressor", slug: "file-decompressor", category: "File & Document Tools", isPro: false },
  { id: 16, name: "TAR Creator", slug: "tar-creator", category: "File & Document Tools", isPro: false },
  { id: 17, name: "TAR Extractor", slug: "tar-extractor", category: "File & Document Tools", isPro: false },
  { id: 18, name: "GZIP Compressor", slug: "gzip-compressor", category: "File & Document Tools", isPro: false },
  { id: 19, name: "GZIP Decompressor", slug: "gzip-decompressor", category: "File & Document Tools", isPro: false },
  { id: 20, name: "7Z Extractor", slug: "7z-extractor", category: "File & Document Tools", isPro: false },
  { id: 21, name: "RAR Extractor", slug: "rar-extractor", category: "File & Document Tools", isPro: false },
  { id: 22, name: "File Extension Changer", slug: "file-extension-changer", category: "File & Document Tools", isPro: false },
  { id: 23, name: "MIME Type Checker", slug: "mime-type-checker", category: "File & Document Tools", isPro: false },
  { id: 24, name: "File Size Calculator", slug: "file-size-calculator", category: "File & Document Tools", isPro: false },
  { id: 25, name: "File Hash Generator", slug: "file-hash-generator", category: "File & Document Tools", isPro: false },
  { id: 26, name: "File Checksum Calculator", slug: "file-checksum-calculator", category: "File & Document Tools", isPro: false },
  { id: 27, name: "Duplicate File Scanner", slug: "duplicate-file-scanner", category: "File & Document Tools", isPro: false },
  { id: 28, name: "Large File Finder", slug: "large-file-finder", category: "File & Document Tools", isPro: false },
  { id: 29, name: "Document Metadata Cleaner", slug: "document-metadata-cleaner", category: "File & Document Tools", isPro: false },
  { id: 30, name: "File Timestamp Editor", slug: "file-timestamp-editor", category: "File & Document Tools", isPro: false },
  { id: 31, name: "File Permission Checker", slug: "file-permission-checker", category: "File & Document Tools", isPro: false },
  { id: 32, name: "File Encoding Detector", slug: "file-encoding-detector", category: "File & Document Tools", isPro: false },
  { id: 33, name: "Text File Converter", slug: "text-file-converter", category: "File & Document Tools", isPro: false },
  { id: 34, name: "CSV File Viewer", slug: "csv-file-viewer", category: "File & Document Tools", isPro: false },
  { id: 35, name: "TSV File Converter", slug: "tsv-file-converter", category: "File & Document Tools", isPro: false },
  { id: 36, name: "DOCX Converter", slug: "docx-converter", category: "File & Document Tools", isPro: false },
  { id: 37, name: "DOC Converter", slug: "doc-converter", category: "File & Document Tools", isPro: false },
  { id: 38, name: "RTF Converter", slug: "rtf-converter", category: "File & Document Tools", isPro: false },
  { id: 39, name: "ODT Converter", slug: "odt-converter", category: "File & Document Tools", isPro: false },
  { id: 40, name: "EPUB Converter", slug: "epub-converter", category: "File & Document Tools", isPro: false },
  { id: 41, name: "MOBI Converter", slug: "mobi-converter", category: "File & Document Tools", isPro: false },
  { id: 42, name: "TXT to DOCX Converter", slug: "txt-to-docx-converter", category: "File & Document Tools", isPro: false },
  { id: 43, name: "DOCX to TXT Converter", slug: "docx-to-txt-converter", category: "File & Document Tools", isPro: false },
  { id: 44, name: "DOCX to HTML Converter", slug: "docx-to-html-converter", category: "File & Document Tools", isPro: false },
  { id: 45, name: "HTML to DOCX Converter", slug: "html-to-docx-converter", category: "File & Document Tools", isPro: false },
  { id: 46, name: "Markdown to DOCX Converter", slug: "markdown-to-docx-converter", category: "File & Document Tools", isPro: false },
  { id: 47, name: "EPUB to PDF Converter", slug: "epub-to-pdf-converter", category: "File & Document Tools", isPro: false },
  { id: 48, name: "EPUB Metadata Editor", slug: "epub-metadata-editor", category: "File & Document Tools", isPro: false },
  { id: 49, name: "EPUB Cover Generator", slug: "epub-cover-generator", category: "File & Document Tools", isPro: false },
  { id: 50, name: "Document Page Counter", slug: "document-page-counter", category: "File & Document Tools", isPro: false },
  { id: 51, name: "Document Word Counter", slug: "document-word-counter", category: "File & Document Tools", isPro: false },
  { id: 52, name: "Document Image Extractor", slug: "document-image-extractor", category: "File & Document Tools", isPro: false },
  { id: 53, name: "Document Organizer", slug: "document-organizer", category: "File & Document Tools", isPro: false },
  { id: 54, name: "Document Naming Tool", slug: "document-naming-tool", category: "File & Document Tools", isPro: false },
  { id: 55, name: "Document Folder Generator", slug: "document-folder-generator", category: "File & Document Tools", isPro: false },
  { id: 56, name: "File List Generator", slug: "file-list-generator", category: "File & Document Tools", isPro: false },
  { id: 57, name: "Directory Tree Generator", slug: "directory-tree-generator", category: "File & Document Tools", isPro: false },
  { id: 58, name: "File Manifest Generator", slug: "file-manifest-generator", category: "File & Document Tools", isPro: false },
  { id: 59, name: "File Inventory Generator", slug: "file-inventory-generator", category: "File & Document Tools", isPro: false },
  { id: 60, name: "Document Checklist Generator", slug: "document-checklist-generator", category: "File & Document Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Document OCR Engine", slug: "document-ocr-engine", category: "File & Document Tools", isPro: true },
  { id: 62, name: "PII Document Scanner", slug: "pii-document-scanner", category: "File & Document Tools", isPro: true },
  { id: 63, name: "Document Redaction Engine", slug: "document-redaction-engine", category: "File & Document Tools", isPro: true },
  { id: 64, name: "Intelligent Document Search", slug: "intelligent-document-search", category: "File & Document Tools", isPro: true },
  { id: 65, name: "AI Document Extraction", slug: "ai-document-extraction", category: "File & Document Tools", isPro: true },
  { id: 66, name: "Enterprise Document Workspace", slug: "enterprise-document-workspace", category: "File & Document Tools", isPro: true },
  { id: 67, name: "Batch File Converter", slug: "batch-file-converter", category: "File & Document Tools", isPro: true },
  { id: 68, name: "Batch File Compressor", slug: "batch-file-compressor", category: "File & Document Tools", isPro: true },
  { id: 69, name: "Batch Metadata Cleaner", slug: "batch-metadata-cleaner", category: "File & Document Tools", isPro: true },
  { id: 70, name: "Multi-Format OCR", slug: "multi-format-ocr", category: "File & Document Tools", isPro: true },
  { id: 71, name: "Document Classification Tool", slug: "document-classification-tool", category: "File & Document Tools", isPro: true },
  { id: 72, name: "Document Entity Extractor", slug: "document-entity-extractor", category: "File & Document Tools", isPro: true },
  { id: 73, name: "Document Structure Analyzer", slug: "document-structure-analyzer", category: "File & Document Tools", isPro: true },
  { id: 74, name: "Document Similarity Analyzer", slug: "document-similarity-analyzer", category: "File & Document Tools", isPro: true },
  { id: 75, name: "Document Version Comparator", slug: "document-version-comparator", category: "File & Document Tools", isPro: true },
  { id: 76, name: "Document Change Tracker", slug: "document-change-tracker", category: "File & Document Tools", isPro: true },
  { id: 77, name: "Sensitive Information Finder", slug: "sensitive-information-finder", category: "File & Document Tools", isPro: true },
  { id: 78, name: "Document Compliance Scanner", slug: "document-compliance-scanner", category: "File & Document Tools", isPro: true },
  { id: 79, name: "Document Accessibility Scanner", slug: "document-accessibility-scanner", category: "File & Document Tools", isPro: true },
  { id: 80, name: "Document Quality Checker", slug: "document-quality-checker", category: "File & Document Tools", isPro: true },
  { id: 81, name: "Document Integrity Verifier", slug: "document-integrity-verifier", category: "File & Document Tools", isPro: true },
  { id: 82, name: "Document Digital Signature Validator", slug: "document-digital-signature-validator", category: "File & Document Tools", isPro: true },
  { id: 83, name: "File Integrity Monitoring", slug: "file-integrity-monitoring", category: "File & Document Tools", isPro: true },
  { id: 84, name: "File Change Detection", slug: "file-change-detection", category: "File & Document Tools", isPro: true },
  { id: 85, name: "Secure File Sharing Workspace", slug: "secure-file-sharing-workspace", category: "File & Document Tools", isPro: true },
  { id: 86, name: "Document Approval Workflow", slug: "document-approval-workflow", category: "File & Document Tools", isPro: true },
  { id: 87, name: "Document Review Workflow", slug: "document-review-workflow", category: "File & Document Tools", isPro: true },
  { id: 88, name: "Document Version Management", slug: "document-version-management", category: "File & Document Tools", isPro: true },
  { id: 89, name: "Document Retention Planner", slug: "document-retention-planner", category: "File & Document Tools", isPro: true },
  { id: 90, name: "Document Archiving Planner", slug: "document-archiving-planner", category: "File & Document Tools", isPro: true },
  { id: 91, name: "Document Lifecycle Manager", slug: "document-lifecycle-manager", category: "File & Document Tools", isPro: true },
  { id: 92, name: "Multi-Document Search", slug: "multi-document-search", category: "File & Document Tools", isPro: true },
  { id: 93, name: "AI Document Classification", slug: "ai-document-classification", category: "File & Document Tools", isPro: true },
  { id: 94, name: "AI Document Comparison", slug: "ai-document-comparison", category: "File & Document Tools", isPro: true },
  { id: 95, name: "AI Document Q&A", slug: "ai-document-qa-file", category: "File & Document Tools", isPro: true },
  { id: 96, name: "AI Document Summarization", slug: "ai-document-summarization-file", category: "File & Document Tools", isPro: true },
  { id: 97, name: "Document Knowledge Base", slug: "document-knowledge-base", category: "File & Document Tools", isPro: true },
  { id: 98, name: "Digital Document Management System", slug: "digital-document-management-system", category: "File & Document Tools", isPro: true },
  { id: 99, name: "Intelligent File Management Workspace", slug: "intelligent-file-management-workspace", category: "File & Document Tools", isPro: true },
  { id: 100, name: "Document Data Extractor", slug: "document-data-extractor-pro", category: "File & Document Tools", isPro: true },
];