export interface GamingTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const gamingToolsList: GamingTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "Gaming PC Requirements Checker", slug: "gaming-pc-requirements-checker", category: "Gaming Tools", isPro: false },
  { id: 2, name: "Game System Requirements Checker", slug: "game-system-requirements-checker", category: "Gaming Tools", isPro: false },
  { id: 3, name: "FPS Calculator", slug: "fps-calculator", category: "Gaming Tools", isPro: false },
  { id: 4, name: "FOV Calculator", slug: "fov-calculator", category: "Gaming Tools", isPro: false },
  { id: 5, name: "Sensitivity Converter", slug: "sensitivity-converter", category: "Gaming Tools", isPro: false },
  { id: 6, name: "eDPI Calculator", slug: "edpi-calculator", category: "Gaming Tools", isPro: false },
  { id: 7, name: "DPI Calculator", slug: "dpi-calculator", category: "Gaming Tools", isPro: false },
  { id: 8, name: "Controller Sensitivity Converter", slug: "controller-sensitivity-converter", category: "Gaming Tools", isPro: false },
  { id: 9, name: "Game Download Time Calculator", slug: "game-download-time-calculator", category: "Gaming Tools", isPro: false },
  { id: 10, name: "Internet Speed Gaming Calculator", slug: "internet-speed-gaming-calculator", category: "Gaming Tools", isPro: false },
  { id: 11, name: "Ping Calculator", slug: "ping-calculator", category: "Gaming Tools", isPro: false },
  { id: 12, name: "Latency Calculator", slug: "latency-calculator", category: "Gaming Tools", isPro: false },
  { id: 13, name: "Streaming Bandwidth Calculator", slug: "streaming-bandwidth-calculator", category: "Gaming Tools", isPro: false },
  { id: 14, name: "Gaming PC Power Calculator", slug: "gaming-pc-power-calculator", category: "Gaming Tools", isPro: false },
  { id: 15, name: "PSU Calculator", slug: "psu-calculator", category: "Gaming Tools", isPro: false },
  { id: 16, name: "Gaming PC Cost Calculator", slug: "gaming-pc-cost-calculator", category: "Gaming Tools", isPro: false },
  { id: 17, name: "Game Completion Time Calculator", slug: "game-completion-time-calculator", category: "Gaming Tools", isPro: false },
  { id: 18, name: "Tournament Bracket Generator", slug: "tournament-bracket-generator", category: "Gaming Tools", isPro: false },
  { id: 19, name: "Gaming PC Build Planner", slug: "gaming-pc-build-planner", category: "Gaming Tools", isPro: true },
  { id: 20, name: "PC Bottleneck Analyzer", slug: "pc-bottleneck-analyzer", category: "Gaming Tools", isPro: true },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Gaming FPS Estimator", slug: "gaming-fps-estimator", category: "Gaming Tools", isPro: false },
  { id: 22, name: "Monitor Refresh Rate Calculator", slug: "monitor-refresh-rate-calculator", category: "Gaming Tools", isPro: false },
  { id: 23, name: "Input Lag Calculator", slug: "input-lag-calculator", category: "Gaming Tools", isPro: false },
  { id: 24, name: "Resolution Scaling Calculator", slug: "resolution-scaling-calculator", category: "Gaming Tools", isPro: false },
  { id: 25, name: "Aspect Ratio Calculator", slug: "aspect-ratio-calculator", category: "Gaming Tools", isPro: false },
  { id: 26, name: "Mouse Sensitivity Calculator", slug: "mouse-sensitivity-calculator", category: "Gaming Tools", isPro: false },
  { id: 27, name: "cm/360 Calculator", slug: "cm-360-calculator", category: "Gaming Tools", isPro: false },
  { id: 28, name: "Gaming Mouse Space Calculator", slug: "gaming-mouse-space-calculator", category: "Gaming Tools", isPro: false },
  { id: 29, name: "Aim Sensitivity Converter", slug: "aim-sensitivity-converter", category: "Gaming Tools", isPro: false },
  { id: 30, name: "Controller Deadzone Calculator", slug: "controller-deadzone-calculator", category: "Gaming Tools", isPro: false },
  { id: 31, name: "Game Install Time Estimator", slug: "game-install-time-estimator", category: "Gaming Tools", isPro: false },
  { id: 32, name: "Game Storage Calculator", slug: "game-storage-calculator", category: "Gaming Tools", isPro: false },
  { id: 33, name: "Storage Requirement Calculator", slug: "storage-requirement-calculator", category: "Gaming Tools", isPro: false },
  { id: 34, name: "Network Bandwidth Calculator", slug: "network-bandwidth-calculator", category: "Gaming Tools", isPro: false },
  { id: 35, name: "Game Server Distance Calculator", slug: "game-server-distance-calculator", category: "Gaming Tools", isPro: false },
  { id: 36, name: "Server Ping Checker", slug: "server-ping-checker", category: "Gaming Tools", isPro: false },
  { id: 37, name: "Gaming Data Usage Calculator", slug: "gaming-data-usage-calculator", category: "Gaming Tools", isPro: false },
  { id: 38, name: "Game Streaming Bitrate Calculator", slug: "game-streaming-bitrate-calculator", category: "Gaming Tools", isPro: false },
  { id: 39, name: "Twitch Bitrate Calculator", slug: "twitch-bitrate-calculator", category: "Gaming Tools", isPro: false },
  { id: 40, name: "YouTube Gaming Bitrate Calculator", slug: "youtube-gaming-bitrate-calculator", category: "Gaming Tools", isPro: false },
  { id: 41, name: "Stream Resolution Calculator", slug: "stream-resolution-calculator", category: "Gaming Tools", isPro: false },
  { id: 42, name: "Stream Storage Calculator", slug: "stream-storage-calculator", category: "Gaming Tools", isPro: false },
  { id: 43, name: "GPU Power Calculator", slug: "gpu-power-calculator", category: "Gaming Tools", isPro: false },
  { id: 44, name: "Gaming Build Budget Calculator", slug: "gaming-build-budget-calculator", category: "Gaming Tools", isPro: false },
  { id: 45, name: "Game Price Comparison Calculator", slug: "game-price-comparison-calculator", category: "Gaming Tools", isPro: false },
  { id: 46, name: "Game Discount Calculator", slug: "game-discount-calculator", category: "Gaming Tools", isPro: false },
  { id: 47, name: "DLC Cost Calculator", slug: "dlc-cost-calculator", category: "Gaming Tools", isPro: false },
  { id: 48, name: "Gaming Subscription Cost Calculator", slug: "gaming-subscription-cost-calculator", category: "Gaming Tools", isPro: false },
  { id: 49, name: "Game Backlog Calculator", slug: "game-backlog-calculator", category: "Gaming Tools", isPro: false },
  { id: 50, name: "Gaming Hours Tracker", slug: "gaming-hours-tracker", category: "Gaming Tools", isPro: false },
  { id: 51, name: "Game Session Timer", slug: "game-session-timer", category: "Gaming Tools", isPro: false },
  { id: 52, name: "Achievement Progress Tracker", slug: "achievement-progress-tracker", category: "Gaming Tools", isPro: false },
  { id: 53, name: "Game Completion Tracker", slug: "game-completion-tracker", category: "Gaming Tools", isPro: false },
  { id: 54, name: "Game Library Organizer", slug: "game-library-organizer", category: "Gaming Tools", isPro: false },
  { id: 55, name: "Gaming Wishlist Organizer", slug: "gaming-wishlist-organizer", category: "Gaming Tools", isPro: false },
  { id: 56, name: "Gaming Backlog Organizer", slug: "gaming-backlog-organizer", category: "Gaming Tools", isPro: false },
  { id: 57, name: "Clan Name Generator", slug: "clan-name-generator", category: "Gaming Tools", isPro: false },
  { id: 58, name: "Gamer Tag Generator", slug: "gamer-tag-generator", category: "Gaming Tools", isPro: false },
  { id: 59, name: "Username Availability Checker", slug: "username-availability-checker", category: "Gaming Tools", isPro: false },
  { id: 60, name: "Team Name Generator", slug: "team-name-generator", category: "Gaming Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Gaming Tournament Planner", slug: "gaming-tournament-planner", category: "Gaming Tools", isPro: true },
  { id: 62, name: "Gaming Schedule Planner", slug: "gaming-schedule-planner", category: "Gaming Tools", isPro: true },
  { id: 63, name: "Gaming Hardware Comparison Workspace", slug: "gaming-hardware-comparison-workspace", category: "Gaming Tools", isPro: true },
  { id: 64, name: "GPU Performance Comparison Tool", slug: "gpu-performance-comparison-tool", category: "Gaming Tools", isPro: true },
  { id: 65, name: "CPU Gaming Performance Analyzer", slug: "cpu-gaming-performance-analyzer", category: "Gaming Tools", isPro: true },
  { id: 66, name: "Gaming Build Optimization Engine", slug: "gaming-build-optimization-engine", category: "Gaming Tools", isPro: true },
  { id: 67, name: "Gaming Upgrade Planner", slug: "gaming-upgrade-planner", category: "Gaming Tools", isPro: true },
  { id: 68, name: "Gaming Budget Optimization Tool", slug: "gaming-budget-optimization-tool", category: "Gaming Tools", isPro: true },
  { id: 69, name: "FPS Performance Analyzer", slug: "fps-performance-analyzer", category: "Gaming Tools", isPro: true },
  { id: 70, name: "Game Settings Optimization Workspace", slug: "game-settings-optimization-workspace", category: "Gaming Tools", isPro: true },
  { id: 71, name: "Graphics Settings Comparison Tool", slug: "graphics-settings-comparison-tool", category: "Gaming Tools", isPro: true },
  { id: 72, name: "Competitive Sensitivity Workspace", slug: "competitive-sensitivity-workspace", category: "Gaming Tools", isPro: true },
  { id: 73, name: "Aim Training Analytics Workspace", slug: "aim-training-analytics-workspace", category: "Gaming Tools", isPro: true },
  { id: 74, name: "Player Performance Dashboard", slug: "player-performance-dashboard", category: "Gaming Tools", isPro: true },
  { id: 75, name: "Gaming Session Analytics", slug: "gaming-session-analytics", category: "Gaming Tools", isPro: true },
  { id: 76, name: "Game Progress Dashboard", slug: "game-progress-dashboard", category: "Gaming Tools", isPro: true },
  { id: 77, name: "Achievement Analytics Workspace", slug: "achievement-analytics-workspace", category: "Gaming Tools", isPro: true },
  { id: 78, name: "Gaming Backlog Management Workspace", slug: "gaming-backlog-management-workspace", category: "Gaming Tools", isPro: true },
  { id: 79, name: "Game Library Intelligence Dashboard", slug: "game-library-intelligence-dashboard", category: "Gaming Tools", isPro: true },
  { id: 80, name: "Gaming Cost Analytics", slug: "gaming-cost-analytics", category: "Gaming Tools", isPro: true },
  { id: 81, name: "Gaming Subscription Tracker", slug: "gaming-subscription-tracker", category: "Gaming Tools", isPro: true },
  { id: 82, name: "Gaming Spending Dashboard", slug: "gaming-spending-dashboard", category: "Gaming Tools", isPro: true },
  { id: 83, name: "Esports Tournament Workspace", slug: "esports-tournament-workspace", category: "Gaming Tools", isPro: true },
  { id: 84, name: "Tournament Bracket Management", slug: "tournament-bracket-management", category: "Gaming Tools", isPro: true },
  { id: 85, name: "Team Roster Management Workspace", slug: "team-roster-management-workspace", category: "Gaming Tools", isPro: true },
  { id: 86, name: "Player Statistics Dashboard", slug: "player-statistics-dashboard", category: "Gaming Tools", isPro: true },
  { id: 87, name: "Competitive Gaming Analytics", slug: "competitive-gaming-analytics", category: "Gaming Tools", isPro: true },
  { id: 88, name: "Gaming Team Performance Analyzer", slug: "gaming-team-performance-analyzer", category: "Gaming Tools", isPro: true },
  { id: 89, name: "Streaming Setup Planner", slug: "streaming-setup-planner", category: "Gaming Tools", isPro: true },
  { id: 90, name: "Stream Performance Dashboard", slug: "stream-performance-dashboard", category: "Gaming Tools", isPro: true },
  { id: 91, name: "Streaming Cost Calculator", slug: "streaming-cost-calculator", category: "Gaming Tools", isPro: true },
  { id: 92, name: "Gaming Content Planning Workspace", slug: "gaming-content-planning-workspace", category: "Gaming Tools", isPro: true },
  { id: 93, name: "Gaming Creator Dashboard", slug: "gaming-creator-dashboard", category: "Gaming Tools", isPro: true },
  { id: 94, name: "Gaming Community Management Workspace", slug: "gaming-community-management-workspace", category: "Gaming Tools", isPro: true },
  { id: 95, name: "Game Server Planning Workspace", slug: "game-server-planning-workspace", category: "Gaming Tools", isPro: true },
  { id: 96, name: "Gaming Network Optimization Workspace", slug: "gaming-network-optimization-workspace", category: "Gaming Tools", isPro: true },
  { id: 97, name: "Gaming API/Data Workspace", slug: "gaming-api-data-workspace", category: "Gaming Tools", isPro: true },
  { id: 98, name: "Gaming Intelligence Platform", slug: "gaming-intelligence-platform", category: "Gaming Tools", isPro: true },
  { id: 99, name: "Esports Operations Platform", slug: "esports-operations-platform", category: "Gaming Tools", isPro: true },
  { id: 100, name: "Professional Gaming Command Center", slug: "professional-gaming-command-center", category: "Gaming Tools", isPro: true }
];