export interface GeographyTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const geographyToolsList: GeographyTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "Country Information Finder", slug: "country-information-finder", category: "Geography Tools", isPro: false },
  { id: 2, name: "Country Comparison Tool", slug: "country-comparison-tool", category: "Geography Tools", isPro: false },
  { id: 3, name: "Capital City Finder", slug: "capital-city-finder", category: "Geography Tools", isPro: false },
  { id: 4, name: "Currency Country Finder", slug: "currency-country-finder", category: "Geography Tools", isPro: false },
  { id: 5, name: "Country Calling Code Finder", slug: "country-calling-code-finder", category: "Geography Tools", isPro: false },
  { id: 6, name: "Country ISO Code Finder", slug: "country-iso-code-finder", category: "Geography Tools", isPro: false },
  { id: 7, name: "Country Time Zone Finder", slug: "country-time-zone-finder", category: "Geography Tools", isPro: false },
  { id: 8, name: "City Country Finder", slug: "city-country-finder", category: "Geography Tools", isPro: false },
  { id: 9, name: "City Coordinates Finder", slug: "city-coordinates-finder", category: "Geography Tools", isPro: false },
  { id: 10, name: "Latitude Longitude Converter", slug: "latitude-longitude-converter", category: "Geography Tools", isPro: false },
  { id: 11, name: "DMS to Decimal Converter", slug: "dms-to-decimal-converter", category: "Geography Tools", isPro: false },
  { id: 12, name: "Latitude Longitude Distance Calculator", slug: "latitude-longitude-distance-calculator", category: "Geography Tools", isPro: false },
  { id: 13, name: "Great Circle Distance Calculator", slug: "great-circle-distance-calculator", category: "Geography Tools", isPro: false },
  { id: 14, name: "Geographic Midpoint Calculator", slug: "geographic-midpoint-calculator", category: "Geography Tools", isPro: false },
  { id: 15, name: "Bearing Calculator", slug: "bearing-calculator", category: "Geography Tools", isPro: false },
  { id: 16, name: "Elevation Calculator", slug: "elevation-calculator", category: "Geography Tools", isPro: false },
  { id: 17, name: "Hemisphere Finder", slug: "hemisphere-finder", category: "Geography Tools", isPro: false },
  { id: 18, name: "Antipode Finder", slug: "antipode-finder", category: "Geography Tools", isPro: false },
  { id: 19, name: "Nearest Country Finder", slug: "nearest-country-finder", category: "Geography Tools", isPro: false },
  { id: 20, name: "Country Data Explorer", slug: "country-data-explorer", category: "Geography Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Country Population Finder", slug: "country-population-finder", category: "Geography Tools", isPro: false },
  { id: 22, name: "Population Density Calculator", slug: "population-density-calculator", category: "Geography Tools", isPro: false },
  { id: 23, name: "Country Area Comparison", slug: "country-area-comparison", category: "Geography Tools", isPro: false },
  { id: 24, name: "Country Capital Quiz", slug: "country-capital-quiz", category: "Geography Tools", isPro: false },
  { id: 25, name: "Continent Finder", slug: "continent-finder", category: "Geography Tools", isPro: false },
  { id: 26, name: "Country Continent Finder", slug: "country-continent-finder", category: "Geography Tools", isPro: false },
  { id: 27, name: "Country Flag Finder", slug: "country-flag-finder", category: "Geography Tools", isPro: false },
  { id: 28, name: "Country Currency Finder", slug: "country-currency-finder", category: "Geography Tools", isPro: false },
  { id: 29, name: "Country Language Finder", slug: "country-language-finder", category: "Geography Tools", isPro: false },
  { id: 30, name: "Official Language Finder", slug: "official-language-finder", category: "Geography Tools", isPro: false },
  { id: 31, name: "Country Internet TLD Finder", slug: "country-internet-tld-finder", category: "Geography Tools", isPro: false },
  { id: 32, name: "Country Time Difference Calculator", slug: "country-time-difference-calculator", category: "Geography Tools", isPro: false },
  { id: 33, name: "Country Driving Side Finder", slug: "country-driving-side-finder", category: "Geography Tools", isPro: false },
  { id: 34, name: "Country Postal Code Finder", slug: "country-postal-code-finder", category: "Geography Tools", isPro: false },
  { id: 35, name: "Country Region Finder", slug: "country-region-finder", category: "Geography Tools", isPro: false },
  { id: 36, name: "State Province Finder", slug: "state-province-finder", category: "Geography Tools", isPro: false },
  { id: 37, name: "State Capital Finder", slug: "state-capital-finder", category: "Geography Tools", isPro: false },
  { id: 38, name: "City Population Finder", slug: "city-population-finder", category: "Geography Tools", isPro: false },
  { id: 39, name: "Geographic Coordinates Finder", slug: "geographic-coordinates-finder", category: "Geography Tools", isPro: false },
  { id: 40, name: "Decimal to DMS Converter", slug: "decimal-to-dms-converter", category: "Geography Tools", isPro: false },
  { id: 41, name: "Compass Direction Calculator", slug: "compass-direction-calculator", category: "Geography Tools", isPro: false },
  { id: 42, name: "Sea Level Elevation Comparison", slug: "sea-level-elevation-comparison", category: "Geography Tools", isPro: false },
  { id: 43, name: "Area Comparison Calculator", slug: "area-comparison-calculator", category: "Geography Tools", isPro: false },
  { id: 44, name: "Population Comparison Tool", slug: "population-comparison-tool", category: "Geography Tools", isPro: false },
  { id: 45, name: "Population Growth Calculator", slug: "population-growth-calculator", category: "Geography Tools", isPro: false },
  { id: 46, name: "Time Zone Map Tool", slug: "time-zone-map-tool", category: "Geography Tools", isPro: false },
  { id: 47, name: "International Date Line Tool", slug: "international-date-line-tool", category: "Geography Tools", isPro: false },
  { id: 48, name: "Equator Distance Calculator", slug: "equator-distance-calculator", category: "Geography Tools", isPro: false },
  { id: 49, name: "Tropic Distance Calculator", slug: "tropic-distance-calculator", category: "Geography Tools", isPro: false },
  { id: 50, name: "Nearest Capital Finder", slug: "nearest-capital-finder", category: "Geography Tools", isPro: false },
  { id: 51, name: "Nearest City Finder", slug: "nearest-city-finder", category: "Geography Tools", isPro: false },
  { id: 52, name: "Country Border Finder", slug: "country-border-finder", category: "Geography Tools", isPro: false },
  { id: 53, name: "Border Distance Calculator", slug: "border-distance-calculator", category: "Geography Tools", isPro: false },
  { id: 54, name: "Land Area Calculator", slug: "land-area-calculator", category: "Geography Tools", isPro: false },
  { id: 55, name: "Geographic Scale Calculator", slug: "geographic-scale-calculator", category: "Geography Tools", isPro: false },
  { id: 56, name: "Map Scale Calculator", slug: "map-scale-calculator", category: "Geography Tools", isPro: false },
  { id: 57, name: "Map Distance Calculator", slug: "map-distance-calculator", category: "Geography Tools", isPro: false },
  { id: 58, name: "Geographic Coordinate Validator", slug: "geographic-coordinate-validator", category: "Geography Tools", isPro: false },
  { id: 59, name: "GeoJSON Coordinate Validator", slug: "geojson-coordinate-validator", category: "Geography Tools", isPro: false },
  { id: 60, name: "Demographic Comparison Workspace", slug: "demographic-comparison-workspace", category: "Geography Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Global Country Intelligence Dashboard", slug: "global-country-intelligence-dashboard", category: "Geography Tools", isPro: true },
  { id: 62, name: "Country Comparison Engine", slug: "country-comparison-engine", category: "Geography Tools", isPro: true },
  { id: 63, name: "Geographic Market Analyzer", slug: "geographic-market-analyzer", category: "Geography Tools", isPro: true },
  { id: 64, name: "Country Market Research Tool", slug: "country-market-research-tool", category: "Geography Tools", isPro: true },
  { id: 65, name: "Population Intelligence Dashboard", slug: "population-intelligence-dashboard", category: "Geography Tools", isPro: true },
  { id: 66, name: "Regional Demographic Analyzer", slug: "regional-demographic-analyzer", category: "Geography Tools", isPro: true },
  { id: 67, name: "City Market Intelligence", slug: "city-market-intelligence", category: "Geography Tools", isPro: true },
  { id: 68, name: "Location Suitability Analyzer", slug: "location-suitability-analyzer", category: "Geography Tools", isPro: true },
  { id: 69, name: "Business Location Comparison", slug: "business-location-comparison", category: "Geography Tools", isPro: true },
  { id: 70, name: "International Expansion Research Tool", slug: "international-expansion-research-tool", category: "Geography Tools", isPro: true },
  { id: 71, name: "Country Expansion Scorecard", slug: "country-expansion-scorecard", category: "Geography Tools", isPro: true },
  { id: 72, name: "Geographic Risk Analyzer", slug: "geographic-risk-analyzer", category: "Geography Tools", isPro: true },
  { id: 73, name: "Country Risk Comparison Workspace", slug: "country-risk-comparison-workspace", category: "Geography Tools", isPro: true },
  { id: 74, name: "Global Workforce Location Analyzer", slug: "global-workforce-location-analyzer", category: "Geography Tools", isPro: true },
  { id: 75, name: "Remote Workforce Country Planner", slug: "remote-workforce-country-planner", category: "Geography Tools", isPro: true },
  { id: 76, name: "International Office Location Analyzer", slug: "international-office-location-analyzer", category: "Geography Tools", isPro: true },
  { id: 77, name: "Global Hiring Location Analyzer", slug: "global-hiring-location-analyzer", category: "Geography Tools", isPro: true },
  { id: 78, name: "Geographic Customer Market Analyzer", slug: "geographic-customer-market-analyzer", category: "Geography Tools", isPro: true },
  { id: 79, name: "International Audience Analyzer", slug: "international-audience-analyzer", category: "Geography Tools", isPro: true },
  { id: 80, name: "Country SEO Market Analyzer", slug: "country-seo-market-analyzer", category: "Geography Tools", isPro: true },
  { id: 81, name: "Regional SEO Market Analyzer", slug: "regional-seo-market-analyzer", category: "Geography Tools", isPro: true },
  { id: 82, name: "Geographic Keyword Planner", slug: "geographic-keyword-planner", category: "Geography Tools", isPro: true },
  { id: 83, name: "Local Search Market Analyzer", slug: "local-search-market-analyzer", category: "Geography Tools", isPro: true },
  { id: 84, name: "Geographic Data Dashboard", slug: "geographic-data-dashboard", category: "Geography Tools", isPro: true },
  { id: 85, name: "Population Projection Workspace", slug: "population-projection-workspace", category: "Geography Tools", isPro: true },
  { id: 86, name: "Geographic Data Comparison Engine", slug: "geographic-data-comparison-engine", category: "Geography Tools", isPro: true },
  { id: 87, name: "GIS Data Explorer", slug: "gis-data-explorer", category: "Geography Tools", isPro: true },
  { id: 88, name: "Coordinate Data Workspace", slug: "coordinate-data-workspace", category: "Geography Tools", isPro: true },
  { id: 89, name: "GeoJSON Analysis Workspace", slug: "geojson-analysis-workspace", category: "Geography Tools", isPro: true },
  { id: 90, name: "Geographic Dataset Analyzer", slug: "geographic-dataset-analyzer", category: "Geography Tools", isPro: true },
  { id: 91, name: "Global Location Intelligence Platform", slug: "global-location-intelligence-platform", category: "Geography Tools", isPro: true },
  { id: 92, name: "International Expansion Workspace", slug: "international-expansion-workspace", category: "Geography Tools", isPro: true },
  { id: 93, name: "Geographic Research Workspace", slug: "geographic-research-workspace", category: "Geography Tools", isPro: true },
  { id: 94, name: "Country Intelligence Platform", slug: "country-intelligence-platform", category: "Geography Tools", isPro: true },
  { id: 95, name: "Global Market Location Dashboard", slug: "global-market-location-dashboard", category: "Geography Tools", isPro: true },
  { id: 96, name: "Demographic Intelligence Platform", slug: "demographic-intelligence-platform", category: "Geography Tools", isPro: true },
  { id: 97, name: "Geographic Business Intelligence", slug: "geographic-business-intelligence", category: "Geography Tools", isPro: true },
  { id: 98, name: "Global Location Strategy Platform", slug: "global-location-strategy-platform", category: "Geography Tools", isPro: true },
  { id: 99, name: "Professional Geography Intelligence Workspace", slug: "professional-geography-intelligence-workspace", category: "Geography Tools", isPro: true },
  { id: 100, name: "Data Driven Border Analyzer", slug: "data-driven-border-analyzer", category: "Geography Tools", isPro: true }
];