export interface GovernmentTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const governmentToolsList: GovernmentTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "Government Service Finder", slug: "government-service-finder", category: "Government & Public Service Tools", isPro: false },
  { id: 2, name: "Government Office Finder", slug: "government-office-finder", category: "Government & Public Service Tools", isPro: false },
  { id: 3, name: "Public Service Directory", slug: "public-service-directory", category: "Government & Public Service Tools", isPro: false },
  { id: 4, name: "Embassy Finder", slug: "embassy-finder", category: "Government & Public Service Tools", isPro: false },
  { id: 5, name: "Passport Office Finder", slug: "passport-office-finder", category: "Government & Public Service Tools", isPro: false },
  { id: 6, name: "Government Form Finder", slug: "government-form-finder", category: "Government & Public Service Tools", isPro: false },
  { id: 7, name: "Passport Document Checklist", slug: "passport-document-checklist", category: "Government & Public Service Tools", isPro: false },
  { id: 8, name: "Visa Document Checklist", slug: "visa-document-checklist", category: "Government & Public Service Tools", isPro: false },
  { id: 9, name: "Business Registration Checklist", slug: "business-registration-checklist", category: "Government & Public Service Tools", isPro: false },
  { id: 10, name: "Public Benefits Finder", slug: "public-benefits-finder", category: "Government & Public Service Tools", isPro: false },
  { id: 11, name: "Tax Deadline Finder", slug: "tax-deadline-finder", category: "Government & Public Service Tools", isPro: false },
  { id: 12, name: "Government Holiday Calendar", slug: "government-holiday-calendar", category: "Government & Public Service Tools", isPro: false },
  { id: 13, name: "Voter Information Finder", slug: "voter-information-finder", category: "Government & Public Service Tools", isPro: false },
  { id: 14, name: "Constituency Finder", slug: "constituency-finder", category: "Government & Public Service Tools", isPro: false },
  { id: 15, name: "Government Scheme Finder", slug: "government-scheme-finder", category: "Government & Public Service Tools", isPro: false },
  { id: 16, name: "Grant Program Finder", slug: "grant-program-finder", category: "Government & Public Service Tools", isPro: false },
  { id: 17, name: "Government Fee Calculator", slug: "government-fee-calculator", category: "Government & Public Service Tools", isPro: false },
  { id: 18, name: "Passport Fee Calculator", slug: "passport-fee-calculator", category: "Government & Public Service Tools", isPro: false },
  { id: 19, name: "Government Document Checklist Generator", slug: "government-document-checklist-generator", category: "Government & Public Service Tools", isPro: false },
  { id: 20, name: "Government Service Status Tracker", slug: "government-service-status-tracker", category: "Government & Public Service Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Government Contact Finder", slug: "government-contact-finder", category: "Government & Public Service Tools", isPro: false },
  { id: 22, name: "Government Department Finder", slug: "government-department-finder", category: "Government & Public Service Tools", isPro: false },
  { id: 23, name: "Public Office Locator", slug: "public-office-locator", category: "Government & Public Service Tools", isPro: false },
  { id: 24, name: "Consulate Finder", slug: "consulate-finder", category: "Government & Public Service Tools", isPro: false },
  { id: 25, name: "Tax Office Finder", slug: "tax-office-finder", category: "Government & Public Service Tools", isPro: false },
  { id: 26, name: "Social Security Office Finder", slug: "social-security-office-finder", category: "Government & Public Service Tools", isPro: false },
  { id: 27, name: "DMV Office Finder", slug: "dmv-office-finder", category: "Government & Public Service Tools", isPro: false },
  { id: 28, name: "Public Records Search Guide", slug: "public-records-search-guide", category: "Government & Public Service Tools", isPro: false },
  { id: 29, name: "Government Application Checklist", slug: "government-application-checklist", category: "Government & Public Service Tools", isPro: false },
  { id: 30, name: "Citizenship Document Checklist", slug: "citizenship-document-checklist", category: "Government & Public Service Tools", isPro: false },
  { id: 31, name: "Birth Certificate Checklist", slug: "birth-certificate-checklist", category: "Government & Public Service Tools", isPro: false },
  { id: 32, name: "Marriage Certificate Checklist", slug: "marriage-certificate-checklist", category: "Government & Public Service Tools", isPro: false },
  { id: 33, name: "Death Certificate Checklist", slug: "death-certificate-checklist", category: "Government & Public Service Tools", isPro: false },
  { id: 34, name: "Address Change Checklist", slug: "address-change-checklist", category: "Government & Public Service Tools", isPro: false },
  { id: 35, name: "Government ID Checklist", slug: "government-id-checklist", category: "Government & Public Service Tools", isPro: false },
  { id: 36, name: "Driving License Checklist", slug: "driving-license-checklist", category: "Government & Public Service Tools", isPro: false },
  { id: 37, name: "Vehicle Registration Checklist", slug: "vehicle-registration-checklist", category: "Government & Public Service Tools", isPro: false },
  { id: 38, name: "Company Registration Checklist", slug: "company-registration-checklist", category: "Government & Public Service Tools", isPro: false },
  { id: 39, name: "Government Benefits Eligibility Guide", slug: "government-benefits-eligibility-guide", category: "Government & Public Service Tools", isPro: false },
  { id: 40, name: "Public Service Eligibility Checklist", slug: "public-service-eligibility-checklist", category: "Government & Public Service Tools", isPro: false },
  { id: 41, name: "Pension Calculator", slug: "pension-calculator", category: "Government & Public Service Tools", isPro: false },
  { id: 42, name: "Retirement Benefits Calculator", slug: "retirement-benefits-calculator", category: "Government & Public Service Tools", isPro: false },
  { id: 43, name: "Social Benefit Calculator", slug: "social-benefit-calculator", category: "Government & Public Service Tools", isPro: false },
  { id: 44, name: "Public Holiday Calendar", slug: "public-holiday-calendar", category: "Government & Public Service Tools", isPro: false },
  { id: 45, name: "Election Date Finder", slug: "election-date-finder", category: "Government & Public Service Tools", isPro: false },
  { id: 46, name: "Voting Registration Checklist", slug: "voting-registration-checklist", category: "Government & Public Service Tools", isPro: false },
  { id: 47, name: "Representative Finder", slug: "representative-finder", category: "Government & Public Service Tools", isPro: false },
  { id: 48, name: "Public Program Finder", slug: "public-program-finder", category: "Government & Public Service Tools", isPro: false },
  { id: 49, name: "Government Grant Checklist", slug: "government-grant-checklist", category: "Government & Public Service Tools", isPro: false },
  { id: 50, name: "Public Tender Finder", slug: "public-tender-finder", category: "Government & Public Service Tools", isPro: false },
  { id: 51, name: "Government Procurement Guide", slug: "government-procurement-guide", category: "Government & Public Service Tools", isPro: false },
  { id: 52, name: "Public Complaint Guide", slug: "public-complaint-guide", category: "Government & Public Service Tools", isPro: false },
  { id: 53, name: "Freedom of Information Guide", slug: "freedom-of-information-guide", category: "Government & Public Service Tools", isPro: false },
  { id: 54, name: "Public Information Request Checklist", slug: "public-information-request-checklist", category: "Government & Public Service Tools", isPro: false },
  { id: 55, name: "Visa Fee Calculator", slug: "visa-fee-calculator", category: "Government & Public Service Tools", isPro: false },
  { id: 56, name: "License Fee Calculator", slug: "license-fee-calculator", category: "Government & Public Service Tools", isPro: false },
  { id: 57, name: "Registration Fee Calculator", slug: "registration-fee-calculator", category: "Government & Public Service Tools", isPro: false },
  { id: 58, name: "Government Appointment Checklist", slug: "government-appointment-checklist", category: "Government & Public Service Tools", isPro: false },
  { id: 59, name: "Public Service Appointment Planner", slug: "public-service-appointment-planner", category: "Government & Public Service Tools", isPro: false },
  { id: 60, name: "Public Service Process Tracker", slug: "public-service-process-tracker", category: "Government & Public Service Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Government Service Intelligence Dashboard", slug: "government-service-intelligence-dashboard", category: "Government & Public Service Tools", isPro: true },
  { id: 62, name: "Public Service Directory Platform", slug: "public-service-directory-platform", category: "Government & Public Service Tools", isPro: true },
  { id: 63, name: "Government Office Locator Platform", slug: "government-office-locator-platform", category: "Government & Public Service Tools", isPro: true },
  { id: 64, name: "Multi-Country Government Service Finder", slug: "multi-country-government-service-finder", category: "Government & Public Service Tools", isPro: true },
  { id: 65, name: "Government Document Management Workspace", slug: "government-document-management-workspace", category: "Government & Public Service Tools", isPro: true },
  { id: 66, name: "Public Service Application Workspace", slug: "public-service-application-workspace", category: "Government & Public Service Tools", isPro: true },
  { id: 67, name: "Government Application Checklist Engine", slug: "government-application-checklist-engine", category: "Government & Public Service Tools", isPro: true },
  { id: 68, name: "Citizen Service Dashboard", slug: "citizen-service-dashboard", category: "Government & Public Service Tools", isPro: true },
  { id: 69, name: "Government Benefits Research Workspace", slug: "government-benefits-research-workspace", category: "Government & Public Service Tools", isPro: true },
  { id: 70, name: "Public Benefits Comparison Tool", slug: "public-benefits-comparison-tool", category: "Government & Public Service Tools", isPro: true },
  { id: 71, name: "Government Scheme Comparison Workspace", slug: "government-scheme-comparison-workspace", category: "Government & Public Service Tools", isPro: true },
  { id: 72, name: "Government Grant Research Workspace", slug: "government-grant-research-workspace", category: "Government & Public Service Tools", isPro: true },
  { id: 73, name: "Public Tender Research Workspace", slug: "public-tender-research-workspace", category: "Government & Public Service Tools", isPro: true },
  { id: 74, name: "Government Procurement Intelligence", slug: "government-procurement-intelligence", category: "Government & Public Service Tools", isPro: true },
  { id: 75, name: "Public Contract Research Workspace", slug: "public-contract-research-workspace", category: "Government & Public Service Tools", isPro: true },
  { id: 76, name: "Government Deadline Dashboard", slug: "government-deadline-dashboard", category: "Government & Public Service Tools", isPro: true },
  { id: 77, name: "Public Holiday Intelligence Dashboard", slug: "public-holiday-intelligence-dashboard", category: "Government & Public Service Tools", isPro: true },
  { id: 78, name: "Government Fee Comparison Engine", slug: "government-fee-comparison-engine", category: "Government & Public Service Tools", isPro: true },
  { id: 79, name: "Government Office Comparison Tool", slug: "government-office-comparison-tool", category: "Government & Public Service Tools", isPro: true },
  { id: 80, name: "Embassy & Consulate Intelligence", slug: "embassy-consulate-intelligence", category: "Government & Public Service Tools", isPro: true },
  { id: 81, name: "Passport Service Planning Workspace", slug: "passport-service-planning-workspace", category: "Government & Public Service Tools", isPro: true },
  { id: 82, name: "Visa Service Planning Workspace", slug: "visa-service-planning-workspace", category: "Government & Public Service Tools", isPro: true },
  { id: 83, name: "Citizenship Process Workspace", slug: "citizenship-process-workspace", category: "Government & Public Service Tools", isPro: true },
  { id: 84, name: "Business Registration Workspace", slug: "business-registration-workspace", category: "Government & Public Service Tools", isPro: true },
  { id: 85, name: "Public Records Research Workspace", slug: "public-records-research-workspace", category: "Government & Public Service Tools", isPro: true },
  { id: 86, name: "Government Document Organizer", slug: "government-document-organizer", category: "Government & Public Service Tools", isPro: true },
  { id: 87, name: "Public Application Tracker", slug: "public-application-tracker", category: "Government & Public Service Tools", isPro: true },
  { id: 88, name: "Citizen Case Tracker", slug: "citizen-case-tracker", category: "Government & Public Service Tools", isPro: true },
  { id: 89, name: "Government Service Notification Workspace", slug: "government-service-notification-workspace", category: "Government & Public Service Tools", isPro: true },
  { id: 90, name: "Public Service Data Importer", slug: "public-service-data-importer", category: "Government & Public Service Tools", isPro: true },
  { id: 91, name: "Government Data Dashboard", slug: "government-data-dashboard", category: "Government & Public Service Tools", isPro: true },
  { id: 92, name: "Government API Workspace", slug: "government-api-workspace", category: "Government & Public Service Tools", isPro: true },
  { id: 93, name: "Public Data Research Workspace", slug: "public-data-research-workspace", category: "Government & Public Service Tools", isPro: true },
  { id: 94, name: "Civic Information Platform", slug: "civic-information-platform", category: "Government & Public Service Tools", isPro: true },
  { id: 95, name: "Public Service Analytics Platform", slug: "public-service-analytics-platform", category: "Government & Public Service Tools", isPro: true },
  { id: 96, name: "Government Information Intelligence", slug: "government-information-intelligence", category: "Government & Public Service Tools", isPro: true },
  { id: 97, name: "Citizen Operations Dashboard", slug: "citizen-operations-dashboard", category: "Government & Public Service Tools", isPro: true },
  { id: 98, name: "Public Service Automation Workspace", slug: "public-service-automation-workspace", category: "Government & Public Service Tools", isPro: true },
  { id: 99, name: "Government Resource Intelligence Platform", slug: "government-resource-intelligence-platform", category: "Government & Public Service Tools", isPro: true },
  { id: 100, name: "Global Public Service Command Center", slug: "global-public-service-command-center", category: "Government & Public Service Tools", isPro: true }
];