export interface HospitalityTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const hospitalityRestaurantOperationsToolsList: HospitalityTool[] = [
  // --- 🔥 PRIORITY 20 FREE TOOLS (IDs 1-20 | isPro: false) ---
  { id: 1, name: "Restaurant Food Cost Calculator", slug: "restaurant-food-cost-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 2, name: "Food Cost Percentage Calculator", slug: "food-cost-percentage-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 3, name: "Recipe Cost Calculator", slug: "recipe-cost-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 4, name: "Menu Item Cost Calculator", slug: "menu-item-cost-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 5, name: "Menu Profit Calculator", slug: "menu-profit-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 6, name: "Menu Margin Calculator", slug: "menu-margin-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 7, name: "Menu Price Calculator", slug: "menu-price-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 8, name: "Portion Cost Calculator", slug: "portion-cost-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 9, name: "Food Waste Cost Calculator", slug: "food-waste-cost-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 10, name: "Restaurant Labor Cost Calculator", slug: "restaurant-labor-cost-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 11, name: "Restaurant Prime Cost Calculator", slug: "restaurant-prime-cost-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 12, name: "Restaurant Break-Even Calculator", slug: "restaurant-break-even-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 13, name: "Average Check Calculator", slug: "average-check-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 14, name: "Table Turnover Calculator", slug: "table-turnover-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 15, name: "Restaurant Capacity Calculator", slug: "restaurant-capacity-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 16, name: "Ingredient Quantity Calculator", slug: "ingredient-quantity-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 17, name: "Ingredient Reorder Calculator", slug: "ingredient-reorder-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 18, name: "Kitchen Production Planner", slug: "kitchen-production-planner", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 19, name: "Menu Engineering Workspace", slug: "menu-engineering-workspace-free", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 20, name: "Restaurant Management Workspace", slug: "restaurant-management-workspace-free", category: "Hospitality & Restaurant Operations Tools", isPro: false },

  // --- REMAINING 40 CORE FREE TOOLS (IDs 21-60 | isPro: false) ---
  { id: 21, name: "Recipe Yield Calculator", slug: "recipe-yield-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 22, name: "Ingredient Cost Calculator", slug: "ingredient-cost-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 23, name: "Recipe Batch Cost Calculator", slug: "recipe-batch-cost-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 24, name: "Food Waste Percentage", slug: "food-waste-percentage", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 25, name: "Beverage Cost Calculator", slug: "beverage-cost-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 26, name: "Beverage Margin Calculator", slug: "beverage-margin-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 27, name: "Labor Cost Percentage", slug: "labor-cost-percentage-hospitality", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 28, name: "Restaurant Profit Calculator", slug: "restaurant-profit-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 29, name: "Restaurant Revenue Calculator", slug: "restaurant-revenue-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 30, name: "Seat Turnover Calculator", slug: "seat-turnover-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 31, name: "Table Utilization Calculator", slug: "table-utilization-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 32, name: "Seating Capacity Calculator", slug: "seating-capacity-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 33, name: "Reservation Capacity Planner", slug: "reservation-capacity-planner", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 34, name: "Restaurant Occupancy Calculator", slug: "restaurant-occupancy-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 35, name: "Catering Cost Calculator", slug: "catering-cost-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 36, name: "Catering Price Calculator", slug: "catering-price-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 37, name: "Catering Profit Calculator", slug: "catering-profit-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 38, name: "Event Food Quantity Calculator", slug: "event-food-quantity-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 39, name: "Guest Count Calculator", slug: "guest-count-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 40, name: "Food Inventory Calculator", slug: "food-inventory-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 41, name: "Par Level Calculator", slug: "par-level-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 42, name: "Restaurant Stock Count", slug: "restaurant-stock-count", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 43, name: "Prep Quantity Calculator", slug: "prep-quantity-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 44, name: "Prep Time Planner", slug: "prep-time-planner", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 45, name: "Kitchen Staffing Calculator", slug: "kitchen-staffing-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 46, name: "Server Staffing Calculator", slug: "server-staffing-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 47, name: "Shift Coverage Calculator", slug: "shift-coverage-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 48, name: "Tip Distribution Calculator", slug: "tip-distribution-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 49, name: "Service Charge Calculator", slug: "service-charge-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 50, name: "Restaurant Discount Calculator", slug: "restaurant-discount-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 51, name: "Promotion Profit Calculator", slug: "promotion-profit-calculator-hospitality", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 52, name: "Restaurant KPI Calculator", slug: "restaurant-kpi-calculator", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 53, name: "Opening Checklist", slug: "opening-checklist", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 54, name: "Closing Checklist", slug: "closing-checklist", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 55, name: "Kitchen Inspection Checklist", slug: "kitchen-inspection-checklist", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 56, name: "Food Inventory Checklist", slug: "food-inventory-checklist", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 57, name: "Service Quality Checklist", slug: "service-quality-checklist", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 58, name: "Restaurant Cleaning Checklist", slug: "restaurant-cleaning-checklist", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 59, name: "Food Waste Tracking Sheet", slug: "food-waste-tracking-sheet", category: "Hospitality & Restaurant Operations Tools", isPro: false },
  { id: 60, name: "Restaurant Operations Checklist", slug: "restaurant-operations-checklist", category: "Hospitality & Restaurant Operations Tools", isPro: false },

  // --- ⚡ 40 PRO / SAAS TOOLS (IDs 61-100 | isPro: true) ---
  { id: 61, name: "Restaurant Management Workspace", slug: "restaurant-management-workspace", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 62, name: "Hospitality Operations Workspace", slug: "hospitality-operations-workspace", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 63, name: "Multi-Location Restaurant Workspace", slug: "multi-location-restaurant-workspace", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 64, name: "Food Cost Management Workspace", slug: "food-cost-management-workspace", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 65, name: "Recipe Costing Workspace", slug: "recipe-costing-workspace", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 66, name: "Menu Engineering Workspace", slug: "menu-engineering-workspace", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 67, name: "Menu Profitability Dashboard", slug: "menu-profitability-dashboard", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 68, name: "Food Margin Dashboard", slug: "food-margin-dashboard", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 69, name: "Beverage Cost Dashboard", slug: "beverage-cost-dashboard", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 70, name: "Food Waste Management Workspace", slug: "food-waste-management-workspace", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 71, name: "Ingredient Inventory Workspace", slug: "ingredient-inventory-workspace", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 72, name: "Restaurant Replenishment Workspace", slug: "restaurant-replenishment-workspace", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 73, name: "Kitchen Production Workspace", slug: "kitchen-production-workspace", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 74, name: "Prep Planning Workspace", slug: "prep-planning-workspace", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 75, name: "Kitchen Scheduling Workspace", slug: "kitchen-scheduling-workspace", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 76, name: "Restaurant Staffing Workspace", slug: "restaurant-staffing-workspace", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 77, name: "Server Scheduling Workspace", slug: "server-scheduling-workspace", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 78, name: "Shift Management Workspace", slug: "shift-management-workspace", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 79, name: "Table Management Workspace", slug: "table-management-workspace", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 80, name: "Reservation Management Workspace", slug: "reservation-management-workspace", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 81, name: "Restaurant Capacity Dashboard", slug: "restaurant-capacity-dashboard", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 82, name: "Table Turnover Analytics", slug: "table-turnover-analytics", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 83, name: "Restaurant Revenue Dashboard", slug: "restaurant-revenue-dashboard", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 84, name: "Restaurant Profitability Workspace", slug: "restaurant-profitability-workspace", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 85, name: "Prime Cost Dashboard", slug: "prime-cost-dashboard", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 86, name: "Restaurant Promotion Workspace", slug: "restaurant-promotion-workspace", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 87, name: "Catering Management Workspace", slug: "catering-management-workspace", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 88, name: "Event Planning Workspace", slug: "event-planning-workspace", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 89, name: "Restaurant KPI Dashboard", slug: "restaurant-kpi-dashboard", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 90, name: "Restaurant Audit Workspace", slug: "restaurant-audit-workspace", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 91, name: "Restaurant Data Importer", slug: "restaurant-data-importer", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 92, name: "Restaurant Data Exporter", slug: "restaurant-data-exporter", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 93, name: "Restaurant API Workspace", slug: "restaurant-api-workspace", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 94, name: "Restaurant Workflow Automation", slug: "restaurant-workflow-automation", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 95, name: "Hospitality Alert Engine", slug: "hospitality-alert-engine", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 96, name: "Restaurant Forecasting Workspace", slug: "restaurant-forecasting-workspace", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 97, name: "Restaurant Intelligence Platform", slug: "restaurant-intelligence-platform", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 98, name: "Enterprise Restaurant Platform", slug: "enterprise-restaurant-platform", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 99, name: "Hospitality Operations Platform", slug: "hospitality-operations-platform", category: "Hospitality & Restaurant Operations Tools", isPro: true },
  { id: 100, name: "Restaurant Command Center", slug: "restaurant-command-center", category: "Hospitality & Restaurant Operations Tools", isPro: true }
];