export interface IAMTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const iamToolsList: IAMTool[] = [
  // --- 🔥 PRIORITY 20 FREE TOOLS (IDs 1-20 | isPro: false) ---
  { id: 1, name: "Permission Matrix Generator", slug: "permission-matrix-generator", category: "Identity & Access Management Tools", isPro: false },
  { id: 2, name: "Access Role Matrix", slug: "access-role-matrix", category: "Identity & Access Management Tools", isPro: false },
  { id: 3, name: "Role Hierarchy Builder", slug: "role-hierarchy-builder", category: "Identity & Access Management Tools", isPro: false },
  { id: 4, name: "Least Privilege Checklist", slug: "least-privilege-checklist", category: "Identity & Access Management Tools", isPro: false },
  { id: 5, name: "User Access Review", slug: "user-access-review", category: "Identity & Access Management Tools", isPro: false },
  { id: 6, name: "Privileged Access Review", slug: "privileged-access-review", category: "Identity & Access Management Tools", isPro: false },
  { id: 7, name: "Orphan Account Finder", slug: "orphan-account-finder", category: "Identity & Access Management Tools", isPro: false },
  { id: 8, name: "Dormant Account Checker", slug: "dormant-account-checker", category: "Identity & Access Management Tools", isPro: false },
  { id: 9, name: "Account Lifecycle Planner", slug: "account-lifecycle-planner", category: "Identity & Access Management Tools", isPro: false },
  { id: 10, name: "Joiner-Mover-Leaver Checklist", slug: "joiner-mover-leaver-checklist", category: "Identity & Access Management Tools", isPro: false },
  { id: 11, name: "Access Request Form Builder", slug: "access-request-form-builder", category: "Identity & Access Management Tools", isPro: false },
  { id: 12, name: "Access Approval Matrix", slug: "access-approval-matrix", category: "Identity & Access Management Tools", isPro: false },
  { id: 13, name: "Access Expiry Calculator", slug: "access-expiry-calculator", category: "Identity & Access Management Tools", isPro: false },
  { id: 14, name: "MFA Rollout Planner", slug: "mfa-rollout-planner", category: "Identity & Access Management Tools", isPro: false },
  { id: 15, name: "SSO Readiness Checklist", slug: "sso-readiness-checklist", category: "Identity & Access Management Tools", isPro: false },
  { id: 16, name: "User Provisioning Checklist", slug: "user-provisioning-checklist", category: "Identity & Access Management Tools", isPro: false },
  { id: 17, name: "Access Certification Checklist", slug: "access-certification-checklist", category: "Identity & Access Management Tools", isPro: false },
  { id: 18, name: "Identity Audit Checklist", slug: "identity-audit-checklist", category: "Identity & Access Management Tools", isPro: false },
  { id: 19, name: "Access Governance Checklist", slug: "access-governance-checklist", category: "Identity & Access Management Tools", isPro: false },
  { id: 20, name: "Role Definition Builder", slug: "role-definition-builder", category: "Identity & Access Management Tools", isPro: false },

  // --- REMAINING 40 CORE FREE TOOLS (IDs 21-60 | isPro: false) ---
  { id: 21, name: "User Role Mapper", slug: "user-role-mapper", category: "Identity & Access Management Tools", isPro: false },
  { id: 22, name: "Permission Group Builder", slug: "permission-group-builder", category: "Identity & Access Management Tools", isPro: false },
  { id: 23, name: "Access Level Planner", slug: "access-level-planner", category: "Identity & Access Management Tools", isPro: false },
  { id: 24, name: "Access Review Checklist", slug: "access-review-checklist", category: "Identity & Access Management Tools", isPro: false },
  { id: 25, name: "Application Access Review", slug: "application-access-review", category: "Identity & Access Management Tools", isPro: false },
  { id: 26, name: "Group Membership Review", slug: "group-membership-review", category: "Identity & Access Management Tools", isPro: false },
  { id: 27, name: "Duplicate Identity Checker", slug: "duplicate-identity-checker", category: "Identity & Access Management Tools", isPro: false },
  { id: 28, name: "Employee Access Checklist", slug: "employee-access-checklist", category: "Identity & Access Management Tools", isPro: false },
  { id: 29, name: "Contractor Access Checklist", slug: "contractor-access-checklist", category: "Identity & Access Management Tools", isPro: false },
  { id: 30, name: "Temporary Access Planner", slug: "temporary-access-planner", category: "Identity & Access Management Tools", isPro: false },
  { id: 31, name: "Emergency Access Checklist", slug: "emergency-access-checklist", category: "Identity & Access Management Tools", isPro: false },
  { id: 32, name: "Privileged Account Inventory", slug: "privileged-account-inventory", category: "Identity & Access Management Tools", isPro: false },
  { id: 33, name: "Service Account Inventory", slug: "service-account-inventory", category: "Identity & Access Management Tools", isPro: false },
  { id: 34, name: "Application Account Inventory", slug: "application-account-inventory", category: "Identity & Access Management Tools", isPro: false },
  { id: 35, name: "Identity Inventory", slug: "identity-inventory", category: "Identity & Access Management Tools", isPro: false },
  { id: 36, name: "Access Approval Form", slug: "access-approval-form", category: "Identity & Access Management Tools", isPro: false },
  { id: 37, name: "Access Request Checklist", slug: "access-request-checklist", category: "Identity & Access Management Tools", isPro: false },
  { id: 38, name: "Permission Request Generator", slug: "permission-request-generator", category: "Identity & Access Management Tools", isPro: false },
  { id: 39, name: "Role Request Generator", slug: "role-request-generator", category: "Identity & Access Management Tools", isPro: false },
  { id: 40, name: "Temporary Access Expiry Tracker", slug: "temporary-access-expiry-tracker", category: "Identity & Access Management Tools", isPro: false },
  { id: 41, name: "Passwordless Readiness Checklist", slug: "passwordless-readiness-checklist", category: "Identity & Access Management Tools", isPro: false },
  { id: 42, name: "SSO Application Inventory", slug: "sso-application-inventory", category: "Identity & Access Management Tools", isPro: false },
  { id: 43, name: "Identity Provider Checklist", slug: "identity-provider-checklist", category: "Identity & Access Management Tools", isPro: false },
  { id: 44, name: "Directory Migration Checklist", slug: "directory-migration-checklist", category: "Identity & Access Management Tools", isPro: false },
  { id: 45, name: "User Deprovisioning Checklist", slug: "user-deprovisioning-checklist", category: "Identity & Access Management Tools", isPro: false },
  { id: 46, name: "Account Termination Checklist", slug: "account-termination-checklist", category: "Identity & Access Management Tools", isPro: false },
  { id: 47, name: "Access Policy Generator", slug: "access-policy-generator", category: "Identity & Access Management Tools", isPro: false },
  { id: 48, name: "Role Policy Generator", slug: "role-policy-generator", category: "Identity & Access Management Tools", isPro: false },
  { id: 49, name: "Privileged Access Policy", slug: "privileged-access-policy", category: "Identity & Access Management Tools", isPro: false },
  { id: 50, name: "Identity Governance Checklist", slug: "identity-governance-checklist", category: "Identity & Access Management Tools", isPro: false },
  { id: 51, name: "Identity Incident Checklist", slug: "identity-incident-checklist", category: "Identity & Access Management Tools", isPro: false },
  { id: 52, name: "Access Exception Tracker", slug: "access-exception-tracker", category: "Identity & Access Management Tools", isPro: false },
  { id: 53, name: "Permission Exception Tracker", slug: "permission-exception-tracker", category: "Identity & Access Management Tools", isPro: false },
  { id: 54, name: "Access Change Log", slug: "access-change-log", category: "Identity & Access Management Tools", isPro: false },
  { id: 55, name: "Role Change Log", slug: "role-change-log", category: "Identity & Access Management Tools", isPro: false },
  { id: 56, name: "Identity Audit Report", slug: "identity-audit-report", category: "Identity & Access Management Tools", isPro: false },
  { id: 57, name: "Access Review Report", slug: "access-review-report", category: "Identity & Access Management Tools", isPro: false },
  { id: 58, name: "Permission Review Report", slug: "permission-review-report", category: "Identity & Access Management Tools", isPro: false },
  { id: 59, name: "Identity Inventory Report", slug: "identity-inventory-report", category: "Identity & Access Management Tools", isPro: false },
  { id: 60, name: "Access Governance Report", slug: "access-governance-report", category: "Identity & Access Management Tools", isPro: false },

  // --- ⚡ 40 PRO / SAAS TOOLS (IDs 61-100 | isPro: true) ---
  { id: 61, name: "Identity Management Workspace", slug: "identity-management-workspace", category: "Identity & Access Management Tools", isPro: true },
  { id: 62, name: "Access Governance Workspace", slug: "access-governance-workspace", category: "Identity & Access Management Tools", isPro: true },
  { id: 63, name: "Identity Lifecycle Workspace", slug: "identity-lifecycle-workspace", category: "Identity & Access Management Tools", isPro: true },
  { id: 64, name: "Role Management Workspace", slug: "role-management-workspace", category: "Identity & Access Management Tools", isPro: true },
  { id: 65, name: "Permission Management Workspace", slug: "permission-management-workspace", category: "Identity & Access Management Tools", isPro: true },
  { id: 66, name: "Access Review Dashboard", slug: "access-review-dashboard", category: "Identity & Access Management Tools", isPro: true },
  { id: 67, name: "Privileged Access Governance", slug: "privileged-access-governance", category: "Identity & Access Management Tools", isPro: true },
  { id: 68, name: "Identity Inventory Dashboard", slug: "identity-inventory-dashboard", category: "Identity & Access Management Tools", isPro: true },
  { id: 69, name: "Account Lifecycle Dashboard", slug: "account-lifecycle-dashboard", category: "Identity & Access Management Tools", isPro: true },
  { id: 70, name: "Joiner-Mover-Leaver Automation", slug: "joiner-mover-leaver-automation", category: "Identity & Access Management Tools", isPro: true },
  { id: 71, name: "User Provisioning Workspace", slug: "user-provisioning-workspace", category: "Identity & Access Management Tools", isPro: true },
  { id: 72, name: "User Deprovisioning Workspace", slug: "user-deprovisioning-workspace", category: "Identity & Access Management Tools", isPro: true },
  { id: 73, name: "Access Request Management", slug: "access-request-management", category: "Identity & Access Management Tools", isPro: true },
  { id: 74, name: "Access Approval Workspace", slug: "access-approval-workspace", category: "Identity & Access Management Tools", isPro: true },
  { id: 75, name: "Access Certification Workspace", slug: "access-certification-workspace", category: "Identity & Access Management Tools", isPro: true },
  { id: 76, name: "Role Engineering Workspace", slug: "role-engineering-workspace", category: "Identity & Access Management Tools", isPro: true },
  { id: 77, name: "Permission Analytics Workspace", slug: "permission-analytics-workspace", category: "Identity & Access Management Tools", isPro: true },
  { id: 78, name: "Entitlement Management Workspace", slug: "entitlement-management-workspace", category: "Identity & Access Management Tools", isPro: true },
  { id: 79, name: "Privileged Identity Dashboard", slug: "privileged-identity-dashboard", category: "Identity & Access Management Tools", isPro: true },
  { id: 80, name: "Service Account Management", slug: "service-account-management", category: "Identity & Access Management Tools", isPro: true },
  { id: 81, name: "Application Access Management", slug: "application-access-management", category: "Identity & Access Management Tools", isPro: true },
  { id: 82, name: "Identity Exception Management", slug: "identity-exception-management", category: "Identity & Access Management Tools", isPro: true },
  { id: 83, name: "Access Expiration Management", slug: "access-expiration-management", category: "Identity & Access Management Tools", isPro: true },
  { id: 84, name: "Identity Policy Management", slug: "identity-policy-management", category: "Identity & Access Management Tools", isPro: true },
  { id: 85, name: "SSO Application Management", slug: "sso-application-management", category: "Identity & Access Management Tools", isPro: true },
  { id: 86, name: "MFA Rollout Management", slug: "mfa-rollout-management", category: "Identity & Access Management Tools", isPro: true },
  { id: 87, name: "Directory Migration Workspace", slug: "directory-migration-workspace", category: "Identity & Access Management Tools", isPro: true },
  { id: 88, name: "Identity Audit Workspace", slug: "identity-audit-workspace", category: "Identity & Access Management Tools", isPro: true },
  { id: 89, name: "Access Compliance Dashboard", slug: "access-compliance-dashboard", category: "Identity & Access Management Tools", isPro: true },
  { id: 90, name: "Identity Analytics", slug: "identity-analytics", category: "Identity & Access Management Tools", isPro: true },
  { id: 91, name: "Identity Risk Analytics", slug: "identity-risk-analytics", category: "Identity & Access Management Tools", isPro: true },
  { id: 92, name: "Access Governance Reporting", slug: "access-governance-reporting", category: "Identity & Access Management Tools", isPro: true },
  { id: 93, name: "Identity Data Import Workspace", slug: "identity-data-import-workspace", category: "Identity & Access Management Tools", isPro: true },
  { id: 94, name: "Identity Data Export Workspace", slug: "identity-data-export-workspace", category: "Identity & Access Management Tools", isPro: true },
  { id: 95, name: "Identity API Workspace", slug: "identity-api-workspace", category: "Identity & Access Management Tools", isPro: true },
  { id: 96, name: "Identity Automation Workspace", slug: "identity-automation-workspace", category: "Identity & Access Management Tools", isPro: true },
  { id: 97, name: "Identity Workflow Engine", slug: "identity-workflow-engine", category: "Identity & Access Management Tools", isPro: true },
  { id: 98, name: "Identity Intelligence Platform", slug: "identity-intelligence-platform", category: "Identity & Access Management Tools", isPro: true },
  { id: 99, name: "Enterprise IAM Platform", slug: "enterprise-iam-platform", category: "Identity & Access Management Tools", isPro: true },
  { id: 100, name: "Identity Command Center", slug: "identity-command-center", category: "Identity & Access Management Tools", isPro: true }
];