export interface ImageTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const imageToolsList: ImageTool[] = [
  // --- TOP PRIORITY (FREE CORE TOOLS) ---
  { id: 1, name: "Image Compressor", slug: "image-compressor", category: "Image Tools", isPro: false },
  { id: 2, name: "Image Resizer", slug: "image-resizer", category: "Image Tools", isPro: false },
  { id: 3, name: "Image Converter", slug: "image-converter", category: "Image Tools", isPro: false },
  { id: 4, name: "Image Cropper", slug: "image-cropper", category: "Image Tools", isPro: false },
  { id: 5, name: "JPG to PNG", slug: "jpg-to-png", category: "Image Tools", isPro: false },
  { id: 6, name: "PNG to JPG", slug: "png-to-jpg", category: "Image Tools", isPro: false },
  { id: 7, name: "JPG to WebP", slug: "jpg-to-webp", category: "Image Tools", isPro: false },
  { id: 8, name: "PNG to WebP", slug: "png-to-webp", category: "Image Tools", isPro: false },
  { id: 9, name: "WebP to JPG", slug: "webp-to-jpg", category: "Image Tools", isPro: false },
  { id: 10, name: "HEIC to JPG", slug: "heic-to-jpg", category: "Image Tools", isPro: false },
  { id: 11, name: "Image Background Remover", slug: "image-background-remover", category: "Image Tools", isPro: false },
  { id: 12, name: "Image Background Changer", slug: "image-background-changer", category: "Image Tools", isPro: false },
  { id: 13, name: "Image Watermark Tool", slug: "image-watermark-tool", category: "Image Tools", isPro: false },
  { id: 14, name: "Image Metadata Viewer", slug: "image-metadata-viewer", category: "Image Tools", isPro: false },
  { id: 15, name: "EXIF Data Remover", slug: "exif-data-remover", category: "Image Tools", isPro: false },
  { id: 16, name: "Image Quality Checker", slug: "image-quality-checker", category: "Image Tools", isPro: false },
  { id: 17, name: "Image Resolution Checker", slug: "image-resolution-checker", category: "Image Tools", isPro: false },

  // --- REMAINING CORE / HIGH-DEMAND (FREE TOOLS: 18-60) ---
  { id: 18, name: "Image Rotator", slug: "image-rotator", category: "Image Tools", isPro: false },
  { id: 19, name: "Image Flipper", slug: "image-flipper", category: "Image Tools", isPro: false },
  { id: 20, name: "JPG Converter", slug: "jpg-converter", category: "Image Tools", isPro: false },
  { id: 21, name: "PNG Converter", slug: "png-converter", category: "Image Tools", isPro: false },
  { id: 22, name: "WebP Converter", slug: "webp-converter", category: "Image Tools", isPro: false },
  { id: 23, name: "GIF Converter", slug: "gif-converter", category: "Image Tools", isPro: false },
  { id: 24, name: "BMP Converter", slug: "bmp-converter", category: "Image Tools", isPro: false },
  { id: 25, name: "TIFF Converter", slug: "tiff-converter", category: "Image Tools", isPro: false },
  { id: 26, name: "SVG Converter", slug: "svg-converter", category: "Image Tools", isPro: false },
  { id: 27, name: "HEIC Converter", slug: "heic-converter", category: "Image Tools", isPro: false },
  { id: 28, name: "AVIF Converter", slug: "avif-converter", category: "Image Tools", isPro: false },
  { id: 29, name: "Image to JPG", slug: "image-to-jpg", category: "Image Tools", isPro: false },
  { id: 30, name: "Image to PNG", slug: "image-to-png", category: "Image Tools", isPro: false },
  { id: 31, name: "Image to WebP", slug: "image-to-webp", category: "Image Tools", isPro: false },
  { id: 32, name: "Image to GIF", slug: "image-to-gif", category: "Image Tools", isPro: false },
  { id: 33, name: "WebP to PNG", slug: "webp-to-png", category: "Image Tools", isPro: false },
  { id: 34, name: "HEIC to PNG", slug: "heic-to-png", category: "Image Tools", isPro: false },
  { id: 35, name: "Image Dimension Checker", slug: "image-dimension-checker", category: "Image Tools", isPro: false },
  { id: 36, name: "Image DPI Checker", slug: "image-dpi-checker", category: "Image Tools", isPro: false },
  { id: 37, name: "Image EXIF Viewer", slug: "image-exif-viewer", category: "Image Tools", isPro: false },
  { id: 38, name: "Image Filename Optimizer", slug: "image-filename-optimizer", category: "Image Tools", isPro: false },
  { id: 39, name: "Image Blur Tool", slug: "image-blur-tool", category: "Image Tools", isPro: false },
  { id: 40, name: "Image Sharpen Tool", slug: "image-sharpen-tool", category: "Image Tools", isPro: false },
  { id: 41, name: "Image Brightness Adjuster", slug: "image-brightness-adjuster", category: "Image Tools", isPro: false },
  { id: 42, name: "Image Contrast Adjuster", slug: "image-contrast-adjuster", category: "Image Tools", isPro: false },
  { id: 43, name: "Image Saturation Adjuster", slug: "image-saturation-adjuster", category: "Image Tools", isPro: false },
  { id: 44, name: "Image Grayscale Converter", slug: "image-grayscale-converter", category: "Image Tools", isPro: false },
  { id: 45, name: "Image Sepia Converter", slug: "image-sepia-converter", category: "Image Tools", isPro: false },
  { id: 46, name: "Image Color Inverter", slug: "image-color-inverter", category: "Image Tools", isPro: false },
  { id: 47, name: "Image Border Generator", slug: "image-border-generator", category: "Image Tools", isPro: false },
  { id: 48, name: "Image Rounded Corner Tool", slug: "image-rounded-corner-tool", category: "Image Tools", isPro: false },
  { id: 49, name: "Image Text Overlay Tool", slug: "image-text-overlay-tool", category: "Image Tools", isPro: false },
  { id: 50, name: "Image Annotation Tool", slug: "image-annotation-tool", category: "Image Tools", isPro: false },
  { id: 51, name: "Image Arrow Tool", slug: "image-arrow-tool", category: "Image Tools", isPro: false },
  { id: 52, name: "Image Highlight Tool", slug: "image-highlight-tool", category: "Image Tools", isPro: false },
  { id: 53, name: "Image Pixelate Tool", slug: "image-pixelate-tool", category: "Image Tools", isPro: false },
  { id: 54, name: "Image Censor Tool", slug: "image-censor-tool", category: "Image Tools", isPro: false },
  { id: 55, name: "Image Mosaic Tool", slug: "image-mosaic-tool", category: "Image Tools", isPro: false },
  { id: 56, name: "Image Collage Maker", slug: "image-collage-maker", category: "Image Tools", isPro: false },
  { id: 57, name: "Image Contact Sheet Maker", slug: "image-contact-sheet-maker", category: "Image Tools", isPro: false },
  { id: 58, name: "Image Splitter", slug: "image-splitter", category: "Image Tools", isPro: false },
  { id: 59, name: "Image Merger", slug: "image-merger", category: "Image Tools", isPro: false },
  { id: 60, name: "Image Frame Generator", slug: "image-frame-generator", category: "Image Tools", isPro: false },

  // --- TOP PRIORITY (PRO LEVEL TOOLS) ---
  { id: 61, name: "AI Image Upscaler", slug: "ai-image-upscaler", category: "Image Tools", isPro: true },
  { id: 62, name: "Super Resolution Tool", slug: "super-resolution-tool", category: "Image Tools", isPro: true },
  { id: 63, name: "Image Denoiser", slug: "image-denoiser", category: "Image Tools", isPro: true },
  { id: 64, name: "Object Removal Tool", slug: "object-removal-tool", category: "Image Tools", isPro: true },
  { id: 65, name: "Magic Eraser", slug: "magic-eraser", category: "Image Tools", isPro: true },
  { id: 66, name: "Old Photo Restoration", slug: "old-photo-restoration", category: "Image Tools", isPro: true },
  { id: 67, name: "Image Inpainting Tool", slug: "image-inpainting-tool", category: "Image Tools", isPro: true },
  { id: 68, name: "Image Duplicate Finder", slug: "image-duplicate-finder", category: "Image Tools", isPro: true },
  { id: 69, name: "Image SEO Analyzer", slug: "image-seo-analyzer", category: "Image Tools", isPro: true },
  { id: 70, name: "Batch Image Compressor", slug: "batch-image-compressor", category: "Image Tools", isPro: true },
  { id: 71, name: "Batch Image Converter", slug: "batch-image-converter", category: "Image Tools", isPro: true },
  { id: 72, name: "Batch Image Resizer", slug: "batch-image-resizer", category: "Image Tools", isPro: true },
  { id: 73, name: "Batch Metadata Cleaner", slug: "batch-metadata-cleaner", category: "Image Tools", isPro: true },
  { id: 74, name: "Responsive Image Generator", slug: "responsive-image-generator", category: "Image Tools", isPro: true },
  { id: 75, name: "Image Optimization Audit", slug: "image-optimization-audit", category: "Image Tools", isPro: true },
  { id: 76, name: "Image Forensics Analyzer", slug: "image-forensics-analyzer", category: "Image Tools", isPro: true },
  { id: 77, name: "Image Similarity Checker", slug: "image-similarity-checker", category: "Image Tools", isPro: true },
  { id: 78, name: "AI Image Extender", slug: "ai-image-extender", category: "Image Tools", isPro: true },

  // --- REMAINING PRO LEVEL TOOLS (79-100) ---
  { id: 79, name: "Face Blur Tool", slug: "face-blur-tool", category: "Image Tools", isPro: true },
  { id: 80, name: "Smart Background Replacement", slug: "smart-background-replacement", category: "Image Tools", isPro: true },
  { id: 81, name: "Background Defocus Tool", slug: "background-defocus-tool", category: "Image Tools", isPro: true },
  { id: 82, name: "Portrait Enhancement Tool", slug: "portrait-enhancement-tool", category: "Image Tools", isPro: true },
  { id: 83, name: "Face Retouching Tool", slug: "face-retouching-tool", category: "Image Tools", isPro: true },
  { id: 84, name: "Skin Smoothing Tool", slug: "skin-smoothing-tool", category: "Image Tools", isPro: true },
  { id: 85, name: "AI Image Deblurring Tool", slug: "ai-image-deblurring-tool", category: "Image Tools", isPro: true },
  { id: 86, name: "AI Image Colorizer", slug: "ai-image-colorizer", category: "Image Tools", isPro: true },
  { id: 87, name: "Photo Scratch Remover", slug: "photo-scratch-remover", category: "Image Tools", isPro: true },
  { id: 88, name: "Image Relighting Tool", slug: "image-relighting-tool", category: "Image Tools", isPro: true },
  { id: 89, name: "Generative Image Outpainting", slug: "generative-image-outpainting", category: "Image Tools", isPro: true },
  { id: 90, name: "Image Style Transfer", slug: "image-style-transfer", category: "Image Tools", isPro: true },
  { id: 91, name: "Image Color Palette Extractor", slug: "image-color-palette-extractor", category: "Image Tools", isPro: true },
  { id: 92, name: "Dominant Color Detector", slug: "dominant-color-detector", category: "Image Tools", isPro: true },
  { id: 93, name: "Perceptual Hash Generator", slug: "perceptual-hash-generator", category: "Image Tools", isPro: true },
  { id: 94, name: "Image Difference Detector", slug: "image-difference-detector", category: "Image Tools", isPro: true },
  { id: 95, name: "Image Steganography Tool", slug: "image-steganography-tool", category: "Image Tools", isPro: true },
  { id: 96, name: "Image Watermark Detection", slug: "image-watermark-detection", category: "Image Tools", isPro: true },
  { id: 97, name: "Image Compression Analyzer", slug: "image-compression-analyzer", category: "Image Tools", isPro: true },
  { id: 98, name: "Batch Image Renamer", slug: "batch-image-renamer", category: "Image Tools", isPro: true },
  { id: 99, name: "Srcset Generator", slug: "srcset-generator", category: "Image Tools", isPro: true },
  { id: 100, name: "Image Accessibility Analyzer", slug: "image-accessibility-analyzer", category: "Image Tools", isPro: true },
];