export interface IoTTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const iotToolsList: IoTTool[] = [
  // --- 🔥 PRIORITY 20 FREE TOOLS (IDs 1-20 | isPro: false) ---
  { id: 1, name: "IoT Battery Life Calculator", slug: "iot-battery-life-calculator", category: "IoT Tools", isPro: false },
  { id: 2, name: "Sensor Sampling Rate Calculator", slug: "sensor-sampling-rate-calculator", category: "IoT Tools", isPro: false },
  { id: 3, name: "Sensor Data Rate Calculator", slug: "sensor-data-rate-calculator", category: "IoT Tools", isPro: false },
  { id: 4, name: "IoT Bandwidth Calculator", slug: "iot-bandwidth-calculator", category: "IoT Tools", isPro: false },
  { id: 5, name: "IoT Data Storage Calculator", slug: "iot-data-storage-calculator", category: "IoT Tools", isPro: false },
  { id: 6, name: "MQTT Message Size Calculator", slug: "mqtt-message-size-calculator", category: "IoT Tools", isPro: false },
  { id: 7, name: "MQTT Bandwidth Calculator", slug: "mqtt-bandwidth-calculator", category: "IoT Tools", isPro: false },
  { id: 8, name: "MQTT Payload Formatter", slug: "mqtt-payload-formatter", category: "IoT Tools", isPro: false },
  { id: 9, name: "IoT Cloud Cost Calculator", slug: "iot-cloud-cost-calculator", category: "IoT Tools", isPro: false },
  { id: 10, name: "Cellular IoT Data Calculator", slug: "cellular-iot-data-calculator", category: "IoT Tools", isPro: false },
  { id: 11, name: "LoRaWAN Airtime Calculator", slug: "lorawan-airtime-calculator", category: "IoT Tools", isPro: false },
  { id: 12, name: "BLE Data Rate Calculator", slug: "ble-data-rate-calculator", category: "IoT Tools", isPro: false },
  { id: 13, name: "IoT Network Capacity Calculator", slug: "iot-network-capacity-calculator", category: "IoT Tools", isPro: false },
  { id: 14, name: "Gateway Capacity Calculator", slug: "gateway-capacity-calculator", category: "IoT Tools", isPro: false },
  { id: 15, name: "Signal-to-Noise Ratio Calculator", slug: "signal-to-noise-ratio-calculator", category: "IoT Tools", isPro: false },
  { id: 16, name: "MTBF Calculator", slug: "mtbf-calculator-iot", category: "IoT Tools", isPro: false },
  { id: 17, name: "MTTR Calculator", slug: "mttr-calculator-iot", category: "IoT Tools", isPro: false },
  { id: 18, name: "IoT Project Cost Calculator", slug: "iot-project-cost-calculator", category: "IoT Tools", isPro: false },
  { id: 19, name: "IoT Device Power Calculator", slug: "iot-device-power-calculator", category: "IoT Tools", isPro: false },
  { id: 20, name: "Sensor Battery Life Calculator", slug: "sensor-battery-life-calculator", category: "IoT Tools", isPro: false },

  // --- REMAINING 40 CORE FREE TOOLS (IDs 21-60 | isPro: false) ---
  { id: 21, name: "IoT Monthly Data Calculator", slug: "iot-monthly-data-calculator", category: "IoT Tools", isPro: false },
  { id: 22, name: "MQTT Topic Builder", slug: "mqtt-topic-builder", category: "IoT Tools", isPro: false },
  { id: 23, name: "MQTT Topic Validator", slug: "mqtt-topic-validator", category: "IoT Tools", isPro: false },
  { id: 24, name: "JSON Sensor Payload Builder", slug: "json-sensor-payload-builder", category: "IoT Tools", isPro: false },
  { id: 25, name: "IoT Payload Size Calculator", slug: "iot-payload-size-calculator", category: "IoT Tools", isPro: false },
  { id: 26, name: "Device Message Frequency Calculator", slug: "device-message-frequency-calculator", category: "IoT Tools", isPro: false },
  { id: 27, name: "Device Fleet Size Calculator", slug: "device-fleet-size-calculator", category: "IoT Tools", isPro: false },
  { id: 28, name: "IoT Connectivity Cost Calculator", slug: "iot-connectivity-cost-calculator", category: "IoT Tools", isPro: false },
  { id: 29, name: "LoRaWAN Payload Calculator", slug: "lorawan-payload-calculator", category: "IoT Tools", isPro: false },
  { id: 30, name: "LoRaWAN Range Planning Tool", slug: "lorawan-range-planning-tool", category: "IoT Tools", isPro: false },
  { id: 31, name: "BLE Battery Calculator", slug: "ble-battery-calculator", category: "IoT Tools", isPro: false },
  { id: 32, name: "Wi-Fi IoT Bandwidth Calculator", slug: "wi-fi-iot-bandwidth-calculator", category: "IoT Tools", isPro: false },
  { id: 33, name: "Zigbee Network Planner", slug: "zigbee-network-planner", category: "IoT Tools", isPro: false },
  { id: 34, name: "Edge Storage Calculator", slug: "edge-storage-calculator", category: "IoT Tools", isPro: false },
  { id: 35, name: "Edge Compute Capacity Calculator", slug: "edge-compute-capacity-calculator", category: "IoT Tools", isPro: false },
  { id: 36, name: "Sensor Resolution Calculator", slug: "sensor-resolution-calculator", category: "IoT Tools", isPro: false },
  { id: 37, name: "ADC Resolution Calculator", slug: "adc-resolution-calculator", category: "IoT Tools", isPro: false },
  { id: 38, name: "ADC Voltage Calculator", slug: "adc-voltage-calculator", category: "IoT Tools", isPro: false },
  { id: 39, name: "DAC Resolution Calculator", slug: "dac-resolution-calculator", category: "IoT Tools", isPro: false },
  { id: 40, name: "Sampling Frequency Calculator", slug: "sampling-frequency-calculator", category: "IoT Tools", isPro: false },
  { id: 41, name: "Nyquist Frequency Calculator", slug: "nyquist-frequency-calculator", category: "IoT Tools", isPro: false },
  { id: 42, name: "Sensor Accuracy Calculator", slug: "sensor-accuracy-calculator", category: "IoT Tools", isPro: false },
  { id: 43, name: "Measurement Error Calculator", slug: "measurement-error-calculator", category: "IoT Tools", isPro: false },
  { id: 44, name: "Temperature Sensor Converter", slug: "temperature-sensor-converter", category: "IoT Tools", isPro: false },
  { id: 45, name: "Pressure Sensor Converter", slug: "pressure-sensor-converter", category: "IoT Tools", isPro: false },
  { id: 46, name: "Humidity Sensor Calculator", slug: "humidity-sensor-calculator", category: "IoT Tools", isPro: false },
  { id: 47, name: "Distance Sensor Calculator", slug: "distance-sensor-calculator", category: "IoT Tools", isPro: false },
  { id: 48, name: "Light Sensor Calculator", slug: "light-sensor-calculator", category: "IoT Tools", isPro: false },
  { id: 49, name: "Motion Sensor Calculator", slug: "motion-sensor-calculator", category: "IoT Tools", isPro: false },
  { id: 50, name: "Device Uptime Calculator", slug: "device-uptime-calculator-iot", category: "IoT Tools", isPro: false },
  { id: 51, name: "IoT SLA Calculator", slug: "iot-sla-calculator", category: "IoT Tools", isPro: false },
  { id: 52, name: "Device Failure Rate Calculator", slug: "device-failure-rate-calculator", category: "IoT Tools", isPro: false },
  { id: 53, name: "IoT Deployment Checklist", slug: "iot-deployment-checklist", category: "IoT Tools", isPro: false },
  { id: 54, name: "Device Provisioning Checklist", slug: "device-provisioning-checklist", category: "IoT Tools", isPro: false },
  { id: 55, name: "Firmware Release Checklist", slug: "firmware-release-checklist", category: "IoT Tools", isPro: false },
  { id: 56, name: "IoT Security Checklist", slug: "iot-security-checklist", category: "IoT Tools", isPro: false },
  { id: 57, name: "IoT Connectivity Checklist", slug: "iot-connectivity-checklist", category: "IoT Tools", isPro: false },
  { id: 58, name: "Sensor Calibration Checklist", slug: "sensor-calibration-checklist", category: "IoT Tools", isPro: false },
  { id: 59, name: "Edge Deployment Checklist", slug: "edge-deployment-checklist", category: "IoT Tools", isPro: false },
  { id: 60, name: "IoT Maintenance Checklist", slug: "iot-maintenance-checklist", category: "IoT Tools", isPro: false },

  // --- ⚡ 40 PRO / SAAS TOOLS (IDs 61-100 | isPro: true) ---
  { id: 61, name: "IoT Fleet Management Workspace", slug: "iot-fleet-management-workspace", category: "IoT Tools", isPro: true },
  { id: 62, name: "Device Health Dashboard", slug: "device-health-dashboard-iot", category: "IoT Tools", isPro: true },
  { id: 63, name: "Device Provisioning Workspace", slug: "device-provisioning-workspace", category: "IoT Tools", isPro: true },
  { id: 64, name: "Device Inventory Dashboard", slug: "device-inventory-dashboard", category: "IoT Tools", isPro: true },
  { id: 65, name: "IoT Device Monitoring", slug: "iot-device-monitoring", category: "IoT Tools", isPro: true },
  { id: 66, name: "IoT Battery Monitoring", slug: "iot-battery-monitoring", category: "IoT Tools", isPro: true },
  { id: 67, name: "Sensor Health Dashboard", slug: "sensor-health-dashboard", category: "IoT Tools", isPro: true },
  { id: 68, name: "IoT Connectivity Monitoring", slug: "iot-connectivity-monitoring", category: "IoT Tools", isPro: true },
  { id: 69, name: "MQTT Monitoring Workspace", slug: "mqtt-monitoring-workspace", category: "IoT Tools", isPro: true },
  { id: 70, name: "IoT Data Pipeline Workspace", slug: "iot-data-pipeline-workspace", category: "IoT Tools", isPro: true },
  { id: 71, name: "IoT Data Ingestion Workspace", slug: "iot-data-ingestion-workspace", category: "IoT Tools", isPro: true },
  { id: 72, name: "IoT Data Storage Planner", slug: "iot-data-storage-planner", category: "IoT Tools", isPro: true },
  { id: 73, name: "IoT Cloud Cost Dashboard", slug: "iot-cloud-cost-dashboard", category: "IoT Tools", isPro: true },
  { id: 74, name: "IoT Bandwidth Optimization", slug: "iot-bandwidth-optimization", category: "IoT Tools", isPro: true },
  { id: 75, name: "IoT Network Planning Workspace", slug: "iot-network-planning-workspace", category: "IoT Tools", isPro: true },
  { id: 76, name: "LoRaWAN Deployment Planner", slug: "lorawan-deployment-planner", category: "IoT Tools", isPro: true },
  { id: 77, name: "BLE Deployment Planner", slug: "ble-deployment-planner", category: "IoT Tools", isPro: true },
  { id: 78, name: "Gateway Planning Workspace", slug: "gateway-planning-workspace", category: "IoT Tools", isPro: true },
  { id: 79, name: "Edge Computing Planner", slug: "edge-computing-planner", category: "IoT Tools", isPro: true },
  { id: 80, name: "Edge Resource Dashboard", slug: "edge-resource-dashboard", category: "IoT Tools", isPro: true },
  { id: 81, name: "IoT Device Configuration Manager", slug: "iot-device-configuration-manager", category: "IoT Tools", isPro: true },
  { id: 82, name: "IoT Firmware Management", slug: "iot-firmware-management", category: "IoT Tools", isPro: true },
  { id: 83, name: "Firmware Version Workspace", slug: "firmware-version-workspace", category: "IoT Tools", isPro: true },
  { id: 84, name: "OTA Update Management", slug: "ota-update-management", category: "IoT Tools", isPro: true },
  { id: 85, name: "IoT Security Management", slug: "iot-security-management", category: "IoT Tools", isPro: true },
  { id: 86, name: "Device Certificate Management", slug: "device-certificate-management", category: "IoT Tools", isPro: true },
  { id: 87, name: "IoT Access Management", slug: "iot-access-management", category: "IoT Tools", isPro: true },
  { id: 88, name: "IoT Incident Management", slug: "iot-incident-management", category: "IoT Tools", isPro: true },
  { id: 89, name: "IoT Alert Management", slug: "iot-alert-management", category: "IoT Tools", isPro: true },
  { id: 90, name: "IoT SLA Monitoring", slug: "iot-sla-monitoring", category: "IoT Tools", isPro: true },
  { id: 91, name: "Device Reliability Analytics", slug: "device-reliability-analytics", category: "IoT Tools", isPro: true },
  { id: 92, name: "MTBF/MTTR Analytics", slug: "mtbf-mttr-analytics", category: "IoT Tools", isPro: true },
  { id: 93, name: "Sensor Data Analytics", slug: "sensor-data-analytics", category: "IoT Tools", isPro: true },
  { id: 94, name: "IoT Time-Series Dashboard", slug: "iot-time-series-dashboard", category: "IoT Tools", isPro: true },
  { id: 95, name: "IoT Data Import Workspace", slug: "iot-data-import-workspace", category: "IoT Tools", isPro: true },
  { id: 96, name: "IoT Data Export Workspace", slug: "iot-data-export-workspace", category: "IoT Tools", isPro: true },
  { id: 97, name: "IoT API Workspace", slug: "iot-api-workspace", category: "IoT Tools", isPro: true },
  { id: 98, name: "IoT Automation Workspace", slug: "iot-automation-workspace", category: "IoT Tools", isPro: true },
  { id: 99, name: "IoT Intelligence Platform", slug: "iot-intelligence-platform", category: "IoT Tools", isPro: true },
  { id: 100, name: "Enterprise IoT Command Center", slug: "enterprise-iot-command-center", category: "IoT Tools", isPro: true }
];