export interface LegalTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const legalToolsList: LegalTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-15) ---
  { id: 1, name: "Privacy Policy Generator", slug: "privacy-policy-generator", category: "Legal Tools", isPro: false },
  { id: 2, name: "Terms of Service Generator", slug: "terms-of-service-generator", category: "Legal Tools", isPro: false },
  { id: 3, name: "NDA Generator", slug: "nda-generator", category: "Legal Tools", isPro: false },
  { id: 4, name: "Freelance Contract Generator", slug: "freelance-contract-generator", category: "Legal Tools", isPro: false },
  { id: 5, name: "Independent Contractor Agreement Generator", slug: "independent-contractor-agreement-generator", category: "Legal Tools", isPro: false },
  { id: 6, name: "Employment Agreement Generator", slug: "employment-agreement-generator", category: "Legal Tools", isPro: false },
  { id: 7, name: "Service Agreement Generator", slug: "service-agreement-generator", category: "Legal Tools", isPro: false },
  { id: 8, name: "Consulting Agreement Generator", slug: "consulting-agreement-generator", category: "Legal Tools", isPro: false },
  { id: 9, name: "Cookie Policy Generator", slug: "cookie-policy-generator", category: "Legal Tools", isPro: false },
  { id: 10, name: "Disclaimer Generator", slug: "disclaimer-generator", category: "Legal Tools", isPro: false },
  { id: 11, name: "Refund Policy Generator", slug: "refund-policy-generator", category: "Legal Tools", isPro: false },
  { id: 12, name: "Data Processing Agreement Generator", slug: "data-processing-agreement-generator", category: "Legal Tools", isPro: false },
  { id: 13, name: "Contract Checklist", slug: "contract-checklist", category: "Legal Tools", isPro: false },
  { id: 14, name: "Contract Review Checklist", slug: "contract-review-checklist", category: "Legal Tools", isPro: false },
  { id: 15, name: "Legal Document Generator", slug: "legal-document-generator", category: "Legal Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (16-60) ---
  { id: 16, name: "Contract Template Generator", slug: "contract-template-generator", category: "Legal Tools", isPro: false },
  { id: 17, name: "Return Policy Generator", slug: "return-policy-generator", category: "Legal Tools", isPro: false },
  { id: 18, name: "Website Terms Generator", slug: "website-terms-generator", category: "Legal Tools", isPro: false },
  { id: 19, name: "Website Disclaimer Generator", slug: "website-disclaimer-generator", category: "Legal Tools", isPro: false },
  { id: 20, name: "Non-Compete Agreement Template", slug: "non-compete-agreement-template", category: "Legal Tools", isPro: false },
  { id: 21, name: "Non-Solicitation Agreement Template", slug: "non-solicitation-agreement-template", category: "Legal Tools", isPro: false },
  { id: 22, name: "Partnership Agreement Generator", slug: "partnership-agreement-generator", category: "Legal Tools", isPro: false },
  { id: 23, name: "Operating Agreement Generator", slug: "operating-agreement-generator", category: "Legal Tools", isPro: false },
  { id: 24, name: "Business Purchase Agreement Template", slug: "business-purchase-agreement-template", category: "Legal Tools", isPro: false },
  { id: 25, name: "Sales Agreement Generator", slug: "sales-agreement-generator", category: "Legal Tools", isPro: false },
  { id: 26, name: "Invoice Terms Generator", slug: "invoice-terms-generator", category: "Legal Tools", isPro: false },
  { id: 27, name: "Payment Terms Generator", slug: "payment-terms-generator", category: "Legal Tools", isPro: false },
  { id: 28, name: "Late Payment Notice Generator", slug: "late-payment-notice-generator", category: "Legal Tools", isPro: false },
  { id: 29, name: "Demand Letter Generator", slug: "demand-letter-generator", category: "Legal Tools", isPro: false },
  { id: 30, name: "Cease and Desist Letter Generator", slug: "cease-and-desist-letter-generator", category: "Legal Tools", isPro: false },
  { id: 31, name: "Complaint Letter Generator", slug: "complaint-letter-generator", category: "Legal Tools", isPro: false },
  { id: 32, name: "Authorization Letter Generator", slug: "authorization-letter-generator", category: "Legal Tools", isPro: false },
  { id: 33, name: "Power of Attorney Template", slug: "power-of-attorney-template", category: "Legal Tools", isPro: false },
  { id: 34, name: "Affidavit Template", slug: "affidavit-template", category: "Legal Tools", isPro: false },
  { id: 35, name: "Declaration Template", slug: "declaration-template", category: "Legal Tools", isPro: false },
  { id: 36, name: "Consent Form Generator", slug: "consent-form-generator", category: "Legal Tools", isPro: false },
  { id: 37, name: "Release Form Generator", slug: "release-form-generator", category: "Legal Tools", isPro: false },
  { id: 38, name: "Liability Waiver Generator", slug: "liability-waiver-generator", category: "Legal Tools", isPro: false },
  { id: 39, name: "Photo Release Form Generator", slug: "photo-release-form-generator", category: "Legal Tools", isPro: false },
  { id: 40, name: "Model Release Form Generator", slug: "model-release-form-generator", category: "Legal Tools", isPro: false },
  { id: 41, name: "Event Waiver Generator", slug: "event-waiver-generator", category: "Legal Tools", isPro: false },
  { id: 42, name: "Property Release Form Generator", slug: "property-release-form-generator", category: "Legal Tools", isPro: false },
  { id: 43, name: "Legal Notice Generator", slug: "legal-notice-generator", category: "Legal Tools", isPro: false },
  { id: 44, name: "Legal Letter Generator", slug: "legal-letter-generator", category: "Legal Tools", isPro: false },
  { id: 45, name: "Meeting Resolution Generator", slug: "meeting-resolution-generator", category: "Legal Tools", isPro: false },
  { id: 46, name: "Board Resolution Generator", slug: "board-resolution-generator", category: "Legal Tools", isPro: false },
  { id: 47, name: "Shareholder Resolution Generator", slug: "shareholder-resolution-generator", category: "Legal Tools", isPro: false },
  { id: 48, name: "Legal Document Checklist", slug: "legal-document-checklist", category: "Legal Tools", isPro: false },
  { id: 49, name: "Business Compliance Checklist", slug: "business-compliance-checklist", category: "Legal Tools", isPro: false },
  { id: 50, name: "Privacy Compliance Checklist", slug: "privacy-compliance-checklist", category: "Legal Tools", isPro: false },
  { id: 51, name: "Contract Date Calculator", slug: "contract-date-calculator", category: "Legal Tools", isPro: false },
  { id: 52, name: "Notice Period Calculator", slug: "notice-period-calculator", category: "Legal Tools", isPro: false },
  { id: 53, name: "Payment Deadline Calculator", slug: "payment-deadline-calculator", category: "Legal Tools", isPro: false },
  { id: 54, name: "Contract Renewal Reminder", slug: "contract-renewal-reminder", category: "Legal Tools", isPro: false },
  { id: 55, name: "Lease Payment Calculator", slug: "lease-payment-calculator", category: "Legal Tools", isPro: false },
  { id: 56, name: "Simple Interest Legal Calculator", slug: "simple-interest-legal-calculator", category: "Legal Tools", isPro: false },
  { id: 57, name: "Settlement Calculator", slug: "settlement-calculator", category: "Legal Tools", isPro: false },
  { id: 58, name: "Damages Calculator", slug: "damages-calculator", category: "Legal Tools", isPro: false },
  { id: 59, name: "Attorney Fee Calculator", slug: "attorney-fee-calculator", category: "Legal Tools", isPro: false },
  { id: 60, name: "Legal Cost Estimator", slug: "legal-cost-estimator", category: "Legal Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "AI Contract Analyzer", slug: "ai-contract-analyzer", category: "Legal Tools", isPro: true },
  { id: 62, name: "Contract Summarizer", slug: "contract-summarizer", category: "Legal Tools", isPro: true },
  { id: 63, name: "Contract Comparison Tool", slug: "contract-comparison-tool", category: "Legal Tools", isPro: true },
  { id: 64, name: "Contract Clause Analyzer", slug: "contract-clause-analyzer", category: "Legal Tools", isPro: true },
  { id: 65, name: "Contract Risk Analyzer", slug: "contract-risk-analyzer", category: "Legal Tools", isPro: true },
  { id: 66, name: "Contract Obligation Tracker", slug: "contract-obligation-tracker", category: "Legal Tools", isPro: true },
  { id: 67, name: "AI Contract Summarizer", slug: "ai-contract-summarizer", category: "Legal Tools", isPro: true },
  { id: 68, name: "Contract Clause Extractor", slug: "contract-clause-extractor", category: "Legal Tools", isPro: true },
  { id: 69, name: "Contract Redline Assistant", slug: "contract-redline-assistant", category: "Legal Tools", isPro: true },
  { id: 70, name: "Contract Renewal Tracker", slug: "contract-renewal-tracker", category: "Legal Tools", isPro: true },
  { id: 71, name: "Contract Deadline Tracker", slug: "contract-deadline-tracker", category: "Legal Tools", isPro: true },
  { id: 72, name: "Legal Document Search", slug: "legal-document-search", category: "Legal Tools", isPro: true },
  { id: 73, name: "Multi-Document Legal Search", slug: "multi-document-legal-search", category: "Legal Tools", isPro: true },
  { id: 74, name: "Legal Document Q&A", slug: "legal-document-qa", category: "Legal Tools", isPro: true },
  { id: 75, name: "Legal Citation Formatter", slug: "legal-citation-formatter", category: "Legal Tools", isPro: true },
  { id: 76, name: "Case Citation Checker", slug: "case-citation-checker", category: "Legal Tools", isPro: true },
  { id: 77, name: "Legal Citation Extractor", slug: "legal-citation-extractor", category: "Legal Tools", isPro: true },
  { id: 78, name: "Legal Reference Organizer", slug: "legal-reference-organizer", category: "Legal Tools", isPro: true },
  { id: 79, name: "Legal Research Organizer", slug: "legal-research-organizer", category: "Legal Tools", isPro: true },
  { id: 80, name: "Legal Research Summarizer", slug: "legal-research-summarizer", category: "Legal Tools", isPro: true },
  { id: 81, name: "Legal Research Comparison Tool", slug: "legal-research-comparison-tool", category: "Legal Tools", isPro: true },
  { id: 82, name: "Regulatory Compliance Checklist", slug: "regulatory-compliance-checklist", category: "Legal Tools", isPro: true },
  { id: 83, name: "Compliance Risk Assessment", slug: "compliance-risk-assessment", category: "Legal Tools", isPro: true },
  { id: 84, name: "GDPR Compliance Checklist", slug: "gdpr-compliance-checklist", category: "Legal Tools", isPro: true },
  { id: 85, name: "CCPA Compliance Checklist", slug: "ccpa-compliance-checklist", category: "Legal Tools", isPro: true },
  { id: 86, name: "Accessibility Compliance Checklist", slug: "accessibility-compliance-checklist", category: "Legal Tools", isPro: true },
  { id: 87, name: "Cookie Compliance Analyzer", slug: "cookie-compliance-analyzer", category: "Legal Tools", isPro: true },
  { id: 88, name: "Privacy Policy Analyzer", slug: "privacy-policy-analyzer", category: "Legal Tools", isPro: true },
  { id: 89, name: "Terms of Service Analyzer", slug: "terms-of-service-analyzer", category: "Legal Tools", isPro: true },
  { id: 90, name: "NDA Risk Analyzer", slug: "nda-risk-analyzer", category: "Legal Tools", isPro: true },
  { id: 91, name: "Employment Contract Analyzer", slug: "employment-contract-analyzer", category: "Legal Tools", isPro: true },
  { id: 92, name: "Vendor Contract Analyzer", slug: "vendor-contract-analyzer", category: "Legal Tools", isPro: true },
  { id: 93, name: "SaaS Agreement Analyzer", slug: "saas-agreement-analyzer", category: "Legal Tools", isPro: true },
  { id: 94, name: "Data Processing Agreement Analyzer", slug: "data-processing-agreement-analyzer", category: "Legal Tools", isPro: true },
  { id: 95, name: "Legal Matter Tracker", slug: "legal-matter-tracker", category: "Legal Tools", isPro: true },
  { id: 96, name: "Legal Case Timeline Builder", slug: "legal-case-timeline-builder", category: "Legal Tools", isPro: true },
  { id: 97, name: "Legal Evidence Organizer", slug: "legal-evidence-organizer", category: "Legal Tools", isPro: true },
  { id: 98, name: "Legal Intake Form Builder", slug: "legal-intake-form-builder", category: "Legal Tools", isPro: true },
  { id: 99, name: "Legal Workflow Workspace", slug: "legal-workflow-workspace", category: "Legal Tools", isPro: true },
  { id: 100, name: "Legal Document Management Workspace", slug: "legal-document-management-workspace", category: "Legal Tools", isPro: true },
];