export interface LogoBrandingTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const logoBrandingToolsList: LogoBrandingTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "Logo Maker", slug: "logo-maker", category: "Logo & Branding Tools", isPro: false },
  { id: 2, name: "Logo Generator", slug: "logo-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 3, name: "Logo Idea Generator", slug: "logo-idea-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 4, name: "Logo Color Generator", slug: "logo-color-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 5, name: "Logo Mockup Generator", slug: "logo-mockup-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 6, name: "Logo Vectorizer", slug: "logo-vectorizer", category: "Logo & Branding Tools", isPro: false },
  { id: 7, name: "Logo SVG Converter", slug: "logo-svg-converter", category: "Logo & Branding Tools", isPro: false },
  { id: 8, name: "Favicon Generator", slug: "favicon-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 9, name: "Brand Name Generator", slug: "brand-name-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 10, name: "Business Name Generator", slug: "business-name-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 11, name: "Startup Name Generator", slug: "startup-name-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 12, name: "Brand Slogan Generator", slug: "brand-slogan-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 13, name: "Brand Voice Generator", slug: "brand-voice-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 14, name: "Brand Color Generator", slug: "brand-color-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 15, name: "Brand Font Pairing Generator", slug: "brand-font-pairing-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 16, name: "Brand Guidelines Generator", slug: "brand-guidelines-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 17, name: "Brand Kit Generator", slug: "brand-kit-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 18, name: "Logo Concept Generator", slug: "logo-concept-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 19, name: "Logo Wordmark Generator", slug: "logo-wordmark-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 20, name: "Brand Tagline Generator", slug: "brand-tagline-generator", category: "Logo & Branding Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Logo Symbol Generator", slug: "logo-symbol-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 22, name: "Logo Icon Generator", slug: "logo-icon-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 23, name: "Logo Monogram Generator", slug: "logo-monogram-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 24, name: "Logo Badge Generator", slug: "logo-badge-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 25, name: "Logo Emblem Generator", slug: "logo-emblem-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 26, name: "Logo Initial Generator", slug: "logo-initial-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 27, name: "Logo Font Finder", slug: "logo-font-finder", category: "Logo & Branding Tools", isPro: false },
  { id: 28, name: "Logo Font Pairing Tool", slug: "logo-font-pairing-tool", category: "Logo & Branding Tools", isPro: false },
  { id: 29, name: "Logo Color Palette Generator", slug: "logo-color-palette-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 30, name: "Logo Shape Generator", slug: "logo-shape-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 31, name: "Logo Layout Generator", slug: "logo-layout-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 32, name: "Logo Background Remover", slug: "logo-background-remover", category: "Logo & Branding Tools", isPro: false },
  { id: 33, name: "Raster to Vector Logo Converter", slug: "raster-to-vector-logo-converter", category: "Logo & Branding Tools", isPro: false },
  { id: 34, name: "Logo PNG Converter", slug: "logo-png-converter", category: "Logo & Branding Tools", isPro: false },
  { id: 35, name: "Logo Size Generator", slug: "logo-size-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 36, name: "Logo App Icon Generator", slug: "logo-app-icon-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 37, name: "Logo Social Profile Generator", slug: "logo-social-profile-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 38, name: "Logo Watermark Generator", slug: "logo-watermark-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 39, name: "Logo Stamp Generator", slug: "logo-stamp-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 40, name: "Logo Signature Generator", slug: "logo-signature-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 41, name: "Product Name Generator", slug: "product-name-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 42, name: "Brand Mission Generator", slug: "brand-mission-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 43, name: "Brand Vision Generator", slug: "brand-vision-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 44, name: "Brand Values Generator", slug: "brand-values-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 45, name: "Brand Story Generator", slug: "brand-story-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 46, name: "Brand Personality Generator", slug: "brand-personality-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 47, name: "Brand Archetype Generator", slug: "brand-archetype-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 48, name: "Brand Typography Generator", slug: "brand-typography-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 49, name: "Brand Style Guide Generator", slug: "brand-style-guide-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 50, name: "Brand Identity Checklist", slug: "brand-identity-checklist", category: "Logo & Branding Tools", isPro: false },
  { id: 51, name: "Brand Positioning Generator", slug: "brand-positioning-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 52, name: "Brand Audience Profile Generator", slug: "brand-audience-profile-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 53, name: "Brand Messaging Generator", slug: "brand-messaging-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 54, name: "Brand Promise Generator", slug: "brand-promise-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 55, name: "Brand Differentiator Generator", slug: "brand-differentiator-generator", category: "Logo & Branding Tools", isPro: false },
  { id: 56, name: "Brand Competitor Comparison", slug: "brand-competitor-comparison", category: "Logo & Branding Tools", isPro: false },
  { id: 57, name: "Brand Consistency Checker", slug: "brand-consistency-checker", category: "Logo & Branding Tools", isPro: false },
  { id: 58, name: "Logo Similarity Checker", slug: "logo-similarity-checker", category: "Logo & Branding Tools", isPro: false },
  { id: 59, name: "Logo Quality Checker", slug: "logo-quality-checker", category: "Logo & Branding Tools", isPro: false },
  { id: 60, name: "Brand Asset Checklist", slug: "brand-asset-checklist", category: "Logo & Branding Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "AI Logo Generator", slug: "ai-logo-generator", category: "Logo & Branding Tools", isPro: true },
  { id: 62, name: "AI Brand Identity Generator", slug: "ai-brand-identity-generator", category: "Logo & Branding Tools", isPro: true },
  { id: 63, name: "AI Brand Naming Engine", slug: "ai-brand-naming-engine", category: "Logo & Branding Tools", isPro: true },
  { id: 64, name: "AI Logo Concept Generator", slug: "ai-logo-concept-generator", category: "Logo & Branding Tools", isPro: true },
  { id: 65, name: "AI Brand Strategy Generator", slug: "ai-brand-strategy-generator", category: "Logo & Branding Tools", isPro: true },
  { id: 66, name: "AI Brand Positioning Analyzer", slug: "ai-brand-positioning-analyzer", category: "Logo & Branding Tools", isPro: true },
  { id: 67, name: "AI Brand Voice Analyzer", slug: "ai-brand-voice-analyzer", category: "Logo & Branding Tools", isPro: true },
  { id: 68, name: "AI Brand Personality Analyzer", slug: "ai-brand-personality-analyzer", category: "Logo & Branding Tools", isPro: true },
  { id: 69, name: "AI Trademark Risk Precheck", slug: "ai-trademark-risk-precheck", category: "Logo & Branding Tools", isPro: true },
  { id: 70, name: "AI Logo Quality Analyzer", slug: "ai-logo-quality-analyzer", category: "Logo & Branding Tools", isPro: true },
  { id: 71, name: "AI Logo Similarity Analyzer", slug: "ai-logo-similarity-analyzer", category: "Logo & Branding Tools", isPro: true },
  { id: 72, name: "AI Brand Consistency Analyzer", slug: "ai-brand-consistency-analyzer", category: "Logo & Branding Tools", isPro: true },
  { id: 73, name: "Brand Identity Scoring Engine", slug: "brand-identity-scoring-engine", category: "Logo & Branding Tools", isPro: true },
  { id: 74, name: "Brand Recognition Analyzer", slug: "brand-recognition-analyzer", category: "Logo & Branding Tools", isPro: true },
  { id: 75, name: "Brand Differentiation Analyzer", slug: "brand-differentiation-analyzer", category: "Logo & Branding Tools", isPro: true },
  { id: 76, name: "Brand Positioning Matrix", slug: "brand-positioning-matrix", category: "Logo & Branding Tools", isPro: true },
  { id: 77, name: "Competitor Brand Analyzer", slug: "competitor-brand-analyzer", category: "Logo & Branding Tools", isPro: true },
  { id: 78, name: "Brand Color Psychology Analyzer", slug: "brand-color-psychology-analyzer", category: "Logo & Branding Tools", isPro: true },
  { id: 79, name: "Brand Typography Analyzer", slug: "brand-typography-analyzer", category: "Logo & Branding Tools", isPro: true },
  { id: 80, name: "Brand Visual System Builder", slug: "brand-visual-system-builder", category: "Logo & Branding Tools", isPro: true },
  { id: 81, name: "Brand Asset Generator", slug: "brand-asset-generator", category: "Logo & Branding Tools", isPro: true },
  { id: 82, name: "Brand Guidelines Builder", slug: "brand-guidelines-builder", category: "Logo & Branding Tools", isPro: true },
  { id: 83, name: "Brand Kit Automation", slug: "brand-kit-automation", category: "Logo & Branding Tools", isPro: true },
  { id: 84, name: "Multi-Brand Asset Manager", slug: "multi-brand-asset-manager", category: "Logo & Branding Tools", isPro: true },
  { id: 85, name: "Brand Approval Workflow", slug: "brand-approval-workflow", category: "Logo & Branding Tools", isPro: true },
  { id: 86, name: "Brand Compliance Checker", slug: "brand-compliance-checker", category: "Logo & Branding Tools", isPro: true },
  { id: 87, name: "Brand Governance Dashboard", slug: "brand-governance-dashboard", category: "Logo & Branding Tools", isPro: true },
  { id: 88, name: "Brand Usage Monitor", slug: "brand-usage-monitor", category: "Logo & Branding Tools", isPro: true },
  { id: 89, name: "Brand Asset Search Engine", slug: "brand-asset-search-engine", category: "Logo & Branding Tools", isPro: true },
  { id: 90, name: "White-Label Brand Kit Builder", slug: "white-label-brand-kit-builder", category: "Logo & Branding Tools", isPro: true },
  { id: 91, name: "Agency Branding Workspace", slug: "agency-branding-workspace", category: "Logo & Branding Tools", isPro: true },
  { id: 92, name: "Startup Branding Workspace", slug: "startup-branding-workspace", category: "Logo & Branding Tools", isPro: true },
  { id: 93, name: "Enterprise Brand Management", slug: "enterprise-brand-management", category: "Logo & Branding Tools", isPro: true },
  { id: 94, name: "Brand Intelligence Dashboard", slug: "brand-intelligence-dashboard", category: "Logo & Branding Tools", isPro: true },
  { id: 95, name: "Brand Performance Tracker", slug: "brand-performance-tracker", category: "Logo & Branding Tools", isPro: true },
  { id: 96, name: "Creative Brand Testing Tool", slug: "creative-brand-testing-tool", category: "Logo & Branding Tools", isPro: true },
  { id: 97, name: "Brand A/B Testing Workspace", slug: "brand-ab-testing-workspace", category: "Logo & Branding Tools", isPro: true },
  { id: 98, name: "AI Brand Consultant", slug: "ai-brand-consultant", category: "Logo & Branding Tools", isPro: true },
  { id: 99, name: "Complete Brand Identity Workspace", slug: "complete-brand-identity-workspace", category: "Logo & Branding Tools", isPro: true },
  { id: 100, name: "Enterprise Brand Intelligence Platform", slug: "enterprise-brand-intelligence-platform", category: "Logo & Branding Tools", isPro: true },
];