export interface MathTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const mathToolsList: MathTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "Percentage Calculator", slug: "percentage-calculator", category: "Mathematics Tools", isPro: false },
  { id: 2, name: "Percentage Change Calculator", slug: "percentage-change-calculator", category: "Mathematics Tools", isPro: false },
  { id: 3, name: "Fraction Calculator", slug: "fraction-calculator", category: "Mathematics Tools", isPro: false },
  { id: 4, name: "Fraction Simplifier", slug: "fraction-simplifier", category: "Mathematics Tools", isPro: false },
  { id: 5, name: "Ratio Calculator", slug: "ratio-calculator", category: "Mathematics Tools", isPro: false },
  { id: 6, name: "Proportion Calculator", slug: "proportion-calculator", category: "Mathematics Tools", isPro: false },
  { id: 7, name: "Average Calculator", slug: "average-calculator", category: "Mathematics Tools", isPro: false },
  { id: 8, name: "Standard Deviation Calculator", slug: "standard-deviation-calculator", category: "Mathematics Tools", isPro: false },
  { id: 9, name: "Probability Calculator", slug: "probability-calculator", category: "Mathematics Tools", isPro: false },
  { id: 10, name: "Permutation Calculator", slug: "permutation-calculator", category: "Mathematics Tools", isPro: false },
  { id: 11, name: "Combination Calculator", slug: "combination-calculator", category: "Mathematics Tools", isPro: false },
  { id: 12, name: "Prime Factorization Calculator", slug: "prime-factorization-calculator", category: "Mathematics Tools", isPro: false },
  { id: 13, name: "Greatest Common Factor Calculator", slug: "greatest-common-factor-calculator", category: "Mathematics Tools", isPro: false },
  { id: 14, name: "Least Common Multiple Calculator", slug: "least-common-multiple-calculator", category: "Mathematics Tools", isPro: false },
  { id: 15, name: "Exponent Calculator", slug: "exponent-calculator", category: "Mathematics Tools", isPro: false },
  { id: 16, name: "Square Root Calculator", slug: "square-root-calculator", category: "Mathematics Tools", isPro: false },
  { id: 17, name: "Equation Solver", slug: "equation-solver", category: "Mathematics Tools", isPro: false },
  { id: 18, name: "Quadratic Equation Solver", slug: "quadratic-equation-solver", category: "Mathematics Tools", isPro: false },
  { id: 19, name: "Pythagorean Theorem Calculator", slug: "pythagorean-theorem-calculator", category: "Mathematics Tools", isPro: false },
  { id: 20, name: "Function Plotter", slug: "function-plotter", category: "Mathematics Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Basic Calculator", slug: "basic-calculator", category: "Mathematics Tools", isPro: false },
  { id: 22, name: "Scientific Calculator", slug: "scientific-calculator", category: "Mathematics Tools", isPro: false },
  { id: 23, name: "Percentage Increase Calculator", slug: "percentage-increase-calculator", category: "Mathematics Tools", isPro: false },
  { id: 24, name: "Percentage Decrease Calculator", slug: "percentage-decrease-calculator", category: "Mathematics Tools", isPro: false },
  { id: 25, name: "Percentage Difference Calculator", slug: "percentage-difference-calculator", category: "Mathematics Tools", isPro: false },
  { id: 26, name: "Fraction Converter", slug: "fraction-converter", category: "Mathematics Tools", isPro: false },
  { id: 27, name: "Decimal to Fraction Converter", slug: "decimal-to-fraction-converter", category: "Mathematics Tools", isPro: false },
  { id: 28, name: "Fraction to Decimal Converter", slug: "fraction-to-decimal-converter", category: "Mathematics Tools", isPro: false },
  { id: 29, name: "Mixed Number Calculator", slug: "mixed-number-calculator", category: "Mathematics Tools", isPro: false },
  { id: 30, name: "Ratio Simplifier", slug: "ratio-simplifier", category: "Mathematics Tools", isPro: false },
  { id: 31, name: "Mean Calculator", slug: "mean-calculator", category: "Mathematics Tools", isPro: false },
  { id: 32, name: "Median Calculator", slug: "median-calculator", category: "Mathematics Tools", isPro: false },
  { id: 33, name: "Mode Calculator", slug: "mode-calculator", category: "Mathematics Tools", isPro: false },
  { id: 34, name: "Weighted Average Calculator", slug: "weighted-average-calculator", category: "Mathematics Tools", isPro: false },
  { id: 35, name: "Variance Calculator", slug: "variance-calculator", category: "Mathematics Tools", isPro: false },
  { id: 36, name: "Range Calculator", slug: "range-calculator", category: "Mathematics Tools", isPro: false },
  { id: 37, name: "Factorial Calculator", slug: "factorial-calculator", category: "Mathematics Tools", isPro: false },
  { id: 38, name: "Prime Number Checker", slug: "prime-number-checker", category: "Mathematics Tools", isPro: false },
  { id: 39, name: "Divisibility Checker", slug: "divisibility-checker", category: "Mathematics Tools", isPro: false },
  { id: 40, name: "Remainder Calculator", slug: "remainder-calculator", category: "Mathematics Tools", isPro: false },
  { id: 41, name: "Cube Root Calculator", slug: "cube-root-calculator", category: "Mathematics Tools", isPro: false },
  { id: 42, name: "Logarithm Calculator", slug: "logarithm-calculator", category: "Mathematics Tools", isPro: false },
  { id: 43, name: "Natural Log Calculator", slug: "natural-log-calculator", category: "Mathematics Tools", isPro: false },
  { id: 44, name: "Exponential Calculator", slug: "exponential-calculator", category: "Mathematics Tools", isPro: false },
  { id: 45, name: "Scientific Notation Calculator", slug: "scientific-notation-calculator", category: "Mathematics Tools", isPro: false },
  { id: 46, name: "Linear Equation Solver", slug: "linear-equation-solver", category: "Mathematics Tools", isPro: false },
  { id: 47, name: "System of Equations Solver", slug: "system-of-equations-solver", category: "Mathematics Tools", isPro: false },
  { id: 48, name: "Inequality Solver", slug: "inequality-solver", category: "Mathematics Tools", isPro: false },
  { id: 49, name: "Absolute Value Solver", slug: "absolute-value-solver", category: "Mathematics Tools", isPro: false },
  { id: 50, name: "Polynomial Calculator", slug: "polynomial-calculator", category: "Mathematics Tools", isPro: false },
  { id: 51, name: "Polynomial Factorization Tool", slug: "polynomial-factorization-tool", category: "Mathematics Tools", isPro: false },
  { id: 52, name: "Matrix Calculator", slug: "matrix-calculator", category: "Mathematics Tools", isPro: false },
  { id: 53, name: "Matrix Addition Calculator", slug: "matrix-addition-calculator", category: "Mathematics Tools", isPro: false },
  { id: 54, name: "Matrix Multiplication Calculator", slug: "matrix-multiplication-calculator", category: "Mathematics Tools", isPro: false },
  { id: 55, name: "Determinant Calculator", slug: "determinant-calculator", category: "Mathematics Tools", isPro: false },
  { id: 56, name: "Vector Calculator", slug: "vector-calculator", category: "Mathematics Tools", isPro: false },
  { id: 57, name: "Distance Formula Calculator", slug: "distance-formula-calculator", category: "Mathematics Tools", isPro: false },
  { id: 58, name: "Midpoint Calculator", slug: "midpoint-calculator", category: "Mathematics Tools", isPro: false },
  { id: 59, name: "Slope Calculator", slug: "slope-calculator", category: "Mathematics Tools", isPro: false },
  { id: 60, name: "Triangle Calculator", slug: "triangle-calculator", category: "Mathematics Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Algebra Workspace", slug: "algebra-workspace", category: "Mathematics Tools", isPro: true },
  { id: 62, name: "Equation Solving Workspace", slug: "equation-solving-workspace", category: "Mathematics Tools", isPro: true },
  { id: 63, name: "Polynomial Analysis Engine", slug: "polynomial-analysis-engine", category: "Mathematics Tools", isPro: true },
  { id: 64, name: "Calculus Calculator", slug: "calculus-calculator", category: "Mathematics Tools", isPro: true },
  { id: 65, name: "Derivative Calculator", slug: "derivative-calculator", category: "Mathematics Tools", isPro: true },
  { id: 66, name: "Integral Calculator", slug: "integral-calculator", category: "Mathematics Tools", isPro: true },
  { id: 67, name: "Limit Calculator", slug: "limit-calculator", category: "Mathematics Tools", isPro: true },
  { id: 68, name: "Series Calculator", slug: "series-calculator", category: "Mathematics Tools", isPro: true },
  { id: 69, name: "Taylor Series Calculator", slug: "taylor-series-calculator", category: "Mathematics Tools", isPro: true },
  { id: 70, name: "Differential Equation Solver", slug: "differential-equation-solver", category: "Mathematics Tools", isPro: true },
  { id: 71, name: "Linear Algebra Workspace", slug: "linear-algebra-workspace", category: "Mathematics Tools", isPro: true },
  { id: 72, name: "Matrix Analysis Engine", slug: "matrix-analysis-engine", category: "Mathematics Tools", isPro: true },
  { id: 73, name: "Vector Analysis Workspace", slug: "vector-analysis-workspace", category: "Mathematics Tools", isPro: true },
  { id: 74, name: "Geometry Workspace", slug: "geometry-workspace", category: "Mathematics Tools", isPro: true },
  { id: 75, name: "Coordinate Geometry Engine", slug: "coordinate-geometry-engine", category: "Mathematics Tools", isPro: true },
  { id: 76, name: "Trigonometry Solver", slug: "trigonometry-solver", category: "Mathematics Tools", isPro: true },
  { id: 77, name: "Trigonometric Identity Checker", slug: "trigonometric-identity-checker", category: "Mathematics Tools", isPro: true },
  { id: 78, name: "Statistics Analysis Workspace", slug: "statistics-analysis-workspace", category: "Mathematics Tools", isPro: true },
  { id: 79, name: "Probability Analysis Workspace", slug: "probability-analysis-workspace", category: "Mathematics Tools", isPro: true },
  { id: 80, name: "Distribution Calculator", slug: "distribution-calculator", category: "Mathematics Tools", isPro: true },
  { id: 81, name: "Normal Distribution Calculator", slug: "normal-distribution-calculator", category: "Mathematics Tools", isPro: true },
  { id: 82, name: "Binomial Distribution Calculator", slug: "binomial-distribution-calculator", category: "Mathematics Tools", isPro: true },
  { id: 83, name: "Poisson Distribution Calculator", slug: "poisson-distribution-calculator", category: "Mathematics Tools", isPro: true },
  { id: 84, name: "Regression Calculator", slug: "regression-calculator", category: "Mathematics Tools", isPro: true },
  { id: 85, name: "Correlation Calculator", slug: "correlation-calculator", category: "Mathematics Tools", isPro: true },
  { id: 86, name: "Hypothesis Testing Calculator", slug: "hypothesis-testing-calculator", category: "Mathematics Tools", isPro: true },
  { id: 87, name: "Confidence Interval Calculator", slug: "confidence-interval-calculator", category: "Mathematics Tools", isPro: true },
  { id: 88, name: "Z-Score Calculator", slug: "z-score-calculator", category: "Mathematics Tools", isPro: true },
  { id: 89, name: "T-Score Calculator", slug: "t-score-calculator", category: "Mathematics Tools", isPro: true },
  { id: 90, name: "ANOVA Calculator", slug: "anova-calculator", category: "Mathematics Tools", isPro: true },
  { id: 91, name: "Data Statistics Dashboard", slug: "data-statistics-dashboard", category: "Mathematics Tools", isPro: true },
  { id: 92, name: "Mathematical Graphing Workspace", slug: "mathematical-graphing-workspace", category: "Mathematics Tools", isPro: true },
  { id: 93, name: "Equation Graphing Engine", slug: "equation-graphing-engine", category: "Mathematics Tools", isPro: true },
  { id: 94, name: "Mathematical Optimization Solver", slug: "mathematical-optimization-solver", category: "Mathematics Tools", isPro: true },
  { id: 95, name: "Numerical Methods Workspace", slug: "numerical-methods-workspace", category: "Mathematics Tools", isPro: true },
  { id: 96, name: "Math Problem Verification Tool", slug: "math-problem-verification-tool", category: "Mathematics Tools", isPro: true },
  { id: 97, name: "Mathematics Research Workspace", slug: "mathematics-research-workspace", category: "Mathematics Tools", isPro: true },
  { id: 98, name: "Advanced Mathematics Intelligence Platform", slug: "advanced-mathematics-intelligence-platform", category: "Mathematics Tools", isPro: true },
  { id: 99, name: "Professional Mathematics Workspace", slug: "professional-mathematics-workspace", category: "Mathematics Tools", isPro: true },
  { id: 100, name: "Circle Calculator", slug: "circle-calculator", category: "Mathematics Tools", isPro: true }
];