export interface NetworkTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const networkToolsList: NetworkTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "IP Address Lookup", slug: "ip-address-lookup", category: "Network & Internet Tools", isPro: false },
  { id: 2, name: "IP Range Calculator", slug: "ip-range-calculator", category: "Network & Internet Tools", isPro: false },
  { id: 3, name: "CIDR Calculator", slug: "cidr-calculator", category: "Network & Internet Tools", isPro: false },
  { id: 4, name: "Subnet Calculator", slug: "subnet-calculator", category: "Network & Internet Tools", isPro: false },
  { id: 5, name: "DNS Lookup", slug: "dns-lookup", category: "Network & Internet Tools", isPro: false },
  { id: 6, name: "DNS Record Checker", slug: "dns-record-checker", category: "Network & Internet Tools", isPro: false },
  { id: 7, name: "DNS Propagation Checker", slug: "dns-propagation-checker", category: "Network & Internet Tools", isPro: false },
  { id: 8, name: "Reverse DNS Lookup", slug: "reverse-dns-lookup", category: "Network & Internet Tools", isPro: false },
  { id: 9, name: "WHOIS Lookup", slug: "whois-lookup", category: "Network & Internet Tools", isPro: false },
  { id: 10, name: "Domain Availability Checker", slug: "domain-availability-checker", category: "Network & Internet Tools", isPro: false },
  { id: 11, name: "Domain Expiration Checker", slug: "domain-expiration-checker", category: "Network & Internet Tools", isPro: false },
  { id: 12, name: "HTTP Status Checker", slug: "http-status-checker", category: "Network & Internet Tools", isPro: false },
  { id: 13, name: "Redirect Checker", slug: "redirect-checker-network", category: "Network & Internet Tools", isPro: false },
  { id: 14, name: "Website Response Time Checker", slug: "website-response-time-checker", category: "Network & Internet Tools", isPro: false },
  { id: 15, name: "Ping Tester", slug: "ping-tester", category: "Network & Internet Tools", isPro: false },
  { id: 16, name: "TCP Port Checker", slug: "tcp-port-checker", category: "Network & Internet Tools", isPro: false },
  { id: 17, name: "Traceroute Tool", slug: "traceroute-tool", category: "Network & Internet Tools", isPro: false },
  { id: 18, name: "Packet Loss Tester", slug: "packet-loss-tester", category: "Network & Internet Tools", isPro: false },
  { id: 19, name: "Bandwidth Calculator", slug: "bandwidth-calculator-network", category: "Network & Internet Tools", isPro: false },
  { id: 20, name: "CDN Performance Analyzer", slug: "cdn-performance-analyzer", category: "Network & Internet Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "IP Address Checker", slug: "ip-address-checker", category: "Network & Internet Tools", isPro: false },
  { id: 22, name: "IPv4 Validator", slug: "ipv4-validator", category: "Network & Internet Tools", isPro: false },
  { id: 23, name: "IPv6 Validator", slug: "ipv6-validator", category: "Network & Internet Tools", isPro: false },
  { id: 24, name: "Subnet Mask Calculator", slug: "subnet-mask-calculator", category: "Network & Internet Tools", isPro: false },
  { id: 25, name: "Network Address Calculator", slug: "network-address-calculator", category: "Network & Internet Tools", isPro: false },
  { id: 26, name: "Broadcast Address Calculator", slug: "broadcast-address-calculator", category: "Network & Internet Tools", isPro: false },
  { id: 27, name: "Usable IP Calculator", slug: "usable-ip-calculator", category: "Network & Internet Tools", isPro: false },
  { id: 28, name: "Wildcard Mask Calculator", slug: "wildcard-mask-calculator", category: "Network & Internet Tools", isPro: false },
  { id: 29, name: "IP Range Converter", slug: "ip-range-converter", category: "Network & Internet Tools", isPro: false },
  { id: 30, name: "CIDR to IP Range Converter", slug: "cidr-to-ip-range-converter", category: "Network & Internet Tools", isPro: false },
  { id: 31, name: "IP to Binary Converter", slug: "ip-to-binary-converter", category: "Network & Internet Tools", isPro: false },
  { id: 32, name: "A Record Lookup", slug: "a-record-lookup", category: "Network & Internet Tools", isPro: false },
  { id: 33, name: "AAAA Record Lookup", slug: "aaaa-record-lookup", category: "Network & Internet Tools", isPro: false },
  { id: 34, name: "CNAME Lookup", slug: "cname-lookup", category: "Network & Internet Tools", isPro: false },
  { id: 35, name: "MX Record Lookup", slug: "mx-record-lookup", category: "Network & Internet Tools", isPro: false },
  { id: 36, name: "TXT Record Lookup", slug: "txt-record-lookup", category: "Network & Internet Tools", isPro: false },
  { id: 37, name: "NS Record Lookup", slug: "ns-record-lookup", category: "Network & Internet Tools", isPro: false },
  { id: 38, name: "SOA Record Lookup", slug: "soa-record-lookup", category: "Network & Internet Tools", isPro: false },
  { id: 39, name: "PTR Lookup", slug: "ptr-lookup", category: "Network & Internet Tools", isPro: false },
  { id: 40, name: "DNS Resolver Checker", slug: "dns-resolver-checker", category: "Network & Internet Tools", isPro: false },
  { id: 41, name: "Domain IP Lookup", slug: "domain-ip-lookup", category: "Network & Internet Tools", isPro: false },
  { id: 42, name: "Domain Nameserver Checker", slug: "domain-nameserver-checker", category: "Network & Internet Tools", isPro: false },
  { id: 43, name: "Domain Age Checker", slug: "domain-age-checker", category: "Network & Internet Tools", isPro: false },
  { id: 44, name: "Domain Redirect Checker", slug: "domain-redirect-checker", category: "Network & Internet Tools", isPro: false },
  { id: 45, name: "HTTP Header Viewer", slug: "http-header-viewer", category: "Network & Internet Tools", isPro: false },
  { id: 46, name: "URL Status Checker", slug: "url-status-checker", category: "Network & Internet Tools", isPro: false },
  { id: 47, name: "Website Ping Tester", slug: "website-ping-tester", category: "Network & Internet Tools", isPro: false },
  { id: 48, name: "UDP Port Checker", slug: "udp-port-checker", category: "Network & Internet Tools", isPro: false },
  { id: 49, name: "Port Range Checker", slug: "port-range-checker", category: "Network & Internet Tools", isPro: false },
  { id: 50, name: "Ping Latency Tester", slug: "ping-latency-tester", category: "Network & Internet Tools", isPro: false },
  { id: 51, name: "DNS Latency Tester", slug: "dns-latency-tester", category: "Network & Internet Tools", isPro: false },
  { id: 52, name: "Network Speed Calculator", slug: "network-speed-calculator", category: "Network & Internet Tools", isPro: false },
  { id: 53, name: "Download Speed Calculator", slug: "download-speed-calculator", category: "Network & Internet Tools", isPro: false },
  { id: 54, name: "Upload Speed Calculator", slug: "upload-speed-calculator", category: "Network & Internet Tools", isPro: false },
  { id: 55, name: "Data Transfer Calculator", slug: "data-transfer-calculator", category: "Network & Internet Tools", isPro: false },
  { id: 56, name: "Download Time Calculator", slug: "download-time-calculator", category: "Network & Internet Tools", isPro: false },
  { id: 57, name: "Upload Time Calculator", slug: "upload-time-calculator", category: "Network & Internet Tools", isPro: false },
  { id: 58, name: "Internet Data Usage Calculator", slug: "internet-data-usage-calculator", category: "Network & Internet Tools", isPro: false },
  { id: 59, name: "Domain Name Encoder", slug: "domain-name-encoder", category: "Network & Internet Tools", isPro: false },
  { id: 60, name: "Query String Builder", slug: "query-string-builder", category: "Network & Internet Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Network Diagnostic Suite", slug: "network-diagnostic-suite", category: "Network & Internet Tools", isPro: true },
  { id: 62, name: "Website Performance Network Analyzer", slug: "website-performance-network-analyzer", category: "Network & Internet Tools", isPro: true },
  { id: 63, name: "Multi-Location Ping Monitor", slug: "multi-location-ping-monitor", category: "Network & Internet Tools", isPro: true },
  { id: 64, name: "Global Latency Monitor", slug: "global-latency-monitor", category: "Network & Internet Tools", isPro: true },
  { id: 65, name: "DNS Monitoring Dashboard", slug: "dns-monitoring-dashboard", category: "Network & Internet Tools", isPro: true },
  { id: 66, name: "DNS Change Monitor", slug: "dns-change-monitor", category: "Network & Internet Tools", isPro: true },
  { id: 67, name: "Domain Monitoring Dashboard", slug: "domain-monitoring-dashboard", category: "Network & Internet Tools", isPro: true },
  { id: 68, name: "SSL Certificate Monitor", slug: "ssl-certificate-monitor-network", category: "Network & Internet Tools", isPro: true },
  { id: 69, name: "HTTP Uptime Monitor", slug: "http-uptime-monitor", category: "Network & Internet Tools", isPro: true },
  { id: 70, name: "TCP Service Monitor", slug: "tcp-service-monitor", category: "Network & Internet Tools", isPro: true },
  { id: 71, name: "Port Monitoring Dashboard", slug: "port-monitoring-dashboard", category: "Network & Internet Tools", isPro: true },
  { id: 72, name: "Network Availability Monitor", slug: "network-availability-monitor", category: "Network & Internet Tools", isPro: true },
  { id: 73, name: "Packet Loss Analyzer", slug: "packet-loss-analyzer", category: "Network & Internet Tools", isPro: true },
  { id: 74, name: "Network Route Analyzer", slug: "network-route-analyzer", category: "Network & Internet Tools", isPro: true },
  { id: 75, name: "Traceroute Comparison Tool", slug: "traceroute-comparison-tool", category: "Network & Internet Tools", isPro: true },
  { id: 76, name: "CDN Location Tester", slug: "cdn-location-tester", category: "Network & Internet Tools", isPro: true },
  { id: 77, name: "Edge Latency Analyzer", slug: "edge-latency-analyzer", category: "Network & Internet Tools", isPro: true },
  { id: 78, name: "Website TTFB Analyzer", slug: "website-ttfb-analyzer", category: "Network & Internet Tools", isPro: true },
  { id: 79, name: "Network Request Analyzer", slug: "network-request-analyzer", category: "Network & Internet Tools", isPro: true },
  { id: 80, name: "HTTP Connection Analyzer", slug: "http-connection-analyzer", category: "Network & Internet Tools", isPro: true },
  { id: 81, name: "HTTP/2 Analyzer", slug: "http2-analyzer", category: "Network & Internet Tools", isPro: true },
  { id: 82, name: "HTTP/3 Analyzer", slug: "http3-analyzer", category: "Network & Internet Tools", isPro: true },
  { id: 83, name: "IPv4/IPv6 Compatibility Tester", slug: "ipv4-ipv6-compatibility-tester", category: "Network & Internet Tools", isPro: true },
  { id: 84, name: "Dual-Stack Analyzer", slug: "dual-stack-analyzer", category: "Network & Internet Tools", isPro: true },
  { id: 85, name: "DNSSEC Validation Tester", slug: "dnssec-validation-tester", category: "Network & Internet Tools", isPro: true },
  { id: 86, name: "Email DNS Configuration Analyzer", slug: "email-dns-configuration-analyzer", category: "Network & Internet Tools", isPro: true },
  { id: 87, name: "Domain Infrastructure Mapper", slug: "domain-infrastructure-mapper", category: "Network & Internet Tools", isPro: true },
  { id: 88, name: "Network Dependency Mapper", slug: "network-dependency-mapper", category: "Network & Internet Tools", isPro: true },
  { id: 89, name: "Service Dependency Monitor", slug: "service-dependency-monitor", category: "Network & Internet Tools", isPro: true },
  { id: 90, name: "Network Capacity Planner", slug: "network-capacity-planner", category: "Network & Internet Tools", isPro: true },
  { id: 91, name: "Bandwidth Capacity Planner", slug: "bandwidth-capacity-planner", category: "Network & Internet Tools", isPro: true },
  { id: 92, name: "Traffic Forecast Calculator", slug: "traffic-forecast-calculator", category: "Network & Internet Tools", isPro: true },
  { id: 93, name: "Network Cost Calculator", slug: "network-cost-calculator", category: "Network & Internet Tools", isPro: true },
  { id: 94, name: "CDN Cost Estimator", slug: "cdn-cost-estimator", category: "Network & Internet Tools", isPro: true },
  { id: 95, name: "Data Transfer Cost Calculator", slug: "data-transfer-cost-calculator", category: "Network & Internet Tools", isPro: true },
  { id: 96, name: "Network Health Dashboard", slug: "network-health-dashboard", category: "Network & Internet Tools", isPro: true },
  { id: 97, name: "Internet Infrastructure Monitor", slug: "internet-infrastructure-monitor", category: "Network & Internet Tools", isPro: true },
  { id: 98, name: "Global Network Intelligence Workspace", slug: "global-network-intelligence-workspace", category: "Network & Internet Tools", isPro: true },
  { id: 99, name: "Network Operations Workspace", slug: "network-operations-workspace", category: "Network & Internet Tools", isPro: true },
  { id: 100, name: "URL Encoder Decoder Suite", slug: "url-encoder-decoder-suite", category: "Network & Internet Tools", isPro: true },
];