export interface NoCodeAutomationTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const noCodeAutomationToolsList: NoCodeAutomationTool[] = [
  // --- 🔥 PRIORITY 20 FREE TOOLS (IDs 1-20 | isPro: false) ---
  { id: 1, name: "Workflow Builder", slug: "workflow-builder", category: "No-Code & Automation Tools", isPro: false },
  { id: 2, name: "Workflow Diagram Generator", slug: "workflow-diagram-generator", category: "No-Code & Automation Tools", isPro: false },
  { id: 3, name: "Conditional Logic Builder", slug: "conditional-logic-builder", category: "No-Code & Automation Tools", isPro: false },
  { id: 4, name: "Automation Rule Generator", slug: "automation-rule-generator", category: "No-Code & Automation Tools", isPro: false },
  { id: 5, name: "Approval Workflow Builder", slug: "approval-workflow-builder", category: "No-Code & Automation Tools", isPro: false },
  { id: 6, name: "Lead Routing Builder", slug: "lead-routing-builder", category: "No-Code & Automation Tools", isPro: false },
  { id: 7, name: "Data Mapping Tool", slug: "data-mapping-tool", category: "No-Code & Automation Tools", isPro: false },
  { id: 8, name: "Webhook Builder", slug: "webhook-builder", category: "No-Code & Automation Tools", isPro: false },
  { id: 9, name: "Webhook Tester", slug: "webhook-tester", category: "No-Code & Automation Tools", isPro: false },
  { id: 10, name: "HTTP Request Builder", slug: "http-request-builder", category: "No-Code & Automation Tools", isPro: false },
  { id: 11, name: "API Workflow Builder", slug: "api-workflow-builder", category: "No-Code & Automation Tools", isPro: false },
  { id: 12, name: "Scheduled Workflow Builder", slug: "scheduled-workflow-builder", category: "No-Code & Automation Tools", isPro: false },
  { id: 13, name: "Multi-Step Workflow Builder", slug: "multi-step-workflow-builder", category: "No-Code & Automation Tools", isPro: false },
  { id: 14, name: "Business Process Mapper", slug: "business-process-mapper", category: "No-Code & Automation Tools", isPro: false },
  { id: 15, name: "Process Bottleneck Finder", slug: "process-bottleneck-finder", category: "No-Code & Automation Tools", isPro: false },
  { id: 16, name: "Automation ROI Calculator", slug: "automation-roi-calculator", category: "No-Code & Automation Tools", isPro: false },
  { id: 17, name: "Automation Savings Calculator", slug: "automation-savings-calculator", category: "No-Code & Automation Tools", isPro: false },
  { id: 18, name: "Task Routing Builder", slug: "task-routing-builder", category: "No-Code & Automation Tools", isPro: false },
  { id: 19, name: "Workflow Dependency Mapper", slug: "workflow-dependency-mapper", category: "No-Code & Automation Tools", isPro: false },
  { id: 20, name: "Data Sync Planner", slug: "data-sync-planner", category: "No-Code & Automation Tools", isPro: false },

  // --- REMAINING 40 CORE FREE TOOLS (IDs 21-60 | isPro: false) ---
  { id: 21, name: "Workflow Step Builder", slug: "workflow-step-builder", category: "No-Code & Automation Tools", isPro: false },
  { id: 22, name: "Workflow Trigger Builder", slug: "workflow-trigger-builder", category: "No-Code & Automation Tools", isPro: false },
  { id: 23, name: "Workflow Action Builder", slug: "workflow-action-builder", category: "No-Code & Automation Tools", isPro: false },
  { id: 24, name: "If-Then Rule Builder", slug: "if-then-rule-builder", category: "No-Code & Automation Tools", isPro: false },
  { id: 25, name: "Automation Flowchart Generator", slug: "automation-flowchart-generator", category: "No-Code & Automation Tools", isPro: false },
  { id: 26, name: "Process Flow Generator", slug: "process-flow-generator", category: "No-Code & Automation Tools", isPro: false },
  { id: 27, name: "Form-to-Workflow Builder", slug: "form-to-workflow-builder", category: "No-Code & Automation Tools", isPro: false },
  { id: 28, name: "Form Workflow Generator", slug: "form-workflow-generator", category: "No-Code & Automation Tools", isPro: false },
  { id: 29, name: "Notification Workflow Builder", slug: "notification-workflow-builder", category: "No-Code & Automation Tools", isPro: false },
  { id: 30, name: "Email Workflow Builder", slug: "email-workflow-builder", category: "No-Code & Automation Tools", isPro: false },
  { id: 31, name: "Field Mapping Generator", slug: "field-mapping-generator", category: "No-Code & Automation Tools", isPro: false },
  { id: 32, name: "CSV Field Mapper", slug: "csv-field-mapper", category: "No-Code & Automation Tools", isPro: false },
  { id: 33, name: "API Field Mapper", slug: "api-field-mapper", category: "No-Code & Automation Tools", isPro: false },
  { id: 34, name: "Webhook Payload Builder", slug: "webhook-payload-builder", category: "No-Code & Automation Tools", isPro: false },
  { id: 35, name: "API Trigger Builder", slug: "api-trigger-builder", category: "No-Code & Automation Tools", isPro: false },
  { id: 36, name: "Recurring Workflow Builder", slug: "recurring-workflow-builder", category: "No-Code & Automation Tools", isPro: false },
  { id: 37, name: "Delay Workflow Builder", slug: "delay-workflow-builder", category: "No-Code & Automation Tools", isPro: false },
  { id: 38, name: "Retry Logic Builder", slug: "retry-logic-builder", category: "No-Code & Automation Tools", isPro: false },
  { id: 39, name: "Error Handling Flow Builder", slug: "error-handling-flow-builder", category: "No-Code & Automation Tools", isPro: false },
  { id: 40, name: "Approval Chain Builder", slug: "approval-chain-builder", category: "No-Code & Automation Tools", isPro: false },
  { id: 41, name: "Automation Checklist Generator", slug: "automation-checklist-generator", category: "No-Code & Automation Tools", isPro: false },
  { id: 42, name: "Automation Process Planner", slug: "automation-process-planner", category: "No-Code & Automation Tools", isPro: false },
  { id: 43, name: "Process Time Calculator", slug: "process-time-calculator", category: "No-Code & Automation Tools", isPro: false },
  { id: 44, name: "Manual Task Cost Calculator", slug: "manual-task-cost-calculator", category: "No-Code & Automation Tools", isPro: false },
  { id: 45, name: "Workflow Cost Calculator", slug: "workflow-cost-calculator", category: "No-Code & Automation Tools", isPro: false },
  { id: 46, name: "Task Automation Calculator", slug: "task-automation-calculator", category: "No-Code & Automation Tools", isPro: false },
  { id: 47, name: "Integration Requirement Planner", slug: "integration-requirement-planner", category: "No-Code & Automation Tools", isPro: false },
  { id: 48, name: "Integration Checklist", slug: "integration-checklist", category: "No-Code & Automation Tools", isPro: false },
  { id: 49, name: "App Integration Mapper", slug: "app-integration-mapper", category: "No-Code & Automation Tools", isPro: false },
  { id: 50, name: "Integration Dependency Mapper", slug: "integration-dependency-mapper", category: "No-Code & Automation Tools", isPro: false },
  { id: 51, name: "Automation Documentation Generator", slug: "automation-documentation-generator", category: "No-Code & Automation Tools", isPro: false },
  { id: 52, name: "Workflow Documentation Generator", slug: "workflow-documentation-generator", category: "No-Code & Automation Tools", isPro: false },
  { id: 53, name: "SOP-to-Workflow Builder", slug: "sop-to-workflow-builder", category: "No-Code & Automation Tools", isPro: false },
  { id: 54, name: "Process-to-Automation Planner", slug: "process-to-automation-planner", category: "No-Code & Automation Tools", isPro: false },
  { id: 55, name: "Automation Testing Checklist", slug: "automation-testing-checklist", category: "No-Code & Automation Tools", isPro: false },
  { id: 56, name: "Workflow Testing Checklist", slug: "workflow-testing-checklist", category: "No-Code & Automation Tools", isPro: false },
  { id: 57, name: "Automation Error Log", slug: "automation-error-log", category: "No-Code & Automation Tools", isPro: false },
  { id: 58, name: "Workflow Run Log", slug: "workflow-run-log", category: "No-Code & Automation Tools", isPro: false },
  { id: 59, name: "Automation Change Log", slug: "automation-change-log", category: "No-Code & Automation Tools", isPro: false },
  { id: 60, name: "Automation Report Generator", slug: "automation-report-generator", category: "No-Code & Automation Tools", isPro: false },

  // --- ⚡ 40 PRO / SAAS TOOLS (IDs 61-100 | isPro: true) ---
  { id: 61, name: "No-Code Automation Workspace", slug: "no-code-automation-workspace", category: "No-Code & Automation Tools", isPro: true },
  { id: 62, name: "Workflow Monitoring Dashboard", slug: "workflow-monitoring-dashboard", category: "No-Code & Automation Tools", isPro: true },
  { id: 63, name: "Business Process Automation Workspace", slug: "business-process-automation-workspace", category: "No-Code & Automation Tools", isPro: true },
  { id: 64, name: "Visual Workflow Builder", slug: "visual-workflow-builder", category: "No-Code & Automation Tools", isPro: true },
  { id: 65, name: "Enterprise Workflow Builder", slug: "enterprise-workflow-builder", category: "No-Code & Automation Tools", isPro: true },
  { id: 66, name: "Multi-App Integration Workspace", slug: "multi-app-integration-workspace", category: "No-Code & Automation Tools", isPro: true },
  { id: 67, name: "Workflow Orchestration Engine", slug: "workflow-orchestration-engine", category: "No-Code & Automation Tools", isPro: true },
  { id: 68, name: "Workflow Automation Engine", slug: "workflow-automation-engine", category: "No-Code & Automation Tools", isPro: true },
  { id: 69, name: "Approval Automation Platform", slug: "approval-automation-platform", category: "No-Code & Automation Tools", isPro: true },
  { id: 70, name: "Lead Routing Automation", slug: "lead-routing-automation", category: "No-Code & Automation Tools", isPro: true },
  { id: 71, name: "Task Routing Automation", slug: "task-routing-automation", category: "No-Code & Automation Tools", isPro: true },
  { id: 72, name: "Data Synchronization Engine", slug: "data-synchronization-engine", category: "No-Code & Automation Tools", isPro: true },
  { id: 73, name: "Data Mapping Workspace", slug: "data-mapping-workspace", category: "No-Code & Automation Tools", isPro: true },
  { id: 74, name: "API Integration Workspace", slug: "api-integration-workspace", category: "No-Code & Automation Tools", isPro: true },
  { id: 75, name: "Webhook Management Workspace", slug: "webhook-management-workspace", category: "No-Code & Automation Tools", isPro: true },
  { id: 76, name: "Integration Monitoring Dashboard", slug: "integration-monitoring-dashboard", category: "No-Code & Automation Tools", isPro: true },
  { id: 77, name: "Automation Run Dashboard", slug: "automation-run-dashboard", category: "No-Code & Automation Tools", isPro: true },
  { id: 78, name: "Automation Error Management", slug: "automation-error-management", category: "No-Code & Automation Tools", isPro: true },
  { id: 79, name: "Workflow Retry Management", slug: "workflow-retry-management", category: "No-Code & Automation Tools", isPro: true },
  { id: 80, name: "Automation Testing Workspace", slug: "automation-testing-workspace", category: "No-Code & Automation Tools", isPro: true },
  { id: 81, name: "Workflow Version Control", slug: "workflow-version-control", category: "No-Code & Automation Tools", isPro: true },
  { id: 82, name: "Workflow Change Management", slug: "workflow-change-management", category: "No-Code & Automation Tools", isPro: true },
  { id: 83, name: "Automation Audit Dashboard", slug: "automation-audit-dashboard", category: "No-Code & Automation Tools", isPro: true },
  { id: 84, name: "Automation ROI Dashboard", slug: "automation-roi-dashboard", category: "No-Code & Automation Tools", isPro: true },
  { id: 85, name: "Automation Savings Dashboard", slug: "automation-savings-dashboard", category: "No-Code & Automation Tools", isPro: true },
  { id: 86, name: "Process Bottleneck Analytics", slug: "process-bottleneck-analytics", category: "No-Code & Automation Tools", isPro: true },
  { id: 87, name: "Business Process Intelligence", slug: "business-process-intelligence", category: "No-Code & Automation Tools", isPro: true },
  { id: 88, name: "Workflow Analytics Workspace", slug: "workflow-analytics-workspace", category: "No-Code & Automation Tools", isPro: true },
  { id: 89, name: "Integration Health Dashboard", slug: "integration-health-dashboard", category: "No-Code & Automation Tools", isPro: true },
  { id: 90, name: "API Workflow Monitoring", slug: "api-workflow-monitoring", category: "No-Code & Automation Tools", isPro: true },
  { id: 91, name: "Multi-Step Automation Workspace", slug: "multi-step-automation-workspace", category: "No-Code & Automation Tools", isPro: true },
  { id: 92, name: "Enterprise Approval Management", slug: "enterprise-approval-management", category: "No-Code & Automation Tools", isPro: true },
  { id: 93, name: "Automation Documentation Workspace", slug: "automation-documentation-workspace", category: "No-Code & Automation Tools", isPro: true },
  { id: 94, name: "Workflow Template Marketplace", slug: "workflow-template-marketplace", category: "No-Code & Automation Tools", isPro: true },
  { id: 95, name: "Integration Template Workspace", slug: "integration-template-workspace", category: "No-Code & Automation Tools", isPro: true },
  { id: 96, name: "Automation Data Importer", slug: "automation-data-importer", category: "No-Code & Automation Tools", isPro: true },
  { id: 97, name: "Automation Data Exporter", slug: "automation-data-exporter", category: "No-Code & Automation Tools", isPro: true },
  { id: 98, name: "Automation API Platform", slug: "automation-api-platform", category: "No-Code & Automation Tools", isPro: true },
  { id: 99, name: "Business Automation Intelligence Platform", slug: "business-automation-intelligence-platform", category: "No-Code & Automation Tools", isPro: true },
  { id: 100, name: "Enterprise Automation Command Center", slug: "enterprise-automation-command-center", category: "No-Code & Automation Tools", isPro: true }
];