export interface PDFTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const pdfToolsList: PDFTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-30) ---
  { id: 1, name: "PDF Merger", slug: "pdf-merger", category: "PDF Tools", isPro: false },
  { id: 2, name: "PDF Splitter", slug: "pdf-splitter", category: "PDF Tools", isPro: false },
  { id: 3, name: "PDF Compressor", slug: "pdf-compressor", category: "PDF Tools", isPro: false },
  { id: 4, name: "PDF to Word", slug: "pdf-to-word", category: "PDF Tools", isPro: false },
  { id: 5, name: "Word to PDF", slug: "word-to-pdf", category: "PDF Tools", isPro: false },
  { id: 6, name: "PDF to Excel", slug: "pdf-to-excel", category: "PDF Tools", isPro: false },
  { id: 7, name: "Excel to PDF", slug: "excel-to-pdf", category: "PDF Tools", isPro: false },
  { id: 8, name: "PDF to JPG", slug: "pdf-to-jpg", category: "PDF Tools", isPro: false },
  { id: 9, name: "JPG to PDF", slug: "jpg-to-pdf", category: "PDF Tools", isPro: false },
  { id: 10, name: "PDF to PNG", slug: "pdf-to-png", category: "PDF Tools", isPro: false },
  { id: 11, name: "PDF to Text", slug: "pdf-to-text", category: "PDF Tools", isPro: false },
  { id: 12, name: "PDF Page Extractor", slug: "pdf-page-extractor", category: "PDF Tools", isPro: false },
  { id: 13, name: "PDF Page Deleter", slug: "pdf-page-deleter", category: "PDF Tools", isPro: false },
  { id: 14, name: "PDF Page Reorderer", slug: "pdf-page-reorderer", category: "PDF Tools", isPro: false },
  { id: 15, name: "PDF Rotator", slug: "pdf-rotator", category: "PDF Tools", isPro: false },
  { id: 16, name: "PDF Password Protector", slug: "pdf-password-protector", category: "PDF Tools", isPro: false },
  { id: 17, name: "PDF Password Remover", slug: "pdf-password-remover", category: "PDF Tools", isPro: false },
  { id: 18, name: "PDF Watermark Tool", slug: "pdf-watermark-tool", category: "PDF Tools", isPro: false },
  { id: 19, name: "PDF Text Extractor", slug: "pdf-text-extractor", category: "PDF Tools", isPro: false },
  { id: 20, name: "PDF Metadata Remover", slug: "pdf-metadata-remover", category: "PDF Tools", isPro: false },
  { id: 21, name: "OCR PDF Converter", slug: "ocr-pdf-converter", category: "PDF Tools", isPro: false },
  { id: 22, name: "Scanned PDF OCR", slug: "scanned-pdf-ocr", category: "PDF Tools", isPro: false },
  { id: 23, name: "Searchable PDF Creator", slug: "searchable-pdf-creator", category: "PDF Tools", isPro: false },
  { id: 24, name: "PDF Form Filler", slug: "pdf-form-filler", category: "PDF Tools", isPro: false },
  { id: 25, name: "PDF Form Creator", slug: "pdf-form-creator", category: "PDF Tools", isPro: false },
  { id: 26, name: "PDF Signature Tool", slug: "pdf-signature-tool", category: "PDF Tools", isPro: false },
  { id: 27, name: "Digital Signature Validator", slug: "digital-signature-validator", category: "PDF Tools", isPro: false },
  { id: 28, name: "PDF Redaction Tool", slug: "pdf-redaction-tool", category: "PDF Tools", isPro: false },
  { id: 29, name: "PII Detection in PDF", slug: "pii-detection-in-pdf", category: "PDF Tools", isPro: false },
  { id: 30, name: "PDF Accessibility Checker", slug: "pdf-accessibility-checker", category: "PDF Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (31-60) ---
  { id: 31, name: "PDF Converter", slug: "pdf-converter", category: "PDF Tools", isPro: false },
  { id: 32, name: "PDF to PowerPoint", slug: "pdf-to-powerpoint", category: "PDF Tools", isPro: false },
  { id: 33, name: "PowerPoint to PDF", slug: "powerpoint-to-pdf", category: "PDF Tools", isPro: false },
  { id: 34, name: "PNG to PDF", slug: "png-to-pdf", category: "PDF Tools", isPro: false },
  { id: 35, name: "Text to PDF", slug: "text-to-pdf", category: "PDF Tools", isPro: false },
  { id: 36, name: "HTML to PDF", slug: "html-to-pdf", category: "PDF Tools", isPro: false },
  { id: 37, name: "PDF Page Duplicator", slug: "pdf-page-duplicator", category: "PDF Tools", isPro: false },
  { id: 38, name: "PDF Page Inserter", slug: "pdf-page-inserter", category: "PDF Tools", isPro: false },
  { id: 39, name: "PDF Page Replacer", slug: "pdf-page-replacer", category: "PDF Tools", isPro: false },
  { id: 40, name: "PDF Unlocker", slug: "pdf-unlocker", category: "PDF Tools", isPro: false },
  { id: 41, name: "PDF Encryption Tool", slug: "pdf-encryption-tool", category: "PDF Tools", isPro: false },
  { id: 42, name: "PDF Decryption Tool", slug: "pdf-decryption-tool", category: "PDF Tools", isPro: false },
  { id: 43, name: "PDF Text Watermark Tool", slug: "pdf-text-watermark-tool", category: "PDF Tools", isPro: false },
  { id: 44, name: "PDF Image Watermark Tool", slug: "pdf-image-watermark-tool", category: "PDF Tools", isPro: false },
  { id: 45, name: "PDF Stamp Tool", slug: "pdf-stamp-tool", category: "PDF Tools", isPro: false },
  { id: 46, name: "PDF Header Footer Tool", slug: "pdf-header-footer-tool", category: "PDF Tools", isPro: false },
  { id: 47, name: "PDF Cropper", slug: "pdf-cropper", category: "PDF Tools", isPro: false },
  { id: 48, name: "PDF Resizer", slug: "pdf-resizer", category: "PDF Tools", isPro: false },
  { id: 49, name: "PDF Viewer", slug: "pdf-viewer", category: "PDF Tools", isPro: false },
  { id: 50, name: "PDF Printer", slug: "pdf-printer", category: "PDF Tools", isPro: false },
  { id: 51, name: "PDF Metadata Viewer", slug: "pdf-metadata-viewer", category: "PDF Tools", isPro: false },
  { id: 52, name: "PDF Metadata Editor", slug: "pdf-metadata-editor", category: "PDF Tools", isPro: false },
  { id: 53, name: "PDF Image Extractor", slug: "pdf-image-extractor", category: "PDF Tools", isPro: false },
  { id: 54, name: "PDF Attachment Extractor", slug: "pdf-attachment-extractor", category: "PDF Tools", isPro: false },
  { id: 55, name: "PDF Search Tool", slug: "pdf-search-tool", category: "PDF Tools", isPro: false },
  { id: 56, name: "PDF Find and Replace", slug: "pdf-find-and-replace", category: "PDF Tools", isPro: false },
  { id: 57, name: "PDF Page Counter", slug: "pdf-page-counter", category: "PDF Tools", isPro: false },
  { id: 58, name: "PDF Word Counter", slug: "pdf-word-counter", category: "PDF Tools", isPro: false },
  { id: 59, name: "PDF Character Counter", slug: "pdf-character-counter", category: "PDF Tools", isPro: false },
  { id: 60, name: "PDF Reading Time Calculator", slug: "pdf-reading-time-calculator", category: "PDF Tools", isPro: false },

  // --- PRO / AI / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "AI PDF Summarizer", slug: "ai-pdf-summarizer", category: "PDF Tools", isPro: true },
  { id: 62, name: "AI PDF Question Answering", slug: "ai-pdf-question-answering", category: "PDF Tools", isPro: true },
  { id: 63, name: "AI PDF Document Analyzer", slug: "ai-pdf-document-analyzer", category: "PDF Tools", isPro: true },
  { id: 64, name: "PDF Table Extractor", slug: "pdf-table-extractor", category: "PDF Tools", isPro: true },
  { id: 65, name: "Multi-PDF Search", slug: "multi-pdf-search", category: "PDF Tools", isPro: true },
  { id: 66, name: "PDF Compare Tool", slug: "pdf-compare-tool", category: "PDF Tools", isPro: true },
  { id: 67, name: "Batch PDF Converter", slug: "batch-pdf-converter", category: "PDF Tools", isPro: true },
  { id: 68, name: "Batch PDF Compressor", slug: "batch-pdf-compressor", category: "PDF Tools", isPro: true },
  { id: 69, name: "PDF Workflow Builder", slug: "pdf-workflow-builder", category: "PDF Tools", isPro: true },
  { id: 70, name: "PDF Compliance Checker", slug: "pdf-compliance-checker", category: "PDF Tools", isPro: true },
  { id: 71, name: "OCR Text Extractor", slug: "ocr-text-extractor", category: "PDF Tools", isPro: true },
  { id: 72, name: "PDF Form Extractor", slug: "pdf-form-extractor", category: "PDF Tools", isPro: true },
  { id: 73, name: "PDF Form Field Editor", slug: "pdf-form-field-editor", category: "PDF Tools", isPro: true },
  { id: 74, name: "PDF Form Flattening Tool", slug: "pdf-form-flattening-tool", category: "PDF Tools", isPro: true },
  { id: 75, name: "Electronic Signature Workflow", slug: "electronic-signature-workflow", category: "PDF Tools", isPro: true },
  { id: 76, name: "PDF Certificate Inspector", slug: "pdf-certificate-inspector", category: "PDF Tools", isPro: true },
  { id: 77, name: "Permanent PDF Redaction", slug: "permanent-pdf-redaction", category: "PDF Tools", isPro: true },
  { id: 78, name: "Sensitive Data Finder", slug: "sensitive-data-finder", category: "PDF Tools", isPro: true },
  { id: 79, name: "Tagged PDF Checker", slug: "tagged-pdf-checker", category: "PDF Tools", isPro: true },
  { id: 80, name: "PDF Structure Analyzer", slug: "pdf-structure-analyzer", category: "PDF Tools", isPro: true },
  { id: 81, name: "PDF Font Analyzer", slug: "pdf-font-analyzer", category: "PDF Tools", isPro: true },
  { id: 82, name: "PDF Image Analyzer", slug: "pdf-image-analyzer", category: "PDF Tools", isPro: true },
  { id: 83, name: "PDF Object Inspector", slug: "pdf-object-inspector", category: "PDF Tools", isPro: true },
  { id: 84, name: "PDF XRef Analyzer", slug: "pdf-xref-analyzer", category: "PDF Tools", isPro: true },
  { id: 85, name: "PDF Content Layer Analyzer", slug: "pdf-content-layer-analyzer", category: "PDF Tools", isPro: true },
  { id: 86, name: "PDF Version Diff Tool", slug: "pdf-version-diff-tool", category: "PDF Tools", isPro: true },
  { id: 87, name: "Batch PDF Merger", slug: "batch-pdf-merger", category: "PDF Tools", isPro: true },
  { id: 88, name: "Batch PDF Watermarker", slug: "batch-pdf-watermarker", category: "PDF Tools", isPro: true },
  { id: 89, name: "Batch PDF OCR", slug: "batch-pdf-ocr", category: "PDF Tools", isPro: true },
  { id: 90, name: "PDF Document Classifier", slug: "pdf-document-classifier", category: "PDF Tools", isPro: true },
  { id: 91, name: "PDF Orientation Checker", slug: "pdf-orientation-checker", category: "PDF Tools", isPro: true },
  { id: 92, name: "PDF Version Checker", slug: "pdf-version-checker", category: "PDF Tools", isPro: true },
  { id: 93, name: "PDF File Size Analyzer", slug: "pdf-file-size-analyzer", category: "PDF Tools", isPro: true },
  { id: 94, name: "PDF Repair Tool", slug: "pdf-repair-tool", category: "PDF Tools", isPro: true },
  { id: 95, name: "PDF Validator", slug: "pdf-validator", category: "PDF Tools", isPro: true },
  { id: 96, name: "PDF/A Converter", slug: "pdf-a-converter", category: "PDF Tools", isPro: true },
  { id: 97, name: "PDF/A Validator", slug: "pdf-a-validator", category: "PDF Tools", isPro: true },
  { id: 98, name: "PDF Linearization Tool", slug: "pdf-linearization-tool", category: "PDF Tools", isPro: true },
  { id: 99, name: "PDF Print Optimizer", slug: "pdf-print-optimizer", category: "PDF Tools", isPro: true },
  { id: 100, name: "PDF Workspace Suite", slug: "pdf-workspace-suite", category: "PDF Tools", isPro: true },
];