export interface PRMediaTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const prMediaRelationsToolsList: PRMediaTool[] = [
  // --- 🔥 PRIORITY 20 FREE TOOLS (IDs 1-20 | isPro: false) ---
  { id: 1, name: "Press Release Planner", slug: "press-release-planner", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 2, name: "News Angle Generator", slug: "news-angle-generator", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 3, name: "Media Pitch Planner", slug: "media-pitch-planner", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 4, name: "Journalist Outreach Planner", slug: "journalist-outreach-planner", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 5, name: "Media Outreach Tracker", slug: "media-outreach-tracker", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 6, name: "Journalist Contact Organizer", slug: "journalist-contact-organizer", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 7, name: "Media List Organizer", slug: "media-list-organizer", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 8, name: "Journalist Beat Mapper", slug: "journalist-beat-mapper", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 9, name: "Media Opportunity Tracker", slug: "media-opportunity-tracker", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 10, name: "PR Campaign Planner", slug: "pr-campaign-planner", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 11, name: "Launch PR Checklist", slug: "launch-pr-checklist", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 12, name: "Crisis Communication Planner", slug: "crisis-communication-planner", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 13, name: "Media Kit Checklist", slug: "media-kit-checklist", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 14, name: "Key Message Builder", slug: "key-message-builder", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 15, name: "Media Outreach Schedule", slug: "media-outreach-schedule", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 16, name: "Media Coverage Tracker", slug: "media-coverage-tracker", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 17, name: "Earned Media Value Calculator", slug: "earned-media-value-calculator", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 18, name: "PR ROI Calculator", slug: "pr-roi-calculator", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 19, name: "Media Coverage Dashboard", slug: "media-coverage-dashboard-free", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 20, name: "Media Relations Workspace", slug: "media-relations-workspace-free", category: "Public Relations & Media Relations Tools", isPro: false },

  // --- REMAINING 40 CORE FREE TOOLS (IDs 21-60 | isPro: false) ---
  { id: 21, name: "Press Release Structure Builder", slug: "press-release-structure-builder", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 22, name: "Story Angle Planner", slug: "story-angle-planner", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 23, name: "Media Pitch Outline", slug: "media-pitch-outline", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 24, name: "Media List Segmentation", slug: "media-list-segmentation", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 25, name: "Publication Category Mapper", slug: "publication-category-mapper", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 26, name: "Media Relationship Tracker", slug: "media-relationship-tracker", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 27, name: "Press Contact Database", slug: "press-contact-database", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 28, name: "Editorial Calendar Planner", slug: "editorial-calendar-planner", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 29, name: "Press Calendar", slug: "press-calendar", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 30, name: "PR Campaign Timeline", slug: "pr-campaign-timeline", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 31, name: "Product Launch PR Planner", slug: "product-launch-pr-planner", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 32, name: "Event PR Checklist", slug: "event-pr-checklist", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 33, name: "Crisis PR Checklist", slug: "crisis-pr-checklist", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 34, name: "Media Interview Checklist", slug: "media-interview-checklist", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 35, name: "Spokesperson Preparation Checklist", slug: "spokesperson-preparation-checklist", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 36, name: "Press Conference Planner", slug: "press-conference-planner", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 37, name: "Press Briefing Planner", slug: "press-briefing-planner", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 38, name: "Press Kit Organizer", slug: "press-kit-organizer", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 39, name: "Company Fact Sheet Builder", slug: "company-fact-sheet-builder", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 40, name: "Executive Bio Builder", slug: "executive-bio-builder", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 41, name: "Media Bio Checklist", slug: "media-bio-checklist", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 42, name: "Press FAQ Builder", slug: "press-faq-builder", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 43, name: "Journalist Brief Builder", slug: "journalist-brief-builder", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 44, name: "Media Briefing Document", slug: "media-briefing-document", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 45, name: "Talking Points Planner", slug: "talking-points-planner", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 46, name: "Message Consistency Checklist", slug: "message-consistency-checklist", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 47, name: "PR Asset Checklist", slug: "pr-asset-checklist", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 48, name: "Follow-Up Schedule Planner", slug: "follow-up-schedule-planner", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 49, name: "Press Embargo Tracker", slug: "press-embargo-tracker", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 50, name: "Publication Deadline Tracker", slug: "publication-deadline-tracker", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 51, name: "Press Mention Tracker", slug: "press-mention-tracker", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 52, name: "Media Reach Calculator", slug: "media-reach-calculator", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 53, name: "Media Response Rate Calculator", slug: "media-response-rate-calculator", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 54, name: "Pitch Response Rate Calculator", slug: "pitch-response-rate-calculator", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 55, name: "Media Conversion Calculator", slug: "media-conversion-calculator", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 56, name: "PR Campaign KPI Calculator", slug: "pr-campaign-kpi-calculator", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 57, name: "Share of Voice Calculator", slug: "share-of-voice-calculator", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 58, name: "PR Performance Report", slug: "pr-performance-report", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 59, name: "Press Outreach Report", slug: "press-outreach-report", category: "Public Relations & Media Relations Tools", isPro: false },
  { id: 60, name: "Crisis Communication Checklist", slug: "crisis-communication-checklist", category: "Public Relations & Media Relations Tools", isPro: false },

  // --- ⚡ 40 PRO / SAAS TOOLS (IDs 61-100 | isPro: true) ---
  { id: 61, name: "PR Management Workspace", slug: "pr-management-workspace", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 62, name: "Media Relations Workspace", slug: "media-relations-workspace", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 63, name: "Journalist Relationship Workspace", slug: "journalist-relationship-workspace", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 64, name: "Media Database Workspace", slug: "media-database-workspace", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 65, name: "Press Outreach Workspace", slug: "press-outreach-workspace", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 66, name: "Pitch Management Workspace", slug: "pitch-management-workspace", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 67, name: "Press Release Management", slug: "press-release-management", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 68, name: "PR Campaign Dashboard", slug: "pr-campaign-dashboard", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 69, name: "Media Coverage Dashboard", slug: "media-coverage-dashboard", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 70, name: "Earned Media Dashboard", slug: "earned-media-dashboard", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 71, name: "Share of Voice Dashboard", slug: "share-of-voice-dashboard", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 72, name: "Journalist Engagement Dashboard", slug: "journalist-engagement-dashboard", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 73, name: "Media Opportunity Dashboard", slug: "media-opportunity-dashboard", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 74, name: "Editorial Calendar Workspace", slug: "editorial-calendar-workspace", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 75, name: "Press Calendar Workspace", slug: "press-calendar-workspace", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 76, name: "Product Launch PR Workspace", slug: "product-launch-pr-workspace", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 77, name: "Event PR Workspace", slug: "event-pr-workspace", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 78, name: "Crisis Communications Workspace", slug: "crisis-communications-workspace", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 79, name: "Spokesperson Management Workspace", slug: "spokesperson-management-workspace", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 80, name: "Media Kit Management", slug: "media-kit-management", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 81, name: "Press Contact Management", slug: "press-contact-management", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 82, name: "Media Relationship Analytics", slug: "media-relationship-analytics", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 83, name: "Pitch Performance Analytics", slug: "pitch-performance-analytics", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 84, name: "Media Response Analytics", slug: "media-response-analytics", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 85, name: "PR ROI Analytics", slug: "pr-roi-analytics", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 86, name: "Coverage Intelligence Workspace", slug: "coverage-intelligence-workspace", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 87, name: "Media Monitoring Workspace", slug: "media-monitoring-workspace", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 88, name: "PR Reporting Engine", slug: "pr-reporting-engine", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 89, name: "PR Data Importer", slug: "pr-data-importer", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 90, name: "PR Data Exporter", slug: "pr-data-exporter", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 91, name: "Media Relations API", slug: "media-relations-api", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 92, name: "PR Workflow Automation", slug: "pr-workflow-automation", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 93, name: "Media Outreach Automation", slug: "media-outreach-automation", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 94, name: "Press Alert Engine", slug: "press-alert-engine", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 95, name: "PR Knowledge Base", slug: "pr-knowledge-base", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 96, name: "PR Intelligence Platform", slug: "pr-intelligence-platform", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 97, name: "Media Relations Platform", slug: "media-relations-platform", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 98, name: "Enterprise PR Platform", slug: "enterprise-pr-platform", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 99, name: "Global Communications Platform", slug: "global-communications-platform", category: "Public Relations & Media Relations Tools", isPro: true },
  { id: 100, name: "PR Command Center", slug: "pr-command-center", category: "Public Relations & Media Relations Tools", isPro: true }
];