export interface ProcurementVendorTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const procurementVendorToolsList: ProcurementVendorTool[] = [
  // --- 🔥 PRIORITY 20 FREE TOOLS (IDs 1-20 | isPro: false) ---
  { id: 1, name: "Vendor Comparison Matrix", slug: "vendor-comparison-matrix", category: "Procurement & Vendor Tools", isPro: false },
  { id: 2, name: "Total Cost of Ownership Calculator", slug: "total-cost-of-ownership-calculator", category: "Procurement & Vendor Tools", isPro: false },
  { id: 3, name: "RFQ Comparison Tool", slug: "rfq-comparison-tool", category: "Procurement & Vendor Tools", isPro: false },
  { id: 4, name: "Vendor Risk Score", slug: "vendor-risk-score", category: "Procurement & Vendor Tools", isPro: false },
  { id: 5, name: "Procurement Savings Calculator", slug: "procurement-savings-calculator", category: "Procurement & Vendor Tools", isPro: false },
  { id: 6, name: "Bid Comparison Calculator", slug: "bid-comparison-calculator", category: "Procurement & Vendor Tools", isPro: false },
  { id: 7, name: "Supplier Scorecard", slug: "supplier-scorecard", category: "Procurement & Vendor Tools", isPro: false },
  { id: 8, name: "Purchase Spend Analyzer", slug: "purchase-spend-analyzer", category: "Procurement & Vendor Tools", isPro: false },
  { id: 9, name: "Vendor Score Calculator", slug: "vendor-score-calculator", category: "Procurement & Vendor Tools", isPro: false },
  { id: 10, name: "Supplier Risk Calculator", slug: "supplier-risk-calculator", category: "Procurement & Vendor Tools", isPro: false },
  { id: 11, name: "Purchase Cost Calculator", slug: "purchase-cost-calculator", category: "Procurement & Vendor Tools", isPro: false },
  { id: 12, name: "Vendor Quote Comparison", slug: "vendor-quote-comparison", category: "Procurement & Vendor Tools", isPro: false },
  { id: 13, name: "Vendor Selection Matrix", slug: "vendor-selection-matrix", category: "Procurement & Vendor Tools", isPro: false },
  { id: 14, name: "Supplier Selection Matrix", slug: "supplier-selection-matrix", category: "Procurement & Vendor Tools", isPro: false },
  { id: 15, name: "Procurement Requirement Builder", slug: "procurement-requirement-builder", category: "Procurement & Vendor Tools", isPro: false },
  { id: 16, name: "RFQ Generator", slug: "rfq-generator", category: "Procurement & Vendor Tools", isPro: false },
  { id: 17, name: "Supplier Spend Analyzer", slug: "supplier-spend-analyzer", category: "Procurement & Vendor Tools", isPro: false },
  { id: 18, name: "Category Spend Calculator", slug: "category-spend-calculator", category: "Procurement & Vendor Tools", isPro: false },
  { id: 19, name: "Supplier Performance Dashboard Free", slug: "supplier-performance-dashboard-free", category: "Procurement & Vendor Tools", isPro: false },
  { id: 20, name: "Procurement Workspace Free", slug: "procurement-workspace-free", category: "Procurement & Vendor Tools", isPro: false },

  // --- REMAINING 40 CORE FREE TOOLS (IDs 21-60 | isPro: false) ---
  { id: 21, name: "Purchase Order Checklist", slug: "purchase-order-checklist", category: "Procurement & Vendor Tools", isPro: false },
  { id: 22, name: "Vendor Onboarding Checklist", slug: "vendor-onboarding-checklist", category: "Procurement & Vendor Tools", isPro: false },
  { id: 23, name: "Supplier Onboarding Checklist", slug: "supplier-onboarding-checklist", category: "Procurement & Vendor Tools", isPro: false },
  { id: 24, name: "Vendor Evaluation Checklist", slug: "vendor-evaluation-checklist", category: "Procurement & Vendor Tools", isPro: false },
  { id: 25, name: "Supplier Evaluation Checklist", slug: "supplier-evaluation-checklist", category: "Procurement & Vendor Tools", isPro: false },
  { id: 26, name: "Procurement Approval Matrix", slug: "procurement-approval-matrix", category: "Procurement & Vendor Tools", isPro: false },
  { id: 27, name: "Purchase Approval Calculator", slug: "purchase-approval-calculator", category: "Procurement & Vendor Tools", isPro: false },
  { id: 28, name: "Vendor Due Diligence Checklist", slug: "vendor-due-diligence-checklist", category: "Procurement & Vendor Tools", isPro: false },
  { id: 29, name: "Supplier Due Diligence Checklist", slug: "supplier-due-diligence-checklist", category: "Procurement & Vendor Tools", isPro: false },
  { id: 30, name: "Purchase Specification Builder", slug: "purchase-specification-builder", category: "Procurement & Vendor Tools", isPro: false },
  { id: 31, name: "RFP Requirement Builder", slug: "rfp-requirement-builder", category: "Procurement & Vendor Tools", isPro: false },
  { id: 32, name: "Vendor Questionnaire Generator", slug: "vendor-questionnaire-generator", category: "Procurement & Vendor Tools", isPro: false },
  { id: 33, name: "Supplier Questionnaire Generator", slug: "supplier-questionnaire-generator", category: "Procurement & Vendor Tools", isPro: false },
  { id: 34, name: "Procurement Checklist Generator", slug: "procurement-checklist-generator", category: "Procurement & Vendor Tools", isPro: false },
  { id: 35, name: "Procurement SOP Generator", slug: "procurement-sop-generator", category: "Procurement & Vendor Tools", isPro: false },
  { id: 36, name: "Vendor Meeting Planner", slug: "vendor-meeting-planner", category: "Procurement & Vendor Tools", isPro: false },
  { id: 37, name: "Supplier Review Planner", slug: "supplier-review-planner", category: "Procurement & Vendor Tools", isPro: false },
  { id: 38, name: "Vendor Performance Tracker", slug: "vendor-performance-tracker", category: "Procurement & Vendor Tools", isPro: false },
  { id: 39, name: "Supplier Performance Tracker", slug: "supplier-performance-tracker", category: "Procurement & Vendor Tools", isPro: false },
  { id: 40, name: "Contract Renewal Reminder", slug: "contract-renewal-reminder", category: "Procurement & Vendor Tools", isPro: false },
  { id: 41, name: "Vendor Renewal Tracker", slug: "vendor-renewal-tracker", category: "Procurement & Vendor Tools", isPro: false },
  { id: 42, name: "Purchase Request Tracker", slug: "purchase-request-tracker", category: "Procurement & Vendor Tools", isPro: false },
  { id: 43, name: "Procurement Request Form", slug: "procurement-request-form", category: "Procurement & Vendor Tools", isPro: false },
  { id: 44, name: "Vendor Contact Organizer", slug: "vendor-contact-organizer", category: "Procurement & Vendor Tools", isPro: false },
  { id: 45, name: "Supplier Directory", slug: "supplier-directory", category: "Procurement & Vendor Tools", isPro: false },
  { id: 46, name: "Procurement Calendar", slug: "procurement-calendar", category: "Procurement & Vendor Tools", isPro: false },
  { id: 47, name: "Purchase Schedule Planner", slug: "purchase-schedule-planner", category: "Procurement & Vendor Tools", isPro: false },
  { id: 48, name: "Supplier Delivery Tracker", slug: "supplier-delivery-tracker", category: "Procurement & Vendor Tools", isPro: false },
  { id: 49, name: "Vendor Issue Tracker", slug: "vendor-issue-tracker", category: "Procurement & Vendor Tools", isPro: false },
  { id: 50, name: "Supplier Issue Tracker", slug: "supplier-issue-tracker", category: "Procurement & Vendor Tools", isPro: false },
  { id: 51, name: "Procurement Risk Register", slug: "procurement-risk-register", category: "Procurement & Vendor Tools", isPro: false },
  { id: 52, name: "Procurement Savings Tracker", slug: "procurement-savings-tracker", category: "Procurement & Vendor Tools", isPro: false },
  { id: 53, name: "Procurement KPI Generator", slug: "procurement-kpi-generator", category: "Procurement & Vendor Tools", isPro: false },
  { id: 54, name: "Vendor Report Generator", slug: "vendor-report-generator", category: "Procurement & Vendor Tools", isPro: false },
  { id: 55, name: "Supplier Report Generator", slug: "supplier-report-generator", category: "Procurement & Vendor Tools", isPro: false },
  { id: 56, name: "Procurement Summary Generator", slug: "procurement-summary-generator", category: "Procurement & Vendor Tools", isPro: false },
  { id: 57, name: "Purchase Analysis Report", slug: "purchase-analysis-report", category: "Procurement & Vendor Tools", isPro: false },
  { id: 58, name: "Vendor Comparison Report", slug: "vendor-comparison-report", category: "Procurement & Vendor Tools", isPro: false },
  { id: 59, name: "Procurement Compliance Checklist", slug: "procurement-compliance-checklist", category: "Procurement & Vendor Tools", isPro: false },
  { id: 60, name: "Procurement Performance Tracker", slug: "procurement-performance-tracker", category: "Procurement & Vendor Tools", isPro: false },

  // --- ⚡ 40 PRO / SAAS TOOLS (IDs 61-100 | isPro: true) ---
  { id: 61, name: "Procurement Workspace", slug: "procurement-workspace", category: "Procurement & Vendor Tools", isPro: true },
  { id: 62, name: "Strategic Sourcing Workspace", slug: "strategic-sourcing-workspace", category: "Procurement & Vendor Tools", isPro: true },
  { id: 63, name: "Vendor Management Workspace", slug: "vendor-management-workspace", category: "Procurement & Vendor Tools", isPro: true },
  { id: 64, name: "Supplier Management Workspace", slug: "supplier-management-workspace", category: "Procurement & Vendor Tools", isPro: true },
  { id: 65, name: "Supplier Risk Dashboard", slug: "supplier-risk-dashboard", category: "Procurement & Vendor Tools", isPro: true },
  { id: 66, name: "Vendor Risk Dashboard", slug: "vendor-risk-dashboard", category: "Procurement & Vendor Tools", isPro: true },
  { id: 67, name: "Spend Intelligence Workspace", slug: "spend-intelligence-workspace", category: "Procurement & Vendor Tools", isPro: true },
  { id: 68, name: "Procurement Savings Dashboard", slug: "procurement-savings-dashboard", category: "Procurement & Vendor Tools", isPro: true },
  { id: 69, name: "TCO Analysis Workspace", slug: "tco-analysis-workspace", category: "Procurement & Vendor Tools", isPro: true },
  { id: 70, name: "RFQ Management Workspace", slug: "rfq-management-workspace", category: "Procurement & Vendor Tools", isPro: true },
  { id: 71, name: "RFP Management Workspace", slug: "rfp-management-workspace", category: "Procurement & Vendor Tools", isPro: true },
  { id: 72, name: "Bid Management Workspace", slug: "bid-management-workspace", category: "Procurement & Vendor Tools", isPro: true },
  { id: 73, name: "Supplier Evaluation Platform", slug: "supplier-evaluation-platform", category: "Procurement & Vendor Tools", isPro: true },
  { id: 74, name: "Vendor Evaluation Platform", slug: "vendor-evaluation-platform", category: "Procurement & Vendor Tools", isPro: true },
  { id: 75, name: "Procurement Approval Workspace", slug: "procurement-approval-workspace", category: "Procurement & Vendor Tools", isPro: true },
  { id: 76, name: "Supplier Performance Dashboard", slug: "supplier-performance-dashboard", category: "Procurement & Vendor Tools", isPro: true },
  { id: 77, name: "Vendor Performance Dashboard", slug: "vendor-performance-dashboard", category: "Procurement & Vendor Tools", isPro: true },
  { id: 78, name: "Supplier Delivery Analytics", slug: "supplier-delivery-analytics", category: "Procurement & Vendor Tools", isPro: true },
  { id: 79, name: "Vendor Compliance Workspace", slug: "vendor-compliance-workspace", category: "Procurement & Vendor Tools", isPro: true },
  { id: 80, name: "Procurement Audit Workspace", slug: "procurement-audit-workspace", category: "Procurement & Vendor Tools", isPro: true },
  { id: 81, name: "Procurement Contract Tracker", slug: "procurement-contract-tracker", category: "Procurement & Vendor Tools", isPro: true },
  { id: 82, name: "Supplier Contract Tracker", slug: "supplier-contract-tracker", category: "Procurement & Vendor Tools", isPro: true },
  { id: 83, name: "Vendor Renewal Management", slug: "vendor-renewal-management", category: "Procurement & Vendor Tools", isPro: true },
  { id: 84, name: "Procurement Forecasting Workspace", slug: "procurement-forecasting-workspace", category: "Procurement & Vendor Tools", isPro: true },
  { id: 85, name: "Supplier Forecasting Workspace", slug: "supplier-forecasting-workspace", category: "Procurement & Vendor Tools", isPro: true },
  { id: 86, name: "Procurement Analytics", slug: "procurement-analytics", category: "Procurement & Vendor Tools", isPro: true },
  { id: 87, name: "Strategic Sourcing Analytics", slug: "strategic-sourcing-analytics", category: "Procurement & Vendor Tools", isPro: true },
  { id: 88, name: "Procurement Automation", slug: "procurement-automation", category: "Procurement & Vendor Tools", isPro: true },
  { id: 89, name: "Vendor Onboarding Workspace", slug: "vendor-onboarding-workspace", category: "Procurement & Vendor Tools", isPro: true },
  { id: 90, name: "Supplier Onboarding Workspace", slug: "supplier-onboarding-workspace", category: "Procurement & Vendor Tools", isPro: true },
  { id: 91, name: "Procurement Data Workspace", slug: "procurement-data-workspace", category: "Procurement & Vendor Tools", isPro: true },
  { id: 92, name: "Procurement API", slug: "procurement-api", category: "Procurement & Vendor Tools", isPro: true },
  { id: 93, name: "Spend Data Importer", slug: "spend-data-importer", category: "Procurement & Vendor Tools", isPro: true },
  { id: 94, name: "Procurement Reporting Engine", slug: "procurement-reporting-engine", category: "Procurement & Vendor Tools", isPro: true },
  { id: 95, name: "Supplier Intelligence Platform", slug: "supplier-intelligence-platform", category: "Procurement & Vendor Tools", isPro: true },
  { id: 96, name: "Vendor Intelligence Platform", slug: "vendor-intelligence-platform", category: "Procurement & Vendor Tools", isPro: true },
  { id: 97, name: "Enterprise Procurement Platform", slug: "enterprise-procurement-platform", category: "Procurement & Vendor Tools", isPro: true },
  { id: 98, name: "Strategic Sourcing Platform", slug: "strategic-sourcing-platform", category: "Procurement & Vendor Tools", isPro: true },
  { id: 99, name: "Procurement Intelligence Platform", slug: "procurement-intelligence-platform", category: "Procurement & Vendor Tools", isPro: true },
  { id: 100, name: "Procurement Command Center", slug: "procurement-command-center", category: "Procurement & Vendor Tools", isPro: true }
];