export interface ProductivityTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const productivityToolsList: ProductivityTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-13) ---
  { id: 1, name: "To-Do List", slug: "to-do-list", category: "Productivity Tools", isPro: false },
  { id: 2, name: "Daily Planner", slug: "daily-planner", category: "Productivity Tools", isPro: false },
  { id: 3, name: "Time Blocking Planner", slug: "time-blocking-planner", category: "Productivity Tools", isPro: false },
  { id: 4, name: "Pomodoro Timer", slug: "pomodoro-timer", category: "Productivity Tools", isPro: false },
  { id: 5, name: "Habit Tracker", slug: "habit-tracker", category: "Productivity Tools", isPro: false },
  { id: 6, name: "Goal Tracker", slug: "goal-tracker", category: "Productivity Tools", isPro: false },
  { id: 7, name: "Project Planner", slug: "project-planner", category: "Productivity Tools", isPro: false },
  { id: 8, name: "Project Timeline Generator", slug: "project-timeline-generator", category: "Productivity Tools", isPro: false },
  { id: 9, name: "Time Tracker", slug: "time-tracker", category: "Productivity Tools", isPro: false },
  { id: 10, name: "Timesheet Calculator", slug: "timesheet-calculator", category: "Productivity Tools", isPro: false },
  { id: 11, name: "Deadline Calculator", slug: "deadline-calculator", category: "Productivity Tools", isPro: false },
  { id: 12, name: "Priority Matrix", slug: "priority-matrix", category: "Productivity Tools", isPro: false },
  { id: 13, name: "Meeting Agenda Generator", slug: "meeting-agenda-generator-prod", category: "Productivity Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (14-60) ---
  { id: 14, name: "Task Planner", slug: "task-planner", category: "Productivity Tools", isPro: false },
  { id: 15, name: "Weekly Planner", slug: "weekly-planner", category: "Productivity Tools", isPro: false },
  { id: 16, name: "Monthly Planner", slug: "monthly-planner", category: "Productivity Tools", isPro: false },
  { id: 17, name: "Yearly Planner", slug: "yearly-planner", category: "Productivity Tools", isPro: false },
  { id: 18, name: "Eisenhower Matrix", slug: "eisenhower-matrix", category: "Productivity Tools", isPro: false },
  { id: 19, name: "Focus Timer", slug: "focus-timer", category: "Productivity Tools", isPro: false },
  { id: 20, name: "Countdown Timer", slug: "countdown-timer", category: "Productivity Tools", isPro: false },
  { id: 21, name: "Stopwatch", slug: "stopwatch", category: "Productivity Tools", isPro: false },
  { id: 22, name: "Goal Planner", slug: "goal-planner", category: "Productivity Tools", isPro: false },
  { id: 23, name: "SMART Goal Generator", slug: "smart-goal-generator", category: "Productivity Tools", isPro: false },
  { id: 24, name: "Routine Builder", slug: "routine-builder", category: "Productivity Tools", isPro: false },
  { id: 25, name: "Morning Routine Planner", slug: "morning-routine-planner", category: "Productivity Tools", isPro: false },
  { id: 26, name: "Evening Routine Planner", slug: "evening-routine-planner", category: "Productivity Tools", isPro: false },
  { id: 27, name: "Workday Planner", slug: "workday-planner", category: "Productivity Tools", isPro: false },
  { id: 28, name: "Meeting Planner", slug: "meeting-planner", category: "Productivity Tools", isPro: false },
  { id: 29, name: "Meeting Notes Template", slug: "meeting-notes-template", category: "Productivity Tools", isPro: false },
  { id: 30, name: "Meeting Action Item Tracker", slug: "meeting-action-item-tracker", category: "Productivity Tools", isPro: false },
  { id: 31, name: "Project Checklist", slug: "project-checklist", category: "Productivity Tools", isPro: false },
  { id: 32, name: "Project Milestone Planner", slug: "project-milestone-planner", category: "Productivity Tools", isPro: false },
  { id: 33, name: "Task Dependency Planner", slug: "task-dependency-planner", category: "Productivity Tools", isPro: false },
  { id: 34, name: "Work Hours Calculator", slug: "work-hours-calculator", category: "Productivity Tools", isPro: false },
  { id: 35, name: "Time Zone Converter", slug: "time-zone-converter", category: "Productivity Tools", isPro: false },
  { id: 36, name: "World Clock", slug: "world-clock", category: "Productivity Tools", isPro: false },
  { id: 37, name: "Focus Session Tracker", slug: "focus-session-tracker", category: "Productivity Tools", isPro: false },
  { id: 38, name: "Break Reminder", slug: "break-reminder", category: "Productivity Tools", isPro: false },
  { id: 39, name: "Productivity Score Calculator", slug: "productivity-score-calculator", category: "Productivity Tools", isPro: false },
  { id: 40, name: "Task Priority Calculator", slug: "task-priority-calculator", category: "Productivity Tools", isPro: false },
  { id: 41, name: "Workload Calculator", slug: "workload-calculator", category: "Productivity Tools", isPro: false },
  { id: 42, name: "Capacity Planner", slug: "capacity-planner", category: "Productivity Tools", isPro: false },
  { id: 43, name: "Resource Planner", slug: "resource-planner", category: "Productivity Tools", isPro: false },
  { id: 44, name: "Team Task Planner", slug: "team-task-planner", category: "Productivity Tools", isPro: false },
  { id: 45, name: "Personal OKR Planner", slug: "personal-okr-planner", category: "Productivity Tools", isPro: false },
  { id: 46, name: "Team OKR Planner", slug: "team-okr-planner", category: "Productivity Tools", isPro: false },
  { id: 47, name: "KPI Goal Tracker", slug: "kpi-goal-tracker", category: "Productivity Tools", isPro: false },
  { id: 48, name: "Decision Matrix", slug: "decision-matrix", category: "Productivity Tools", isPro: false },
  { id: 49, name: "Pros and Cons Generator", slug: "pros-and-cons-generator", category: "Productivity Tools", isPro: false },
  { id: 50, name: "Eisenhower Task Sorter", slug: "eisenhower-task-sorter", category: "Productivity Tools", isPro: false },
  { id: 51, name: "Brain Dump Organizer", slug: "brain-dump-organizer", category: "Productivity Tools", isPro: false },
  { id: 52, name: "Notes Organizer", slug: "notes-organizer", category: "Productivity Tools", isPro: false },
  { id: 53, name: "Checklist Generator", slug: "checklist-generator", category: "Productivity Tools", isPro: false },
  { id: 54, name: "Packing Checklist Generator", slug: "packing-checklist-generator", category: "Productivity Tools", isPro: false },
  { id: 55, name: "Moving Checklist Generator", slug: "moving-checklist-generator", category: "Productivity Tools", isPro: false },
  { id: 56, name: "Cleaning Schedule Generator", slug: "cleaning-schedule-generator", category: "Productivity Tools", isPro: false },
  { id: 57, name: "Meal Planning Calendar", slug: "meal-planning-calendar", category: "Productivity Tools", isPro: false },
  { id: 58, name: "Shopping List Generator", slug: "shopping-list-generator", category: "Productivity Tools", isPro: false },
  { id: 59, name: "Personal Budget Planner", slug: "personal-budget-planner", category: "Productivity Tools", isPro: false },
  { id: 60, name: "Weekly Review Generator", slug: "weekly-review-generator", category: "Productivity Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Gantt Chart Generator", slug: "gantt-chart-generator", category: "Productivity Tools", isPro: true },
  { id: 62, name: "Kanban Board", slug: "kanban-board", category: "Productivity Tools", isPro: true },
  { id: 63, name: "Sprint Planner", slug: "sprint-planner", category: "Productivity Tools", isPro: true },
  { id: 64, name: "Roadmap Generator", slug: "roadmap-generator", category: "Productivity Tools", isPro: true },
  { id: 65, name: "OKR Dashboard", slug: "okr-dashboard", category: "Productivity Tools", isPro: true },
  { id: 66, name: "Team Capacity Planner", slug: "team-capacity-planner", category: "Productivity Tools", isPro: true },
  { id: 67, name: "Personal Productivity Analytics", slug: "personal-productivity-analytics", category: "Productivity Tools", isPro: true },
  { id: 68, name: "Project Management Dashboard", slug: "project-management-dashboard", category: "Productivity Tools", isPro: true },
  { id: 69, name: "Portfolio Project Tracker", slug: "portfolio-project-tracker", category: "Productivity Tools", isPro: true },
  { id: 70, name: "Resource Allocation Planner", slug: "resource-allocation-planner", category: "Productivity Tools", isPro: true },
  { id: 71, name: "Workload Balancer", slug: "workload-balancer", category: "Productivity Tools", isPro: true },
  { id: 72, name: "Project Risk Register", slug: "project-risk-register", category: "Productivity Tools", isPro: true },
  { id: 73, name: "Project Risk Score Calculator", slug: "project-risk-score-calculator", category: "Productivity Tools", isPro: true },
  { id: 74, name: "Project Cost Estimator", slug: "project-cost-estimator", category: "Productivity Tools", isPro: true },
  { id: 75, name: "Project Schedule Analyzer", slug: "project-schedule-analyzer", category: "Productivity Tools", isPro: true },
  { id: 76, name: "Critical Path Calculator", slug: "critical-path-calculator", category: "Productivity Tools", isPro: true },
  { id: 77, name: "PERT Calculator", slug: "pert-calculator", category: "Productivity Tools", isPro: true },
  { id: 78, name: "Agile Sprint Calculator", slug: "agile-sprint-calculator", category: "Productivity Tools", isPro: true },
  { id: 79, name: "Scrum Planning Tool", slug: "scrum-planning-tool", category: "Productivity Tools", isPro: true },
  { id: 80, name: "Story Point Calculator", slug: "story-point-calculator", category: "Productivity Tools", isPro: true },
  { id: 81, name: "Velocity Calculator", slug: "velocity-calculator", category: "Productivity Tools", isPro: true },
  { id: 82, name: "Burndown Chart Generator", slug: "burndown-chart-generator", category: "Productivity Tools", isPro: true },
  { id: 83, name: "Release Planning Tool", slug: "release-planning-tool", category: "Productivity Tools", isPro: true },
  { id: 84, name: "Product Roadmap Planner", slug: "product-roadmap-planner", category: "Productivity Tools", isPro: true },
  { id: 85, name: "KPI Dashboard", slug: "kpi-dashboard", category: "Productivity Tools", isPro: true },
  { id: 86, name: "Goal Alignment Analyzer", slug: "goal-alignment-analyzer", category: "Productivity Tools", isPro: true },
  { id: 87, name: "Team Performance Planner", slug: "team-performance-planner", category: "Productivity Tools", isPro: true },
  { id: 88, name: "Meeting Intelligence Workspace", slug: "meeting-intelligence-workspace", category: "Productivity Tools", isPro: true },
  { id: 89, name: "Meeting Decision Tracker", slug: "meeting-decision-tracker", category: "Productivity Tools", isPro: true },
  { id: 90, name: "Automated Task Extractor", slug: "automated-task-extractor", category: "Productivity Tools", isPro: true },
  { id: 91, name: "Workflow Planner", slug: "workflow-planner", category: "Productivity Tools", isPro: true },
  { id: 92, name: "Team Productivity Analytics", slug: "team-productivity-analytics", category: "Productivity Tools", isPro: true },
  { id: 93, name: "Time Allocation Analyzer", slug: "time-allocation-analyzer", category: "Productivity Tools", isPro: true },
  { id: 94, name: "Deep Work Planner", slug: "deep-work-planner", category: "Productivity Tools", isPro: true },
  { id: 95, name: "Focus Analytics Dashboard", slug: "focus-analytics-dashboard", category: "Productivity Tools", isPro: true },
  { id: 96, name: "Work-Life Time Analyzer", slug: "work-life-time-analyzer", category: "Productivity Tools", isPro: true },
  { id: 97, name: "Productivity Forecasting Tool", slug: "productivity-forecasting-tool", category: "Productivity Tools", isPro: true },
  { id: 98, name: "Executive Productivity Dashboard", slug: "executive-productivity-dashboard", category: "Productivity Tools", isPro: true },
  { id: 99, name: "Personal Productivity Workspace", slug: "personal-productivity-workspace", category: "Productivity Tools", isPro: true },
  { id: 100, name: "Team Productivity Workspace", slug: "team-productivity-workspace", category: "Productivity Tools", isPro: true },
];