export interface ProductManagementTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const productManagementToolsList: ProductManagementTool[] = [
  // --- 🔥 PRIORITY 20 FREE TOOLS (IDs 1-20 | isPro: false) ---
  { id: 1, name: "Product Requirements Builder", slug: "product-requirements-builder", category: "Product Management Tools", isPro: false },
  { id: 2, name: "Product Brief Builder", slug: "product-brief-builder", category: "Product Management Tools", isPro: false },
  { id: 3, name: "Product Strategy Canvas", slug: "product-strategy-canvas", category: "Product Management Tools", isPro: false },
  { id: 4, name: "Feature Definition Builder", slug: "feature-definition-builder", category: "Product Management Tools", isPro: false },
  { id: 5, name: "User Story Builder", slug: "user-story-builder", category: "Product Management Tools", isPro: false },
  { id: 6, name: "Acceptance Criteria Builder", slug: "acceptance-criteria-builder", category: "Product Management Tools", isPro: false },
  { id: 7, name: "Product Risk Register", slug: "product-risk-register", category: "Product Management Tools", isPro: false },
  { id: 8, name: "Feature Request Organizer", slug: "feature-request-organizer", category: "Product Management Tools", isPro: false },
  { id: 9, name: "Opportunity Score Calculator", slug: "opportunity-score-calculator", category: "Product Management Tools", isPro: false },
  { id: 10, name: "Feature Priority Calculator", slug: "feature-priority-calculator", category: "Product Management Tools", isPro: false },
  { id: 11, name: "Feature Impact Calculator", slug: "feature-impact-calculator", category: "Product Management Tools", isPro: false },
  { id: 12, name: "Feature Scoring Matrix", slug: "feature-scoring-matrix", category: "Product Management Tools", isPro: false },
  { id: 13, name: "Product Prioritization Matrix", slug: "product-prioritization-matrix", category: "Product Management Tools", isPro: false },
  { id: 14, name: "RICE Score Calculator", slug: "rice-score-calculator", category: "Product Management Tools", isPro: false },
  { id: 15, name: "Product Roadmap Planner", slug: "product-roadmap-planner", category: "Product Management Tools", isPro: false },
  { id: 16, name: "Product Release Checklist", slug: "product-release-checklist", category: "Product Management Tools", isPro: false },
  { id: 17, name: "Product KPI Planner", slug: "product-kpi-planner", category: "Product Management Tools", isPro: false },
  { id: 18, name: "Product Feedback Workspace", slug: "product-feedback-workspace-free", category: "Product Management Tools", isPro: false },
  { id: 19, name: "Product Roadmap Workspace", slug: "product-roadmap-workspace-free", category: "Product Management Tools", isPro: false },
  { id: 20, name: "Product Management Workspace", slug: "product-management-workspace-free", category: "Product Management Tools", isPro: false },

  // --- REMAINING 40 CORE FREE TOOLS (IDs 21-60 | isPro: false) ---
  { id: 21, name: "Product Vision Builder", slug: "product-vision-builder", category: "Product Management Tools", isPro: false },
  { id: 22, name: "Product Mission Builder", slug: "product-mission-builder", category: "Product Management Tools", isPro: false },
  { id: 23, name: "Product Objective Builder", slug: "product-objective-builder", category: "Product Management Tools", isPro: false },
  { id: 24, name: "Product Goal Planner", slug: "product-goal-planner", category: "Product Management Tools", isPro: false },
  { id: 25, name: "Feature Scope Planner", slug: "feature-scope-planner", category: "Product Management Tools", isPro: false },
  { id: 26, name: "Feature Requirement Builder", slug: "feature-requirement-builder", category: "Product Management Tools", isPro: false },
  { id: 27, name: "Product Hypothesis Builder", slug: "product-hypothesis-builder", category: "Product Management Tools", isPro: false },
  { id: 28, name: "Product Assumption Tracker", slug: "product-assumption-tracker", category: "Product Management Tools", isPro: false },
  { id: 29, name: "Product Dependency Tracker", slug: "product-dependency-tracker", category: "Product Management Tools", isPro: false },
  { id: 30, name: "Product Decision Log", slug: "product-decision-log", category: "Product Management Tools", isPro: false },
  { id: 31, name: "Product Feedback Log", slug: "product-feedback-log", category: "Product Management Tools", isPro: false },
  { id: 32, name: "Product Opportunity Tracker", slug: "product-opportunity-tracker", category: "Product Management Tools", isPro: false },
  { id: 33, name: "Feature Effort Calculator", slug: "feature-effort-calculator", category: "Product Management Tools", isPro: false },
  { id: 34, name: "Feature Value Calculator", slug: "feature-value-calculator", category: "Product Management Tools", isPro: false },
  { id: 35, name: "ICE Score Calculator", slug: "ice-score-calculator", category: "Product Management Tools", isPro: false },
  { id: 36, name: "MoSCoW Prioritization Tool", slug: "moscow-prioritization-tool", category: "Product Management Tools", isPro: false },
  { id: 37, name: "Kano Prioritization Tool", slug: "kano-prioritization-tool", category: "Product Management Tools", isPro: false },
  { id: 38, name: "Feature Roadmap Planner", slug: "feature-roadmap-planner", category: "Product Management Tools", isPro: false },
  { id: 39, name: "Release Roadmap Planner", slug: "release-roadmap-planner", category: "Product Management Tools", isPro: false },
  { id: 40, name: "Product Timeline Planner", slug: "product-timeline-planner", category: "Product Management Tools", isPro: false },
  { id: 41, name: "Product Milestone Planner", slug: "product-milestone-planner", category: "Product Management Tools", isPro: false },
  { id: 42, name: "Feature Launch Checklist", slug: "feature-launch-checklist", category: "Product Management Tools", isPro: false },
  { id: 43, name: "Product Discovery Checklist", slug: "product-discovery-checklist", category: "Product Management Tools", isPro: false },
  { id: 44, name: "Product Validation Checklist", slug: "product-validation-checklist", category: "Product Management Tools", isPro: false },
  { id: 45, name: "Product Research Brief", slug: "product-research-brief", category: "Product Management Tools", isPro: false },
  { id: 46, name: "User Interview Planner", slug: "user-interview-planner", category: "Product Management Tools", isPro: false },
  { id: 47, name: "Product Interview Question Builder", slug: "product-interview-question-builder", category: "Product Management Tools", isPro: false },
  { id: 48, name: "Customer Feedback Categorizer", slug: "customer-feedback-categorizer", category: "Product Management Tools", isPro: false },
  { id: 49, name: "Product Feedback Prioritizer", slug: "product-feedback-prioritizer", category: "Product Management Tools", isPro: false },
  { id: 50, name: "Product Requirement Checklist", slug: "product-requirement-checklist", category: "Product Management Tools", isPro: false },
  { id: 51, name: "Product Launch Checklist", slug: "product-launch-checklist", category: "Product Management Tools", isPro: false },
  { id: 52, name: "Release Readiness Checklist", slug: "release-readiness-checklist", category: "Product Management Tools", isPro: false },
  { id: 53, name: "Product Go-To-Market Checklist", slug: "product-go-to-market-checklist", category: "Product Management Tools", isPro: false },
  { id: 54, name: "Product North Star Metric Builder", slug: "product-north-star-metric-builder", category: "Product Management Tools", isPro: false },
  { id: 55, name: "Product Metric Tree Builder", slug: "product-metric-tree-builder", category: "Product Management Tools", isPro: false },
  { id: 56, name: "Product Success Criteria Builder", slug: "product-success-criteria-builder", category: "Product Management Tools", isPro: false },
  { id: 57, name: "Product Review Template", slug: "product-review-template", category: "Product Management Tools", isPro: false },
  { id: 58, name: "Product Strategy Review", slug: "product-strategy-review", category: "Product Management Tools", isPro: false },
  { id: 59, name: "Product Roadmap Report", slug: "product-roadmap-report", category: "Product Management Tools", isPro: false },
  { id: 60, name: "Feature Prioritization Report", slug: "feature-prioritization-report", category: "Product Management Tools", isPro: false },

  // --- ⚡ 40 PRO / SAAS TOOLS (IDs 61-100 | isPro: true) ---
  { id: 61, name: "Product Management Workspace", slug: "product-management-workspace", category: "Product Management Tools", isPro: true },
  { id: 62, name: "Product Strategy Workspace", slug: "product-strategy-workspace", category: "Product Management Tools", isPro: true },
  { id: 63, name: "Product Discovery Workspace", slug: "product-discovery-workspace", category: "Product Management Tools", isPro: true },
  { id: 64, name: "Product Requirements Workspace", slug: "product-requirements-workspace", category: "Product Management Tools", isPro: true },
  { id: 65, name: "Product Roadmap Workspace", slug: "product-roadmap-workspace", category: "Product Management Tools", isPro: true },
  { id: 66, name: "Feature Management Workspace", slug: "feature-management-workspace", category: "Product Management Tools", isPro: true },
  { id: 67, name: "Product Backlog Workspace", slug: "product-backlog-workspace", category: "Product Management Tools", isPro: true },
  { id: 68, name: "Product Prioritization Workspace", slug: "product-prioritization-workspace", category: "Product Management Tools", isPro: true },
  { id: 69, name: "Product Opportunity Workspace", slug: "product-opportunity-workspace", category: "Product Management Tools", isPro: true },
  { id: 70, name: "Product Feedback Workspace", slug: "product-feedback-workspace", category: "Product Management Tools", isPro: true },
  { id: 71, name: "Customer Insight Workspace", slug: "customer-insight-workspace", category: "Product Management Tools", isPro: true },
  { id: 72, name: "Product Research Workspace", slug: "product-research-workspace", category: "Product Management Tools", isPro: true },
  { id: 73, name: "Product Hypothesis Workspace", slug: "product-hypothesis-workspace", category: "Product Management Tools", isPro: true },
  { id: 74, name: "Product Experiment Workspace", slug: "product-experiment-workspace", category: "Product Management Tools", isPro: true },
  { id: 75, name: "Product Decision Management", slug: "product-decision-management", category: "Product Management Tools", isPro: true },
  { id: 76, name: "Product Risk Management", slug: "product-risk-management", category: "Product Management Tools", isPro: true },
  { id: 77, name: "Product Dependency Management", slug: "product-dependency-management", category: "Product Management Tools", isPro: true },
  { id: 78, name: "Release Planning Workspace", slug: "release-planning-workspace", category: "Product Management Tools", isPro: true },
  { id: 79, name: "Launch Planning Workspace", slug: "launch-planning-workspace", category: "Product Management Tools", isPro: true },
  { id: 80, name: "Product KPI Dashboard", slug: "product-kpi-dashboard", category: "Product Management Tools", isPro: true },
  { id: 81, name: "Product Metrics Workspace", slug: "product-metrics-workspace", category: "Product Management Tools", isPro: true },
  { id: 82, name: "Product Portfolio Dashboard", slug: "product-portfolio-dashboard", category: "Product Management Tools", isPro: true },
  { id: 83, name: "Product Roadmap Dashboard", slug: "product-roadmap-dashboard", category: "Product Management Tools", isPro: true },
  { id: 84, name: "Feature Performance Dashboard", slug: "feature-performance-dashboard", category: "Product Management Tools", isPro: true },
  { id: 85, name: "Product Lifecycle Dashboard", slug: "product-lifecycle-dashboard", category: "Product Management Tools", isPro: true },
  { id: 86, name: "Product Planning Analytics", slug: "product-planning-analytics", category: "Product Management Tools", isPro: true },
  { id: 87, name: "Product Portfolio Analytics", slug: "product-portfolio-analytics", category: "Product Management Tools", isPro: true },
  { id: 88, name: "Product Feedback Analytics", slug: "product-feedback-analytics", category: "Product Management Tools", isPro: true },
  { id: 89, name: "Product Prioritization Analytics", slug: "product-prioritization-analytics", category: "Product Management Tools", isPro: true },
  { id: 90, name: "Product Data Importer", slug: "product-data-importer", category: "Product Management Tools", isPro: true },
  { id: 91, name: "Product Data Exporter", slug: "product-data-exporter", category: "Product Management Tools", isPro: true },
  { id: 92, name: "Product Management API", slug: "product-management-api", category: "Product Management Tools", isPro: true },
  { id: 93, name: "Product Workflow Automation", slug: "product-workflow-automation", category: "Product Management Tools", isPro: true },
  { id: 94, name: "Product Alert Engine", slug: "product-alert-engine", category: "Product Management Tools", isPro: true },
  { id: 95, name: "Product Documentation Workspace", slug: "product-documentation-workspace", category: "Product Management Tools", isPro: true },
  { id: 96, name: "Product Knowledge Base", slug: "product-knowledge-base", category: "Product Management Tools", isPro: true },
  { id: 97, name: "Product Intelligence Platform", slug: "product-intelligence-platform", category: "Product Management Tools", isPro: true },
  { id: 98, name: "Product Operations Platform", slug: "product-operations-platform", category: "Product Management Tools", isPro: true },
  { id: 99, name: "Enterprise Product Management Platform", slug: "enterprise-product-management-platform", category: "Product Management Tools", isPro: true },
  { id: 100, name: "Product Command Center", slug: "product-command-center", category: "Product Management Tools", isPro: true }
];