export interface Tool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const salesCrmToolsList: Tool[] = [
  // --- 🔥 PRIORITY 20 FREE TOOLS (isPro: false) ---
  { id: 1, name: "Sales Pipeline Velocity Calculator", slug: "sales-pipeline-velocity-calculator", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 2, name: "Sales Quota Attainment Calculator", slug: "sales-quota-attainment-calculator", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 3, name: "Lead Conversion Rate Calculator", slug: "lead-conversion-rate-calculator", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 4, name: "Sales Commission Calculator", slug: "sales-commission-calculator-crm", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 5, name: "Average Deal Size Calculator", slug: "average-deal-size-calculator", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 6, name: "Sales Win Rate Calculator", slug: "sales-win-rate-calculator", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 7, name: "Sales Cycle Length Calculator", slug: "sales-cycle-length-calculator", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 8, name: "Customer Acquisition Cost (CAC) Estimator", slug: "customer-acquisition-cost-cac-estimator", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 9, name: "Sales Ramp-Up Time Calculator", slug: "sales-ramp-up-time-calculator", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 10, name: "Inbound Lead Value Calculator", slug: "inbound-lead-value-calculator", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 11, name: "Outbound SDR Capacity Planner", slug: "outbound-sdr-capacity-planner", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 12, name: "Lead-to-Opportunity Ratio Calculator", slug: "lead-to-opportunity-ratio-calculator", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 13, name: "Opportunity-to-Close Rate Calculator", slug: "opportunity-to-close-rate-calculator", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 14, name: "Sales Discount Margin Impact Calculator", slug: "sales-discount-margin-impact-calculator", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 15, name: "Sales Rep Capacity Calculator", slug: "sales-rep-capacity-calculator", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 16, name: "Territory Quota Allocation Tool", slug: "territory-quota-allocation-tool", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 17, name: "Sales Churn Risk Estimator", slug: "sales-churn-risk-estimator", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 18, name: "Cold Email Response Rate Calculator", slug: "cold-email-response-rate-calculator", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 19, name: "Lead Score Matrix Generator", slug: "lead-score-matrix-generator", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 20, name: "Sales Meeting Prep Checklist", slug: "sales-meeting-prep-checklist", category: "Sales & CRM Operations Tools", isPro: false },

  // --- CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Annual Contract Value (ACV) Calculator", slug: "annual-contract-value-acv-calculator", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 22, name: "Total Contract Value (TCV) Calculator", slug: "total-contract-value-tcv-calculator", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 23, name: "B2B Sales Call Script Generator", slug: "b2b-sales-call-script-generator", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 24, name: "Sales Objection Handling Guide", slug: "sales-objection-handling-guide", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 25, name: "Discovery Call Checklist", slug: "discovery-call-checklist", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 26, name: "Sales Demo Feedback Sheet", slug: "sales-demo-feedback-sheet", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 27, name: "Sales Follow-Up Email Generator", slug: "sales-follow-up-email-generator", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 28, name: "Sales Activity Score Calculator", slug: "sales-activity-score-calculator", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 29, name: "Sales Lead Decay Calculator", slug: "sales-lead-decay-calculator", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 30, name: "Sales Incentive Plan Estimator", slug: "sales-incentive-plan-estimator", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 31, name: "Sales Stage Duration Tracker", slug: "sales-stage-duration-tracker", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 32, name: "Account Health Scorecard", slug: "account-health-scorecard-sales", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 33, name: "Sales Headcount Planning Calculator", slug: "sales-headcount-planning-calculator", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 34, name: "Pipeline Coverage Ratio Calculator", slug: "pipeline-coverage-ratio-calculator", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 35, name: "Sales Lead Velocity Rate (LVR)", slug: "sales-lead-velocity-rate-lvr", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 36, name: "Competitor Battlecard Generator", slug: "competitor-battlecard-generator", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 37, name: "MEDDIC Sales Qualifier Tool", slug: "meddic-sales-qualifier-tool", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 38, name: "BANT Qualification Calculator", slug: "bant-qualification-calculator", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 39, name: "Sales Pipeline Health Checker", slug: "sales-pipeline-health-checker", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 40, name: "Sales Discount Approvals Matrix", slug: "sales-discount-approvals-matrix", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 41, name: "Cold Call Success Rate Calculator", slug: "cold-call-success-rate-calculator", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 42, name: "Sales Revenue Forecast Estimator", slug: "sales-revenue-forecast-estimator", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 43, name: "SDR-to-AE Ratio Planner", slug: "sdr-to-ae-ratio-planner", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 44, name: "Deal Margin Health Calculator", slug: "deal-margin-health-calculator", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 45, name: "Contract Renewal Timeline Planner", slug: "contract-renewal-timeline-planner", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 46, name: "Sales Training ROI Calculator", slug: "sales-training-roi-calculator", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 47, name: "Sales Rep Performance Scorecard", slug: "sales-rep-performance-scorecard", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 48, name: "Channel Partner Margin Calculator", slug: "channel-partner-margin-calculator", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 49, name: "Key Account Review Template", slug: "key-account-review-template", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 50, name: "Sales Email Subject Line Grader", slug: "sales-email-subject-line-grader", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 51, name: "Sales SLA Tracker", slug: "sales-sla-tracker", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 52, name: "Sales Compensation Plan Checklist", slug: "sales-compensation-plan-checklist", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 53, name: "Sales Kickoff (SKO) Budget Planner", slug: "sales-kickoff-sko-budget-planner", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 54, name: "Customer Referral Incentive Calculator", slug: "customer-referral-incentive-calculator", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 55, name: "Lead Response Time Impact Calculator", slug: "lead-response-time-impact-calculator", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 56, name: "Sales Pipeline Stage Probability Matrix", slug: "sales-pipeline-stage-probability-matrix", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 57, name: "Account-Based Marketing (ABM) Account Scorer", slug: "account-based-marketing-abm-account-scorer", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 58, name: "Sales Opportunity Loss Analysis Tool", slug: "sales-opportunity-loss-analysis-tool", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 59, name: "Quarterly Sales Review Checklist", slug: "quarterly-sales-review-checklist", category: "Sales & CRM Operations Tools", isPro: false },
  { id: 60, name: "Sales Operations Audit Sheet", slug: "sales-operations-audit-sheet", category: "Sales & CRM Operations Tools", isPro: false },

  // --- ⚡ PRO / SAAS TOOLS (61-100) ---
  { id: 61, name: "Enterprise Sales Pipeline Workspace", slug: "enterprise-sales-pipeline-workspace", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 62, name: "Sales Revenue Intelligence Engine", slug: "sales-revenue-intelligence-engine", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 63, name: "AI Deal Score Predictor", slug: "ai-deal-score-predictor", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 64, name: "Automated Lead Routing Engine", slug: "automated-lead-routing-engine", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 65, name: "Enterprise Sales Territory Planner", slug: "enterprise-sales-territory-planner", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 66, name: "Sales Quota & Capacity Dashboard", slug: "sales-quota-capacity-dashboard", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 67, name: "AI Cold Outreach Personalizer", slug: "ai-cold-outreach-personalizer", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 68, name: "Multi-Tier Sales Commission Engine", slug: "multi-tier-sales-commission-engine", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 69, name: "Sales Opportunity Stage Automation", slug: "sales-opportunity-stage-automation", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 70, name: "CRM Data Hygiene & Enrichment Tool", slug: "crm-data-hygiene-enrichment-tool", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 71, name: "Real-Time Sales Forecasting Workspace", slug: "real-time-sales-forecasting-workspace", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 72, name: "Key Account Expansion Planner", slug: "key-account-expansion-planner", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 73, name: "Sales Activity & Cadence Optimizer", slug: "sales-activity-cadence-optimizer", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 74, name: "AI Sales Objection Assistant", slug: "ai-sales-objection-assistant", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 75, name: "Enterprise CPQ (Configure, Price, Quote) Tool", slug: "enterprise-cpq-configure-price-quote-tool", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 76, name: "Deal Slippage Risk Radar", slug: "deal-slippage-risk-radar", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 77, name: "Sales Team Performance Analytics", slug: "sales-team-performance-analytics", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 78, name: "Lead Intent Signal Analyzer", slug: "lead-intent-signal-analyzer", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 79, name: "B2B Sales Contract Lifecycle Manager", slug: "b2b-sales-contract-lifecycle-manager", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 80, name: "Sales Enablement Content Matrix", slug: "sales-enablement-content-matrix", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 81, name: "Channel Partner Revenue Dashboard", slug: "channel-partner-revenue-dashboard", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 82, name: "Inbound Lead SLA Monitoring Engine", slug: "inbound-lead-sla-monitoring-engine", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 83, name: "Sales Win/Loss Analytics Hub", slug: "sales-win-loss-analytics-hub", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 84, name: "Sales Compensation Dispute Manager", slug: "sales-compensation-dispute-manager", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 85, name: "Cross-Sell & Upsell Opportunity Finder", slug: "cross-sell-upsell-opportunity-finder", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 86, name: "Sales Coaching & Call Review Hub", slug: "sales-coaching-call-review-hub", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 87, name: "Executive Sales Dashboard Pro", slug: "executive-sales-dashboard-pro", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 88, name: "Enterprise Account Mapping Workspace", slug: "enterprise-account-mapping-workspace", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 89, name: "Sales Lead Deduplication Engine", slug: "sales-lead-deduplication-engine", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 90, name: "Sales Workflow Automation Builder", slug: "sales-workflow-automation-builder", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 91, name: "CRM Data Migration Tool", slug: "crm-data-migration-tool", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 92, name: "Sales Data Export & Integration Hub", slug: "sales-data-export-integration-hub", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 93, name: "Sales API Webhook Engine", slug: "sales-api-webhook-engine", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 94, name: "Sales Analytics Data Sync Engine", slug: "sales-analytics-data-sync-engine", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 95, name: "High-Value Deal Alert System", slug: "high-value-deal-alert-system", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 96, name: "Sales AI Copilot Workspace", slug: "sales-ai-copilot-workspace", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 97, name: "Enterprise Revenue Operations Platform", slug: "enterprise-revenue-operations-platform", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 98, name: "Sales Rep Gamification & Leaderboard Hub", slug: "sales-rep-gamification-leaderboard-hub", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 99, name: "Global Sales Operations Platform", slug: "global-sales-operations-platform", category: "Sales & CRM Operations Tools", isPro: true },
  { id: 100, name: "Revenue Command Center Pro", slug: "revenue-command-center-pro", category: "Sales & CRM Operations Tools", isPro: true }
];