export interface ShoppingTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const shoppingToolsList: ShoppingTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "Product Price Comparison", slug: "product-price-comparison", category: "Shopping Tools", isPro: false },
  { id: 2, name: "Discount Calculator", slug: "discount-calculator", category: "Shopping Tools", isPro: false },
  { id: 3, name: "Final Price Calculator", slug: "final-price-calculator", category: "Shopping Tools", isPro: false },
  { id: 4, name: "Shipping Cost Calculator", slug: "shipping-cost-calculator", category: "Shopping Tools", isPro: false },
  { id: 5, name: "Unit Price Calculator", slug: "unit-price-calculator", category: "Shopping Tools", isPro: false },
  { id: 6, name: "Cost Per Use Calculator", slug: "cost-per-use-calculator", category: "Shopping Tools", isPro: false },
  { id: 7, name: "Product Comparison Tool", slug: "product-comparison-tool", category: "Shopping Tools", isPro: false },
  { id: 8, name: "Product Feature Comparison", slug: "product-feature-comparison", category: "Shopping Tools", isPro: false },
  { id: 9, name: "Product Specification Comparison", slug: "product-specification-comparison", category: "Shopping Tools", isPro: false },
  { id: 10, name: "Review Summary Tool", slug: "review-summary-tool", category: "Shopping Tools", isPro: false },
  { id: 11, name: "Review Sentiment Analyzer", slug: "review-sentiment-analyzer", category: "Shopping Tools", isPro: false },
  { id: 12, name: "Product Review Analyzer", slug: "product-review-analyzer", category: "Shopping Tools", isPro: false },
  { id: 13, name: "Product Pros & Cons Generator", slug: "product-pros-and-cons-generator", category: "Shopping Tools", isPro: false },
  { id: 14, name: "Product Buying Checklist", slug: "product-buying-checklist", category: "Shopping Tools", isPro: false },
  { id: 15, name: "Shopping List Generator", slug: "shopping-list-generator", category: "Shopping Tools", isPro: false },
  { id: 16, name: "Clothing Size Converter", slug: "clothing-size-converter", category: "Shopping Tools", isPro: false },
  { id: 17, name: "Shoe Size Converter", slug: "shoe-size-converter", category: "Shopping Tools", isPro: false },
  { id: 18, name: "Shopping Budget Tracker", slug: "shopping-budget-tracker", category: "Shopping Tools", isPro: false },
  { id: 19, name: "Price Difference Calculator", slug: "price-difference-calculator", category: "Shopping Tools", isPro: false },
  { id: 20, name: "Sale Price Calculator", slug: "sale-price-calculator", category: "Shopping Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Coupon Savings Calculator", slug: "coupon-savings-calculator", category: "Shopping Tools", isPro: false },
  { id: 22, name: "Tax-Inclusive Price Calculator", slug: "tax-inclusive-price-calculator", category: "Shopping Tools", isPro: false },
  { id: 23, name: "Tax-Exclusive Price Calculator", slug: "tax-exclusive-price-calculator", category: "Shopping Tools", isPro: false },
  { id: 24, name: "Total Purchase Cost Calculator", slug: "total-purchase-cost-calculator", category: "Shopping Tools", isPro: false },
  { id: 25, name: "Price Per Weight Calculator", slug: "price-per-weight-calculator", category: "Shopping Tools", isPro: false },
  { id: 26, name: "Price Per Volume Calculator", slug: "price-per-volume-calculator", category: "Shopping Tools", isPro: false },
  { id: 27, name: "Price Per Item Calculator", slug: "price-per-item-calculator", category: "Shopping Tools", isPro: false },
  { id: 28, name: "Subscription Cost Calculator", slug: "subscription-cost-calculator", category: "Shopping Tools", isPro: false },
  { id: 29, name: "Monthly Purchase Cost Calculator", slug: "monthly-purchase-cost-calculator", category: "Shopping Tools", isPro: false },
  { id: 30, name: "Annual Purchase Cost Calculator", slug: "annual-purchase-cost-calculator", category: "Shopping Tools", isPro: false },
  { id: 31, name: "Buy vs Subscribe Calculator", slug: "buy-vs-subscribe-calculator", category: "Shopping Tools", isPro: false },
  { id: 32, name: "New vs Used Price Comparison", slug: "new-vs-used-price-comparison", category: "Shopping Tools", isPro: false },
  { id: 33, name: "Product Size Comparison", slug: "product-size-comparison", category: "Shopping Tools", isPro: false },
  { id: 34, name: "Product Weight Comparison", slug: "product-weight-comparison", category: "Shopping Tools", isPro: false },
  { id: 35, name: "Product Value Score Calculator", slug: "product-value-score-calculator", category: "Shopping Tools", isPro: false },
  { id: 36, name: "Product Rating Calculator", slug: "product-rating-calculator", category: "Shopping Tools", isPro: false },
  { id: 37, name: "Review Score Calculator", slug: "review-score-calculator", category: "Shopping Tools", isPro: false },
  { id: 38, name: "Review Count Analyzer", slug: "review-count-analyzer", category: "Shopping Tools", isPro: false },
  { id: 39, name: "Product Research Checklist", slug: "product-research-checklist", category: "Shopping Tools", isPro: false },
  { id: 40, name: "Gift Budget Calculator", slug: "gift-budget-calculator", category: "Shopping Tools", isPro: false },
  { id: 41, name: "Gift Cost Splitter", slug: "gift-cost-splitter", category: "Shopping Tools", isPro: false },
  { id: 42, name: "Grocery List Generator", slug: "grocery-list-generator", category: "Shopping Tools", isPro: false },
  { id: 43, name: "Household Shopping List", slug: "household-shopping-list", category: "Shopping Tools", isPro: false },
  { id: 44, name: "Moving Shopping Checklist", slug: "moving-shopping-checklist", category: "Shopping Tools", isPro: false },
  { id: 45, name: "Baby Shopping Checklist", slug: "baby-shopping-checklist", category: "Shopping Tools", isPro: false },
  { id: 46, name: "Wedding Shopping Checklist", slug: "wedding-shopping-checklist", category: "Shopping Tools", isPro: false },
  { id: 47, name: "Travel Shopping Checklist", slug: "travel-shopping-checklist", category: "Shopping Tools", isPro: false },
  { id: 48, name: "Back-to-School Shopping List", slug: "back-to-school-shopping-list", category: "Shopping Tools", isPro: false },
  { id: 49, name: "Home Improvement Shopping List", slug: "home-improvement-shopping-list", category: "Shopping Tools", isPro: false },
  { id: 50, name: "Electronics Buying Checklist", slug: "electronics-buying-checklist", category: "Shopping Tools", isPro: false },
  { id: 51, name: "Laptop Buying Checklist", slug: "laptop-buying-checklist", category: "Shopping Tools", isPro: false },
  { id: 52, name: "Phone Buying Checklist", slug: "phone-buying-checklist", category: "Shopping Tools", isPro: false },
  { id: 53, name: "Car Buying Checklist", slug: "car-buying-checklist", category: "Shopping Tools", isPro: false },
  { id: 54, name: "Appliance Buying Checklist", slug: "appliance-buying-checklist", category: "Shopping Tools", isPro: false },
  { id: 55, name: "Furniture Buying Checklist", slug: "furniture-buying-checklist", category: "Shopping Tools", isPro: false },
  { id: 56, name: "Ring Size Converter", slug: "ring-size-converter", category: "Shopping Tools", isPro: false },
  { id: 57, name: "Clothing Size Comparison", slug: "clothing-size-comparison", category: "Shopping Tools", isPro: false },
  { id: 58, name: "Package Weight Calculator", slug: "package-weight-calculator", category: "Shopping Tools", isPro: false },
  { id: 59, name: "Order Cost Splitter", slug: "order-cost-splitter", category: "Shopping Tools", isPro: false },
  { id: 60, name: "Purchase Decision Calculator", slug: "purchase-decision-calculator", category: "Shopping Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Price Tracking Dashboard", slug: "price-tracking-dashboard", category: "Shopping Tools", isPro: true },
  { id: 62, name: "Price Drop Alert System", slug: "price-drop-alert-system", category: "Shopping Tools", isPro: true },
  { id: 63, name: "Historical Price Analyzer", slug: "historical-price-analyzer", category: "Shopping Tools", isPro: true },
  { id: 64, name: "Product Price History Chart", slug: "product-price-history-chart", category: "Shopping Tools", isPro: true },
  { id: 65, name: "Price Trend Analyzer", slug: "price-trend-analyzer", category: "Shopping Tools", isPro: true },
  { id: 66, name: "Deal Quality Analyzer", slug: "deal-quality-analyzer", category: "Shopping Tools", isPro: true },
  { id: 67, name: "Deal Score Engine", slug: "deal-score-engine", category: "Shopping Tools", isPro: true },
  { id: 68, name: "Coupon Optimization Engine", slug: "coupon-optimization-engine", category: "Shopping Tools", isPro: true },
  { id: 69, name: "Shopping Savings Optimizer", slug: "shopping-savings-optimizer", category: "Shopping Tools", isPro: true },
  { id: 70, name: "Product Value Intelligence", slug: "product-value-intelligence", category: "Shopping Tools", isPro: true },
  { id: 71, name: "Product Comparison Engine", slug: "product-comparison-engine", category: "Shopping Tools", isPro: true },
  { id: 72, name: "Multi-Store Comparison Workspace", slug: "multi-store-comparison-workspace", category: "Shopping Tools", isPro: true },
  { id: 73, name: "Product Research Workspace", slug: "product-research-workspace", category: "Shopping Tools", isPro: true },
  { id: 74, name: "Buying Decision Intelligence", slug: "buying-decision-intelligence", category: "Shopping Tools", isPro: true },
  { id: 75, name: "Review Intelligence Dashboard", slug: "review-intelligence-dashboard", category: "Shopping Tools", isPro: true },
  { id: 76, name: "Review Authenticity Analyzer", slug: "review-authenticity-analyzer", category: "Shopping Tools", isPro: true },
  { id: 77, name: "Review Quality Analyzer", slug: "review-quality-analyzer", category: "Shopping Tools", isPro: true },
  { id: 78, name: "Review Trend Analyzer", slug: "review-trend-analyzer", category: "Shopping Tools", isPro: true },
  { id: 79, name: "Product Sentiment Dashboard", slug: "product-sentiment-dashboard", category: "Shopping Tools", isPro: true },
  { id: 80, name: "Product Feature Intelligence", slug: "product-feature-intelligence", category: "Shopping Tools", isPro: true },
  { id: 81, name: "Competitor Product Monitor", slug: "competitor-product-monitor", category: "Shopping Tools", isPro: true },
  { id: 82, name: "Product Availability Monitor", slug: "product-availability-monitor", category: "Shopping Tools", isPro: true },
  { id: 83, name: "Stock Availability Tracker", slug: "stock-availability-tracker", category: "Shopping Tools", isPro: true },
  { id: 84, name: "Restock Alert System", slug: "restock-alert-system", category: "Shopping Tools", isPro: true },
  { id: 85, name: "Shopping Price Monitor", slug: "shopping-price-monitor", category: "Shopping Tools", isPro: true },
  { id: 86, name: "Shopping List Intelligence", slug: "shopping-list-intelligence", category: "Shopping Tools", isPro: true },
  { id: 87, name: "Household Budget Shopping Planner", slug: "household-budget-shopping-planner", category: "Shopping Tools", isPro: true },
  { id: 88, name: "Subscription Expense Analyzer", slug: "subscription-expense-analyzer", category: "Shopping Tools", isPro: true },
  { id: 89, name: "Purchase History Analyzer", slug: "purchase-history-analyzer", category: "Shopping Tools", isPro: true },
  { id: 90, name: "Spending Category Analyzer", slug: "spending-category-analyzer", category: "Shopping Tools", isPro: true },
  { id: 91, name: "E-commerce Product Research Workspace", slug: "e-commerce-product-research-workspace", category: "Shopping Tools", isPro: true },
  { id: 92, name: "Affiliate Product Research Tool", slug: "affiliate-product-research-tool", category: "Shopping Tools", isPro: true },
  { id: 93, name: "Affiliate Product Comparison Builder", slug: "affiliate-product-comparison-builder", category: "Shopping Tools", isPro: true },
  { id: 94, name: "Product Recommendation Engine", slug: "product-recommendation-engine", category: "Shopping Tools", isPro: true },
  { id: 95, name: "Personalized Shopping Workspace", slug: "personalized-shopping-workspace", category: "Shopping Tools", isPro: true },
  { id: 96, name: "Shopping Deal Intelligence Platform", slug: "shopping-deal-intelligence-platform", category: "Shopping Tools", isPro: true },
  { id: 97, name: "Retail Price Intelligence Dashboard", slug: "retail-price-intelligence-dashboard", category: "Shopping Tools", isPro: true },
  { id: 98, name: "E-commerce Competitive Intelligence", slug: "e-commerce-competitive-intelligence", category: "Shopping Tools", isPro: true },
  { id: 99, name: "Consumer Purchase Intelligence Workspace", slug: "consumer-purchase-intelligence-workspace", category: "Shopping Tools", isPro: true },
  { id: 100, name: "Shopping Decision Command Center", slug: "shopping-decision-command-center", category: "Shopping Tools", isPro: true }
];