export interface SocialMediaTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const socialToolsList: SocialMediaTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "Social Media Post Generator", slug: "social-media-post-generator", category: "Social Media Tools", isPro: false },
  { id: 2, name: "Social Caption Generator", slug: "social-caption-generator", category: "Social Media Tools", isPro: false },
  { id: 3, name: "Social Hashtag Generator", slug: "social-hashtag-generator", category: "Social Media Tools", isPro: false },
  { id: 4, name: "Social Content Idea Generator", slug: "social-content-idea-generator", category: "Social Media Tools", isPro: false },
  { id: 5, name: "Social Content Calendar", slug: "social-content-calendar", category: "Social Media Tools", isPro: false },
  { id: 6, name: "Social Media Planner", slug: "social-media-planner", category: "Social Media Tools", isPro: false },
  { id: 7, name: "Social Character Counter", slug: "social-character-counter", category: "Social Media Tools", isPro: false },
  { id: 8, name: "Instagram Caption Generator", slug: "instagram-caption-generator", category: "Social Media Tools", isPro: false },
  { id: 9, name: "Instagram Hashtag Generator", slug: "instagram-hashtag-generator", category: "Social Media Tools", isPro: false },
  { id: 10, name: "Instagram Bio Generator", slug: "instagram-bio-generator", category: "Social Media Tools", isPro: false },
  { id: 11, name: "Instagram Reel Idea Generator", slug: "instagram-reel-idea-generator", category: "Social Media Tools", isPro: false },
  { id: 12, name: "Instagram Content Planner", slug: "instagram-content-planner", category: "Social Media Tools", isPro: false },
  { id: 13, name: "TikTok Caption Generator", slug: "tiktok-caption-generator", category: "Social Media Tools", isPro: false },
  { id: 14, name: "TikTok Hashtag Generator", slug: "tiktok-hashtag-generator", category: "Social Media Tools", isPro: false },
  { id: 15, name: "TikTok Video Idea Generator", slug: "tiktok-video-idea-generator", category: "Social Media Tools", isPro: false },
  { id: 16, name: "TikTok Hook Generator", slug: "tiktok-hook-generator", category: "Social Media Tools", isPro: false },
  { id: 17, name: "TikTok Script Generator", slug: "tiktok-script-generator", category: "Social Media Tools", isPro: false },
  { id: 18, name: "LinkedIn Post Generator", slug: "linkedin-post-generator", category: "Social Media Tools", isPro: false },
  { id: 19, name: "LinkedIn Headline Generator", slug: "linkedin-headline-generator", category: "Social Media Tools", isPro: false },
  { id: 20, name: "LinkedIn About Generator", slug: "linkedin-about-generator", category: "Social Media Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Social Bio Generator", slug: "social-bio-generator", category: "Social Media Tools", isPro: false },
  { id: 22, name: "Social Username Generator", slug: "social-username-generator", category: "Social Media Tools", isPro: false },
  { id: 23, name: "Social Hook Generator", slug: "social-hook-generator", category: "Social Media Tools", isPro: false },
  { id: 24, name: "Social Headline Generator", slug: "social-headline-generator", category: "Social Media Tools", isPro: false },
  { id: 25, name: "Social CTA Generator", slug: "social-cta-generator", category: "Social Media Tools", isPro: false },
  { id: 26, name: "Social Post Scheduler", slug: "social-post-scheduler", category: "Social Media Tools", isPro: false },
  { id: 27, name: "Instagram Username Generator", slug: "instagram-username-generator", category: "Social Media Tools", isPro: false },
  { id: 28, name: "Instagram Reel Caption Generator", slug: "instagram-reel-caption-generator", category: "Social Media Tools", isPro: false },
  { id: 29, name: "Instagram Story Idea Generator", slug: "instagram-story-idea-generator", category: "Social Media Tools", isPro: false },
  { id: 30, name: "Instagram Carousel Idea Generator", slug: "instagram-carousel-idea-generator", category: "Social Media Tools", isPro: false },
  { id: 31, name: "Instagram Engagement Calculator", slug: "instagram-engagement-calculator", category: "Social Media Tools", isPro: false },
  { id: 32, name: "Instagram Hashtag Analyzer", slug: "instagram-hashtag-analyzer", category: "Social Media Tools", isPro: false },
  { id: 33, name: "Instagram Profile Analyzer", slug: "instagram-profile-analyzer", category: "Social Media Tools", isPro: false },
  { id: 34, name: "Instagram Post Preview", slug: "instagram-post-preview", category: "Social Media Tools", isPro: false },
  { id: 35, name: "Instagram Grid Planner", slug: "instagram-grid-planner", category: "Social Media Tools", isPro: false },
  { id: 36, name: "Instagram Name Generator", slug: "instagram-name-generator", category: "Social Media Tools", isPro: false },
  { id: 37, name: "TikTok Bio Generator", slug: "tiktok-bio-generator", category: "Social Media Tools", isPro: false },
  { id: 38, name: "TikTok Username Generator", slug: "tiktok-username-generator", category: "Social Media Tools", isPro: false },
  { id: 39, name: "TikTok Engagement Calculator", slug: "tiktok-engagement-calculator", category: "Social Media Tools", isPro: false },
  { id: 40, name: "TikTok Content Planner", slug: "tiktok-content-planner", category: "Social Media Tools", isPro: false },
  { id: 41, name: "TikTok Profile Analyzer", slug: "tiktok-profile-analyzer", category: "Social Media Tools", isPro: false },
  { id: 42, name: "Facebook Post Generator", slug: "facebook-post-generator", category: "Social Media Tools", isPro: false },
  { id: 43, name: "Facebook Bio Generator", slug: "facebook-bio-generator", category: "Social Media Tools", isPro: false },
  { id: 44, name: "Facebook Ad Copy Generator", slug: "facebook-ad-copy-generator", category: "Social Media Tools", isPro: false },
  { id: 45, name: "Facebook Engagement Calculator", slug: "facebook-engagement-calculator", category: "Social Media Tools", isPro: false },
  { id: 46, name: "Facebook Content Planner", slug: "facebook-content-planner", category: "Social Media Tools", isPro: false },
  { id: 47, name: "LinkedIn Bio Generator", slug: "linkedin-bio-generator", category: "Social Media Tools", isPro: false },
  { id: 48, name: "LinkedIn Content Idea Generator", slug: "linkedin-content-idea-generator", category: "Social Media Tools", isPro: false },
  { id: 49, name: "LinkedIn Hook Generator", slug: "linkedin-hook-generator", category: "Social Media Tools", isPro: false },
  { id: 50, name: "LinkedIn Post Formatter", slug: "linkedin-post-formatter", category: "Social Media Tools", isPro: false },
  { id: 51, name: "LinkedIn Engagement Calculator", slug: "linkedin-engagement-calculator", category: "Social Media Tools", isPro: false },
  { id: 52, name: "LinkedIn Profile Analyzer", slug: "linkedin-profile-analyzer", category: "Social Media Tools", isPro: false },
  { id: 53, name: "X Post Generator", slug: "x-post-generator", category: "Social Media Tools", isPro: false },
  { id: 54, name: "X Thread Generator", slug: "x-thread-generator", category: "Social Media Tools", isPro: false },
  { id: 55, name: "X Bio Generator", slug: "x-bio-generator", category: "Social Media Tools", isPro: false },
  { id: 56, name: "X Username Generator", slug: "x-username-generator", category: "Social Media Tools", isPro: false },
  { id: 57, name: "X Hashtag Generator", slug: "x-hashtag-generator", category: "Social Media Tools", isPro: false },
  { id: 58, name: "X Engagement Calculator", slug: "x-engagement-calculator", category: "Social Media Tools", isPro: false },
  { id: 59, name: "X Thread Formatter", slug: "x-thread-formatter", category: "Social Media Tools", isPro: false },
  { id: 60, name: "X Character Counter", slug: "x-character-counter", category: "Social Media Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-85) ---
  { id: 61, name: "Social Media Audit Tool", slug: "social-media-audit-tool", category: "Social Media Tools", isPro: true },
  { id: 62, name: "Social Engagement Rate Analyzer", slug: "social-engagement-rate-analyzer", category: "Social Media Tools", isPro: true },
  { id: 63, name: "Social Growth Rate Calculator", slug: "social-growth-rate-calculator", category: "Social Media Tools", isPro: true },
  { id: 64, name: "Social Media ROI Calculator", slug: "social-media-roi-calculator", category: "Social Media Tools", isPro: true },
  { id: 65, name: "Social Competitor Analyzer", slug: "social-competitor-analyzer", category: "Social Media Tools", isPro: true },
  { id: 66, name: "Social Content Performance Analyzer", slug: "social-content-performance-analyzer", category: "Social Media Tools", isPro: true },
  { id: 67, name: "Social Posting Time Analyzer", slug: "social-posting-time-analyzer", category: "Social Media Tools", isPro: true },
  { id: 68, name: "Hashtag Competition Analyzer", slug: "hashtag-competition-analyzer", category: "Social Media Tools", isPro: true },
  { id: 69, name: "Hashtag Research Dashboard", slug: "hashtag-research-dashboard", category: "Social Media Tools", isPro: true },
  { id: 70, name: "Social Trend Analyzer", slug: "social-trend-analyzer", category: "Social Media Tools", isPro: true },
  { id: 71, name: "Content Repurposing Tool", slug: "content-repurposing-tool", category: "Social Media Tools", isPro: true },
  { id: 72, name: "Cross-Platform Content Converter", slug: "cross-platform-content-converter", category: "Social Media Tools", isPro: true },
  { id: 73, name: "Long-Form to Social Post Converter", slug: "long-form-to-social-post-converter", category: "Social Media Tools", isPro: true },
  { id: 74, name: "Blog to Social Posts Converter", slug: "blog-to-social-posts-converter", category: "Social Media Tools", isPro: true },
  { id: 75, name: "Video to Social Content Planner", slug: "video-to-social-content-planner", category: "Social Media Tools", isPro: true },
  { id: 76, name: "Podcast to Social Content Planner", slug: "podcast-to-social-content-planner", category: "Social Media Tools", isPro: true },
  { id: 77, name: "Social Media Campaign Planner", slug: "social-media-campaign-planner", category: "Social Media Tools", isPro: true },
  { id: 78, name: "Influencer Rate Calculator", slug: "influencer-rate-calculator", category: "Social Media Tools", isPro: true },
  { id: 79, name: "Influencer Campaign Calculator", slug: "influencer-campaign-calculator", category: "Social Media Tools", isPro: true },
  { id: 80, name: "Social Media Reporting Generator", slug: "social-media-reporting-generator", category: "Social Media Tools", isPro: true },
  { id: 81, name: "Client Report Generator", slug: "client-report-generator", category: "Social Media Tools", isPro: true },
  { id: 82, name: "Agency Social Media Dashboard", slug: "agency-social-media-dashboard", category: "Social Media Tools", isPro: true },
  { id: 83, name: "Multi-Platform Content Workspace", slug: "multi-platform-content-workspace", category: "Social Media Tools", isPro: true },
  { id: 84, name: "Viral Content Analyzer", slug: "viral-content-analyzer", category: "Social Media Tools", isPro: true },
  { id: 85, name: "Social Media KPI Dashboard", slug: "social-media-kpi-dashboard", category: "Social Media Tools", isPro: true },

  // --- REMAINING PRO LEVEL TOOLS (86-100) ---
  { id: 86, name: "Social Media Analytics Dashboard", slug: "social-media-analytics-dashboard", category: "Social Media Tools", isPro: true },
  { id: 87, name: "Social Reach Calculator", slug: "social-reach-calculator", category: "Social Media Tools", isPro: true },
  { id: 88, name: "Social Impressions Calculator", slug: "social-impressions-calculator", category: "Social Media Tools", isPro: true },
  { id: 89, name: "Social Engagement Calculator", slug: "social-engagement-calculator", category: "Social Media Tools", isPro: true },
  { id: 90, name: "Social Profile Audit", slug: "social-profile-audit", category: "Social Media Tools", isPro: true },
  { id: 91, name: "Social Competitor Benchmarking", slug: "social-competitor-benchmarking", category: "Social Media Tools", isPro: true },
  { id: 92, name: "Social Content Gap Analyzer", slug: "social-content-gap-analyzer", category: "Social Media Tools", isPro: true },
  { id: 93, name: "Social Best Time Predictor", slug: "social-best-time-predictor", category: "Social Media Tools", isPro: true },
  { id: 94, name: "Social Hashtag Performance Analyzer", slug: "social-hashtag-performance-analyzer", category: "Social Media Tools", isPro: true },
  { id: 95, name: "Hashtag Cluster Generator", slug: "hashtag-cluster-generator", category: "Social Media Tools", isPro: true },
  { id: 96, name: "Viral Hook Analyzer", slug: "viral-hook-analyzer", category: "Social Media Tools", isPro: true },
  { id: 97, name: "Social Media Campaign ROI Calculator", slug: "social-media-campaign-roi-calculator", category: "Social Media Tools", isPro: true },
  { id: 98, name: "Influencer Engagement Calculator", slug: "influencer-engagement-calculator", category: "Social Media Tools", isPro: true },
  { id: 99, name: "Sponsorship Rate Calculator", slug: "sponsorship-rate-calculator", category: "Social Media Tools", isPro: true },
  { id: 100, name: "Brand Deal Calculator", slug: "brand-deal-calculator", category: "Social Media Tools", isPro: true },
];