export interface SportsTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const sportsToolsList: SportsTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "Win Percentage Calculator", slug: "win-percentage-calculator", category: "Sports Tools", isPro: false },
  { id: 2, name: "League Points Calculator", slug: "league-points-calculator", category: "Sports Tools", isPro: false },
  { id: 3, name: "Goal Difference Calculator", slug: "goal-difference-calculator", category: "Sports Tools", isPro: false },
  { id: 4, name: "Run Rate Calculator", slug: "run-rate-calculator", category: "Sports Tools", isPro: false },
  { id: 5, name: "Net Run Rate Calculator", slug: "net-run-rate-calculator", category: "Sports Tools", isPro: false },
  { id: 6, name: "Required Run Rate Calculator", slug: "required-run-rate-calculator", category: "Sports Tools", isPro: false },
  { id: 7, name: "Batting Average Calculator", slug: "batting-average-calculator", category: "Sports Tools", isPro: false },
  { id: 8, name: "Strike Rate Calculator", slug: "strike-rate-calculator", category: "Sports Tools", isPro: false },
  { id: 9, name: "Economy Rate Calculator", slug: "economy-rate-calculator", category: "Sports Tools", isPro: false },
  { id: 10, name: "Golf Handicap Calculator", slug: "golf-handicap-calculator", category: "Sports Tools", isPro: false },
  { id: 11, name: "Player Ranking Calculator", slug: "player-ranking-calculator", category: "Sports Tools", isPro: false },
  { id: 12, name: "Team Ranking Calculator", slug: "team-ranking-calculator", category: "Sports Tools", isPro: false },
  { id: 13, name: "Tournament Bracket Generator", slug: "tournament-bracket-generator", category: "Sports Tools", isPro: false },
  { id: 14, name: "League Fixture Generator", slug: "league-fixture-generator", category: "Sports Tools", isPro: false },
  { id: 15, name: "Round Robin Generator", slug: "round-robin-generator", category: "Sports Tools", isPro: false },
  { id: 16, name: "Sports Schedule Generator", slug: "sports-schedule-generator", category: "Sports Tools", isPro: false },
  { id: 17, name: "Player Performance Dashboard", slug: "player-performance-dashboard", category: "Sports Tools", isPro: true },
  { id: 18, name: "Team Performance Dashboard", slug: "team-performance-dashboard", category: "Sports Tools", isPro: true },
  { id: 19, name: "Player Comparison Engine", slug: "player-comparison-engine", category: "Sports Tools", isPro: true },
  { id: 20, name: "Sports Statistics Analyzer", slug: "sports-statistics-analyzer", category: "Sports Tools", isPro: true },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Sports Score Calculator", slug: "sports-score-calculator", category: "Sports Tools", isPro: false },
  { id: 22, name: "Winning Percentage Calculator", slug: "winning-percentage-calculator", category: "Sports Tools", isPro: false },
  { id: 23, name: "Team Points Calculator", slug: "team-points-calculator", category: "Sports Tools", isPro: false },
  { id: 24, name: "Bowling Average Calculator", slug: "bowling-average-calculator", category: "Sports Tools", isPro: false },
  { id: 25, name: "Cricket Run Rate Calculator", slug: "cricket-run-rate-calculator", category: "Sports Tools", isPro: false },
  { id: 26, name: "Cricket Strike Rate Calculator", slug: "cricket-strike-rate-calculator", category: "Sports Tools", isPro: false },
  { id: 27, name: "Cricket Required Run Rate Calculator", slug: "cricket-required-run-rate-calculator", category: "Sports Tools", isPro: false },
  { id: 28, name: "Baseball Batting Average Calculator", slug: "baseball-batting-average-calculator", category: "Sports Tools", isPro: false },
  { id: 29, name: "Baseball ERA Calculator", slug: "baseball-era-calculator", category: "Sports Tools", isPro: false },
  { id: 30, name: "Baseball WHIP Calculator", slug: "baseball-whip-calculator", category: "Sports Tools", isPro: false },
  { id: 31, name: "Basketball Shooting Percentage Calculator", slug: "basketball-shooting-percentage-calculator", category: "Sports Tools", isPro: false },
  { id: 32, name: "Basketball Free Throw Percentage Calculator", slug: "basketball-free-throw-percentage-calculator", category: "Sports Tools", isPro: false },
  { id: 33, name: "Basketball 3-Point Percentage Calculator", slug: "basketball-3-point-percentage-calculator", category: "Sports Tools", isPro: false },
  { id: 34, name: "Basketball Player Efficiency Calculator", slug: "basketball-player-efficiency-calculator", category: "Sports Tools", isPro: false },
  { id: 35, name: "Football Completion Percentage Calculator", slug: "football-completion-percentage-calculator", category: "Sports Tools", isPro: false },
  { id: 36, name: "Football Passer Rating Calculator", slug: "football-passer-rating-calculator", category: "Sports Tools", isPro: false },
  { id: 37, name: "Soccer Win Probability Calculator", slug: "soccer-win-probability-calculator", category: "Sports Tools", isPro: false },
  { id: 38, name: "Soccer Goal Difference Calculator", slug: "soccer-goal-difference-calculator", category: "Sports Tools", isPro: false },
  { id: 39, name: "Tennis Win Percentage Calculator", slug: "tennis-win-percentage-calculator", category: "Sports Tools", isPro: false },
  { id: 40, name: "Tennis Ranking Points Calculator", slug: "tennis-ranking-points-calculator", category: "Sports Tools", isPro: false },
  { id: 41, name: "Golf Score Calculator", slug: "golf-score-calculator", category: "Sports Tools", isPro: false },
  { id: 42, name: "Golf Stableford Calculator", slug: "golf-stableford-calculator", category: "Sports Tools", isPro: false },
  { id: 43, name: "Golf Distance Calculator", slug: "golf-distance-calculator", category: "Sports Tools", isPro: false },
  { id: 44, name: "Golf Pace of Play Calculator", slug: "golf-pace-of-play-calculator", category: "Sports Tools", isPro: false },
  { id: 45, name: "Bowling Strike Percentage Calculator", slug: "bowling-strike-percentage-calculator", category: "Sports Tools", isPro: false },
  { id: 46, name: "Volleyball Rotation Planner", slug: "volleyball-rotation-planner", category: "Sports Tools", isPro: false },
  { id: 47, name: "Volleyball Score Calculator", slug: "volleyball-score-calculator", category: "Sports Tools", isPro: false },
  { id: 48, name: "Badminton Score Calculator", slug: "badminton-score-calculator", category: "Sports Tools", isPro: false },
  { id: 49, name: "Table Tennis Score Calculator", slug: "table-tennis-score-calculator", category: "Sports Tools", isPro: false },
  { id: 50, name: "Tennis Score Calculator", slug: "tennis-score-calculator", category: "Sports Tools", isPro: false },
  { id: 51, name: "Tennis Set Calculator", slug: "tennis-set-calculator", category: "Sports Tools", isPro: false },
  { id: 52, name: "Rugby Score Calculator", slug: "rugby-score-calculator", category: "Sports Tools", isPro: false },
  { id: 53, name: "Hockey Score Calculator", slug: "hockey-score-calculator", category: "Sports Tools", isPro: false },
  { id: 54, name: "Knockout Bracket Generator", slug: "knockout-bracket-generator", category: "Sports Tools", isPro: false },
  { id: 55, name: "Match Countdown", slug: "match-countdown", category: "Sports Tools", isPro: false },
  { id: 56, name: "Game Duration Calculator", slug: "game-duration-calculator", category: "Sports Tools", isPro: false },
  { id: 57, name: "Sports Training Timer", slug: "sports-training-timer", category: "Sports Tools", isPro: false },
  { id: 58, name: "Athlete Age Calculator", slug: "athlete-age-calculator", category: "Sports Tools", isPro: false },
  { id: 59, name: "Sports Pace Calculator", slug: "sports-pace-calculator", category: "Sports Tools", isPro: false },
  { id: 60, name: "Team Statistics Calculator", slug: "team-statistics-calculator", category: "Sports Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Advanced Team Analytics", slug: "advanced-team-analytics", category: "Sports Tools", isPro: true },
  { id: 62, name: "Match Performance Analyzer", slug: "match-performance-analyzer", category: "Sports Tools", isPro: true },
  { id: 63, name: "Tournament Management Workspace", slug: "tournament-management-workspace", category: "Sports Tools", isPro: true },
  { id: 64, name: "League Management Workspace", slug: "league-management-workspace", category: "Sports Tools", isPro: true },
  { id: 65, name: "Fixture Optimization Engine", slug: "fixture-optimization-engine", category: "Sports Tools", isPro: true },
  { id: 66, name: "Sports Schedule Optimization", slug: "sports-schedule-optimization", category: "Sports Tools", isPro: true },
  { id: 67, name: "Team Ranking Engine", slug: "team-ranking-engine", category: "Sports Tools", isPro: true },
  { id: 68, name: "Player Ranking Engine", slug: "player-ranking-engine", category: "Sports Tools", isPro: true },
  { id: 69, name: "Athlete Performance Analytics", slug: "athlete-performance-analytics", category: "Sports Tools", isPro: true },
  { id: 70, name: "Training Load Analyzer", slug: "training-load-analyzer", category: "Sports Tools", isPro: true },
  { id: 71, name: "Athlete Workload Dashboard", slug: "athlete-workload-dashboard", category: "Sports Tools", isPro: true },
  { id: 72, name: "Match Statistics Dashboard", slug: "match-statistics-dashboard", category: "Sports Tools", isPro: true },
  { id: 73, name: "Game-by-Game Performance Analyzer", slug: "game-by-game-performance-analyzer", category: "Sports Tools", isPro: true },
  { id: 74, name: "Season Performance Dashboard", slug: "season-performance-dashboard", category: "Sports Tools", isPro: true },
  { id: 75, name: "Sports Data Import Workspace", slug: "sports-data-import-workspace", category: "Sports Tools", isPro: true },
  { id: 76, name: "Sports CSV Analyzer", slug: "sports-csv-analyzer", category: "Sports Tools", isPro: true },
  { id: 77, name: "Sports Statistics Report Generator", slug: "sports-statistics-report-generator", category: "Sports Tools", isPro: true },
  { id: 78, name: "Team Roster Management", slug: "team-roster-management", category: "Sports Tools", isPro: true },
  { id: 79, name: "Player Roster Management", slug: "player-roster-management", category: "Sports Tools", isPro: true },
  { id: 80, name: "Coach Planning Workspace", slug: "coach-planning-workspace", category: "Sports Tools", isPro: true },
  { id: 81, name: "Training Session Planner", slug: "training-session-planner", category: "Sports Tools", isPro: true },
  { id: 82, name: "Tournament Operations Dashboard", slug: "tournament-operations-dashboard", category: "Sports Tools", isPro: true },
  { id: 83, name: "League Operations Dashboard", slug: "league-operations-dashboard", category: "Sports Tools", isPro: true },
  { id: 84, name: "Sports Competition Manager", slug: "sports-competition-manager", category: "Sports Tools", isPro: true },
  { id: 85, name: "Fantasy Sports Statistics Workspace", slug: "fantasy-sports-statistics-workspace", category: "Sports Tools", isPro: true },
  { id: 86, name: "Sports Scouting Workspace", slug: "sports-scouting-workspace", category: "Sports Tools", isPro: true },
  { id: 87, name: "Team Comparison Engine", slug: "team-comparison-engine", category: "Sports Tools", isPro: true },
  { id: 88, name: "Opponent Analysis Workspace", slug: "opponent-analysis-workspace", category: "Sports Tools", isPro: true },
  { id: 89, name: "Sports Strategy Dashboard", slug: "sports-strategy-dashboard", category: "Sports Tools", isPro: true },
  { id: 90, name: "Athlete Progress Tracker", slug: "athlete-progress-tracker", category: "Sports Tools", isPro: true },
  { id: 91, name: "Sports Data API Workspace", slug: "sports-data-api-workspace", category: "Sports Tools", isPro: true },
  { id: 92, name: "Sports Analytics API", slug: "sports-analytics-api", category: "Sports Tools", isPro: true },
  { id: 93, name: "Sports Intelligence Dashboard", slug: "sports-intelligence-dashboard", category: "Sports Tools", isPro: true },
  { id: 94, name: "Professional Team Management Platform", slug: "professional-team-management-platform", category: "Sports Tools", isPro: true },
  { id: 95, name: "Sports Performance Intelligence Platform", slug: "sports-performance-intelligence-platform", category: "Sports Tools", isPro: true },
  { id: 96, name: "Sports Operations Command Center", slug: "sports-operations-command-center", category: "Sports Tools", isPro: true },
  { id: 97, name: "Athlete Recovery Workspace", slug: "athlete-recovery-workspace", category: "Sports Tools", isPro: true },
  { id: 98, name: "Esports Tournament Dashboard", slug: "esports-tournament-dashboard", category: "Sports Tools", isPro: true },
  { id: 99, name: "Sports Simulation Engine", slug: "sports-simulation-engine", category: "Sports Tools", isPro: true },
  { id: 100, name: "Advanced Coach Analytics Dashboard", slug: "advanced-coach-analytics-dashboard", category: "Sports Tools", isPro: true }
];