export interface StudentTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const studentToolsList: StudentTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "GPA Calculator", slug: "gpa-calculator", category: "Student Tools", isPro: false },
  { id: 2, name: "CGPA Calculator", slug: "cgpa-calculator", category: "Student Tools", isPro: false },
  { id: 3, name: "Grade Calculator", slug: "grade-calculator", category: "Student Tools", isPro: false },
  { id: 4, name: "Final Grade Calculator", slug: "final-grade-calculator", category: "Student Tools", isPro: false },
  { id: 5, name: "Weighted Grade Calculator", slug: "weighted-grade-calculator", category: "Student Tools", isPro: false },
  { id: 6, name: "Required Exam Score Calculator", slug: "required-exam-score-calculator", category: "Student Tools", isPro: false },
  { id: 7, name: "Study Time Calculator", slug: "study-time-calculator", category: "Student Tools", isPro: false },
  { id: 8, name: "Exam Countdown", slug: "exam-countdown", category: "Student Tools", isPro: false },
  { id: 9, name: "Assignment Deadline Calculator", slug: "assignment-deadline-calculator", category: "Student Tools", isPro: false },
  { id: 10, name: "Study Schedule Generator", slug: "study-schedule-generator", category: "Student Tools", isPro: false },
  { id: 11, name: "Exam Study Planner", slug: "exam-study-planner", category: "Student Tools", isPro: false },
  { id: 12, name: "Homework Planner", slug: "homework-planner", category: "Student Tools", isPro: false },
  { id: 13, name: "Timetable Generator", slug: "timetable-generator", category: "Student Tools", isPro: false },
  { id: 14, name: "Pomodoro Study Timer", slug: "pomodoro-study-timer", category: "Student Tools", isPro: false },
  { id: 15, name: "Assignment Tracker", slug: "assignment-tracker", category: "Student Tools", isPro: false },
  { id: 16, name: "Citation Generator", slug: "citation-generator", category: "Student Tools", isPro: false },
  { id: 17, name: "APA Citation Generator", slug: "apa-citation-generator", category: "Student Tools", isPro: false },
  { id: 18, name: "Flashcard Generator", slug: "flashcard-generator", category: "Student Tools", isPro: false },
  { id: 19, name: "Student Budget Calculator", slug: "student-budget-calculator", category: "Student Tools", isPro: false },
  { id: 20, name: "Student Productivity Dashboard", slug: "student-productivity-dashboard", category: "Student Tools", isPro: true },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Percentage Calculator", slug: "percentage-calculator", category: "Student Tools", isPro: false },
  { id: 22, name: "Marks Percentage Calculator", slug: "marks-percentage-calculator", category: "Student Tools", isPro: false },
  { id: 23, name: "Exam Score Calculator", slug: "exam-score-calculator", category: "Student Tools", isPro: false },
  { id: 24, name: "Semester Grade Calculator", slug: "semester-grade-calculator", category: "Student Tools", isPro: false },
  { id: 25, name: "Course Grade Calculator", slug: "course-grade-calculator", category: "Student Tools", isPro: false },
  { id: 26, name: "Credit GPA Calculator", slug: "credit-gpa-calculator", category: "Student Tools", isPro: false },
  { id: 27, name: "Grade Point Converter", slug: "grade-point-converter", category: "Student Tools", isPro: false },
  { id: 28, name: "Letter Grade Converter", slug: "letter-grade-converter", category: "Student Tools", isPro: false },
  { id: 29, name: "Study Hours Calculator", slug: "study-hours-calculator", category: "Student Tools", isPro: false },
  { id: 30, name: "Assignment Planner", slug: "assignment-planner", category: "Student Tools", isPro: false },
  { id: 31, name: "Revision Planner", slug: "revision-planner", category: "Student Tools", isPro: false },
  { id: 32, name: "Daily Study Planner", slug: "daily-study-planner", category: "Student Tools", isPro: false },
  { id: 33, name: "Weekly Study Planner", slug: "weekly-study-planner", category: "Student Tools", isPro: false },
  { id: 34, name: "Monthly Study Planner", slug: "monthly-study-planner", category: "Student Tools", isPro: false },
  { id: 35, name: "Semester Planner", slug: "semester-planner", category: "Student Tools", isPro: false },
  { id: 36, name: "Academic Calendar", slug: "academic-calendar", category: "Student Tools", isPro: false },
  { id: 37, name: "Class Schedule Generator", slug: "class-schedule-generator", category: "Student Tools", isPro: false },
  { id: 38, name: "Focus Timer", slug: "focus-timer", category: "Student Tools", isPro: false },
  { id: 39, name: "Break Timer", slug: "break-timer", category: "Student Tools", isPro: false },
  { id: 40, name: "Study Session Tracker", slug: "study-session-tracker", category: "Student Tools", isPro: false },
  { id: 41, name: "Study Streak Tracker", slug: "study-streak-tracker", category: "Student Tools", isPro: false },
  { id: 42, name: "Study Progress Tracker", slug: "study-progress-tracker", category: "Student Tools", isPro: false },
  { id: 43, name: "Subject Progress Tracker", slug: "subject-progress-tracker", category: "Student Tools", isPro: false },
  { id: 44, name: "Exam Tracker", slug: "exam-tracker", category: "Student Tools", isPro: false },
  { id: 45, name: "Course Tracker", slug: "course-tracker", category: "Student Tools", isPro: false },
  { id: 46, name: "Reading Time Calculator", slug: "reading-time-calculator", category: "Student Tools", isPro: false },
  { id: 47, name: "Essay Word Count", slug: "essay-word-count", category: "Student Tools", isPro: false },
  { id: 48, name: "Essay Page Count", slug: "essay-page-count", category: "Student Tools", isPro: false },
  { id: 49, name: "Bibliography Generator", slug: "bibliography-generator", category: "Student Tools", isPro: false },
  { id: 50, name: "Reference Formatter", slug: "reference-formatter", category: "Student Tools", isPro: false },
  { id: 51, name: "MLA Citation Generator", slug: "mla-citation-generator", category: "Student Tools", isPro: false },
  { id: 52, name: "Chicago Citation Generator", slug: "chicago-citation-generator", category: "Student Tools", isPro: false },
  { id: 53, name: "Harvard Citation Generator", slug: "harvard-citation-generator", category: "Student Tools", isPro: false },
  { id: 54, name: "Research Question Generator", slug: "research-question-generator", category: "Student Tools", isPro: false },
  { id: 55, name: "Thesis Statement Helper", slug: "thesis-statement-helper", category: "Student Tools", isPro: false },
  { id: 56, name: "Study Notes Organizer", slug: "study-notes-organizer", category: "Student Tools", isPro: false },
  { id: 57, name: "Quiz Generator", slug: "quiz-generator", category: "Student Tools", isPro: false },
  { id: 58, name: "Study Checklist", slug: "study-checklist", category: "Student Tools", isPro: false },
  { id: 59, name: "Assignment Checklist", slug: "assignment-checklist", category: "Student Tools", isPro: false },
  { id: 60, name: "Exam Checklist", slug: "exam-checklist", category: "Student Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Academic Performance Dashboard", slug: "academic-performance-dashboard", category: "Student Tools", isPro: true },
  { id: 62, name: "Semester Planning Workspace", slug: "semester-planning-workspace", category: "Student Tools", isPro: true },
  { id: 63, name: "Multi-Course Management Workspace", slug: "multi-course-management-workspace", category: "Student Tools", isPro: true },
  { id: 64, name: "Exam Preparation Workspace", slug: "exam-preparation-workspace", category: "Student Tools", isPro: true },
  { id: 65, name: "Assignment Management Workspace", slug: "assignment-management-workspace", category: "Student Tools", isPro: true },
  { id: 66, name: "Study Schedule Optimization", slug: "study-schedule-optimization", category: "Student Tools", isPro: true },
  { id: 67, name: "Study Time Analytics", slug: "study-time-analytics", category: "Student Tools", isPro: true },
  { id: 68, name: "Learning Progress Dashboard", slug: "learning-progress-dashboard", category: "Student Tools", isPro: true },
  { id: 69, name: "Subject Performance Analyzer", slug: "subject-performance-analyzer", category: "Student Tools", isPro: true },
  { id: 70, name: "Grade Prediction Workspace", slug: "grade-prediction-workspace", category: "Student Tools", isPro: true },
  { id: 71, name: "Academic Goal Planner", slug: "academic-goal-planner", category: "Student Tools", isPro: true },
  { id: 72, name: "Course Planning Workspace", slug: "course-planning-workspace", category: "Student Tools", isPro: true },
  { id: 73, name: "Degree Planning Workspace", slug: "degree-planning-workspace", category: "Student Tools", isPro: true },
  { id: 74, name: "Credit Requirement Tracker", slug: "credit-requirement-tracker", category: "Student Tools", isPro: true },
  { id: 75, name: "Graduation Progress Tracker", slug: "graduation-progress-tracker", category: "Student Tools", isPro: true },
  { id: 76, name: "Research Project Workspace", slug: "research-project-workspace", category: "Student Tools", isPro: true },
  { id: 77, name: "Literature Review Workspace", slug: "literature-review-workspace", category: "Student Tools", isPro: true },
  { id: 78, name: "Citation Management Workspace", slug: "citation-management-workspace", category: "Student Tools", isPro: true },
  { id: 79, name: "Academic Reference Workspace", slug: "academic-reference-workspace", category: "Student Tools", isPro: true },
  { id: 80, name: "Research Data Organizer", slug: "research-data-organizer", category: "Student Tools", isPro: true },
  { id: 81, name: "Thesis Planning Workspace", slug: "thesis-planning-workspace", category: "Student Tools", isPro: true },
  { id: 82, name: "Dissertation Planning Workspace", slug: "dissertation-planning-workspace", category: "Student Tools", isPro: true },
  { id: 83, name: "Academic Writing Workspace", slug: "academic-writing-workspace", category: "Student Tools", isPro: true },
  { id: 84, name: "Student Budget Dashboard", slug: "student-budget-dashboard", category: "Student Tools", isPro: true },
  { id: 85, name: "Scholarship Management Workspace", slug: "scholarship-management-workspace", category: "Student Tools", isPro: true },
  { id: 86, name: "Scholarship Deadline Tracker", slug: "scholarship-deadline-tracker", category: "Student Tools", isPro: true },
  { id: 87, name: "College Application Planner", slug: "college-application-planner", category: "Student Tools", isPro: true },
  { id: 88, name: "University Application Tracker", slug: "university-application-tracker", category: "Student Tools", isPro: true },
  { id: 89, name: "Internship Application Tracker", slug: "internship-application-tracker", category: "Student Tools", isPro: true },
  { id: 90, name: "Student Document Organizer", slug: "student-document-organizer", category: "Student Tools", isPro: true },
  { id: 91, name: "Academic Calendar Dashboard", slug: "academic-calendar-dashboard", category: "Student Tools", isPro: true },
  { id: 92, name: "Student Task Management Workspace", slug: "student-task-management-workspace", category: "Student Tools", isPro: true },
  { id: 93, name: "Study Group Workspace", slug: "study-group-workspace", category: "Student Tools", isPro: true },
  { id: 94, name: "Collaborative Notes Workspace", slug: "collaborative-notes-workspace", category: "Student Tools", isPro: true },
  { id: 95, name: "Academic Data Import Workspace", slug: "academic-data-import-workspace", category: "Student Tools", isPro: true },
  { id: 96, name: "Student Progress Report Generator", slug: "student-progress-report-generator", category: "Student Tools", isPro: true },
  { id: 97, name: "Student Productivity Analytics", slug: "student-productivity-analytics", category: "Student Tools", isPro: true },
  { id: 98, name: "Education API Workspace", slug: "education-api-workspace", category: "Student Tools", isPro: true },
  { id: 99, name: "Academic Intelligence Platform", slug: "academic-intelligence-platform", category: "Student Tools", isPro: true },
  { id: 100, name: "Student Command Center", slug: "student-command-center", category: "Student Tools", isPro: true }
];