export interface TaxAccountingTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const taxAccountingToolsList: TaxAccountingTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "Income Tax Calculator", slug: "income-tax-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 2, name: "Take-Home Pay Calculator", slug: "take-home-pay-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 3, name: "Salary Tax Calculator", slug: "salary-tax-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 4, name: "Self-Employment Tax Calculator", slug: "self-employment-tax-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 5, name: "Capital Gains Tax Calculator", slug: "capital-gains-tax-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 6, name: "Sales Tax Calculator", slug: "sales-tax-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 7, name: "VAT Calculator", slug: "vat-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 8, name: "GST Calculator", slug: "gst-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 9, name: "Tax Deduction Calculator", slug: "tax-deduction-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 10, name: "Taxable Income Calculator", slug: "taxable-income-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 11, name: "Tax Withholding Calculator", slug: "tax-withholding-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 12, name: "Estimated Tax Payment Calculator", slug: "estimated-tax-payment-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 13, name: "Tax Refund Estimator", slug: "tax-refund-estimator", category: "Tax & Accounting Tools", isPro: false },
  { id: 14, name: "Profit & Loss Calculator", slug: "profit-and-loss-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 15, name: "Gross Margin Calculator", slug: "gross-margin-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 16, name: "Break-Even Calculator", slug: "break-even-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 17, name: "Cash Flow Calculator", slug: "cash-flow-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 18, name: "Depreciation Calculator", slug: "depreciation-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 19, name: "Tax Bracket Calculator", slug: "tax-bracket-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 20, name: "Effective Tax Rate Calculator", slug: "effective-tax-rate-calculator", category: "Tax & Accounting Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Marginal Tax Rate Calculator", slug: "marginal-tax-rate-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 22, name: "Payroll Tax Calculator", slug: "payroll-tax-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 23, name: "Freelancer Tax Calculator", slug: "freelancer-tax-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 24, name: "Business Tax Calculator", slug: "business-tax-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 25, name: "Corporate Tax Calculator", slug: "corporate-tax-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 26, name: "Dividend Tax Calculator", slug: "dividend-tax-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 27, name: "Interest Income Tax Calculator", slug: "interest-income-tax-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 28, name: "Rental Income Tax Calculator", slug: "rental-income-tax-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 29, name: "Property Tax Calculator", slug: "property-tax-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 30, name: "Tax-Inclusive Price Calculator", slug: "tax-inclusive-price-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 31, name: "Tax-Exclusive Price Calculator", slug: "tax-exclusive-price-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 32, name: "Tax Reverse Calculator", slug: "tax-reverse-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 33, name: "Tax Percentage Calculator", slug: "tax-percentage-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 34, name: "Tax Credit Calculator", slug: "tax-credit-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 35, name: "Standard Deduction Calculator", slug: "standard-deduction-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 36, name: "Adjusted Gross Income Calculator", slug: "adjusted-gross-income-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 37, name: "Net Income Calculator", slug: "net-income-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 38, name: "Gross-to-Net Calculator", slug: "gross-to-net-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 39, name: "Net-to-Gross Calculator", slug: "net-to-gross-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 40, name: "Payroll Deduction Calculator", slug: "payroll-deduction-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 41, name: "Overtime Pay Calculator", slug: "overtime-pay-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 42, name: "Bonus Tax Calculator", slug: "bonus-tax-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 43, name: "Commission Tax Calculator", slug: "commission-tax-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 44, name: "Severance Tax Calculator", slug: "severance-tax-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 45, name: "Retirement Withdrawal Tax Calculator", slug: "retirement-withdrawal-tax-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 46, name: "Retirement Contribution Calculator", slug: "retirement-contribution-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 47, name: "Pension Tax Calculator", slug: "pension-tax-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 48, name: "Quarterly Tax Calculator", slug: "quarterly-tax-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 49, name: "Tax Underpayment Calculator", slug: "tax-underpayment-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 50, name: "Late Tax Payment Calculator", slug: "late-tax-payment-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 51, name: "Invoice Tax Calculator", slug: "invoice-tax-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 52, name: "Business Expense Calculator", slug: "business-expense-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 53, name: "Gross Profit Calculator", slug: "gross-profit-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 54, name: "Net Profit Calculator", slug: "net-profit-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 55, name: "Net Margin Calculator", slug: "net-margin-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 56, name: "Accounts Receivable Calculator", slug: "accounts-receivable-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 57, name: "Accounts Payable Calculator", slug: "accounts-payable-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 58, name: "Straight-Line Depreciation Calculator", slug: "straight-line-depreciation-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 59, name: "Declining Balance Depreciation Calculator", slug: "declining-balance-depreciation-calculator", category: "Tax & Accounting Tools", isPro: false },
  { id: 60, name: "Accounting Ratio Calculator", slug: "accounting-ratio-calculator", category: "Tax & Accounting Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Tax Planning Workspace", slug: "tax-planning-workspace", category: "Tax & Accounting Tools", isPro: true },
  { id: 62, name: "Financial Statement Analyzer", slug: "financial-statement-analyzer", category: "Tax & Accounting Tools", isPro: true },
  { id: 63, name: "Multi-Income Tax Analyzer", slug: "multi-income-tax-analyzer", category: "Tax & Accounting Tools", isPro: true },
  { id: 64, name: "Tax Liability Forecast", slug: "tax-liability-forecast", category: "Tax & Accounting Tools", isPro: true },
  { id: 65, name: "Tax Optimization Planner", slug: "tax-optimization-planner", category: "Tax & Accounting Tools", isPro: true },
  { id: 66, name: "Tax Scenario Comparison Engine", slug: "tax-scenario-comparison-engine", category: "Tax & Accounting Tools", isPro: true },
  { id: 67, name: "Tax Deduction Optimization Tool", slug: "tax-deduction-optimization-tool", category: "Tax & Accounting Tools", isPro: true },
  { id: 68, name: "Tax Credit Optimization Tool", slug: "tax-credit-optimization-tool", category: "Tax & Accounting Tools", isPro: true },
  { id: 69, name: "Capital Gains Tax Planner", slug: "capital-gains-tax-planner", category: "Tax & Accounting Tools", isPro: true },
  { id: 70, name: "Self-Employment Tax Planner", slug: "self-employment-tax-planner", category: "Tax & Accounting Tools", isPro: true },
  { id: 71, name: "Freelancer Tax Workspace", slug: "freelancer-tax-workspace", category: "Tax & Accounting Tools", isPro: true },
  { id: 72, name: "Small Business Tax Workspace", slug: "small-business-tax-workspace", category: "Tax & Accounting Tools", isPro: true },
  { id: 73, name: "Corporate Tax Planning Workspace", slug: "corporate-tax-planning-workspace", category: "Tax & Accounting Tools", isPro: true },
  { id: 74, name: "Multi-State Tax Analyzer", slug: "multi-state-tax-analyzer", category: "Tax & Accounting Tools", isPro: true },
  { id: 75, name: "International Tax Comparison Tool", slug: "international-tax-comparison-tool", category: "Tax & Accounting Tools", isPro: true },
  { id: 76, name: "VAT/GST Compliance Workspace", slug: "vat-gst-compliance-workspace", category: "Tax & Accounting Tools", isPro: true },
  { id: 77, name: "Sales Tax Nexus Analyzer", slug: "sales-tax-nexus-analyzer", category: "Tax & Accounting Tools", isPro: true },
  { id: 78, name: "Payroll Compliance Analyzer", slug: "payroll-compliance-analyzer", category: "Tax & Accounting Tools", isPro: true },
  { id: 79, name: "Payroll Cost Forecast", slug: "payroll-cost-forecast", category: "Tax & Accounting Tools", isPro: true },
  { id: 80, name: "Employee Cost Calculator", slug: "employee-cost-calculator", category: "Tax & Accounting Tools", isPro: true },
  { id: 81, name: "Contractor vs Employee Cost Analyzer", slug: "contractor-vs-employee-cost-analyzer", category: "Tax & Accounting Tools", isPro: true },
  { id: 82, name: "Profitability Analyzer", slug: "profitability-analyzer", category: "Tax & Accounting Tools", isPro: true },
  { id: 83, name: "Cash Flow Forecasting Engine", slug: "cash-flow-forecasting-engine", category: "Tax & Accounting Tools", isPro: true },
  { id: 84, name: "Accounts Receivable Aging Analyzer", slug: "accounts-receivable-aging-analyzer", category: "Tax & Accounting Tools", isPro: true },
  { id: 85, name: "Accounts Payable Aging Analyzer", slug: "accounts-payable-aging-analyzer", category: "Tax & Accounting Tools", isPro: true },
  { id: 86, name: "Working Capital Analyzer", slug: "working-capital-analyzer", category: "Tax & Accounting Tools", isPro: true },
  { id: 87, name: "Balance Sheet Analyzer", slug: "balance-sheet-analyzer", category: "Tax & Accounting Tools", isPro: true },
  { id: 88, name: "Income Statement Analyzer", slug: "income-statement-analyzer", category: "Tax & Accounting Tools", isPro: true },
  { id: 89, name: "Cash Flow Statement Analyzer", slug: "cash-flow-statement-analyzer", category: "Tax & Accounting Tools", isPro: true },
  { id: 90, name: "Financial Ratio Dashboard", slug: "financial-ratio-dashboard", category: "Tax & Accounting Tools", isPro: true },
  { id: 91, name: "Budget vs Actual Analyzer", slug: "budget-vs-actual-analyzer", category: "Tax & Accounting Tools", isPro: true },
  { id: 92, name: "Expense Intelligence Dashboard", slug: "expense-intelligence-dashboard", category: "Tax & Accounting Tools", isPro: true },
  { id: 93, name: "Revenue Forecasting Engine", slug: "revenue-forecasting-engine", category: "Tax & Accounting Tools", isPro: true },
  { id: 94, name: "Business Financial Dashboard", slug: "business-financial-dashboard", category: "Tax & Accounting Tools", isPro: true },
  { id: 95, name: "Tax Document Organizer", slug: "tax-document-organizer", category: "Tax & Accounting Tools", isPro: true },
  { id: 96, name: "Accounting Close Checklist", slug: "accounting-close-checklist", category: "Tax & Accounting Tools", isPro: true },
  { id: 97, name: "Accountant Workspace", slug: "accountant-workspace", category: "Tax & Accounting Tools", isPro: true },
  { id: 98, name: "Small Business Accounting Workspace", slug: "small-business-accounting-workspace", category: "Tax & Accounting Tools", isPro: true },
  { id: 99, name: "Tax Intelligence Platform", slug: "tax-intelligence-platform", category: "Tax & Accounting Tools", isPro: true },
  { id: 100, name: "Financial Operations Command Center", slug: "financial-operations-command-center", category: "Tax & Accounting Tools", isPro: true }
];