export interface UnitConversionTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const unitConversionToolsList: UnitConversionTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "Length Converter", slug: "length-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 2, name: "Area Converter", slug: "area-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 3, name: "Volume Converter", slug: "volume-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 4, name: "Weight Converter", slug: "weight-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 5, name: "Temperature Converter", slug: "temperature-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 6, name: "Speed Converter", slug: "speed-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 7, name: "Time Converter", slug: "time-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 8, name: "Pressure Converter", slug: "pressure-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 9, name: "Energy Converter", slug: "energy-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 10, name: "Power Converter", slug: "power-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 11, name: "Force Converter", slug: "force-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 12, name: "Torque Converter", slug: "torque-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 13, name: "Density Converter", slug: "density-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 14, name: "Data Storage Converter", slug: "data-storage-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 15, name: "Fuel Economy Converter", slug: "fuel-economy-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 16, name: "Flow Rate Converter", slug: "flow-rate-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 17, name: "Voltage Converter", slug: "voltage-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 18, name: "Celsius Fahrenheit Converter", slug: "celsius-fahrenheit-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 19, name: "Miles Kilometers Converter", slug: "miles-kilometers-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 20, name: "Pounds Kilograms Converter", slug: "pounds-kilograms-converter", category: "Unit Conversion Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Distance Converter", slug: "distance-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 22, name: "Mass Converter", slug: "mass-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 23, name: "Frequency Converter", slug: "frequency-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 24, name: "Acceleration Converter", slug: "acceleration-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 25, name: "Digital Data Rate Converter", slug: "digital-data-rate-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 26, name: "Angle Converter", slug: "angle-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 27, name: "Plane Angle Converter", slug: "plane-angle-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 28, name: "Solid Angle Converter", slug: "solid-angle-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 29, name: "Volumetric Flow Converter", slug: "volumetric-flow-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 30, name: "Mass Flow Converter", slug: "mass-flow-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 31, name: "Molarity Converter", slug: "molarity-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 32, name: "Concentration Converter", slug: "concentration-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 33, name: "Viscosity Converter", slug: "viscosity-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 34, name: "Kinematic Viscosity Converter", slug: "kinematic-viscosity-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 35, name: "Dynamic Viscosity Converter", slug: "dynamic-viscosity-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 36, name: "Electric Current Converter", slug: "electric-current-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 37, name: "Resistance Converter", slug: "resistance-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 38, name: "Conductance Converter", slug: "conductance-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 39, name: "Capacitance Converter", slug: "capacitance-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 40, name: "Inductance Converter", slug: "inductance-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 41, name: "Magnetic Field Converter", slug: "magnetic-field-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 42, name: "Magnetic Flux Converter", slug: "magnetic-flux-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 43, name: "Illuminance Converter", slug: "illuminance-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 44, name: "Luminance Converter", slug: "luminance-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 45, name: "Radiation Converter", slug: "radiation-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 46, name: "Sound Level Converter", slug: "sound-level-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 47, name: "Decibel Converter", slug: "decibel-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 48, name: "Frequency Wavelength Converter", slug: "frequency-wavelength-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 49, name: "Celsius Kelvin Converter", slug: "celsius-kelvin-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 50, name: "Fahrenheit Kelvin Converter", slug: "fahrenheit-kelvin-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 51, name: "Feet Meters Converter", slug: "feet-meters-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 52, name: "Inches Centimeters Converter", slug: "inches-centimeters-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 53, name: "Ounces Grams Converter", slug: "ounces-grams-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 54, name: "Gallons Liters Converter", slug: "gallons-liters-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 55, name: "Acres Hectares Converter", slug: "acres-hectares-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 56, name: "Square Feet Square Meters Converter", slug: "square-feet-square-meters-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 57, name: "Cubic Feet Cubic Meters Converter", slug: "cubic-feet-cubic-meters-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 58, name: "PSI Bar Converter", slug: "psi-bar-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 59, name: "Bar Pascal Converter", slug: "bar-pascal-converter", category: "Unit Conversion Tools", isPro: false },
  { id: 60, name: "kWh Joule Converter", slug: "kwh-joule-converter", category: "Unit Conversion Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Engineering Unit Conversion Workspace", slug: "engineering-unit-conversion-workspace", category: "Unit Conversion Tools", isPro: true },
  { id: 62, name: "Scientific Unit Conversion Workspace", slug: "scientific-unit-conversion-workspace", category: "Unit Conversion Tools", isPro: true },
  { id: 63, name: "Construction Unit Conversion Workspace", slug: "construction-unit-conversion-workspace", category: "Unit Conversion Tools", isPro: true },
  { id: 64, name: "Manufacturing Unit Converter", slug: "manufacturing-unit-converter", category: "Unit Conversion Tools", isPro: true },
  { id: 65, name: "HVAC Unit Conversion Workspace", slug: "hvac-unit-conversion-workspace", category: "Unit Conversion Tools", isPro: true },
  { id: 66, name: "Electrical Unit Conversion Workspace", slug: "electrical-unit-conversion-workspace", category: "Unit Conversion Tools", isPro: true },
  { id: 67, name: "Mechanical Unit Conversion Workspace", slug: "mechanical-unit-conversion-workspace", category: "Unit Conversion Tools", isPro: true },
  { id: 68, name: "Fluid Engineering Converter", slug: "fluid-engineering-converter", category: "Unit Conversion Tools", isPro: true },
  { id: 69, name: "Chemical Concentration Converter", slug: "chemical-concentration-converter", category: "Unit Conversion Tools", isPro: true },
  { id: 70, name: "Laboratory Unit Converter", slug: "laboratory-unit-converter", category: "Unit Conversion Tools", isPro: true },
  { id: 71, name: "Pharmaceutical Unit Converter", slug: "pharmaceutical-unit-converter", category: "Unit Conversion Tools", isPro: true },
  { id: 72, name: "Energy Engineering Converter", slug: "energy-engineering-converter", category: "Unit Conversion Tools", isPro: true },
  { id: 73, name: "Industrial Measurement Converter", slug: "industrial-measurement-converter", category: "Unit Conversion Tools", isPro: true },
  { id: 74, name: "Batch Unit Conversion Tool", slug: "batch-unit-conversion-tool", category: "Unit Conversion Tools", isPro: true },
  { id: 75, name: "Multi-Unit Conversion Engine", slug: "multi-unit-conversion-engine", category: "Unit Conversion Tools", isPro: true },
  { id: 76, name: "Custom Unit Builder", slug: "custom-unit-builder", category: "Unit Conversion Tools", isPro: true },
  { id: 77, name: "Custom Unit Formula Builder", slug: "custom-unit-formula-builder", category: "Unit Conversion Tools", isPro: true },
  { id: 78, name: "Unit Conversion API Generator", slug: "unit-conversion-api-generator", category: "Unit Conversion Tools", isPro: true },
  { id: 79, name: "Conversion History Workspace", slug: "conversion-history-workspace", category: "Unit Conversion Tools", isPro: true },
  { id: 80, name: "Saved Conversion Workspace", slug: "saved-conversion-workspace", category: "Unit Conversion Tools", isPro: true },
  { id: 81, name: "Bulk Unit Converter", slug: "bulk-unit-converter", category: "Unit Conversion Tools", isPro: true },
  { id: 82, name: "CSV Unit Conversion Tool", slug: "csv-unit-conversion-tool", category: "Unit Conversion Tools", isPro: true },
  { id: 83, name: "Excel Unit Conversion Tool", slug: "excel-unit-conversion-tool", category: "Unit Conversion Tools", isPro: true },
  { id: 84, name: "Measurement Standard Comparison", slug: "measurement-standard-comparison", category: "Unit Conversion Tools", isPro: true },
  { id: 85, name: "SI vs Imperial Converter", slug: "si-vs-imperial-converter", category: "Unit Conversion Tools", isPro: true },
  { id: 86, name: "Metric vs US Customary Converter", slug: "metric-vs-us-customary-converter", category: "Unit Conversion Tools", isPro: true },
  { id: 87, name: "Precision Conversion Calculator", slug: "precision-conversion-calculator", category: "Unit Conversion Tools", isPro: true },
  { id: 88, name: "Significant Digit Conversion Tool", slug: "significant-digit-conversion-tool", category: "Unit Conversion Tools", isPro: true },
  { id: 89, name: "Engineering Tolerance Converter", slug: "engineering-tolerance-converter", category: "Unit Conversion Tools", isPro: true },
  { id: 90, name: "Dimensional Analysis Workspace", slug: "dimensional-analysis-workspace", category: "Unit Conversion Tools", isPro: true },
  { id: 91, name: "Unit Consistency Checker", slug: "unit-consistency-checker", category: "Unit Conversion Tools", isPro: true },
  { id: 92, name: "Formula Unit Validator", slug: "formula-unit-validator", category: "Unit Conversion Tools", isPro: true },
  { id: 93, name: "Scientific Measurement Workspace", slug: "scientific-measurement-workspace", category: "Unit Conversion Tools", isPro: true },
  { id: 94, name: "Professional Conversion Dashboard", slug: "professional-conversion-dashboard", category: "Unit Conversion Tools", isPro: true },
  { id: 95, name: "Industrial Measurement Dashboard", slug: "industrial-measurement-dashboard", category: "Unit Conversion Tools", isPro: true },
  { id: 96, name: "Engineering Conversion Dashboard", slug: "engineering-conversion-dashboard", category: "Unit Conversion Tools", isPro: true },
  { id: 97, name: "Laboratory Conversion Dashboard", slug: "laboratory-conversion-dashboard", category: "Unit Conversion Tools", isPro: true },
  { id: 98, name: "Conversion Report Generator", slug: "conversion-report-generator", category: "Unit Conversion Tools", isPro: true },
  { id: 99, name: "Unit Conversion Intelligence Platform", slug: "unit-conversion-intelligence-platform", category: "Unit Conversion Tools", isPro: true },
  { id: 100, name: "Universal Professional Unit Engine", slug: "universal-professional-unit-engine", category: "Unit Conversion Tools", isPro: true }
];