export interface VideoTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const videoToolsList: VideoTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-17) ---
  { id: 1, name: "Video Compressor", slug: "video-compressor", category: "Video Tools", isPro: false },
  { id: 2, name: "Video Resizer", slug: "video-resizer", category: "Video Tools", isPro: false },
  { id: 3, name: "Video Trimmer", slug: "video-trimmer", category: "Video Tools", isPro: false },
  { id: 4, name: "Video Cutter", slug: "video-cutter", category: "Video Tools", isPro: false },
  { id: 5, name: "Video Merger", slug: "video-merger", category: "Video Tools", isPro: false },
  { id: 6, name: "Video Format Converter", slug: "video-format-converter", category: "Video Tools", isPro: false },
  { id: 7, name: "Video to GIF Converter", slug: "video-to-gif-converter", category: "Video Tools", isPro: false },
  { id: 8, name: "Video Resolution Converter", slug: "video-resolution-converter", category: "Video Tools", isPro: false },
  { id: 9, name: "Video Aspect Ratio Converter", slug: "video-aspect-ratio-converter", category: "Video Tools", isPro: false },
  { id: 10, name: "Subtitle Converter", slug: "subtitle-converter", category: "Video Tools", isPro: false },
  { id: 11, name: "Subtitle Synchronizer", slug: "subtitle-synchronizer", category: "Video Tools", isPro: false },
  { id: 12, name: "Auto Subtitle Generator", slug: "auto-subtitle-generator", category: "Video Tools", isPro: false },
  { id: 13, name: "Video Transcript Generator", slug: "video-transcript-generator", category: "Video Tools", isPro: false },
  { id: 14, name: "Video Chapter Generator", slug: "video-chapter-generator", category: "Video Tools", isPro: false },
  { id: 15, name: "Video SEO Analyzer", slug: "video-seo-analyzer-tool", category: "Video Tools", isPro: false },
  { id: 16, name: "Video Watch Time Calculator", slug: "video-watch-time-calculator", category: "Video Tools", isPro: false },
  { id: 17, name: "Video Revenue Estimator", slug: "video-revenue-estimator", category: "Video Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (18-60) ---
  { id: 18, name: "Video Cropper", slug: "video-cropper", category: "Video Tools", isPro: false },
  { id: 19, name: "Video Splitter", slug: "video-splitter", category: "Video Tools", isPro: false },
  { id: 20, name: "Video Rotator", slug: "video-rotator", category: "Video Tools", isPro: false },
  { id: 21, name: "Video Flipper", slug: "video-flipper", category: "Video Tools", isPro: false },
  { id: 22, name: "Video Speed Changer", slug: "video-speed-changer", category: "Video Tools", isPro: false },
  { id: 23, name: "Video Reverse Tool", slug: "video-reverse-tool", category: "Video Tools", isPro: false },
  { id: 24, name: "Video Loop Maker", slug: "video-loop-maker", category: "Video Tools", isPro: false },
  { id: 25, name: "Video Stabilizer", slug: "video-stabilizer", category: "Video Tools", isPro: false },
  { id: 26, name: "Video Frame Extractor", slug: "video-frame-extractor", category: "Video Tools", isPro: false },
  { id: 27, name: "Video Thumbnail Extractor", slug: "video-thumbnail-extractor", category: "Video Tools", isPro: false },
  { id: 28, name: "GIF to Video Converter", slug: "gif-to-video-converter", category: "Video Tools", isPro: false },
  { id: 29, name: "Video to MP4 Converter", slug: "video-to-mp4-converter", category: "Video Tools", isPro: false },
  { id: 30, name: "Video to WebM Converter", slug: "video-to-webm-converter", category: "Video Tools", isPro: false },
  { id: 31, name: "Video to MOV Converter", slug: "video-to-mov-converter", category: "Video Tools", isPro: false },
  { id: 32, name: "MOV to MP4 Converter", slug: "mov-to-mp4-converter", category: "Video Tools", isPro: false },
  { id: 33, name: "MKV to MP4 Converter", slug: "mkv-to-mp4-converter", category: "Video Tools", isPro: false },
  { id: 34, name: "AVI to MP4 Converter", slug: "avi-to-mp4-converter", category: "Video Tools", isPro: false },
  { id: 35, name: "WebM to MP4 Converter", slug: "webm-to-mp4-converter", category: "Video Tools", isPro: false },
  { id: 36, name: "Video Frame Rate Converter", slug: "video-frame-rate-converter", category: "Video Tools", isPro: false },
  { id: 37, name: "Video Bitrate Calculator", slug: "video-bitrate-calculator", category: "Video Tools", isPro: false },
  { id: 38, name: "Video File Size Calculator", slug: "video-file-size-calculator", category: "Video Tools", isPro: false },
  { id: 39, name: "Video Upload Time Calculator", slug: "video-upload-time-calculator", category: "Video Tools", isPro: false },
  { id: 40, name: "Video Download Time Calculator", slug: "video-download-time-calculator", category: "Video Tools", isPro: false },
  { id: 41, name: "Subtitle Extractor", slug: "subtitle-extractor", category: "Video Tools", isPro: false },
  { id: 42, name: "Subtitle Formatter", slug: "subtitle-formatter", category: "Video Tools", isPro: false },
  { id: 43, name: "Subtitle Merger", slug: "subtitle-merger", category: "Video Tools", isPro: false },
  { id: 44, name: "Subtitle Splitter", slug: "subtitle-splitter", category: "Video Tools", isPro: false },
  { id: 45, name: "SRT Generator", slug: "srt-generator", category: "Video Tools", isPro: false },
  { id: 46, name: "VTT Generator", slug: "vtt-generator", category: "Video Tools", isPro: false },
  { id: 47, name: "SRT to VTT Converter", slug: "srt-to-vtt-converter", category: "Video Tools", isPro: false },
  { id: 48, name: "VTT to SRT Converter", slug: "vtt-to-srt-converter", category: "Video Tools", isPro: false },
  { id: 49, name: "Video Caption Generator", slug: "video-caption-generator", category: "Video Tools", isPro: false },
  { id: 50, name: "Transcript Formatter", slug: "transcript-formatter", category: "Video Tools", isPro: false },
  { id: 51, name: "Video Description Generator", slug: "video-description-generator", category: "Video Tools", isPro: false },
  { id: 52, name: "Video Title Generator", slug: "video-title-generator", category: "Video Tools", isPro: false },
  { id: 53, name: "Video Tags Generator", slug: "video-tags-generator", category: "Video Tools", isPro: false },
  { id: 54, name: "Video Hashtag Generator", slug: "video-hashtag-generator", category: "Video Tools", isPro: false },
  { id: 55, name: "Video Metadata Generator", slug: "video-metadata-generator", category: "Video Tools", isPro: false },
  { id: 56, name: "Video Engagement Calculator", slug: "video-engagement-calculator", category: "Video Tools", isPro: false },
  { id: 57, name: "Video Retention Calculator", slug: "video-retention-calculator", category: "Video Tools", isPro: false },
  { id: 58, name: "Video CTR Calculator", slug: "video-ctr-calculator", category: "Video Tools", isPro: false },
  { id: 59, name: "Video RPM Calculator", slug: "video-rpm-calculator", category: "Video Tools", isPro: false },
  { id: 60, name: "Video CPM Calculator", slug: "video-cpm-calculator", category: "Video Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "AI Video Editor", slug: "ai-video-editor", category: "Video Tools", isPro: true },
  { id: 62, name: "AI Video Clipper", slug: "ai-video-clipper", category: "Video Tools", isPro: true },
  { id: 63, name: "AI Highlight Generator", slug: "ai-highlight-generator", category: "Video Tools", isPro: true },
  { id: 64, name: "AI Content Repurposing Engine", slug: "ai-content-repurposing-engine", category: "Video Tools", isPro: true },
  { id: 65, name: "AI Scene Detector", slug: "ai-scene-detector", category: "Video Tools", isPro: true },
  { id: 66, name: "AI Silence Remover", slug: "ai-silence-remover", category: "Video Tools", isPro: true },
  { id: 67, name: "AI Filler Word Remover", slug: "ai-filler-word-remover", category: "Video Tools", isPro: true },
  { id: 68, name: "AI Jump Cut Generator", slug: "ai-jump-cut-generator", category: "Video Tools", isPro: true },
  { id: 69, name: "AI Caption Styler", slug: "ai-caption-styler", category: "Video Tools", isPro: true },
  { id: 70, name: "AI Subtitle Translator", slug: "ai-subtitle-translator", category: "Video Tools", isPro: true },
  { id: 71, name: "AI Voiceover Generator", slug: "ai-voiceover-generator-video", category: "Video Tools", isPro: true },
  { id: 72, name: "AI Dubbing Workflow", slug: "ai-dubbing-workflow", category: "Video Tools", isPro: true },
  { id: 73, name: "AI Lip Sync Tool", slug: "ai-lip-sync-tool", category: "Video Tools", isPro: true },
  { id: 74, name: "AI Background Remover", slug: "ai-background-remover", category: "Video Tools", isPro: true },
  { id: 75, name: "AI Video Upscaler", slug: "ai-video-upscaler", category: "Video Tools", isPro: true },
  { id: 76, name: "AI Video Enhancer", slug: "ai-video-enhancer", category: "Video Tools", isPro: true },
  { id: 77, name: "AI Noise Reduction", slug: "ai-noise-reduction-video", category: "Video Tools", isPro: true },
  { id: 78, name: "AI Audio Cleanup", slug: "ai-audio-cleanup-video", category: "Video Tools", isPro: true },
  { id: 79, name: "AI Color Correction", slug: "ai-color-correction", category: "Video Tools", isPro: true },
  { id: 80, name: "AI Video Color Grader", slug: "ai-video-color-grader", category: "Video Tools", isPro: true },
  { id: 81, name: "AI B-Roll Finder", slug: "ai-b-roll-finder", category: "Video Tools", isPro: true },
  { id: 82, name: "AI Stock Footage Matcher", slug: "ai-stock-footage-matcher", category: "Video Tools", isPro: true },
  { id: 83, name: "AI Script-to-Video Planner", slug: "ai-script-to-video-planner", category: "Video Tools", isPro: true },
  { id: 84, name: "AI Storyboard Generator", slug: "ai-storyboard-generator", category: "Video Tools", isPro: true },
  { id: 85, name: "AI Shot List Generator", slug: "ai-shot-list-generator", category: "Video Tools", isPro: true },
  { id: 86, name: "AI Video Hook Generator", slug: "ai-video-hook-generator", category: "Video Tools", isPro: true },
  { id: 87, name: "AI Retention Analyzer", slug: "ai-retention-analyzer", category: "Video Tools", isPro: true },
  { id: 88, name: "AI Thumbnail Brief Generator", slug: "ai-thumbnail-brief-generator", category: "Video Tools", isPro: true },
  { id: 89, name: "AI Video SEO Optimizer", slug: "ai-video-seo-optimizer", category: "Video Tools", isPro: true },
  { id: 90, name: "Long-to-Short Video Converter", slug: "long-to-short-video-converter", category: "Video Tools", isPro: true },
  { id: 91, name: "Podcast-to-Shorts Generator", slug: "podcast-to-shorts-generator", category: "Video Tools", isPro: true },
  { id: 92, name: "Webinar-to-Shorts Generator", slug: "webinar-to-shorts-generator", category: "Video Tools", isPro: true },
  { id: 93, name: "Video-to-Social Clips Engine", slug: "video-to-social-clips-engine", category: "Video Tools", isPro: true },
  { id: 94, name: "Multi-Platform Video Resizer", slug: "multi-platform-video-resizer", category: "Video Tools", isPro: true },
  { id: 95, name: "Automated Video Publishing Workflow", slug: "automated-video-publishing-workflow", category: "Video Tools", isPro: true },
  { id: 96, name: "Video Content Calendar", slug: "video-content-calendar", category: "Video Tools", isPro: true },
  { id: 97, name: "Video Production Planner", slug: "video-production-planner", category: "Video Tools", isPro: true },
  { id: 98, name: "Video Analytics Dashboard", slug: "video-analytics-dashboard", category: "Video Tools", isPro: true },
  { id: 99, name: "Creator Video Intelligence Workspace", slug: "creator-video-intelligence-workspace", category: "Video Tools", isPro: true },
  { id: 100, name: "AI Video Production Workspace", slug: "ai-video-production-workspace", category: "Video Tools", isPro: true },
];