export interface WeatherTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const weatherToolsList: WeatherTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "Current Weather Lookup", slug: "current-weather-lookup", category: "Weather Tools", isPro: false },
  { id: 2, name: "Hourly Weather Forecast", slug: "hourly-weather-forecast", category: "Weather Tools", isPro: false },
  { id: 3, name: "7-Day Weather Forecast", slug: "7-day-weather-forecast", category: "Weather Tools", isPro: false },
  { id: 4, name: "14-Day Weather Forecast", slug: "14-day-weather-forecast", category: "Weather Tools", isPro: false },
  { id: 5, name: "Heat Index Calculator", slug: "heat-index-calculator", category: "Weather Tools", isPro: false },
  { id: 6, name: "Wind Chill Calculator", slug: "wind-chill-calculator", category: "Weather Tools", isPro: false },
  { id: 7, name: "UV Index Checker", slug: "uv-index-checker", category: "Weather Tools", isPro: false },
  { id: 8, name: "Sunrise/Sunset Calculator", slug: "sunrise-sunset-calculator", category: "Weather Tools", isPro: false },
  { id: 9, name: "Rain Probability Checker", slug: "rain-probability-checker", category: "Weather Tools", isPro: false },
  { id: 10, name: "Weather Alert Checker", slug: "weather-alert-checker", category: "Weather Tools", isPro: false },
  { id: 11, name: "Air Quality Checker", slug: "air-quality-checker", category: "Weather Tools", isPro: false },
  { id: 12, name: "AQI Calculator", slug: "aqi-calculator", category: "Weather Tools", isPro: false },
  { id: 13, name: "Pollen Level Checker", slug: "pollen-level-checker", category: "Weather Tools", isPro: false },
  { id: 14, name: "Travel Weather Checker", slug: "travel-weather-checker", category: "Weather Tools", isPro: false },
  { id: 15, name: "Hiking Weather Checker", slug: "hiking-weather-checker", category: "Weather Tools", isPro: false },
  { id: 16, name: "Farming Weather Checker", slug: "farming-weather-checker", category: "Weather Tools", isPro: false },
  { id: 17, name: "Construction Weather Checker", slug: "construction-weather-checker", category: "Weather Tools", isPro: false },
  { id: 18, name: "Weather History Lookup", slug: "weather-history-lookup", category: "Weather Tools", isPro: false },
  { id: 19, name: "City Weather Comparison", slug: "city-weather-comparison", category: "Weather Tools", isPro: false },
  { id: 20, name: "Daily Weather Forecast", slug: "daily-weather-forecast", category: "Weather Tools", isPro: false },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "10-Day Weather Forecast", slug: "10-day-weather-forecast", category: "Weather Tools", isPro: false },
  { id: 22, name: "Temperature Converter", slug: "temperature-converter", category: "Weather Tools", isPro: false },
  { id: 23, name: "Wind Speed Converter", slug: "wind-speed-converter", category: "Weather Tools", isPro: false },
  { id: 24, name: "Pressure Converter", slug: "pressure-converter", category: "Weather Tools", isPro: false },
  { id: 25, name: "Humidity Calculator", slug: "humidity-calculator", category: "Weather Tools", isPro: false },
  { id: 26, name: "Dew Point Calculator", slug: "dew-point-calculator", category: "Weather Tools", isPro: false },
  { id: 27, name: "Feels-Like Temperature Calculator", slug: "feels-like-temperature-calculator", category: "Weather Tools", isPro: false },
  { id: 28, name: "Apparent Temperature Calculator", slug: "apparent-temperature-calculator", category: "Weather Tools", isPro: false },
  { id: 29, name: "Daylight Duration Calculator", slug: "daylight-duration-calculator", category: "Weather Tools", isPro: false },
  { id: 30, name: "Moonrise Calculator", slug: "moonrise-calculator", category: "Weather Tools", isPro: false },
  { id: 31, name: "Moonset Calculator", slug: "moonset-calculator", category: "Weather Tools", isPro: false },
  { id: 32, name: "Weather Time Converter", slug: "weather-time-converter", category: "Weather Tools", isPro: false },
  { id: 33, name: "Rainfall Calculator", slug: "rainfall-calculator", category: "Weather Tools", isPro: false },
  { id: 34, name: "Snowfall Calculator", slug: "snowfall-calculator", category: "Weather Tools", isPro: false },
  { id: 35, name: "Snow Depth Converter", slug: "snow-depth-converter", category: "Weather Tools", isPro: false },
  { id: 36, name: "Visibility Checker", slug: "visibility-checker", category: "Weather Tools", isPro: false },
  { id: 37, name: "Wind Direction Converter", slug: "wind-direction-converter", category: "Weather Tools", isPro: false },
  { id: 38, name: "Barometric Pressure Converter", slug: "barometric-pressure-converter", category: "Weather Tools", isPro: false },
  { id: 39, name: "Storm Alert Checker", slug: "storm-alert-checker", category: "Weather Tools", isPro: false },
  { id: 40, name: "Flood Risk Checker", slug: "flood-risk-checker", category: "Weather Tools", isPro: false },
  { id: 41, name: "Lightning Risk Checker", slug: "lightning-risk-checker", category: "Weather Tools", isPro: false },
  { id: 42, name: "AQI Converter", slug: "aqi-converter", category: "Weather Tools", isPro: false },
  { id: 43, name: "Allergy Weather Checker", slug: "allergy-weather-checker", category: "Weather Tools", isPro: false },
  { id: 44, name: "Fire Weather Checker", slug: "fire-weather-checker", category: "Weather Tools", isPro: false },
  { id: 45, name: "Beach Weather Checker", slug: "beach-weather-checker", category: "Weather Tools", isPro: false },
  { id: 46, name: "Camping Weather Checker", slug: "camping-weather-checker", category: "Weather Tools", isPro: false },
  { id: 47, name: "Golf Weather Checker", slug: "golf-weather-checker", category: "Weather Tools", isPro: false },
  { id: 48, name: "Running Weather Checker", slug: "running-weather-checker", category: "Weather Tools", isPro: false },
  { id: 49, name: "Cycling Weather Checker", slug: "cycling-weather-checker", category: "Weather Tools", isPro: false },
  { id: 50, name: "Fishing Weather Checker", slug: "fishing-weather-checker", category: "Weather Tools", isPro: false },
  { id: 51, name: "Gardening Weather Checker", slug: "gardening-weather-checker", category: "Weather Tools", isPro: false },
  { id: 52, name: "Outdoor Event Weather Checker", slug: "outdoor-event-weather-checker", category: "Weather Tools", isPro: false },
  { id: 53, name: "Historical Temperature Lookup", slug: "historical-temperature-lookup", category: "Weather Tools", isPro: false },
  { id: 54, name: "Historical Rainfall Lookup", slug: "historical-rainfall-lookup", category: "Weather Tools", isPro: false },
  { id: 55, name: "Climate Comparison Tool", slug: "climate-comparison-tool", category: "Weather Tools", isPro: false },
  { id: 56, name: "Weather Unit Converter", slug: "weather-unit-converter", category: "Weather Tools", isPro: false },
  { id: 57, name: "Weather Forecast Exporter", slug: "weather-forecast-exporter", category: "Weather Tools", isPro: false },
  { id: 58, name: "Weather Report Generator", slug: "weather-report-generator", category: "Weather Tools", isPro: false },
  { id: 59, name: "Sunrise Calculator", slug: "sunrise-calculator", category: "Weather Tools", isPro: false },
  { id: 60, name: "Sunset Calculator", slug: "sunset-calculator", category: "Weather Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Severe Weather Intelligence Dashboard", slug: "severe-weather-intelligence-dashboard", category: "Weather Tools", isPro: true },
  { id: 62, name: "Multi-City Weather Dashboard", slug: "multi-city-weather-dashboard", category: "Weather Tools", isPro: true },
  { id: 63, name: "Weather Monitoring Workspace", slug: "weather-monitoring-workspace", category: "Weather Tools", isPro: true },
  { id: 64, name: "Weather Alert Monitoring System", slug: "weather-alert-monitoring-system", category: "Weather Tools", isPro: true },
  { id: 65, name: "Storm Tracking Dashboard", slug: "storm-tracking-dashboard", category: "Weather Tools", isPro: true },
  { id: 66, name: "Hurricane Tracking Workspace", slug: "hurricane-tracking-workspace", category: "Weather Tools", isPro: true },
  { id: 67, name: "Flood Monitoring Dashboard", slug: "flood-monitoring-dashboard", category: "Weather Tools", isPro: true },
  { id: 68, name: "Lightning Monitoring Dashboard", slug: "lightning-monitoring-dashboard", category: "Weather Tools", isPro: true },
  { id: 69, name: "Air Quality Intelligence Dashboard", slug: "air-quality-intelligence-dashboard", category: "Weather Tools", isPro: true },
  { id: 70, name: "Pollen Intelligence Dashboard", slug: "pollen-intelligence-dashboard", category: "Weather Tools", isPro: true },
  { id: 71, name: "Agricultural Weather Planner", slug: "agricultural-weather-planner", category: "Weather Tools", isPro: true },
  { id: 72, name: "Construction Weather Planner", slug: "construction-weather-planner", category: "Weather Tools", isPro: true },
  { id: 73, name: "Outdoor Event Weather Planner", slug: "outdoor-event-weather-planner", category: "Weather Tools", isPro: true },
  { id: 74, name: "Travel Weather Intelligence", slug: "travel-weather-intelligence", category: "Weather Tools", isPro: true },
  { id: 75, name: "Aviation Weather Planning Workspace", slug: "aviation-weather-planning-workspace", category: "Weather Tools", isPro: true },
  { id: 76, name: "Marine Weather Planning Workspace", slug: "marine-weather-planning-workspace", category: "Weather Tools", isPro: true },
  { id: 77, name: "Solar Production Weather Planner", slug: "solar-production-weather-planner", category: "Weather Tools", isPro: true },
  { id: 78, name: "Weather-Based Energy Forecast", slug: "weather-based-energy-forecast", category: "Weather Tools", isPro: true },
  { id: 79, name: "Weather Risk Analyzer", slug: "weather-risk-analyzer", category: "Weather Tools", isPro: true },
  { id: 80, name: "Weather Impact Analyzer", slug: "weather-impact-analyzer", category: "Weather Tools", isPro: true },
  { id: 81, name: "Weather-Based Business Planner", slug: "weather-based-business-planner", category: "Weather Tools", isPro: true },
  { id: 82, name: "Historical Climate Analyzer", slug: "historical-climate-analyzer", category: "Weather Tools", isPro: true },
  { id: 83, name: "Climate Trend Analyzer", slug: "climate-trend-analyzer", category: "Weather Tools", isPro: true },
  { id: 84, name: "Weather Anomaly Analyzer", slug: "weather-anomaly-analyzer", category: "Weather Tools", isPro: true },
  { id: 85, name: "Temperature Trend Analyzer", slug: "temperature-trend-analyzer", category: "Weather Tools", isPro: true },
  { id: 86, name: "Rainfall Trend Analyzer", slug: "rainfall-trend-analyzer", category: "Weather Tools", isPro: true },
  { id: 87, name: "Weather Data Export Workspace", slug: "weather-data-export-workspace", category: "Weather Tools", isPro: true },
  { id: 88, name: "Weather API Testing Workspace", slug: "weather-api-testing-workspace", category: "Weather Tools", isPro: true },
  { id: 89, name: "Weather API Dashboard", slug: "weather-api-dashboard", category: "Weather Tools", isPro: true },
  { id: 90, name: "Global Weather Monitoring Workspace", slug: "global-weather-monitoring-workspace", category: "Weather Tools", isPro: true },
  { id: 91, name: "Location Weather Intelligence", slug: "location-weather-intelligence", category: "Weather Tools", isPro: true },
  { id: 92, name: "Weather Comparison Dashboard", slug: "weather-comparison-dashboard", category: "Weather Tools", isPro: true },
  { id: 93, name: "Weather Risk Management Workspace", slug: "weather-risk-management-workspace", category: "Weather Tools", isPro: true },
  { id: 94, name: "Climate Intelligence Workspace", slug: "climate-intelligence-workspace", category: "Weather Tools", isPro: true },
  { id: 95, name: "Weather Forecast Analytics", slug: "weather-forecast-analytics", category: "Weather Tools", isPro: true },
  { id: 96, name: "Weather Data Visualization Workspace", slug: "weather-data-visualization-workspace", category: "Weather Tools", isPro: true },
  { id: 97, name: "Enterprise Weather Operations Dashboard", slug: "enterprise-weather-operations-dashboard", category: "Weather Tools", isPro: true },
  { id: 98, name: "Weather Intelligence Platform", slug: "weather-intelligence-platform", category: "Weather Tools", isPro: true },
  { id: 99, name: "Global Climate Intelligence Workspace", slug: "global-climate-intelligence-workspace", category: "Weather Tools", isPro: true },
  { id: 100, name: "Weather Decision Support Workspace", slug: "weather-decision-support-workspace", category: "Weather Tools", isPro: true }
];