export interface WorkoutFitnessTool {
  id: number;
  name: string;
  slug: string;
  category: string;
  isPro: boolean;
}

export const workoutFitnessToolsList: WorkoutFitnessTool[] = [
  // --- TOP PRIORITY (FREE CORE & TIER A TOOLS: 1-20) ---
  { id: 1, name: "Workout Calorie Calculator", slug: "workout-calorie-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 2, name: "One Rep Max Calculator", slug: "one-rep-max-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 3, name: "Weightlifting Plate Calculator", slug: "weightlifting-plate-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 4, name: "Training Volume Calculator", slug: "training-volume-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 5, name: "Pace Calculator", slug: "pace-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 6, name: "Running Pace Calculator", slug: "running-pace-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 7, name: "Race Time Predictor", slug: "race-time-predictor", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 8, name: "Marathon Pace Calculator", slug: "marathon-pace-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 9, name: "Cycling Speed Calculator", slug: "cycling-speed-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 10, name: "VO2 Max Estimator", slug: "vo2-max-estimator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 11, name: "Body Fat Calculator", slug: "body-fat-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 12, name: "Workout Split Planner", slug: "workout-split-planner", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 13, name: "HIIT Timer", slug: "hiit-timer", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 14, name: "Workout Generator", slug: "workout-generator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 15, name: "Weekly Workout Planner", slug: "weekly-workout-planner", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 16, name: "Training Schedule Generator", slug: "training-schedule-generator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 17, name: "Workout Log", slug: "workout-log", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 18, name: "Personal Record Tracker", slug: "personal-record-tracker", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 19, name: "Fitness Goal Tracker", slug: "fitness-goal-tracker", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 20, name: "Personalized Workout Planner", slug: "personalized-workout-planner", category: "Workout & Fitness Planning Tools", isPro: true },

  // --- REMAINING CORE FREE TOOLS (21-60) ---
  { id: 21, name: "Exercise Calorie Calculator", slug: "exercise-calorie-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 22, name: "Workout Duration Calculator", slug: "workout-duration-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 23, name: "One Rep Max Percentage Calculator", slug: "one-rep-max-percentage-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 24, name: "Weightlifting Percentage Calculator", slug: "weightlifting-percentage-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 25, name: "BMI Calculator", slug: "bmi-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 26, name: "BMR Calculator", slug: "bmr-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 27, name: "TDEE Calculator", slug: "tdee-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 28, name: "Heart Rate Zone Calculator", slug: "heart-rate-zone-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 29, name: "Target Heart Rate Calculator", slug: "target-heart-rate-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 30, name: "Running Speed Calculator", slug: "running-speed-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 31, name: "Running Time Calculator", slug: "running-time-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 32, name: "Split Time Calculator", slug: "split-time-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 33, name: "Mile Pace Calculator", slug: "mile-pace-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 34, name: "5K Pace Calculator", slug: "5k-pace-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 35, name: "10K Pace Calculator", slug: "10k-pace-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 36, name: "Half Marathon Pace Calculator", slug: "half-marathon-pace-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 37, name: "Cycling Distance Calculator", slug: "cycling-distance-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 38, name: "Cycling Time Calculator", slug: "cycling-time-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 39, name: "Swimming Pace Calculator", slug: "swimming-pace-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 40, name: "Swimming Calorie Calculator", slug: "swimming-calorie-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 41, name: "Walking Pace Calculator", slug: "walking-pace-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 42, name: "Walking Calorie Calculator", slug: "walking-calorie-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 43, name: "Hiking Pace Calculator", slug: "hiking-pace-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 44, name: "Hiking Time Calculator", slug: "hiking-time-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 45, name: "Elevation Gain Calculator", slug: "elevation-gain-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 46, name: "Lean Body Mass Calculator", slug: "lean-body-mass-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 47, name: "Ideal Weight Calculator", slug: "ideal-weight-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 48, name: "Strength Ratio Calculator", slug: "strength-ratio-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 49, name: "Training Frequency Calculator", slug: "training-frequency-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 50, name: "Rest Day Calculator", slug: "rest-day-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 51, name: "Recovery Time Planner", slug: "recovery-time-planner", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 52, name: "Exercise Repetition Calculator", slug: "exercise-repetition-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 53, name: "Set Calculator", slug: "set-calculator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 54, name: "Workout Timer", slug: "workout-timer", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 55, name: "Interval Timer", slug: "interval-timer", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 56, name: "Tabata Timer", slug: "tabata-timer", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 57, name: "Circuit Timer", slug: "circuit-timer", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 58, name: "Exercise Routine Generator", slug: "exercise-routine-generator", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 59, name: "Monthly Workout Planner", slug: "monthly-workout-planner", category: "Workout & Fitness Planning Tools", isPro: false },
  { id: 60, name: "Exercise Log", slug: "exercise-log", category: "Workout & Fitness Planning Tools", isPro: false },

  // --- PRO / SAAS PRIORITY TOOLS (61-100) ---
  { id: 61, name: "Workout Progress Tracker", slug: "workout-progress-tracker", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 62, name: "Advanced Training Program Builder", slug: "advanced-training-program-builder", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 63, name: "Strength Program Generator", slug: "strength-program-generator", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 64, name: "Hypertrophy Program Builder", slug: "hypertrophy-program-builder", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 65, name: "Endurance Program Builder", slug: "endurance-program-builder", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 66, name: "Running Training Planner", slug: "running-training-planner", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 67, name: "Cycling Training Planner", slug: "cycling-training-planner", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 68, name: "Swimming Training Planner", slug: "swimming-training-planner", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 69, name: "Marathon Training Planner", slug: "marathon-training-planner", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 70, name: "Race Training Workspace", slug: "race-training-workspace", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 71, name: "Progressive Overload Planner", slug: "progressive-overload-planner", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 72, name: "Training Volume Analyzer", slug: "training-volume-analyzer", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 73, name: "Workout Intensity Analyzer", slug: "workout-intensity-analyzer", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 74, name: "Training Load Analyzer", slug: "training-load-analyzer", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 75, name: "Recovery Planning Workspace", slug: "recovery-planning-workspace", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 76, name: "Workout Balance Analyzer", slug: "workout-balance-analyzer", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 77, name: "Exercise Muscle Group Analyzer", slug: "exercise-muscle-group-analyzer", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 78, name: "Training Frequency Optimizer", slug: "training-frequency-optimizer", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 79, name: "Strength Progress Dashboard", slug: "strength-progress-dashboard", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 80, name: "Fitness Progress Dashboard", slug: "fitness-progress-dashboard", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 81, name: "Personal Record Dashboard", slug: "personal-record-dashboard", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 82, name: "Exercise History Workspace", slug: "exercise-history-workspace", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 83, name: "Workout Calendar Workspace", slug: "workout-calendar-workspace", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 84, name: "Training Calendar Generator", slug: "training-calendar-generator", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 85, name: "Athlete Performance Dashboard", slug: "athlete-performance-dashboard", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 86, name: "Endurance Performance Analyzer", slug: "endurance-performance-analyzer", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 87, name: "Running Performance Dashboard", slug: "running-performance-dashboard", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 88, name: "Cycling Performance Dashboard", slug: "cycling-performance-dashboard", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 89, name: "Workout Analytics Engine", slug: "workout-analytics-engine", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 90, name: "Training Data Import Workspace", slug: "training-data-import-workspace", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 91, name: "Fitness Data Export Tool", slug: "fitness-data-export-tool", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 92, name: "Fitness Report Generator", slug: "fitness-report-generator", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 93, name: "Workout Plan PDF Generator", slug: "workout-plan-pdf-generator", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 94, name: "Trainer Client Workspace", slug: "trainer-client-workspace", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 95, name: "Fitness Coaching Dashboard", slug: "fitness-coaching-dashboard", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 96, name: "Gym Management Workout Workspace", slug: "gym-management-workout-workspace", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 97, name: "Personal Training Business Workspace", slug: "personal-training-business-workspace", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 98, name: "Fitness API Workspace", slug: "fitness-api-workspace", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 99, name: "Fitness Intelligence Platform", slug: "fitness-intelligence-platform", category: "Workout & Fitness Planning Tools", isPro: true },
  { id: 100, name: "Professional Training Command Center", slug: "professional-training-command-center", category: "Workout & Fitness Planning Tools", isPro: true }
];